SMACC2: smacc::client_bases::SmaccPublisherClient Class Reference
smacc::client_bases::SmaccPublisherClient Class Reference
#include <smacc_publisher_client.hpp>
Public Member Functions
SmaccPublisherClient ()
virtual ~SmaccPublisherClient ()
template<typename MessageType >
void configure (std::string topicName)
template<typename MessageType >
void publish (const MessageType &msg)
Public Member Functions inherited from smacc::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void onInitialize ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent >> &components)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Public Attributes
std::optional< std::string > topicName
std::optional< int > queueSize
rclcpp::PublisherBase::SharedPtr pub_
Private Attributes
bool initialized_
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Detailed Description
Definition at line 30 of file smacc_publisher_client.hpp.
Constructor & Destructor Documentation
SmaccPublisherClient()
smacc::client_bases::SmaccPublisherClient::SmaccPublisherClient ()
Definition at line 27 of file smacc_publisher_client.cpp.
 { initialized_ = false; }
References initialized_.
~SmaccPublisherClient()
smacc::client_bases::SmaccPublisherClient::~SmaccPublisherClient () virtual
Definition at line 29 of file smacc_publisher_client.cpp.
 {}
Member Function Documentation
configure()
template<typename MessageType > void smacc::client_bases::SmaccPublisherClient::configure (std::string topicName) inline
Definition at line 40 of file smacc_publisher_client.hpp.
   {
     this->topicName = topicName;
     if (!initialized_)
     {
       if (!this->topicName)
       {
         RCLCPP_ERROR(
           getNode()->get_logger(), "topic publisher with no topic name set. Skipping advertising.");
         return;
       }
       if (!queueSize) queueSize = 1;
       rclcpp::SensorDataQoS qos;
       qos.keep_last(*queueSize);
       RCLCPP_INFO_STREAM(
         getNode()->get_logger(),
         "[" << this->getName() << "] Client Publisher to topic: " << topicName);
       pub_ = getNode()->create_publisher<MessageType>(*(this->topicName), qos);
       this->initialized_ = true;
     }
   }
References smacc::ISmaccClient::getName(), smacc::ISmaccClient::getNode(), initialized_, pub_, queueSize, and topicName.
publish()
template<typename MessageType > void smacc::client_bases::SmaccPublisherClient::publish (const MessageType & msg) inline
Definition at line 66 of file smacc_publisher_client.hpp.
   {
     //pub_->publish(msg);
     std::dynamic_pointer_cast<rclcpp::Publisher<MessageType>>(pub_)->publish(msg);
   }
References pub_.
Referenced by sm_dance_bot::cl_string_publisher::CbStringPublisher::onExit(), and sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher::onExit().
Member Data Documentation
initialized_
bool smacc::client_bases::SmaccPublisherClient::initialized_ private
Definition at line 75 of file smacc_publisher_client.hpp.
Referenced by configure(), and SmaccPublisherClient().
pub_
rclcpp::PublisherBase::SharedPtr smacc::client_bases::SmaccPublisherClient::pub_
Definition at line 72 of file smacc_publisher_client.hpp.
Referenced by configure(), and publish().
queueSize
std::optional<int> smacc::client_bases::SmaccPublisherClient::queueSize
Definition at line 34 of file smacc_publisher_client.hpp.
Referenced by configure().
topicName
std::optional<std::string> smacc::client_bases::SmaccPublisherClient::topicName
Definition at line 33 of file smacc_publisher_client.hpp.
Referenced by configure(), and cl_ros_publisher::ClRosPublisher::configure().
The documentation for this class was generated from the following files:
smacc2/include/smacc/client_bases/smacc_publisher_client.hpp
smacc2/src/smacc/client_bases/smacc_publisher_client.cpp