SMACC2: smacc::SmaccClientBehavior Class Reference
smacc::SmaccClientBehavior Class Reference
#include <smacc_client_behavior.hpp>
Public Member Functions
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Detailed Description
Definition at line 26 of file smacc_client_behavior.hpp.
Member Function Documentation
onEntry()
void smacc::SmaccClientBehavior::onEntry () override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Reimplemented in sm_dance_bot_strikes_back::cl_service3::CbService3, sm_dance_bot_strikes_back::cl_lidar::CbLidarSensor, sm_dance_bot_strikes_back::cl_led::CbLEDOn, sm_dance_bot_strikes_back::cl_led::CbLEDOff, sm_dance_bot::cl_service3::CbService3, sm_dance_bot::cl_lidar::CbLidarSensor, sm_dance_bot::cl_led::CbLEDOn, sm_dance_bot::cl_led::CbLEDOff, cl_ros_timer::CbTimerCountdownOnce, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimer, cl_ros_timer::CbTimerCountdownOnce, cl_ros_timer::CbTimerCountdownOnce, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimer, cl_ros_timer::CbTimer, cl_ros_publisher::CbPublishOnce< RosMsgType >, cl_ros_publisher::CbMutedBehavior< RosMsgType >, cl_ros_publisher::CbDefaultPublishLoop, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >, sm_three_some::cl_subscriber::CbWatchdogSubscriberBehavior, sm_three_some::cl_subscriber::CbDefaultSubscriberBehavior, sm_respira_1::cl_subscriber::CbWatchdogSubscriberBehavior, sm_respira_1::cl_subscriber::CbDefaultSubscriberBehavior, sm_ferrari::cl_subscriber::CbMySubscriberBehavior, sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, sm_dance_bot::cl_string_publisher::CbStringPublisher, and cl_keyboard::CbDefaultKeyboardBehavior.
Definition at line 19 of file smacc_client_behavior.cpp.
 {
   RCLCPP_DEBUG(
     getLogger(), "[%s] Default empty SmaccClientBehavior onEntry", this->getName().c_str());
 }
References smacc::ISmaccClientBehavior::getLogger(), and smacc::ISmaccClientBehavior::getName().
onExit()
void smacc::SmaccClientBehavior::onExit () override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Reimplemented in sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, sm_dance_bot_strikes_back::cl_led::CbLEDOn, sm_dance_bot_strikes_back::cl_led::CbLEDOff, sm_dance_bot::cl_string_publisher::CbStringPublisher, sm_dance_bot::cl_led::CbLEDOn, sm_dance_bot::cl_led::CbLEDOff, cl_ros_timer::CbTimerCountdownOnce, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimer, cl_ros_publisher::CbPublishOnce< RosMsgType >, cl_ros_publisher::CbMutedBehavior< RosMsgType >, cl_ros_publisher::CbDefaultPublishLoop, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClLidarSensor >, and cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >.
Definition at line 25 of file smacc_client_behavior.cpp.
 {
   RCLCPP_DEBUG(
     getLogger(), "[%s] Default empty SmaccClientBehavior onExit", this->getName().c_str());
 }
References smacc::ISmaccClientBehavior::getLogger(), and smacc::ISmaccClientBehavior::getName().
The documentation for this class was generated from the following files:
smacc2/include/smacc/smacc_client_behavior.hpp
smacc2/src/smacc/smacc_client_behavior.cpp