SMACC2: smacc::ISmaccComponent Class Reference
smacc::ISmaccComponent Class Reference
#include <component.hpp>
Public Member Functions
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Protected Member Functions
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Private Member Functions
void initialize (ISmaccClient *owner)
void setStateMachine (ISmaccStateMachine *stateMachine)
Friends
class ISmaccOrthogonal
class ISmaccClient
Detailed Description
Definition at line 29 of file component.hpp.
Constructor & Destructor Documentation
ISmaccComponent()
smacc::ISmaccComponent::ISmaccComponent ()
Definition at line 26 of file smacc_component.cpp.
 : owner_(nullptr) {}
~ISmaccComponent()
smacc::ISmaccComponent::~ISmaccComponent () virtual
Definition at line 24 of file smacc_component.cpp.
 {}
Member Function Documentation
createSiblingComponent()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs> SmaccComponentType * smacc::ISmaccComponent::createSiblingComponent (TArgs... targs) protected
Definition at line 49 of file smacc_component_impl.hpp.
 {
   return this->owner_->createComponent<SmaccComponentType, TOrthogonal, TClient>(targs...);
 }
References smacc::ISmaccClient::createComponent(), and owner_.
createSiblingNamedComponent()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs> SmaccComponentType * smacc::ISmaccComponent::createSiblingNamedComponent (std::string name, TArgs... targs) protected
Definition at line 55 of file smacc_component_impl.hpp.
 {
   return this->owner_->createNamedComponent<SmaccComponentType, TOrthogonal, TClient>(
     name, targs...);
 }
References smacc::ISmaccClient::createNamedComponent(), and owner_.
getLogger()
rclcpp::Logger smacc::ISmaccComponent::getLogger () protected
Definition at line 43 of file smacc_component.cpp.
 { return getLogger(); }
Referenced by cl_move_base_z::CostmapSwitch::disable(), cl_move_base_z::CostmapSwitch::enable(), cl_move_base_z::WaypointNavigator::loadWayPointsFromFile(), cl_move_base_z::odom_tracker::OdomTracker::logStateString(), cl_move_base_z::CostmapSwitch::onInitialize(), cl_move_base_z::odom_tracker::OdomTracker::onInitialize(), cl_move_base_z::Pose::onInitialize(), cl_move_base_z::odom_tracker::OdomTracker::popPath(), cl_move_base_z::odom_tracker::OdomTracker::pushPath(), cl_move_base_z::CostmapSwitch::registerProxyFromDynamicReconfigureServer(), cl_move_base_z::WaypointNavigator::sendNextGoal(), cl_move_base_z::GoalCheckerSwitcher::setGoalCheckerId(), cl_move_base_z::odom_tracker::OdomTracker::setStartPoint(), cl_move_base_z::odom_tracker::OdomTracker::setWorkingMode(), cl_move_base_z::Pose::update(), cl_move_base_z::odom_tracker::OdomTracker::updateClearPath(), and cl_move_base_z::Pose::waitTransformUpdate().
getName()
std::string smacc::ISmaccComponent::getName () const virtual
Definition at line 45 of file smacc_component.cpp.
 {
   std::string keyname = demangleSymbol(typeid(*this).name());
   return keyname;
 }
References smacc::introspection::demangleSymbol().
getNode()
rclcpp::Node::SharedPtr smacc::ISmaccComponent::getNode () protected
Definition at line 41 of file smacc_component.cpp.
 { return this->owner_->getNode(); }
References smacc::ISmaccClient::getNode(), and owner_.
Referenced by cl_move_base_z::odom_tracker::OdomTracker::clearPath(), cl_move_base_z::GoalCheckerSwitcher::onInitialize(), cl_move_base_z::odom_tracker::OdomTracker::onInitialize(), cl_move_base_z::Pose::onInitialize(), cl_move_base_z::CostmapSwitch::registerProxyFromDynamicReconfigureServer(), cl_move_base_z::WaypointNavigator::sendNextGoal(), cl_move_base_z::odom_tracker::OdomTracker::setStartPoint(), cl_move_base_z::Pose::update(), cl_move_base_z::odom_tracker::OdomTracker::updateConfiguration(), and cl_move_base_z::Pose::waitTransformUpdate().
initialize()
void smacc::ISmaccComponent::initialize (ISmaccClient * owner) private
Definition at line 28 of file smacc_component.cpp.
 {
   owner_ = owner;
   this->onInitialize();
 }
References onInitialize(), and owner_.
onInitialize()
void smacc::ISmaccComponent::onInitialize () protected virtual
Reimplemented in sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData, cl_move_base_z::WaypointNavigator, cl_move_base_z::Pose, cl_move_base_z::PlannerSwitcher, cl_move_base_z::odom_tracker::OdomTracker, cl_move_base_z::GoalCheckerSwitcher, and cl_move_base_z::CostmapSwitch.
Definition at line 34 of file smacc_component.cpp.
 {}
Referenced by initialize().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc::ISmaccComponent::onOrthogonalAllocation () inline protected
Definition at line 51 of file component.hpp.
   {
   }
postEvent() [1/2]
template<typename EventType > void smacc::ISmaccComponent::postEvent () protected
postEvent() [2/2]
template<typename EventType > void smacc::ISmaccComponent::postEvent (const EventType & ev) protected
Definition at line 31 of file smacc_component_impl.hpp.
 {
   stateMachine_->postEvent(ev);
 }
References smacc::ISmaccStateMachine::postEvent(), and stateMachine_.
requiresClient()
template<typename TClient > void smacc::ISmaccComponent::requiresClient (TClient *& requiredClientStorage) protected
Definition at line 43 of file smacc_component_impl.hpp.
 {
   this->owner_->requiresClient(requiredClientStorage);
 }
References owner_, and smacc::ISmaccClient::requiresClient().
requiresComponent()
template<typename TComponent > void smacc::ISmaccComponent::requiresComponent (TComponent *& requiredComponentStorage) protected
Definition at line 37 of file smacc_component_impl.hpp.
 {
   requiredComponentStorage = this->owner_->getComponent<TComponent>();
 }
References smacc::ISmaccClient::getComponent(), and owner_.
setStateMachine()
void smacc::ISmaccComponent::setStateMachine (ISmaccStateMachine * stateMachine) private
Definition at line 36 of file smacc_component.cpp.
 {
   stateMachine_ = stateMachine;
 }
References stateMachine_.
Friends And Related Function Documentation
ISmaccClient
friend class ISmaccClient friend
Definition at line 85 of file component.hpp.
ISmaccOrthogonal
friend class ISmaccOrthogonal friend
Definition at line 84 of file component.hpp.
Member Data Documentation
owner_
ISmaccClient* smacc::ISmaccComponent::owner_ protected
Definition at line 74 of file component.hpp.
Referenced by createSiblingComponent(), createSiblingNamedComponent(), getNode(), initialize(), cl_move_base_z::CostmapSwitch::onInitialize(), cl_move_base_z::WaypointNavigator::onInitialize(), requiresClient(), and requiresComponent().
stateMachine_
ISmaccStateMachine* smacc::ISmaccComponent::stateMachine_ protected
Definition at line 72 of file component.hpp.
Referenced by postEvent(), and setStateMachine().
The documentation for this class was generated from the following files:
smacc2/include/smacc/component.hpp
smacc2/include/smacc/impl/smacc_component_impl.hpp
smacc2/src/smacc/smacc_component.cpp