SMACC2: smacc::client_behaviors::CbWaitActionServer Class Reference
smacc::client_behaviors::CbWaitActionServer Class Reference
#include <cb_wait_action_server.hpp>
Public Member Functions
CbWaitActionServer (std::chrono::milliseconds timeout)
virtual ~CbWaitActionServer ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void executeOnEntry () override
Public Member Functions inherited from smacc::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Private Attributes
ISmaccActionClient * client_
std::chrono::milliseconds timeout_
Additional Inherited Members
Protected Member Functions inherited from smacc::SmaccAsyncClientBehavior
void executeOnEntry () override
void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Detailed Description
Definition at line 26 of file cb_wait_action_server.hpp.
Constructor & Destructor Documentation
CbWaitActionServer()
smacc::client_behaviors::CbWaitActionServer::CbWaitActionServer (std::chrono::milliseconds timeout)
Definition at line 21 of file cb_wait_action_server.cpp.
 : timeout_(timeout) {}
~CbWaitActionServer()
smacc::client_behaviors::CbWaitActionServer::~CbWaitActionServer () virtual
Definition at line 23 of file cb_wait_action_server.cpp.
 {}
Member Function Documentation
executeOnEntry()
void smacc::client_behaviors::CbWaitActionServer::executeOnEntry () override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 25 of file cb_wait_action_server.cpp.
 {
   if (client_ != nullptr)
   {
     std::shared_ptr<rclcpp_action::ClientBase> client_base = client_->getClientBase();
     RCLCPP_INFO(getLogger(), "[CbWaitActionServer] waiting action server..");
     bool found = client_base->wait_for_action_server(timeout_);
     if (found)
     {
       RCLCPP_INFO(getLogger(), "[CbWaitActionServer] action server already available");
       this->postSuccessEvent();
     }
     else
     {
       RCLCPP_INFO(getLogger(), "[CbWaitActionServer] action server not found, timeout");
       this->postFailureEvent();
     }
   }
   else
   {
     RCLCPP_INFO(getLogger(), "[CbWaitActionServer] there is no action client in this orthogonal");
     this->postFailureEvent();
   }
 }
References client_, smacc::client_bases::ISmaccActionClient::getClientBase(), smacc::ISmaccClientBehavior::getLogger(), smacc::SmaccAsyncClientBehavior::postFailureEvent(), smacc::SmaccAsyncClientBehavior::postSuccessEvent(), and timeout_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc::client_behaviors::CbWaitActionServer::onOrthogonalAllocation () inline
Definition at line 33 of file cb_wait_action_server.hpp.
   {
     SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
     this->requiresClient(client_);
   }
Member Data Documentation
client_
ISmaccActionClient* smacc::client_behaviors::CbWaitActionServer::client_ private
Definition at line 42 of file cb_wait_action_server.hpp.
Referenced by executeOnEntry().
timeout_
std::chrono::milliseconds smacc::client_behaviors::CbWaitActionServer::timeout_ private
Definition at line 43 of file cb_wait_action_server.hpp.
Referenced by executeOnEntry().
The documentation for this class was generated from the following files:
smacc2/include/smacc/client_behaviors/cb_wait_action_server.hpp
smacc2/src/smacc/client_behaviors/cb_wait_action_server.cpp