SMACC2: smacc::client_behaviors::CbSubscriptionCallbackBase< TMsg > Class Template Reference
smacc::client_behaviors::CbSubscriptionCallbackBase< TMsg > Class Template Reference abstract
#include <cb_subscription_callback_base.hpp>
Public Member Functions
void onEntry () override
virtual void onMessageReceived (const TMsg &msg)=0
Public Member Functions inherited from smacc::SmaccClientBehavior
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Protected Attributes
smacc::client_bases::SmaccSubscriberClient< TMsg > * attachedClient_ = nullptr
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Detailed Description
template<typename TMsg>
class smacc::client_behaviors::CbSubscriptionCallbackBase< TMsg >
Definition at line 28 of file cb_subscription_callback_base.hpp.
Member Function Documentation
onEntry()
template<typename TMsg > void smacc::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onEntry () inline override virtual
Reimplemented from smacc::ISmaccClientBehavior.
Definition at line 31 of file cb_subscription_callback_base.hpp.
   {
     this->requiresClient(attachedClient_);
     attachedClient_->onMessageReceived(&CbSubscriptionCallbackBase::onMessageReceived, this);
   }
References smacc::client_behaviors::CbSubscriptionCallbackBase< TMsg >::attachedClient_, smacc::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onMessageReceived(), smacc::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), and smacc::ISmaccClientBehavior::requiresClient().
onMessageReceived()
template<typename TMsg > virtual void smacc::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onMessageReceived (const TMsg & msg) pure virtual
Referenced by smacc::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onEntry().
Member Data Documentation
attachedClient_
template<typename TMsg > smacc::client_bases::SmaccSubscriberClient<TMsg>* smacc::client_behaviors::CbSubscriptionCallbackBase< TMsg >::attachedClient_ = nullptr protected
Definition at line 40 of file cb_subscription_callback_base.hpp.
Referenced by smacc::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onEntry().
The documentation for this class was generated from the following file:
smacc2/include/smacc/client_behaviors/cb_subscription_callback_base.hpp