SMACC2: smacc::client_bases::SmaccActionClientBase< ActionType > Class Template Reference
smacc::client_bases::SmaccActionClientBase< ActionType > Class Template Reference
#include <smacc_action_client_base.hpp>
Public Types
typedef rclcpp_action::Client< ActionType > ActionClient
using Goal = typename ActionClient::Goal
using Feedback = typename ActionClient::Feedback
using GoalHandle = rclcpp_action::ClientGoalHandle< ActionType >
typedef GoalHandle::WrappedResult WrappedResult
using SendGoalOptions = typename ActionClient::SendGoalOptions
using GoalResponseCallback = std::function< void(std::shared_future< typename GoalHandle::SharedPtr >)>
using FeedbackCallback = typename GoalHandle::FeedbackCallback
using ResultCallback = typename GoalHandle::ResultCallback
using CancelRequest = typename ActionType::Impl::CancelGoalService::Request
using CancelResponse = typename ActionType::Impl::CancelGoalService::Response
using CancelCallback = std::function< void(typename CancelResponse::SharedPtr)>
Public Member Functions
SmaccActionClientBase (std::string actionServerName)
SmaccActionClientBase ()
virtual ~SmaccActionClientBase ()
virtual std::shared_ptr< rclcpp_action::ClientBase > getClientBase () override
void onInitialize () override
template<typename EvType >
void postResultEvent (WrappedResult &)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename T >
boost::signals2::connection onSucceeded (void(T::*callback)(WrappedResult &), T *object)
template<typename T >
boost::signals2::connection onSucceeded (std::function< void(WrappedResult &)> callback)
template<typename T >
boost::signals2::connection onAborted (void(T::*callback)(WrappedResult &), T *object)
template<typename T >
boost::signals2::connection onAborted (std::function< void(WrappedResult &)> callback)
template<typename T >
boost::signals2::connection onCancelled (void(T::*callback)(WrappedResult &), T *object)
template<typename T >
boost::signals2::connection onCancelled (std::function< void(WrappedResult &)> callback)
virtual void cancelGoal () override
void sendGoal (Goal &goal)
Public Member Functions inherited from smacc::client_bases::ISmaccActionClient
ISmaccActionClient ()
virtual ~ISmaccActionClient ()
std::string getNamespace () const
Public Member Functions inherited from smacc::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
virtual smacc::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent >> &components)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Static Public Member Functions
static std::string getEventLabel ()
Public Attributes
std::string name_
rosnamespace path
std::optional< std::shared_future< typename GoalHandle::SharedPtr > > lastRequest_
GoalHandle::SharedPtr goalHandle_
smacc::SmaccSignal< void(const WrappedResult &)> onSucceeded_
smacc::SmaccSignal< void(const WrappedResult &)> onAborted_
smacc::SmaccSignal< void(const WrappedResult &)> onCancelled_
std::function< void(WrappedResult)> postSuccessEvent
std::function< void(WrappedResult)> postAbortedEvent
std::function< void(WrappedResult)> postCancelledEvent
std::function< void(const Feedback &)> postFeedbackEvent
ResultCallback done_cb
FeedbackCallback feedback_cb
Protected Member Functions
void onFeedback (typename GoalHandle::SharedPtr, const std::shared_ptr< const Feedback > feedback_msg)
void onResult (const WrappedResult &result_msg)
Protected Member Functions inherited from smacc::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes
ActionClient::SharedPtr client_
Protected Attributes inherited from smacc::client_bases::ISmaccActionClient
std::string name_
Protected Attributes inherited from smacc::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc::ISmaccComponent > > components_
Detailed Description
template<typename ActionType>
class smacc::client_bases::SmaccActionClientBase< ActionType >
Definition at line 37 of file smacc_action_client_base.hpp.
Member Typedef Documentation
ActionClient
template<typename ActionType > typedef rclcpp_action::Client<ActionType> smacc::client_bases::SmaccActionClientBase< ActionType >::ActionClient
Definition at line 42 of file smacc_action_client_base.hpp.
CancelCallback
template<typename ActionType > using smacc::client_bases::SmaccActionClientBase< ActionType >::CancelCallback = std::function<void(typename CancelResponse::SharedPtr)>
Definition at line 61 of file smacc_action_client_base.hpp.
CancelRequest
template<typename ActionType > using smacc::client_bases::SmaccActionClientBase< ActionType >::CancelRequest = typename ActionType::Impl::CancelGoalService::Request
Definition at line 59 of file smacc_action_client_base.hpp.
CancelResponse
template<typename ActionType > using smacc::client_bases::SmaccActionClientBase< ActionType >::CancelResponse = typename ActionType::Impl::CancelGoalService::Response
Definition at line 60 of file smacc_action_client_base.hpp.
Feedback
template<typename ActionType > using smacc::client_bases::SmaccActionClientBase< ActionType >::Feedback = typename ActionClient::Feedback
Definition at line 50 of file smacc_action_client_base.hpp.
FeedbackCallback
template<typename ActionType > using smacc::client_bases::SmaccActionClientBase< ActionType >::FeedbackCallback = typename GoalHandle::FeedbackCallback
Definition at line 57 of file smacc_action_client_base.hpp.
Goal
template<typename ActionType > using smacc::client_bases::SmaccActionClientBase< ActionType >::Goal = typename ActionClient::Goal
Definition at line 49 of file smacc_action_client_base.hpp.
GoalHandle
template<typename ActionType > using smacc::client_bases::SmaccActionClientBase< ActionType >::GoalHandle = rclcpp_action::ClientGoalHandle<ActionType>
Definition at line 51 of file smacc_action_client_base.hpp.
GoalResponseCallback
template<typename ActionType > using smacc::client_bases::SmaccActionClientBase< ActionType >::GoalResponseCallback = std::function<void(std::shared_future<typename GoalHandle::SharedPtr>)>
Definition at line 55 of file smacc_action_client_base.hpp.
ResultCallback
template<typename ActionType > using smacc::client_bases::SmaccActionClientBase< ActionType >::ResultCallback = typename GoalHandle::ResultCallback
Definition at line 58 of file smacc_action_client_base.hpp.
SendGoalOptions
template<typename ActionType > using smacc::client_bases::SmaccActionClientBase< ActionType >::SendGoalOptions = typename ActionClient::SendGoalOptions
Definition at line 54 of file smacc_action_client_base.hpp.
WrappedResult
template<typename ActionType > typedef GoalHandle::WrappedResult smacc::client_bases::SmaccActionClientBase< ActionType >::WrappedResult
Definition at line 52 of file smacc_action_client_base.hpp.
Constructor & Destructor Documentation
SmaccActionClientBase() [1/2]
template<typename ActionType > smacc::client_bases::SmaccActionClientBase< ActionType >::SmaccActionClientBase (std::string actionServerName) inline
Definition at line 63 of file smacc_action_client_base.hpp.
   : ISmaccActionClient(), name_(actionServerName)
   {
   }
SmaccActionClientBase() [2/2]
template<typename ActionType > smacc::client_bases::SmaccActionClientBase< ActionType >::SmaccActionClientBase () inline
Definition at line 68 of file smacc_action_client_base.hpp.
 : ISmaccActionClient(), name_("") {}
~SmaccActionClientBase()
template<typename ActionType > virtual smacc::client_bases::SmaccActionClientBase< ActionType >::~SmaccActionClientBase () inline virtual
Definition at line 70 of file smacc_action_client_base.hpp.
 {}
Member Function Documentation
cancelGoal()
template<typename ActionType > virtual void smacc::client_bases::SmaccActionClientBase< ActionType >::cancelGoal () inline override virtual
Implements smacc::client_bases::ISmaccActionClient.
Definition at line 218 of file smacc_action_client_base.hpp.
   {
     if (lastRequest_ && lastRequest_->valid())
     {
       RCLCPP_INFO(getNode()->get_logger(), "Cancelling goal of %s", this->getName().c_str());
       std::shared_future<typename CancelResponse::SharedPtr> cancelresult =
         client_->async_cancel_goal(lastRequest_->get());
       // wait actively
       cancelresult.get();
       lastRequest_.reset();
     }
     else
     {
       RCLCPP_ERROR(
         getNode()->get_logger(),
         "%s [at %s]: not connected with actionserver, skipping cancel goal ...", getName().c_str(),
         getNamespace().c_str());
     }
   }
getClientBase()
template<typename ActionType > virtual std::shared_ptr<rclcpp_action::ClientBase> smacc::client_bases::SmaccActionClientBase< ActionType >::getClientBase () inline override virtual
Implements smacc::client_bases::ISmaccActionClient.
Definition at line 72 of file smacc_action_client_base.hpp.
 { return client_; }
getEventLabel()
template<typename ActionType > static std::string smacc::client_bases::SmaccActionClientBase< ActionType >::getEventLabel () inline static
Definition at line 83 of file smacc_action_client_base.hpp.
   {
     auto type = TypeInfo::getTypeInfoFromType<ActionType>();
     return type->getNonTemplatedTypeName();
   }
References generate_debs::type.
onAborted() [1/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onAborted (std::function< void(WrappedResult &)> callback) inline
Definition at line 175 of file smacc_action_client_base.hpp.
   {
     return this->getStateMachine()->createSignalConnection(onAborted_, callback);
   }
onAborted() [2/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onAborted (void(T::*)(WrappedResult &) callback, T * object) inline
Definition at line 169 of file smacc_action_client_base.hpp.
   {
     return this->getStateMachine()->createSignalConnection(onAborted_, callback, object);
   }
Referenced by cl_move_base_z::CbMoveBaseClientBehaviorBase::onOrthogonalAllocation().
onCancelled() [1/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onCancelled (std::function< void(WrappedResult &)> callback) inline
Definition at line 187 of file smacc_action_client_base.hpp.
   {
     return this->getStateMachine()->createSignalConnection(onCancelled_, callback);
   }
onCancelled() [2/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onCancelled (void(T::*)(WrappedResult &) callback, T * object) inline
Definition at line 181 of file smacc_action_client_base.hpp.
   {
     return this->getStateMachine()->createSignalConnection(onCancelled_, callback, object);
   }
onFeedback()
template<typename ActionType > void smacc::client_bases::SmaccActionClientBase< ActionType >::onFeedback (typename GoalHandle::SharedPtr , const std::shared_ptr< const Feedback > feedback_msg) inline protected
Definition at line 340 of file smacc_action_client_base.hpp.
   {
     postFeedbackEvent(*feedback_msg);
   }
onInitialize()
template<typename ActionType > void smacc::client_bases::SmaccActionClientBase< ActionType >::onInitialize () inline override virtual
Reimplemented from smacc::ISmaccClient.
Definition at line 74 of file smacc_action_client_base.hpp.
   {
     this->client_ = rclcpp_action::create_client<ActionType>(getNode(), name_);
     RCLCPP_INFO_STREAM(
       this->getNode()->get_logger(),
       "Waiting for action server '" << name_ << "' of type: " << demangledTypeName<ActionType>());
     client_->wait_for_action_server();
   }
onOrthogonalAllocation()
template<typename ActionType > template<typename TOrthogonal , typename TSourceObject > void smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation () inline
Definition at line 126 of file smacc_action_client_base.hpp.
   {
     // we create here all the event factory functions capturing the TOrthogonal
     postSuccessEvent = [=](auto msg) {
       this->postResultEvent<EvActionSucceeded<TSourceObject, TOrthogonal>>(msg);
     };
     postAbortedEvent = [=](auto msg) {
       this->postResultEvent<EvActionAborted<TSourceObject, TOrthogonal>>(msg);
     };
     // postPreemptedEvent = [=](auto msg) { this->postResultEvent<EvActionPreempted<TSourceObject, TOrthogonal>>(msg);
     // }; postRejectedEvent = [=](auto msg) { this->postResultEvent<EvActionRejected<TSourceObject, TOrthogonal>>(msg);
     // };
     postCancelledEvent = [=](auto msg) {
       this->postResultEvent<EvActionCancelled<TSourceObject, TOrthogonal>>(msg);
     };
     postFeedbackEvent = [=](auto msg) {
       auto actionFeedbackEvent = new EvActionFeedback<Feedback, TOrthogonal>();
       actionFeedbackEvent->client = this;
       actionFeedbackEvent->feedbackMessage = msg;
       this->postEvent(actionFeedbackEvent);
       RCLCPP_DEBUG(
         getNode()->get_logger(), "[%s] FEEDBACK EVENT", demangleType(typeid(*this)).c_str());
     };
     done_cb = [=](auto r) { this->onResult(r); };
     // done_cb = boost::bind(&SmaccActionClientBase<ActionType>::onResult, this, _1, _2);
     // active_cb;
     feedback_cb = [=](auto client, auto feedback) { this->onFeedback(client, feedback); };
   }
References smacc::introspection::demangleType().
onResult()
template<typename ActionType > void smacc::client_bases::SmaccActionClientBase< ActionType >::onResult (const WrappedResult & result_msg) inline protected
Definition at line 347 of file smacc_action_client_base.hpp.
   {
     // auto *actionResultEvent = new EvActionResult<TDerived>();
     // actionResultEvent->client = this;
     // actionResultEvent->resultMessage = *result_msg;
     // const auto &resultType = this->getState();
     const auto & resultType = result_msg.code;
     RCLCPP_INFO_STREAM(
       getNode()->get_logger(), "[" << this->getName() << "] request result of request ["
                                    << rclcpp_action::to_string(result_msg.goal_id)
                                    << "]: " << (int)resultType);
     if (resultType == rclcpp_action::ResultCode::SUCCEEDED)
     {
       RCLCPP_INFO(getNode()->get_logger(), "[%s] request result: Success", this->getName().c_str());
       onSucceeded_(result_msg);
       postSuccessEvent(result_msg);
     }
     else if (resultType == rclcpp_action::ResultCode::ABORTED)
     {
       RCLCPP_INFO(getNode()->get_logger(), "[%s] request result: Aborted", this->getName().c_str());
       onAborted_(result_msg);
       postAbortedEvent(result_msg);
     }
     else if (resultType == rclcpp_action::ResultCode::CANCELED)
     {
       RCLCPP_INFO(
         getNode()->get_logger(), "[%s] request result: Rejected", this->getName().c_str());
       onCancelled_(result_msg);
       postCancelledEvent(result_msg);
     }
     /*
     else if (resultType == actionlib::SimpleClientGoalState::REJECTED)
     {
         RCLCPP_INFO(getNode()->get_logger(),"[%s] request result: Rejected", this->getName().c_str());
         onRejected_(result_msg);
         postRejectedEvent(result_msg);
     }
     else if (resultType == actionlib::SimpleClientGoalState::PREEMPTED)
     {
         RCLCPP_INFO(getNode()->get_logger(),"[%s] request result: Preempted", this->getName().c_str());
         onPreempted_(result_msg);
         postPreemptedEvent(result_msg);
     }*/
     else
     {
       RCLCPP_INFO(
         getNode()->get_logger(), "[%s] request result: NOT HANDLED TYPE: %d",
         this->getName().c_str(), (int)resultType);
     }
   }
onSucceeded() [1/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded (std::function< void(WrappedResult &)> callback) inline
Definition at line 163 of file smacc_action_client_base.hpp.
   {
     return this->getStateMachine()->createSignalConnection(onSucceeded_, callback);
   }
onSucceeded() [2/2]
template<typename ActionType > template<typename T > boost::signals2::connection smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded (void(T::*)(WrappedResult &) callback, T * object) inline
Definition at line 157 of file smacc_action_client_base.hpp.
   {
     return this->getStateMachine()->createSignalConnection(onSucceeded_, callback, object);
   }
Referenced by cl_move_base_z::CbMoveBaseClientBehaviorBase::onOrthogonalAllocation(), sm_dance_bot::StNavigateForward1::runtimeConfigure(), and cl_move_base_z::WaypointNavigator::sendNextGoal().
postResultEvent()
template<typename ActionType > template<typename EvType > void smacc::client_bases::SmaccActionClientBase< ActionType >::postResultEvent (WrappedResult &) inline
Definition at line 115 of file smacc_action_client_base.hpp.
   {
     auto * ev = new EvType();
     // ev->client = this;
     // ev->resultMessage = *result;
     RCLCPP_INFO(
       getNode()->get_logger(), "Posting EVENT %s", demangleSymbol(typeid(ev).name()).c_str());
     this->postEvent(ev);
   }
References smacc::introspection::demangleSymbol().
sendGoal()
template<typename ActionType > void smacc::client_bases::SmaccActionClientBase< ActionType >::sendGoal (Goal & goal) inline
Function called whenever feedback is received for the goal.
Function called when the result for the goal is received.
Definition at line 245 of file smacc_action_client_base.hpp.
   {
     RCLCPP_INFO_STREAM(
       getNode()->get_logger(),
       "Sending goal with guid to actionserver located in " << this->name_ << "\"");
     // if (client_->isServerConnected())
     // {
     RCLCPP_INFO_STREAM(getNode()->get_logger(), getName() << ": Goal sent.");
     // client_->sendGoal(goal, done_cb, active_cb, feedback_cb);
     // std::shared_future<typename GoalHandle::SharedPtr>
     SendGoalOptions options;
     // GoalResponseCallback
     // options.goal_response_callback;
     // FeedbackCallback
     options.feedback_callback = feedback_cb;
     // ResultCallback result_callback;
     // options.result_callback = done_cb;
     options.result_callback =
       [this](const typename rclcpp_action::ClientGoalHandle<ActionType>::WrappedResult & result) {
         // TODO(#1652): a work around until rcl_action interface is updated
         // if goal ids are not matched, the older goal call this callback so ignore the result
         // if matched, it must be processed (including aborted)
         RCLCPP_INFO_STREAM(
           getNode()->get_logger(), getName() << ": Result callback, getting shared future");
         goalHandle_ = lastRequest_->get();
         RCLCPP_INFO_STREAM(getNode()->get_logger(), getName() << ": Result CB Check goal id");
         if (this->goalHandle_->get_goal_id() == result.goal_id)
         {
           // goal_result_available_ = true;
           // result_ = result;
           RCLCPP_INFO_STREAM(getNode()->get_logger(), getName() << ": Result CB Goal id matches");
           done_cb(result);
         }
         else
         {
           RCLCPP_INFO_STREAM(
             getNode()->get_logger(), getName() << ": Result CB Goal id DOES NOT match");
         }
       };
     // if (lastRequest_ && lastRequest_->valid())
     // {
     //   RCLCPP_INFO_STREAM(getNode()->get_logger(), getName() << ": checking previous request is really finished.");
     //   auto res = this->lastRequest_->get();
     //   RCLCPP_INFO_STREAM(getNode()->get_logger(), getName() << ": okay");
     // }
     // else
     // {
     //   RCLCPP_INFO_STREAM(getNode()->get_logger(), getName() << ": no previous request.");
     // }
     RCLCPP_INFO_STREAM(getNode()->get_logger(), getName() << ": async send goal.");
     this->lastRequest_ = this->client_->async_send_goal(goal, options);
     // RCLCPP_INFO_STREAM(getNode()->get_logger(), getName() << ": Goal Id: "  <<
     // rclcpp_action::to_string(lastRequest_->get()->get_goal_id()));
     RCLCPP_INFO_STREAM(
       getNode()->get_logger(),
       getName() << ": client ready clients: " << this->client_->get_number_of_ready_clients());
     RCLCPP_INFO_STREAM(
       getNode()->get_logger(), getName()
                                  << ": Waiting it is ready? " << client_->action_server_is_ready());
     // RCLCPP_INFO_STREAM(getNode()->get_logger(), getName() << ": spinning until completed");
     // if (rclcpp::spin_until_future_complete(this->getNode(), lastRequest_, std::chrono::seconds(2))
     // !=rclcpp::executor::FutureReturnCode::SUCCESS)
     // {
     //   throw std::runtime_error("send_goal failed");
     // }
     // goalHandle_ = lastRequest_->get();
     // if (!goalHandle_) {
     //   throw std::runtime_error("Goal was rejected by the action server");
     // }
     // }
     // else
     // {
     //     RCLCPP_ERROR(getNode()->get_logger(),"%s [at %s]: not connected with actionserver, skipping goal request
     //     ...", getName().c_str(), getNamespace().c_str());
     //     //client_->waitForServer();
     // }
   }
Referenced by cl_move_base_z::CbNavigateGlobalPosition::execute(), cl_move_base_z::CbAbsoluteRotate::onEntry(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), cl_move_base_z::CbRotate::onEntry(), cl_move_base_z::CbUndoPathBackwards::onEntry(), sm_dance_bot::cl_led::CbLEDOff::onEntry(), sm_dance_bot::cl_led::CbLEDOn::onEntry(), sm_dance_bot_strikes_back::cl_led::CbLEDOff::onEntry(), sm_dance_bot_strikes_back::cl_led::CbLEDOn::onEntry(), and cl_move_base_z::WaypointNavigator::sendNextGoal().
Member Data Documentation
client_
template<typename ActionType > ActionClient::SharedPtr smacc::client_bases::SmaccActionClientBase< ActionType >::client_ protected
Definition at line 338 of file smacc_action_client_base.hpp.
done_cb
template<typename ActionType > ResultCallback smacc::client_bases::SmaccActionClientBase< ActionType >::done_cb
Definition at line 110 of file smacc_action_client_base.hpp.
feedback_cb
template<typename ActionType > FeedbackCallback smacc::client_bases::SmaccActionClientBase< ActionType >::feedback_cb
Definition at line 112 of file smacc_action_client_base.hpp.
goalHandle_
template<typename ActionType > GoalHandle::SharedPtr smacc::client_bases::SmaccActionClientBase< ActionType >::goalHandle_
Definition at line 93 of file smacc_action_client_base.hpp.
lastRequest_
template<typename ActionType > std::optional<std::shared_future<typename GoalHandle::SharedPtr> > smacc::client_bases::SmaccActionClientBase< ActionType >::lastRequest_
Definition at line 92 of file smacc_action_client_base.hpp.
name_
template<typename ActionType > std::string smacc::client_bases::SmaccActionClientBase< ActionType >::name_
rosnamespace path
Definition at line 90 of file smacc_action_client_base.hpp.
Referenced by cl_move_base_z::CostmapSwitch::registerProxyFromDynamicReconfigureServer().
onAborted_
template<typename ActionType > smacc::SmaccSignal<void(const WrappedResult &)> smacc::client_bases::SmaccActionClientBase< ActionType >::onAborted_
Definition at line 96 of file smacc_action_client_base.hpp.
onCancelled_
template<typename ActionType > smacc::SmaccSignal<void(const WrappedResult &)> smacc::client_bases::SmaccActionClientBase< ActionType >::onCancelled_
Definition at line 99 of file smacc_action_client_base.hpp.
onSucceeded_
template<typename ActionType > smacc::SmaccSignal<void(const WrappedResult &)> smacc::client_bases::SmaccActionClientBase< ActionType >::onSucceeded_
Definition at line 95 of file smacc_action_client_base.hpp.
postAbortedEvent
template<typename ActionType > std::function<void(WrappedResult)> smacc::client_bases::SmaccActionClientBase< ActionType >::postAbortedEvent
Definition at line 103 of file smacc_action_client_base.hpp.
postCancelledEvent
template<typename ActionType > std::function<void(WrappedResult)> smacc::client_bases::SmaccActionClientBase< ActionType >::postCancelledEvent
Definition at line 106 of file smacc_action_client_base.hpp.
postFeedbackEvent
template<typename ActionType > std::function<void(const Feedback &)> smacc::client_bases::SmaccActionClientBase< ActionType >::postFeedbackEvent
Definition at line 108 of file smacc_action_client_base.hpp.
postSuccessEvent
template<typename ActionType > std::function<void(WrappedResult)> smacc::client_bases::SmaccActionClientBase< ActionType >::postSuccessEvent
Definition at line 102 of file smacc_action_client_base.hpp.
The documentation for this class was generated from the following file:
smacc2/include/smacc/client_bases/smacc_action_client_base.hpp