SMACC2: smacc::StateReactor Class Reference
smacc::StateReactor Class Reference abstract
#include <smacc_state_reactor.hpp>
Public Member Functions
StateReactor ()
virtual ~StateReactor ()
virtual void onInitialized ()
virtual void onEntry ()
virtual void onExit ()
virtual void onEventNotified (const std::type_info *eventType)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename T , typename TClass >
void createEventCallback (void(TClass::*callback)(T *), TClass *object)
template<typename T >
void createEventCallback (std::function< void(T *)> callback)
void update ()
virtual bool triggers ()=0
template<typename TEv >
void addInputEvent ()
template<typename TEv >
void setOutputEvent ()
void initialize (ISmaccState *ownerState)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Public Attributes
ISmaccState * ownerState
std::function< void()> postEventFn
std::vector< const std::type_info * > eventTypes
std::map< const std::type_info *, std::function< void(void *)> > eventCallbacks_
Private Member Functions
template<typename TEvent >
void notifyEvent (TEvent *ev)
Private Attributes
friend ISmaccStateMachine
Detailed Description
Definition at line 43 of file smacc_state_reactor.hpp.
Constructor & Destructor Documentation
StateReactor()
smacc::StateReactor::StateReactor ()
Definition at line 23 of file state_reactor.cpp.
 {}
~StateReactor()
smacc::StateReactor::~StateReactor () virtual
Definition at line 25 of file state_reactor.cpp.
 {}
Member Function Documentation
addInputEvent()
template<typename TEv > void smacc::StateReactor::addInputEvent
Definition at line 51 of file smacc_state_reactor_impl.hpp.
 {
   this->eventTypes.push_back(&typeid(TEv));
 }
References eventTypes.
Referenced by smacc::AddTEventTypeStateReactor< TEventList >::operator()().
createEventCallback() [1/2]
template<typename T > void smacc::StateReactor::createEventCallback (std::function< void(T *)> callback)
Definition at line 67 of file smacc_state_reactor_impl.hpp.
 {
   const auto * eventtype = &typeid(T);
   this->eventCallbacks_[eventtype] = [=](void * msg) {
     T * evptr = (T *)msg;
     callback(evptr);
   };
 }
References eventCallbacks_.
createEventCallback() [2/2]
template<typename T , typename TClass > void smacc::StateReactor::createEventCallback (void(TClass::*)(T *) callback, TClass * object)
Definition at line 57 of file smacc_state_reactor_impl.hpp.
 {
   const auto * eventtype = &typeid(T);
   this->eventCallbacks_[eventtype] = [=](void * msg) {
     T * evptr = (T *)msg;
     (object->*callback)(evptr);
   };
 }
References eventCallbacks_.
Referenced by smacc::state_reactors::Srsr_conditional::Srsr_conditional().
getLogger()
rclcpp::Logger smacc::StateReactor::getLogger () inline
Definition at line 91 of file smacc_state_reactor.hpp.
 { return getNode()->get_logger(); }
References getNode().
Referenced by smacc::state_reactors::SrEventCountdown::onEventNotified(), setOutputEvent(), smacc::state_reactors::SrEventCountdown::triggers(), and update().
getNode()
rclcpp::Node::SharedPtr smacc::StateReactor::getNode ()
Definition at line 50 of file state_reactor.cpp.
 { return ownerState->getNode(); }
References smacc::ISmaccState::getNode(), and ownerState.
Referenced by getLogger().
initialize()
void smacc::StateReactor::initialize (smacc::ISmaccState * ownerState)
Definition at line 27 of file state_reactor.cpp.
 {
   this->ownerState = ownerState;
   this->onInitialized();
 }
References onInitialized(), and ownerState.
notifyEvent()
template<typename TEvent > void smacc::StateReactor::notifyEvent (TEvent * ev) inline private
Definition at line 97 of file smacc_state_reactor.hpp.
   {
     //the state machine uses this method to notify this state reactor some event happened.
     auto tid = &(typeid(TEvent));
     if (std::find(eventTypes.begin(), eventTypes.end(), tid) != eventTypes.end())
     {
       this->onEventNotified(tid);
       this->update();
       if (eventCallbacks_.count(tid))
       {
         eventCallbacks_[tid]((void *)ev);
       }
     }
   }
References eventCallbacks_, eventTypes, onEventNotified(), and update().
onEntry()
void smacc::StateReactor::onEntry () virtual
Definition at line 37 of file state_reactor.cpp.
 {}
onEventNotified()
void smacc::StateReactor::onEventNotified (const std::type_info * eventType) virtual
Reimplemented in smacc::state_reactors::SrEventCountdown, and smacc::state_reactors::SrAllEventsGo.
Definition at line 35 of file state_reactor.cpp.
 {}
Referenced by notifyEvent().
onExit()
void smacc::StateReactor::onExit () virtual
Definition at line 39 of file state_reactor.cpp.
 {}
onInitialized()
void smacc::StateReactor::onInitialized () virtual
Reimplemented in smacc::state_reactors::SrEventCountdown, and smacc::state_reactors::SrAllEventsGo.
Definition at line 33 of file state_reactor.cpp.
 {}
Referenced by initialize().
postEvent() [1/2]
template<typename EventType > void smacc::StateReactor::postEvent
Definition at line 34 of file smacc_state_reactor_impl.hpp.
 {
   ownerState->postEvent<EventType>();
 }
References ownerState, and smacc::ISmaccState::postEvent().
postEvent() [2/2]
template<typename EventType > void smacc::StateReactor::postEvent (const EventType & ev)
Definition at line 28 of file smacc_state_reactor_impl.hpp.
 {
   ownerState->postEvent(ev);
 }
References ownerState, and smacc::ISmaccState::postEvent().
setOutputEvent()
template<typename TEv > void smacc::StateReactor::setOutputEvent
Definition at line 40 of file smacc_state_reactor_impl.hpp.
 {
   this->postEventFn = [this]() {
     RCLCPP_INFO_STREAM(
       this->getLogger(), "[State Reactor Base] postingfn posting event: " << demangleSymbol<TEv>());
     auto * ev = new TEv();
     this->ownerState->getStateMachine().postEvent(ev);
   };
 }
References getLogger(), smacc::ISmaccState::getStateMachine(), ownerState, smacc::ISmaccStateMachine::postEvent(), and postEventFn.
triggers()
virtual bool smacc::StateReactor::triggers () pure virtual
Implemented in smacc::state_reactors::SrEventCountdown, smacc::state_reactors::Srsr_conditional, and smacc::state_reactors::SrAllEventsGo.
Referenced by update().
update()
void smacc::StateReactor::update ()
Definition at line 41 of file state_reactor.cpp.
 {
   if (this->triggers())
   {
     RCLCPP_INFO(getLogger(), "State reactor base REALLY TRIGGERS!!");
     this->postEventFn();
   }
 }
References getLogger(), postEventFn, and triggers().
Referenced by notifyEvent().
Member Data Documentation
eventCallbacks_
std::map<const std::type_info *, std::function<void(void *)> > smacc::StateReactor::eventCallbacks_
Definition at line 49 of file smacc_state_reactor.hpp.
Referenced by createEventCallback(), and notifyEvent().
eventTypes
std::vector<const std::type_info *> smacc::StateReactor::eventTypes
Definition at line 48 of file smacc_state_reactor.hpp.
Referenced by addInputEvent(), notifyEvent(), and smacc::state_reactors::SrEventCountdown::onInitialized().
ISmaccStateMachine
friend smacc::StateReactor::ISmaccStateMachine private
Definition at line 94 of file smacc_state_reactor.hpp.
ownerState
ISmaccState* smacc::StateReactor::ownerState
Definition at line 46 of file smacc_state_reactor.hpp.
Referenced by getNode(), initialize(), postEvent(), and setOutputEvent().
postEventFn
std::function<void()> smacc::StateReactor::postEventFn
Definition at line 47 of file smacc_state_reactor.hpp.
Referenced by setOutputEvent(), and update().
The documentation for this class was generated from the following files:
smacc2/include/smacc/smacc_state_reactor.hpp
smacc2/include/smacc/impl/smacc_state_reactor_impl.hpp
smacc2/src/smacc/state_reactor.cpp