SMACC2: smacc::SignalDetector Class Reference
smacc::SignalDetector Class Reference
#include <smacc_signal_detector.hpp>
Public Member Functions
SignalDetector (SmaccFifoScheduler *scheduler)
void initialize (ISmaccStateMachine *stateMachine)
void setProcessorHandle (SmaccFifoScheduler::processor_handle processorHandle)
void runThread ()
void join ()
void stop ()
void pollingLoop ()
void pollOnce ()
template<typename EventType >
void postEvent (EventType *ev)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Private Member Functions
void findUpdatableClientsAndComponents ()
void findUpdatableStateElements (ISmaccState *currentState)
Private Attributes
ISmaccStateMachine * smaccStateMachine_
std::vector< ISmaccUpdatable * > updatableClients_
std::vector< ISmaccUpdatable * > updatableStateElements_
std::atomic< unsigned long > lastState_
double loop_rate_hz
std::atomic< bool > end_
std::atomic< bool > initialized_
rclcpp::Publisher< smacc_msgs::msg::SmaccStatus >::SharedPtr statusPub_
SmaccFifoScheduler * scheduler_
SmaccFifoScheduler::processor_handle processorHandle_
boost::thread signalDetectorThread_
Detailed Description
Definition at line 29 of file smacc_signal_detector.hpp.
Constructor & Destructor Documentation
SignalDetector()
smacc::SignalDetector::SignalDetector (SmaccFifoScheduler * scheduler)
SignalDetector()
Definition at line 42 of file signal_detector.cpp.
 {
   scheduler_ = scheduler;
   loop_rate_hz = 20.0;
   end_ = false;
   initialized_ = false;
 }
Member Function Documentation
findUpdatableClientsAndComponents()
void smacc::SignalDetector::findUpdatableClientsAndComponents () private
findUpdatableClientsAndComponents()
Definition at line 72 of file signal_detector.cpp.
 {
   this->updatableClients_.clear();
   for (auto pair : this->smaccStateMachine_->getOrthogonals())
   {
     auto & orthogonal = pair.second;
     auto & clients = orthogonal->getClients();
     for (auto & client : clients)
     {
       // updatable client components
       auto updatableClient = dynamic_cast<ISmaccUpdatable *>(client.get());
       if (updatableClient != nullptr)
       {
         RCLCPP_DEBUG_STREAM(
           getLogger(), "Adding updatable client: " << demangleType(typeid(updatableClient)));
         this->updatableClients_.push_back(updatableClient);
       }
       // updatable client components
       std::vector<std::shared_ptr<ISmaccComponent>> components;
       client->getComponents(components);
       for (auto & componententry : components)
       {
         auto updatableComponent = dynamic_cast<ISmaccUpdatable *>(componententry.get());
         if (updatableComponent != nullptr)
         {
           RCLCPP_DEBUG_STREAM(
             getLogger(),
             "Adding updatable component: " << demangleType(typeid(*updatableComponent)));
           this->updatableClients_.push_back(updatableComponent);
         }
       }
     }
   }
 }
References smacc::introspection::demangleType().
findUpdatableStateElements()
void smacc::SignalDetector::findUpdatableStateElements (ISmaccState * currentState) private
findUpdatableClientBehaviors()
Definition at line 115 of file signal_detector.cpp.
 {
   this->updatableStateElements_.clear();
   for (auto pair : this->smaccStateMachine_->getOrthogonals())
   {
     auto & orthogonal = pair.second;
     auto & behaviors = orthogonal->getClientBehaviors();
     for (auto & currentBehavior : behaviors)
     {
       ISmaccUpdatable * updatableClientBehavior =
         dynamic_cast<ISmaccUpdatable *>(currentBehavior.get());
       if (updatableClientBehavior != nullptr)
       {
         RCLCPP_DEBUG_STREAM(
           getLogger(),
           "Adding updatable behavior: " << demangleType(typeid(updatableClientBehavior)));
         this->updatableStateElements_.push_back(updatableClientBehavior);
       }
     }
   }
   auto updatableState = dynamic_cast<ISmaccUpdatable *>(currentState);
   if (updatableState != nullptr)
   {
     this->updatableStateElements_.push_back(updatableState);
   }
   auto statereactors = currentState->getStateReactors();
   for (auto & sr : statereactors)
   {
     ISmaccUpdatable * updatableStateReactor = dynamic_cast<ISmaccUpdatable *>(sr.get());
     if (updatableStateReactor != nullptr)
     {
       RCLCPP_DEBUG_STREAM(
         getLogger(),
         "Adding updatable stateReactorr: " << demangleType(typeid(updatableStateReactor)));
       this->updatableStateElements_.push_back(updatableStateReactor);
     }
   }
   auto eventgenerators = currentState->getEventGenerators();
   for (auto & eg : eventgenerators)
   {
     ISmaccUpdatable * updatableEventGenerator = dynamic_cast<ISmaccUpdatable *>(eg.get());
     if (updatableEventGenerator != nullptr)
     {
       RCLCPP_DEBUG_STREAM(
         getLogger(),
         "Adding updatable eventGenerator: " << demangleType(typeid(updatableEventGenerator)));
       this->updatableStateElements_.push_back(updatableEventGenerator);
     }
   }
 }
References smacc::introspection::demangleType(), smacc::ISmaccState::getEventGenerators(), and smacc::ISmaccState::getStateReactors().
getLogger()
rclcpp::Logger smacc::SignalDetector::getLogger () inline
Definition at line 58 of file smacc_signal_detector.hpp.
 { return getNode()->get_logger(); }
References getNode().
getNode()
rclcpp::Node::SharedPtr smacc::SignalDetector::getNode ()
Definition at line 50 of file signal_detector.cpp.
 { return this->smaccStateMachine_->getNode(); }
Referenced by getLogger().
initialize()
void smacc::SignalDetector::initialize (ISmaccStateMachine * stateMachine)
initialize()
Definition at line 57 of file signal_detector.cpp.
 {
   smaccStateMachine_ = stateMachine;
   lastState_ = std::numeric_limits<unsigned long>::quiet_NaN();
   findUpdatableClientsAndComponents();
   this->getNode()->declare_parameter("signal_detector_loop_freq", this->loop_rate_hz);
   initialized_ = true;
 }
Referenced by smacc::ISmaccStateMachine::ISmaccStateMachine().
join()
void smacc::SignalDetector::join ()
join()
Definition at line 196 of file signal_detector.cpp.
 { signalDetectorThread_.join(); }
pollingLoop()
void smacc::SignalDetector::pollingLoop ()
pollingLoop()
Definition at line 333 of file signal_detector.cpp.
 {
   // rclcpp::Node::SharedPtr nh("~"); // use node name as root of the parameter server
   rclcpp::Node::SharedPtr _;
   rclcpp::Rate r0(20);
   while (!initialized_)
   {
     r0.sleep();
   }
   if (!getNode()->get_parameter("signal_detector_loop_freq", this->loop_rate_hz))
   {
     RCLCPP_WARN(
       getLogger(),
       "Signal detector frequency (ros param signal_detector_loop_freq) was not set, using default "
       "frequency: "
       "%lf",
       this->loop_rate_hz);
   }
   else
   {
     RCLCPP_WARN(
       getLogger(), "Signal detector frequency (ros param signal_detector_loop_freq): %lf",
       this->loop_rate_hz);
   }
   getNode()->set_parameter(rclcpp::Parameter("signal_detector_loop_freq", this->loop_rate_hz));
   RCLCPP_INFO_STREAM(getLogger(), "[SignalDetector] loop rate hz:" << loop_rate_hz);
   rclcpp::Rate r(loop_rate_hz);
   while (rclcpp::ok() && !end_)
   {
     pollOnce();
     rclcpp::spin_some(getNode());
     r.sleep();
   }
 }
Referenced by smacc::run(), and runThread().
pollOnce()
void smacc::SignalDetector::pollOnce ()
poll()
Definition at line 210 of file signal_detector.cpp.
 {
   // precondition: smaccStateMachine_ != nullptr
   //TRACEPOINT( spinOnce);
   TRACEPOINT(spinOnce);
   try
   {
     smaccStateMachine_->lockStateMachine("update behaviors");
     long currentStateIndex = smaccStateMachine_->getCurrentStateCounter();
     auto currentState = smaccStateMachine_->getCurrentState();
     if (currentState != nullptr)
     {
       RCLCPP_INFO_THROTTLE(
         getLogger(), *(getNode()->get_clock()), 10000,
         "[SignalDetector] heartbeat. Current State: %s",
         demangleType(typeid(*currentState)).c_str());
     }
     this->findUpdatableClientsAndComponents();
     RCLCPP_DEBUG_STREAM(getLogger(), "updatable clients: " << this->updatableClients_.size());
     if (this->updatableClients_.size())
     {
       auto node = getNode();
       for (auto * updatableClient : this->updatableClients_)
       {
         auto updatableElementName = demangleType(typeid(*updatableClient)).c_str();
         try
         {
           RCLCPP_DEBUG_STREAM(
             node->get_logger(),
             "[PollOnce] update client call:  " << demangleType(typeid(*updatableClient)));
           TRACEPOINT(update_start, updatableElementName);
           updatableClient->executeUpdate(node);
           TRACEPOINT(update_start, updatableElementName);
         }
         catch (const std::exception & e)
         {
           RCLCPP_ERROR_STREAM(
             node->get_logger(),
             "Error in updatable elemnent " << updatableElementName << ": " << e.what() << '\n');
         }
       }
     }
     // STATE UPDATABLE ELEMENTS
     if (
       this->smaccStateMachine_->stateMachineCurrentAction !=
         StateMachineInternalAction::TRANSITIONING &&
       this->smaccStateMachine_->stateMachineCurrentAction !=
         StateMachineInternalAction::STATE_CONFIGURING &&
       this->smaccStateMachine_->stateMachineCurrentAction !=
         StateMachineInternalAction::STATE_EXITING)
     {
       // we do not update updatable elements during trasitioning or configuration of states
       RCLCPP_DEBUG_STREAM(getLogger(), "[SignalDetector] update behaviors. checking current state");
       if (currentState != nullptr)
       {
         RCLCPP_DEBUG_STREAM(getLogger(), "[SignalDetector] current state: " << currentStateIndex);
         RCLCPP_DEBUG_STREAM(getLogger(), "[SignalDetector] last state: " << this->lastState_);
         if (currentStateIndex != 0)
         {
           if (currentStateIndex != (long)this->lastState_)
           {
             RCLCPP_DEBUG_STREAM(
               getLogger(),
               "[PollOnce] detected new state, refreshing updatable client "
               "behavior table");
             // we are in a new state, refresh the updatable client behaviors table
             this->lastState_ = currentStateIndex;
             this->findUpdatableStateElements(currentState);
           }
           RCLCPP_DEBUG_STREAM(
             getLogger(),
             "[SignalDetector] updatable state elements: " << this->updatableStateElements_.size());
           auto node = getNode();
           for (auto * udpatableStateElement : this->updatableStateElements_)
           {
             auto updatableElementName = demangleType(typeid(*udpatableStateElement)).c_str();
             try
             {
               RCLCPP_DEBUG_STREAM(
                 getLogger(),
                 "[SignalDetector] update client behavior call: " << updatableElementName);
               TRACEPOINT(update_start, updatableElementName);
               udpatableStateElement->executeUpdate(node);
               TRACEPOINT(update_start, updatableElementName);
             }
             catch (const std::exception & e)
             {
               RCLCPP_ERROR_STREAM(
                 node->get_logger(),
                 "Error in updatable elemnent " << updatableElementName << ": " << e.what() << '\n');
             }
           }
         }
       }
     }
   }
   catch (std::exception & ex)
   {
     RCLCPP_ERROR(getLogger(), "Exception during Signal Detector update loop. %s", ex.what());
   }
   auto nh = this->getNode();
   rclcpp::spin_some(nh);
   smaccStateMachine_->unlockStateMachine("update behaviors");
 }
References smacc::introspection::demangleType(), smacc::STATE_CONFIGURING, smacc::STATE_EXITING, TRACEPOINT(), smacc::TRANSITIONING, and update_start.
postEvent()
template<typename EventType > void smacc::SignalDetector::postEvent (EventType * ev) inline
Definition at line 51 of file smacc_signal_detector.hpp.
   {
     boost::intrusive_ptr<EventType> weakPtrEvent = ev;
     this->scheduler_->queue_event(processorHandle_, weakPtrEvent);
   }
References processorHandle_, and scheduler_.
runThread()
void smacc::SignalDetector::runThread ()
runThread()
Definition at line 186 of file signal_detector.cpp.
 {
   signalDetectorThread_ = boost::thread(boost::bind(&SignalDetector::pollingLoop, this));
 }
References pollingLoop().
setProcessorHandle()
void smacc::SignalDetector::setProcessorHandle (SmaccFifoScheduler::processor_handle processorHandle)
setProcessorHandle()
Definition at line 176 of file signal_detector.cpp.
 {
   processorHandle_ = processorHandle;
 }
Referenced by smacc::run().
stop()
void smacc::SignalDetector::stop ()
stop()
Definition at line 203 of file signal_detector.cpp.
 { end_ = true; }
Member Data Documentation
end_
std::atomic<bool> smacc::SignalDetector::end_ private
Definition at line 75 of file smacc_signal_detector.hpp.
initialized_
std::atomic<bool> smacc::SignalDetector::initialized_ private
Definition at line 77 of file smacc_signal_detector.hpp.
lastState_
std::atomic<unsigned long> smacc::SignalDetector::lastState_ private
Definition at line 67 of file smacc_signal_detector.hpp.
loop_rate_hz
double smacc::SignalDetector::loop_rate_hz private
Definition at line 73 of file smacc_signal_detector.hpp.
processorHandle_
SmaccFifoScheduler::processor_handle smacc::SignalDetector::processorHandle_ private
Definition at line 85 of file smacc_signal_detector.hpp.
Referenced by postEvent().
scheduler_
SmaccFifoScheduler* smacc::SignalDetector::scheduler_ private
Definition at line 83 of file smacc_signal_detector.hpp.
Referenced by postEvent().
signalDetectorThread_
boost::thread smacc::SignalDetector::signalDetectorThread_ private
Definition at line 87 of file smacc_signal_detector.hpp.
smaccStateMachine_
ISmaccStateMachine* smacc::SignalDetector::smaccStateMachine_ private
Definition at line 61 of file smacc_signal_detector.hpp.
statusPub_
rclcpp::Publisher<smacc_msgs::msg::SmaccStatus>::SharedPtr smacc::SignalDetector::statusPub_ private
Definition at line 79 of file smacc_signal_detector.hpp.
updatableClients_
std::vector<ISmaccUpdatable *> smacc::SignalDetector::updatableClients_ private
Definition at line 63 of file smacc_signal_detector.hpp.
updatableStateElements_
std::vector<ISmaccUpdatable *> smacc::SignalDetector::updatableStateElements_ private
Definition at line 65 of file smacc_signal_detector.hpp.
The documentation for this class was generated from the following files:
smacc2/include/smacc/smacc_signal_detector.hpp
smacc2/src/smacc/signal_detector.cpp