SMACC2: smacc::ISmaccOrthogonal Class Reference
smacc::ISmaccOrthogonal Class Reference
#include <smacc_orthogonal.hpp>
Public Member Functions
void setStateMachine (ISmaccStateMachine *value)
ISmaccStateMachine * getStateMachine ()
void addClientBehavior (std::shared_ptr< smacc::ISmaccClientBehavior > clientBehavior)
void runtimeConfigure ()
void onEntry ()
void onExit ()
virtual std::string getName () const
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
bool requiresClient (SmaccClientType *&storage)
const std::vector< std::shared_ptr< smacc::ISmaccClient > > & getClients ()
const std::vector< std::shared_ptr< smacc::ISmaccClientBehavior > > & getClientBehaviors () const
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename TClientBehavior >
TClientBehavior * getClientBehavior ()
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Member Functions
virtual void onInitialize ()
void initializeClients ()
template<typename TOrthogonal , typename TClient >
void assignClientToOrthogonal (TClient *client)
Protected Attributes
std::vector< std::shared_ptr< smacc::ISmaccClient > > clients_
Private Attributes
ISmaccStateMachine * stateMachine_
std::vector< std::shared_ptr< smacc::ISmaccClientBehavior > > clientBehaviors_
Friends
class ISmaccStateMachine
Detailed Description
Definition at line 27 of file smacc_orthogonal.hpp.
Member Function Documentation
addClientBehavior()
void smacc::ISmaccOrthogonal::addClientBehavior (std::shared_ptr< smacc::ISmaccClientBehavior > clientBehavior)
Definition at line 43 of file orthogonal.cpp.
 {
   if (clBehavior != nullptr)
   {
     RCLCPP_INFO(
       getLogger(), "[Orthogonal %s] adding client behavior: %s", this->getName().c_str(),
       clBehavior->getName().c_str());
     clBehavior->stateMachine_ = this->getStateMachine();
     clBehavior->currentOrthogonal = this;
     clientBehaviors_.push_back(clBehavior);
   }
   else
   {
     RCLCPP_INFO(
       getLogger(), "[orthogonal %s] no client behaviors in this state", this->getName().c_str());
   }
 }
References clientBehaviors_, getLogger(), getName(), and getStateMachine().
assignClientToOrthogonal()
template<typename TOrthogonal , typename TClient > void smacc::ISmaccOrthogonal::assignClientToOrthogonal (TClient * client) protected
Definition at line 82 of file smacc_orthogonal_impl.hpp.
 {
   client->setStateMachine(getStateMachine());
   client->setOrthogonal(this);
   client->template onOrthogonalAllocation<TOrthogonal, TClient>();
 }
References getStateMachine().
getClientBehavior()
template<typename TClientBehavior > TClientBehavior * smacc::ISmaccOrthogonal::getClientBehavior
Definition at line 91 of file smacc_orthogonal_impl.hpp.
 {
   for (auto & cb : this->clientBehaviors_)
   {
     auto * ret = dynamic_cast<TClientBehavior *>(cb.get());
     if (ret != nullptr)
     {
       return ret;
     }
   }
   return nullptr;
 }
References clientBehaviors_.
getClientBehaviors()
const std::vector< std::shared_ptr< smacc::ISmaccClientBehavior > > & smacc::ISmaccOrthogonal::getClientBehaviors () const inline
Definition at line 111 of file smacc_orthogonal_impl.hpp.
 {
   return this->clientBehaviors_;
 }
References clientBehaviors_.
getClients()
const std::vector< std::shared_ptr< smacc::ISmaccClient > > & smacc::ISmaccOrthogonal::getClients () inline
Definition at line 105 of file smacc_orthogonal_impl.hpp.
 {
   return clients_;
 }
References clients_.
getGlobalSMData()
template<typename T > bool smacc::ISmaccOrthogonal::getGlobalSMData (std::string name, T & ret)
Definition at line 123 of file smacc_orthogonal_impl.hpp.
 {
   return this->getStateMachine()->getGlobalSMData(name, ret);
 }
References smacc::ISmaccStateMachine::getGlobalSMData(), and getStateMachine().
getLogger()
rclcpp::Logger smacc::ISmaccOrthogonal::getLogger () inline
Definition at line 65 of file smacc_orthogonal.hpp.
 { return getNode()->get_logger(); }
References getNode().
Referenced by addClientBehavior(), smacc::Orthogonal< TOrthogonal >::createClient(), onEntry(), onExit(), requiresClient(), requiresComponent(), and runtimeConfigure().
getName()
std::string smacc::ISmaccOrthogonal::getName () const virtual
Definition at line 64 of file orthogonal.cpp.
 { return demangleSymbol(typeid(*this).name()); }
References smacc::introspection::demangleSymbol().
Referenced by addClientBehavior(), and runtimeConfigure().
getNode()
rclcpp::Node::SharedPtr smacc::ISmaccOrthogonal::getNode ()
Definition at line 41 of file orthogonal.cpp.
 { return this->stateMachine_->getNode(); }
References smacc::ISmaccStateMachine::getNode(), and stateMachine_.
Referenced by getLogger().
getStateMachine()
ISmaccStateMachine * smacc::ISmaccOrthogonal::getStateMachine () inline
Definition at line 129 of file smacc_orthogonal_impl.hpp.
 { return this->stateMachine_; }
References stateMachine_.
Referenced by addClientBehavior(), assignClientToOrthogonal(), getGlobalSMData(), requiresClient(), and setGlobalSMData().
initializeClients()
void smacc::ISmaccOrthogonal::initializeClients () protected
Definition at line 33 of file orthogonal.cpp.
 {
   for (auto & c : this->clients_)
   {
     c->initialize();
   }
 }
References clients_.
Referenced by setStateMachine().
onEntry()
void smacc::ISmaccOrthogonal::onEntry ()
Definition at line 78 of file orthogonal.cpp.
 {
   if (clientBehaviors_.size() > 0)
   {
     for (auto & clBehavior : clientBehaviors_)
     {
       RCLCPP_INFO(
         getLogger(), "[Orthogonal %s] OnEntry, current Behavior: %s", orthogonalName, cbName);
       try
       {
         TRACEPOINT(client_behavior_on_entry_start, statename, orthogonalName, cbName);
         clBehavior->executeOnEntry();
       }
       catch (const std::exception & e)
       {
         RCLCPP_ERROR(
           getLogger(),
           "[ClientBehavior %s] Exception on Entry - continuing with next client behavior. "
           "Exception info: "
           "%s",
           cbName, e.what());
       }
       TRACEPOINT(client_behavior_on_entry_end, statename, orthogonalName, cbName);
     }
   }
   else
   {
     RCLCPP_INFO(
       getLogger(), "[Orthogonal %s] OnEntry -> empty orthogonal (no client behavior) ",
       orthogonalName);
   }
 }
References cbName, client_behavior_on_entry_end, client_behavior_on_entry_start, clientBehaviors_, getLogger(), orthogonalName, statename, and TRACEPOINT().
onExit()
void smacc::ISmaccOrthogonal::onExit ()
Definition at line 112 of file orthogonal.cpp.
 {
   if (clientBehaviors_.size() > 0)
   {
     for (auto & clBehavior : clientBehaviors_)
     {
       RCLCPP_INFO(
         getLogger(), "[Orthogonal %s] OnExit, current Behavior: %s", orthogonalName, cbName);
       try
       {
         TRACEPOINT(client_behavior_on_exit_start, statename, orthogonalName, cbName);
         clBehavior->executeOnExit();
       }
       catch (const std::exception & e)
       {
         RCLCPP_ERROR(
           getLogger(),
           "[ClientBehavior %s] Exception onExit - continuing with next client behavior. Exception "
           "info: %s",
           cbName, e.what());
       }
       TRACEPOINT(client_behavior_on_exit_end, statename, orthogonalName, cbName);
     }
     int i = 0;
     for (auto & clBehavior : clientBehaviors_)
     {
       clBehavior->dispose();
       clientBehaviors_[i] = nullptr;
     }
     clientBehaviors_.clear();
   }
   else
   {
     RCLCPP_INFO(getLogger(), "[Orthogonal %s] OnExit", orthogonalName);
   }
 }
References cbName, client_behavior_on_exit_end, client_behavior_on_exit_start, clientBehaviors_, getLogger(), orthogonalName, statename, and TRACEPOINT().
onInitialize()
void smacc::ISmaccOrthogonal::onInitialize () protected virtual
Reimplemented in sm_three_some::OrUpdatablePublisher, sm_three_some::OrTimer, sm_three_some::OrSubscriber, sm_three_some::OrKeyboard, sm_respira_1::OrUpdatablePublisher, sm_respira_1::OrTimer, sm_respira_1::OrSubscriber, sm_respira_1::OrKeyboard, sm_ferrari::OrUpdatablePublisher, sm_ferrari::OrTimer, sm_ferrari::OrSubscriber, sm_ferrari::OrKeyboard, sm_dance_bot_strikes_back::OrUpdatablePublisher, sm_dance_bot_strikes_back::OrTimer, sm_dance_bot_strikes_back::OrTemperatureSensor, sm_dance_bot_strikes_back::OrStringPublisher, sm_dance_bot_strikes_back::OrService3, sm_dance_bot_strikes_back::OrObstaclePerception, sm_dance_bot_strikes_back::OrNavigation, sm_dance_bot_strikes_back::OrLED, sm_dance_bot::OrUpdatablePublisher, sm_dance_bot::OrTimer, sm_dance_bot::OrTemperatureSensor, sm_dance_bot::OrStringPublisher, sm_dance_bot::OrService3, sm_dance_bot::OrObstaclePerception, sm_dance_bot::OrNavigation, sm_dance_bot::OrLED, sm_branching::OrTimer, sm_atomic_subscribers_performance_test::OrSubscriber, and sm_atomic::OrTimer.
Definition at line 62 of file orthogonal.cpp.
 {}
Referenced by setStateMachine().
requiresClient()
template<typename SmaccClientType > bool smacc::ISmaccOrthogonal::requiresClient (SmaccClientType *& storage)
Definition at line 29 of file smacc_orthogonal_impl.hpp.
 {
   for (auto & client : clients_)
   {
     storage = dynamic_cast<SmaccClientType *>(client.get());
     if (storage != nullptr) return true;
   }
   auto requiredClientName = demangledTypeName<SmaccClientType>();
   RCLCPP_WARN_STREAM(
     getLogger(), "Required client ["
                    << requiredClientName
                    << "] not found in current orthogonal. Searching in other orthogonals.");
   for (auto & orthoentry : this->getStateMachine()->getOrthogonals())
   {
     for (auto & client : orthoentry.second->getClients())
     {
       storage = dynamic_cast<SmaccClientType *>(client.get());
       if (storage != nullptr)
       {
         RCLCPP_WARN_STREAM(
           getLogger(),
           "Required client  [" << requiredClientName << "] found in other orthogonal.");
         return true;
       }
     }
   }
   RCLCPP_ERROR_STREAM(
     getLogger(), "Required client ["
                    << requiredClientName
                    << "] not found even in other orthogonals. Returning null pointer. If the "
                       "requested client is used may result in a segmentation fault.");
   return false;
 }
References clients_, getLogger(), and getStateMachine().
Referenced by smacc::ISmaccClient::requiresClient(), and smacc::ISmaccClientBehavior::requiresClient().
requiresComponent()
template<typename SmaccComponentType > void smacc::ISmaccOrthogonal::requiresComponent (SmaccComponentType *& storage)
Definition at line 67 of file smacc_orthogonal_impl.hpp.
 {
   if (stateMachine_ == nullptr)
   {
     RCLCPP_ERROR(
       getLogger(),
       "Cannot use the requiresComponent funcionality from an orthogonal before onInitialize");
   }
   else
   {
     stateMachine_->requiresComponent(storage);
   }
 }
References getLogger(), smacc::ISmaccStateMachine::requiresComponent(), and stateMachine_.
runtimeConfigure()
void smacc::ISmaccOrthogonal::runtimeConfigure ()
Definition at line 66 of file orthogonal.cpp.
 {
   for (auto & clBehavior : clientBehaviors_)
   {
     RCLCPP_INFO(
       getLogger(), "[Orthogonal %s] runtimeConfigure, current Behavior: %s",
       this->getName().c_str(), clBehavior->getName().c_str());
     clBehavior->runtimeConfigure();
   }
 }
References clientBehaviors_, getLogger(), and getName().
setGlobalSMData()
template<typename T > void smacc::ISmaccOrthogonal::setGlobalSMData (std::string name, T value)
Definition at line 117 of file smacc_orthogonal_impl.hpp.
 {
   this->getStateMachine()->setGlobalSMData(name, value);
 }
References getStateMachine(), and smacc::ISmaccStateMachine::setGlobalSMData().
setStateMachine()
void smacc::ISmaccOrthogonal::setStateMachine (ISmaccStateMachine * value)
Definition at line 26 of file orthogonal.cpp.
 {
   this->stateMachine_ = value;
   this->onInitialize();
   this->initializeClients();
 }
References initializeClients(), onInitialize(), and stateMachine_.
Friends And Related Function Documentation
ISmaccStateMachine
friend class ISmaccStateMachine friend
Definition at line 81 of file smacc_orthogonal.hpp.
Member Data Documentation
clientBehaviors_
std::vector<std::shared_ptr<smacc::ISmaccClientBehavior> > smacc::ISmaccOrthogonal::clientBehaviors_ private
Definition at line 80 of file smacc_orthogonal.hpp.
Referenced by addClientBehavior(), getClientBehavior(), getClientBehaviors(), onEntry(), onExit(), and runtimeConfigure().
clients_
std::vector<std::shared_ptr<smacc::ISmaccClient> > smacc::ISmaccOrthogonal::clients_ protected
Definition at line 75 of file smacc_orthogonal.hpp.
Referenced by smacc::Orthogonal< TOrthogonal >::createClient(), getClients(), initializeClients(), and requiresClient().
stateMachine_
ISmaccStateMachine* smacc::ISmaccOrthogonal::stateMachine_ private
Definition at line 78 of file smacc_orthogonal.hpp.
Referenced by getNode(), getStateMachine(), requiresComponent(), and setStateMachine().
The documentation for this class was generated from the following files:
smacc2/include/smacc/smacc_orthogonal.hpp
smacc2/include/smacc/impl/smacc_orthogonal_impl.hpp
smacc2/src/smacc/orthogonal.cpp