SMACC2: smacc::utils Namespace Reference
smacc::utils Namespace Reference
Classes
struct Bind
struct Bind< 1 >
struct Bind< 2 >
struct Bind< 3 >
struct Bind< 4 >
Functions
std::string cleanShortTypeName (const std::type_info &tinfo)
template<typename T >
std::string cleanShortTypeName ()
Function Documentation
cleanShortTypeName() [1/2]
template<typename T > std::string smacc::utils::cleanShortTypeName ()
Definition at line 57 of file common.hpp.
 {
   return cleanShortTypeName(typeid(T));
 }
References cleanShortTypeName().
cleanShortTypeName() [2/2]
std::string smacc::utils::cleanShortTypeName (const std::type_info & tinfo)
Definition at line 27 of file common.cpp.
 {
   auto typeinfo = TypeInfo::getFromStdTypeInfo(tinfo);
   auto nontemplatedfullclasname = typeinfo->getNonTemplatedTypeName();
   std::vector<std::string> strs;
   boost::split(strs, nontemplatedfullclasname, boost::is_any_of("::"));
   std::string classname = strs.back();
   return classname;
 }
References smacc::introspection::TypeInfo::getFromStdTypeInfo().
Referenced by cleanShortTypeName(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::configure_orthogonal_internal(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getShortName(), smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::initiate_impl(), and smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().