SMACC2: smacc::introspection Namespace Reference
smacc::introspection Namespace Reference
Classes
struct typelist
class HasEventLabel
class HasAutomaticTransitionTag
class HasAutomaticTransitionType
struct type_
struct add_type_wrapper
struct CheckType
struct ClientBehaviorInfoEntry
struct SmaccEventInfo
struct SmaccTransitionInfo
struct StateReactorCallbackFunctor
class StateReactorHandler
struct SmaccStateReactorInfo
struct EventGeneratorCallbackFunctor
class EventGeneratorHandler
struct SmaccEventGeneratorInfo
class SmaccStateInfo
class SmaccStateMachineInfo
struct AddSubState
struct AddTransition
struct WalkStatesExecutor
class HasOnDefinition
class TypeInfo
Typedefs
typedef std::allocator< boost::statechart::none > SmaccAllocator
typedef boost::mpl::list< SUCCESS, ABORT, CANCEL, CONTINUELOOP, ENDLOOP > DEFAULT_TRANSITION_TYPES
Enumerations
enum class SmaccStateType { SUPERSTATE = 2 , STATE = 1 , SUPERSTATE_ROUTINE = 1 }
Functions
void transitionInfoToMsg (const SmaccTransitionInfo &transition, smacc_msgs::msg::SmaccTransition &transitionMsg)
template<class T >
auto optionalNodeHandle (std::shared_ptr< T > &obj) -> T *
template<class T >
auto optionalNodeHandle (boost::intrusive_ptr< T > &obj) -> T *
template<class T >
auto optionalNodeHandle (T *obj) -> T *
std::string demangleSymbol (const std::string &name)
std::string demangleSymbol (const char *name)
template<typename T >
std::string demangleSymbol ()
template<class T >
std::string demangledTypeName ()
std::string demangleType (const std::type_info *tinfo)
std::string demangleType (const std::type_info &tinfo)
template<typename T >
std::enable_if< HasEventLabel< T >::value, void >::type EventLabel (std::string &label)
template<typename T >
std::enable_if<!HasEventLabel< T >::value, void >::type EventLabel (std::string &label)
template<typename T >
std::enable_if< HasAutomaticTransitionTag< T >::value, void >::type automaticTransitionTag (std::string &transition_name)
template<typename T >
std::enable_if<!HasAutomaticTransitionTag< T >::value, void >::type automaticTransitionTag (std::string &transition_name)
template<typename T >
std::enable_if< HasAutomaticTransitionType< T >::value, void >::type automaticTransitionType (std::string &transition_type)
template<typename T >
std::enable_if<!HasAutomaticTransitionType< T >::value, void >::type automaticTransitionType (std::string &transition_type)
template<typename TTransition >
static std::string getTransitionType ()
template<typename T >
disable_if< boost::mpl::is_sequence< T > >::type processSubState (std::shared_ptr< SmaccStateInfo > &parentState)
template<typename T >
enable_if< boost::mpl::is_sequence< T > >::type processSubState (std::shared_ptr< SmaccStateInfo > &parentState)
template<typename T >
enable_if< boost::mpl::is_sequence< T > >::type processTransitions (std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev , typename Dst , typename Tag >
void processTransition (smacc::Transition< Ev, boost::statechart::deep_history< Dst >, Tag > *, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev , typename Dst , typename Tag >
void processTransition (smacc::Transition< Ev, Dst, Tag > *t, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev , typename Dst , typename Tag >
void processTransitionAux (smacc::Transition< Ev, Dst, Tag > *, std::shared_ptr< SmaccStateInfo > &sourceState, bool history, TypeInfo::Ptr &transitionTypeInfo)
template<typename Ev , typename Dst >
void processTransition (statechart::transition< Ev, Dst > *, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev >
void processTransition (statechart::custom_reaction< Ev > *, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename T >
disable_if< boost::mpl::is_sequence< T > >::type processTransitions (std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename T >
std::enable_if< HasOnDefinition< T >::value, void >::type CallOnDefinition ()
template<typename T >
std::enable_if<!HasOnDefinition< T >::value, void >::type CallOnDefinition ()
bool replace (std::string &str, const std::string &from, const std::string &to)
std::string replace_back (std::string roottype, std::vector< std::pair< std::string, std::string >> &orderedtypesdict)
Variables
rclcpp::Node::SharedPtr globalNh_
Typedef Documentation
DEFAULT_TRANSITION_TYPES
typedef boost::mpl::list<SUCCESS, ABORT, CANCEL, CONTINUELOOP, ENDLOOP> smacc::introspection::DEFAULT_TRANSITION_TYPES
Definition at line 223 of file introspection.hpp.
SmaccAllocator
typedef std::allocator<boost::statechart::none> smacc::introspection::SmaccAllocator
Definition at line 52 of file introspection.hpp.
Enumeration Type Documentation
SmaccStateType
enum smacc::introspection::SmaccStateType strong
Enumerator
SUPERSTATE
STATE
SUPERSTATE_ROUTINE
Definition at line 155 of file smacc_state_info.hpp.
 {
   SUPERSTATE = 2,
   STATE = 1,
   SUPERSTATE_ROUTINE = 1
 };
Function Documentation
automaticTransitionTag() [1/2]
template<typename T > std::enable_if<HasAutomaticTransitionTag<T>::value, void>::type smacc::introspection::automaticTransitionTag (std::string & transition_name)
Definition at line 174 of file introspection.hpp.
 {
   transition_name = T::getDefaultTransitionTag();
 }
automaticTransitionTag() [2/2]
template<typename T > std::enable_if<!HasAutomaticTransitionTag<T>::value, void>::type smacc::introspection::automaticTransitionTag (std::string & transition_name)
Definition at line 181 of file introspection.hpp.
 {
   transition_name = "";
 }
automaticTransitionType() [1/2]
template<typename T > std::enable_if<HasAutomaticTransitionType<T>::value, void>::type smacc::introspection::automaticTransitionType (std::string & transition_type)
Definition at line 208 of file introspection.hpp.
 {
   transition_type = T::getDefaultTransitionType();
 }
automaticTransitionType() [2/2]
template<typename T > std::enable_if<!HasAutomaticTransitionType<T>::value, void>::type smacc::introspection::automaticTransitionType (std::string & transition_type)
Definition at line 215 of file introspection.hpp.
 {
   transition_type = demangledTypeName<DEFAULT>();
 }
CallOnDefinition() [1/2]
template<typename T > std::enable_if<HasOnDefinition<T>::value, void>::type smacc::introspection::CallOnDefinition ()
Definition at line 343 of file smacc_state_machine_info.hpp.
 {
   /* something when T has toString ... */
   RCLCPP_INFO_STREAM(
     globalNh_->get_logger(), "EXECUTING ONDEFINITION: " << demangleSymbol(typeid(T).name()));
   T::staticConfigure();
 }
References demangleSymbol(), and globalNh_.
CallOnDefinition() [2/2]
template<typename T > std::enable_if<!HasOnDefinition<T>::value, void>::type smacc::introspection::CallOnDefinition ()
Definition at line 352 of file smacc_state_machine_info.hpp.
 {
   RCLCPP_INFO_STREAM(
     globalNh_->get_logger(),
     "static OnDefinition: dont exist for " << demangleSymbol(typeid(T).name()));
   /* something when T has toString ... */
 }
References demangleSymbol(), and globalNh_.
demangledTypeName()
template<class T > std::string smacc::introspection::demangledTypeName () inline
Definition at line 101 of file introspection.hpp.
 {
   return demangleSymbol(typeid(T).name());
 }
References demangleSymbol().
demangleSymbol() [1/3]
template<typename T > std::string smacc::introspection::demangleSymbol () inline
Definition at line 95 of file introspection.hpp.
 {
   return demangleSymbol(typeid(T).name());
 }
References demangleSymbol().
demangleSymbol() [2/3]
std::string smacc::introspection::demangleSymbol (const char * name) inline
Definition at line 76 of file introspection.hpp.
 {
 #if (__GNUC__ && __cplusplus && __GNUC__ >= 3)
   int status;
   char * res = abi::__cxa_demangle(name, 0, 0, &status);
   if (res)
   {
     const std::string demangled_name(res);
     std::free(res);
     return demangled_name;
   }
   // Demangling failed, fallback to mangled name
   return std::string(name);
 #else
   return std::string(name);
 #endif
 }
demangleSymbol() [3/3]
std::string smacc::introspection::demangleSymbol (const std::string & name) inline
Definition at line 74 of file introspection.hpp.
 { return demangleSymbol(name.c_str()); }
Referenced by smacc::introspection::SmaccStateMachineInfo::assembleSMStructureMessage(), CallOnDefinition(), demangledTypeName(), demangleSymbol(), demangleType(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal(), smacc::ISmaccState::getClassName(), smacc::introspection::SmaccStateInfo::getDemangledFullName(), cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::getEventLabel(), smacc::introspection::SmaccEventInfo::getEventSourceName(), smacc::introspection::SmaccEventInfo::getEventTypeName(), smacc::introspection::TypeInfo::getFromStdTypeInfo(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getFullName(), smacc::ISmaccComponent::getName(), smacc::ISmaccClient::getName(), smacc::ISmaccClientBehavior::getName(), smacc::ISmaccOrthogonal::getName(), smacc::introspection::SmaccEventInfo::getOrthogonalName(), smacc::ISmaccStateMachine::getStateMachineName(), smacc::ISmaccStateMachine::mapBehavior(), smacc::ISmaccStateMachine::notifyOnStateEntryEnd(), smacc::ISmaccStateMachine::notifyOnStateEntryStart(), smacc::ISmaccStateMachine::notifyOnStateExited(), smacc::ISmaccStateMachine::notifyOnStateExitting(), smacc::state_reactors::SrAllEventsGo::onEventNotified(), smacc::state_reactors::SrEventCountdown::onEventNotified(), cl_keyboard::ClKeyboard::postKeyEvent(), cl_keyboard::CbDefaultKeyboardBehavior::postKeyEvent(), smacc::client_bases::SmaccActionClientBase< ActionType >::postResultEvent(), processTransitionAux(), smacc::ISmaccState::requiresClient(), and smacc::ISmaccStateMachine::requiresComponent().
demangleType() [1/2]
std::string smacc::introspection::demangleType (const std::type_info & tinfo) inline
Definition at line 111 of file introspection.hpp.
 {
   return demangleSymbol(tinfo.name());
 }
References demangleSymbol().
demangleType() [2/2]
std::string smacc::introspection::demangleType (const std::type_info * tinfo) inline
Definition at line 106 of file introspection.hpp.
 {
   return demangleSymbol(tinfo->name());
 }
References demangleSymbol().
Referenced by smacc::Orthogonal< TOrthogonal >::createClient(), smacc::SignalDetector::findUpdatableClientsAndComponents(), smacc::SignalDetector::findUpdatableStateElements(), smacc::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), smacc::SignalDetector::pollOnce(), and smacc::SmaccAsyncClientBehavior::waitFutureIfNotFinished().
EventLabel() [1/2]
template<typename T > std::enable_if<HasEventLabel<T>::value, void>::type smacc::introspection::EventLabel (std::string & label)
Definition at line 142 of file introspection.hpp.
 {
   label = T::getEventLabel();
 }
EventLabel() [2/2]
template<typename T > std::enable_if<!HasEventLabel<T>::value, void>::type smacc::introspection::EventLabel (std::string & label)
Definition at line 148 of file introspection.hpp.
 {
   label = "";
 }
getTransitionType()
template<typename TTransition > static std::string smacc::introspection::getTransitionType () static
Definition at line 259 of file introspection.hpp.
 {
   std::string output;
   CheckType<TTransition> op(&output);
   using boost::mpl::_1;
   using wrappedList = typename boost::mpl::transform<DEFAULT_TRANSITION_TYPES, _1>::type;
   boost::mpl::for_each<wrappedList>(op);
   return output;
 }
References generate_debs::type.
optionalNodeHandle() [1/3]
template<class T > auto smacc::introspection::optionalNodeHandle (boost::intrusive_ptr< T > & obj) -> T *
Definition at line 62 of file introspection.hpp.
 {
   //return obj->getNode();
   return obj.get();
 }
optionalNodeHandle() [2/3]
template<class T > auto smacc::introspection::optionalNodeHandle (std::shared_ptr< T > & obj) -> T *
Definition at line 55 of file introspection.hpp.
 {
   //return obj->getNode();
   return obj.get;
 }
Referenced by smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().
optionalNodeHandle() [3/3]
template<class T > auto smacc::introspection::optionalNodeHandle (T * obj) -> T *
Definition at line 69 of file introspection.hpp.
 {
   return obj;
 }
processSubState() [1/2]
template<typename T > disable_if<boost::mpl::is_sequence<T> >::type smacc::introspection::processSubState (std::shared_ptr< SmaccStateInfo > & parentState)
Definition at line 141 of file smacc_state_machine_info.hpp.
 {
   WalkStatesExecutor<T>::walkStates(parentState, false);
 }
References smacc::introspection::WalkStatesExecutor< InitialStateType >::walkStates().
processSubState() [2/2]
template<typename T > enable_if<boost::mpl::is_sequence<T> >::type smacc::introspection::processSubState (std::shared_ptr< SmaccStateInfo > & parentState)
Definition at line 149 of file smacc_state_machine_info.hpp.
 {
   using boost::mpl::_1;
   using wrappedList = typename boost::mpl::transform<T, add_type_wrapper<_1>>::type;
   boost::mpl::for_each<wrappedList>(AddSubState(parentState));
 }
References generate_debs::type.
processTransition() [1/4]
template<typename Ev , typename Dst , typename Tag > void smacc::introspection::processTransition (smacc::Transition< Ev, boost::statechart::deep_history< Dst >, Tag > * , std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 170 of file smacc_state_machine_info.hpp.
 {
   auto transitionTypeInfo = TypeInfo::getTypeInfoFromType<
     smacc::Transition<Ev, boost::statechart::deep_history<Dst>, Tag>>();
   smacc::Transition<Ev, Dst, Tag> * mock = nullptr;
   processTransitionAux(mock, sourceState, true, transitionTypeInfo);
 }
References smacc::introspection::TypeInfo::getTypeInfoFromType(), and processTransitionAux().
Referenced by processTransitions().
processTransition() [2/4]
template<typename Ev , typename Dst , typename Tag > void smacc::introspection::processTransition (smacc::Transition< Ev, Dst, Tag > * t, std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 181 of file smacc_state_machine_info.hpp.
 {
   auto transitionTypeInfo = TypeInfo::getTypeInfoFromType<smacc::Transition<Ev, Dst, Tag>>();
   processTransitionAux(t, sourceState, false, transitionTypeInfo);
 }
References processTransitionAux().
processTransition() [3/4]
template<typename Ev > void smacc::introspection::processTransition (statechart::custom_reaction< Ev > * , std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 323 of file smacc_state_machine_info.hpp.
 {
   // RCLCPP_INFO_STREAM(getLogger(),"GOTCHA");
 }
processTransition() [4/4]
template<typename Ev , typename Dst > void smacc::introspection::processTransition (statechart::transition< Ev, Dst > * , std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 316 of file smacc_state_machine_info.hpp.
 {
   // RCLCPP_INFO_STREAM(getLogger(),"GOTCHA");
 }
processTransitionAux()
template<typename Ev , typename Dst , typename Tag > void smacc::introspection::processTransitionAux (smacc::Transition< Ev, Dst, Tag > * , std::shared_ptr< SmaccStateInfo > & sourceState, bool history, TypeInfo::Ptr & transitionTypeInfo)
Definition at line 189 of file smacc_state_machine_info.hpp.
 {
   RCLCPP_INFO(
     globalNh_->get_logger(), "State %s Walker transition: %s", sourceState->toShortName().c_str(),
     demangleSymbol(typeid(Ev).name()).c_str());
   std::string transitionTag;
   std::string transitionType;
   if (typeid(Tag) != typeid(default_transition_name))
   {
     transitionTag = demangleSymbol<Tag>();
     transitionType = getTransitionType<Tag>();
     RCLCPP_DEBUG_STREAM(globalNh_->get_logger(), "TRANSITION TYPE:" << transitionType);
   }
   else
   {
     transitionTag = "";
     automaticTransitionTag<Ev>(transitionTag);
     automaticTransitionType<Ev>(transitionType);
   }
   RCLCPP_INFO_STREAM(globalNh_->get_logger(), "Transition tag: " << transitionTag);
   if (!sourceState->stateMachine_->containsState<Dst>())
   {
     auto realparentState = sourceState->stateMachine_->getState<typename Dst::TContext>();
     auto siblingnode = sourceState->stateMachine_->createState<Dst>(realparentState);
     // auto siblingnode = sourceState->stateMachine_->createState<Dst>(sourceState->parentState_);
     WalkStatesExecutor<Dst>::walkStates(siblingnode, true);
     sourceState->declareTransition<Ev>(
       siblingnode, transitionTag, transitionType, history, transitionTypeInfo);
   }
   else
   {
     // auto realparentState = sourceState->stateMachine_->getState<typename Dst::TContext>();
     // auto siblingnode = sourceState->stateMachine_->createState<Dst>(realparentState);
     auto siblingnode = sourceState->stateMachine_->getState<Dst>();
     sourceState->declareTransition<Ev>(
       siblingnode, transitionTag, transitionType, history, transitionTypeInfo);
   }
 }
References demangleSymbol(), globalNh_, and smacc::introspection::WalkStatesExecutor< InitialStateType >::walkStates().
Referenced by processTransition().
processTransitions() [1/2]
template<typename T > enable_if<boost::mpl::is_sequence<T> >::type smacc::introspection::processTransitions (std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 160 of file smacc_state_machine_info.hpp.
 {
   RCLCPP_INFO_STREAM(globalNh_->get_logger(), "State %s Walker has transition list");
   using boost::mpl::_1;
   using wrappedList = typename boost::mpl::transform<T, add_type_wrapper<_1>>::type;
   boost::mpl::for_each<wrappedList>(AddTransition(sourceState));
 }
References globalNh_, and generate_debs::type.
processTransitions() [2/2]
template<typename T > disable_if<boost::mpl::is_sequence<T> >::type smacc::introspection::processTransitions (std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 333 of file smacc_state_machine_info.hpp.
 {
   // RCLCPP_INFO_STREAM(getLogger(),"state transition from: " << sourceState->demangledStateName <<
   // " of type: " << demangledTypeName<T>());
   T * dummy = nullptr;
   processTransition(dummy, sourceState);
 }
References processTransition().
replace()
bool smacc::introspection::replace (std::string & str, const std::string & from, const std::string & to)
Definition at line 33 of file string_type_walker.cpp.
 {
   size_t start_pos = str.find(from);
   if (start_pos == std::string::npos) return false;
   str.replace(start_pos, from.length(), to);
   return true;
 }
Referenced by smacc::introspection::TypeInfo::getTypeInfoFromString(), and replace_back().
replace_back()
std::string smacc::introspection::replace_back (std::string roottype, std::vector< std::pair< std::string, std::string >> & orderedtypesdict)
Definition at line 41 of file string_type_walker.cpp.
 {
   while (roottype.find("$") != std::string::npos)
   {
     for (auto & t : orderedtypesdict)
     {
       auto & tkey = t.first;
       auto & tval = t.second;
       replace(roottype, tkey, tval);
     }
   }
   return roottype;
   //   def replace_back(roottype, typesdict):
   //     # replace back
   //     while "$" in roottype:
   //         #print roottype
   //         for tkey in typesdict:
   //             tval = typesdict[tkey]
   //             roottype = roottype.replace(tkey, tval)
   //     return roottype
 }
References replace().
Referenced by smacc::introspection::TypeInfo::getTypeInfoFromString().
transitionInfoToMsg()
void smacc::introspection::transitionInfoToMsg (const SmaccTransitionInfo & transition, smacc_msgs::msg::SmaccTransition & transitionMsg)
Definition at line 24 of file reflection.cpp.
 {
   transitionMsg.index = transition.index;
   transitionMsg.event.event_type = transition.eventInfo->getEventTypeName();
   transitionMsg.source_state_name = transition.sourceState->demangledStateName;
   transitionMsg.transition_name = transition.transitionTag;
   transitionMsg.transition_type = transition.transitionType;
   transitionMsg.event.event_source = transition.eventInfo->getEventSourceName();
   transitionMsg.event.event_object_tag = transition.eventInfo->getOrthogonalName();
   transitionMsg.event.label = transition.eventInfo->label;
   transitionMsg.history_node = transition.historyNode;
   if (transition.historyNode)
   {
     if (transition.destinyState->parentState_ != nullptr)
     {
       transitionMsg.destiny_state_name = transition.destinyState->parentState_->demangledStateName;
     }
     else
     {
       transitionMsg.destiny_state_name = "";
     }
   }
   else
   {
     transitionMsg.destiny_state_name = transition.destinyState->demangledStateName;
   }
 }
References smacc::introspection::SmaccTransitionInfo::destinyState, smacc::introspection::SmaccTransitionInfo::eventInfo, smacc::introspection::SmaccTransitionInfo::historyNode, smacc::introspection::SmaccTransitionInfo::index, smacc::introspection::SmaccTransitionInfo::sourceState, smacc::introspection::SmaccTransitionInfo::transitionTag, and smacc::introspection::SmaccTransitionInfo::transitionType.
Referenced by smacc::introspection::SmaccStateMachineInfo::assembleSMStructureMessage(), and smacc::ISmaccStateMachine::publishTransition().
Variable Documentation
globalNh_
rclcpp::Node::SharedPtr smacc::introspection::globalNh_
Definition at line 22 of file reflection.cpp.
Referenced by CallOnDefinition(), smacc::introspection::TypeInfo::getTypeInfoFromString(), smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::initiate_impl(), processTransitionAux(), processTransitions(), smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::static_createStateReactor(), and smacc::SmaccState< MostDerived, Context, InnerInitial, historyMode >::static_createStateReactor_aux().