SMACC2: smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType > Struct Template Reference
smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType > Struct Template Reference
State Machine.
#include <smacc_state_machine_base.hpp>
Public Member Functions
SmaccStateMachineBase (my_context ctx, SignalDetector *signalDetector)
virtual ~SmaccStateMachineBase ()
void reset () override
void stop () override
void eStop () override
void initiate_impl () override
Public Member Functions inherited from smacc::ISmaccStateMachine
ISmaccStateMachine (std::string stateMachineName, SignalDetector *signalDetector)
virtual ~ISmaccStateMachine ()
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
const std::map< std::string, std::shared_ptr< smacc::ISmaccOrthogonal > > & getOrthogonals () const
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename EventType >
void postEvent (EventType *ev, EventLifeTime evlifetime=EventLifeTime::ABSOLUTE)
template<typename EventType >
void postEvent (EventLifeTime evlifetime=EventLifeTime::ABSOLUTE)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename StateField , typename BehaviorType >
void mapBehavior ()
std::string getStateMachineName ()
void state_machine_visualization ()
std::shared_ptr< SmaccStateInfo > getCurrentStateInfo ()
void publishTransition (const SmaccTransitionInfo &transitionInfo)
virtual void onInitialize ()
this function should be implemented by the user to create the orthogonals
void getTransitionLogHistory (const std::shared_ptr< rmw_request_id_t > request_header, const std::shared_ptr< smacc_msgs::srv::SmaccGetTransitionHistory::Request > req, std::shared_ptr< smacc_msgs::srv::SmaccGetTransitionHistory::Response > res)
template<typename TSmaccSignal , typename TMemberFunctionPrototype , typename TSmaccObjectType >
boost::signals2::connection createSignalConnection (TSmaccSignal &signal, TMemberFunctionPrototype callback, TSmaccObjectType *object)
template<typename StateType >
void notifyOnStateEntryStart (StateType *state)
template<typename StateType >
void notifyOnStateEntryEnd (StateType *state)
template<typename StateType >
void notifyOnRuntimeConfigured (StateType *state)
template<typename StateType >
void notifyOnStateExitting (StateType *state)
template<typename StateType >
void notifyOnStateExited (StateType *state)
template<typename StateType >
void notifyOnRuntimeConfigurationFinished (StateType *state)
unsigned long getCurrentStateCounter () const
ISmaccState * getCurrentState () const
const SmaccStateMachineInfo & getStateMachineInfo ()
template<typename InitialStateType >
void buildStateMachineInfo ()
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Additional Inherited Members
Protected Member Functions inherited from smacc::ISmaccStateMachine
void checkStateMachineConsistence ()
void initializeROS (std::string smshortname)
void onInitialized ()
template<typename TOrthogonal >
void createOrthogonal ()
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
template<typename T >
bool param (std::string param_name, T &param_val, const T &default_val)
Protected Attributes inherited from smacc::ISmaccStateMachine
rclcpp::Node::SharedPtr nh_
rclcpp::TimerBase::SharedPtr timer_
rclcpp::Publisher< smacc_msgs::msg::SmaccStateMachine >::SharedPtr stateMachinePub_
rclcpp::Publisher< smacc_msgs::msg::SmaccStatus >::SharedPtr stateMachineStatusPub_
rclcpp::Publisher< smacc_msgs::msg::SmaccTransitionLogEntry >::SharedPtr transitionLogPub_
rclcpp::Service< smacc_msgs::srv::SmaccGetTransitionHistory >::SharedPtr transitionHistoryService_
ISmaccState * currentState_
std::shared_ptr< SmaccStateInfo > currentStateInfo_
smacc_msgs::msg::SmaccStatus status_msg_
std::map< std::string, std::shared_ptr< smacc::ISmaccOrthogonal > > orthogonals_
Detailed Description
template<typename DerivedStateMachine, typename InitialStateType>
struct smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >
State Machine.
Definition at line 30 of file smacc_state_machine_base.hpp.
Constructor & Destructor Documentation
SmaccStateMachineBase()
template<typename DerivedStateMachine , typename InitialStateType > smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::SmaccStateMachineBase (my_context ctx, SignalDetector * signalDetector) inline
Definition at line 36 of file smacc_state_machine_base.hpp.
   : ISmaccStateMachine(smacc::utils::cleanShortTypeName<DerivedStateMachine>(), signalDetector),
     sc::asynchronous_state_machine<
       DerivedStateMachine, InitialStateType, SmaccFifoScheduler, SmaccAllocator>(ctx)
   {
   }
~SmaccStateMachineBase()
template<typename DerivedStateMachine , typename InitialStateType > virtual smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::~SmaccStateMachineBase () inline virtual
Definition at line 43 of file smacc_state_machine_base.hpp.
   {
     //updateCurrentState<InitialStateType>(false);
   }
Member Function Documentation
eStop()
template<typename DerivedStateMachine , typename InitialStateType > void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::eStop () inline override virtual
Reimplemented from smacc::ISmaccStateMachine.
Definition at line 61 of file smacc_state_machine_base.hpp.
   {
     ISmaccStateMachine::eStop();
     this->terminate();
   }
References smacc::ISmaccStateMachine::eStop().
initiate_impl()
template<typename DerivedStateMachine , typename InitialStateType > void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::initiate_impl () inline override
Definition at line 67 of file smacc_state_machine_base.hpp.
   {
     globalNh_ = this->getNode();
     // this is before because this creates orthogonals
     this->onInitialize();
     RCLCPP_INFO(getLogger(), "[SmaccStateMachine] Introspecting state machine via typeWalker");
     this->buildStateMachineInfo<InitialStateType>();
     RCLCPP_INFO(getLogger(), "[SmaccStateMachine] initiate_impl");
     auto shortname = smacc::utils::cleanShortTypeName(typeid(DerivedStateMachine));
     this->initializeROS(shortname);
     RCLCPP_INFO(getLogger(), "[SmaccStateMachine] Initializing ROS communication mechanisms");
     this->onInitialized();
     RCLCPP_INFO(getLogger(), "[SmaccStateMachine] Initializing state machine");
     sc::state_machine<DerivedStateMachine, InitialStateType, SmaccAllocator>::initiate();
   }
References smacc::utils::cleanShortTypeName(), smacc::ISmaccStateMachine::getLogger(), smacc::ISmaccStateMachine::getNode(), smacc::introspection::globalNh_, smacc::ISmaccStateMachine::initializeROS(), smacc::ISmaccStateMachine::onInitialize(), and smacc::ISmaccStateMachine::onInitialized().
reset()
template<typename DerivedStateMachine , typename InitialStateType > void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::reset () inline override virtual
Reimplemented from smacc::ISmaccStateMachine.
Definition at line 48 of file smacc_state_machine_base.hpp.
   {
     ISmaccStateMachine::reset();
     this->terminate();
     smacc::run<DerivedStateMachine>();
   }
References smacc::ISmaccStateMachine::reset().
stop()
template<typename DerivedStateMachine , typename InitialStateType > void smacc::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::stop () inline override virtual
Reimplemented from smacc::ISmaccStateMachine.
Definition at line 55 of file smacc_state_machine_base.hpp.
   {
     ISmaccStateMachine::stop();
     this->terminate();
   }
References smacc::ISmaccStateMachine::stop().
The documentation for this struct was generated from the following file:
smacc2/include/smacc/smacc_state_machine_base.hpp