SMACC2: smacc::introspection::WalkStatesExecutor< InitialStateType > Struct Template Reference
smacc::introspection::WalkStatesExecutor< InitialStateType > Struct Template Reference
#include <smacc_state_machine_info.hpp>
Static Public Member Functions
static void walkStates (std::shared_ptr< SmaccStateInfo > &currentState, bool rootInitialNode)
Detailed Description
template<typename InitialStateType>
struct smacc::introspection::WalkStatesExecutor< InitialStateType >
Definition at line 125 of file smacc_state_machine_info.hpp.
Member Function Documentation
walkStates()
template<typename InitialStateType > void smacc::introspection::WalkStatesExecutor< InitialStateType >::walkStates (std::shared_ptr< SmaccStateInfo > & currentState, bool rootInitialNode) static
Definition at line 422 of file smacc_state_machine_info.hpp.
 {
   //rclcpp::Duration(1).sleep();
   auto currentname = demangledTypeName<InitialStateType>();
   std::shared_ptr<SmaccStateInfo> targetState;
   if (!rootInitialNode)
   {
     if (parentState->stateMachine_->containsState<InitialStateType>())
     {
       // it already exist: break;
       return;
     }
     targetState = parentState->createChildState<InitialStateType>();
   }
   else
   {
     targetState = parentState;
   }
   CallOnDefinition<InitialStateType>();
   typedef
     typename std::remove_pointer<decltype(InitialStateType::smacc_inner_type)>::type InnerType;
   processSubState<InnerType>(targetState);
   // -------------------- REACTIONS --------------------
   typedef typename InitialStateType::reactions reactions;
   // RCLCPP_INFO_STREAM(getLogger(),"state machine initial state reactions: "
   // << demangledTypeName<reactions>());
   processTransitions<reactions>(targetState);
 }
References generate_debs::type.
Referenced by smacc::introspection::SmaccStateMachineInfo::buildStateMachineInfo(), smacc::introspection::AddSubState::operator()(), smacc::introspection::processSubState(), and smacc::introspection::processTransitionAux().
The documentation for this struct was generated from the following file:
smacc2/include/smacc/introspection/smacc_state_machine_info.hpp