SMACC2: sm_branching::State2c Struct Reference
sm_branching::State2c Struct Reference
#include <st_state_2c.hpp>
Public Types
typedef mpl::list< Transition< EvTimer< CbTimerCountdownOnce, OrTimer >, State3c, SUCCESS > > reactions
Public Types inherited from smacc::SmaccState< State2c, SmBranching >
typedef SmBranching TContext
typedef Context::inner_context_type context_type
typedef context_type::state_iterator state_iterator
typedef mpl::list<> LastDeepState
typedef base_type::outermost_context_base_type outermost_context_base_type
typedef base_type::inner_context_ptr_type inner_context_ptr_type
typedef base_type::context_ptr_type context_ptr_type
typedef base_type::inner_initial_list inner_initial_list
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void onExit ()
Public Member Functions inherited from smacc::SmaccState< State2c, SmBranching >
SmaccState ()=delete
SmaccState (my_context ctx)
virtual ~SmaccState ()
const smacc::introspection::SmaccStateInfo * getStateInfo ()
std::string getFullName ()
std::string getShortName ()
virtual ISmaccState * getParentState ()
void exit ()
void runtimeConfigure ()
void onEntry ()
void onExit ()
bool getGlobalSMData (std::string name, T &ret)
void setGlobalSMData (std::string name, T value)
void requiresComponent (SmaccComponentType *&storage)
virtual ISmaccStateMachine & getStateMachine ()
void checkWhileLoopConditionAndThrowEvent (bool(MostDerived::*conditionFn)())
void throwSequenceFinishedEvent ()
Public Member Functions inherited from smacc::ISmaccState
ISmaccState * getParentState ()
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
void param (std::string param_name)
template<typename T >
void param (std::string param_name, T default_value)
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Static Public Member Functions
static void staticConfigure ()
Static Public Member Functions inherited from smacc::SmaccState< State2c, SmBranching >
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh, State2c &)> initializationFunction)
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh)> initializationFunction)
static void configure_orthogonal (Args &&... args)
static std::shared_ptr< smacc::introspection::StateReactorHandler > static_createStateReactor (TArgs... args)
static std::shared_ptr< smacc::introspection::EventGeneratorHandler > static_createEventGenerator (TUArgs... args)
static std::shared_ptr< smacc::introspection::StateReactorHandler > static_createStateReactor_aux (TUArgs... args)
static void initial_deep_construct (outermost_context_base_type &outermostContextBase)
static void deep_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
static inner_context_ptr_type shallow_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
Additional Inherited Members
Public Attributes inherited from smacc::SmaccState< State2c, SmBranching >
bool finishStateThrown
mpl::list<> * smacc_inner_type
Public Attributes inherited from smacc::ISmaccState
rclcpp::Node::SharedPtr stateNode_
Protected Attributes inherited from smacc::ISmaccState
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc::SmaccEventGenerator > > eventGenerators_
rclcpp::Node::SharedPtr contextNh
ISmaccState * parentState_
const smacc::introspection::SmaccStateInfo * stateInfo_
Detailed Description
Definition at line 22 of file st_state_2c.hpp.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvTimer<CbTimerCountdownOnce, OrTimer>, State3c, SUCCESS> > sm_branching::State2c::reactions
Definition at line 32 of file st_state_2c.hpp.
Member Function Documentation
onEntry()
void sm_branching::State2c::onEntry () inline
Definition at line 43 of file st_state_2c.hpp.
 { RCLCPP_INFO(getLogger(), "On Entry!"); }
References smacc::ISmaccState::getLogger().
onExit()
void sm_branching::State2c::onExit () inline
Definition at line 45 of file st_state_2c.hpp.
 { RCLCPP_INFO(getLogger(), "On Exit!"); }
References smacc::ISmaccState::getLogger().
runtimeConfigure()
void sm_branching::State2c::runtimeConfigure () inline
Definition at line 41 of file st_state_2c.hpp.
 { RCLCPP_INFO(getLogger(), "Entering State2"); }
References smacc::ISmaccState::getLogger().
staticConfigure()
static void sm_branching::State2c::staticConfigure () inline static
Definition at line 35 of file st_state_2c.hpp.
   {
     configure_orthogonal<OrTimer, CbTimerCountdownOnce>(
       5);  // EvTimer triggers once at 10 client ticks
   }
The documentation for this struct was generated from the following file:
smacc_sm_reference_library/sm_branching/include/sm_branching/states/st_state_2c.hpp