SMACC2: smacc2::event_generators::EgConditionalGenerator Class Reference
smacc2::event_generators::EgConditionalGenerator Class Reference
#include <eg_conditional_generator.hpp>
Public Member Functions
EgConditionalGenerator (ConditionalGeneratorMode mode, std::function< bool()> updatePredicate=nullptr)
virtual ~EgConditionalGenerator ()
void onEntry () override
template<typename TState , typename TSource >
void onStateAllocation ()
virtual void update () override
void setPredicateFunction (std::function< bool()> updatePredicate)
Public Member Functions inherited from smacc2::SmaccEventGenerator
SmaccEventGenerator ()
virtual ~SmaccEventGenerator ()
template<typename TState , typename TSource >
void onStateAllocation ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
void initialize (ISmaccState *ownerState)
virtual void onInitialized ()
Public Member Functions inherited from smacc2::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (rclcpp::Duration duration)
void executeUpdate (rclcpp::Node::SharedPtr node)
void setUpdatePeriod (rclcpp::Duration duration)
Public Attributes
ConditionalGeneratorMode mode_
Private Member Functions
void checkPredicateAndPost ()
Private Attributes
std::function< void()> postEventTrue
std::function< void()> postEventFalse
std::function< bool()> updatePredicate_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccUpdatable
Detailed Description
Definition at line 44 of file eg_conditional_generator.hpp.
Constructor & Destructor Documentation
EgConditionalGenerator()
smacc2::event_generators::EgConditionalGenerator::EgConditionalGenerator (ConditionalGeneratorMode mode, std::function< bool()> updatePredicate = nullptr)
Definition at line 21 of file eg_conditional_generator.cpp.
: mode_(mode), updatePredicate_(updatePredicate)
{
}
~EgConditionalGenerator()
smacc2::event_generators::EgConditionalGenerator::~EgConditionalGenerator () virtual
Definition at line 27 of file eg_conditional_generator.cpp.
{}
Member Function Documentation
checkPredicateAndPost()
void smacc2::event_generators::EgConditionalGenerator::checkPredicateAndPost () private
Definition at line 29 of file eg_conditional_generator.cpp.
{
  if (this->updatePredicate_())
  {
    this->postEventTrue();
  }
  else
  {
    this->postEventFalse();
  }
}
References postEventFalse, postEventTrue, and updatePredicate_.
Referenced by onEntry(), and update().
onEntry()
void smacc2::event_generators::EgConditionalGenerator::onEntry () override virtual
Reimplemented from smacc2::SmaccEventGenerator.
Definition at line 41 of file eg_conditional_generator.cpp.
{
  if (mode_ == ConditionalGeneratorMode::ONE_SHOT)
  {
    this->checkPredicateAndPost();
  }
}
References checkPredicateAndPost(), mode_, and smacc2::event_generators::ONE_SHOT.
onStateAllocation()
template<typename TState , typename TSource > void smacc2::event_generators::EgConditionalGenerator::onStateAllocation () inline
Definition at line 54 of file eg_conditional_generator.hpp.
  {
    this->postEventTrue = [this]() { this->postEvent<EvTrue<TSource, TState>>(); };
    this->postEventFalse = [this]() { this->postEvent<EvFalse<TSource, TState>>(); };
  }
References smacc2::SmaccEventGenerator::postEvent(), postEventFalse, and postEventTrue.
setPredicateFunction()
void smacc2::event_generators::EgConditionalGenerator::setPredicateFunction (std::function< bool()> updatePredicate)
Definition at line 57 of file eg_conditional_generator.cpp.
{
  updatePredicate_ = updatePredicate;
}
References updatePredicate_.
update()
void smacc2::event_generators::EgConditionalGenerator::update () override virtual
Implements smacc2::ISmaccUpdatable.
Definition at line 49 of file eg_conditional_generator.cpp.
{
  if (mode_ == ConditionalGeneratorMode::ON_UPDATE)
  {
    this->checkPredicateAndPost();
  }
}
References checkPredicateAndPost(), mode_, and smacc2::event_generators::ON_UPDATE.
Member Data Documentation
mode_
ConditionalGeneratorMode smacc2::event_generators::EgConditionalGenerator::mode_
Definition at line 61 of file eg_conditional_generator.hpp.
Referenced by onEntry(), and update().
postEventFalse
std::function<void()> smacc2::event_generators::EgConditionalGenerator::postEventFalse private
Definition at line 68 of file eg_conditional_generator.hpp.
Referenced by checkPredicateAndPost(), and onStateAllocation().
postEventTrue
std::function<void()> smacc2::event_generators::EgConditionalGenerator::postEventTrue private
Definition at line 67 of file eg_conditional_generator.hpp.
Referenced by checkPredicateAndPost(), and onStateAllocation().
updatePredicate_
std::function<bool()> smacc2::event_generators::EgConditionalGenerator::updatePredicate_ private
Definition at line 69 of file eg_conditional_generator.hpp.
Referenced by checkPredicateAndPost(), and setPredicateFunction().
The documentation for this class was generated from the following files:
smacc2_event_generator_library/eg_conditional_generator/include/eg_conditional_generator/eg_conditional_generator.hpp
smacc2_event_generator_library/eg_conditional_generator/src/eg_conditional_generator/eg_conditional_generator.cpp