SMACC2: cl_nitrosz::CbWaitNav2Nodes Class Reference
cl_nitrosz::CbWaitNav2Nodes Class Reference
#include <cb_wait_nitros_nodes.hpp>
Public Member Functions
CbWaitNav2Nodes (std::string topicname, std::vector< Nav2Nodes > waitNodes={ Nav2Nodes::PlannerServer, Nav2Nodes::ControllerServer, Nav2Nodes::BtNavigator})
CbWaitNav2Nodes (std::vector< Nav2Nodes > waitNodes={ Nav2Nodes::PlannerServer, Nav2Nodes::ControllerServer, Nav2Nodes::BtNavigator})
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onExit ()
Private Member Functions
void onMessageReceived (const bond::msg::Status &msg)
Private Attributes
std::string topicname_
rclcpp::Subscription< bond::msg::Status >::SharedPtr sub_
std::map< Nav2Nodes, bool > receivedAliveMsg_
std::vector< Nav2Nodes > waitNodes_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 43 of file cb_wait_nitros_nodes.hpp.
Constructor & Destructor Documentation
CbWaitNav2Nodes() [1/2]
cl_nitrosz::CbWaitNav2Nodes::CbWaitNav2Nodes (std::string topicname, std::vector< Nav2Nodes > waitNodes = { Nav2Nodes::PlannerServer, Nav2Nodes::ControllerServer, Nav2Nodes::BtNavigator})
Definition at line 31 of file cb_wait_nitros_nodes.cpp.
: topicname_(topic), waitNodes_(waitNodes)
{
}
CbWaitNav2Nodes() [2/2]
cl_nitrosz::CbWaitNav2Nodes::CbWaitNav2Nodes (std::vector< Nav2Nodes > waitNodes = { Nav2Nodes::PlannerServer, Nav2Nodes::ControllerServer, Nav2Nodes::BtNavigator})
Definition at line 26 of file cb_wait_nitros_nodes.cpp.
: CbWaitNav2Nodes("/bond", waitNodes)
{
}
Member Function Documentation
onEntry()
void cl_nitrosz::CbWaitNav2Nodes::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 80 of file cb_wait_nitros_nodes.cpp.
{
  std::stringstream ss;
  for (auto v : waitNodes_)
  {
    receivedAliveMsg_[v] = false;
    ss << "[CbWaitNav2Nodes] - " << toString(v) << ": waiting" << std::endl;
  }
  RCLCPP_INFO(getLogger(), ss.str().c_str());
  //rclcpp::SensorDataQoS qos;
  rclcpp::SubscriptionOptions sub_option;
  sub_ = getNode()->create_subscription<bond::msg::Status>(
    topicname_, 20, std::bind(&CbWaitNav2Nodes::onMessageReceived, this, std::placeholders::_1),
    sub_option);
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), onMessageReceived(), receivedAliveMsg_, sub_, topicname_, cl_nitrosz::toString(), and waitNodes_.
onMessageReceived()
void cl_nitrosz::CbWaitNav2Nodes::onMessageReceived (const bond::msg::Status & msg) private
Definition at line 36 of file cb_wait_nitros_nodes.cpp.
{
  auto value = fromString(msg.id);
  bool updated = false;
  // RCLCPP_INFO(getLogger(), "[CbWaitNav2Nodes] received '%s'", msg.id.c_str());
  if (receivedAliveMsg_.count(value) && !receivedAliveMsg_[value])
  {
    RCLCPP_INFO(getLogger(), "[CbWaitNav2Nodes] '%s' alive received", msg.id.c_str());
    receivedAliveMsg_[value] = true;
    updated = true;
  }
  if (updated)
  {
    bool success = true;
    std::stringstream ss;
    for (auto & pair : receivedAliveMsg_)
    {
      if (!pair.second)
      {
        success = false;
      }
      ss << "- " << toString(pair.first) << ": " << (pair.second ? "ALIVE" : "WAITING")
         << std::endl;
    }
    RCLCPP_INFO_STREAM(
      getLogger(), "[CbWaitNav2Nodes] waiting nodes status:" << std::endl
                                                             << ss.str().c_str());
    if (success)
    {
      RCLCPP_INFO(getLogger(), "[CbWaitNav2Nodes] success event");
      this->postSuccessEvent();
      sub_ = nullptr;
    }
    else
    {
      RCLCPP_INFO(getLogger(), "[CbWaitNav2Nodes] still missing nodes");
    }
  }
}
References cl_nitrosz::fromString(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), receivedAliveMsg_, sub_, and cl_nitrosz::toString().
Referenced by onEntry().
Member Data Documentation
receivedAliveMsg_
std::map<Nav2Nodes, bool> cl_nitrosz::CbWaitNav2Nodes::receivedAliveMsg_ private
Definition at line 63 of file cb_wait_nitros_nodes.hpp.
Referenced by onEntry(), and onMessageReceived().
sub_
rclcpp::Subscription<bond::msg::Status>::SharedPtr cl_nitrosz::CbWaitNav2Nodes::sub_ private
Definition at line 62 of file cb_wait_nitros_nodes.hpp.
Referenced by onEntry(), and onMessageReceived().
topicname_
std::string cl_nitrosz::CbWaitNav2Nodes::topicname_ private
Definition at line 60 of file cb_wait_nitros_nodes.hpp.
Referenced by onEntry().
waitNodes_
std::vector<Nav2Nodes> cl_nitrosz::CbWaitNav2Nodes::waitNodes_ private
Definition at line 65 of file cb_wait_nitros_nodes.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/nitrosz_client/nitrosz_client/include/nitrosz_client/client_behaviors/cb_wait_nitros_nodes.hpp
smacc2_client_library/nitrosz_client/nitrosz_client/src/nitrosz_client/client_behaviors/cb_wait_nitros_nodes.cpp