SMACC2: cl_nav2z::CbNav2ZClientBehaviorBase Class Reference
cl_nav2z::CbNav2ZClientBehaviorBase Class Reference
#include <cb_nav2z_client_behavior_base.hpp>
Public Member Functions
virtual ~CbNav2ZClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
Protected Member Functions
void sendGoal (ClNav2Z::Goal &goal)
void cancelGoal ()
bool isOwnActionResponse (const ClNav2Z::WrappedResult &)
virtual void onNavigationResult (const ClNav2Z::WrappedResult &)
virtual void onNavigationActionSuccess (const ClNav2Z::WrappedResult &)
virtual void onNavigationActionAbort (const ClNav2Z::WrappedResult &)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Attributes
cl_nav2z::ClNav2Z * nav2zClient_
cl_nav2z::ClNav2Z::SmaccNavigateResultSignal::SharedPtr navigationCallback_
rclcpp_action::ResultCode navigationResult_
std::shared_future< std::shared_ptr< rclcpp_action::ClientGoalHandle< nav2_msgs::action::NavigateToPose > > > goalHandleFuture_
Detailed Description
Definition at line 28 of file cb_nav2z_client_behavior_base.hpp.
Constructor & Destructor Documentation
~CbNav2ZClientBehaviorBase()
cl_nav2z::CbNav2ZClientBehaviorBase::~CbNav2ZClientBehaviorBase () virtual
Definition at line 24 of file cb_nav2z_client_behavior_base.cpp.
{}
Member Function Documentation
cancelGoal()
void cl_nav2z::CbNav2ZClientBehaviorBase::cancelGoal () protected
Definition at line 43 of file cb_nav2z_client_behavior_base.cpp.
{ this->nav2zClient_->cancelGoal(); }
References smacc2::client_bases::SmaccActionClientBase< ActionType >::cancelGoal(), and nav2zClient_.
isOwnActionResponse()
bool cl_nav2z::CbNav2ZClientBehaviorBase::isOwnActionResponse (const ClNav2Z::WrappedResult & r) protected
Definition at line 45 of file cb_nav2z_client_behavior_base.cpp.
{
  auto name = getName();
  if (isShutdownRequested())
  {
    RCLCPP_ERROR(
      getLogger(), "[%s] Propagating action client signal skipped. the behavior is shutting down",
      name.c_str());
    return false;
  }
  if (!goalHandleFuture_.valid())
  {
    RCLCPP_ERROR(
      this->getLogger(), "[%s]Propagating action client signal, our goal handle is not valid",
      name.c_str());
    return false;
  }
  auto goalHandle = goalHandleFuture_.get();
  auto goal_uuid_ = goalHandle->get_goal_id();
  if (r.goal_id != goal_uuid_)
  {
    RCLCPP_ERROR(
      getLogger(),
      "[%s] Received a failure event from an action server with a different goal_uuid: %s, "
      "expected: %s",
      smacc2::demangleType(typeid(*this)).c_str(), rclcpp_action::to_string(r.goal_id).c_str(),
      rclcpp_action::to_string(goal_uuid_).c_str());
    return false;
  }
  return true;
}
References smacc2::introspection::demangleType(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), goalHandleFuture_, and smacc2::SmaccAsyncClientBehavior::isShutdownRequested().
onNavigationActionAbort()
void cl_nav2z::CbNav2ZClientBehaviorBase::onNavigationActionAbort (const ClNav2Z::WrappedResult & r) protected virtual
Definition at line 112 of file cb_nav2z_client_behavior_base.cpp.
{
  // if (!isOwnActionResponse(r))
  // {
  //   RCLCPP_WARN(
  //     getLogger(), "[%s] Propagating success event skipped. Action response is not ours.",
  //     getName().c_str());
  //   return;
  // }
  navigationResult_ = r.code;
  auto name = getName();
  RCLCPP_INFO(getLogger(), "[%s] Propagating failure event from action server", name.c_str());
  this->postFailureEvent();
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), navigationResult_, and smacc2::SmaccAsyncClientBehavior::postFailureEvent().
Referenced by onNavigationResult().
onNavigationActionSuccess()
void cl_nav2z::CbNav2ZClientBehaviorBase::onNavigationActionSuccess (const ClNav2Z::WrappedResult & r) protected virtual
Reimplemented in cl_nav2z::CbNavigateNextWaypointUntilReached.
Definition at line 96 of file cb_nav2z_client_behavior_base.cpp.
{
  // if (!isOwnActionResponse(r))
  // {
  //   RCLCPP_WARN(
  //     getLogger(), "[%s] Propagating success event skipped. Action response is not ours.",
  //     getName().c_str());
  //   return;
  // }
  navigationResult_ = r.code;
  RCLCPP_INFO(getLogger(), "[%s] Propagating success event from action server", getName().c_str());
  this->postSuccessEvent();
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), navigationResult_, and smacc2::SmaccAsyncClientBehavior::postSuccessEvent().
Referenced by onNavigationResult().
onNavigationResult()
void cl_nav2z::CbNav2ZClientBehaviorBase::onNavigationResult (const ClNav2Z::WrappedResult & r) protected virtual
Definition at line 81 of file cb_nav2z_client_behavior_base.cpp.
{
  RCLCPP_DEBUG(
    getLogger(), "[%s] Received result event from action server, result code", getName().c_str());
  if (r.code == rclcpp_action::ResultCode::SUCCEEDED)
  {
    this->onNavigationActionSuccess(r);
  }
  else
  {
    this->onNavigationActionAbort(r);
  }
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), onNavigationActionAbort(), and onNavigationActionSuccess().
Referenced by cl_nav2z::CbNavigateNextWaypoint::onEntry(), and sendGoal().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_nav2z::CbNav2ZClientBehaviorBase::onOrthogonalAllocation () inline
Definition at line 34 of file cb_nav2z_client_behavior_base.hpp.
  {
    this->requiresClient(nav2zClient_);
    smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
  }
References nav2zClient_, smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation(), and smacc2::ISmaccClientBehavior::requiresClient().
sendGoal()
void cl_nav2z::CbNav2ZClientBehaviorBase::sendGoal (ClNav2Z::Goal & goal) protected
Definition at line 26 of file cb_nav2z_client_behavior_base.cpp.
{
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] Creating sending goal callback signal.");
  this->navigationCallback_ = std::make_shared<cl_nav2z::ClNav2Z::SmaccNavigateResultSignal>();
  this->getStateMachine()->createSignalConnection(
    *navigationCallback_, &CbNav2ZClientBehaviorBase::onNavigationResult, this);
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] Sending goal");
  goalHandleFuture_ = this->nav2zClient_->sendGoal(goal, navigationCallback_);
  RCLCPP_INFO_STREAM(
    getLogger(), "[" << getName() << "] Goal set, future valid: " << goalHandleFuture_.valid());
  // this->goal_uuid_ = gh.get_goal_id () ;
}
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::getStateMachine(), goalHandleFuture_, nav2zClient_, navigationCallback_, onNavigationResult(), and smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
Referenced by cl_nav2z::CbNavigateGlobalPosition::execute(), cl_nav2z::CbAbsoluteRotate::onEntry(), cl_nav2z::CbNavigateBackwards::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbRotate::onEntry(), and cl_nav2z::CbUndoPathBackwards::onEntry().
Member Data Documentation
goalHandleFuture_
std::shared_future< std::shared_ptr<rclcpp_action::ClientGoalHandle<nav2_msgs::action::NavigateToPose> > > cl_nav2z::CbNav2ZClientBehaviorBase::goalHandleFuture_ protected
Definition at line 58 of file cb_nav2z_client_behavior_base.hpp.
Referenced by isOwnActionResponse(), and sendGoal().
nav2zClient_
cl_nav2z::ClNav2Z* cl_nav2z::CbNav2ZClientBehaviorBase::nav2zClient_ protected
Definition at line 51 of file cb_nav2z_client_behavior_base.hpp.
Referenced by cancelGoal(), cl_nav2z::CbNavigateGlobalPosition::execute(), cl_nav2z::CbAbsoluteRotate::onEntry(), cl_nav2z::CbNavigateBackwards::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbNavigateGlobalPosition::onEntry(), cl_nav2z::CbNavigateNamedWaypoint::onEntry(), cl_nav2z::CbNavigateNextWaypoint::onEntry(), cl_nav2z::CbRotate::onEntry(), cl_nav2z::CbUndoPathBackwards::onEntry(), cl_nav2z::CbUndoPathBackwards::onExit(), cl_nav2z::CbNavigateNextWaypointUntilReached::onNavigationActionSuccess(), onOrthogonalAllocation(), cl_nav2z::CbNavigateNextWaypointUntilReached::onOrthogonalAllocation(), and sendGoal().
navigationCallback_
cl_nav2z::ClNav2Z::SmaccNavigateResultSignal::SharedPtr cl_nav2z::CbNav2ZClientBehaviorBase::navigationCallback_ protected
Definition at line 52 of file cb_nav2z_client_behavior_base.hpp.
Referenced by sendGoal().
navigationResult_
rclcpp_action::ResultCode cl_nav2z::CbNav2ZClientBehaviorBase::navigationResult_ protected
Definition at line 55 of file cb_nav2z_client_behavior_base.hpp.
Referenced by cl_nav2z::CbUndoPathBackwards::onExit(), onNavigationActionAbort(), onNavigationActionSuccess(), and cl_nav2z::CbNavigateNextWaypointUntilReached::onNavigationActionSuccess().
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/client_behaviors/cb_nav2z_client_behavior_base.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/client_behaviors/cb_nav2z_client_behavior_base.cpp