SMACC2: cl_nitrosz::CpPlannerSwitcher Class Reference
cl_nitrosz::CpPlannerSwitcher Class Reference
#include <cp_planner_switcher.hpp>
Public Member Functions
CpPlannerSwitcher ()
void onInitialize () override
void setDesiredGlobalPlanner (std::string)
void setDesiredController (std::string)
void commitPublish ()
void setBackwardPlanner (bool commit=true)
void setUndoPathBackwardPlanner (bool commit=true)
void setForwardPlanner (bool commit=true)
void setPureSpinningPlanner (bool commit=true)
void setDefaultPlanners (bool commit=true)
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Private Attributes
std::string desired_planner_
std::string desired_controller_
bool set_planners_mode_flag_
rclcpp::Publisher< std_msgs::msg::String >::SharedPtr planner_selector_pub_
rclcpp::Publisher< std_msgs::msg::String >::SharedPtr controller_selector_pub_
rclcpp::Publisher< std_msgs::msg::String >::SharedPtr goal_checker_selector_pub_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 31 of file cp_planner_switcher.hpp.
Constructor & Destructor Documentation
CpPlannerSwitcher()
cl_nitrosz::CpPlannerSwitcher::CpPlannerSwitcher ()
Definition at line 27 of file cp_planner_switcher.cpp.
{}
Member Function Documentation
commitPublish()
void cl_nitrosz::CpPlannerSwitcher::commitPublish ()
Definition at line 99 of file cp_planner_switcher.cpp.
{
  std_msgs::msg::String planner_msg;
  planner_msg.data = desired_planner_;
  this->planner_selector_pub_->publish(planner_msg);
  std_msgs::msg::String controller_msg;
  controller_msg.data = desired_controller_;
  this->controller_selector_pub_->publish(controller_msg);
}
References controller_selector_pub_, desired_controller_, desired_planner_, and planner_selector_pub_.
Referenced by setBackwardPlanner(), setDefaultPlanners(), setForwardPlanner(), setPureSpinningPlanner(), and setUndoPathBackwardPlanner().
onInitialize()
void cl_nitrosz::CpPlannerSwitcher::onInitialize () override virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 29 of file cp_planner_switcher.cpp.
{
  rclcpp::QoS qos(rclcpp::KeepLast(1));
  qos.transient_local().reliable();
  this->planner_selector_pub_ =
    getNode()->create_publisher<std_msgs::msg::String>("planner_selector", qos);
  this->controller_selector_pub_ =
    getNode()->create_publisher<std_msgs::msg::String>("controller_selector", qos);
}
References controller_selector_pub_, smacc2::ISmaccComponent::getNode(), and planner_selector_pub_.
setBackwardPlanner()
void cl_nitrosz::CpPlannerSwitcher::setBackwardPlanner (bool commit = true)
Definition at line 60 of file cp_planner_switcher.cpp.
{
  RCLCPP_INFO(getLogger(), "[CpPlannerSwitcher] Planner Switcher: Trying to set BackwardPlanner");
  desired_planner_ = "BackwardGlobalPlanner";
  desired_controller_ = "BackwardLocalPlanner";
  if (commit) commitPublish();
}
References commitPublish(), desired_controller_, desired_planner_, and smacc2::ISmaccComponent::getLogger().
Referenced by cl_nitrosz::CbNavigateBackwards::onEntry().
setDefaultPlanners()
void cl_nitrosz::CpPlannerSwitcher::setDefaultPlanners (bool commit = true)
Definition at line 91 of file cp_planner_switcher.cpp.
{
  desired_planner_ = "GridBased";
  desired_controller_ = "FollowPath";
  if (commit) commitPublish();
}
References commitPublish(), desired_controller_, and desired_planner_.
Referenced by cl_nitrosz::CpWaypointNavigator::sendNextGoal().
setDesiredController()
void cl_nitrosz::CpPlannerSwitcher::setDesiredController (std::string controllerName)
Definition at line 45 of file cp_planner_switcher.cpp.
{
  desired_controller_ = controllerName;
}
References desired_controller_.
setDesiredGlobalPlanner()
void cl_nitrosz::CpPlannerSwitcher::setDesiredGlobalPlanner (std::string plannerName)
Definition at line 40 of file cp_planner_switcher.cpp.
{
  desired_planner_ = plannerName;
}
References desired_planner_.
setForwardPlanner()
void cl_nitrosz::CpPlannerSwitcher::setForwardPlanner (bool commit = true)
Definition at line 70 of file cp_planner_switcher.cpp.
{
  RCLCPP_INFO(getLogger(), "[CpPlannerSwitcher] Planner Switcher: Trying to set ForwardPlanner");
  desired_planner_ = "ForwardGlobalPlanner";
  desired_controller_ = "ForwardLocalPlanner";
  if (commit) commitPublish();
}
References commitPublish(), desired_controller_, desired_planner_, and smacc2::ISmaccComponent::getLogger().
Referenced by cl_nitrosz::CbNavigateForward::onEntry().
setPureSpinningPlanner()
void cl_nitrosz::CpPlannerSwitcher::setPureSpinningPlanner (bool commit = true)
Definition at line 80 of file cp_planner_switcher.cpp.
{
  RCLCPP_INFO(
    getLogger(), "[CpPlannerSwitcher] Planner Switcher: Trying to set PureSpinningPlanner");
  desired_planner_ = "ForwardGlobalPlanner";
  desired_controller_ = "PureSpinningLocalPlanner";
  if (commit) commitPublish();
}
References commitPublish(), desired_controller_, desired_planner_, and smacc2::ISmaccComponent::getLogger().
Referenced by cl_nitrosz::CbAbsoluteRotate::onEntry(), and cl_nitrosz::CbRotate::onEntry().
setUndoPathBackwardPlanner()
void cl_nitrosz::CpPlannerSwitcher::setUndoPathBackwardPlanner (bool commit = true)
Definition at line 50 of file cp_planner_switcher.cpp.
{
  RCLCPP_INFO(getLogger(), "[CpPlannerSwitcher] Planner Switcher: Trying to set BackwardPlanner");
  desired_planner_ = "UndoPathGlobalPlanner";
  desired_controller_ = "BackwardLocalPlanner";
  if (commit) commitPublish();
}
References commitPublish(), desired_controller_, desired_planner_, and smacc2::ISmaccComponent::getLogger().
Member Data Documentation
controller_selector_pub_
rclcpp::Publisher<std_msgs::msg::String>::SharedPtr cl_nitrosz::CpPlannerSwitcher::controller_selector_pub_ private
Definition at line 66 of file cp_planner_switcher.hpp.
Referenced by commitPublish(), and onInitialize().
desired_controller_
std::string cl_nitrosz::CpPlannerSwitcher::desired_controller_ private
Definition at line 60 of file cp_planner_switcher.hpp.
Referenced by commitPublish(), setBackwardPlanner(), setDefaultPlanners(), setDesiredController(), setForwardPlanner(), setPureSpinningPlanner(), and setUndoPathBackwardPlanner().
desired_planner_
std::string cl_nitrosz::CpPlannerSwitcher::desired_planner_ private
Definition at line 58 of file cp_planner_switcher.hpp.
Referenced by commitPublish(), setBackwardPlanner(), setDefaultPlanners(), setDesiredGlobalPlanner(), setForwardPlanner(), setPureSpinningPlanner(), and setUndoPathBackwardPlanner().
goal_checker_selector_pub_
rclcpp::Publisher<std_msgs::msg::String>::SharedPtr cl_nitrosz::CpPlannerSwitcher::goal_checker_selector_pub_ private
Definition at line 68 of file cp_planner_switcher.hpp.
planner_selector_pub_
rclcpp::Publisher<std_msgs::msg::String>::SharedPtr cl_nitrosz::CpPlannerSwitcher::planner_selector_pub_ private
Definition at line 64 of file cp_planner_switcher.hpp.
Referenced by commitPublish(), and onInitialize().
set_planners_mode_flag_
bool cl_nitrosz::CpPlannerSwitcher::set_planners_mode_flag_ private
Definition at line 62 of file cp_planner_switcher.hpp.
The documentation for this class was generated from the following files:
smacc2_client_library/nitrosz_client/nitrosz_client/include/nitrosz_client/components/planner_switcher/cp_planner_switcher.hpp
smacc2_client_library/nitrosz_client/nitrosz_client/src/nitrosz_client/components/planner_switcher/cp_planner_switcher.cpp