SMACC2: smacc2::client_behaviors::CbWaitActionServer Class Reference
smacc2::client_behaviors::CbWaitActionServer Class Reference
#include <cb_wait_action_server.hpp>
Public Member Functions
CbWaitActionServer (std::chrono::milliseconds timeout)
virtual ~CbWaitActionServer ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onExit ()
Private Attributes
ISmaccActionClient * client_
std::chrono::milliseconds timeout_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 33 of file cb_wait_action_server.hpp.
Constructor & Destructor Documentation
CbWaitActionServer()
smacc2::client_behaviors::CbWaitActionServer::CbWaitActionServer (std::chrono::milliseconds timeout)
Definition at line 27 of file cb_wait_action_server.cpp.
: timeout_(timeout) {}
~CbWaitActionServer()
smacc2::client_behaviors::CbWaitActionServer::~CbWaitActionServer () virtual
Definition at line 29 of file cb_wait_action_server.cpp.
{}
Member Function Documentation
onEntry()
void smacc2::client_behaviors::CbWaitActionServer::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 31 of file cb_wait_action_server.cpp.
{
  if (client_ != nullptr)
  {
    bool found = false;
    auto starttime = getNode()->now();
    while (!this->isShutdownRequested() && !found && (getNode()->now() - starttime) < timeout_)
    {
      std::shared_ptr<rclcpp_action::ClientBase> client_base = client_->getClientBase();
      RCLCPP_INFO(getLogger(), "[CbWaitActionServer] waiting action server..");
      found = client_base->wait_for_action_server(std::chrono::milliseconds(1000));
    }
    if (found)
    {
      RCLCPP_INFO(getLogger(), "[CbWaitActionServer] action server already available");
      this->postSuccessEvent();
    }
    else
    {
      RCLCPP_INFO(getLogger(), "[CbWaitActionServer] action server not found, timeout");
      this->postFailureEvent();
    }
  }
  else
  {
    RCLCPP_INFO(getLogger(), "[CbWaitActionServer] there is no action client in this orthogonal");
    this->postFailureEvent();
  }
}
References client_, smacc2::client_bases::ISmaccActionClient::getClientBase(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), smacc2::SmaccAsyncClientBehavior::isShutdownRequested(), smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), and timeout_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc2::client_behaviors::CbWaitActionServer::onOrthogonalAllocation () inline
Definition at line 40 of file cb_wait_action_server.hpp.
  {
    SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
    this->requiresClient(client_);
  }
References client_, smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation(), and smacc2::ISmaccClientBehavior::requiresClient().
Member Data Documentation
client_
ISmaccActionClient* smacc2::client_behaviors::CbWaitActionServer::client_ private
Definition at line 49 of file cb_wait_action_server.hpp.
Referenced by onEntry(), and onOrthogonalAllocation().
timeout_
std::chrono::milliseconds smacc2::client_behaviors::CbWaitActionServer::timeout_ private
Definition at line 50 of file cb_wait_action_server.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/client_behaviors/cb_wait_action_server.hpp
smacc2/src/smacc2/client_behaviors/cb_wait_action_server.cpp