SMACC2: cl_nitrosz::CpGoalCheckerSwitcher Class Reference
cl_nitrosz::CpGoalCheckerSwitcher Class Reference
#include <cp_goal_checker_switcher.hpp>
Public Member Functions
CpGoalCheckerSwitcher (std::string goal_checker_selector_topic="goal_checker_selector", std::string default_goal_checker_name="goal_checker")
void onInitialize () override
virtual ~CpGoalCheckerSwitcher ()
void setDefaultGoalChecker ()
void setGoalCheckerId (std::string goal_checker_id)
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Private Attributes
std::string goal_checker_selector_topic_
std::string default_goal_checker_name_
rclcpp::Publisher< std_msgs::msg::String >::SharedPtr goal_checker_selector_pub_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 31 of file cp_goal_checker_switcher.hpp.
Constructor & Destructor Documentation
CpGoalCheckerSwitcher()
cl_nitrosz::CpGoalCheckerSwitcher::CpGoalCheckerSwitcher (std::string goal_checker_selector_topic = "goal_checker_selector", std::string default_goal_checker_name = "goal_checker")
Definition at line 24 of file cp_goal_checker_switcher.cpp.
: goal_checker_selector_topic_(goal_checker_selector_topic),
  default_goal_checker_name_(default_goal_checker_name)
{
}
~CpGoalCheckerSwitcher()
cl_nitrosz::CpGoalCheckerSwitcher::~CpGoalCheckerSwitcher () virtual
Definition at line 31 of file cp_goal_checker_switcher.cpp.
{}
Member Function Documentation
onInitialize()
void cl_nitrosz::CpGoalCheckerSwitcher::onInitialize () override virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 33 of file cp_goal_checker_switcher.cpp.
{
  rclcpp::QoS qos(rclcpp::KeepLast(1));
  qos.transient_local().reliable();
  this->goal_checker_selector_pub_ =
    getNode()->create_publisher<std_msgs::msg::String>(goal_checker_selector_topic_, qos);
}
References smacc2::ISmaccComponent::getNode(), goal_checker_selector_pub_, and goal_checker_selector_topic_.
setDefaultGoalChecker()
void cl_nitrosz::CpGoalCheckerSwitcher::setDefaultGoalChecker ()
Definition at line 42 of file cp_goal_checker_switcher.cpp.
{
  setGoalCheckerId(default_goal_checker_name_);  // default id in navigation2 stack
}
References default_goal_checker_name_, and setGoalCheckerId().
setGoalCheckerId()
void cl_nitrosz::CpGoalCheckerSwitcher::setGoalCheckerId (std::string goal_checker_id)
Definition at line 47 of file cp_goal_checker_switcher.cpp.
{
  RCLCPP_INFO_STREAM(
    getLogger(), "[CpGoalCheckerSwitcher] Setting goal checker: " << goalcheckerid);
  // controller_server_node_->wait_for_service();
  // std::vector<rclcpp::Parameter> params{ rclcpp::Parameter("current_goal_checker", goalcheckerid) };
  // auto futureResults = controller_server_node_->set_parameters(params);
  std_msgs::msg::String msg;
  msg.data = goalcheckerid;
  this->goal_checker_selector_pub_->publish(msg);
  // int i = 0;
  // for (auto& res : futureResults.get())
  // {
  //   RCLCPP_INFO_STREAM(getLogger(), "[CpGoalCheckerSwitcher] parameter result: "
  //                                                   << params[i].get_name() << "=" << params[i].as_string()
  //                                                   << ". Result: " << res.successful);
  //   i++;
  //   if (!res.successful)
  //     RCLCPP_ERROR_STREAM(this->getLogger(), "[CpGoalCheckerSwitcher] goal checker could not properly
  //     switch "
  //                                                        "the goal checker of the controller_server");
  // }
}
References smacc2::ISmaccComponent::getLogger(), and goal_checker_selector_pub_.
Referenced by cl_nitrosz::CbAbsoluteRotate::onEntry(), cl_nitrosz::CbNavigateBackwards::onEntry(), cl_nitrosz::CbNavigateForward::onEntry(), cl_nitrosz::CbNavigateGlobalPosition::onEntry(), cl_nitrosz::CbUndoPathBackwards::onEntry(), and setDefaultGoalChecker().
Member Data Documentation
default_goal_checker_name_
std::string cl_nitrosz::CpGoalCheckerSwitcher::default_goal_checker_name_ private
Definition at line 44 of file cp_goal_checker_switcher.hpp.
Referenced by setDefaultGoalChecker().
goal_checker_selector_pub_
rclcpp::Publisher<std_msgs::msg::String>::SharedPtr cl_nitrosz::CpGoalCheckerSwitcher::goal_checker_selector_pub_ private
Definition at line 45 of file cp_goal_checker_switcher.hpp.
Referenced by onInitialize(), and setGoalCheckerId().
goal_checker_selector_topic_
std::string cl_nitrosz::CpGoalCheckerSwitcher::goal_checker_selector_topic_ private
Definition at line 43 of file cp_goal_checker_switcher.hpp.
Referenced by onInitialize().
The documentation for this class was generated from the following files:
smacc2_client_library/nitrosz_client/nitrosz_client/include/nitrosz_client/components/goal_checker_switcher/cp_goal_checker_switcher.hpp
smacc2_client_library/nitrosz_client/nitrosz_client/src/nitrosz_client/components/goal_checker_switcher/cp_goal_checker_switcher.cpp