SMACC2: cl_ros_timer::CbTimerCountdownOnce Class Reference
cl_ros_timer::CbTimerCountdownOnce Class Reference
#include <cb_timer_countdown_once.hpp>
Public Member Functions
CbTimerCountdownOnce (int64_t triggerTickCount)
void onEntry () override
void onEntry () override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename T >
boost::signals2::connection onTimerTick (void(T::*callback)(), T *object)
CbTimerCountdownOnce (int64_t triggerTickCount)
void onEntry () override
void onExit () override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename T >
boost::signals2::connection onTimerTick (void(T::*callback)(), T *object)
Public Member Functions inherited from smacc2::SmaccClientBehavior
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Member Functions
void onClientTimerTickCallback ()
void onClientTimerTickCallback ()
Private Attributes
int64_t tickCounter_
int64_t tickTriggerCount_
ClRosTimer * timerClient_
std::function< void()> postCountDownEvent_
smacc2::SmaccSignal< void()> onTimerTick_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 22 of file cb_timer_countdown_once.hpp.
Constructor & Destructor Documentation
CbTimerCountdownOnce() [1/2]
cl_ros_timer::CbTimerCountdownOnce::CbTimerCountdownOnce (int64_t triggerTickCount)
Definition at line 19 of file cb_timer_countdown_once.cpp.
: tickCounter_(0), tickTriggerCount_(triggerTickCount)
{
}
CbTimerCountdownOnce() [2/2]
cl_ros_timer::CbTimerCountdownOnce::CbTimerCountdownOnce (int64_t triggerTickCount)
Member Function Documentation
onClientTimerTickCallback() [1/2]
void cl_ros_timer::CbTimerCountdownOnce::onClientTimerTickCallback () private
Definition at line 24 of file cb_timer_countdown_once.cpp.
{
  tickCounter_++;
  if (tickCounter_ % tickTriggerCount_ == 0)
  {
    onTimerTick_();
    postCountDownEvent_();
  }
}
References onTimerTick_, postCountDownEvent_, tickCounter_, and tickTriggerCount_.
Referenced by onEntry().
onClientTimerTickCallback() [2/2]
void cl_ros_timer::CbTimerCountdownOnce::onClientTimerTickCallback () private
onEntry() [1/3]
void cl_ros_timer::CbTimerCountdownOnce::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 35 of file cb_timer_countdown_once.cpp.
{
  this->requiresClient(timerClient_);
  timerClient_->onTimerTick(&CbTimerCountdownOnce::onClientTimerTickCallback, this);
}
References onClientTimerTickCallback(), cl_ros_timer::ClRosTimer::onTimerTick(), smacc2::ISmaccClientBehavior::requiresClient(), and timerClient_.
onEntry() [2/3]
void cl_ros_timer::CbTimerCountdownOnce::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
onEntry() [3/3]
void cl_ros_timer::CbTimerCountdownOnce::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
onExit()
void cl_ros_timer::CbTimerCountdownOnce::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 41 of file cb_timer_countdown_once.cpp.
{}
onOrthogonalAllocation() [1/2]
template<typename TOrthogonal , typename TSourceObject > void cl_ros_timer::CbTimerCountdownOnce::onOrthogonalAllocation () inline
Definition at line 31 of file cb_timer_countdown_once.hpp.
  {
    this->postCountDownEvent_ = [=]()
    { this->template postEvent<EvTimer<TSourceObject, TOrthogonal>>(); };
  }
References postCountDownEvent_, and smacc2::ISmaccClientBehavior::postEvent().
onOrthogonalAllocation() [2/2]
template<typename TOrthogonal , typename TSourceObject > void cl_ros_timer::CbTimerCountdownOnce::onOrthogonalAllocation () inline
Definition at line 31 of file cb_timer_countdown_once.hpp.
  {
    this->postCountDownEvent_ = [=]()
    { this->template postEvent<EvTimer<TSourceObject, TOrthogonal>>(); };
  }
References postCountDownEvent_, and smacc2::ISmaccClientBehavior::postEvent().
onTimerTick() [1/2]
template<typename T > boost::signals2::connection cl_ros_timer::CbTimerCountdownOnce::onTimerTick (void(T::* callback)(), T * object) inline
Definition at line 38 of file cb_timer_countdown_once.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onTimerTick_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClientBehavior::getStateMachine(), and onTimerTick_.
onTimerTick() [2/2]
template<typename T > boost::signals2::connection cl_ros_timer::CbTimerCountdownOnce::onTimerTick (void(T::* callback)(), T * object) inline
Definition at line 38 of file cb_timer_countdown_once.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onTimerTick_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClientBehavior::getStateMachine(), and onTimerTick_.
Member Data Documentation
onTimerTick_
smacc2::SmaccSignal< void()> cl_ros_timer::CbTimerCountdownOnce::onTimerTick_ private
Definition at line 49 of file cb_timer_countdown_once.hpp.
Referenced by onClientTimerTickCallback(), and onTimerTick().
postCountDownEvent_
std::function< void()> cl_ros_timer::CbTimerCountdownOnce::postCountDownEvent_ private
Definition at line 48 of file cb_timer_countdown_once.hpp.
Referenced by onClientTimerTickCallback(), and onOrthogonalAllocation().
tickCounter_
int64_t cl_ros_timer::CbTimerCountdownOnce::tickCounter_ private
Definition at line 44 of file cb_timer_countdown_once.hpp.
Referenced by onClientTimerTickCallback().
tickTriggerCount_
int64_t cl_ros_timer::CbTimerCountdownOnce::tickTriggerCount_ private
Definition at line 45 of file cb_timer_countdown_once.hpp.
Referenced by onClientTimerTickCallback().
timerClient_
ClRosTimer * cl_ros_timer::CbTimerCountdownOnce::timerClient_ private
Definition at line 47 of file cb_timer_countdown_once.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/ros_timer_client/include/include/ros_timer_client/client_behaviors/cb_timer_countdown_once.hpp
smacc2_client_library/ros_timer_client/include/ros_timer_client/client_behaviors/cb_timer_countdown_once.hpp
smacc2_client_library/ros_timer_client/src/ros_timer_client/cb_timer_countdown_once.cpp