SMACC2: cl_nav2z::CbWaitPose Class Reference
cl_nav2z::CbWaitPose Class Reference
#include <cb_wait_pose.hpp>
Public Member Functions
CbWaitPose ()
CbWaitPose (WaitPoseStandardReferenceFrame frame)
virtual ~CbWaitPose ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Protected Attributes
cl_nav2z::ClNav2Z * nav2zClient_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 36 of file cb_wait_pose.hpp.
Constructor & Destructor Documentation
CbWaitPose() [1/2]
cl_nav2z::CbWaitPose::CbWaitPose ()
Definition at line 29 of file cb_wait_pose.cpp.
{}
CbWaitPose() [2/2]
cl_nav2z::CbWaitPose::CbWaitPose (WaitPoseStandardReferenceFrame frame)
~CbWaitPose()
cl_nav2z::CbWaitPose::~CbWaitPose () virtual
Definition at line 31 of file cb_wait_pose.cpp.
{}
Member Function Documentation
onEntry()
void cl_nav2z::CbWaitPose::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 33 of file cb_wait_pose.cpp.
{
  auto pose = this->nav2zClient_->getComponent<Pose>();
  try
  {
    pose->waitTransformUpdate(rclcpp::Rate(20));
    auto posemsg = pose->toPoseMsg();
    RCLCPP_INFO_STREAM(getLogger(), "[CbWaitPose] pose arrived: " << std::endl << posemsg);
  }
  catch (std::exception & ex)
  {
    RCLCPP_INFO(getLogger(), "[CbWaitPose] error getting the robot pose");
    this->postFailureEvent();
    return;
  }
  RCLCPP_INFO(getLogger(), "[CbWaitPose] pose received");
  this->postSuccessEvent();
}
References smacc2::ISmaccClient::getComponent(), smacc2::ISmaccClientBehavior::getLogger(), nav2zClient_, smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), and cl_nav2z::Pose::waitTransformUpdate().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_nav2z::CbWaitPose::onOrthogonalAllocation () inline
Definition at line 48 of file cb_wait_pose.hpp.
  {
    this->requiresClient(nav2zClient_);
    smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
  }
References nav2zClient_, and smacc2::ISmaccClientBehavior::requiresClient().
Member Data Documentation
nav2zClient_
cl_nav2z::ClNav2Z* cl_nav2z::CbWaitPose::nav2zClient_ protected
Definition at line 57 of file cb_wait_pose.hpp.
Referenced by onEntry(), and onOrthogonalAllocation().
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/client_behaviors/cb_wait_pose.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/client_behaviors/cb_wait_pose.cpp