SMACC2: cl_nav2z::CbAbortNavigation Class Reference
cl_nav2z::CbAbortNavigation Class Reference
#include <cb_abort_navigation.hpp>
Public Member Functions
CbAbortNavigation ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Attributes
cl_nav2z::ClNav2Z * nav2zClient_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 30 of file cb_abort_navigation.hpp.
Constructor & Destructor Documentation
CbAbortNavigation()
cl_nav2z::CbAbortNavigation::CbAbortNavigation ()
Definition at line 32 of file cb_abort_navigation.cpp.
{}
Member Function Documentation
onEntry()
void cl_nav2z::CbAbortNavigation::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 34 of file cb_abort_navigation.cpp.
{
  // this->sendGoal(goal);
  this->nav2zClient_->cancelGoal();
  this->postSuccessEvent();
}
References smacc2::client_bases::SmaccActionClientBase< ActionType >::cancelGoal(), nav2zClient_, and smacc2::SmaccAsyncClientBehavior::postSuccessEvent().
onExit()
void cl_nav2z::CbAbortNavigation::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 42 of file cb_abort_navigation.cpp.
{}
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_nav2z::CbAbortNavigation::onOrthogonalAllocation () inline
Definition at line 36 of file cb_abort_navigation.hpp.
  {
    this->requiresClient(nav2zClient_);
    smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
  }
References nav2zClient_, and smacc2::ISmaccClientBehavior::requiresClient().
Member Data Documentation
nav2zClient_
cl_nav2z::ClNav2Z* cl_nav2z::CbAbortNavigation::nav2zClient_ private
Definition at line 46 of file cb_abort_navigation.hpp.
Referenced by onEntry(), and onOrthogonalAllocation().
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/client_behaviors/cb_abort_navigation.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/client_behaviors/cb_abort_navigation.cpp