SMACC2: cl_move_group_interface::CbMoveEndEffectorRelative Class Reference
cl_move_group_interface::CbMoveEndEffectorRelative Class Reference
#include <cb_move_end_effector_relative.hpp>
Public Member Functions
CbMoveEndEffectorRelative ()
CbMoveEndEffectorRelative (geometry_msgs::msg::Transform transform)
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Attributes
geometry_msgs::msg::Transform transform_
std::optional< std::string > group_
Protected Member Functions
void moveRelative (moveit::planning_interface::MoveGroupInterface &moveGroupinterface, geometry_msgs::msg::Transform &transformOffset)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 28 of file cb_move_end_effector_relative.hpp.
Constructor & Destructor Documentation
CbMoveEndEffectorRelative() [1/2]
cl_move_group_interface::CbMoveEndEffectorRelative::CbMoveEndEffectorRelative ()
Definition at line 34 of file cb_move_end_effector_relative.cpp.
{ transform_.rotation.w = 1; }
References transform_.
CbMoveEndEffectorRelative() [2/2]
cl_move_group_interface::CbMoveEndEffectorRelative::CbMoveEndEffectorRelative (geometry_msgs::msg::Transform transform)
Definition at line 36 of file cb_move_end_effector_relative.cpp.
: transform_(transform)
{
}
Member Function Documentation
moveRelative()
void cl_move_group_interface::CbMoveEndEffectorRelative::moveRelative (moveit::planning_interface::MoveGroupInterface & moveGroupinterface, geometry_msgs::msg::Transform & transformOffset) protected
Definition at line 63 of file cb_move_end_effector_relative.cpp.
{
  auto referenceStartPose = moveGroupInterface.getCurrentPose();
  tf2::Quaternion currentOrientation;
  tf2::convert(referenceStartPose.pose.orientation, currentOrientation);
  tf2::Quaternion desiredRelativeRotation;
  tf2::convert(transformOffset.rotation, desiredRelativeRotation);
  auto targetOrientation = desiredRelativeRotation * currentOrientation;
  geometry_msgs::msg::PoseStamped targetObjectPose = referenceStartPose;
  targetObjectPose.pose.orientation = tf2::toMsg(targetOrientation);
  targetObjectPose.pose.position.x += transformOffset.translation.x;
  targetObjectPose.pose.position.y += transformOffset.translation.y;
  targetObjectPose.pose.position.z += transformOffset.translation.z;
  moveGroupInterface.setPlanningTime(1.0);
  RCLCPP_INFO_STREAM(
    getLogger(), "[CbMoveEndEffectorRelative] Target End efector Pose: " << targetObjectPose);
  moveGroupInterface.setPoseTarget(targetObjectPose);
  moveGroupInterface.setPoseReferenceFrame("map");
  moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
  bool success =
    (moveGroupInterface.plan(computedMotionPlan) == moveit::core::MoveItErrorCode::SUCCESS);
  RCLCPP_INFO(getLogger(), "Success Visualizing plan 1 (pose goal) %s", success ? "" : "FAILED");
  if (success)
  {
    auto executionResult = moveGroupInterface.execute(computedMotionPlan);
    if (executionResult == moveit_msgs::msg::MoveItErrorCodes::SUCCESS)
    {
      RCLCPP_INFO(getLogger(), "[CbMoveEndEffectorRelative] motion execution succeeded");
      movegroupClient_->postEventMotionExecutionSucceded();
      this->postSuccessEvent();
    }
    else
    {
      moveGroupInterface.setPoseTarget(
        referenceStartPose);  // undo to avoid abort-repeat state issues with this relative motion
      RCLCPP_INFO(getLogger(), "[CbMoveEndEffectorRelative] motion execution failed");
      movegroupClient_->postEventMotionExecutionFailed();
      this->postFailureEvent();
    }
  }
  else
  {
    moveGroupInterface.setPoseTarget(
      referenceStartPose);  //undo since we did not executed the motion
    RCLCPP_INFO(getLogger(), "[CbMoveEndEffectorRelative] motion execution failed");
    movegroupClient_->postEventMotionExecutionFailed();
    this->postFailureEvent();
  }
}
References smacc2::ISmaccClientBehavior::getLogger(), movegroupClient_, cl_move_group_interface::ClMoveGroup::postEventMotionExecutionFailed(), cl_move_group_interface::ClMoveGroup::postEventMotionExecutionSucceded(), smacc2::SmaccAsyncClientBehavior::postFailureEvent(), and smacc2::SmaccAsyncClientBehavior::postSuccessEvent().
Referenced by onEntry().
onEntry()
void cl_move_group_interface::CbMoveEndEffectorRelative::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 41 of file cb_move_end_effector_relative.cpp.
{
  RCLCPP_INFO_STREAM(
    getLogger(),
    "[CbMoveEndEffectorRelative] Transform end effector pose relative: " << transform_);
  this->requiresClient(movegroupClient_);
  if (this->group_)
  {
    moveit::planning_interface::MoveGroupInterface move_group(
      getNode(), moveit::planning_interface::MoveGroupInterface::Options(*(this->group_)));
    this->moveRelative(move_group, this->transform_);
  }
  else
  {
    this->moveRelative(*movegroupClient_->moveGroupClientInterface, this->transform_);
  }
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), group_, movegroupClient_, cl_move_group_interface::ClMoveGroup::moveGroupClientInterface, moveRelative(), smacc2::ISmaccClientBehavior::requiresClient(), and transform_.
onExit()
void cl_move_group_interface::CbMoveEndEffectorRelative::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 61 of file cb_move_end_effector_relative.cpp.
{}
Member Data Documentation
group_
std::optional<std::string> cl_move_group_interface::CbMoveEndEffectorRelative::group_
Definition at line 33 of file cb_move_end_effector_relative.hpp.
Referenced by onEntry().
movegroupClient_
ClMoveGroup* cl_move_group_interface::CbMoveEndEffectorRelative::movegroupClient_ protected
Definition at line 48 of file cb_move_end_effector_relative.hpp.
Referenced by moveRelative(), and onEntry().
transform_
geometry_msgs::msg::Transform cl_move_group_interface::CbMoveEndEffectorRelative::transform_
Definition at line 31 of file cb_move_end_effector_relative.hpp.
Referenced by CbMoveEndEffectorRelative(), and onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_move_end_effector_relative.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_move_end_effector_relative.cpp