SMACC2: smacc2::client_behaviors::CbRosStop2 Class Reference
smacc2::client_behaviors::CbRosStop2 Class Reference
#include <cb_ros_stop_2.hpp>
Public Member Functions
CbRosStop2 ()
CbRosStop2 (pid_t launchPid)
virtual ~CbRosStop2 ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onExit ()
Public Attributes
std::optional< std::string > packageName_
std::optional< std::string > launchFileName_
Protected Attributes
std::future< std::string > result_
smacc2::client_bases::ClRosLaunch2 * client_
std::future< std::string > future_
Static Private Attributes
static std::vector< std::future< std::string > > detached_futures_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 29 of file cb_ros_stop_2.hpp.
Constructor & Destructor Documentation
CbRosStop2() [1/2]
smacc2::client_behaviors::CbRosStop2::CbRosStop2 ()
Definition at line 28 of file cb_ros_stop_2.cpp.
{}
CbRosStop2() [2/2]
smacc2::client_behaviors::CbRosStop2::CbRosStop2 (pid_t launchPid)
Definition at line 30 of file cb_ros_stop_2.cpp.
{}
~CbRosStop2()
smacc2::client_behaviors::CbRosStop2::~CbRosStop2 () virtual
Definition at line 32 of file cb_ros_stop_2.cpp.
{}
Member Function Documentation
onEntry()
void smacc2::client_behaviors::CbRosStop2::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 40 of file cb_ros_stop_2.cpp.
{
  this->requiresClient(client_);
  client_->stop();
}
References client_, smacc2::ISmaccClientBehavior::requiresClient(), and smacc2::client_bases::ClRosLaunch2::stop().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc2::client_behaviors::CbRosStop2::onOrthogonalAllocation () inline
Definition at line 44 of file cb_ros_stop_2.hpp.
  {
    smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
  }
References smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation().
Member Data Documentation
client_
smacc2::client_bases::ClRosLaunch2* smacc2::client_behaviors::CbRosStop2::client_ protected
Definition at line 57 of file cb_ros_stop_2.hpp.
Referenced by onEntry().
detached_futures_
std::vector< std::future< std::string > > smacc2::client_behaviors::CbRosStop2::detached_futures_ static private
Definition at line 32 of file cb_ros_stop_2.hpp.
future_
std::future<std::string> smacc2::client_behaviors::CbRosStop2::future_ protected
Definition at line 59 of file cb_ros_stop_2.hpp.
launchFileName_
std::optional<std::string> smacc2::client_behaviors::CbRosStop2::launchFileName_
Definition at line 52 of file cb_ros_stop_2.hpp.
packageName_
std::optional<std::string> smacc2::client_behaviors::CbRosStop2::packageName_
Definition at line 51 of file cb_ros_stop_2.hpp.
result_
std::future<std::string> smacc2::client_behaviors::CbRosStop2::result_ protected
Definition at line 55 of file cb_ros_stop_2.hpp.
The documentation for this class was generated from the following files:
smacc2/include/smacc2/client_behaviors/cb_ros_stop_2.hpp
smacc2/src/smacc2/client_behaviors/cb_ros_stop_2.cpp