SMACC2: cl_nav2z::CpCostmapSwitch Class Reference
cl_nav2z::CpCostmapSwitch Class Reference
#include <cp_costmap_switch.hpp>
Public Types
enum class StandardLayers { GLOBAL_OBSTACLES_LAYER = 0 , LOCAL_OBSTACLES_LAYER = 1 , GLOBAL_INFLATED_LAYER = 2 , LOCAL_INFLATED_LAYER = 3 }
Public Member Functions
CpCostmapSwitch ()
void onInitialize () override
bool exists (std::string layerName)
void enable (std::string layerName)
void enable (StandardLayers layerType)
void disable (std::string layerName)
void disable (StandardLayers layerType)
void registerProxyFromDynamicReconfigureServer (std::string costmapName, std::string enablePropertyName="enabled")
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Static Public Member Functions
static std::string getStandardCostmapName (StandardLayers layertype)
Static Public Attributes
static std::array< std::string, 4 > layerNames
Private Attributes
std::map< std::string, std::shared_ptr< CpCostmapProxy > > costmapProxies
cl_nav2z::ClNav2Z * nav2zClient_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 41 of file cp_costmap_switch.hpp.
Member Enumeration Documentation
StandardLayers
enum class cl_nav2z::CpCostmapSwitch::StandardLayers strong
Enumerator
GLOBAL_OBSTACLES_LAYER
LOCAL_OBSTACLES_LAYER
GLOBAL_INFLATED_LAYER
LOCAL_INFLATED_LAYER
Definition at line 44 of file cp_costmap_switch.hpp.
  {
    GLOBAL_OBSTACLES_LAYER = 0,
    LOCAL_OBSTACLES_LAYER = 1,
    GLOBAL_INFLATED_LAYER = 2,
    LOCAL_INFLATED_LAYER = 3
  };
Constructor & Destructor Documentation
CpCostmapSwitch()
cl_nav2z::CpCostmapSwitch::CpCostmapSwitch ()
Definition at line 34 of file cp_costmap_switch.cpp.
{}
Member Function Documentation
disable() [1/2]
void cl_nav2z::CpCostmapSwitch::disable (StandardLayers layerType)
Definition at line 111 of file cp_costmap_switch.cpp.
{
  this->disable(getStandardCostmapName(layerType));
}
References disable(), and getStandardCostmapName().
disable() [2/2]
void cl_nav2z::CpCostmapSwitch::disable (std::string layerName)
Definition at line 93 of file cp_costmap_switch.cpp.
{
  RCLCPP_INFO(getLogger(), "[CpCostmapSwitch] disabling %s", layerName.c_str());
  if (!exists(layerName))
  {
    RCLCPP_ERROR(getLogger(), "[CpCostmapSwitch] costmap %s does not exist", layerName.c_str());
    return;
  }
  else
  {
    RCLCPP_INFO(
      getLogger(), "[CpCostmapSwitch] costmap %s found. Calling dynamic reconfigure server.",
      layerName.c_str());
    costmapProxies[layerName]->setCostmapEnabled(false);
  }
}
References costmapProxies, exists(), and smacc2::ISmaccComponent::getLogger().
Referenced by disable().
enable() [1/2]
void cl_nav2z::CpCostmapSwitch::enable (StandardLayers layerType)
Definition at line 88 of file cp_costmap_switch.cpp.
{
  this->enable(getStandardCostmapName(layerType));
}
References enable(), and getStandardCostmapName().
enable() [2/2]
void cl_nav2z::CpCostmapSwitch::enable (std::string layerName)
Definition at line 70 of file cp_costmap_switch.cpp.
{
  RCLCPP_INFO(getLogger(), "[CpCostmapSwitch] enabling %s", layerName.c_str());
  if (!exists(layerName))
  {
    RCLCPP_ERROR(getLogger(), "[CpCostmapSwitch] costmap %s does not exist", layerName.c_str());
    return;
  }
  else
  {
    RCLCPP_INFO(
      getLogger(), "[CpCostmapSwitch] costmap %s found. Calling dynamic reconfigure server.",
      layerName.c_str());
    costmapProxies[layerName]->setCostmapEnabled(true);
  }
}
References costmapProxies, exists(), and smacc2::ISmaccComponent::getLogger().
Referenced by enable().
exists()
bool cl_nav2z::CpCostmapSwitch::exists (std::string layerName)
Definition at line 60 of file cp_costmap_switch.cpp.
{
  if (!this->costmapProxies.count(layerName))
  {
    return false;
  }
  return true;
}
References costmapProxies.
Referenced by disable(), and enable().
getStandardCostmapName()
std::string cl_nav2z::CpCostmapSwitch::getStandardCostmapName (StandardLayers layertype) static
Definition at line 55 of file cp_costmap_switch.cpp.
{
  return CpCostmapSwitch::layerNames[(int)layertype];
}
References layerNames.
Referenced by disable(), enable(), and onInitialize().
onInitialize()
void cl_nav2z::CpCostmapSwitch::onInitialize () override virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 36 of file cp_costmap_switch.cpp.
{
  this->nav2zClient_ = dynamic_cast<cl_nav2z::ClNav2Z *>(owner_);
  if (this->nav2zClient_ == nullptr)
  {
    RCLCPP_ERROR(getLogger(), "the owner of the CpCostmapSwitch must be a ClNav2Z");
  }
  registerProxyFromDynamicReconfigureServer(
    getStandardCostmapName(StandardLayers::GLOBAL_OBSTACLES_LAYER));
  registerProxyFromDynamicReconfigureServer(
    getStandardCostmapName(StandardLayers::LOCAL_OBSTACLES_LAYER));
  registerProxyFromDynamicReconfigureServer(
    getStandardCostmapName(StandardLayers::GLOBAL_INFLATED_LAYER));
  registerProxyFromDynamicReconfigureServer(
    getStandardCostmapName(StandardLayers::LOCAL_INFLATED_LAYER));
}
References smacc2::ISmaccComponent::getLogger(), getStandardCostmapName(), GLOBAL_INFLATED_LAYER, GLOBAL_OBSTACLES_LAYER, LOCAL_INFLATED_LAYER, LOCAL_OBSTACLES_LAYER, nav2zClient_, smacc2::ISmaccComponent::owner_, and registerProxyFromDynamicReconfigureServer().
registerProxyFromDynamicReconfigureServer()
void cl_nav2z::CpCostmapSwitch::registerProxyFromDynamicReconfigureServer (std::string costmapName, std::string enablePropertyName = "enabled")
Definition at line 25 of file cp_costmap_switch.cpp.
{
  RCLCPP_INFO(getLogger(), "[CpCostmapSwitch] registering costmap type: %s", costmapName.c_str());
  auto proxy = std::make_shared<CpCostmapProxy>(
    this->nav2zClient_->getName() + "/" + costmapName, enablePropertyName, getNode());
  costmapProxies[costmapName] = proxy;
}
References costmapProxies, smacc2::ISmaccComponent::getLogger(), smacc2::client_bases::ISmaccActionClient::getName(), smacc2::ISmaccComponent::getNode(), and nav2zClient_.
Referenced by onInitialize().
Member Data Documentation
costmapProxies
std::map<std::string, std::shared_ptr<CpCostmapProxy> > cl_nav2z::CpCostmapSwitch::costmapProxies private
Definition at line 74 of file cp_costmap_switch.hpp.
Referenced by disable(), enable(), exists(), and registerProxyFromDynamicReconfigureServer().
layerNames
std::array< std::string, 4 > cl_nav2z::CpCostmapSwitch::layerNames static
Initial value:
= {
  "global_costmap/obstacles_layer",
  "local_costmap/obstacles_layer"
  "global_costmap/inflater_layer",
  "local_costmap/inflater_layer"}
Definition at line 52 of file cp_costmap_switch.hpp.
Referenced by getStandardCostmapName().
nav2zClient_
cl_nav2z::ClNav2Z* cl_nav2z::CpCostmapSwitch::nav2zClient_ private
Definition at line 75 of file cp_costmap_switch.hpp.
Referenced by onInitialize(), and registerProxyFromDynamicReconfigureServer().
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/components/costmap_switch/cp_costmap_switch.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/components/costmap_switch/cp_costmap_switch.cpp