SMACC2: smacc2::client_bases::SmaccServiceClient< ServiceType > Class Template Reference
smacc2::client_bases::SmaccServiceClient< ServiceType > Class Template Reference
#include <smacc_service_client.hpp>
Public Member Functions
SmaccServiceClient (std::string serviceName)
SmaccServiceClient ()
void onInitialize () override
std::shared_ptr< typename ServiceType::Response > call (std::shared_ptr< typename ServiceType::Request > &request)
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Public Attributes
std::optional< std::string > serviceName_
Protected Attributes
std::shared_ptr< rclcpp::Client< ServiceType > > client_
bool initialized_
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Detailed Description
template<typename ServiceType>
class smacc2::client_bases::SmaccServiceClient< ServiceType >
Definition at line 31 of file smacc_service_client.hpp.
Constructor & Destructor Documentation
SmaccServiceClient() [1/2]
template<typename ServiceType > smacc2::client_bases::SmaccServiceClient< ServiceType >::SmaccServiceClient (std::string serviceName) inline
Definition at line 36 of file smacc_service_client.hpp.
: serviceName_(serviceName) { initialized_ = false; }
References smacc2::client_bases::SmaccServiceClient< ServiceType >::initialized_.
SmaccServiceClient() [2/2]
template<typename ServiceType > smacc2::client_bases::SmaccServiceClient< ServiceType >::SmaccServiceClient () inline
Definition at line 38 of file smacc_service_client.hpp.
{ initialized_ = false; }
References smacc2::client_bases::SmaccServiceClient< ServiceType >::initialized_.
Member Function Documentation
call()
template<typename ServiceType > std::shared_ptr< typename ServiceType::Response > smacc2::client_bases::SmaccServiceClient< ServiceType >::call (std::shared_ptr< typename ServiceType::Request > & request) inline
Definition at line 58 of file smacc_service_client.hpp.
  {
    auto result = client_->async_send_request(request);
    //rclcpp::spin_until_future_complete(getNode(), result);
    return result.get();
  }
References smacc2::client_bases::SmaccServiceClient< ServiceType >::client_.
onInitialize()
template<typename ServiceType > void smacc2::client_bases::SmaccServiceClient< ServiceType >::onInitialize () inline override virtual
Reimplemented from smacc2::ISmaccClient.
Definition at line 40 of file smacc_service_client.hpp.
  {
    if (!initialized_)
    {
      if (!serviceName_)
      {
        RCLCPP_ERROR(getLogger(), "service client with no service name set. Skipping.");
      }
      else
      {
        RCLCPP_INFO_STREAM(
          getLogger(), "[" << this->getName() << "] Client Service: " << *serviceName_);
        this->initialized_ = true;
        client_ = getNode()->create_client<ServiceType>(*serviceName_);
      }
    }
  }
References smacc2::client_bases::SmaccServiceClient< ServiceType >::client_, smacc2::ISmaccClient::getLogger(), smacc2::ISmaccClient::getName(), smacc2::ISmaccClient::getNode(), smacc2::client_bases::SmaccServiceClient< ServiceType >::initialized_, and smacc2::client_bases::SmaccServiceClient< ServiceType >::serviceName_.
Member Data Documentation
client_
template<typename ServiceType > std::shared_ptr<rclcpp::Client<ServiceType> > smacc2::client_bases::SmaccServiceClient< ServiceType >::client_ protected
Definition at line 68 of file smacc_service_client.hpp.
Referenced by smacc2::client_bases::SmaccServiceClient< ServiceType >::call(), and smacc2::client_bases::SmaccServiceClient< ServiceType >::onInitialize().
initialized_
template<typename ServiceType > bool smacc2::client_bases::SmaccServiceClient< ServiceType >::initialized_ protected
Definition at line 69 of file smacc_service_client.hpp.
Referenced by smacc2::client_bases::SmaccServiceClient< ServiceType >::onInitialize(), smacc2::client_bases::SmaccServiceClient< ServiceType >::SmaccServiceClient(), and smacc2::client_bases::SmaccServiceClient< ServiceType >::SmaccServiceClient().
serviceName_
template<typename ServiceType > std::optional<std::string> smacc2::client_bases::SmaccServiceClient< ServiceType >::serviceName_
Definition at line 34 of file smacc_service_client.hpp.
Referenced by smacc2::client_bases::SmaccServiceClient< ServiceType >::onInitialize().
The documentation for this class was generated from the following file:
smacc2/include/smacc2/client_bases/smacc_service_client.hpp