SMACC2: cl_move_group_interface::CbEndEffectorRotate Class Reference
cl_move_group_interface::CbEndEffectorRotate Class Reference
#include <cb_end_effector_rotate.hpp>
Public Member Functions
CbEndEffectorRotate (double deltaRadians, std::optional< std::string > tipLink=std::nullopt)
virtual ~CbEndEffectorRotate ()
virtual void onEntry () override
Public Member Functions inherited from cl_move_group_interface::CbCircularPivotMotion
CbCircularPivotMotion (std::optional< std::string > tipLink=std::nullopt)
CbCircularPivotMotion (const geometry_msgs::msg::PoseStamped &planePivotPose, double deltaRadians, std::optional< std::string > tipLink=std::nullopt)
CbCircularPivotMotion (const geometry_msgs::msg::PoseStamped &planePivotPose, const geometry_msgs::msg::Pose &relativeInitialPose, double deltaRadians, std::optional< std::string > tipLink=std::nullopt)
virtual void generateTrajectory () override
virtual void createMarkers () override
Public Member Functions inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
CbMoveEndEffectorTrajectory (std::optional< std::string > tipLink=std::nullopt)
CbMoveEndEffectorTrajectory (const std::vector< geometry_msgs::msg::PoseStamped > &endEffectorTrajectory, std::optional< std::string > tipLink=std::nullopt)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual void onEntry () override
virtual void onExit () override
virtual void update () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Member Functions inherited from smacc2::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (rclcpp::Duration duration)
void executeUpdate (rclcpp::Node::SharedPtr node)
void setUpdatePeriod (rclcpp::Duration duration)
Public Attributes
std::optional< std::string > tipLink
Public Attributes inherited from cl_move_group_interface::CbCircularPivotMotion
std::optional< double > angularSpeed_rad_s_
std::optional< double > linearSpeed_m_s_
std::optional< geometry_msgs::msg::Pose > relativeInitialPose_
Public Attributes inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
std::optional< std::string > group_
std::optional< std::string > tipLink_
std::optional< bool > allowInitialTrajectoryStateJointDiscontinuity_
Additional Inherited Members
Protected Member Functions inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
ComputeJointTrajectoryErrorCode computeJointSpaceTrajectory (moveit_msgs::msg::RobotTrajectory &computedJointTrajectory)
void executeJointSpaceTrajectory (const moveit_msgs::msg::RobotTrajectory &computedJointTrajectory)
virtual void generateTrajectory ()=0
virtual void createMarkers ()
void getCurrentEndEffectorPose (std::string globalFrame, tf2::Stamped< tf2::Transform > &currentEndEffectorTransform)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
virtual void update ()=0
Protected Attributes inherited from cl_move_group_interface::CbCircularPivotMotion
geometry_msgs::msg::PoseStamped planePivotPose_
double deltaRadians_
Protected Attributes inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
std::vector< geometry_msgs::msg::PoseStamped > endEffectorTrajectory_
ClMoveGroup * movegroupClient_ = nullptr
visualization_msgs::msg::MarkerArray beahiorMarkers_
Detailed Description
Definition at line 26 of file cb_end_effector_rotate.hpp.
Constructor & Destructor Documentation
CbEndEffectorRotate()
cl_move_group_interface::CbEndEffectorRotate::CbEndEffectorRotate (double deltaRadians, std::optional< std::string > tipLink = std::nullopt)
Definition at line 34 of file cb_end_effector_rotate.cpp.
: CbCircularPivotMotion(tipLink)
{
  deltaRadians_ = deltaRadians;
}
References cl_move_group_interface::CbCircularPivotMotion::deltaRadians_.
~CbEndEffectorRotate()
cl_move_group_interface::CbEndEffectorRotate::~CbEndEffectorRotate () virtual
Definition at line 40 of file cb_end_effector_rotate.cpp.
{}
Member Function Documentation
onEntry()
void cl_move_group_interface::CbEndEffectorRotate::onEntry () override virtual
Reimplemented from cl_move_group_interface::CbMoveEndEffectorTrajectory.
Definition at line 42 of file cb_end_effector_rotate.cpp.
{
  // autocompute pivot pose
  tf2_ros::Buffer tfBuffer(getNode()->get_clock());
  tf2_ros::TransformListener tfListener(tfBuffer);
  tf2::Stamped<tf2::Transform> endEffectorInPivotFrame;
  int attempts = 3;
  this->requiresClient(movegroupClient_);
  if (!tipLink_)
  {
    tipLink_ = this->movegroupClient_->moveGroupClientInterface->getEndEffectorLink();
    RCLCPP_WARN_STREAM(
      getLogger(),
      "[" << getName() << "] tip unspecified, using default end effector: " << *tipLink_);
  }
  while (attempts > 0)
  {
    try
    {
      //auto pivotFrameName = this->movegroupClient_->moveGroupClientInterface->getPlanningFrame();
      auto pivotFrameName = this->movegroupClient_->moveGroupClientInterface->getEndEffectorLink();
      tf2::Stamped<tf2::Transform> endEffectorInPivotFrame;
      tf2::fromMsg(
        tfBuffer.lookupTransform(pivotFrameName, *tipLink_, rclcpp::Time(), rclcpp::Duration(10s)),
        endEffectorInPivotFrame);
      tf2::toMsg(endEffectorInPivotFrame, this->planePivotPose_.pose);
      this->planePivotPose_.header.frame_id = endEffectorInPivotFrame.frame_id_;
      this->planePivotPose_.header.stamp =
        rclcpp::Time(endEffectorInPivotFrame.stamp_.time_since_epoch().count());
      break;
    }
    catch (const std::exception & e)
    {
      RCLCPP_ERROR_STREAM(getLogger(), e.what() << ". Attempt countdown: " << attempts);
      rclcpp::Duration(500ms);
      attempts--;
    }
  }
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] pivotPose: " << planePivotPose_);
  RCLCPP_INFO_STREAM(
    getLogger(), "[" << getName() << "] calling base CbCircularPivotMotion::onEntry");
  CbCircularPivotMotion::onEntry();
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::getNode(), cl_move_group_interface::CbMoveEndEffectorTrajectory::movegroupClient_, cl_move_group_interface::ClMoveGroup::moveGroupClientInterface, smacc2::ISmaccClientBehavior::onEntry(), cl_move_group_interface::CbCircularPivotMotion::planePivotPose_, smacc2::ISmaccClientBehavior::requiresClient(), and cl_move_group_interface::CbMoveEndEffectorTrajectory::tipLink_.
Member Data Documentation
tipLink
std::optional<std::string> cl_move_group_interface::CbEndEffectorRotate::tipLink
Definition at line 35 of file cb_end_effector_rotate.hpp.
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_end_effector_rotate.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_end_effector_rotate.cpp