SMACC2: smacc2::client_bases::ClRosLaunch2 Class Reference
smacc2::client_bases::ClRosLaunch2 Class Reference
#include <smacc_ros_launch_client_2.hpp>
Public Member Functions
ClRosLaunch2 ()
ClRosLaunch2 (std::string packageName, std::string launchFilename)
virtual ~ClRosLaunch2 ()
void launch ()
void stop ()
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void onInitialize ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Static Public Member Functions
static std::future< std::string > executeRosLaunch (std::string packageName, std::string launchFilename, std::function< bool()> cancelCondition, ClRosLaunch2 *client=nullptr)
Public Attributes
std::string packageName_
std::string launchFileName_
pid_t launchPid_
Protected Types
typedef std::function< void > cancelCallback
Protected Attributes
std::future< std::string > result_
std::atomic< bool > cancellationToken_ = ATOMIC_VAR_INIT(false)
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Static Protected Attributes
static std::map< std::future< void >, cancelCallback > detached_futures_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Detailed Description
Definition at line 43 of file smacc_ros_launch_client_2.hpp.
Member Typedef Documentation
cancelCallback
typedef std::function<void> smacc2::client_bases::ClRosLaunch2::cancelCallback protected
Definition at line 73 of file smacc_ros_launch_client_2.hpp.
Constructor & Destructor Documentation
ClRosLaunch2() [1/2]
smacc2::client_bases::ClRosLaunch2::ClRosLaunch2 ()
Definition at line 41 of file smacc_ros_launch_client_2.cpp.
: /*packageName_(std::nullopt), launchFileName_(std::nullopt),*/ cancellationToken_(false)
{
}
ClRosLaunch2() [2/2]
smacc2::client_bases::ClRosLaunch2::ClRosLaunch2 (std::string packageName, std::string launchFilename)
Definition at line 46 of file smacc_ros_launch_client_2.cpp.
: packageName_(packageName), launchFileName_(launchFilename), cancellationToken_(false)
{
}
~ClRosLaunch2()
smacc2::client_bases::ClRosLaunch2::~ClRosLaunch2 () virtual
Definition at line 51 of file smacc_ros_launch_client_2.cpp.
{}
Member Function Documentation
executeRosLaunch()
std::future< std::string > smacc2::client_bases::ClRosLaunch2::executeRosLaunch (std::string packageName, std::string launchFilename, std::function< bool()> cancelCondition, ClRosLaunch2 * client = nullptr) static
Definition at line 69 of file smacc_ros_launch_client_2.cpp.
{
  return std::async(
    std::launch::async,
    [packageName, launchFileName, cancelCondition, client]()
    {
      RCLCPP_WARN_STREAM(rclcpp::get_logger("smacc2"), "[ClRosLaunch2] Starting ros launch thread");
      std::stringstream cmd;
      cmd << "ros2 launch " << packageName << " " << launchFileName;
      std::array<char, 128> buffer;
      std::string result;
      auto child = runProcess(cmd.str().c_str());
      if (!child.pipe)
      {
        throw std::runtime_error("popen() failed!");
      }
      if (client != nullptr)
      {
        client->launchPid_ = child.pid;
      }
      int fd = fileno(child.pipe);
      int flags = fcntl(fd, F_GETFL, 0);
      fcntl(fd, F_SETFL, flags | O_NONBLOCK);
      bool cancelled = false;
      // while (!cancelCondition())
      while (!cancelled)
      {
        cancelled = cancelCondition();
        size_t bytesRead = fread(buffer.data(), 1, buffer.size(), /*data*/ child.pipe);
        if (bytesRead > 0)
        {
          result.append(buffer.data(), bytesRead);
        }
        else if (bytesRead == 0)
        {
          // No se han ledo ms datos
          std::this_thread::sleep_for(
            std::chrono::milliseconds(100));  // Espera antes de intentar nuevamente
        }
        else
        {
          // Error de lectura
          RCLCPP_ERROR(rclcpp::get_logger("smacc2"), "Error de lectura en pipe");
          break;
        }
      }
      rclcpp::sleep_for(2s);
      if (child.pid > 0)
      {
        killGrandchildren(child.pid);
        rclcpp::sleep_for(2s);
      }
      int status;
      pid_t child_pid = child.pid;
      if (waitpid(child_pid, &status, 0) != -1)
      {
        if (WIFEXITED(status))
        {
          int exit_status = WEXITSTATUS(status);
          RCLCPP_INFO(
            rclcpp::get_logger("smacc2"), "Child process exited with status: %d", exit_status);
        }
        else if (WIFSIGNALED(status))
        {
          int term_signal = WTERMSIG(status);
          RCLCPP_WARN(
            rclcpp::get_logger("smacc2"), "Child process terminated by signal: %d", term_signal);
        }
      }
      else
      {
        RCLCPP_ERROR(rclcpp::get_logger("smacc2"), "Error waiting for child process.");
      }
      pclose(child.pipe);
      close(child.pipe->_fileno);  // Close pipe file descriptor but not processes
      RCLCPP_WARN_STREAM(rclcpp::get_logger("smacc2"), "[ClRosLaunch2] RESULT:\n" << result);
      // Devuelve una std::future con el resultado
      // return std::async(std::launch::async, [result]() { return result; });
      return result;
    });
}
References smacc2::client_bases::killGrandchildren(), launchPid_, and smacc2::client_bases::runProcess().
Referenced by launch(), and smacc2::client_behaviors::CbRosLaunch2::onEntry().
launch()
void smacc2::client_bases::ClRosLaunch2::launch ()
Definition at line 53 of file smacc_ros_launch_client_2.cpp.
{
  cancellationToken_.store(false);
  // Iniciar el hilo para la ejecucin del lanzamiento
  this->result_ = /*std::async([this]()*/
                  // {
    executeRosLaunch(packageName_, launchFileName_, [this]() { return cancellationToken_.load(); });
  // });
}
References cancellationToken_, executeRosLaunch(), launchFileName_, packageName_, and result_.
Referenced by smacc2::client_behaviors::CbRosLaunch2::onEntry().
stop()
void smacc2::client_bases::ClRosLaunch2::stop ()
Definition at line 63 of file smacc_ros_launch_client_2.cpp.
{
  // Establecer la bandera de cancelacin
  cancellationToken_.store(true);
}
References cancellationToken_.
Referenced by smacc2::client_behaviors::CbRosStop2::onEntry().
Member Data Documentation
cancellationToken_
std::atomic<bool> smacc2::client_bases::ClRosLaunch2::cancellationToken_ = ATOMIC_VAR_INIT(false) protected
Definition at line 77 of file smacc_ros_launch_client_2.hpp.
Referenced by launch(), and stop().
detached_futures_
std::map<std::future<void>, cancelCallback> smacc2::client_bases::ClRosLaunch2::detached_futures_ static protected
Definition at line 75 of file smacc_ros_launch_client_2.hpp.
launchFileName_
std::string smacc2::client_bases::ClRosLaunch2::launchFileName_
Definition at line 65 of file smacc_ros_launch_client_2.hpp.
Referenced by launch(), and smacc2::client_behaviors::CbRosLaunch2::onEntry().
launchPid_
pid_t smacc2::client_bases::ClRosLaunch2::launchPid_
Definition at line 67 of file smacc_ros_launch_client_2.hpp.
Referenced by executeRosLaunch().
packageName_
std::string smacc2::client_bases::ClRosLaunch2::packageName_
Definition at line 63 of file smacc_ros_launch_client_2.hpp.
Referenced by launch(), and smacc2::client_behaviors::CbRosLaunch2::onEntry().
result_
std::future<std::string> smacc2::client_bases::ClRosLaunch2::result_ protected
Definition at line 71 of file smacc_ros_launch_client_2.hpp.
Referenced by launch().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/client_bases/smacc_ros_launch_client_2.hpp
smacc2/src/smacc2/client_bases/smacc_ros_launch_client_2.cpp