SMACC2: cl_http::ClHttp Class Reference
cl_http::ClHttp Class Reference
#include <cl_http_client.hpp>
Classes
class Server
Public Types
enum class kHttpRequestMethod { GET = static_cast<int>(boost::beast::http::verb::get) , POST = static_cast<int>(boost::beast::http::verb::post) , PUT = static_cast<int>(boost::beast::http::verb::put) }
using TResponse = http_session_base::TResponse
Public Member Functions
template<typename T >
boost::signals2::connection onResponseReceived (void(T::*callback)(const TResponse &), T *object)
ClHttp (const std::string &server, const int &timeout=1500)
virtual ~ClHttp ()
void onInitialize () override
void makeRequest (const kHttpRequestMethod http_method, const std::string &path="/", const std::string &body="", const std::unordered_map< std::string, std::string > &headers={})
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Private Attributes
const int HTTP_VERSION = 11
bool initialized_
bool is_ssl_
int timeout_
Server server_
boost::asio::io_context io_context_
boost::asio::executor_work_guard< decltype(io_context_)::executor_type > worker_guard_
std::thread tcp_connection_runner_
boost::asio::ssl::context ssl_context_
smacc2::SmaccSignal< void(const TResponse &)> onResponseReceived_
std::function< void(TResponse)> callbackHandler
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Detailed Description
Definition at line 38 of file cl_http_client.hpp.
Member Typedef Documentation
TResponse
using cl_http::ClHttp::TResponse = http_session_base::TResponse
Definition at line 76 of file cl_http_client.hpp.
Member Enumeration Documentation
kHttpRequestMethod
enum class cl_http::ClHttp::kHttpRequestMethod strong
Enumerator
GET
POST
PUT
Definition at line 69 of file cl_http_client.hpp.
  {
    GET = static_cast<int>(boost::beast::http::verb::get),
    POST = static_cast<int>(boost::beast::http::verb::post),
    PUT = static_cast<int>(boost::beast::http::verb::put),
  };
Constructor & Destructor Documentation
ClHttp()
cl_http::ClHttp::ClHttp (const std::string & server, const int & timeout = 1500) explicit
Definition at line 25 of file cl_http_client.cpp.
: initialized_{false},
  timeout_{timeout},
  server_{server_name},
  worker_guard_{boost::asio::make_work_guard(io_context_.get_executor())},
  ssl_context_{boost::asio::ssl::context::tlsv13_client}
{
  ssl_context_.set_default_verify_paths();
  ssl_context_.set_verify_mode(boost::asio::ssl::verify_peer);
}
References ssl_context_.
~ClHttp()
cl_http::ClHttp::~ClHttp () virtual
Definition at line 36 of file cl_http_client.cpp.
{
  worker_guard_.reset();
  tcp_connection_runner_.join();
}
References tcp_connection_runner_, and worker_guard_.
Member Function Documentation
makeRequest()
void cl_http::ClHttp::makeRequest (const kHttpRequestMethod http_method, const std::string & path = "/", const std::string & body = "", const std::unordered_map< std::string, std::string > & headers = {})
Definition at line 51 of file cl_http_client.cpp.
{
  auto path_used = path;
  if (path[0] != '/')
  {
    std::reverse(path_used.begin(), path_used.end());
    path_used += '/';
    std::reverse(path_used.begin(), path_used.end());
  }
  RCLCPP_INFO(this->getLogger(), "SSL? %d", server_.isSSL());
  RCLCPP_INFO(this->getLogger(), "Server %s", server_.getServerName().c_str());
  RCLCPP_INFO(this->getLogger(), "Path %s", path_used.c_str());
  RCLCPP_INFO(this->getLogger(), "Port %s", server_.getPort().c_str());
  std::shared_ptr<http_session_base> http_session_ptr;
  if (server_.isSSL())
  {
    http_session_ptr = std::make_shared<ssl_http_session>(
      boost::asio::make_strand(io_context_), ssl_context_, callbackHandler);
  }
  else
  {
    http_session_ptr =
      std::make_shared<http_session>(boost::asio::make_strand(io_context_), callbackHandler);
  }
  http_session_ptr->setBody(body);
  http_session_ptr->setHeaders(headers);
  http_session_ptr->run(
    server_.getServerName(), path_used, static_cast<boost::beast::http::verb>(http_method),
    HTTP_VERSION);
}
References callbackHandler, smacc2::ISmaccClient::getLogger(), cl_http::ClHttp::Server::getPort(), cl_http::ClHttp::Server::getServerName(), HTTP_VERSION, io_context_, cl_http::ClHttp::Server::isSSL(), server_, and ssl_context_.
Referenced by cl_http::CbHttpRequestBase::onEntry().
onInitialize()
void cl_http::ClHttp::onInitialize () override virtual
Reimplemented from smacc2::ISmaccClient.
Definition at line 42 of file cl_http_client.cpp.
{
  if (!initialized_)
  {
    tcp_connection_runner_ = std::thread{[&]() { io_context_.run(); }};
    this->initialized_ = true;
  }
}
References initialized_, io_context_, and tcp_connection_runner_.
onResponseReceived()
template<typename T > boost::signals2::connection cl_http::ClHttp::onResponseReceived (void(T::* callback)(const TResponse &), T * object) inline
Definition at line 79 of file cl_http_client.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onResponseReceived_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClient::getStateMachine(), and onResponseReceived_.
Referenced by cl_http::CbHttpRequestBase::runtimeConfigure().
Member Data Documentation
callbackHandler
std::function<void(TResponse)> cl_http::ClHttp::callbackHandler private
Initial value:
= [&](const TResponse & res)
  { onResponseReceived_(res); }
Definition at line 112 of file cl_http_client.hpp.
  { onResponseReceived_(res); };
Referenced by makeRequest().
HTTP_VERSION
const int cl_http::ClHttp::HTTP_VERSION = 11 private
Definition at line 96 of file cl_http_client.hpp.
Referenced by makeRequest().
initialized_
bool cl_http::ClHttp::initialized_ private
Definition at line 98 of file cl_http_client.hpp.
Referenced by onInitialize().
io_context_
boost::asio::io_context cl_http::ClHttp::io_context_ private
Definition at line 104 of file cl_http_client.hpp.
Referenced by makeRequest(), and onInitialize().
is_ssl_
bool cl_http::ClHttp::is_ssl_ private
Definition at line 99 of file cl_http_client.hpp.
onResponseReceived_
smacc2::SmaccSignal<void(const TResponse &)> cl_http::ClHttp::onResponseReceived_ private
Definition at line 110 of file cl_http_client.hpp.
Referenced by onResponseReceived().
server_
Server cl_http::ClHttp::server_ private
Definition at line 102 of file cl_http_client.hpp.
Referenced by makeRequest().
ssl_context_
boost::asio::ssl::context cl_http::ClHttp::ssl_context_ private
Definition at line 108 of file cl_http_client.hpp.
Referenced by ClHttp(), and makeRequest().
tcp_connection_runner_
std::thread cl_http::ClHttp::tcp_connection_runner_ private
Definition at line 106 of file cl_http_client.hpp.
Referenced by onInitialize(), and ~ClHttp().
timeout_
int cl_http::ClHttp::timeout_ private
Definition at line 100 of file cl_http_client.hpp.
worker_guard_
boost::asio::executor_work_guard<decltype(io_context_)::executor_type> cl_http::ClHttp::worker_guard_ private
Definition at line 105 of file cl_http_client.hpp.
Referenced by ~ClHttp().
The documentation for this class was generated from the following files:
smacc2_client_library/http_client/include/http_client/cl_http_client.hpp
smacc2_client_library/http_client/src/http_client/cl_http_client.cpp