SMACC2: cl_nitrosz::CbNavigateNextWaypointFree Class Reference
cl_nitrosz::CbNavigateNextWaypointFree Class Reference
#include <cb_navigate_next_waypoint_free.hpp>
Public Member Functions
CbNavigateNextWaypointFree ()
virtual ~CbNavigateNextWaypointFree ()
void onEntry () override
void onSucessCallback ()
void onExit () override
Public Member Functions inherited from cl_nitrosz::CbPositionControlFreeSpace
CbPositionControlFreeSpace ()
void updateParameters ()
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
Protected Attributes
cl_nitrosz::CpWaypointNavigatorBase * waypointsNavigator_
Additional Inherited Members
Public Attributes inherited from cl_nitrosz::CbPositionControlFreeSpace
double yaw_goal_tolerance_rads_ = 0.1
double threshold_distance_ = 3.0
geometry_msgs::msg::Pose target_pose_
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 27 of file cb_navigate_next_waypoint_free.hpp.
Constructor & Destructor Documentation
CbNavigateNextWaypointFree()
cl_nitrosz::CbNavigateNextWaypointFree::CbNavigateNextWaypointFree ()
Definition at line 25 of file cb_navigate_next_waypoint_free.cpp.
{}
~CbNavigateNextWaypointFree()
cl_nitrosz::CbNavigateNextWaypointFree::~CbNavigateNextWaypointFree () virtual
Definition at line 27 of file cb_navigate_next_waypoint_free.cpp.
{}
Member Function Documentation
onEntry()
void cl_nitrosz::CbNavigateNextWaypointFree::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 29 of file cb_navigate_next_waypoint_free.cpp.
{
  requiresComponent(this->waypointsNavigator_);
  this->target_pose_ = this->waypointsNavigator_->getCurrentPose();
  this->onSuccess(&CbNavigateNextWaypointFree::CbNavigateNextWaypointFree::onSucessCallback, this);
  RCLCPP_INFO_STREAM(
    getLogger(), "[CbNavigateNextWaypoint] initial load file target pose: x: "
                   << this->target_pose_.position.x << ", y: " << this->target_pose_.position.y);
  CbPositionControlFreeSpace::onEntry();
}
References cl_nitrosz::CpWaypointNavigatorBase::getCurrentPose(), smacc2::ISmaccClientBehavior::getLogger(), cl_nitrosz::CbPositionControlFreeSpace::onEntry(), smacc2::SmaccAsyncClientBehavior::onSuccess(), smacc2::ISmaccClientBehavior::requiresComponent(), cl_nitrosz::CbPositionControlFreeSpace::target_pose_, and waypointsNavigator_.
onExit()
void cl_nitrosz::CbNavigateNextWaypointFree::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 52 of file cb_navigate_next_waypoint_free.cpp.
{}
onSucessCallback()
void cl_nitrosz::CbNavigateNextWaypointFree::onSucessCallback ()
Definition at line 41 of file cb_navigate_next_waypoint_free.cpp.
{
  RCLCPP_INFO_STREAM(getLogger(), "[CbNavigateNextWaypoint] Success on planning to next waypoint");
  this->waypointsNavigator_->notifyGoalReached();
  this->waypointsNavigator_->forward(1);
  RCLCPP_INFO_STREAM(
    getLogger(), "[CbNavigateNextWaypoint] next position index: "
                   << this->waypointsNavigator_->getCurrentWaypointIndex() << "/"
                   << this->waypointsNavigator_->getWaypoints().size());
}
References cl_nitrosz::CpWaypointNavigatorBase::forward(), cl_nitrosz::CpWaypointNavigatorBase::getCurrentWaypointIndex(), smacc2::ISmaccClientBehavior::getLogger(), cl_nitrosz::CpWaypointNavigatorBase::notifyGoalReached(), and waypointsNavigator_.
Member Data Documentation
waypointsNavigator_
cl_nitrosz::CpWaypointNavigatorBase* cl_nitrosz::CbNavigateNextWaypointFree::waypointsNavigator_ protected
Definition at line 41 of file cb_navigate_next_waypoint_free.hpp.
Referenced by onEntry(), and onSucessCallback().
The documentation for this class was generated from the following files:
smacc2_client_library/nitrosz_client/nitrosz_client/include/nitrosz_client/client_behaviors/cb_navigate_next_waypoint_free.hpp
smacc2_client_library/nitrosz_client/nitrosz_client/src/nitrosz_client/client_behaviors/cb_navigate_next_waypoint_free.cpp