SMACC2: smacc2::SmaccAsyncClientBehavior Class Reference
smacc2::SmaccAsyncClientBehavior Class Reference
#include <smacc_asynchronous_client_behavior.hpp>
Public Member Functions
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
Protected Member Functions
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Private Member Functions
void waitFutureIfNotFinished (std::optional< std::future< int > > &threadfut, bool requestFinish)
Private Attributes
std::optional< std::future< int > > onEntryThread_
std::optional< std::future< int > > onExitThread_
std::function< void()> postFinishEventFn_
std::function< void()> postSuccessEventFn_
std::function< void()> postFailureEventFn_
SmaccSignal< void()> onFinished_
SmaccSignal< void()> onSuccess_
SmaccSignal< void()> onFailure_
bool isShutdownRequested_ = false
Detailed Description
Definition at line 55 of file smacc_asynchronous_client_behavior.hpp.
Constructor & Destructor Documentation
~SmaccAsyncClientBehavior()
smacc2::SmaccAsyncClientBehavior::~SmaccAsyncClientBehavior () virtual
Definition at line 151 of file smacc_client_async_behavior.cpp.
{}
Member Function Documentation
dispose()
void smacc2::SmaccAsyncClientBehavior::dispose () override protected virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 122 of file smacc_client_async_behavior.cpp.
{
  RCLCPP_DEBUG_STREAM(
    getLogger(), "[" << getName()
                     << "] Destroying client behavior- Waiting finishing of asynchronous onExit "
                        "thread");
  try
  {
    if (this->onExitThread_)
    {
      // this->onExitThread_->get();
      this->onExitThread_->get();
    }
    //this->onExitThread_->get();
  }
  catch (...)
  {
    RCLCPP_DEBUG(
      getLogger(),
      "[SmaccAsyncClientBehavior] trying to Join onExit function, but it was already "
      "finished.");
  }
  RCLCPP_DEBUG_STREAM(
    getLogger(), "[" << getName()
                     << "] Destroying client behavior-  onExit thread finished. Proccedding "
                        "destruction.");
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), and onExitThread_.
executeOnEntry()
void smacc2::SmaccAsyncClientBehavior::executeOnEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 27 of file smacc_client_async_behavior.cpp.
{
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] asynchronous onEntry thread started");
  this->onEntryThread_ = std::async(
    std::launch::async,
    [=]
    {
      this->onEntry();
      this->postFinishEventFn_();
      RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] asynchronous onEntry thread finished");
      return 0;
    });
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::onEntry(), onEntryThread_, and postFinishEventFn_.
executeOnExit()
void smacc2::SmaccAsyncClientBehavior::executeOnExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 105 of file smacc_client_async_behavior.cpp.
{
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] onExit - join async onEntry thread");
  this->waitOnEntryThread(true);
  RCLCPP_INFO_STREAM(
    getLogger(), "[" << getName() << "] onExit - Creating asynchronous onExit thread");
  this->onExitThread_ = std::async(
    std::launch::async,
    [=]
    {
      this->onExit();
      RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] asynchronous onExit done.");
      return 0;
    });
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::onExit(), onExitThread_, and waitOnEntryThread().
isShutdownRequested()
bool smacc2::SmaccAsyncClientBehavior::isShutdownRequested () protected
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Definition at line 165 of file smacc_client_async_behavior.cpp.
{
  std::string shut = "";
  if (isShutdownRequested_)
  {
    shut = "True";
  }
  else
  {
    shut = "False";
  }
  // RCLCPP_FATAL_STREAM_THROTTLE(
  //   getLogger(), *(getNode()->get_clock()), 1000, "[" << getName() << "] " << ((uint64_t) this ) << " Is requestForceFinish active? " << shut );
  return isShutdownRequested_;
}
References isShutdownRequested_.
Referenced by cl_nav2z::CbNav2ZClientBehaviorBase::isOwnActionResponse(), cl_nav2z::CbActiveStop::onEntry(), smacc2::client_behaviors::CbRosLaunch2::onEntry(), smacc2::client_behaviors::CbRosLaunch::onEntry(), smacc2::client_behaviors::CbSequence::onEntry(), smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry(), smacc2::client_behaviors::CbSleepFor::onEntry(), smacc2::client_behaviors::CbWaitActionServer::onEntry(), smacc2::client_behaviors::CbWaitNode::onEntry(), and smacc2::client_behaviors::CbWaitTopic::onEntry().
onFailure() [1/2]
template<typename TCallback , typename T > boost::signals2::connection smacc2::SmaccAsyncClientBehavior::onFailure (TCallback callback, T * object)
onFailure() [2/2]
template<typename TCallbackMethod , typename T > boost::signals2::connection smacc2::SmaccAsyncClientBehavior::onFailure (TCallbackMethod callback, T * object)
Definition at line 64 of file smacc_asynchronous_client_behavior_impl.hpp.
{
  return this->getStateMachine()->createSignalConnection(onFailure_, callback, object);
}
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClientBehavior::getStateMachine(), and onFailure_.
onFinished() [1/2]
template<typename TCallback , typename T > boost::signals2::connection smacc2::SmaccAsyncClientBehavior::onFinished (TCallback callback, T * object)
onFinished() [2/2]
template<typename TCallbackMethod , typename T > boost::signals2::connection smacc2::SmaccAsyncClientBehavior::onFinished (TCallbackMethod callback, T * object)
Definition at line 57 of file smacc_asynchronous_client_behavior_impl.hpp.
{
  return this->getStateMachine()->createSignalConnection(onFinished_, callback, object);
}
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClientBehavior::getStateMachine(), and onFinished_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation ()
Definition at line 28 of file smacc_asynchronous_client_behavior_impl.hpp.
{
  postFinishEventFn_ = [this]
  {
    this->onFinished_();
    this->postEvent<EvCbFinished<TSourceObject, TOrthogonal>>();
  };
  postSuccessEventFn_ = [this]
  {
    this->onSuccess_();
    this->postEvent<EvCbSuccess<TSourceObject, TOrthogonal>>();
  };
  postFailureEventFn_ = [this]
  {
    this->onFailure_();
    this->postEvent<EvCbFailure<TSourceObject, TOrthogonal>>();
  };
}
References onFailure_, onFinished_, onSuccess_, smacc2::ISmaccClientBehavior::postEvent(), postFailureEventFn_, postFinishEventFn_, and postSuccessEventFn_.
Referenced by cl_lifecyclenode::CbActivate::onOrthogonalAllocation(), cl_lifecyclenode::CbCleanup::onOrthogonalAllocation(), cl_lifecyclenode::CbConfigure::onOrthogonalAllocation(), cl_lifecyclenode::CbDeactivate::onOrthogonalAllocation(), cl_lifecyclenode::CbDeactivateOnExit::onOrthogonalAllocation(), cl_lifecyclenode::CbDestroy::onOrthogonalAllocation(), cl_lifecyclenode::CbShutdown::onOrthogonalAllocation(), cl_moveit2z::CbMoveEndEffectorTrajectory::onOrthogonalAllocation(), cl_nav2z::CbAbortNavigation::onOrthogonalAllocation(), cl_nav2z::CbNav2ZClientBehaviorBase::onOrthogonalAllocation(), cl_nav2z::CbNavigateNextWaypointUntilReached::onOrthogonalAllocation(), cl_nav2z::CbWaitPose::onOrthogonalAllocation(), cl_nav2z::CbWaitTransform::onOrthogonalAllocation(), smacc2::client_behaviors::CbRosLaunch2::onOrthogonalAllocation(), smacc2::client_behaviors::CbRosLaunch::onOrthogonalAllocation(), smacc2::client_behaviors::CbRosStop2::onOrthogonalAllocation(), smacc2::client_behaviors::CbWaitActionServer::onOrthogonalAllocation(), smacc2::client_behaviors::onOrthogonalAllocation(), and smacc2::client_behaviors::CbSequence::then().
onSuccess() [1/2]
template<typename TCallback , typename T > boost::signals2::connection smacc2::SmaccAsyncClientBehavior::onSuccess (TCallback callback, T * object)
Referenced by cl_nav2z::CbNavigateNextWaypointFree::onEntry().
onSuccess() [2/2]
template<typename TCallbackMethod , typename T > boost::signals2::connection smacc2::SmaccAsyncClientBehavior::onSuccess (TCallbackMethod callback, T * object)
Definition at line 50 of file smacc_asynchronous_client_behavior_impl.hpp.
{
  return this->getStateMachine()->createSignalConnection(onSuccess_, callback, object);
}
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClientBehavior::getStateMachine(), and onSuccess_.
postFailureEvent()
void smacc2::SmaccAsyncClientBehavior::postFailureEvent () protected
Definition at line 155 of file smacc_client_async_behavior.cpp.
{ postFailureEventFn_(); }
References postFailureEventFn_.
Referenced by cl_moveit2z::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_moveit2z::CbMoveJoints::moveJoints(), cl_moveit2z::CbMoveEndEffectorRelative::moveRelative(), cl_moveit2z::CbMoveCartesianRelative::moveRelativeCartesian(), cl_moveit2z::CbMoveEndEffector::moveToAbsolutePose(), cl_moveit2z::CbAttachObject::onEntry(), cl_moveit2z::CbDetachObject::onEntry(), cl_moveit2z::CbMoveEndEffectorTrajectory::onEntry(), cl_nav2z::CbWaitPose::onEntry(), cl_nav2z::CbWaitTransform::onEntry(), smacc2::client_behaviors::CbSequence::onEntry(), smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry(), smacc2::client_behaviors::CbWaitActionServer::onEntry(), smacc2::client_behaviors::CbWaitNode::onEntry(), smacc2::client_behaviors::CbWaitTopic::onEntry(), cl_nav2z::CbNav2ZClientBehaviorBase::onNavigationActionAbort(), cl_lifecyclenode::CbActivate::onOrthogonalAllocation(), cl_lifecyclenode::CbCleanup::onOrthogonalAllocation(), cl_lifecyclenode::CbConfigure::onOrthogonalAllocation(), cl_lifecyclenode::CbDeactivate::onOrthogonalAllocation(), cl_lifecyclenode::CbDeactivateOnExit::onOrthogonalAllocation(), cl_lifecyclenode::CbDestroy::onOrthogonalAllocation(), cl_lifecyclenode::CbShutdown::onOrthogonalAllocation(), and smacc2::client_behaviors::CbSequence::onSubNodeAbort().
postSuccessEvent()
void smacc2::SmaccAsyncClientBehavior::postSuccessEvent () protected
Definition at line 153 of file smacc_client_async_behavior.cpp.
{ postSuccessEventFn_(); }
References postSuccessEventFn_.
Referenced by cl_moveit2z::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_moveit2z::CbMoveJoints::moveJoints(), cl_moveit2z::CbMoveEndEffectorRelative::moveRelative(), cl_moveit2z::CbMoveCartesianRelative::moveRelativeCartesian(), cl_moveit2z::CbMoveEndEffector::moveToAbsolutePose(), cl_moveit2z::CbAttachObject::onEntry(), cl_moveit2z::CbDetachObject::onEntry(), cl_nav2z::CbAbortNavigation::onEntry(), cl_nav2z::CbActiveStop::onEntry(), cl_nav2z::CbLoadWaypointsFile::onEntry(), cl_nav2z::CbPositionControlFreeSpace::onEntry(), cl_nav2z::CbPureSpinning::onEntry(), cl_nav2z::CbWaitPose::onEntry(), cl_nav2z::CbWaitTransform::onEntry(), smacc2::client_behaviors::CbSequence::onEntry(), smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry(), smacc2::client_behaviors::CbSleepFor::onEntry(), smacc2::client_behaviors::CbWaitActionServer::onEntry(), smacc2::client_behaviors::CbWaitNode::onEntry(), smacc2::client_behaviors::CbWaitTopic::onEntry(), cl_nav2z::CbWaitNav2Nodes::onMessageReceived(), smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onMessageReceived(), cl_nav2z::CbNav2ZClientBehaviorBase::onNavigationActionSuccess(), cl_nav2z::CbNavigateNextWaypointUntilReached::onNavigationActionSuccess(), cl_lifecyclenode::CbActivate::onOrthogonalAllocation(), cl_lifecyclenode::CbCleanup::onOrthogonalAllocation(), cl_lifecyclenode::CbConfigure::onOrthogonalAllocation(), cl_lifecyclenode::CbDeactivate::onOrthogonalAllocation(), cl_lifecyclenode::CbDeactivateOnExit::onOrthogonalAllocation(), cl_lifecyclenode::CbDestroy::onOrthogonalAllocation(), and cl_lifecyclenode::CbShutdown::onOrthogonalAllocation().
requestForceFinish()
void smacc2::SmaccAsyncClientBehavior::requestForceFinish ()
Definition at line 157 of file smacc_client_async_behavior.cpp.
{
  RCLCPP_FATAL_STREAM_THROTTLE(
    getLogger(), *(getNode()->get_clock()), 1000,
    "[" << getName() << "] " << ((uint64_t)this) << " requestForceFinish");
  isShutdownRequested_ = true;
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::getNode(), and isShutdownRequested_.
Referenced by smacc2::client_behaviors::CbSequence::onSubNodeAbort(), and waitFutureIfNotFinished().
waitFutureIfNotFinished()
void smacc2::SmaccAsyncClientBehavior::waitFutureIfNotFinished (std::optional< std::future< int > > & threadfut, bool requestFinish) private
Definition at line 41 of file smacc_client_async_behavior.cpp.
{
  try
  {
    rclcpp::Rate r(100);
    while (rclcpp::ok())
    {
      //bool valid = threadfut.valid();
      if (threadfut && threadfut->valid())
      {
        auto status = threadfut->wait_for(std::chrono::milliseconds(20));
        if (status == std::future_status::ready)
        // auto status = threadfut->wait();
        // if(status)
        {
          // done
          threadfut->get();
          break;
        }
        else
        {
          // in progress
          RCLCPP_INFO_STREAM(
            getLogger(),
            "[" << getName()
                << "] fut valid but waiting for asynchronous onEntry thread to finish: state: "
                << (int)status);
        }
      }
      else
      {
        RCLCPP_INFO_STREAM(
          getLogger(),
          "[" << getName()
              << "] waiting future onEntryThread. It was not even created. Skipping wait.");
        break;
      }
      // r.sleep();
      rclcpp::sleep_for(100ms);
      // rclcpp::spin_some(getNode());
      RCLCPP_WARN_THROTTLE(
        getLogger(), *(getNode()->get_clock()), 1000,
        "[%s] waiting for finishing client behavior, before leaving the state. Is the client "
        "behavior stuck? requesting force finish",
        this->getName().c_str());
      if (requestFinish) requestForceFinish();
    }
  }
  catch (const std::exception & e)
  {
    RCLCPP_DEBUG(
      getLogger(),
      "[SmaccAsyncClientBehavior] trying to join function, but it was already finished.");
  }
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::getNode(), and requestForceFinish().
Referenced by waitOnEntryThread().
waitOnEntryThread()
void smacc2::SmaccAsyncClientBehavior::waitOnEntryThread (bool requestFinish)
Definition at line 100 of file smacc_client_async_behavior.cpp.
{
  waitFutureIfNotFinished(this->onEntryThread_, requestFinish);
}
References onEntryThread_, and waitFutureIfNotFinished().
Referenced by executeOnExit().
Member Data Documentation
isShutdownRequested_
bool smacc2::SmaccAsyncClientBehavior::isShutdownRequested_ = false private
Definition at line 109 of file smacc_asynchronous_client_behavior.hpp.
Referenced by isShutdownRequested(), and requestForceFinish().
onEntryThread_
std::optional<std::future<int> > smacc2::SmaccAsyncClientBehavior::onEntryThread_ private
Definition at line 98 of file smacc_asynchronous_client_behavior.hpp.
Referenced by executeOnEntry(), and waitOnEntryThread().
onExitThread_
std::optional<std::future<int> > smacc2::SmaccAsyncClientBehavior::onExitThread_ private
Definition at line 99 of file smacc_asynchronous_client_behavior.hpp.
Referenced by dispose(), and executeOnExit().
onFailure_
SmaccSignal<void()> smacc2::SmaccAsyncClientBehavior::onFailure_ private
Definition at line 107 of file smacc_asynchronous_client_behavior.hpp.
Referenced by onFailure(), and onOrthogonalAllocation().
onFinished_
SmaccSignal<void()> smacc2::SmaccAsyncClientBehavior::onFinished_ private
Definition at line 105 of file smacc_asynchronous_client_behavior.hpp.
Referenced by onFinished(), and onOrthogonalAllocation().
onSuccess_
SmaccSignal<void()> smacc2::SmaccAsyncClientBehavior::onSuccess_ private
Definition at line 106 of file smacc_asynchronous_client_behavior.hpp.
Referenced by onOrthogonalAllocation(), and onSuccess().
postFailureEventFn_
std::function<void()> smacc2::SmaccAsyncClientBehavior::postFailureEventFn_ private
Definition at line 103 of file smacc_asynchronous_client_behavior.hpp.
Referenced by onOrthogonalAllocation(), and postFailureEvent().
postFinishEventFn_
std::function<void()> smacc2::SmaccAsyncClientBehavior::postFinishEventFn_ private
Definition at line 101 of file smacc_asynchronous_client_behavior.hpp.
Referenced by executeOnEntry(), and onOrthogonalAllocation().
postSuccessEventFn_
std::function<void()> smacc2::SmaccAsyncClientBehavior::postSuccessEventFn_ private
Definition at line 102 of file smacc_asynchronous_client_behavior.hpp.
Referenced by onOrthogonalAllocation(), and postSuccessEvent().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/smacc_asynchronous_client_behavior.hpp
smacc2/include/smacc2/impl/smacc_asynchronous_client_behavior_impl.hpp
smacc2/src/smacc2/smacc_client_async_behavior.cpp