SMACC2: smacc2::ISmaccComponent Class Reference
smacc2::ISmaccComponent Class Reference
#include <component.hpp>
Public Member Functions
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Protected Member Functions
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Private Member Functions
void initialize (ISmaccClient *owner)
void setStateMachine (ISmaccStateMachine *stateMachine)
Friends
class ISmaccOrthogonal
class ISmaccClient
Detailed Description
Definition at line 29 of file component.hpp.
Constructor & Destructor Documentation
ISmaccComponent()
smacc2::ISmaccComponent::ISmaccComponent ()
Definition at line 27 of file smacc_component.cpp.
: owner_(nullptr) {}
~ISmaccComponent()
smacc2::ISmaccComponent::~ISmaccComponent () virtual
Definition at line 25 of file smacc_component.cpp.
{}
Member Function Documentation
createSiblingComponent()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs> SmaccComponentType * smacc2::ISmaccComponent::createSiblingComponent (TArgs... targs) protected
Definition at line 103 of file smacc_component_impl.hpp.
{
  return this->owner_->createComponent<SmaccComponentType, TOrthogonal, TClient>(targs...);
}
References smacc2::ISmaccClient::createComponent(), and owner_.
createSiblingNamedComponent()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs> SmaccComponentType * smacc2::ISmaccComponent::createSiblingNamedComponent (std::string name, TArgs... targs) protected
Definition at line 109 of file smacc_component_impl.hpp.
{
  return this->owner_->createNamedComponent<SmaccComponentType, TOrthogonal, TClient>(
    name, targs...);
}
References smacc2::ISmaccClient::createNamedComponent(), and owner_.
getLogger()
rclcpp::Logger smacc2::ISmaccComponent::getLogger () const protected
Definition at line 44 of file smacc_component.cpp.
{ return owner_->getLogger(); }
References smacc2::ISmaccClient::getLogger(), and owner_.
Referenced by cl_moveit2z::CpGraspingComponent::createGraspableBox(), cl_nav2z::CpCostmapSwitch::disable(), cl_nitrosz::CpCostmapSwitch::disable(), cl_nav2z::CpCostmapSwitch::enable(), cl_nitrosz::CpCostmapSwitch::enable(), cl_moveit2z::CpTrajectoryHistory::getLastTrajectory(), cl_nav2z::CpWaypointNavigatorBase::loadWayPointsFromFile(), cl_nitrosz::CpWaypointNavigatorBase::loadWayPointsFromFile(), cl_nav2z::CpWaypointNavigatorBase::loadWayPointsFromFile2(), cl_nitrosz::CpWaypointNavigatorBase::loadWayPointsFromFile2(), cl_nav2z::CpWaypointNavigatorBase::loadWaypointsFromYamlParameter(), cl_nitrosz::CpWaypointNavigatorBase::loadWaypointsFromYamlParameter(), cl_nav2z::odom_tracker::CpOdomTracker::logStateString(), cl_nitrosz::odom_tracker::CpOdomTracker::logStateString(), cl_nav2z::CpWaypointNavigatorBase::notifyGoalReached(), cl_nitrosz::CpWaypointNavigatorBase::notifyGoalReached(), cl_nav2z::CpWaypointNavigator::onGoalReached(), cl_nitrosz::CpWaypointNavigator::onGoalReached(), smacc2::components::CpTopicSubscriber< MessageType >::onInitialize(), cl_nav2z::CpCostmapSwitch::onInitialize(), cl_nav2z::odom_tracker::CpOdomTracker::onInitialize(), cl_nav2z::Pose::onInitialize(), cl_nitrosz::CpCostmapSwitch::onInitialize(), cl_nitrosz::odom_tracker::CpOdomTracker::onInitialize(), cl_nitrosz::Pose::onInitialize(), cl_nav2z::odom_tracker::CpOdomTracker::popPath(), cl_nitrosz::odom_tracker::CpOdomTracker::popPath(), cl_nav2z::odom_tracker::CpOdomTracker::processOdometryMessage(), cl_nitrosz::odom_tracker::CpOdomTracker::processOdometryMessage(), cl_nav2z::odom_tracker::CpOdomTracker::pushPath(), cl_nitrosz::odom_tracker::CpOdomTracker::pushPath(), cl_moveit2z::CpTrajectoryHistory::pushTrajectory(), cl_nav2z::CpCostmapSwitch::registerProxyFromDynamicReconfigureServer(), cl_nitrosz::CpCostmapSwitch::registerProxyFromDynamicReconfigureServer(), requiresComponent(), requiresComponent(), cl_nav2z::CpWaypointNavigatorBase::seekName(), cl_nitrosz::CpWaypointNavigatorBase::seekName(), cl_nav2z::CpWaypointNavigator::sendNextGoal(), cl_nitrosz::CpWaypointNavigator::sendNextGoal(), cl_nav2z::CpPlannerSwitcher::setBackwardPlanner(), cl_nitrosz::CpPlannerSwitcher::setBackwardPlanner(), cl_nav2z::CpPlannerSwitcher::setForwardPlanner(), cl_nitrosz::CpPlannerSwitcher::setForwardPlanner(), cl_nav2z::CpGoalCheckerSwitcher::setGoalCheckerId(), cl_nitrosz::CpGoalCheckerSwitcher::setGoalCheckerId(), cl_nav2z::CpPlannerSwitcher::setPureSpinningPlanner(), cl_nitrosz::CpPlannerSwitcher::setPureSpinningPlanner(), cl_nav2z::odom_tracker::CpOdomTracker::setStartPoint(), cl_nitrosz::odom_tracker::CpOdomTracker::setStartPoint(), cl_nav2z::odom_tracker::CpOdomTracker::setStartPoint(), cl_nitrosz::odom_tracker::CpOdomTracker::setStartPoint(), cl_nav2z::CpPlannerSwitcher::setUndoPathBackwardPlanner(), cl_nitrosz::CpPlannerSwitcher::setUndoPathBackwardPlanner(), cl_nav2z::odom_tracker::CpOdomTracker::setWorkingMode(), cl_nitrosz::odom_tracker::CpOdomTracker::setWorkingMode(), cl_nav2z::Pose::update(), cl_nitrosz::Pose::update(), cl_nav2z::odom_tracker::CpOdomTracker::updateClearPath(), cl_nitrosz::odom_tracker::CpOdomTracker::updateClearPath(), cl_nav2z::odom_tracker::CpOdomTracker::updateRecordPath(), cl_nitrosz::odom_tracker::CpOdomTracker::updateRecordPath(), cl_nav2z::Pose::waitTransformUpdate(), and cl_nitrosz::Pose::waitTransformUpdate().
getName()
std::string smacc2::ISmaccComponent::getName () const virtual
Reimplemented in cl_nav2z::CpAmcl, and cl_nitrosz::CpAmcl.
Definition at line 46 of file smacc_component.cpp.
{
  std::string keyname = demangleSymbol(typeid(*this).name());
  return keyname;
}
References smacc2::introspection::demangleSymbol().
Referenced by cl_moveit2z::CpGraspingComponent::createGraspableBox(), cl_moveit2z::CpTrajectoryHistory::getLastTrajectory(), smacc2::components::CpTopicSubscriber< MessageType >::onInitialize(), cl_moveit2z::CpTrajectoryHistory::pushTrajectory(), cl_nav2z::CpWaypointNavigator::sendNextGoal(), and cl_nitrosz::CpWaypointNavigator::sendNextGoal().
getNode()
rclcpp::Node::SharedPtr smacc2::ISmaccComponent::getNode () protected
Definition at line 42 of file smacc_component.cpp.
{ return owner_->getNode(); }
References smacc2::ISmaccClient::getNode(), and owner_.
Referenced by cl_nav2z::odom_tracker::CpOdomTracker::clearPath(), cl_nitrosz::odom_tracker::CpOdomTracker::clearPath(), cl_nav2z::CpWaypointsVisualizer::createMarker(), cl_nitrosz::CpWaypointsVisualizer::createMarker(), cl_nav2z::CpWaypointsVisualizer::createMarkerLabel(), cl_nitrosz::CpWaypointsVisualizer::createMarkerLabel(), cl_nav2z::CpWaypointNavigatorBase::loadWaypointsFromYamlParameter(), cl_nitrosz::CpWaypointNavigatorBase::loadWaypointsFromYamlParameter(), smacc2::components::CpTopicSubscriber< MessageType >::onInitialize(), cl_nav2z::CpAmcl::onInitialize(), cl_nav2z::CpGoalCheckerSwitcher::onInitialize(), cl_nav2z::odom_tracker::CpOdomTracker::onInitialize(), cl_nav2z::CpPlannerSwitcher::onInitialize(), cl_nav2z::Pose::onInitialize(), cl_nav2z::CpWaypointsVisualizer::onInitialize(), cl_nitrosz::CpAmcl::onInitialize(), cl_nitrosz::CpGoalCheckerSwitcher::onInitialize(), cl_nitrosz::odom_tracker::CpOdomTracker::onInitialize(), cl_nitrosz::CpPlannerSwitcher::onInitialize(), cl_nitrosz::Pose::onInitialize(), cl_nitrosz::CpWaypointsVisualizer::onInitialize(), cl_nav2z::odom_tracker::CpOdomTracker::processOdometryMessage(), cl_nitrosz::odom_tracker::CpOdomTracker::processOdometryMessage(), cl_nav2z::CpCostmapSwitch::registerProxyFromDynamicReconfigureServer(), cl_nitrosz::CpCostmapSwitch::registerProxyFromDynamicReconfigureServer(), cl_nav2z::odom_tracker::CpOdomTracker::setStartPoint(), cl_nitrosz::odom_tracker::CpOdomTracker::setStartPoint(), cl_nav2z::Pose::update(), cl_nav2z::CpWaypointsVisualizer::update(), cl_nitrosz::Pose::update(), cl_nitrosz::CpWaypointsVisualizer::update(), cl_nav2z::odom_tracker::CpOdomTracker::updateConfiguration(), cl_nitrosz::odom_tracker::CpOdomTracker::updateConfiguration(), cl_nav2z::odom_tracker::CpOdomTracker::updateRecordPath(), cl_nitrosz::odom_tracker::CpOdomTracker::updateRecordPath(), cl_nav2z::Pose::waitTransformUpdate(), and cl_nitrosz::Pose::waitTransformUpdate().
getStateMachine()
ISmaccStateMachine * smacc2::ISmaccComponent::getStateMachine () protected
Definition at line 52 of file smacc_component.cpp.
{ return this->stateMachine_; }
References stateMachine_.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived(), smacc2::components::CpTopicSubscriber< MessageType >::onMessageReceived(), cl_nav2z::CpWaypointNavigator::sendNextGoal(), and cl_nitrosz::CpWaypointNavigator::sendNextGoal().
initialize()
void smacc2::ISmaccComponent::initialize (ISmaccClient * owner) private
Definition at line 29 of file smacc_component.cpp.
{
  owner_ = owner;
  this->onInitialize();
}
References onInitialize(), and owner_.
onInitialize()
void smacc2::ISmaccComponent::onInitialize () protected virtual
Reimplemented in smacc2::components::CpTopicPublisher< MessageType >, smacc2::components::CpTopicSubscriber< MessageType >, cl_nav2z::CpAmcl, cl_nav2z::CpCostmapSwitch, cl_nav2z::CpGoalCheckerSwitcher, cl_nav2z::odom_tracker::CpOdomTracker, cl_nav2z::CpPlannerSwitcher, cl_nav2z::Pose, cl_nav2z::CpWaypointNavigator, cl_nav2z::CpWaypointNavigatorBase, cl_nav2z::CpWaypointsVisualizer, cl_nitrosz::CpAmcl, cl_nitrosz::CpCostmapSwitch, cl_nitrosz::CpGoalCheckerSwitcher, cl_nitrosz::odom_tracker::CpOdomTracker, cl_nitrosz::CpPlannerSwitcher, cl_nitrosz::Pose, cl_nitrosz::CpWaypointNavigator, cl_nitrosz::CpWaypointNavigatorBase, and cl_nitrosz::CpWaypointsVisualizer.
Definition at line 35 of file smacc_component.cpp.
{}
Referenced by initialize().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc2::ISmaccComponent::onOrthogonalAllocation () inline protected
Definition at line 51 of file component.hpp.
  {
  }
postEvent() [1/2]
template<typename EventType > void smacc2::ISmaccComponent::postEvent () protected
Definition at line 37 of file smacc_component_impl.hpp.
{
  auto ev = new EventType();
  stateMachine_->postEvent(ev);
}
References smacc2::ISmaccStateMachine::postEvent(), and stateMachine_.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::onOrthogonalAllocation().
postEvent() [2/2]
template<typename EventType > void smacc2::ISmaccComponent::postEvent (const EventType & ev) protected
Definition at line 31 of file smacc_component_impl.hpp.
{
  stateMachine_->postEvent(ev);
}
References smacc2::ISmaccStateMachine::postEvent(), and stateMachine_.
requiresClient()
template<typename TClient > void smacc2::ISmaccComponent::requiresClient (TClient *& requiredClientStorage) protected
Definition at line 97 of file smacc_component_impl.hpp.
{
  this->owner_->requiresClient(requiredClientStorage);
}
References owner_, and smacc2::ISmaccClient::requiresClient().
requiresComponent() [1/2]
template<typename TComponent > void smacc2::ISmaccComponent::requiresComponent (std::string name, TComponent *& requiredComponentStorage, bool throwExceptionIfNotExist = false) protected
Definition at line 70 of file smacc_component_impl.hpp.
{
  requiredComponentStorage = this->owner_->getComponent<TComponent>(name);
  if (requiredComponentStorage == nullptr && throwExceptionIfNotExist)
  {
    RCLCPP_DEBUG_STREAM(
      this->getLogger(), std::string("Required component with name: '") + name + "'" +
                           demangleSymbol(typeid(TComponent).name()) +
                           " not found. Available components:");
    std::vector<std::shared_ptr<ISmaccComponent>> components;
    this->owner_->getComponents(components);
    for (auto c : components)
    {
      RCLCPP_DEBUG(this->getLogger(), " - Component %s", c->getName().c_str());
    }
    throw std::runtime_error(
      std::string("Component ") + demangleSymbol(typeid(TComponent).name()) +
      std::string(" not found"));
  }
}
References smacc2::introspection::demangleSymbol(), smacc2::ISmaccClient::getComponent(), smacc2::ISmaccClient::getComponents(), getLogger(), and owner_.
requiresComponent() [2/2]
template<typename TComponent > void smacc2::ISmaccComponent::requiresComponent (TComponent *& requiredComponentStorage, bool throwExceptionIfNotExist = false) protected
Definition at line 44 of file smacc_component_impl.hpp.
{
  requiredComponentStorage = this->owner_->getComponent<TComponent>();
  if (requiredComponentStorage == nullptr && throwExceptionIfNotExist)
  {
    RCLCPP_DEBUG_STREAM(
      this->getLogger(), std::string("Required component ") +
                           demangleSymbol(typeid(TComponent).name()) +
                           " not found. Available components:");
    std::vector<std::shared_ptr<ISmaccComponent>> components;
    this->owner_->getComponents(components);
    for (auto c : components)
    {
      RCLCPP_DEBUG(this->getLogger(), "- Component %s", c->getName().c_str());
    }
    throw std::runtime_error(
      std::string("Component ") + demangleSymbol(typeid(TComponent).name()) + " not found");
  }
}
References smacc2::introspection::demangleSymbol(), smacc2::ISmaccClient::getComponent(), smacc2::ISmaccClient::getComponents(), getLogger(), and owner_.
Referenced by cl_nav2z::CpWaypointsVisualizer::onInitialize(), and cl_nitrosz::CpWaypointsVisualizer::onInitialize().
setStateMachine()
void smacc2::ISmaccComponent::setStateMachine (ISmaccStateMachine * stateMachine) private
Definition at line 37 of file smacc_component.cpp.
{
  stateMachine_ = stateMachine;
}
References stateMachine_.
Friends And Related Symbol Documentation
ISmaccClient
friend class ISmaccClient friend
Definition at line 94 of file component.hpp.
ISmaccOrthogonal
friend class ISmaccOrthogonal friend
Definition at line 93 of file component.hpp.
Member Data Documentation
owner_
ISmaccClient* smacc2::ISmaccComponent::owner_ protected
Definition at line 83 of file component.hpp.
Referenced by createSiblingComponent(), createSiblingNamedComponent(), getLogger(), getNode(), initialize(), cl_nav2z::CpCostmapSwitch::onInitialize(), cl_nav2z::CpWaypointNavigator::onInitialize(), cl_nitrosz::CpCostmapSwitch::onInitialize(), cl_nitrosz::CpWaypointNavigator::onInitialize(), requiresClient(), requiresComponent(), requiresComponent(), cl_nav2z::CpWaypointNavigator::sendNextGoal(), and cl_nitrosz::CpWaypointNavigator::sendNextGoal().
stateMachine_
ISmaccStateMachine* smacc2::ISmaccComponent::stateMachine_ protected
Definition at line 81 of file component.hpp.
Referenced by getStateMachine(), postEvent(), postEvent(), and setStateMachine().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/component.hpp
smacc2/include/smacc2/impl/smacc_component_impl.hpp
smacc2/src/smacc2/smacc_component.cpp