SMACC2: cl_ros_publisher::CbDefaultPublishLoop Class Reference
cl_ros_publisher::CbDefaultPublishLoop Class Reference
#include <cb_default_publish_loop.hpp>
Public Member Functions
CbDefaultPublishLoop ()
template<typename TMessage >
CbDefaultPublishLoop (const TMessage &data)
template<typename TMessage >
void setMessage (const TMessage &data)
void onEntry () override
virtual void update ()
void onExit () override
Public Member Functions inherited from smacc2::SmaccClientBehavior
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Member Functions inherited from smacc2::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (rclcpp::Duration duration)
void executeUpdate (rclcpp::Node::SharedPtr node)
void setUpdatePeriod (rclcpp::Duration duration)
Private Attributes
std::function< void()> deferedPublishFn_
ClRosPublisher * client_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Member Functions inherited from smacc2::ISmaccUpdatable
Detailed Description
Definition at line 26 of file cb_default_publish_loop.hpp.
Constructor & Destructor Documentation
CbDefaultPublishLoop() [1/2]
cl_ros_publisher::CbDefaultPublishLoop::CbDefaultPublishLoop () inline
Definition at line 33 of file cb_default_publish_loop.hpp.
: deferedPublishFn_(nullptr) {}
CbDefaultPublishLoop() [2/2]
template<typename TMessage > cl_ros_publisher::CbDefaultPublishLoop::CbDefaultPublishLoop (const TMessage & data) inline
Definition at line 36 of file cb_default_publish_loop.hpp.
  {
    this->setMessage(data);
  }
References setMessage().
Member Function Documentation
onEntry()
void cl_ros_publisher::CbDefaultPublishLoop::onEntry () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 47 of file cb_default_publish_loop.hpp.
{ this->requiresClient(client_); }
References smacc2::ISmaccClientBehavior::requiresClient().
onExit()
void cl_ros_publisher::CbDefaultPublishLoop::onExit () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 57 of file cb_default_publish_loop.hpp.
{}
setMessage()
template<typename TMessage > void cl_ros_publisher::CbDefaultPublishLoop::setMessage (const TMessage & data) inline
Definition at line 42 of file cb_default_publish_loop.hpp.
  {
    deferedPublishFn_ = [this, data]() { this->client_->publish(data); };
  }
References deferedPublishFn_, and cl_ros_publisher::ClRosPublisher::publish().
Referenced by CbDefaultPublishLoop().
update()
virtual void cl_ros_publisher::CbDefaultPublishLoop::update () inline virtual
Implements smacc2::ISmaccUpdatable.
Definition at line 49 of file cb_default_publish_loop.hpp.
  {
    if (deferedPublishFn_ != nullptr)
    {
      deferedPublishFn_();
    }
  }
References deferedPublishFn_.
Member Data Documentation
client_
ClRosPublisher* cl_ros_publisher::CbDefaultPublishLoop::client_ private
Definition at line 30 of file cb_default_publish_loop.hpp.
deferedPublishFn_
std::function<void()> cl_ros_publisher::CbDefaultPublishLoop::deferedPublishFn_ private
Definition at line 29 of file cb_default_publish_loop.hpp.
Referenced by setMessage(), and update().
The documentation for this class was generated from the following file:
smacc2_client_library/ros_publisher_client/include/ros_publisher_client/client_behaviors/cb_default_publish_loop.hpp