SMACC2: cl_lifecyclenode::CbShutdown Class Reference
cl_lifecyclenode::CbShutdown Class Reference
#include <cb_shutdown.hpp>
Public Member Functions
CbShutdown ()
virtual ~CbShutdown ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Attributes
ClLifecycleNode * lifecycleNodeClient_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 28 of file cb_shutdown.hpp.
Constructor & Destructor Documentation
CbShutdown()
cl_lifecyclenode::CbShutdown::CbShutdown () inline
Definition at line 31 of file cb_shutdown.hpp.
{}
~CbShutdown()
virtual cl_lifecyclenode::CbShutdown::~CbShutdown () inline virtual
Definition at line 32 of file cb_shutdown.hpp.
{}
Member Function Documentation
onEntry()
virtual void cl_lifecyclenode::CbShutdown::onEntry () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 49 of file cb_shutdown.hpp.
{ lifecycleNodeClient_->shutdown(); }
References lifecycleNodeClient_, and cl_lifecyclenode::ClLifecycleNode::shutdown().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_lifecyclenode::CbShutdown::onOrthogonalAllocation () inline
Definition at line 35 of file cb_shutdown.hpp.
  {
    smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
    this->requiresClient(this->lifecycleNodeClient_);
    lifecycleNodeClient_->onTransitionOnShutdownSuccess_.connect([this]()
                                                                 { this->postSuccessEvent(); });
    lifecycleNodeClient_->onTransitionOnShutdownFailure_.connect([this]()
                                                                 { this->postFailureEvent(); });
    lifecycleNodeClient_->onTransitionOnShutdownError_.connect([this]()
                                                               { this->postFailureEvent(); });
  }
References lifecycleNodeClient_, cl_lifecyclenode::ClLifecycleNode::onTransitionOnShutdownError_, cl_lifecyclenode::ClLifecycleNode::onTransitionOnShutdownFailure_, cl_lifecyclenode::ClLifecycleNode::onTransitionOnShutdownSuccess_, smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), and smacc2::ISmaccClientBehavior::requiresClient().
Member Data Documentation
lifecycleNodeClient_
ClLifecycleNode* cl_lifecyclenode::CbShutdown::lifecycleNodeClient_ private
Definition at line 52 of file cb_shutdown.hpp.
Referenced by onEntry(), and onOrthogonalAllocation().
The documentation for this class was generated from the following file:
smacc2_client_library/lifecyclenode_client/include/lifecyclenode_client/client_behaviors/cb_shutdown.hpp