SMACC2: cl_moveit2z::ClMoveit2z Class Reference
cl_moveit2z::ClMoveit2z Class Reference
#include <cl_moveit2z.hpp>
Public Member Functions
ClMoveit2z (std::string groupName)
ClMoveit2z (const moveit::planning_interface::MoveGroupInterface::Options &options)
virtual ~ClMoveit2z ()
void onInitialize () override
void postEventMotionExecutionSucceded ()
void postEventMotionExecutionFailed ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TCallback , typename T >
boost::signals2::connection onMotionExecutionSuccedded (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onMotionExecutionFailed (TCallback callback, T *object)
const moveit::planning_interface::MoveGroupInterface::Options & getOptions () const
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Public Attributes
std::shared_ptr< moveit::planning_interface::MoveGroupInterface > moveGroupClientInterface
std::shared_ptr< moveit::planning_interface::PlanningSceneInterface > planningSceneInterface
Private Attributes
std::function< void()> postEventMotionExecutionSucceded_
std::function< void()> postEventMotionExecutionFailed_
smacc2::SmaccSignal< void()> onSucceded_
smacc2::SmaccSignal< void()> onFailed_
moveit::planning_interface::MoveGroupInterface::Options options_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Detailed Description
Definition at line 78 of file cl_moveit2z.hpp.
Constructor & Destructor Documentation
ClMoveit2z() [1/2]
cl_moveit2z::ClMoveit2z::ClMoveit2z (std::string groupName)
Definition at line 36 of file cl_moveit2z.cpp.
: options_(groupName) {}
ClMoveit2z() [2/2]
cl_moveit2z::ClMoveit2z::ClMoveit2z (const moveit::planning_interface::MoveGroupInterface::Options & options)
Definition at line 31 of file cl_moveit2z.cpp.
: options_(options)
{
}
~ClMoveit2z()
cl_moveit2z::ClMoveit2z::~ClMoveit2z () virtual
Definition at line 38 of file cl_moveit2z.cpp.
{}
Member Function Documentation
getOptions()
const moveit::planning_interface::MoveGroupInterface::Options & cl_moveit2z::ClMoveit2z::getOptions () const
Definition at line 58 of file cl_moveit2z.cpp.
{
  return options_;
}
References options_.
onInitialize()
void cl_moveit2z::ClMoveit2z::onInitialize () override virtual
Reimplemented from smacc2::ISmaccClient.
Definition at line 40 of file cl_moveit2z.cpp.
{
  moveGroupClientInterface = std::make_shared<MoveGroupInterface>(getNode(), options_);
  planningSceneInterface = std::make_shared<PlanningSceneInterface>(options_.move_group_namespace_);
}
References smacc2::ISmaccClient::getNode(), moveGroupClientInterface, options_, and planningSceneInterface.
onMotionExecutionFailed()
template<typename TCallback , typename T > boost::signals2::connection cl_moveit2z::ClMoveit2z::onMotionExecutionFailed (TCallback callback, T * object) inline
Definition at line 123 of file cl_moveit2z.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onFailed_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClient::getStateMachine(), and onFailed_.
onMotionExecutionSuccedded()
template<typename TCallback , typename T > boost::signals2::connection cl_moveit2z::ClMoveit2z::onMotionExecutionSuccedded (TCallback callback, T * object) inline
Definition at line 117 of file cl_moveit2z.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onSucceded_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClient::getStateMachine(), and onSucceded_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_moveit2z::ClMoveit2z::onOrthogonalAllocation () inline
Definition at line 101 of file cl_moveit2z.hpp.
  {
    postEventMotionExecutionSucceded_ = [=]()
    {
      this->onSucceded_();
      this->postEvent<EvMoveGroupMotionExecutionSucceded<TSourceObject, TOrthogonal>>();
    };
    postEventMotionExecutionFailed_ = [=]()
    {
      this->onFailed_();
      this->postEvent<EvMoveGroupMotionExecutionFailed<TSourceObject, TOrthogonal>>();
    };
  }
References onFailed_, onSucceded_, smacc2::ISmaccClient::postEvent(), postEventMotionExecutionFailed_, and postEventMotionExecutionSucceded_.
postEventMotionExecutionFailed()
void cl_moveit2z::ClMoveit2z::postEventMotionExecutionFailed ()
Definition at line 52 of file cl_moveit2z.cpp.
{
  RCLCPP_INFO(getLogger(), "[ClMoveit2z] Post Motion Failure Event");
  postEventMotionExecutionFailed_();
}
References smacc2::ISmaccClient::getLogger(), and postEventMotionExecutionFailed_.
Referenced by cl_moveit2z::CbMoveJoints::moveJoints(), cl_moveit2z::CbMoveEndEffectorRelative::moveRelative(), cl_moveit2z::CbMoveCartesianRelative::moveRelativeCartesian(), cl_moveit2z::CbMoveEndEffector::moveToAbsolutePose(), cl_moveit2z::CbMoveEndEffectorTrajectory::onEntry(), and cl_moveit2z::CbMoveEndEffectorTrajectory::onOrthogonalAllocation().
postEventMotionExecutionSucceded()
void cl_moveit2z::ClMoveit2z::postEventMotionExecutionSucceded ()
Definition at line 46 of file cl_moveit2z.cpp.
{
  RCLCPP_INFO(getLogger(), "[ClMoveit2z] Post Motion Success Event");
  postEventMotionExecutionSucceded_();
}
References smacc2::ISmaccClient::getLogger(), and postEventMotionExecutionSucceded_.
Referenced by cl_moveit2z::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_moveit2z::CbMoveJoints::moveJoints(), cl_moveit2z::CbMoveEndEffectorRelative::moveRelative(), cl_moveit2z::CbMoveCartesianRelative::moveRelativeCartesian(), and cl_moveit2z::CbMoveEndEffector::moveToAbsolutePose().
Member Data Documentation
moveGroupClientInterface
std::shared_ptr<moveit::planning_interface::MoveGroupInterface> cl_moveit2z::ClMoveit2z::moveGroupClientInterface
Definition at line 84 of file cl_moveit2z.hpp.
Referenced by cl_moveit2z::CbCircularPivotMotion::computeCurrentEndEffectorPoseRelativeToPivot(), cl_moveit2z::CbMoveEndEffectorTrajectory::computeJointSpaceTrajectory(), cl_moveit2z::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_moveit2z::CbMoveEndEffectorTrajectory::getCurrentEndEffectorPose(), cl_moveit2z::CbMoveNamedTarget::getNamedTargetValues(), cl_moveit2z::CbAttachObject::onEntry(), cl_moveit2z::CbDetachObject::onEntry(), cl_moveit2z::CbEndEffectorRotate::onEntry(), cl_moveit2z::CbMoveCartesianRelative::onEntry(), cl_moveit2z::CbMoveEndEffector::onEntry(), cl_moveit2z::CbMoveEndEffectorRelative::onEntry(), cl_moveit2z::CbMoveJoints::onEntry(), cl_moveit2z::CbMoveNamedTarget::onEntry(), and onInitialize().
onFailed_
smacc2::SmaccSignal<void()> cl_moveit2z::ClMoveit2z::onFailed_ private
Definition at line 135 of file cl_moveit2z.hpp.
Referenced by onMotionExecutionFailed(), and onOrthogonalAllocation().
onSucceded_
smacc2::SmaccSignal<void()> cl_moveit2z::ClMoveit2z::onSucceded_ private
Definition at line 134 of file cl_moveit2z.hpp.
Referenced by onMotionExecutionSuccedded(), and onOrthogonalAllocation().
options_
moveit::planning_interface::MoveGroupInterface::Options cl_moveit2z::ClMoveit2z::options_ private
Definition at line 138 of file cl_moveit2z.hpp.
Referenced by getOptions(), and onInitialize().
planningSceneInterface
std::shared_ptr<moveit::planning_interface::PlanningSceneInterface> cl_moveit2z::ClMoveit2z::planningSceneInterface
Definition at line 86 of file cl_moveit2z.hpp.
Referenced by cl_moveit2z::CbAttachObject::onEntry(), cl_moveit2z::CbDetachObject::onEntry(), and onInitialize().
postEventMotionExecutionFailed_
std::function<void()> cl_moveit2z::ClMoveit2z::postEventMotionExecutionFailed_ private
Definition at line 132 of file cl_moveit2z.hpp.
Referenced by onOrthogonalAllocation(), and postEventMotionExecutionFailed().
postEventMotionExecutionSucceded_
std::function<void()> cl_moveit2z::ClMoveit2z::postEventMotionExecutionSucceded_ private
Definition at line 131 of file cl_moveit2z.hpp.
Referenced by onOrthogonalAllocation(), and postEventMotionExecutionSucceded().
The documentation for this class was generated from the following files:
smacc2_client_library/moveit2z_client/include/moveit2z_client/cl_moveit2z.hpp
smacc2_client_library/moveit2z_client/src/moveit2z_client/cl_moveit2z.cpp