SMACC2: cl_move_group_interface::CbDetachObject Class Reference
cl_move_group_interface::CbDetachObject Class Reference
#include <cb_detach_object.hpp>
Public Member Functions
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 30 of file cb_detach_object.hpp.
Member Function Documentation
onEntry()
void cl_move_group_interface::CbDetachObject::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 26 of file cb_detach_object.cpp.
{
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] requesting components");
  cl_move_group_interface::CpGraspingComponent * graspingComponent;
  this->requiresComponent(graspingComponent);
  cl_move_group_interface::ClMoveGroup * moveGroupClient;
  this->requiresClient(moveGroupClient);
  auto & planningSceneInterface = moveGroupClient->planningSceneInterface;
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] requesting detach object");
  auto res = moveGroupClient->moveGroupClientInterface->detachObject(
    *(graspingComponent->currentAttachedObjectName));
  planningSceneInterface->removeCollisionObjects({*(graspingComponent->currentAttachedObjectName)});
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] detach result: " << res);
  if (res)
    this->postSuccessEvent();
  else
    this->postFailureEvent();
}
References cl_move_group_interface::CpGraspingComponent::currentAttachedObjectName, smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), cl_move_group_interface::ClMoveGroup::moveGroupClientInterface, cl_move_group_interface::ClMoveGroup::planningSceneInterface, smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), smacc2::ISmaccClientBehavior::requiresClient(), and smacc2::ISmaccClientBehavior::requiresComponent().
onExit()
void cl_move_group_interface::CbDetachObject::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 52 of file cb_detach_object.cpp.
{}
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_detach_object.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_detach_object.cpp