SMACC2: cl_nav2z::CbStopNavigation Class Reference
cl_nav2z::CbStopNavigation Class Reference
#include <cb_stop_navigation.hpp>
Public Member Functions
CbStopNavigation ()
void onEntry () override
void onExit () override
Public Member Functions inherited from cl_nav2z::CbNavigateGlobalPosition
CbNavigateGlobalPosition ()
CbNavigateGlobalPosition (float x, float y, float yaw, std::optional< CbNavigateGlobalPositionOptions > options=std::nullopt)
void setGoal (const geometry_msgs::msg::Pose &pose)
virtual void onEntry () override
void onExit () override
void execute ()
Public Member Functions inherited from cl_nav2z::CbNav2ZClientBehaviorBase
virtual ~CbNav2ZClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Additional Inherited Members
Public Attributes inherited from cl_nav2z::CbNavigateGlobalPosition
float goalYaw
CbNavigateGlobalPositionOptions options
geometry_msgs::msg::Point goalPosition
Protected Member Functions inherited from cl_nav2z::CbNav2ZClientBehaviorBase
void sendGoal (ClNav2Z::Goal &goal)
void cancelGoal ()
bool isOwnActionResponse (const ClNav2Z::WrappedResult &)
virtual void onNavigationResult (const ClNav2Z::WrappedResult &)
virtual void onNavigationActionSuccess (const ClNav2Z::WrappedResult &)
virtual void onNavigationActionAbort (const ClNav2Z::WrappedResult &)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Attributes inherited from cl_nav2z::CbNav2ZClientBehaviorBase
cl_nav2z::ClNav2Z * nav2zClient_
cl_nav2z::ClNav2Z::SmaccNavigateResultSignal::SharedPtr navigationCallback_
rclcpp_action::ResultCode navigationResult_
std::shared_future< std::shared_ptr< rclcpp_action::ClientGoalHandle< nav2_msgs::action::NavigateToPose > > > goalHandleFuture_
Detailed Description
Definition at line 30 of file cb_stop_navigation.hpp.
Constructor & Destructor Documentation
CbStopNavigation()
cl_nav2z::CbStopNavigation::CbStopNavigation ()
Definition at line 32 of file cb_stop_navigation.cpp.
{}
Member Function Documentation
onEntry()
void cl_nav2z::CbStopNavigation::onEntry () override virtual
Reimplemented from cl_nav2z::CbNavigateGlobalPosition.
Definition at line 34 of file cb_stop_navigation.cpp.
{
  // this->sendGoal(goal);
  // this->cancelGoal();
  cl_nav2z::Pose * poseComponent;
  this->requiresComponent(poseComponent);
  this->setGoal(poseComponent->toPoseMsg());
  CbNavigateGlobalPosition::onEntry();
  // this->sendGoal(goal);
}
References cl_nav2z::CbNavigateGlobalPosition::onEntry(), smacc2::ISmaccClientBehavior::requiresComponent(), cl_nav2z::CbNavigateGlobalPosition::setGoal(), and cl_nav2z::Pose::toPoseMsg().
onExit()
void cl_nav2z::CbStopNavigation::onExit () override virtual
Reimplemented from cl_nav2z::CbNavigateGlobalPosition.
Definition at line 50 of file cb_stop_navigation.cpp.
{}
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/client_behaviors/cb_stop_navigation.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/client_behaviors/cb_stop_navigation.cpp