SMACC2: smacc2::client_behaviors::CbSequence Class Reference
smacc2::client_behaviors::CbSequence Class Reference
#include <cb_sequence.hpp>
Public Member Functions
CbSequence ()
void onEntry () override
void onExit () override
template<typename TOrthogonal , typename TBehavior , typename... Args>
CbSequence * then (Args &&... args)
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Member Functions
void onSubNodeSuccess ()
void onSubNodeAbort ()
void recursiveConsumeNext ()
Private Attributes
std::list< std::function< std::shared_ptr< smacc2::SmaccAsyncClientBehavior >()> > sequenceNodes_
boost::signals2::connection conn_
boost::signals2::connection conn2_
std::shared_ptr< smacc2::SmaccAsyncClientBehavior > bh_
std::atomic< int > consume_ {0}
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 31 of file cb_sequence.hpp.
Constructor & Destructor Documentation
CbSequence()
smacc2::client_behaviors::CbSequence::CbSequence ()
Definition at line 30 of file cb_sequence.cpp.
{}
Member Function Documentation
onEntry()
void smacc2::client_behaviors::CbSequence::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 60 of file cb_sequence.cpp.
{
  this->recursiveConsumeNext();
  while (!sequenceNodes_.empty())
  {
    bool is_shutdown_requested = this->isShutdownRequested();
    if (is_shutdown_requested)
    {
      break;
    }
    rclcpp::sleep_for(std::chrono::milliseconds(200));
    RCLCPP_INFO_THROTTLE(
      getLogger(), *(getNode()->get_clock()), 1000,
      "[CbSequence %ld] Waiting for subnodes to finish %ld. Current head Behavior: %s ", (long)this,
      sequenceNodes_.size(), demangleType(&typeid(*bh_)).c_str());
    if (consume_)
    {
      // bh_->waitOnEntryThread();
      this->conn_.disconnect();
      this->conn2_.disconnect();
      sequenceNodes_.pop_front();
      consume_--;
      if (sequenceNodes_.size() > 0)
      {
        this->recursiveConsumeNext();
      }
    }
  }
  if (sequenceNodes_.empty())
  {
    RCLCPP_INFO(getLogger(), "[CbSequence %ld] All subnodes finished", (long)this);
    this->postSuccessEvent();
  }
  else
  {
    RCLCPP_INFO(getLogger(), "[CbSequence %ld] Aborting", (long)this);
    this->postFailureEvent();
  }
}
References bh_, conn2_, conn_, consume_, smacc2::introspection::demangleType(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), smacc2::SmaccAsyncClientBehavior::isShutdownRequested(), smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), recursiveConsumeNext(), and sequenceNodes_.
onExit()
void smacc2::client_behaviors::CbSequence::onExit () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 55 of file cb_sequence.hpp.
{ sequenceNodes_.clear(); }
References sequenceNodes_.
onSubNodeAbort()
void smacc2::client_behaviors::CbSequence::onSubNodeAbort () private
Definition at line 112 of file cb_sequence.cpp.
{
  RCLCPP_INFO(
    getLogger(), "[CbSequence %ld] Abort NextCbSequence %ld", (long)this, sequenceNodes_.size());
  // bh_->waitOnEntryThread();
  this->conn_.disconnect();
  this->conn2_.disconnect();
  this->postFailureEvent();
  RCLCPP_INFO(
    getLogger(), "[CbSequence %ld] Abort NextCbSequence requesting for force finish", (long)this);
  this->requestForceFinish();
  consume_++;
}
References conn2_, conn_, consume_, smacc2::ISmaccClientBehavior::getLogger(), smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::requestForceFinish(), and sequenceNodes_.
Referenced by recursiveConsumeNext().
onSubNodeSuccess()
void smacc2::client_behaviors::CbSequence::onSubNodeSuccess () private
Definition at line 105 of file cb_sequence.cpp.
{
  RCLCPP_INFO(
    getLogger(), "[CbSequence %ld] Success NextCbSequence %ld", (long)this, sequenceNodes_.size());
  consume_++;
}
References consume_, smacc2::ISmaccClientBehavior::getLogger(), and sequenceNodes_.
Referenced by recursiveConsumeNext().
recursiveConsumeNext()
void smacc2::client_behaviors::CbSequence::recursiveConsumeNext () private
Definition at line 32 of file cb_sequence.cpp.
{
  RCLCPP_INFO(
    getLogger(), "[SequenceNode %ld] next onEntry: %ld", (long)this, sequenceNodes_.size());
  auto first = sequenceNodes_.front();
  auto onDelayedConfigureFn = first;
  RCLCPP_INFO(getLogger(), "[SequenceNode %ld] Behavior on delayed sequence configure", (long)this);
  bh_ = onDelayedConfigureFn();
  std::string currentNodeName = bh_->getName();
  RCLCPP_INFO(getLogger(), "[SequenceNode %ld] Subscribing OnSuccess", (long)this);
  this->conn_ = bh_->onSuccess(&CbSequence::onSubNodeSuccess, this);
  this->conn2_ = bh_->onFailure(&CbSequence::onSubNodeAbort, this);
  RCLCPP_INFO(
    getLogger(), "[SequenceNode %ld] subnode %s on entry", (long)this, currentNodeName.c_str());
  bh_->executeOnEntry();
  RCLCPP_INFO(
    getLogger(), "[SequenceNode %ld] subnode %s on entry finished", (long)this,
    currentNodeName.c_str());
  bh_->waitOnEntryThread(false);  // we do not request to finish to keep on subscriptions
  RCLCPP_INFO(
    getLogger(), "[SequenceNode %ld] subnode %s thread finished", (long)this,
    currentNodeName.c_str());
}
References bh_, conn2_, conn_, smacc2::ISmaccClientBehavior::getLogger(), onSubNodeAbort(), onSubNodeSuccess(), and sequenceNodes_.
Referenced by onEntry().
then()
template<typename TOrthogonal , typename TBehavior , typename... Args> CbSequence * smacc2::client_behaviors::CbSequence::then (Args &&... args) inline
Definition at line 58 of file cb_sequence.hpp.
  {
    std::function<std::shared_ptr<smacc2::SmaccAsyncClientBehavior>()> delayedCBFactoryFn =
      [this, args...]()
    {
      RCLCPP_INFO(
        getLogger(), "[CbSequence] then creating new sub behavior %s ",
        demangleSymbol<TBehavior>().c_str());
      auto createdBh = std::shared_ptr<TBehavior>(new TBehavior(args...));
      this->getCurrentState()->getOrthogonal<TOrthogonal>()->addClientBehavior(createdBh);
      createdBh->template onOrthogonalAllocation<TOrthogonal, TBehavior>();
      return createdBh;
    };
    sequenceNodes_.push_back(delayedCBFactoryFn);
    return this;
  }
References smacc2::ISmaccClientBehavior::getCurrentState(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccState::getOrthogonal(), and sequenceNodes_.
Member Data Documentation
bh_
std::shared_ptr<smacc2::SmaccAsyncClientBehavior> smacc2::client_behaviors::CbSequence::bh_ private
Definition at line 88 of file cb_sequence.hpp.
Referenced by onEntry(), and recursiveConsumeNext().
conn2_
boost::signals2::connection smacc2::client_behaviors::CbSequence::conn2_ private
Definition at line 86 of file cb_sequence.hpp.
Referenced by onEntry(), onSubNodeAbort(), and recursiveConsumeNext().
conn_
boost::signals2::connection smacc2::client_behaviors::CbSequence::conn_ private
Definition at line 85 of file cb_sequence.hpp.
Referenced by onEntry(), onSubNodeAbort(), and recursiveConsumeNext().
consume_
std::atomic<int> smacc2::client_behaviors::CbSequence::consume_ {0} private
Definition at line 89 of file cb_sequence.hpp.
Referenced by onEntry(), onSubNodeAbort(), and onSubNodeSuccess().
sequenceNodes_
std::list<std::function<std::shared_ptr<smacc2::SmaccAsyncClientBehavior>()> > smacc2::client_behaviors::CbSequence::sequenceNodes_ private
Definition at line 84 of file cb_sequence.hpp.
Referenced by onEntry(), onExit(), onSubNodeAbort(), onSubNodeSuccess(), recursiveConsumeNext(), and then().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/client_behaviors/cb_sequence.hpp
smacc2/src/smacc2/client_behaviors/cb_sequence.cpp