SMACC2: smacc2::client_bases::SmaccServiceServerClient< TService > Class Template Reference
smacc2::client_bases::SmaccServiceServerClient< TService > Class Template Reference
#include <smacc_service_server_client.hpp>
Public Member Functions
SmaccServiceServerClient ()
SmaccServiceServerClient (std::string service_name)
virtual ~SmaccServiceServerClient ()
template<typename T >
boost::signals2::connection onServiceRequestReceived (void(T::*callback)(const std::shared_ptr< typename TService::Request >, std::shared_ptr< typename TService::Response >), T *object)
void onInitialize () override
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Public Attributes
std::optional< std::string > serviceName_
smacc2::SmaccSignal< void(const std::shared_ptr< typename TService::Request >, std::shared_ptr< typename TService::Response >)> onServiceRequestReceived_
Private Types
using TServiceRequest = typename TService::Request
using TServiceResponse = typename TService::Response
Private Member Functions
void serviceCallback (const std::shared_ptr< typename TService::Request > req, std::shared_ptr< typename TService::Response > res)
Private Attributes
rclcpp::Service< TService >::SharedPtr server_
bool initialized_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Detailed Description
template<typename TService>
class smacc2::client_bases::SmaccServiceServerClient< TService >
Definition at line 32 of file smacc_service_server_client.hpp.
Member Typedef Documentation
TServiceRequest
template<typename TService > using smacc2::client_bases::SmaccServiceServerClient< TService >::TServiceRequest = typename TService::Request private
Definition at line 34 of file smacc_service_server_client.hpp.
TServiceResponse
template<typename TService > using smacc2::client_bases::SmaccServiceServerClient< TService >::TServiceResponse = typename TService::Response private
Definition at line 35 of file smacc_service_server_client.hpp.
Constructor & Destructor Documentation
SmaccServiceServerClient() [1/2]
template<typename TService > smacc2::client_bases::SmaccServiceServerClient< TService >::SmaccServiceServerClient () inline
Definition at line 39 of file smacc_service_server_client.hpp.
{ initialized_ = false; }
References smacc2::client_bases::SmaccServiceServerClient< TService >::initialized_.
SmaccServiceServerClient() [2/2]
template<typename TService > smacc2::client_bases::SmaccServiceServerClient< TService >::SmaccServiceServerClient (std::string service_name) inline
Definition at line 40 of file smacc_service_server_client.hpp.
  {
    serviceName_ = service_name;
    initialized_ = false;
  }
References smacc2::client_bases::SmaccServiceServerClient< TService >::initialized_, and smacc2::client_bases::SmaccServiceServerClient< TService >::serviceName_.
~SmaccServiceServerClient()
template<typename TService > virtual smacc2::client_bases::SmaccServiceServerClient< TService >::~SmaccServiceServerClient () inline virtual
Definition at line 46 of file smacc_service_server_client.hpp.
{}
Member Function Documentation
onInitialize()
template<typename TService > void smacc2::client_bases::SmaccServiceServerClient< TService >::onInitialize () inline override virtual
Reimplemented from smacc2::ISmaccClient.
Definition at line 64 of file smacc_service_server_client.hpp.
  {
    if (!initialized_)
    {
      if (!serviceName_)
      {
        RCLCPP_ERROR_STREAM(
          getLogger(),
          "[" << this->getName() << "] service server with no service name set. Skipping.");
      }
      else
      {
        RCLCPP_INFO_STREAM(
          getLogger(), "[" << this->getName() << "] Client Service: " << *serviceName_);
        server_ = getNode()->create_service<TService>(
          *serviceName_, std::bind(
                           &SmaccServiceServerClient<TService>::serviceCallback, this,
                           std::placeholders::_1, std::placeholders::_2));
        this->initialized_ = true;
      }
    }
  }
References smacc2::ISmaccClient::getLogger(), smacc2::ISmaccClient::getName(), smacc2::ISmaccClient::getNode(), smacc2::client_bases::SmaccServiceServerClient< TService >::initialized_, smacc2::client_bases::SmaccServiceServerClient< TService >::server_, and smacc2::client_bases::SmaccServiceServerClient< TService >::serviceName_.
onServiceRequestReceived()
template<typename TService > template<typename T > boost::signals2::connection smacc2::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived (void(T::* callback)(const std::shared_ptr< typename TService::Request >, std::shared_ptr< typename TService::Response >), T * object) inline
Definition at line 54 of file smacc_service_server_client.hpp.
  {
    return this->getStateMachine()->createSignalConnection(
      onServiceRequestReceived_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClient::getStateMachine(), and smacc2::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived_.
serviceCallback()
template<typename TService > void smacc2::client_bases::SmaccServiceServerClient< TService >::serviceCallback (const std::shared_ptr< typename TService::Request > req, std::shared_ptr< typename TService::Response > res) inline private
Definition at line 90 of file smacc_service_server_client.hpp.
  {
    onServiceRequestReceived_(req, res);
  }
References smacc2::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived_.
Member Data Documentation
initialized_
template<typename TService > bool smacc2::client_bases::SmaccServiceServerClient< TService >::initialized_ private
Definition at line 97 of file smacc_service_server_client.hpp.
Referenced by smacc2::client_bases::SmaccServiceServerClient< TService >::onInitialize(), smacc2::client_bases::SmaccServiceServerClient< TService >::SmaccServiceServerClient(), and smacc2::client_bases::SmaccServiceServerClient< TService >::SmaccServiceServerClient().
onServiceRequestReceived_
template<typename TService > smacc2::SmaccSignal<void(const std::shared_ptr<typename TService::Request>, std::shared_ptr<typename TService::Response>)> smacc2::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived_
Definition at line 51 of file smacc_service_server_client.hpp.
Referenced by smacc2::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived(), and smacc2::client_bases::SmaccServiceServerClient< TService >::serviceCallback().
server_
template<typename TService > rclcpp::Service<TService>::SharedPtr smacc2::client_bases::SmaccServiceServerClient< TService >::server_ private
Definition at line 96 of file smacc_service_server_client.hpp.
Referenced by smacc2::client_bases::SmaccServiceServerClient< TService >::onInitialize().
serviceName_
template<typename TService > std::optional<std::string> smacc2::client_bases::SmaccServiceServerClient< TService >::serviceName_
Definition at line 38 of file smacc_service_server_client.hpp.
Referenced by smacc2::client_bases::SmaccServiceServerClient< TService >::onInitialize(), and smacc2::client_bases::SmaccServiceServerClient< TService >::SmaccServiceServerClient().
The documentation for this class was generated from the following file:
smacc2/include/smacc2/client_bases/smacc_service_server_client.hpp