SMACC2: cl_nitrosz::CbNavigateNextWaypointUntilReached Class Reference
cl_nitrosz::CbNavigateNextWaypointUntilReached Class Reference
#include <cb_navigate_next_waypoint_until_reached.hpp>
Public Member Functions
CbNavigateNextWaypointUntilReached (std::string goalWaypointName, std::optional< NavigateNextWaypointOptions > options=std::nullopt)
virtual ~CbNavigateNextWaypointUntilReached ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onEntry () override
void onExit () override
void onNavigationActionSuccess (const ClNitrosZ::WrappedResult &r) override
Public Member Functions inherited from cl_nitrosz::CbNavigateNextWaypoint
CbNavigateNextWaypoint (std::optional< NavigateNextWaypointOptions > options=std::nullopt)
virtual ~CbNavigateNextWaypoint ()
Public Member Functions inherited from cl_nitrosz::CbNav2ZClientBehaviorBase
virtual ~CbNav2ZClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
Private Attributes
std::string goalWaypointName_
std::function< void()> postEvGoalWaypointReached_
Additional Inherited Members
Protected Member Functions inherited from cl_nitrosz::CbNav2ZClientBehaviorBase
void sendGoal (ClNitrosZ::Goal &goal)
void cancelGoal ()
bool isOwnActionResponse (const ClNitrosZ::WrappedResult &)
virtual void onNavigationResult (const ClNitrosZ::WrappedResult &)
virtual void onNavigationActionAbort (const ClNitrosZ::WrappedResult &)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Attributes inherited from cl_nitrosz::CbNavigateNextWaypoint
CpWaypointNavigator * waypointsNavigator_
NavigateNextWaypointOptions options_
cl_nitrosz::ClNitrosZ::SmaccNavigateResultSignal::SharedPtr navigationCallback_
Protected Attributes inherited from cl_nitrosz::CbNav2ZClientBehaviorBase
cl_nitrosz::ClNitrosZ * nitroszClient_
cl_nitrosz::ClNitrosZ::SmaccNavigateResultSignal::SharedPtr navigationCallback_
rclcpp_action::ResultCode navigationResult_
std::shared_future< std::shared_ptr< rclcpp_action::ClientGoalHandle< nav2_msgs::action::NavigateToPose > > > goalHandleFuture_
Detailed Description
Definition at line 31 of file cb_navigate_next_waypoint_until_reached.hpp.
Constructor & Destructor Documentation
CbNavigateNextWaypointUntilReached()
cl_nitrosz::CbNavigateNextWaypointUntilReached::CbNavigateNextWaypointUntilReached (std::string goalWaypointName, std::optional< NavigateNextWaypointOptions > options = std::nullopt)
Definition at line 25 of file cb_navigate_next_waypoint_until_reached.cpp.
: CbNavigateNextWaypoint(options), goalWaypointName_(goalWaypointName)
{
}
~CbNavigateNextWaypointUntilReached()
cl_nitrosz::CbNavigateNextWaypointUntilReached::~CbNavigateNextWaypointUntilReached () virtual
Definition at line 31 of file cb_navigate_next_waypoint_until_reached.cpp.
{}
Member Function Documentation
onEntry()
void cl_nitrosz::CbNavigateNextWaypointUntilReached::onEntry () override virtual
Reimplemented from cl_nitrosz::CbNavigateNextWaypoint.
Definition at line 33 of file cb_navigate_next_waypoint_until_reached.cpp.
{ CbNavigateNextWaypoint::onEntry(); }
References cl_nitrosz::CbNavigateNextWaypoint::onEntry().
onExit()
void cl_nitrosz::CbNavigateNextWaypointUntilReached::onExit () override virtual
Reimplemented from cl_nitrosz::CbNavigateNextWaypoint.
Definition at line 35 of file cb_navigate_next_waypoint_until_reached.cpp.
{ CbNavigateNextWaypoint::onExit(); }
References cl_nitrosz::CbNavigateNextWaypoint::onExit().
onNavigationActionSuccess()
void cl_nitrosz::CbNavigateNextWaypointUntilReached::onNavigationActionSuccess (const ClNitrosZ::WrappedResult & r) inline override virtual
Reimplemented from cl_nitrosz::CbNav2ZClientBehaviorBase.
Definition at line 58 of file cb_navigate_next_waypoint_until_reached.hpp.
  {
    // if (!isOwnActionResponse(r))
    // {
    //   RCLCPP_WARN(
    //     getLogger(), "[%s] Propagating success event skipped. Action response is not ours.",
    //     getName().c_str());
    //   return;
    // }
    navigationResult_ = r.code;
    RCLCPP_INFO(
      getLogger(), "[%s] Propagating success event from action server", getName().c_str());
    waypointsNavigator_ = nitroszClient_->getComponent<CpWaypointNavigator>();
    auto current_waypoint_name = waypointsNavigator_->getCurrentWaypointName();
    if (current_waypoint_name == this->goalWaypointName_)
    {
      RCLCPP_INFO(
        getLogger(),
        "[CbNavigateNextWaypointUntilReached] GoalReached current iteration waypoint i: %ld with "
        "name '%s'",
        waypointsNavigator_->getCurrentWaypointIndex(), current_waypoint_name->c_str());
      this->postEvGoalWaypointReached_();
    }
    else
    {
      RCLCPP_INFO(
        getLogger(),
        "[CbNavigateNextWaypointUntilReached] goal:'%s' current:'%s'. keep navigating.",
        goalWaypointName_.c_str(), current_waypoint_name->c_str());
    }
    this->postSuccessEvent();
  }
References smacc2::ISmaccClient::getComponent(), cl_nitrosz::CpWaypointNavigatorBase::getCurrentWaypointIndex(), cl_nitrosz::CpWaypointNavigatorBase::getCurrentWaypointName(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), goalWaypointName_, cl_nitrosz::CbNav2ZClientBehaviorBase::navigationResult_, cl_nitrosz::CbNav2ZClientBehaviorBase::nitroszClient_, postEvGoalWaypointReached_, smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), and cl_nitrosz::CbNavigateNextWaypoint::waypointsNavigator_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_nitrosz::CbNavigateNextWaypointUntilReached::onOrthogonalAllocation () inline
Definition at line 41 of file cb_navigate_next_waypoint_until_reached.hpp.
  {
    this->requiresClient(nitroszClient_);
    CbNavigateNextWaypoint::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
    postEvGoalWaypointReached_ = [this]()
    {
      this->postEvent<EvGoalWaypointReached<TSourceObject, TOrthogonal>>();
      // nitroszClient_->onSucceeded(&CbNavigateNextWaypointUntilReached::onWaypointReached, this);
    };
  }
References cl_nitrosz::CbNav2ZClientBehaviorBase::nitroszClient_, postEvGoalWaypointReached_, and smacc2::ISmaccClientBehavior::requiresClient().
Member Data Documentation
goalWaypointName_
std::string cl_nitrosz::CbNavigateNextWaypointUntilReached::goalWaypointName_ private
Definition at line 99 of file cb_navigate_next_waypoint_until_reached.hpp.
Referenced by onNavigationActionSuccess().
postEvGoalWaypointReached_
std::function<void()> cl_nitrosz::CbNavigateNextWaypointUntilReached::postEvGoalWaypointReached_ private
Definition at line 101 of file cb_navigate_next_waypoint_until_reached.hpp.
Referenced by onNavigationActionSuccess(), and onOrthogonalAllocation().
The documentation for this class was generated from the following files:
smacc2_client_library/nitrosz_client/nitrosz_client/include/nitrosz_client/client_behaviors/cb_navigate_next_waypoint_until_reached.hpp
smacc2_client_library/nitrosz_client/nitrosz_client/src/nitrosz_client/client_behaviors/cb_navigate_next_waypoint_until_reached.cpp