SMACC2: cl_http::CbHttpRequestBase Class Reference
cl_http::CbHttpRequestBase Class Reference
#include <cb_http_request.hpp>
Public Member Functions
CbHttpRequestBase (const ClHttp::kHttpRequestMethod http_request_type)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual void runtimeConfigure () override
virtual void onResponseReceived (const ClHttp::TResponse &response)
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc2::SmaccClientBehavior
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Attributes
const ClHttp::kHttpRequestMethod kRequestType
ClHttp * cl_http_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 30 of file cb_http_request.hpp.
Constructor & Destructor Documentation
CbHttpRequestBase()
cl_http::CbHttpRequestBase::CbHttpRequestBase (const ClHttp::kHttpRequestMethod http_request_type) inline
Definition at line 33 of file cb_http_request.hpp.
  : kRequestType(http_request_type)
  {
  }
Member Function Documentation
onEntry()
virtual void cl_http::CbHttpRequestBase::onEntry () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 51 of file cb_http_request.hpp.
{ cl_http_->makeRequest(kRequestType); }
References cl_http_, kRequestType, and cl_http::ClHttp::makeRequest().
onExit()
virtual void cl_http::CbHttpRequestBase::onExit () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 53 of file cb_http_request.hpp.
{}
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_http::CbHttpRequestBase::onOrthogonalAllocation () inline
Definition at line 39 of file cb_http_request.hpp.
  {
  }
onResponseReceived()
virtual void cl_http::CbHttpRequestBase::onResponseReceived (const ClHttp::TResponse & response) inline virtual
Definition at line 49 of file cb_http_request.hpp.
{}
Referenced by runtimeConfigure().
runtimeConfigure()
virtual void cl_http::CbHttpRequestBase::runtimeConfigure () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 43 of file cb_http_request.hpp.
  {
    this->requiresClient(cl_http_);
    cl_http_->onResponseReceived(&CbHttpRequestBase::onResponseReceived, this);
  }
References cl_http_, onResponseReceived(), cl_http::ClHttp::onResponseReceived(), and smacc2::ISmaccClientBehavior::requiresClient().
Member Data Documentation
cl_http_
ClHttp* cl_http::CbHttpRequestBase::cl_http_ private
Definition at line 58 of file cb_http_request.hpp.
Referenced by onEntry(), and runtimeConfigure().
kRequestType
const ClHttp::kHttpRequestMethod cl_http::CbHttpRequestBase::kRequestType private
Definition at line 56 of file cb_http_request.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following file:
smacc2_client_library/http_client/include/http_client/client_behaviors/cb_http_request.hpp