SMACC2: smacc2::client_bases::ClRosLaunch Class Reference
smacc2::client_bases::ClRosLaunch Class Reference
#include <smacc_ros_launch_client.hpp>
Public Member Functions
ClRosLaunch (std::string packageName, std::string launchFilename)
virtual ~ClRosLaunch ()
void launch ()
void stop ()
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void onInitialize ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Static Public Member Functions
static std::future< std::string > executeRosLaunch (std::string packageName, std::string launchFilename, std::function< bool()> cancelCondition)
Public Attributes
std::string packageName_
std::string launchFileName_
Protected Types
typedef std::function< void > cancelCallback
Protected Attributes
std::future< std::string > result_
std::atomic< bool > cancellationToken_ = ATOMIC_VAR_INIT(false)
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Static Protected Attributes
static std::map< std::future< void >, cancelCallback > detached_futures_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Detailed Description
Definition at line 33 of file smacc_ros_launch_client.hpp.
Member Typedef Documentation
cancelCallback
typedef std::function<void> smacc2::client_bases::ClRosLaunch::cancelCallback protected
Definition at line 54 of file smacc_ros_launch_client.hpp.
Constructor & Destructor Documentation
ClRosLaunch()
smacc2::client_bases::ClRosLaunch::ClRosLaunch (std::string packageName, std::string launchFilename)
Definition at line 27 of file smacc_ros_launch_client.cpp.
: packageName_(packageName), launchFileName_(launchFilename), cancellationToken_(false)
{
}
~ClRosLaunch()
smacc2::client_bases::ClRosLaunch::~ClRosLaunch () virtual
Definition at line 32 of file smacc_ros_launch_client.cpp.
{}
Member Function Documentation
executeRosLaunch()
std::future< std::string > smacc2::client_bases::ClRosLaunch::executeRosLaunch (std::string packageName, std::string launchFilename, std::function< bool()> cancelCondition) static
Definition at line 42 of file smacc_ros_launch_client.cpp.
{
  return std::async(
    std::launch::async,
    [=]()
    {
      RCLCPP_WARN_STREAM(
        rclcpp::get_logger("smacc2"), "[ClRosLaunch static] starting ros launch thread ");
      std::stringstream cmd;
      cmd << "ros2 launch " << packageName << " " << launchFileName;
      std::array<char, 128> buffer;
      std::string result;
      std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd.str().c_str(), "r"), pclose);
      if (!pipe)
      {
        throw std::runtime_error("popen() failed!");
      }
      std::stringstream ss;
      bool cancelled = false;
      try
      {
        while (fgets(buffer.data(), buffer.size(), pipe.get()) != nullptr &&
               !(cancelled = cancelCondition()))
        {
          ss << buffer.data();
          if (cancelled)  // break_pipe
          {
            RCLCPP_WARN_STREAM(
              rclcpp::get_logger("smacc2"), "[ClRosLaunch static] cancelling ros launch thread ");
            // break pipe
            pclose(pipe.release());
            break;
          }
        }
      }
      catch (const std::exception & e)
      {
        std::cerr << e.what() << '\n';
      }
      result = ss.str();
      RCLCPP_WARN_STREAM(
        rclcpp::get_logger("smacc2"), "[ClRosLaunch static]] RESULT = \n " << ss.str());
      return result;
    });
}
Referenced by launch(), and smacc2::client_behaviors::CbRosLaunch::onEntry().
launch()
void smacc2::client_bases::ClRosLaunch::launch ()
Definition at line 34 of file smacc_ros_launch_client.cpp.
{
  this->result_ = executeRosLaunch(
    packageName_, launchFileName_, [this]() { return this->cancellationToken_.load(); });
}
References cancellationToken_, executeRosLaunch(), launchFileName_, packageName_, and result_.
Referenced by smacc2::client_behaviors::CbRosLaunch::onEntry().
stop()
void smacc2::client_bases::ClRosLaunch::stop ()
Definition at line 40 of file smacc_ros_launch_client.cpp.
{ cancellationToken_.store(true); }
References cancellationToken_.
Member Data Documentation
cancellationToken_
std::atomic<bool> smacc2::client_bases::ClRosLaunch::cancellationToken_ = ATOMIC_VAR_INIT(false) protected
Definition at line 58 of file smacc_ros_launch_client.hpp.
Referenced by launch(), and stop().
detached_futures_
std::map<std::future<void>, cancelCallback> smacc2::client_bases::ClRosLaunch::detached_futures_ static protected
Definition at line 56 of file smacc_ros_launch_client.hpp.
launchFileName_
std::string smacc2::client_bases::ClRosLaunch::launchFileName_
Definition at line 49 of file smacc_ros_launch_client.hpp.
Referenced by launch(), and smacc2::client_behaviors::CbRosLaunch::onEntry().
packageName_
std::string smacc2::client_bases::ClRosLaunch::packageName_
Definition at line 47 of file smacc_ros_launch_client.hpp.
Referenced by launch(), and smacc2::client_behaviors::CbRosLaunch::onEntry().
result_
std::future<std::string> smacc2::client_bases::ClRosLaunch::result_ protected
Definition at line 52 of file smacc_ros_launch_client.hpp.
Referenced by launch().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/client_bases/smacc_ros_launch_client.hpp
smacc2/src/smacc2/client_bases/smacc_ros_launch_client.cpp