SMACC2: cl_nav2z::odom_tracker::OdomTracker Class Reference
cl_nav2z::odom_tracker::OdomTracker Class Reference
#include <odom_tracker.hpp>
Classes
struct PathInfo
Public Member Functions
OdomTracker (std::string odomtopicName="/odom", std::string odomFrame="odom")
virtual void processOdometryMessage (const nav_msgs::msg::Odometry::SharedPtr odom)
odom callback: Updates the path - this must be called periodically for each odometry message.
void setWorkingMode (WorkingMode workingMode)
void setPublishMessages (bool value)
void pushPath ()
void pushPath (std::string pathname)
void popPath (int pathCount=1, bool keepPreviousPath=false)
void clearPath ()
void setStartPoint (const geometry_msgs::msg::PoseStamped &pose)
void setStartPoint (const geometry_msgs::msg::Pose &pose)
void setCurrentMotionGoal (const geometry_msgs::msg::PoseStamped &pose)
void setCurrentPathName (const std::string &currentPathName)
std::optional< geometry_msgs::msg::PoseStamped > getCurrentMotionGoal ()
nav_msgs::msg::Path getPath ()
void logStateString (bool debug=true)
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Protected Member Functions
void onInitialize () override
void updateConfiguration ()
virtual void rtPublishPaths (rclcpp::Time timestamp)
virtual bool updateRecordPath (const nav_msgs::msg::Odometry &odom)
virtual bool updateClearPath (const nav_msgs::msg::Odometry &odom)
void updateAggregatedStackPath ()
Protected Member Functions inherited from smacc2::ISmaccComponent
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes
rclcpp::Publisher< nav_msgs::msg::Path >::SharedPtr robotBasePathPub_
rclcpp::Publisher< nav_msgs::msg::Path >::SharedPtr robotBasePathStackedPub_
rclcpp::Subscription< nav_msgs::msg::Odometry >::SharedPtr odomSub_
double recordPointDistanceThreshold_
How much distance there is between two points of the path.
double recordAngularDistanceThreshold_
Meters.
double clearPointDistanceThreshold_
rads
double clearAngularDistanceThreshold_
rads
std::string odomFrame_
std::string odomTopicName_
bool publishMessages
nav_msgs::msg::Path baseTrajectory_
Processed path for the mouth of the reel.
WorkingMode workingMode_
std::vector< nav_msgs::msg::Path > pathStack_
std::vector< PathInfo > pathInfos_
nav_msgs::msg::Path aggregatedStackPathMsg_
bool subscribeToOdometryTopic_
std::optional< geometry_msgs::msg::PoseStamped > currentMotionGoal_
std::string currentPathName_
std::mutex m_mutex_
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
This object tracks and saves the trajectories performed by the vehicle so that they can be used later to execute operations such as "undo motions"
Definition at line 53 of file odom_tracker.hpp.
Constructor & Destructor Documentation
OdomTracker()
cl_nav2z::odom_tracker::OdomTracker::OdomTracker (std::string odomtopicName = "/odom", std::string odomFrame = "odom")
Definition at line 32 of file odom_tracker.cpp.
{
  workingMode_ = WorkingMode::RECORD_PATH;
  publishMessages = true;
  subscribeToOdometryTopic_ = true;
  odomFrame_ = odomFrame;
  odomTopicName_ = odomTopicName;
}
References odomFrame_, odomTopicName_, publishMessages, cl_nav2z::odom_tracker::RECORD_PATH, subscribeToOdometryTopic_, and workingMode_.
Member Function Documentation
clearPath()
void cl_nav2z::odom_tracker::OdomTracker::clearPath ()
Definition at line 247 of file odom_tracker.cpp.
{
  std::lock_guard<std::mutex> lock(m_mutex_);
  baseTrajectory_.poses.clear();
  rtPublishPaths(getNode()->now());
  this->logStateString();
  this->updateAggregatedStackPath();
  this->currentMotionGoal_.reset();
}
References baseTrajectory_, currentMotionGoal_, smacc2::ISmaccComponent::getNode(), logStateString(), m_mutex_, rtPublishPaths(), and updateAggregatedStackPath().
Referenced by cl_nav2z::CbNavigateBackwards::onEntry().
getCurrentMotionGoal()
std::optional< geometry_msgs::msg::PoseStamped > cl_nav2z::odom_tracker::OdomTracker::getCurrentMotionGoal ()
Definition at line 305 of file odom_tracker.cpp.
{
  std::lock_guard<std::mutex> lock(m_mutex_);
  return this->currentMotionGoal_;
}
References currentMotionGoal_, and m_mutex_.
Referenced by cl_nav2z::CbRetry< TCbRelativeMotion >::onEntry().
getPath()
nav_msgs::msg::Path cl_nav2z::odom_tracker::OdomTracker::getPath ()
Definition at line 311 of file odom_tracker.cpp.
{
  std::lock_guard<std::mutex> lock(m_mutex_);
  return this->baseTrajectory_;
}
References baseTrajectory_, and m_mutex_.
Referenced by cl_nav2z::CbUndoPathBackwards::onEntry().
logStateString()
void cl_nav2z::odom_tracker::OdomTracker::logStateString (bool debug = true)
Definition at line 213 of file odom_tracker.cpp.
{
  std::stringstream ss;
  ss << "--- odom tracker state ---" << std::endl;
  ss
    << " - path stack -" << currentPathName_ << " -  size:"
    << pathStack_.size()
    //<< " goal: " << (getCurrentMotionGoal()? getCurrentMotionGoal()->pose: geometry_msgs::msg::Pose())
    << std::endl;
  ss << " - [STACK-HEAD active path size: " << baseTrajectory_.poses.size() << "]" << std::endl;
  int i = 0;
  for (auto & p : pathStack_ | boost::adaptors::reversed)
  {
    auto & pathinfo = pathInfos_[pathInfos_.size() - i - 1];
    std::string goalstr = "[]";
    if (pathinfo.goalPose)
    {
      std::stringstream ss;
      ss << *(pathinfo.goalPose);
      goalstr = ss.str();
    }
    ss << " - p " << i << "[" << p.header.stamp << "], size: " << p.poses.size() << " - "
       << pathinfo.name << " - goal: " << goalstr << std::endl;
    i++;
  }
  ss << "---";
  if (debug)
    RCLCPP_DEBUG(getLogger(), ss.str().c_str());
  else
    RCLCPP_INFO(getLogger(), ss.str().c_str());
}
References baseTrajectory_, currentPathName_, smacc2::ISmaccComponent::getLogger(), pathInfos_, and pathStack_.
Referenced by clearPath(), cl_nav2z::CbUndoPathBackwards::onEntry(), cl_nav2z::CbUndoPathBackwards::onExit(), popPath(), and pushPath().
onInitialize()
void cl_nav2z::odom_tracker::OdomTracker::onInitialize () override protected virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 56 of file odom_tracker.cpp.
{
  // default values
  recordPointDistanceThreshold_ = 0.005;  // 5 mm
  recordAngularDistanceThreshold_ = 0.1;  // radians
  clearPointDistanceThreshold_ = 0.05;    // 5 cm
  clearAngularDistanceThreshold_ = 0.1;   // radi
  auto nh = getNode();
  RCLCPP_WARN(getLogger(), "[OdomTracker] Initializing Odometry Tracker");
  parameterDeclareAndtryGetOrSet(nh, "odom_frame", this->odomFrame_);
  parameterDeclareAndtryGetOrSet(
    nh, "record_point_distance_threshold", recordPointDistanceThreshold_);
  parameterDeclareAndtryGetOrSet(
    nh, "record_angular_distance_threshold", recordAngularDistanceThreshold_);
  parameterDeclareAndtryGetOrSet(
    nh, "clear_point_distance_threshold", clearPointDistanceThreshold_);
  parameterDeclareAndtryGetOrSet(
    nh, "clear_angular_distance_threshold", clearAngularDistanceThreshold_);
  if (this->subscribeToOdometryTopic_)
  {
    RCLCPP_INFO_STREAM(
      nh->get_logger(), "[OdomTracker] subscribing to odom topic: " << odomTopicName_);
    rclcpp::SensorDataQoS qos;
    odomSub_ = nh->create_subscription<nav_msgs::msg::Odometry>(
      odomTopicName_, qos,
      std::bind(&OdomTracker::processOdometryMessage, this, std::placeholders::_1));
  }
  robotBasePathPub_ =
    nh->create_publisher<nav_msgs::msg::Path>("odom_tracker_path", rclcpp::QoS(1));
  robotBasePathStackedPub_ =
    nh->create_publisher<nav_msgs::msg::Path>("odom_tracker_stacked_path", rclcpp::QoS(1));
}
References clearAngularDistanceThreshold_, clearPointDistanceThreshold_, smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getNode(), odomFrame_, odomSub_, odomTopicName_, cl_nav2z::odom_tracker::parameterDeclareAndtryGetOrSet(), processOdometryMessage(), recordAngularDistanceThreshold_, recordPointDistanceThreshold_, robotBasePathPub_, robotBasePathStackedPub_, and subscribeToOdometryTopic_.
popPath()
void cl_nav2z::odom_tracker::OdomTracker::popPath (int pathCount = 1, bool keepPreviousPath = false)
Definition at line 176 of file odom_tracker.cpp.
{
  RCLCPP_INFO(getLogger(), "odom_tracker m_mutex acquire");
  std::lock_guard<std::mutex> lock(m_mutex_);
  RCLCPP_INFO(getLogger(), "POP PATH ENTRY");
  this->logStateString();
  if (!keepPreviousPath)
  {
    baseTrajectory_.poses.clear();
  }
  while (popCount > 0 && !pathStack_.empty())
  {
    auto & stackedPath = pathStack_.back().poses;
    auto & stackedPathInfo = pathInfos_.back();
    baseTrajectory_.poses.insert(
      baseTrajectory_.poses.begin(), stackedPath.begin(), stackedPath.end());
    this->currentMotionGoal_ = stackedPathInfo.goalPose;
    pathStack_.pop_back();
    pathInfos_.pop_back();
    popCount--;
    RCLCPP_INFO(getLogger(), "POP PATH Iteration ");
    this->logStateString();
  }
  RCLCPP_INFO(getLogger(), "POP PATH EXITING");
  this->logStateString();
  RCLCPP_INFO(getLogger(), "odom_tracker m_mutex release");
  this->updateAggregatedStackPath();
  this->currentMotionGoal_.reset();
}
References baseTrajectory_, currentMotionGoal_, smacc2::ISmaccComponent::getLogger(), logStateString(), m_mutex_, pathInfos_, pathStack_, and updateAggregatedStackPath().
Referenced by OdomTrackerActionServer::execute(), and cl_nav2z::CbUndoPathBackwards::onExit().
processOdometryMessage()
void cl_nav2z::odom_tracker::OdomTracker::processOdometryMessage (const nav_msgs::msg::Odometry::SharedPtr odom) virtual
odom callback: Updates the path - this must be called periodically for each odometry message.
processOdometryMessage()
Definition at line 515 of file odom_tracker.cpp.
{
  RCLCPP_INFO_THROTTLE(getLogger(), *getNode()->get_clock(), 2000, "[odom_tracker] update");
  std::lock_guard<std::mutex> lock(m_mutex_);
  updateConfiguration();
  if (workingMode_ == WorkingMode::RECORD_PATH)
  {
    updateRecordPath(*odom);
  }
  else if (workingMode_ == WorkingMode::CLEAR_PATH)
  {
    updateClearPath(*odom);
  }
  // RCLCPP_WARN(getLogger(),"odomTracker odometry callback");
  if (publishMessages)
  {
    rtPublishPaths(odom->header.stamp);
  }
  // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex release");
}
References cl_nav2z::odom_tracker::CLEAR_PATH, smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getNode(), m_mutex_, publishMessages, cl_nav2z::odom_tracker::RECORD_PATH, rtPublishPaths(), updateClearPath(), updateConfiguration(), updateRecordPath(), and workingMode_.
Referenced by onInitialize().
pushPath() [1/2]
void cl_nav2z::odom_tracker::OdomTracker::pushPath ()
Definition at line 146 of file odom_tracker.cpp.
{ this->pushPath(std::string()); }
References pushPath().
Referenced by OdomTrackerActionServer::execute(), cl_nav2z::CbNavigateForward::onEntry(), and pushPath().
pushPath() [2/2]
void cl_nav2z::odom_tracker::OdomTracker::pushPath (std::string pathname)
Definition at line 148 of file odom_tracker.cpp.
{
  RCLCPP_INFO(getLogger(), "odom_tracker m_mutex acquire");
  std::lock_guard<std::mutex> lock(m_mutex_);
  this->logStateString(false);
  pathInfos_.push_back({currentPathName_, this->currentMotionGoal_});
  pathStack_.push_back(baseTrajectory_);
  geometry_msgs::msg::PoseStamped goalPose;
  if (this->currentMotionGoal_) goalPose = *this->currentMotionGoal_;
  RCLCPP_INFO_STREAM(
    getLogger(), "[OdomTracker] currentPathName: " << pathname
                                                   << "  size: " << baseTrajectory_.poses.size()
                                                   << "  current motion goal: " << goalPose);
  currentPathName_ = pathname;
  // clean the current trajectory to start a new one
  baseTrajectory_.poses.clear();
  this->logStateString(false);
  this->updateAggregatedStackPath();
  this->currentMotionGoal_.reset();
}
References baseTrajectory_, currentMotionGoal_, currentPathName_, smacc2::ISmaccComponent::getLogger(), logStateString(), m_mutex_, pathInfos_, pathStack_, and updateAggregatedStackPath().
rtPublishPaths()
void cl_nav2z::odom_tracker::OdomTracker::rtPublishPaths (rclcpp::Time timestamp) protected virtual
rtPublishPaths()
Definition at line 322 of file odom_tracker.cpp.
{
  baseTrajectory_.header.stamp = timestamp;
  robotBasePathPub_->publish(baseTrajectory_);
  aggregatedStackPathMsg_.header.stamp = timestamp;
  robotBasePathStackedPub_->publish(aggregatedStackPathMsg_);
}
References aggregatedStackPathMsg_, baseTrajectory_, robotBasePathPub_, and robotBasePathStackedPub_.
Referenced by clearPath(), and processOdometryMessage().
setCurrentMotionGoal()
void cl_nav2z::odom_tracker::OdomTracker::setCurrentMotionGoal (const geometry_msgs::msg::PoseStamped & pose)
Definition at line 299 of file odom_tracker.cpp.
{
  std::lock_guard<std::mutex> lock(m_mutex_);
  this->currentMotionGoal_ = pose;
}
References currentMotionGoal_, and m_mutex_.
Referenced by cl_nav2z::CbNavigateForward::onEntry().
setCurrentPathName()
void cl_nav2z::odom_tracker::OdomTracker::setCurrentPathName (const std::string & currentPathName)
Definition at line 259 of file odom_tracker.cpp.
{
  currentPathName_ = currentPathName;
}
References currentPathName_.
setPublishMessages()
void cl_nav2z::odom_tracker::OdomTracker::setPublishMessages (bool value)
setPublishMessages()
Definition at line 137 of file odom_tracker.cpp.
{
  // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex acquire");
  std::lock_guard<std::mutex> lock(m_mutex_);
  publishMessages = value;
  // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex release");
  this->updateAggregatedStackPath();
}
References m_mutex_, publishMessages, and updateAggregatedStackPath().
Referenced by OdomTrackerActionServer::execute().
setStartPoint() [1/2]
void cl_nav2z::odom_tracker::OdomTracker::setStartPoint (const geometry_msgs::msg::Pose & pose)
Definition at line 279 of file odom_tracker.cpp.
{
  std::lock_guard<std::mutex> lock(m_mutex_);
  RCLCPP_INFO_STREAM(getLogger(), "[OdomTracker] set current path starting point: " << pose);
  geometry_msgs::msg::PoseStamped posestamped;
  posestamped.header.frame_id = this->odomFrame_;
  posestamped.header.stamp = getNode()->now();
  posestamped.pose = pose;
  if (baseTrajectory_.poses.size() > 0)
  {
    baseTrajectory_.poses[0] = posestamped;
  }
  else
  {
    baseTrajectory_.poses.push_back(posestamped);
  }
  this->updateAggregatedStackPath();
}
References baseTrajectory_, smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getNode(), m_mutex_, odomFrame_, and updateAggregatedStackPath().
setStartPoint() [2/2]
void cl_nav2z::odom_tracker::OdomTracker::setStartPoint (const geometry_msgs::msg::PoseStamped & pose)
Definition at line 264 of file odom_tracker.cpp.
{
  std::lock_guard<std::mutex> lock(m_mutex_);
  RCLCPP_INFO_STREAM(getLogger(), "[OdomTracker] set current path starting point: " << pose);
  if (baseTrajectory_.poses.size() > 0)
  {
    baseTrajectory_.poses[0] = pose;
  }
  else
  {
    baseTrajectory_.poses.push_back(pose);
  }
  this->updateAggregatedStackPath();
}
References baseTrajectory_, smacc2::ISmaccComponent::getLogger(), m_mutex_, and updateAggregatedStackPath().
Referenced by cl_nav2z::CbNavigateBackwards::onEntry(), and cl_nav2z::CbNavigateForward::onEntry().
setWorkingMode()
void cl_nav2z::odom_tracker::OdomTracker::setWorkingMode (WorkingMode workingMode)
setWorkingMode()
Definition at line 99 of file odom_tracker.cpp.
{
  // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex acquire");
  std::lock_guard<std::mutex> lock(m_mutex_);
  switch (workingMode)
  {
    case WorkingMode::RECORD_PATH:
      RCLCPP_INFO_STREAM(
        getLogger(),
        "[OdomTracker] setting working mode to RECORD - record_point_distance_threshold: "
          << recordPointDistanceThreshold_
          << ", record_angular_distance_threshold: " << recordAngularDistanceThreshold_);
      break;
    case WorkingMode::CLEAR_PATH:
      RCLCPP_INFO_STREAM(
        getLogger(),
        "[OdomTracker] setting working mode to CLEAR - clear_point_distance_threshold: "
          << clearPointDistanceThreshold_
          << ", clear_angular_distance_threshold: " << clearAngularDistanceThreshold_);
      break;
    case WorkingMode::IDLE:
      RCLCPP_INFO_STREAM(getLogger(), "[OdomTracker] setting working mode to IDLE");
      break;
    default:
      RCLCPP_INFO_STREAM(getLogger(), "[OdomTracker] setting working mode to <UNKNOWN>");
  }
  workingMode_ = workingMode;
  // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex release");
}
References cl_nav2z::odom_tracker::CLEAR_PATH, clearAngularDistanceThreshold_, clearPointDistanceThreshold_, smacc2::ISmaccComponent::getLogger(), cl_nav2z::odom_tracker::IDLE, m_mutex_, cl_nav2z::odom_tracker::RECORD_PATH, recordAngularDistanceThreshold_, recordPointDistanceThreshold_, and workingMode_.
Referenced by OdomTrackerActionServer::execute(), cl_nav2z::CbNavigateBackwards::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbUndoPathBackwards::onEntry(), cl_nav2z::CbNavigateBackwards::onExit(), and cl_nav2z::CbNavigateForward::onExit().
updateAggregatedStackPath()
void cl_nav2z::odom_tracker::OdomTracker::updateAggregatedStackPath () protected
Definition at line 331 of file odom_tracker.cpp.
{
  aggregatedStackPathMsg_.poses.clear();
  for (auto & p : pathStack_)
  {
    aggregatedStackPathMsg_.poses.insert(
      aggregatedStackPathMsg_.poses.end(), p.poses.begin(), p.poses.end());
  }
  aggregatedStackPathMsg_.header.frame_id = this->odomFrame_;
}
References aggregatedStackPathMsg_, odomFrame_, and pathStack_.
Referenced by clearPath(), popPath(), pushPath(), setPublishMessages(), and setStartPoint().
updateClearPath()
bool cl_nav2z::odom_tracker::OdomTracker::updateClearPath (const nav_msgs::msg::Odometry & odom) protected virtual
updateBackward()
Track robot base pose
Not removing point because it is enough far from the last cord point
Definition at line 348 of file odom_tracker.cpp.
{
  // we initially accept any message if the queue is empty
  geometry_msgs::msg::PoseStamped base_pose;
  base_pose.pose = odom.pose.pose;
  base_pose.header = odom.header;
  baseTrajectory_.header = odom.header;
  bool acceptBackward = false;
  bool clearingError = false;
  bool finished = false;
  while (!finished)
  {
    if (
      baseTrajectory_.poses.size() <=
      1)  // we at least keep always the first point of the forward path when clearing
          // (this is important for backwards planner replanning and not losing the
          // last goal)
    {
      acceptBackward = false;
      finished = true;
    }
    else
    {
      auto & carrotPose = baseTrajectory_.poses.back().pose;
      auto & carrotPoint = carrotPose.position;
      double carrotAngle = tf2::getYaw(carrotPose.orientation);
      auto & currePose = base_pose.pose;
      auto & currePoint = currePose.position;
      double currentAngle = tf2::getYaw(currePose.orientation);
      double lastpointdist = p2pDistance(carrotPoint, currePoint);
      double goalAngleOffset = fabs(angles::shortest_angular_distance(carrotAngle, currentAngle));
      acceptBackward = !baseTrajectory_.poses.empty() &&
                       lastpointdist < clearPointDistanceThreshold_ &&
                       goalAngleOffset < clearAngularDistanceThreshold_;
      clearingError = lastpointdist > 2 * clearPointDistanceThreshold_;
      RCLCPP_DEBUG_STREAM(
        getLogger(), "[OdomTracker] clearing (accepted: " << acceptBackward
                                                          << ") linerr: " << lastpointdist
                                                          << ", anglerr: " << goalAngleOffset);
    }
    // RCLCPP_INFO(getLogger(),"Backwards, last distance: %lf < %lf accept: %d", dist,
    // minPointDistanceBackwardThresh_, acceptBackward);
    if (
      acceptBackward &&
      baseTrajectory_.poses.size() > 1) /* we always leave at least one item, specially interesting
                                                                                   for the backward local planner reach
                                                               the backwards goal with enough precision*/
    {
      baseTrajectory_.poses.pop_back();
    }
    else if (clearingError)
    {
      finished = true;
      RCLCPP_WARN(getLogger(), "[OdomTracker] Incorrect odom clearing motion.");
    }
    else
    {
      finished = true;
    }
  }
  return acceptBackward;
}
References baseTrajectory_, clearAngularDistanceThreshold_, clearPointDistanceThreshold_, smacc2::ISmaccComponent::getLogger(), and cl_nav2z::odom_tracker::p2pDistance().
Referenced by processOdometryMessage().
updateConfiguration()
void cl_nav2z::odom_tracker::OdomTracker::updateConfiguration () protected
reconfigCB()
Definition at line 486 of file odom_tracker.cpp.
{
  if (!getNode()->get_parameter("odom_frame", this->odomFrame_))
  {
  }
  if (!getNode()->get_parameter("record_point_distance_threshold", recordPointDistanceThreshold_))
  {
  }
  if (!getNode()->get_parameter(
        "record_angular_distance_threshold", recordAngularDistanceThreshold_))
  {
  }
  if (!getNode()->get_parameter("clear_point_distance_threshold", clearPointDistanceThreshold_))
  {
  }
  if (!getNode()->get_parameter("clear_angular_distance_threshold", clearAngularDistanceThreshold_))
  {
  }
}
References clearAngularDistanceThreshold_, clearPointDistanceThreshold_, smacc2::ISmaccComponent::getNode(), odomFrame_, recordAngularDistanceThreshold_, and recordPointDistanceThreshold_.
Referenced by processOdometryMessage().
updateRecordPath()
bool cl_nav2z::odom_tracker::OdomTracker::updateRecordPath (const nav_msgs::msg::Odometry & odom) protected virtual
updateRecordPath()
Track robot base pose
Definition at line 427 of file odom_tracker.cpp.
{
  geometry_msgs::msg::PoseStamped base_pose;
  base_pose.pose = odom.pose.pose;
  base_pose.header = odom.header;
  baseTrajectory_.header = odom.header;
  bool enqueueOdomMessage = false;
  double dist = -1;
  if (baseTrajectory_.poses.empty())
  {
    enqueueOdomMessage = true;
  }
  else
  {
    const auto & prevPose = baseTrajectory_.poses.back().pose;
    const geometry_msgs::msg::Point & prevPoint = prevPose.position;
    double prevAngle = tf2::getYaw(prevPose.orientation);
    const geometry_msgs::msg::Point & currePoint = base_pose.pose.position;
    double currentAngle = tf2::getYaw(base_pose.pose.orientation);
    dist = p2pDistance(prevPoint, currePoint);
    double goalAngleOffset = fabs(angles::shortest_angular_distance(prevAngle, currentAngle));
    // RCLCPP_WARN(getLogger(),"dist %lf vs min %lf", dist, recordPointDistanceThreshold_);
    RCLCPP_WARN_THROTTLE(getLogger(), *getNode()->get_clock(), 2000, "odom received");
    if (dist > recordPointDistanceThreshold_ || goalAngleOffset > recordAngularDistanceThreshold_)
    {
      enqueueOdomMessage = true;
    }
    else
    {
      // RCLCPP_WARN(getLogger(),"skip odom, dist: %lf", dist);
      enqueueOdomMessage = false;
    }
  }
  if (enqueueOdomMessage)
  {
    RCLCPP_WARN_THROTTLE(
      getLogger(), *getNode()->get_clock(), 2000, "enqueue odom tracker pose. dist %lf vs min %lf",
      dist, recordPointDistanceThreshold_);
    baseTrajectory_.poses.push_back(base_pose);
  }
  return enqueueOdomMessage;
}
References baseTrajectory_, smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getNode(), cl_nav2z::odom_tracker::p2pDistance(), recordAngularDistanceThreshold_, and recordPointDistanceThreshold_.
Referenced by processOdometryMessage().
Member Data Documentation
aggregatedStackPathMsg_
nav_msgs::msg::Path cl_nav2z::odom_tracker::OdomTracker::aggregatedStackPathMsg_ protected
Definition at line 163 of file odom_tracker.hpp.
Referenced by rtPublishPaths(), and updateAggregatedStackPath().
baseTrajectory_
nav_msgs::msg::Path cl_nav2z::odom_tracker::OdomTracker::baseTrajectory_ protected
Processed path for the mouth of the reel.
Definition at line 149 of file odom_tracker.hpp.
Referenced by clearPath(), getPath(), logStateString(), popPath(), pushPath(), rtPublishPaths(), setStartPoint(), updateClearPath(), and updateRecordPath().
clearAngularDistanceThreshold_
double cl_nav2z::odom_tracker::OdomTracker::clearAngularDistanceThreshold_ protected
rads
Definition at line 138 of file odom_tracker.hpp.
Referenced by onInitialize(), setWorkingMode(), updateClearPath(), and updateConfiguration().
clearPointDistanceThreshold_
double cl_nav2z::odom_tracker::OdomTracker::clearPointDistanceThreshold_ protected
rads
Definition at line 135 of file odom_tracker.hpp.
Referenced by onInitialize(), setWorkingMode(), updateClearPath(), and updateConfiguration().
currentMotionGoal_
std::optional<geometry_msgs::msg::PoseStamped> cl_nav2z::odom_tracker::OdomTracker::currentMotionGoal_ protected
Definition at line 168 of file odom_tracker.hpp.
Referenced by clearPath(), getCurrentMotionGoal(), popPath(), pushPath(), and setCurrentMotionGoal().
currentPathName_
std::string cl_nav2z::odom_tracker::OdomTracker::currentPathName_ protected
Definition at line 169 of file odom_tracker.hpp.
Referenced by logStateString(), pushPath(), and setCurrentPathName().
m_mutex_
std::mutex cl_nav2z::odom_tracker::OdomTracker::m_mutex_ protected
Definition at line 171 of file odom_tracker.hpp.
Referenced by clearPath(), getCurrentMotionGoal(), getPath(), popPath(), processOdometryMessage(), pushPath(), setCurrentMotionGoal(), setPublishMessages(), setStartPoint(), and setWorkingMode().
odomFrame_
std::string cl_nav2z::odom_tracker::OdomTracker::odomFrame_ protected
Definition at line 140 of file odom_tracker.hpp.
Referenced by OdomTracker(), onInitialize(), setStartPoint(), updateAggregatedStackPath(), and updateConfiguration().
odomSub_
rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr cl_nav2z::odom_tracker::OdomTracker::odomSub_ protected
Definition at line 125 of file odom_tracker.hpp.
Referenced by onInitialize().
odomTopicName_
std::string cl_nav2z::odom_tracker::OdomTracker::odomTopicName_ protected
Definition at line 142 of file odom_tracker.hpp.
Referenced by OdomTracker(), and onInitialize().
pathInfos_
std::vector<PathInfo> cl_nav2z::odom_tracker::OdomTracker::pathInfos_ protected
Definition at line 161 of file odom_tracker.hpp.
Referenced by logStateString(), popPath(), and pushPath().
pathStack_
std::vector<nav_msgs::msg::Path> cl_nav2z::odom_tracker::OdomTracker::pathStack_ protected
Definition at line 153 of file odom_tracker.hpp.
Referenced by logStateString(), popPath(), pushPath(), and updateAggregatedStackPath().
publishMessages
bool cl_nav2z::odom_tracker::OdomTracker::publishMessages protected
Definition at line 146 of file odom_tracker.hpp.
Referenced by OdomTracker(), processOdometryMessage(), and setPublishMessages().
recordAngularDistanceThreshold_
double cl_nav2z::odom_tracker::OdomTracker::recordAngularDistanceThreshold_ protected
Meters.
Definition at line 132 of file odom_tracker.hpp.
Referenced by onInitialize(), setWorkingMode(), updateConfiguration(), and updateRecordPath().
recordPointDistanceThreshold_
double cl_nav2z::odom_tracker::OdomTracker::recordPointDistanceThreshold_ protected
How much distance there is between two points of the path.
Definition at line 129 of file odom_tracker.hpp.
Referenced by onInitialize(), setWorkingMode(), updateConfiguration(), and updateRecordPath().
robotBasePathPub_
rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr cl_nav2z::odom_tracker::OdomTracker::robotBasePathPub_ protected
Definition at line 119 of file odom_tracker.hpp.
Referenced by onInitialize(), and rtPublishPaths().
robotBasePathStackedPub_
rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr cl_nav2z::odom_tracker::OdomTracker::robotBasePathStackedPub_ protected
Definition at line 120 of file odom_tracker.hpp.
Referenced by onInitialize(), and rtPublishPaths().
subscribeToOdometryTopic_
bool cl_nav2z::odom_tracker::OdomTracker::subscribeToOdometryTopic_ protected
Definition at line 166 of file odom_tracker.hpp.
Referenced by OdomTracker(), and onInitialize().
workingMode_
WorkingMode cl_nav2z::odom_tracker::OdomTracker::workingMode_ protected
Definition at line 151 of file odom_tracker.hpp.
Referenced by OdomTracker(), processOdometryMessage(), and setWorkingMode().
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/components/odom_tracker/odom_tracker.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/components/odom_tracker/odom_tracker.cpp