SMACC2: cl_nav2z::CbSeekWaypoint Class Reference
cl_nav2z::CbSeekWaypoint Class Reference
#include <cb_seek_waypoint.hpp>
Public Member Functions
CbSeekWaypoint (std::string skip_until_name)
virtual ~CbSeekWaypoint ()
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Attributes
WaypointNavigator * waypointsNavigator_
NavigateNextWaypointOptions options_
Private Attributes
std::optional< int > count_
std::optional< std::string > seekWaypointName_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 29 of file cb_seek_waypoint.hpp.
Constructor & Destructor Documentation
CbSeekWaypoint()
cl_nav2z::CbSeekWaypoint::CbSeekWaypoint (std::string skip_until_name)
Definition at line 25 of file cb_seek_waypoint.cpp.
: count_(std::nullopt), seekWaypointName_(seekWaypointName)
{
}
~CbSeekWaypoint()
cl_nav2z::CbSeekWaypoint::~CbSeekWaypoint () virtual
Definition at line 30 of file cb_seek_waypoint.cpp.
{}
Member Function Documentation
onEntry()
void cl_nav2z::CbSeekWaypoint::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 32 of file cb_seek_waypoint.cpp.
{
  cl_nav2z::ClNav2Z * nav2zClient_;
  this->requiresClient(nav2zClient_);
  waypointsNavigator_ = nav2zClient_->getComponent<WaypointNavigator>();
  if (count_)
  {
    waypointsNavigator_->forward(*count_);
    count_ = std::nullopt;
  }
  else if (seekWaypointName_)
  {
    waypointsNavigator_->seekName(*seekWaypointName_);
    seekWaypointName_ = std::nullopt;
  }
}
References count_, cl_nav2z::WaypointNavigator::forward(), smacc2::ISmaccClient::getComponent(), smacc2::ISmaccClientBehavior::requiresClient(), cl_nav2z::WaypointNavigator::seekName(), seekWaypointName_, and waypointsNavigator_.
onExit()
void cl_nav2z::CbSeekWaypoint::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 50 of file cb_seek_waypoint.cpp.
{}
Member Data Documentation
count_
std::optional<int> cl_nav2z::CbSeekWaypoint::count_ private
Definition at line 45 of file cb_seek_waypoint.hpp.
Referenced by onEntry().
options_
NavigateNextWaypointOptions cl_nav2z::CbSeekWaypoint::options_
Definition at line 42 of file cb_seek_waypoint.hpp.
seekWaypointName_
std::optional<std::string> cl_nav2z::CbSeekWaypoint::seekWaypointName_ private
Definition at line 46 of file cb_seek_waypoint.hpp.
Referenced by onEntry().
waypointsNavigator_
WaypointNavigator* cl_nav2z::CbSeekWaypoint::waypointsNavigator_
Definition at line 40 of file cb_seek_waypoint.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/client_behaviors/cb_seek_waypoint.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/client_behaviors/cb_seek_waypoint.cpp