SMACC2: cl_nitrosz::CpWaypointNavigator Class Reference
cl_nitrosz::CpWaypointNavigator Class Reference
#include <cp_waypoints_navigator.hpp>
Public Member Functions
CpWaypointNavigator ()
void onInitialize () override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
std::optional< std::shared_future< std::shared_ptr< rclcpp_action::ClientGoalHandle< nav2_msgs::action::NavigateToPose > > > > sendNextGoal (std::optional< NavigateNextWaypointOptions > options=std::nullopt, cl_nitrosz::ClNitrosZ::SmaccNavigateResultSignal::WeakPtr callback=cl_nitrosz::ClNitrosZ::SmaccNavigateResultSignal::WeakPtr())
void stopWaitingResult ()
Public Member Functions inherited from cl_nitrosz::CpWaypointNavigatorBase
CpWaypointNavigatorBase ()
virtual ~CpWaypointNavigatorBase ()
void onInitialize () override
void loadWayPointsFromFile (std::string filepath)
void loadWayPointsFromFile2 (std::string filepath)
void setWaypoints (const std::vector< geometry_msgs::msg::Pose > &waypoints)
void setWaypoints (const std::vector< Pose2D > &waypoints)
const std::vector< geometry_msgs::msg::Pose > & getWaypoints () const
const std::vector< std::string > & getWaypointNames () const
std::optional< geometry_msgs::msg::Pose > getNamedPose (std::string name) const
geometry_msgs::msg::Pose getPose (int index) const
geometry_msgs::msg::Pose getCurrentPose () const
long getCurrentWaypointIndex () const
std::optional< std::string > getCurrentWaypointName () const
void rewind (int count)
void forward (int count)
void seekName (std::string name)
void loadWaypointsFromYamlParameter (std::string parameter_name, std::string yaml_file_package_name)
void notifyGoalReached ()
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Attributes
ClNitrosZ * client_
smacc2::SmaccSignal< void()> onNavigationRequestSucceded
smacc2::SmaccSignal< void()> onNavigationRequestAborted
smacc2::SmaccSignal< void()> onNavigationRequestCancelled
Public Attributes inherited from cl_nitrosz::CpWaypointNavigatorBase
WaypointEventDispatcher waypointsEventDispatcher
long currentWaypoint_
Private Member Functions
void onNavigationResult (const ClNitrosZ::WrappedResult &r)
void onGoalReached (const ClNitrosZ::WrappedResult &res)
void onGoalCancelled (const ClNitrosZ::WrappedResult &)
void onGoalAborted (const ClNitrosZ::WrappedResult &)
Private Attributes
boost::signals2::connection succeddedNav2ZClientConnection_
boost::signals2::connection abortedNav2ZClientConnection_
boost::signals2::connection cancelledNav2ZClientConnection_
Additional Inherited Members
Protected Member Functions inherited from cl_nitrosz::CpWaypointNavigatorBase
void insertWaypoint (int index, geometry_msgs::msg::Pose &newpose)
void removeWaypoint (int index)
Protected Member Functions inherited from smacc2::ISmaccComponent
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes inherited from cl_nitrosz::CpWaypointNavigatorBase
std::vector< geometry_msgs::msg::Pose > waypoints_
std::vector< std::string > waypointsNames_
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 46 of file cp_waypoints_navigator.hpp.
Constructor & Destructor Documentation
CpWaypointNavigator()
cl_nitrosz::CpWaypointNavigator::CpWaypointNavigator ()
Definition at line 42 of file cp_waypoints_navigator.cpp.
{}
Member Function Documentation
onGoalAborted()
void cl_nitrosz::CpWaypointNavigator::onGoalAborted (const ClNitrosZ::WrappedResult &) private
Definition at line 55 of file cp_waypoints_navigator.cpp.
{
  stopWaitingResult();
  this->onNavigationRequestAborted();
}
References onNavigationRequestAborted, and stopWaitingResult().
Referenced by onNavigationResult().
onGoalCancelled()
void cl_nitrosz::CpWaypointNavigator::onGoalCancelled (const ClNitrosZ::WrappedResult &) private
Definition at line 48 of file cp_waypoints_navigator.cpp.
{
  stopWaitingResult();
  this->onNavigationRequestCancelled();
}
References onNavigationRequestCancelled, and stopWaitingResult().
Referenced by onNavigationResult().
onGoalReached()
void cl_nitrosz::CpWaypointNavigator::onGoalReached (const ClNitrosZ::WrappedResult & res) private
Definition at line 62 of file cp_waypoints_navigator.cpp.
{
  waypointsEventDispatcher.postWaypointEvent(currentWaypoint_);
  currentWaypoint_++;
  RCLCPP_WARN(
    getLogger(), "[CpWaypointNavigator] Goal result received, incrementing waypoint index: %ld",
    currentWaypoint_);
  stopWaitingResult();
  this->notifyGoalReached();
  onNavigationRequestSucceded();
}
References cl_nitrosz::CpWaypointNavigatorBase::currentWaypoint_, smacc2::ISmaccComponent::getLogger(), cl_nitrosz::CpWaypointNavigatorBase::notifyGoalReached(), onNavigationRequestSucceded, WaypointEventDispatcher::postWaypointEvent(), stopWaitingResult(), and cl_nitrosz::CpWaypointNavigatorBase::waypointsEventDispatcher.
Referenced by onNavigationResult().
onInitialize()
void cl_nitrosz::CpWaypointNavigator::onInitialize () override virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 46 of file cp_waypoints_navigator.cpp.
{ client_ = dynamic_cast<ClNitrosZ *>(owner_); }
References client_, and smacc2::ISmaccComponent::owner_.
onNavigationResult()
void cl_nitrosz::CpWaypointNavigator::onNavigationResult (const ClNitrosZ::WrappedResult & r) private
Definition at line 308 of file cp_waypoints_navigator.cpp.
{
  if (r.code == rclcpp_action::ResultCode::SUCCEEDED)
  {
    this->onGoalReached(r);
  }
  else if (r.code == rclcpp_action::ResultCode::ABORTED)
  {
    this->onGoalAborted(r);
  }
  else if (r.code == rclcpp_action::ResultCode::CANCELED)
  {
    this->onGoalCancelled(r);
  }
  else
  {
    this->onGoalAborted(r);
  }
}
References onGoalAborted(), onGoalCancelled(), and onGoalReached().
Referenced by sendNextGoal().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_nitrosz::CpWaypointNavigator::onOrthogonalAllocation () inline
Definition at line 56 of file cp_waypoints_navigator.hpp.
  {
    waypointsEventDispatcher.initialize<TSourceObject, TOrthogonal>(client_);
  }
References client_, WaypointEventDispatcher::initialize(), and cl_nitrosz::CpWaypointNavigatorBase::waypointsEventDispatcher.
sendNextGoal()
std::optional< std::shared_future< std::shared_ptr< rclcpp_action::ClientGoalHandle< nav2_msgs::action::NavigateToPose > > > > cl_nitrosz::CpWaypointNavigator::sendNextGoal (std::optional< NavigateNextWaypointOptions > options = std::nullopt, cl_nitrosz::ClNitrosZ::SmaccNavigateResultSignal::WeakPtr callback = cl_nitrosz::ClNitrosZ::SmaccNavigateResultSignal::WeakPtr())
Definition at line 192 of file cp_waypoints_navigator.cpp.
{
  if (currentWaypoint_ >= 0 && currentWaypoint_ < (int)waypoints_.size())
  {
    auto & next = waypoints_[currentWaypoint_];
    std::string nextName;
    if ((long)waypointsNames_.size() > currentWaypoint_)
    {
      nextName = waypointsNames_[currentWaypoint_];
      RCLCPP_INFO(
        getLogger(), "[CpWaypointNavigator] sending goal, waypoint: %s", nextName.c_str());
    }
    else
    {
      RCLCPP_INFO(
        getLogger(), "[CpWaypointNavigator] sending goal, waypoint: %ld", currentWaypoint_);
    }
    ClNitrosZ::Goal goal;
    auto p = client_->getComponent<cl_nitrosz::Pose>();
    auto pose = p->toPoseMsg();
    // configuring goal
    goal.pose.header.frame_id = p->getReferenceFrame();
    //goal.pose.header.stamp = getNode()->now();
    goal.pose.pose = next;
    auto plannerSwitcher = client_->getComponent<CpPlannerSwitcher>();
    plannerSwitcher->setDefaultPlanners(false);
    if (options && options->controllerName_)
    {
      RCLCPP_WARN(
        getLogger(), "[WaypointsNavigator] override controller: %s",
        options->controllerName_->c_str());
      plannerSwitcher->setDesiredController(*options->controllerName_);
    }
    else
    {
      RCLCPP_WARN(getLogger(), "[WaypointsNavigator] Configuring default planners");
    }
    auto goalCheckerSwitcher = client_->getComponent<CpGoalCheckerSwitcher>();
    if (options && options->goalCheckerName_)
    {
      RCLCPP_WARN(
        getLogger(), "[WaypointsNavigator] override goal checker: %s",
        options->goalCheckerName_->c_str());
      goalCheckerSwitcher->setGoalCheckerId(*options->goalCheckerName_);
    }
    else
    {
      RCLCPP_WARN(getLogger(), "[WaypointsNavigator] Configuring default goal checker");
      goalCheckerSwitcher->setGoalCheckerId("goal_checker");
    }
    plannerSwitcher->commitPublish();
    // publish stuff
    // rclcpp::sleep_for(5s);
    RCLCPP_INFO(getLogger(), "[WaypointsNavigator] Getting odom tracker");
    auto odomTracker = client_->getComponent<cl_nitrosz::odom_tracker::CpOdomTracker>();
    if (odomTracker != nullptr)
    {
      RCLCPP_INFO(getLogger(), "[WaypointsNavigator] Storing path in odom tracker");
      auto pathname = this->owner_->getStateMachine()->getCurrentState()->getName() + " - " +
                      getName() + " - " + nextName;
      odomTracker->pushPath(pathname);
      odomTracker->setStartPoint(pose);
      odomTracker->setWorkingMode(cl_nitrosz::odom_tracker::WorkingMode::RECORD_PATH);
    }
    // SEND GOAL
    // if (!succeddedNav2ZClientConnection_.connected())
    // {
    //   this->succeddedNav2ZClientConnection_ =
    //     client_->onSucceeded(&WaypointNavigator::onGoalReached, this);
    //   this->cancelledNav2ZClientConnection_ =
    //     client_->onAborted(&WaypointNavigator::onGoalCancelled, this);
    //   this->abortedNav2ZClientConnection_ =
    //     client_->onCancelled(&WaypointNavigator::onGoalAborted, this);
    // }
    auto callbackptr = resultCallback.lock();
    succeddedNav2ZClientConnection_ = this->getStateMachine()->createSignalConnection(
      *callbackptr, &CpWaypointNavigator::onNavigationResult, this);
    return client_->sendGoal(goal, resultCallback);
  }
  else
  {
    RCLCPP_WARN(
      getLogger(),
      "[CpWaypointsNavigator] All waypoints were consumed. There is no more waypoints available.");
  }
  return std::nullopt;
}
References client_, smacc2::ISmaccStateMachine::createSignalConnection(), cl_nitrosz::CpWaypointNavigatorBase::currentWaypoint_, smacc2::ISmaccClient::getComponent(), smacc2::ISmaccStateMachine::getCurrentState(), smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getName(), smacc2::ISmaccState::getName(), smacc2::ISmaccComponent::getStateMachine(), smacc2::ISmaccClient::getStateMachine(), onNavigationResult(), smacc2::ISmaccComponent::owner_, cl_nitrosz::odom_tracker::RECORD_PATH, smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), cl_nitrosz::CpPlannerSwitcher::setDefaultPlanners(), succeddedNav2ZClientConnection_, cl_nitrosz::Pose::toPoseMsg(), cl_nitrosz::CpWaypointNavigatorBase::waypoints_, and cl_nitrosz::CpWaypointNavigatorBase::waypointsNames_.
Referenced by cl_nitrosz::CbNavigateNextWaypoint::onEntry().
stopWaitingResult()
void cl_nitrosz::CpWaypointNavigator::stopWaitingResult ()
Definition at line 180 of file cp_waypoints_navigator.cpp.
{
  if (succeddedNav2ZClientConnection_.connected())
  {
    this->succeddedNav2ZClientConnection_.disconnect();
    this->cancelledNav2ZClientConnection_.disconnect();
    this->abortedNav2ZClientConnection_.disconnect();
  }
}
References abortedNav2ZClientConnection_, cancelledNav2ZClientConnection_, and succeddedNav2ZClientConnection_.
Referenced by cl_nitrosz::CbNavigateNextWaypoint::onExit(), onGoalAborted(), onGoalCancelled(), and onGoalReached().
Member Data Documentation
abortedNav2ZClientConnection_
boost::signals2::connection cl_nitrosz::CpWaypointNavigator::abortedNav2ZClientConnection_ private
Definition at line 82 of file cp_waypoints_navigator.hpp.
Referenced by stopWaitingResult().
cancelledNav2ZClientConnection_
boost::signals2::connection cl_nitrosz::CpWaypointNavigator::cancelledNav2ZClientConnection_ private
Definition at line 83 of file cp_waypoints_navigator.hpp.
Referenced by stopWaitingResult().
client_
ClNitrosZ* cl_nitrosz::CpWaypointNavigator::client_
Definition at line 49 of file cp_waypoints_navigator.hpp.
Referenced by onInitialize(), onOrthogonalAllocation(), and sendNextGoal().
onNavigationRequestAborted
smacc2::SmaccSignal<void()> cl_nitrosz::CpWaypointNavigator::onNavigationRequestAborted
Definition at line 71 of file cp_waypoints_navigator.hpp.
Referenced by onGoalAborted().
onNavigationRequestCancelled
smacc2::SmaccSignal<void()> cl_nitrosz::CpWaypointNavigator::onNavigationRequestCancelled
Definition at line 72 of file cp_waypoints_navigator.hpp.
Referenced by onGoalCancelled().
onNavigationRequestSucceded
smacc2::SmaccSignal<void()> cl_nitrosz::CpWaypointNavigator::onNavigationRequestSucceded
Definition at line 70 of file cp_waypoints_navigator.hpp.
Referenced by onGoalReached().
succeddedNav2ZClientConnection_
boost::signals2::connection cl_nitrosz::CpWaypointNavigator::succeddedNav2ZClientConnection_ private
Definition at line 81 of file cp_waypoints_navigator.hpp.
Referenced by sendNextGoal(), and stopWaitingResult().
The documentation for this class was generated from the following files:
smacc2_client_library/nitrosz_client/nitrosz_client/include/nitrosz_client/components/waypoints_navigator/cp_waypoints_navigator.hpp
smacc2_client_library/nitrosz_client/nitrosz_client/src/nitrosz_client/components/waypoints_navigator/cp_waypoints_navigator.cpp