SMACC2: cl_nav2z::CbNavigateNextWaypointUntilReached Class Reference
cl_nav2z::CbNavigateNextWaypointUntilReached Class Reference
#include <cb_navigate_next_waypoint_until_reached.hpp>
Public Member Functions
CbNavigateNextWaypointUntilReached (std::string goalWaypointName, std::optional< NavigateNextWaypointOptions > options=std::nullopt)
virtual ~CbNavigateNextWaypointUntilReached ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onEntry () override
void onExit () override
void onNavigationActionSuccess (const ClNav2Z::WrappedResult &r) override
Public Member Functions inherited from cl_nav2z::CbNavigateNextWaypoint
CbNavigateNextWaypoint (std::optional< NavigateNextWaypointOptions > options=std::nullopt)
virtual ~CbNavigateNextWaypoint ()
void onEntry () override
void onExit () override
Public Member Functions inherited from cl_nav2z::CbNav2ZClientBehaviorBase
virtual ~CbNav2ZClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Attributes
std::string goalWaypointName_
std::function< void()> postEvGoalWaypointReached_
Additional Inherited Members
Protected Member Functions inherited from cl_nav2z::CbNav2ZClientBehaviorBase
void sendGoal (ClNav2Z::Goal &goal)
void cancelGoal ()
bool isOwnActionResponse (const ClNav2Z::WrappedResult &)
virtual void onNavigationResult (const ClNav2Z::WrappedResult &)
virtual void onNavigationActionSuccess (const ClNav2Z::WrappedResult &)
virtual void onNavigationActionAbort (const ClNav2Z::WrappedResult &)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Attributes inherited from cl_nav2z::CbNavigateNextWaypoint
CpWaypointNavigator * waypointsNavigator_
NavigateNextWaypointOptions options_
cl_nav2z::ClNav2Z::SmaccNavigateResultSignal::SharedPtr navigationCallback_
Protected Attributes inherited from cl_nav2z::CbNav2ZClientBehaviorBase
cl_nav2z::ClNav2Z * nav2zClient_
cl_nav2z::ClNav2Z::SmaccNavigateResultSignal::SharedPtr navigationCallback_
rclcpp_action::ResultCode navigationResult_
std::shared_future< std::shared_ptr< rclcpp_action::ClientGoalHandle< nav2_msgs::action::NavigateToPose > > > goalHandleFuture_
Detailed Description
Definition at line 31 of file cb_navigate_next_waypoint_until_reached.hpp.
Constructor & Destructor Documentation
CbNavigateNextWaypointUntilReached()
cl_nav2z::CbNavigateNextWaypointUntilReached::CbNavigateNextWaypointUntilReached (std::string goalWaypointName, std::optional< NavigateNextWaypointOptions > options = std::nullopt)
Definition at line 25 of file cb_navigate_next_waypoint_until_reached.cpp.
: CbNavigateNextWaypoint(options), goalWaypointName_(goalWaypointName)
{
}
~CbNavigateNextWaypointUntilReached()
cl_nav2z::CbNavigateNextWaypointUntilReached::~CbNavigateNextWaypointUntilReached () virtual
Definition at line 31 of file cb_navigate_next_waypoint_until_reached.cpp.
{}
Member Function Documentation
onEntry()
void cl_nav2z::CbNavigateNextWaypointUntilReached::onEntry () override virtual
Reimplemented from cl_nav2z::CbNavigateNextWaypoint.
Definition at line 33 of file cb_navigate_next_waypoint_until_reached.cpp.
{ CbNavigateNextWaypoint::onEntry(); }
References cl_nav2z::CbNavigateNextWaypoint::onEntry().
onExit()
void cl_nav2z::CbNavigateNextWaypointUntilReached::onExit () override virtual
Reimplemented from cl_nav2z::CbNavigateNextWaypoint.
Definition at line 35 of file cb_navigate_next_waypoint_until_reached.cpp.
{ CbNavigateNextWaypoint::onExit(); }
References cl_nav2z::CbNavigateNextWaypoint::onExit().
onNavigationActionSuccess()
void cl_nav2z::CbNavigateNextWaypointUntilReached::onNavigationActionSuccess (const ClNav2Z::WrappedResult & r) inline override virtual
Reimplemented from cl_nav2z::CbNav2ZClientBehaviorBase.
Definition at line 58 of file cb_navigate_next_waypoint_until_reached.hpp.
  {
    // if (!isOwnActionResponse(r))
    // {
    //   RCLCPP_WARN(
    //     getLogger(), "[%s] Propagating success event skipped. Action response is not ours.",
    //     getName().c_str());
    //   return;
    // }
    navigationResult_ = r.code;
    RCLCPP_INFO(
      getLogger(), "[%s] Propagating success event from action server", getName().c_str());
    waypointsNavigator_ = nav2zClient_->getComponent<CpWaypointNavigator>();
    auto current_waypoint_name = waypointsNavigator_->getCurrentWaypointName();
    if (current_waypoint_name == this->goalWaypointName_)
    {
      RCLCPP_INFO(
        getLogger(),
        "[CbNavigateNextWaypointUntilReached] GoalReached current iteration waypoint i: %ld with "
        "name '%s'",
        waypointsNavigator_->getCurrentWaypointIndex(), current_waypoint_name->c_str());
      this->postEvGoalWaypointReached_();
    }
    else
    {
      RCLCPP_INFO(
        getLogger(),
        "[CbNavigateNextWaypointUntilReached] goal:'%s' current:'%s'. keep navigating.",
        goalWaypointName_.c_str(), current_waypoint_name->c_str());
    }
    this->postSuccessEvent();
  }
References smacc2::ISmaccClient::getComponent(), cl_nav2z::CpWaypointNavigatorBase::getCurrentWaypointIndex(), cl_nav2z::CpWaypointNavigatorBase::getCurrentWaypointName(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), goalWaypointName_, cl_nav2z::CbNav2ZClientBehaviorBase::nav2zClient_, cl_nav2z::CbNav2ZClientBehaviorBase::navigationResult_, postEvGoalWaypointReached_, smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), and cl_nav2z::CbNavigateNextWaypoint::waypointsNavigator_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_nav2z::CbNavigateNextWaypointUntilReached::onOrthogonalAllocation () inline
Definition at line 41 of file cb_navigate_next_waypoint_until_reached.hpp.
  {
    this->requiresClient(nav2zClient_);
    CbNavigateNextWaypoint::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
    postEvGoalWaypointReached_ = [this]()
    {
      this->postEvent<EvGoalWaypointReached<TSourceObject, TOrthogonal>>();
      // nav2zClient_->onSucceeded(&CbNavigateNextWaypointUntilReached::onWaypointReached, this);
    };
  }
References cl_nav2z::CbNav2ZClientBehaviorBase::nav2zClient_, postEvGoalWaypointReached_, and smacc2::ISmaccClientBehavior::requiresClient().
Member Data Documentation
goalWaypointName_
std::string cl_nav2z::CbNavigateNextWaypointUntilReached::goalWaypointName_ private
Definition at line 99 of file cb_navigate_next_waypoint_until_reached.hpp.
Referenced by onNavigationActionSuccess().
postEvGoalWaypointReached_
std::function<void()> cl_nav2z::CbNavigateNextWaypointUntilReached::postEvGoalWaypointReached_ private
Definition at line 101 of file cb_navigate_next_waypoint_until_reached.hpp.
Referenced by onNavigationActionSuccess(), and onOrthogonalAllocation().
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/client_behaviors/cb_navigate_next_waypoint_until_reached.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/client_behaviors/cb_navigate_next_waypoint_until_reached.cpp