SMACC2: smacc2::client_behaviors::CbRosLaunch Class Reference
smacc2::client_behaviors::CbRosLaunch Class Reference
#include <cb_ros_launch.hpp>
Public Member Functions
CbRosLaunch ()
CbRosLaunch (std::string package, std::string launchfile, RosLaunchMode)
virtual ~CbRosLaunch ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onExit ()
Public Attributes
std::optional< std::string > packageName_
std::optional< std::string > launchFileName_
RosLaunchMode launchMode_
Protected Attributes
std::string result_
smacc2::client_bases::ClRosLaunch * client_
std::future< std::string > future_
Static Private Attributes
static std::vector< std::future< std::string > > detached_futures_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 35 of file cb_ros_launch.hpp.
Constructor & Destructor Documentation
CbRosLaunch() [1/2]
smacc2::client_behaviors::CbRosLaunch::CbRosLaunch ()
Definition at line 28 of file cb_ros_launch.cpp.
: packageName_(std::nullopt),
  launchFileName_(std::nullopt),
  launchMode_(RosLaunchMode::LAUNCH_CLIENT_BEHAVIOR_LIFETIME)
{
}
CbRosLaunch() [2/2]
smacc2::client_behaviors::CbRosLaunch::CbRosLaunch (std::string package, std::string launchfile, RosLaunchMode launchmode)
Definition at line 35 of file cb_ros_launch.cpp.
: packageName_(package), launchFileName_(launchfile), launchMode_(launchmode)
{
}
~CbRosLaunch()
smacc2::client_behaviors::CbRosLaunch::~CbRosLaunch () virtual
Definition at line 40 of file cb_ros_launch.cpp.
{}
Member Function Documentation
onEntry()
void smacc2::client_behaviors::CbRosLaunch::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 48 of file cb_ros_launch.cpp.
{
  RCLCPP_INFO_STREAM(getLogger(), "[CbRosLaunch] OnEntry");
  std::string packageName, launchFileName;
  if (launchFileName_ && packageName_)
  {
    std::function<bool()> breakfunction;
    if (launchMode_ == RosLaunchMode::LAUNCH_CLIENT_BEHAVIOR_LIFETIME)
    {
      breakfunction = [this]() -> bool { return this->isShutdownRequested(); };
    }
    else
    {
      breakfunction = []() -> bool { return false; };
    }
    RCLCPP_INFO_STREAM(
      getLogger(), "[CbRosLaunch] launching: " << *packageName_ << " , " << *launchFileName_
                                               << "LaunchMode: " << (int)launchMode_);
    auto fut = smacc2::client_bases::ClRosLaunch::executeRosLaunch(
      *packageName_, *launchFileName_, breakfunction);
    if (launchMode_ == RosLaunchMode::LAUNCH_DETTACHED)
      detached_futures_.push_back(std::move(fut));
    else
      future_ = std::move(fut);
  }
  else
  {
    RCLCPP_INFO_STREAM(getLogger(), "[CbRosLaunch] finding Ros Launch client");
    this->requiresClient(client_);
    if (client_ != nullptr)
    {
      RCLCPP_INFO_STREAM(
        getLogger(), "[CbRosLaunch] launching from client: " << client_->packageName_ << " , "
                                                             << client_->launchFileName_);
      client_->launch();
    }
    else
    {
      RCLCPP_ERROR(
        getLogger(),
        "[CbRosLaunch] Inccorrect ros launch operation. No Ros Launch client specified neither "
        "package/roslaunch file path.");
    }
  }
}
References client_, detached_futures_, smacc2::client_bases::ClRosLaunch::executeRosLaunch(), future_, smacc2::ISmaccClientBehavior::getLogger(), smacc2::SmaccAsyncClientBehavior::isShutdownRequested(), smacc2::client_bases::ClRosLaunch::launch(), smacc2::client_behaviors::LAUNCH_CLIENT_BEHAVIOR_LIFETIME, smacc2::client_behaviors::LAUNCH_DETTACHED, smacc2::client_bases::ClRosLaunch::launchFileName_, launchFileName_, launchMode_, smacc2::client_bases::ClRosLaunch::packageName_, packageName_, and smacc2::ISmaccClientBehavior::requiresClient().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc2::client_behaviors::CbRosLaunch::onOrthogonalAllocation () inline
Definition at line 50 of file cb_ros_launch.hpp.
  {
    smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
  }
References smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation().
Member Data Documentation
client_
smacc2::client_bases::ClRosLaunch* smacc2::client_behaviors::CbRosLaunch::client_ protected
Definition at line 65 of file cb_ros_launch.hpp.
Referenced by onEntry().
detached_futures_
std::vector< std::future< std::string > > smacc2::client_behaviors::CbRosLaunch::detached_futures_ static private
Definition at line 38 of file cb_ros_launch.hpp.
Referenced by onEntry().
future_
std::future<std::string> smacc2::client_behaviors::CbRosLaunch::future_ protected
Definition at line 67 of file cb_ros_launch.hpp.
Referenced by onEntry().
launchFileName_
std::optional<std::string> smacc2::client_behaviors::CbRosLaunch::launchFileName_
Definition at line 58 of file cb_ros_launch.hpp.
Referenced by onEntry().
launchMode_
RosLaunchMode smacc2::client_behaviors::CbRosLaunch::launchMode_
Definition at line 60 of file cb_ros_launch.hpp.
Referenced by onEntry().
packageName_
std::optional<std::string> smacc2::client_behaviors::CbRosLaunch::packageName_
Definition at line 57 of file cb_ros_launch.hpp.
Referenced by onEntry().
result_
std::string smacc2::client_behaviors::CbRosLaunch::result_ protected
Definition at line 63 of file cb_ros_launch.hpp.
The documentation for this class was generated from the following files:
smacc2/include/smacc2/client_behaviors/cb_ros_launch.hpp
smacc2/src/smacc2/client_behaviors/cb_ros_launch.cpp