SMACC2: cl_move_group_interface::CbMoveLastTrajectoryInitialState Class Reference
cl_move_group_interface::CbMoveLastTrajectoryInitialState Class Reference
#include <cb_move_last_trajectory_initial_state.hpp>
Public Member Functions
CbMoveLastTrajectoryInitialState ()
CbMoveLastTrajectoryInitialState (int backIndex)
virtual ~CbMoveLastTrajectoryInitialState ()
virtual void onEntry () override
Public Member Functions inherited from cl_move_group_interface::CbMoveJoints
CbMoveJoints ()
CbMoveJoints (const std::map< std::string, double > &jointValueTarget)
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Attributes
int backIndex_ = -1
Additional Inherited Members
Public Attributes inherited from cl_move_group_interface::CbMoveJoints
std::optional< double > scalingFactor_
std::map< std::string, double > jointValueTarget_
std::optional< std::string > group_
Protected Member Functions inherited from cl_move_group_interface::CbMoveJoints
void moveJoints (moveit::planning_interface::MoveGroupInterface &moveGroupInterface)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Attributes inherited from cl_move_group_interface::CbMoveJoints
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 27 of file cb_move_last_trajectory_initial_state.hpp.
Constructor & Destructor Documentation
CbMoveLastTrajectoryInitialState() [1/2]
cl_move_group_interface::CbMoveLastTrajectoryInitialState::CbMoveLastTrajectoryInitialState ()
Definition at line 26 of file cb_move_last_trajectory_initial_state.cpp.
{}
CbMoveLastTrajectoryInitialState() [2/2]
cl_move_group_interface::CbMoveLastTrajectoryInitialState::CbMoveLastTrajectoryInitialState (int backIndex)
Definition at line 28 of file cb_move_last_trajectory_initial_state.cpp.
: backIndex_(backIndex)
{
}
~CbMoveLastTrajectoryInitialState()
cl_move_group_interface::CbMoveLastTrajectoryInitialState::~CbMoveLastTrajectoryInitialState () virtual
Definition at line 33 of file cb_move_last_trajectory_initial_state.cpp.
{}
Member Function Documentation
onEntry()
void cl_move_group_interface::CbMoveLastTrajectoryInitialState::onEntry () override virtual
Reimplemented from cl_move_group_interface::CbMoveJoints.
Definition at line 35 of file cb_move_last_trajectory_initial_state.cpp.
{
  CpTrajectoryHistory * trajectoryHistory;
  this->requiresComponent(trajectoryHistory);
  if (trajectoryHistory != nullptr)
  {
    moveit_msgs::msg::RobotTrajectory trajectory;
    bool trajectoryFound = trajectoryHistory->getLastTrajectory(backIndex_, trajectory);
    if (trajectoryFound)
    {
      trajectory_msgs::msg::JointTrajectoryPoint & initialPoint =
        trajectory.joint_trajectory.points.front();
      std::stringstream ss;
      for (size_t i = 0; i < trajectory.joint_trajectory.joint_names.size(); i++)
      {
        auto & name = trajectory.joint_trajectory.joint_names[i];
        jointValueTarget_[name] = initialPoint.positions[i];
        ss << name << ": " << jointValueTarget_[name] << std::endl;
      }
      RCLCPP_INFO_STREAM(getLogger(), "[" << this->getName() << "]" << std::endl << ss.str());
      RCLCPP_INFO_STREAM(getLogger(), "[" << this->getName() << "] move joint onEntry");
      CbMoveJoints::onEntry();
      RCLCPP_INFO_STREAM(getLogger(), "[" << this->getName() << "] move joint onEntry finished");
    }
  }
  //call base OnEntry
}
References backIndex_, cl_move_group_interface::CpTrajectoryHistory::getLastTrajectory(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), cl_move_group_interface::CbMoveJoints::jointValueTarget_, cl_move_group_interface::CbMoveJoints::onEntry(), and smacc2::ISmaccClientBehavior::requiresComponent().
Member Data Documentation
backIndex_
int cl_move_group_interface::CbMoveLastTrajectoryInitialState::backIndex_ = -1 private
Definition at line 39 of file cb_move_last_trajectory_initial_state.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_move_last_trajectory_initial_state.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_move_last_trajectory_initial_state.cpp