SMACC2: smacc2::ClientHandler< TOrthogonal, TClient > Class Template Reference
smacc2::ClientHandler< TOrthogonal, TClient > Class Template Reference
#include <smacc_orthogonal_impl.hpp>
Public Member Functions
template<typename... TArgs>
ClientHandler (TArgs... args)
ClientHandler ()
template<typename SmaccComponentType , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
smacc2::introspection::TypeInfo::Ptr getType () override
Detailed Description
template<typename TOrthogonal, typename TClient>
class smacc2::ClientHandler< TOrthogonal, TClient >
Definition at line 135 of file smacc_orthogonal_impl.hpp.
Constructor & Destructor Documentation
ClientHandler() [1/2]
template<typename TOrthogonal , typename TClient > template<typename... TArgs> smacc2::ClientHandler< TOrthogonal, TClient >::ClientHandler (TArgs... args) inline
Definition at line 139 of file smacc_orthogonal_impl.hpp.
                               : TClient(args...)
  {
  }
ClientHandler() [2/2]
template<typename TOrthogonal , typename TClient > smacc2::ClientHandler< TOrthogonal, TClient >::ClientHandler () inline
Definition at line 143 of file smacc_orthogonal_impl.hpp.
: TClient() {}
Member Function Documentation
createComponent()
template<typename TOrthogonal , typename TClient > template<typename SmaccComponentType , typename... TArgs> SmaccComponentType * smacc2::ClientHandler< TOrthogonal, TClient >::createComponent (TArgs... targs) inline
Definition at line 146 of file smacc_orthogonal_impl.hpp.
  {
    return ISmaccClient::createComponent<SmaccComponentType, TOrthogonal, TClient, TArgs...>(
      targs...);
  }
References smacc2::ISmaccClient::createComponent().
createNamedComponent()
template<typename TOrthogonal , typename TClient > template<typename SmaccComponentType , typename... TArgs> SmaccComponentType * smacc2::ClientHandler< TOrthogonal, TClient >::createNamedComponent (std::string name, TArgs... targs) inline
Definition at line 153 of file smacc_orthogonal_impl.hpp.
  {
    return ISmaccClient::createNamedComponent<SmaccComponentType, TOrthogonal, TClient, TArgs...>(
      name, targs...);
  }
References smacc2::ISmaccClient::createNamedComponent().
getType()
template<typename TOrthogonal , typename TClient > smacc2::introspection::TypeInfo::Ptr smacc2::ClientHandler< TOrthogonal, TClient >::getType () inline override
Definition at line 159 of file smacc_orthogonal_impl.hpp.
  {
    return smacc2::introspection::TypeInfo::getTypeInfoFromType<TClient>();
  }
References smacc2::introspection::TypeInfo::getTypeInfoFromType().
The documentation for this class was generated from the following file:
smacc2/include/smacc2/impl/smacc_orthogonal_impl.hpp