SMACC2: smacc2::introspection::StateReactorHandler Class Reference
smacc2::introspection::StateReactorHandler Class Reference
#include <smacc_state_info.hpp>
Public Member Functions
StateReactorHandler (rclcpp::Node::SharedPtr nh)
void configureStateReactor (std::shared_ptr< smacc2::StateReactor > sr)
template<typename TEv >
void addInputEvent ()
template<typename TEv >
void setOutputEvent ()
rclcpp::Node::SharedPtr getNode ()
Public Attributes
std::shared_ptr< smacc2::introspection::SmaccStateReactorInfo > srInfo_
Private Attributes
std::vector< StateReactorCallbackFunctor > callbacks_
rclcpp::Node::SharedPtr nh_
Detailed Description
Definition at line 83 of file smacc_state_info.hpp.
Constructor & Destructor Documentation
StateReactorHandler()
smacc2::introspection::StateReactorHandler::StateReactorHandler (rclcpp::Node::SharedPtr nh) inline
Definition at line 89 of file smacc_state_info.hpp.
: nh_(nh) {}
Member Function Documentation
addInputEvent()
template<typename TEv > void smacc2::introspection::StateReactorHandler::addInputEvent ()
Definition at line 82 of file smacc_state_reactor_impl.hpp.
{
  StateReactorCallbackFunctor functor;
  functor.fn = [this](std::shared_ptr<smacc2::StateReactor> sr)
  {
    RCLCPP_INFO(
      nh_->get_logger(), "[%s] State Reactor adding input event: %s",
      srInfo_->stateReactorType->getFullName().c_str(), demangledTypeName<TEv>().c_str());
    sr->addInputEvent<TEv>();
  };
  this->callbacks_.push_back(functor);
  auto evtype = TypeInfo::getFromStdTypeInfo(typeid(TEv));
  auto evinfo = std::make_shared<SmaccEventInfo>(evtype);
  EventLabel<TEv>(evinfo->label);
  srInfo_->sourceEventTypes.push_back(evinfo);
}
References callbacks_, smacc2::introspection::demangledTypeName(), smacc2::introspection::EventLabel(), smacc2::introspection::StateReactorCallbackFunctor::fn, smacc2::introspection::TypeInfo::getFromStdTypeInfo(), nh_, and srInfo_.
configureStateReactor()
void smacc2::introspection::StateReactorHandler::configureStateReactor (std::shared_ptr< smacc2::StateReactor > sr)
Definition at line 62 of file state_reactor.cpp.
{
  for (auto callback : this->callbacks_)
  {
    callback.fn(sb);
  }
}
References callbacks_.
getNode()
rclcpp::Node::SharedPtr smacc2::introspection::StateReactorHandler::getNode ()
setOutputEvent()
template<typename TEv > void smacc2::introspection::StateReactorHandler::setOutputEvent ()
Definition at line 103 of file smacc_state_reactor_impl.hpp.
{
  StateReactorCallbackFunctor functor;
  functor.fn = [this](std::shared_ptr<smacc2::StateReactor> sr)
  {
    RCLCPP_INFO(
      nh_->get_logger(), "[%s] State Reactor setting output event: %s",
      srInfo_->stateReactorType->getFullName().c_str(), demangledTypeName<TEv>().c_str());
    sr->setOutputEvent<TEv>();
  };
  this->callbacks_.push_back(functor);
}
References callbacks_, smacc2::introspection::demangledTypeName(), smacc2::introspection::StateReactorCallbackFunctor::fn, nh_, and srInfo_.
Member Data Documentation
callbacks_
std::vector<StateReactorCallbackFunctor> smacc2::introspection::StateReactorHandler::callbacks_ private
Definition at line 86 of file smacc_state_info.hpp.
Referenced by addInputEvent(), configureStateReactor(), and setOutputEvent().
nh_
rclcpp::Node::SharedPtr smacc2::introspection::StateReactorHandler::nh_ private
Definition at line 104 of file smacc_state_info.hpp.
Referenced by addInputEvent(), and setOutputEvent().
srInfo_
std::shared_ptr<smacc2::introspection::SmaccStateReactorInfo> smacc2::introspection::StateReactorHandler::srInfo_
Definition at line 101 of file smacc_state_info.hpp.
Referenced by addInputEvent(), and setOutputEvent().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/introspection/smacc_state_info.hpp
smacc2/include/smacc2/impl/smacc_state_reactor_impl.hpp
smacc2/src/smacc2/state_reactor.cpp