SMACC2: cl_multirole_sensor::ClMultiroleSensor< MessageType > Class Template Reference
cl_multirole_sensor::ClMultiroleSensor< MessageType > Class Template Reference
#include <cl_multirole_sensor.hpp>
Public Types
typedef MessageType TMessageType
Public Types inherited from smacc2::client_bases::SmaccSubscriberClient< MessageType >
typedef MessageType TMessageType
Public Member Functions
ClMultiroleSensor ()
template<typename T >
boost::signals2::connection onMessageTimeout (void(T::*callback)(), T *object)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onInitialize () override
Public Member Functions inherited from smacc2::client_bases::SmaccSubscriberClient< MessageType >
SmaccSubscriberClient ()
SmaccSubscriberClient (std::string topicname)
virtual ~SmaccSubscriberClient ()
template<typename T >
boost::signals2::connection onMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename T >
boost::signals2::connection onFirstMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Public Attributes
SmaccSignal< void()> onMessageTimeout_
std::function< void()> postTimeoutMessageEvent
std::optional< rclcpp::Duration > timeout_
Public Attributes inherited from smacc2::client_bases::SmaccSubscriberClient< MessageType >
std::optional< std::string > topicName
std::optional< int > queueSize
smacc2::SmaccSignal< void(const MessageType &)> onFirstMessageReceived_
smacc2::SmaccSignal< void(const MessageType &)> onMessageReceived_
std::function< void(const MessageType &)> postMessageEvent
std::function< void(const MessageType &)> postInitialMessageEvent
Protected Member Functions
void resetTimer (const MessageType &)
Protected Member Functions inherited from smacc2::client_bases::SmaccSubscriberClient< MessageType >
void onInitialize () override
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Private Member Functions
void timeoutCallback ()
Private Attributes
rclcpp::TimerBase::SharedPtr timeoutTimer_
bool initialized_
Additional Inherited Members
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Detailed Description
template<typename MessageType>
class cl_multirole_sensor::ClMultiroleSensor< MessageType >
Definition at line 37 of file cl_multirole_sensor.hpp.
Member Typedef Documentation
TMessageType
template<typename MessageType > typedef MessageType cl_multirole_sensor::ClMultiroleSensor< MessageType >::TMessageType
Definition at line 40 of file cl_multirole_sensor.hpp.
Constructor & Destructor Documentation
ClMultiroleSensor()
template<typename MessageType > cl_multirole_sensor::ClMultiroleSensor< MessageType >::ClMultiroleSensor () inline
Definition at line 43 of file cl_multirole_sensor.hpp.
                      : smacc2::client_bases::SmaccSubscriberClient<MessageType>()
  {
    initialized_ = false;
  }
References cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialized_.
Member Function Documentation
onInitialize()
template<typename MessageType > void cl_multirole_sensor::ClMultiroleSensor< MessageType >::onInitialize () inline override virtual
Reimplemented from smacc2::ISmaccClient.
Definition at line 71 of file cl_multirole_sensor.hpp.
  {
    if (!initialized_)
    {
      SmaccSubscriberClient<MessageType>::onInitialize();
      this->onMessageReceived(&ClMultiroleSensor<MessageType>::resetTimer, this);
      if (timeout_)
      {
        auto ros_clock = rclcpp::Clock::make_shared();
        timeoutTimer_ = rclcpp::create_timer(
          this->getNode(), this->getNode()->get_clock(), *timeout_,
          std::bind(&ClMultiroleSensor<MessageType>::timeoutCallback, this));
        timeoutTimer_->reset();
      }
      else
      {
        RCLCPP_WARN(
          this->getLogger(),
          "Timeout sensor client not set, skipping timeout watchdog funcionality");
      }
      initialized_ = true;
    }
  }
References smacc2::ISmaccClient::getLogger(), smacc2::ISmaccClient::getNode(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialized_, smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeout_, and cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeoutTimer_.
onMessageTimeout()
template<typename MessageType > template<typename T > boost::signals2::connection cl_multirole_sensor::ClMultiroleSensor< MessageType >::onMessageTimeout (void(T::*)() callback, T * object) inline
Definition at line 49 of file cl_multirole_sensor.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onMessageTimeout_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), and smacc2::ISmaccClient::getStateMachine().
onOrthogonalAllocation()
template<typename MessageType > template<typename TOrthogonal , typename TSourceObject > void cl_multirole_sensor::ClMultiroleSensor< MessageType >::onOrthogonalAllocation () inline
Definition at line 57 of file cl_multirole_sensor.hpp.
  {
    SmaccSubscriberClient<MessageType>::template onOrthogonalAllocation<
      TOrthogonal, TSourceObject>();
    this->postTimeoutMessageEvent = [this]()
    {
      this->onMessageTimeout_();
      auto event = new EvTopicMessageTimeout<TSourceObject, TOrthogonal>();
      this->postEvent(event);
    };
  }
References cl_multirole_sensor::ClMultiroleSensor< MessageType >::onMessageTimeout_, cl_multirole_sensor::ClMultiroleSensor< MessageType >::onOrthogonalAllocation(), and smacc2::ISmaccClient::postEvent().
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::onOrthogonalAllocation().
resetTimer()
template<typename MessageType > void cl_multirole_sensor::ClMultiroleSensor< MessageType >::resetTimer (const MessageType &) inline protected
Definition at line 102 of file cl_multirole_sensor.hpp.
  {
    //resetting the timer
    timeoutTimer_->reset();
    //timeoutTimer_->stop();
    //timeoutTimer_->start();
  }
References cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeoutTimer_.
timeoutCallback()
template<typename MessageType > void cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeoutCallback () inline private
Definition at line 114 of file cl_multirole_sensor.hpp.
{ postTimeoutMessageEvent(); }
References cl_multirole_sensor::ClMultiroleSensor< MessageType >::postTimeoutMessageEvent.
Member Data Documentation
initialized_
template<typename MessageType > bool cl_multirole_sensor::ClMultiroleSensor< MessageType >::initialized_ private
Definition at line 112 of file cl_multirole_sensor.hpp.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::ClMultiroleSensor(), and cl_multirole_sensor::ClMultiroleSensor< MessageType >::onInitialize().
onMessageTimeout_
template<typename MessageType > SmaccSignal<void()> cl_multirole_sensor::ClMultiroleSensor< MessageType >::onMessageTimeout_
Definition at line 41 of file cl_multirole_sensor.hpp.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::onOrthogonalAllocation().
postTimeoutMessageEvent
template<typename MessageType > std::function<void()> cl_multirole_sensor::ClMultiroleSensor< MessageType >::postTimeoutMessageEvent
Definition at line 54 of file cl_multirole_sensor.hpp.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeoutCallback().
timeout_
template<typename MessageType > std::optional<rclcpp::Duration> cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeout_
Definition at line 99 of file cl_multirole_sensor.hpp.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::onInitialize().
timeoutTimer_
template<typename MessageType > rclcpp::TimerBase::SharedPtr cl_multirole_sensor::ClMultiroleSensor< MessageType >::timeoutTimer_ private
Definition at line 111 of file cl_multirole_sensor.hpp.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::onInitialize(), and cl_multirole_sensor::ClMultiroleSensor< MessageType >::resetTimer().
The documentation for this class was generated from the following file:
smacc2_client_library/multirole_sensor_client/include/multirole_sensor_client/cl_multirole_sensor.hpp