SMACC2: cl_lifecyclenode::ClLifecycleNode Class Reference
cl_lifecyclenode::ClLifecycleNode Class Reference
#include <lifecyclenode_client.hpp>
Public Member Functions
ClLifecycleNode (std::string nodeName)
virtual ~ClLifecycleNode ()
void onInitialize () override
void changeState (uint8_t state)
void configure ()
void activate ()
void deactivate ()
void cleanup ()
void shutdown ()
void destroy ()
virtual void onTransitionEvent (const lifecycle_msgs::msg::TransitionEvent::SharedPtr msg)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Public Attributes
boost::signals2::signal< void(const lifecycle_msgs::msg::TransitionEvent::SharedPtr)> onTransitionEventSignal
boost::signals2::signal< void()> onTransitionCreate_
boost::signals2::signal< void()> onTransitionConfigure_
boost::signals2::signal< void()> onTransitionCleanup_
boost::signals2::signal< void()> onTransitionActivate_
boost::signals2::signal< void()> onTransitionDeactivate_
boost::signals2::signal< void()> onTransitionUnconfiguredShutdown_
boost::signals2::signal< void()> onTransitionInactiveShutdown_
boost::signals2::signal< void()> onTransitionActiveShutdown_
boost::signals2::signal< void()> onTransitionDestroy_
boost::signals2::signal< void()> onTransitionOnConfigureSuccess_
boost::signals2::signal< void()> onTransitionOnConfigureFailure_
boost::signals2::signal< void()> onTransitionOnConfigureError_
boost::signals2::signal< void()> onTransitionOnActivateSuccess_
boost::signals2::signal< void()> onTransitionOnActivateFailure_
boost::signals2::signal< void()> onTransitionOnActivateError_
boost::signals2::signal< void()> onTransitionOnDeactivateSuccess_
boost::signals2::signal< void()> onTransitionOnDeactivateFailure_
boost::signals2::signal< void()> onTransitionOnDeactivateError_
boost::signals2::signal< void()> onTransitionOnCleanupSuccess_
boost::signals2::signal< void()> onTransitionOnCleanupFailure_
boost::signals2::signal< void()> onTransitionOnCleanupError_
boost::signals2::signal< void()> onTransitionOnShutdownSuccess_
boost::signals2::signal< void()> onTransitionOnShutdownFailure_
boost::signals2::signal< void()> onTransitionOnShutdownError_
boost::signals2::signal< void()> onTransitionOnActiveShutdownSuccess_
boost::signals2::signal< void()> onTransitionOnActiveShutdownFailure_
boost::signals2::signal< void()> onTransitionOnActiveShutdownError_
boost::signals2::signal< void()> onTransitionOnErrorSuccess_
boost::signals2::signal< void()> onTransitionOnErrorFailure_
boost::signals2::signal< void()> onTransitionOnErrorError_
Private Attributes
rclcpp::Client< lifecycle_msgs::srv::GetState >::SharedPtr client_get_state_
rclcpp::Client< lifecycle_msgs::srv::ChangeState >::SharedPtr client_change_state_
rclcpp::Subscription< lifecycle_msgs::msg::TransitionEvent >::SharedPtr subscription_transition_event_
std::string nodeName_
const std::string node_get_state_topic = "/get_state"
const std::string node_change_state_topic = "/change_state"
const std::string node_transition_event_topic = "/transition_event"
lifecycle_msgs::msg::TransitionEvent::SharedPtr lastTransitionEvent_
std::function< void()> postOnTransitionCreate_
std::function< void()> postOnTransitionConfigure_
std::function< void()> postOnTransitionCleanup_
std::function< void()> postOnTransitionActivate_
std::function< void()> postOnTransitionDeactivate_
std::function< void()> postOnTransitionUnconfiguredShutdown_
std::function< void()> postOnTransitionInactiveShutdown_
std::function< void()> postOnTransitionActiveShutdown_
std::function< void()> postOnTransitionDestroy_
std::function< void()> postOnTransitionOnConfigureSuccess_
std::function< void()> postOnTransitionOnConfigureFailure_
std::function< void()> postOnTransitionOnConfigureError_
std::function< void()> postOnTransitionOnActivateSuccess_
std::function< void()> postOnTransitionOnActivateFailure_
std::function< void()> postOnTransitionOnActivateError_
std::function< void()> postOnTransitionOnDeactivateSuccess_
std::function< void()> postOnTransitionOnDeactivateFailure_
std::function< void()> postOnTransitionOnDeactivateError_
std::function< void()> postOnTransitionOnCleanupSuccess_
std::function< void()> postOnTransitionOnCleanupFailure_
std::function< void()> postOnTransitionOnCleanupError_
std::function< void()> postOnTransitionOnShutdownSuccess_
std::function< void()> postOnTransitionOnShutdownFailure_
std::function< void()> postOnTransitionOnShutdownError_
std::function< void()> postOnTransitionOnErrorSuccess_
std::function< void()> postOnTransitionOnErrorFailure_
std::function< void()> postOnTransitionOnErrorError_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Detailed Description
Definition at line 192 of file lifecyclenode_client.hpp.
Constructor & Destructor Documentation
ClLifecycleNode()
cl_lifecyclenode::ClLifecycleNode::ClLifecycleNode (std::string nodeName)
Definition at line 25 of file lifecyclenode_client.cpp.
: nodeName_(node_name) {}
~ClLifecycleNode()
cl_lifecyclenode::ClLifecycleNode::~ClLifecycleNode () virtual
Definition at line 27 of file lifecyclenode_client.cpp.
{}
Member Function Documentation
activate()
void cl_lifecyclenode::ClLifecycleNode::activate ()
Definition at line 50 of file lifecyclenode_client.cpp.
{
  changeState(lifecycle_msgs::msg::Transition::TRANSITION_ACTIVATE);
}
References changeState().
Referenced by cl_lifecyclenode::CbActivate::onEntry().
changeState()
void cl_lifecyclenode::ClLifecycleNode::changeState (uint8_t state)
Definition at line 42 of file lifecyclenode_client.cpp.
{
  auto request = std::make_shared<lifecycle_msgs::srv::ChangeState::Request>();
  request->transition.id = state;
  auto future = client_change_state_->async_send_request(request);
  future.wait();
}
References client_change_state_.
Referenced by activate(), cleanup(), configure(), deactivate(), and shutdown().
cleanup()
void cl_lifecyclenode::ClLifecycleNode::cleanup ()
Definition at line 65 of file lifecyclenode_client.cpp.
{
  changeState(lifecycle_msgs::msg::Transition::TRANSITION_CLEANUP);
}
References changeState().
Referenced by cl_lifecyclenode::CbCleanup::onEntry().
configure()
void cl_lifecyclenode::ClLifecycleNode::configure ()
Definition at line 60 of file lifecyclenode_client.cpp.
{
  changeState(lifecycle_msgs::msg::Transition::TRANSITION_CONFIGURE);
}
References changeState().
Referenced by cl_lifecyclenode::CbConfigure::onEntry().
deactivate()
void cl_lifecyclenode::ClLifecycleNode::deactivate ()
Definition at line 55 of file lifecyclenode_client.cpp.
{
  changeState(lifecycle_msgs::msg::Transition::TRANSITION_DEACTIVATE);
}
References changeState().
Referenced by cl_lifecyclenode::CbDeactivate::onEntry(), and cl_lifecyclenode::CbDeactivateOnExit::onExit().
destroy()
void cl_lifecyclenode::ClLifecycleNode::destroy ()
Referenced by cl_lifecyclenode::CbDestroy::onEntry().
onInitialize()
void cl_lifecyclenode::ClLifecycleNode::onInitialize () override virtual
Reimplemented from smacc2::ISmaccClient.
Definition at line 29 of file lifecyclenode_client.cpp.
{
  client_get_state_ = this->getNode()->create_client<lifecycle_msgs::srv::GetState>(
    this->nodeName_ + node_get_state_topic);
  client_change_state_ = this->getNode()->create_client<lifecycle_msgs::srv::ChangeState>(
    this->nodeName_ + node_change_state_topic);
  this->subscription_transition_event_ =
    this->getNode() /*  */->create_subscription<lifecycle_msgs::msg::TransitionEvent>(
      this->nodeName_ + node_transition_event_topic, 100,
      std::bind(&ClLifecycleNode::onTransitionEvent, this, std::placeholders::_1));
}
References client_change_state_, client_get_state_, smacc2::ISmaccClient::getNode(), node_change_state_topic, node_get_state_topic, node_transition_event_topic, nodeName_, onTransitionEvent(), and subscription_transition_event_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_lifecyclenode::ClLifecycleNode::onOrthogonalAllocation () inline
Definition at line 269 of file lifecyclenode_client.hpp.
  {
    this->postOnTransitionCreate_ = [=]()
    {
      RCLCPP_INFO(this->getLogger(), "postOnTransitionCreate_");
      this->onTransitionCreate_();
      sc::event<EvTransitionCreate<TSourceObject, TOrthogonal>> * ev =
        new EvTransitionCreate<TSourceObject, TOrthogonal>();
      this->postEvent(ev);
    };
    this->postOnTransitionConfigure_ = [=]()
    {
      this->onTransitionConfigure_();
      this->postEvent<EvTransitionConfigure<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionActivate_ = [=]()
    {
      this->onTransitionActivate_();
      this->postEvent<EvTransitionActivate<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionDeactivate_ = [=]()
    {
      this->onTransitionDeactivate_();
      this->postEvent<EvTransitionDeactivate<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionUnconfiguredShutdown_ = [=]()
    {
      this->onTransitionUnconfiguredShutdown_();
      this->postEvent<EvTransitionUnconfiguredShutdown<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionInactiveShutdown_ = [=]()
    {
      this->onTransitionInactiveShutdown_();
      this->postEvent<EvTransitionInactiveShutdown<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionActiveShutdown_ = [=]()
    {
      this->onTransitionActiveShutdown_();
      this->postEvent<EvTransitionActiveShutdown<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionDestroy_ = [=]()
    {
      this->onTransitionDestroy_();
      this->postEvent<EvTransitionDestroy<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnConfigureSuccess_ = [=]()
    {
      this->onTransitionOnConfigureSuccess_();
      this->postEvent<EvTransitionOnConfigureSuccess<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnConfigureFailure_ = [=]()
    {
      this->onTransitionOnConfigureFailure_();
      this->postEvent<EvTransitionOnConfigureFailure<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnConfigureError_ = [=]()
    {
      this->onTransitionOnConfigureError_();
      this->postEvent<EvTransitionOnConfigureError<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnActivateSuccess_ = [=]()
    {
      this->onTransitionOnActivateSuccess_();
      this->postEvent<EvTransitionOnActivateSuccess<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnActivateFailure_ = [=]()
    {
      this->onTransitionOnActivateFailure_();
      this->postEvent<EvTransitionOnActivateFailure<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnActivateError_ = [=]()
    {
      this->onTransitionOnActivateError_();
      this->postEvent<EvTransitionOnActivateError<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnDeactivateSuccess_ = [=]()
    {
      this->onTransitionOnDeactivateSuccess_();
      this->postEvent<EvTransitionOnDeactivateSuccess<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnDeactivateFailure_ = [=]()
    {
      this->onTransitionOnDeactivateFailure_();
      this->postEvent<EvTransitionOnDeactivateFailure<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnDeactivateError_ = [=]()
    {
      this->onTransitionOnDeactivateError_();
      this->postEvent<EvTransitionOnDeactivateError<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionCleanup_ = [=]()
    {
      this->onTransitionCleanup_();
      this->postEvent<EvTransitionCleanup<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnCleanupSuccess_ = [=]()
    {
      this->onTransitionOnCleanupSuccess_();
      this->postEvent<EvTransitionOnCleanupSuccess<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnCleanupFailure_ = [=]()
    {
      this->onTransitionOnCleanupFailure_();
      this->postEvent<EvTransitionOnCleanupFailure<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnCleanupError_ = [=]()
    {
      this->onTransitionOnCleanupError_();
      this->postEvent<EvTransitionOnCleanupError<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnShutdownSuccess_ = [=]()
    {
      this->onTransitionOnShutdownSuccess_();
      this->postEvent<EvTransitionOnShutdownSuccess<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnShutdownFailure_ = [=]()
    {
      this->onTransitionOnShutdownFailure_();
      this->postEvent<EvTransitionOnShutdownFailure<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnShutdownError_ = [=]()
    {
      this->onTransitionOnShutdownError_();
      this->postEvent<EvTransitionOnShutdownError<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnErrorSuccess_ = [=]()
    {
      this->onTransitionOnErrorSuccess_();
      this->postEvent<EvTransitionOnErrorSuccess<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnErrorFailure_ = [=]()
    {
      this->onTransitionOnErrorFailure_();
      this->postEvent<EvTransitionOnErrorFailure<TSourceObject, TOrthogonal>>();
    };
    this->postOnTransitionOnErrorError_ = [=]()
    {
      this->onTransitionOnErrorError_();
      this->postEvent<EvTransitionOnErrorError<TSourceObject, TOrthogonal>>();
    };
  }
References smacc2::ISmaccClient::getLogger(), onTransitionActivate_, onTransitionActiveShutdown_, onTransitionCleanup_, onTransitionConfigure_, onTransitionCreate_, onTransitionDeactivate_, onTransitionDestroy_, onTransitionInactiveShutdown_, onTransitionOnActivateError_, onTransitionOnActivateFailure_, onTransitionOnActivateSuccess_, onTransitionOnCleanupError_, onTransitionOnCleanupFailure_, onTransitionOnCleanupSuccess_, onTransitionOnConfigureError_, onTransitionOnConfigureFailure_, onTransitionOnConfigureSuccess_, onTransitionOnDeactivateError_, onTransitionOnDeactivateFailure_, onTransitionOnDeactivateSuccess_, onTransitionOnErrorError_, onTransitionOnErrorFailure_, onTransitionOnErrorSuccess_, onTransitionOnShutdownError_, onTransitionOnShutdownFailure_, onTransitionOnShutdownSuccess_, onTransitionUnconfiguredShutdown_, smacc2::ISmaccClient::postEvent(), postOnTransitionActivate_, postOnTransitionActiveShutdown_, postOnTransitionCleanup_, postOnTransitionConfigure_, postOnTransitionCreate_, postOnTransitionDeactivate_, postOnTransitionDestroy_, postOnTransitionInactiveShutdown_, postOnTransitionOnActivateError_, postOnTransitionOnActivateFailure_, postOnTransitionOnActivateSuccess_, postOnTransitionOnCleanupError_, postOnTransitionOnCleanupFailure_, postOnTransitionOnCleanupSuccess_, postOnTransitionOnConfigureError_, postOnTransitionOnConfigureFailure_, postOnTransitionOnConfigureSuccess_, postOnTransitionOnDeactivateError_, postOnTransitionOnDeactivateFailure_, postOnTransitionOnDeactivateSuccess_, postOnTransitionOnErrorError_, postOnTransitionOnErrorFailure_, postOnTransitionOnErrorSuccess_, postOnTransitionOnShutdownError_, postOnTransitionOnShutdownFailure_, postOnTransitionOnShutdownSuccess_, and postOnTransitionUnconfiguredShutdown_.
onTransitionEvent()
void cl_lifecyclenode::ClLifecycleNode::onTransitionEvent (const lifecycle_msgs::msg::TransitionEvent::SharedPtr msg) virtual
Definition at line 75 of file lifecyclenode_client.cpp.
{
  RCLCPP_INFO(
    this->getNode()->get_logger(), "[ClLifecycleNode] Transition event received: %d -> %d",
    msg->start_state.id, msg->goal_state.id);
  lastTransitionEvent_ = msg;
  // switch (msg->transition.id)
  // {
  // case lifecycle_msgs::msg::Transition::TRANSITION_CREATE:
  // if (msg->start_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_UNKNOWN &&
  //     msg->goal_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_UNCONFIGURED)
  // {
  //   RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_CREATE");
  //   this->postOnTransitionCreate_();
  // }
  // // case lifecycle_msgs::msg::Transition::TRANSITION_CONFIGURE:
  // else
  if (
    msg->start_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_UNCONFIGURED &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_CONFIGURING)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_CONFIGURE");
    this->postOnTransitionConfigure_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_CLEANUP:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_INACTIVE &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_CLEANINGUP)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_CLEANUP");
    this->postOnTransitionCleanup_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ACTIVATE:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_INACTIVE &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ACTIVATING)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ACTIVATE");
    this->postOnTransitionActivate_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_DEACTIVATE:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_ACTIVE &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_DEACTIVATING)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_DEACTIVATE");
    this->postOnTransitionDeactivate_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_UNCONFIGURED_SHUTDOWN:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_UNCONFIGURED &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_SHUTTINGDOWN)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_UNCONFIGURED_SHUTDOWN");
    this->postOnTransitionUnconfiguredShutdown_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_INACTIVE_SHUTDOWN:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_INACTIVE &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_SHUTTINGDOWN)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_INACTIVE_SHUTDOWN");
    this->postOnTransitionInactiveShutdown_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ACTIVE_SHUTDOWN:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_ACTIVE &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_SHUTTINGDOWN)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ACTIVE_SHUTDOWN");
    this->postOnTransitionActiveShutdown_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_DESTROY:
  else if (msg->start_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_FINALIZED)
  // &&msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_DESTROYING
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_DESTROY");
    this->postOnTransitionDestroy_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_CONFIGURE_SUCCESS:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_CONFIGURING &&
    msg->goal_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_INACTIVE)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_CONFIGURE_SUCCESS");
    this->postOnTransitionOnConfigureSuccess_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_CONFIGURE_FAILURE:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_CONFIGURING &&
    msg->goal_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_UNCONFIGURED)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_CONFIGURE_FAILURE");
    this->postOnTransitionOnConfigureFailure_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_CONFIGURE_ERROR:
  if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_CONFIGURING &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ERRORPROCESSING)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_CONFIGURE_ERROR");
    this->postOnTransitionOnConfigureError_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_CLEANUP_SUCCESS:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_CLEANINGUP &&
    msg->goal_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_UNCONFIGURED)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_CLEANUP_SUCCESS");
    this->postOnTransitionOnCleanupSuccess_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_CLEANUP_FAILURE:
  // else if (msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_CLEANINGUP
  // &&msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ERRORPROCESSING)
  // {
  //   RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_CLEANUP_FAILURE");
  //   this->postOnTransitionOnCleanupFailure_();
  // }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_CLEANUP_ERROR:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_CLEANINGUP &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ERRORPROCESSING)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_CLEANUP_ERROR");
    this->postOnTransitionOnCleanupError_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_ACTIVATE_SUCCESS:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ACTIVATING &&
    msg->goal_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_ACTIVE)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_ACTIVATE_SUCCESS");
    this->postOnTransitionOnActivateSuccess_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_ACTIVATE_FAILURE:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ACTIVATING &&
    msg->goal_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_INACTIVE)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_ACTIVATE_FAILURE");
    this->postOnTransitionOnActivateFailure_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_ACTIVATE_ERROR:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ACTIVATING &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ERRORPROCESSING)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_ACTIVATE_ERROR");
    this->postOnTransitionOnActivateError_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_DEACTIVATE_SUCCESS:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_DEACTIVATING &&
    msg->goal_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_INACTIVE)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_DEACTIVATE_SUCCESS");
    this->postOnTransitionOnDeactivateSuccess_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_DEACTIVATE_FAILURE:
  // else if (msg->start_state.id == &&msg->goal_state.id ==)
  // {
  //   RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_DEACTIVATE_FAILURE");
  //   this->postOnTransitionOnDeactivateFailure_();
  // }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_DEACTIVATE_ERROR:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_DEACTIVATING &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ERRORPROCESSING)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_DEACTIVATE_ERROR");
    this->postOnTransitionOnDeactivateError_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_SHUTDOWN_SUCCESS:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_SHUTTINGDOWN &&
    msg->goal_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_FINALIZED)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_SHUTDOWN_SUCCESS");
    this->postOnTransitionOnShutdownSuccess_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_SHUTDOWN_FAILURE:
  // else if (msg->start_state.id == &&msg->goal_state.id ==)
  // {
  //   RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_SHUTDOWN_FAILURE");
  //   this->postOnTransitionOnShutdownFailure_();
  // }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_SHUTDOWN_ERROR:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_SHUTTINGDOWN &&
    msg->goal_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ERRORPROCESSING)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_SHUTDOWN_ERROR");
    this->postOnTransitionOnShutdownError_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_ERROR_SUCCESS:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ERRORPROCESSING &&
    msg->goal_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_UNCONFIGURED)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_ERROR_SUCCESS");
    this->postOnTransitionOnErrorSuccess_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_ERROR_FAILURE:
  else if (
    msg->start_state.id == lifecycle_msgs::msg::State::TRANSITION_STATE_ERRORPROCESSING &&
    msg->goal_state.id == lifecycle_msgs::msg::State::PRIMARY_STATE_FINALIZED)
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_ERROR_FAILURE");
    this->postOnTransitionOnErrorFailure_();
  }
  // case lifecycle_msgs::msg::Transition::TRANSITION_ON_ERROR_ERROR:
  // else if (msg->start_state.id == &&msg->goal_state.id ==)
  // {
  //   RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_ON_ERROR_ERROR");
  //   this->postOnTransitionOnErrorError_();
  // }
  // default:
  else
  {
    RCLCPP_INFO(this->getNode()->get_logger(), "TRANSITION_UNKNOWN");
  }
  // }
}  // namespace cl_lifecyclenode
References smacc2::ISmaccClient::getNode(), lastTransitionEvent_, postOnTransitionActivate_, postOnTransitionActiveShutdown_, postOnTransitionCleanup_, postOnTransitionConfigure_, postOnTransitionDeactivate_, postOnTransitionDestroy_, postOnTransitionInactiveShutdown_, postOnTransitionOnActivateError_, postOnTransitionOnActivateFailure_, postOnTransitionOnActivateSuccess_, postOnTransitionOnCleanupError_, postOnTransitionOnCleanupSuccess_, postOnTransitionOnConfigureError_, postOnTransitionOnConfigureFailure_, postOnTransitionOnConfigureSuccess_, postOnTransitionOnDeactivateError_, postOnTransitionOnDeactivateSuccess_, postOnTransitionOnErrorFailure_, postOnTransitionOnErrorSuccess_, postOnTransitionOnShutdownError_, postOnTransitionOnShutdownSuccess_, and postOnTransitionUnconfiguredShutdown_.
Referenced by onInitialize().
shutdown()
void cl_lifecyclenode::ClLifecycleNode::shutdown ()
Definition at line 70 of file lifecyclenode_client.cpp.
{
  changeState(lifecycle_msgs::msg::Transition::TRANSITION_UNCONFIGURED_SHUTDOWN);
}
References changeState().
Referenced by cl_lifecyclenode::CbShutdown::onEntry().
Member Data Documentation
client_change_state_
rclcpp::Client<lifecycle_msgs::srv::ChangeState>::SharedPtr cl_lifecyclenode::ClLifecycleNode::client_change_state_ private
Definition at line 439 of file lifecyclenode_client.hpp.
Referenced by changeState(), and onInitialize().
client_get_state_
rclcpp::Client<lifecycle_msgs::srv::GetState>::SharedPtr cl_lifecyclenode::ClLifecycleNode::client_get_state_ private
Definition at line 438 of file lifecyclenode_client.hpp.
Referenced by onInitialize().
lastTransitionEvent_
lifecycle_msgs::msg::TransitionEvent::SharedPtr cl_lifecyclenode::ClLifecycleNode::lastTransitionEvent_ private
Definition at line 449 of file lifecyclenode_client.hpp.
Referenced by onTransitionEvent().
node_change_state_topic
const std::string cl_lifecyclenode::ClLifecycleNode::node_change_state_topic = "/change_state" private
Definition at line 446 of file lifecyclenode_client.hpp.
Referenced by onInitialize().
node_get_state_topic
const std::string cl_lifecyclenode::ClLifecycleNode::node_get_state_topic = "/get_state" private
Definition at line 445 of file lifecyclenode_client.hpp.
Referenced by onInitialize().
node_transition_event_topic
const std::string cl_lifecyclenode::ClLifecycleNode::node_transition_event_topic = "/transition_event" private
Definition at line 447 of file lifecyclenode_client.hpp.
Referenced by onInitialize().
nodeName_
std::string cl_lifecyclenode::ClLifecycleNode::nodeName_ private
Definition at line 444 of file lifecyclenode_client.hpp.
Referenced by onInitialize().
onTransitionActivate_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionActivate_
Definition at line 231 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionActiveShutdown_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionActiveShutdown_
Definition at line 236 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionCleanup_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionCleanup_
Definition at line 230 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionConfigure_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionConfigure_
Definition at line 229 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionCreate_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionCreate_
Definition at line 228 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionDeactivate_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionDeactivate_
Definition at line 232 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionDestroy_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionDestroy_
Definition at line 238 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionEventSignal
boost::signals2::signal<void(const lifecycle_msgs::msg::TransitionEvent::SharedPtr)> cl_lifecyclenode::ClLifecycleNode::onTransitionEventSignal
Definition at line 226 of file lifecyclenode_client.hpp.
onTransitionInactiveShutdown_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionInactiveShutdown_
Definition at line 235 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionOnActivateError_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnActivateError_
Definition at line 246 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbActivate::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnActivateFailure_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnActivateFailure_
Definition at line 245 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbActivate::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnActivateSuccess_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnActivateSuccess_
Definition at line 244 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbActivate::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnActiveShutdownError_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnActiveShutdownError_
Definition at line 262 of file lifecyclenode_client.hpp.
onTransitionOnActiveShutdownFailure_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnActiveShutdownFailure_
Definition at line 261 of file lifecyclenode_client.hpp.
onTransitionOnActiveShutdownSuccess_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnActiveShutdownSuccess_
Definition at line 260 of file lifecyclenode_client.hpp.
onTransitionOnCleanupError_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnCleanupError_
Definition at line 254 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbCleanup::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnCleanupFailure_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnCleanupFailure_
Definition at line 253 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbCleanup::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnCleanupSuccess_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnCleanupSuccess_
Definition at line 252 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbCleanup::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnConfigureError_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnConfigureError_
Definition at line 242 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbConfigure::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnConfigureFailure_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnConfigureFailure_
Definition at line 241 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbConfigure::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnConfigureSuccess_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnConfigureSuccess_
Definition at line 240 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbConfigure::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnDeactivateError_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnDeactivateError_
Definition at line 250 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbDeactivate::onOrthogonalAllocation(), cl_lifecyclenode::CbDeactivateOnExit::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnDeactivateFailure_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnDeactivateFailure_
Definition at line 249 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbDeactivate::onOrthogonalAllocation(), cl_lifecyclenode::CbDeactivateOnExit::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnDeactivateSuccess_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnDeactivateSuccess_
Definition at line 248 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbDeactivate::onOrthogonalAllocation(), cl_lifecyclenode::CbDeactivateOnExit::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnErrorError_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnErrorError_
Definition at line 266 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionOnErrorFailure_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnErrorFailure_
Definition at line 265 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionOnErrorSuccess_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnErrorSuccess_
Definition at line 264 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
onTransitionOnShutdownError_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnShutdownError_
Definition at line 258 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbShutdown::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnShutdownFailure_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnShutdownFailure_
Definition at line 257 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbShutdown::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionOnShutdownSuccess_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionOnShutdownSuccess_
Definition at line 256 of file lifecyclenode_client.hpp.
Referenced by cl_lifecyclenode::CbShutdown::onOrthogonalAllocation(), and onOrthogonalAllocation().
onTransitionUnconfiguredShutdown_
boost::signals2::signal<void()> cl_lifecyclenode::ClLifecycleNode::onTransitionUnconfiguredShutdown_
Definition at line 234 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
postOnTransitionActivate_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionActivate_ private
Definition at line 454 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionActiveShutdown_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionActiveShutdown_ private
Definition at line 458 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionCleanup_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionCleanup_ private
Definition at line 453 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionConfigure_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionConfigure_ private
Definition at line 452 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionCreate_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionCreate_ private
Definition at line 451 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
postOnTransitionDeactivate_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionDeactivate_ private
Definition at line 455 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionDestroy_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionDestroy_ private
Definition at line 459 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionInactiveShutdown_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionInactiveShutdown_ private
Definition at line 457 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnActivateError_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnActivateError_ private
Definition at line 467 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnActivateFailure_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnActivateFailure_ private
Definition at line 466 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnActivateSuccess_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnActivateSuccess_ private
Definition at line 465 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnCleanupError_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnCleanupError_ private
Definition at line 475 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnCleanupFailure_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnCleanupFailure_ private
Definition at line 474 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
postOnTransitionOnCleanupSuccess_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnCleanupSuccess_ private
Definition at line 473 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnConfigureError_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnConfigureError_ private
Definition at line 463 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnConfigureFailure_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnConfigureFailure_ private
Definition at line 462 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnConfigureSuccess_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnConfigureSuccess_ private
Definition at line 461 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnDeactivateError_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnDeactivateError_ private
Definition at line 471 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnDeactivateFailure_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnDeactivateFailure_ private
Definition at line 470 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
postOnTransitionOnDeactivateSuccess_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnDeactivateSuccess_ private
Definition at line 469 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnErrorError_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnErrorError_ private
Definition at line 483 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
postOnTransitionOnErrorFailure_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnErrorFailure_ private
Definition at line 482 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnErrorSuccess_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnErrorSuccess_ private
Definition at line 481 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnShutdownError_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnShutdownError_ private
Definition at line 479 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionOnShutdownFailure_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnShutdownFailure_ private
Definition at line 478 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation().
postOnTransitionOnShutdownSuccess_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionOnShutdownSuccess_ private
Definition at line 477 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
postOnTransitionUnconfiguredShutdown_
std::function<void()> cl_lifecyclenode::ClLifecycleNode::postOnTransitionUnconfiguredShutdown_ private
Definition at line 456 of file lifecyclenode_client.hpp.
Referenced by onOrthogonalAllocation(), and onTransitionEvent().
subscription_transition_event_
rclcpp::Subscription<lifecycle_msgs::msg::TransitionEvent>::SharedPtr cl_lifecyclenode::ClLifecycleNode::subscription_transition_event_ private
Definition at line 442 of file lifecyclenode_client.hpp.
Referenced by onInitialize().
The documentation for this class was generated from the following files:
smacc2_client_library/lifecyclenode_client/include/lifecyclenode_client/lifecyclenode_client.hpp
smacc2_client_library/lifecyclenode_client/src/lifecyclenode_client/lifecyclenode_client.cpp