SMACC2: smacc2::client_behaviors::CbWaitNode Class Reference
smacc2::client_behaviors::CbWaitNode Class Reference
#include <cb_wait_node.hpp>
Public Member Functions
CbWaitNode (std::string nodeName)
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onExit ()
Protected Attributes
std::string nodeName_
rclcpp::Rate rate_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 33 of file cb_wait_node.hpp.
Constructor & Destructor Documentation
CbWaitNode()
smacc2::client_behaviors::CbWaitNode::CbWaitNode (std::string nodeName)
Definition at line 27 of file cb_wait_node.cpp.
: nodeName_(nodeName), rate_(5) {}
Member Function Documentation
onEntry()
void smacc2::client_behaviors::CbWaitNode::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 29 of file cb_wait_node.cpp.
{
  bool found = false;
  while (!this->isShutdownRequested() && !found)
  {
    std::stringstream ss;
    auto nodenames = getNode()->get_node_names();
    for (auto n : nodenames)
    {
      ss << " - " << n << std::endl;
      if (n == nodeName_) found = true;
    }
    auto totalstr = ss.str();
    RCLCPP_INFO_STREAM(
      getLogger(), "[" << getName() << "] on entry, listing nodes (" << nodenames.size() << ")"
                       << std::endl
                       << totalstr);
    rate_.sleep();
  }
  if (found)
  {
    this->postSuccessEvent();
  }
  else
  {
    this->postFailureEvent();
  }
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::getNode(), smacc2::SmaccAsyncClientBehavior::isShutdownRequested(), nodeName_, smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), and rate_.
Member Data Documentation
nodeName_
std::string smacc2::client_behaviors::CbWaitNode::nodeName_ protected
Definition at line 41 of file cb_wait_node.hpp.
Referenced by onEntry().
rate_
rclcpp::Rate smacc2::client_behaviors::CbWaitNode::rate_ protected
Definition at line 43 of file cb_wait_node.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/client_behaviors/cb_wait_node.hpp
smacc2/src/smacc2/client_behaviors/cb_wait_node.cpp