SMACC2: cl_move_group_interface::CbMoveEndEffector Class Reference
cl_move_group_interface::CbMoveEndEffector Class Reference
#include <cb_move_end_effector.hpp>
Public Member Functions
CbMoveEndEffector ()
CbMoveEndEffector (geometry_msgs::msg::PoseStamped target_pose, std::string tip_link="")
virtual void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Attributes
geometry_msgs::msg::PoseStamped targetPose
std::string tip_link_
std::optional< std::string > group_
Protected Member Functions
bool moveToAbsolutePose (moveit::planning_interface::MoveGroupInterface &moveGroupInterface, geometry_msgs::msg::PoseStamped &targetObjectPose)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Attributes
ClMoveGroup * movegroupClient_
Detailed Description
Definition at line 28 of file cb_move_end_effector.hpp.
Constructor & Destructor Documentation
CbMoveEndEffector() [1/2]
cl_move_group_interface::CbMoveEndEffector::CbMoveEndEffector ()
Definition at line 33 of file cb_move_end_effector.cpp.
{}
CbMoveEndEffector() [2/2]
cl_move_group_interface::CbMoveEndEffector::CbMoveEndEffector (geometry_msgs::msg::PoseStamped target_pose, std::string tip_link = "")
Definition at line 35 of file cb_move_end_effector.cpp.
: targetPose(target_pose)
{
  tip_link_ = tip_link;
}
References tip_link_.
Member Function Documentation
moveToAbsolutePose()
bool cl_move_group_interface::CbMoveEndEffector::moveToAbsolutePose (moveit::planning_interface::MoveGroupInterface & moveGroupInterface, geometry_msgs::msg::PoseStamped & targetObjectPose) protected
Definition at line 63 of file cb_move_end_effector.cpp.
{
  // auto & planningSceneInterface = movegroupClient_->planningSceneInterface;
  RCLCPP_DEBUG(getLogger(), "[CbMoveEndEffector] Synchronous sleep of 1 seconds");
  rclcpp::sleep_for(500ms);
  moveGroupInterface.setPlanningTime(1.0);
  RCLCPP_INFO_STREAM(
    getLogger(), "[CbMoveEndEffector] Target End efector Pose: " << targetObjectPose);
  moveGroupInterface.setPoseTarget(targetObjectPose, tip_link_);
  moveGroupInterface.setPoseReferenceFrame(targetObjectPose.header.frame_id);
  moveit::planning_interface::MoveGroupInterface::Plan computedMotionPlan;
  bool success =
    (moveGroupInterface.plan(computedMotionPlan) == moveit::core::MoveItErrorCode::SUCCESS);
  RCLCPP_INFO(
    getLogger(), "[CbMoveEndEffector] Success Visualizing plan 1 (pose goal) %s",
    success ? "" : "FAILED");
  if (success)
  {
    auto executionResult = moveGroupInterface.execute(computedMotionPlan);
    if (executionResult == moveit_msgs::msg::MoveItErrorCodes::SUCCESS)
    {
      RCLCPP_INFO(getLogger(), "[CbMoveEndEffector] motion execution succeeded");
      movegroupClient_->postEventMotionExecutionSucceded();
      this->postSuccessEvent();
    }
    else
    {
      RCLCPP_INFO(getLogger(), "[CbMoveEndEffector] motion execution failed");
      movegroupClient_->postEventMotionExecutionFailed();
      this->postFailureEvent();
    }
  }
  else
  {
    RCLCPP_INFO(getLogger(), "[CbMoveEndEffector] motion execution failed");
    movegroupClient_->postEventMotionExecutionFailed();
    this->postFailureEvent();
  }
  RCLCPP_DEBUG(getLogger(), "[CbMoveEndEffector] Synchronous sleep of 1 seconds");
  rclcpp::sleep_for(500ms);
  return success;
}
References smacc2::ISmaccClientBehavior::getLogger(), movegroupClient_, cl_move_group_interface::ClMoveGroup::postEventMotionExecutionFailed(), cl_move_group_interface::ClMoveGroup::postEventMotionExecutionSucceded(), smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), and tip_link_.
Referenced by onEntry().
onEntry()
void cl_move_group_interface::CbMoveEndEffector::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 42 of file cb_move_end_effector.cpp.
{
  this->requiresClient(movegroupClient_);
  if (this->group_)
  {
    RCLCPP_DEBUG(
      getLogger(), "[CbMoveEndEfector] new thread started to move absolute end effector");
    moveit::planning_interface::MoveGroupInterface move_group(getNode(), *group_);
    this->moveToAbsolutePose(move_group, targetPose);
    RCLCPP_DEBUG(getLogger(), "[CbMoveEndEfector] to move absolute end effector thread destroyed");
  }
  else
  {
    RCLCPP_DEBUG(
      getLogger(), "[CbMoveEndEfector] new thread started to move absolute end effector");
    this->moveToAbsolutePose(*(movegroupClient_->moveGroupClientInterface), targetPose);
    RCLCPP_DEBUG(getLogger(), "[CbMoveEndEfector] to move absolute end effector thread destroyed");
  }
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), group_, movegroupClient_, cl_move_group_interface::ClMoveGroup::moveGroupClientInterface, moveToAbsolutePose(), smacc2::ISmaccClientBehavior::requiresClient(), and targetPose.
Member Data Documentation
group_
std::optional<std::string> cl_move_group_interface::CbMoveEndEffector::group_
Definition at line 33 of file cb_move_end_effector.hpp.
Referenced by onEntry().
movegroupClient_
ClMoveGroup* cl_move_group_interface::CbMoveEndEffector::movegroupClient_ protected
Definition at line 45 of file cb_move_end_effector.hpp.
Referenced by moveToAbsolutePose(), and onEntry().
targetPose
geometry_msgs::msg::PoseStamped cl_move_group_interface::CbMoveEndEffector::targetPose
Definition at line 31 of file cb_move_end_effector.hpp.
Referenced by onEntry().
tip_link_
std::string cl_move_group_interface::CbMoveEndEffector::tip_link_
Definition at line 32 of file cb_move_end_effector.hpp.
Referenced by CbMoveEndEffector(), and moveToAbsolutePose().
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_move_end_effector.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_move_end_effector.cpp