SMACC2: sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition Class Reference
sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition Class Reference
#include <cb_navigate_global_position.hpp>
Public Member Functions
CbNavigateGlobalPosition (const geometry_msgs::msg::PoseStamped &goalPose)
virtual void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Attributes
geometry_msgs::msg::PoseStamped goalPose_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 31 of file cb_navigate_global_position.hpp.
Constructor & Destructor Documentation
CbNavigateGlobalPosition()
sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition::CbNavigateGlobalPosition (const geometry_msgs::msg::PoseStamped & goalPose)
Definition at line 31 of file cb_navigate_global_position.cpp.
: goalPose_(goalPose)
{
}
Member Function Documentation
onEntry()
void sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 45 of file cb_navigate_global_position.cpp.
{
  RCLCPP_INFO(getLogger(), "On Entry!");
  sm_autoware_avp::clients::ClAutoware * autowareClient_;
  this->requiresClient(autowareClient_);
  this->goalPose_.header.stamp = getNode()->now();
  autowareClient_->publishGoalPose(this->goalPose_);
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), goalPose_, sm_autoware_avp::clients::ClAutoware::publishGoalPose(), and smacc2::ISmaccClientBehavior::requiresClient().
onExit()
void sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 57 of file cb_navigate_global_position.cpp.
{}
Member Data Documentation
goalPose_
geometry_msgs::msg::PoseStamped sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition::goalPose_ private
Definition at line 41 of file cb_navigate_global_position.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_sm_reference_library/sm_autoware_avp/include/sm_autoware_avp/clients/autoware_client/client_behaviors/cb_navigate_global_position.hpp
smacc2_sm_reference_library/sm_autoware_avp/src/sm_autoware_avp/clients/autoware_client/client_behaviors/cb_navigate_global_position.cpp