SMACC2: smacc2::client_behaviors::CbServiceCall< ServiceType > Class Template Reference
smacc2::client_behaviors::CbServiceCall< ServiceType > Class Template Reference
#include <cb_call_service.hpp>
Public Member Functions
CbServiceCall (const char *serviceName)
CbServiceCall (const char *serviceName, std::shared_ptr< typename ServiceType::Request > request, std::chrono::milliseconds pollRate=100ms)
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onExit ()
Public Attributes
std::shared_future< std::shared_ptr< typename ServiceType::Response > > resultFuture_
std::shared_ptr< typename ServiceType::Response > result_
std::chrono::milliseconds pollRate_
Protected Member Functions
virtual void onServiceResponse (std::shared_ptr< typename ServiceType::Response >)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Attributes
std::shared_ptr< rclcpp::Client< ServiceType > > client_
std::string serviceName_
std::shared_ptr< typename ServiceType::Request > request_
Detailed Description
template<typename ServiceType>
class smacc2::client_behaviors::CbServiceCall< ServiceType >
Definition at line 30 of file cb_call_service.hpp.
Constructor & Destructor Documentation
CbServiceCall() [1/2]
template<typename ServiceType > smacc2::client_behaviors::CbServiceCall< ServiceType >::CbServiceCall (const char * serviceName) inline
Definition at line 33 of file cb_call_service.hpp.
                                          : serviceName_(serviceName)
  {
    request_ = std::make_shared<typename ServiceType::Request>();
    pollRate_ = 100ms;
  }
References smacc2::client_behaviors::CbServiceCall< ServiceType >::pollRate_, and smacc2::client_behaviors::CbServiceCall< ServiceType >::request_.
CbServiceCall() [2/2]
template<typename ServiceType > smacc2::client_behaviors::CbServiceCall< ServiceType >::CbServiceCall (const char * serviceName, std::shared_ptr< typename ServiceType::Request > request, std::chrono::milliseconds pollRate = 100ms) inline
Definition at line 39 of file cb_call_service.hpp.
  : serviceName_(serviceName), request_(request), result_(nullptr), pollRate_(pollRate)
  {
  }
Member Function Documentation
onEntry()
template<typename ServiceType > void smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 46 of file cb_call_service.hpp.
  {
    RCLCPP_INFO_STREAM(
      getLogger(), "[" << this->getName() << "] creating ros service client: " << serviceName_);
    client_ = getNode()->create_client<ServiceType>(serviceName_);
    RCLCPP_INFO_STREAM(
      getLogger(), "[" << this->getName() << "] making service request to " << serviceName_);
    resultFuture_ = client_->async_send_request(request_).future.share();
    std::future_status status = resultFuture_.wait_for(0s);
    RCLCPP_INFO_STREAM(
      getLogger(), "thread state: " << (int)status << " ok " << rclcpp::ok() << " shutdown "
                                    << this->isShutdownRequested() << "");
    while (status != std::future_status::ready && rclcpp::ok() && !this->isShutdownRequested())
    {
      RCLCPP_INFO_STREAM_THROTTLE(
        getLogger(), *getNode()->get_clock(), 1000,
        "[" << this->getName() << "] waiting response ");
      rclcpp::sleep_for(pollRate_);
      status = resultFuture_.wait_for(0s);
    }
    if (status == std::future_status::ready)
    {
      RCLCPP_INFO_STREAM(getLogger(), "[" << this->getName() << "] response received ");
      result_ = resultFuture_.get();
      onServiceResponse(result_);
      this->postSuccessEvent();
    }
    else
    {
      RCLCPP_INFO_STREAM(getLogger(), "[" << this->getName() << "] response not received ");
      this->postFailureEvent();
    }
  }
References smacc2::client_behaviors::CbServiceCall< ServiceType >::client_, smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::getNode(), smacc2::SmaccAsyncClientBehavior::isShutdownRequested(), smacc2::client_behaviors::CbServiceCall< ServiceType >::onServiceResponse(), smacc2::client_behaviors::CbServiceCall< ServiceType >::pollRate_, smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), smacc2::client_behaviors::CbServiceCall< ServiceType >::request_, smacc2::client_behaviors::CbServiceCall< ServiceType >::result_, smacc2::client_behaviors::CbServiceCall< ServiceType >::resultFuture_, and smacc2::client_behaviors::CbServiceCall< ServiceType >::serviceName_.
Referenced by cl_nav2z::CbPauseSlam::onEntry(), and cl_nav2z::CbResumeSlam::onEntry().
onServiceResponse()
template<typename ServiceType > virtual void smacc2::client_behaviors::CbServiceCall< ServiceType >::onServiceResponse (std::shared_ptr< typename ServiceType::Response >) inline protected virtual
Definition at line 98 of file cb_call_service.hpp.
  {
    RCLCPP_INFO_STREAM(getLogger(), "[" << this->getName() << "] response received ");
  }
References smacc2::ISmaccClientBehavior::getLogger(), and smacc2::ISmaccClientBehavior::getName().
Referenced by smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry().
Member Data Documentation
client_
template<typename ServiceType > std::shared_ptr<rclcpp::Client<ServiceType> > smacc2::client_behaviors::CbServiceCall< ServiceType >::client_ protected
Definition at line 94 of file cb_call_service.hpp.
Referenced by smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry().
pollRate_
template<typename ServiceType > std::chrono::milliseconds smacc2::client_behaviors::CbServiceCall< ServiceType >::pollRate_
Definition at line 90 of file cb_call_service.hpp.
Referenced by smacc2::client_behaviors::CbServiceCall< ServiceType >::CbServiceCall(), and smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry().
request_
template<typename ServiceType > std::shared_ptr<typename ServiceType::Request> smacc2::client_behaviors::CbServiceCall< ServiceType >::request_ protected
Definition at line 96 of file cb_call_service.hpp.
Referenced by smacc2::client_behaviors::CbServiceCall< ServiceType >::CbServiceCall(), and smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry().
result_
template<typename ServiceType > std::shared_ptr<typename ServiceType::Response> smacc2::client_behaviors::CbServiceCall< ServiceType >::result_
Definition at line 89 of file cb_call_service.hpp.
Referenced by smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry().
resultFuture_
template<typename ServiceType > std::shared_future<std::shared_ptr<typename ServiceType::Response> > smacc2::client_behaviors::CbServiceCall< ServiceType >::resultFuture_
Definition at line 87 of file cb_call_service.hpp.
Referenced by smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry().
serviceName_
template<typename ServiceType > std::string smacc2::client_behaviors::CbServiceCall< ServiceType >::serviceName_ protected
Definition at line 95 of file cb_call_service.hpp.
Referenced by smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry().
The documentation for this class was generated from the following file:
smacc2/include/smacc2/client_behaviors/cb_call_service.hpp