SMACC2: cl_http::http_session Class Reference
cl_http::http_session Class Reference
#include <http_session.hpp>
Public Member Functions
http_session (boost::asio::any_io_executor ioc, const std::function< void(const TResponse &)> response)
virtual ~http_session ()
void run (const std::string &host, const std::string &target, const boost::beast::http::verb http_method, const int &version) override
std::string getPort () override
Public Member Functions inherited from cl_http::http_session_base
virtual ~http_session_base ()
Private Member Functions
void on_resolve (boost::beast::error_code ec, boost::asio::ip::tcp::resolver::results_type results) override
void fail (boost::beast::error_code ec, const char *what) override
void on_connect (boost::beast::error_code ec, boost::asio::ip::tcp::resolver::results_type::endpoint_type) override
void on_write (boost::beast::error_code ec, std::size_t bytes_transferred) override
void on_read (boost::beast::error_code ec, std::size_t bytes_transferred) override
void setBody (const std::string &body) override
void setHeaders (const std::unordered_map< std::string, std::string > &headers) override
Private Attributes
const std::string kPort = "80"
std::function< void(const TResponse &)> onResponse
boost::asio::ip::tcp::resolver resolver_
boost::beast::tcp_stream stream_
boost::beast::flat_buffer buffer_
boost::beast::http::request< boost::beast::http::string_body > req_
TResponse res_
Additional Inherited Members
Public Types inherited from cl_http::http_session_base
using TResponse = boost::beast::http::response< boost::beast::http::string_body >
Protected Member Functions inherited from cl_http::http_session_base
virtual void on_handshake (boost::beast::error_code ec)
virtual void on_shutdown (boost::beast::error_code ec)
Detailed Description
Definition at line 35 of file http_session.hpp.
Constructor & Destructor Documentation
http_session()
cl_http::http_session::http_session (boost::asio::any_io_executor ioc, const std::function< void(const TResponse &)> response)
Definition at line 27 of file http_session.cpp.
: onResponse{response}, resolver_{ioc}, stream_{ioc}
{
}
~http_session()
virtual cl_http::http_session::~http_session () inline virtual
Definition at line 43 of file http_session.hpp.
{}
Member Function Documentation
fail()
void cl_http::http_session::fail (boost::beast::error_code ec, const char * what) override private virtual
Implements cl_http::http_session_base.
Definition at line 65 of file http_session.cpp.
{
  std::cout << "Failure!..." << std::endl;
  std::cerr << what << ": " << ec.message() << "\n";
  res_.result(boost::beast::http::status::bad_request);
  res_.reason() = ec.message();
  onResponse(res_);
}
References onResponse, and res_.
Referenced by on_connect(), on_read(), on_resolve(), and on_write().
getPort()
std::string cl_http::http_session::getPort () inline override virtual
Implements cl_http::http_session_base.
Definition at line 50 of file http_session.hpp.
{ return kPort; }
References kPort.
on_connect()
void cl_http::http_session::on_connect (boost::beast::error_code ec, boost::asio::ip::tcp::resolver::results_type::endpoint_type) override private virtual
Implements cl_http::http_session_base.
Definition at line 74 of file http_session.cpp.
{
  if (ec) return fail(ec, "connect");
  // Set a timeout on the operation
  stream_.expires_after(std::chrono::seconds(1));
  // Send the HTTP request to the remote host
  boost::beast::http::async_write(
    stream_, req_, boost::beast::bind_front_handler(&http_session::on_write, shared_from_this()));
}
References fail(), on_write(), req_, and stream_.
Referenced by on_resolve().
on_read()
void cl_http::http_session::on_read (boost::beast::error_code ec, std::size_t bytes_transferred) override private virtual
Implements cl_http::http_session_base.
Definition at line 99 of file http_session.cpp.
{
  boost::ignore_unused(bytes_transferred);
  if (ec) return fail(ec, "read");
  // Gracefully close the socket
  stream_.socket().shutdown(boost::asio::ip::tcp::socket::shutdown_both, ec);
  // not_connected happens sometimes so don't bother reporting it.
  if (ec && ec != boost::beast::errc::not_connected) return fail(ec, "shutdown");
  // If we get here then the connection is closed gracefully
  onResponse(res_);
}
References fail(), onResponse, res_, and stream_.
Referenced by on_write().
on_resolve()
void cl_http::http_session::on_resolve (boost::beast::error_code ec, boost::asio::ip::tcp::resolver::results_type results) override private virtual
Implements cl_http::http_session_base.
Definition at line 52 of file http_session.cpp.
{
  if (ec) return fail(ec, "resolve");
  // Set a timeout on the operation
  stream_.expires_after(std::chrono::seconds(1));
  // Make the connection on the IP address we get from a lookup
  stream_.async_connect(
    results, boost::beast::bind_front_handler(&http_session::on_connect, shared_from_this()));
}
References fail(), on_connect(), and stream_.
Referenced by run().
on_write()
void cl_http::http_session::on_write (boost::beast::error_code ec, std::size_t bytes_transferred) override private virtual
Implements cl_http::http_session_base.
Definition at line 87 of file http_session.cpp.
{
  boost::ignore_unused(bytes_transferred);
  if (ec) return fail(ec, "write");
  // Receive the HTTP response
  boost::beast::http::async_read(
    stream_, buffer_, res_,
    boost::beast::bind_front_handler(&http_session::on_read, shared_from_this()));
}
References buffer_, fail(), on_read(), res_, and stream_.
Referenced by on_connect().
run()
void cl_http::http_session::run (const std::string & host, const std::string & target, const boost::beast::http::verb http_method, const int & version) override virtual
Implements cl_http::http_session_base.
Definition at line 35 of file http_session.cpp.
{
  // Set up an HTTP request
  req_.version(version);
  req_.method(http_method);
  req_.target(target);
  req_.set(boost::beast::http::field::host, host);
  req_.set(boost::beast::http::field::user_agent, BOOST_BEAST_VERSION_STRING);
  // Look up the domain name
  resolver_.async_resolve(
    host.c_str(), kPort.c_str(),
    boost::beast::bind_front_handler(&http_session::on_resolve, shared_from_this()));
}
References kPort, on_resolve(), req_, and resolver_.
setBody()
void cl_http::http_session::setBody (const std::string & body) override private virtual
Implements cl_http::http_session_base.
Definition at line 33 of file http_session.cpp.
{ req_.body() = body; }
References req_.
setHeaders()
void cl_http::http_session::setHeaders (const std::unordered_map< std::string, std::string > & headers) inline override private virtual
Implements cl_http::http_session_base.
Definition at line 64 of file http_session.hpp.
{}
Member Data Documentation
buffer_
boost::beast::flat_buffer cl_http::http_session::buffer_ private
Definition at line 70 of file http_session.hpp.
Referenced by on_write().
kPort
const std::string cl_http::http_session::kPort = "80" private
Definition at line 53 of file http_session.hpp.
Referenced by getPort(), and run().
onResponse
std::function<void(const TResponse &)> cl_http::http_session::onResponse private
Definition at line 66 of file http_session.hpp.
Referenced by fail(), and on_read().
req_
boost::beast::http::request<boost::beast::http::string_body> cl_http::http_session::req_ private
Definition at line 71 of file http_session.hpp.
Referenced by on_connect(), run(), and setBody().
res_
TResponse cl_http::http_session::res_ private
Definition at line 72 of file http_session.hpp.
Referenced by fail(), on_read(), and on_write().
resolver_
boost::asio::ip::tcp::resolver cl_http::http_session::resolver_ private
Definition at line 68 of file http_session.hpp.
Referenced by run().
stream_
boost::beast::tcp_stream cl_http::http_session::stream_ private
Definition at line 69 of file http_session.hpp.
Referenced by on_connect(), on_read(), on_resolve(), and on_write().
The documentation for this class was generated from the following files:
smacc2_client_library/http_client/include/http_client/http_session.hpp
smacc2_client_library/http_client/src/http_client/http_session.cpp