SMACC2: cl_nav2z::PlannerSwitcher Class Reference
cl_nav2z::PlannerSwitcher Class Reference
#include <planner_switcher.hpp>
Public Member Functions
PlannerSwitcher ()
void onInitialize () override
void setDesiredGlobalPlanner (std::string)
void setDesiredController (std::string)
void commitPublish ()
void setBackwardPlanner (bool commit=true)
void setUndoPathBackwardPlanner (bool commit=true)
void setForwardPlanner (bool commit=true)
void setPureSpinningPlanner (bool commit=true)
void setDefaultPlanners (bool commit=true)
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Private Attributes
std::string desired_planner_
std::string desired_controller_
bool set_planners_mode_flag_
rclcpp::Publisher< std_msgs::msg::String >::SharedPtr planner_selector_pub_
rclcpp::Publisher< std_msgs::msg::String >::SharedPtr controller_selector_pub_
rclcpp::Publisher< std_msgs::msg::String >::SharedPtr goal_checker_selector_pub_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 31 of file planner_switcher.hpp.
Constructor & Destructor Documentation
PlannerSwitcher()
cl_nav2z::PlannerSwitcher::PlannerSwitcher ()
Definition at line 27 of file planner_switcher.cpp.
{}
Member Function Documentation
commitPublish()
void cl_nav2z::PlannerSwitcher::commitPublish ()
Definition at line 98 of file planner_switcher.cpp.
{
  std_msgs::msg::String planner_msg;
  planner_msg.data = desired_planner_;
  this->planner_selector_pub_->publish(planner_msg);
  std_msgs::msg::String controller_msg;
  controller_msg.data = desired_controller_;
  this->controller_selector_pub_->publish(controller_msg);
}
References controller_selector_pub_, desired_controller_, desired_planner_, and planner_selector_pub_.
Referenced by setBackwardPlanner(), setDefaultPlanners(), setForwardPlanner(), setPureSpinningPlanner(), and setUndoPathBackwardPlanner().
onInitialize()
void cl_nav2z::PlannerSwitcher::onInitialize () override virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 29 of file planner_switcher.cpp.
{
  rclcpp::QoS qos(rclcpp::KeepLast(1));
  qos.transient_local().reliable();
  this->planner_selector_pub_ =
    getNode()->create_publisher<std_msgs::msg::String>("planner_selector", qos);
  this->controller_selector_pub_ =
    getNode()->create_publisher<std_msgs::msg::String>("controller_selector", qos);
}
References controller_selector_pub_, smacc2::ISmaccComponent::getNode(), and planner_selector_pub_.
setBackwardPlanner()
void cl_nav2z::PlannerSwitcher::setBackwardPlanner (bool commit = true)
Definition at line 60 of file planner_switcher.cpp.
{
  RCLCPP_INFO(getLogger(), "[PlannerSwitcher] Planner Switcher: Trying to set BackwardPlanner");
  desired_planner_ = "BackwardGlobalPlanner";
  desired_controller_ = "BackwardLocalPlanner";
  if (commit) commitPublish();
}
References commitPublish(), desired_controller_, desired_planner_, and smacc2::ISmaccComponent::getLogger().
Referenced by cl_nav2z::CbNavigateBackwards::onEntry().
setDefaultPlanners()
void cl_nav2z::PlannerSwitcher::setDefaultPlanners (bool commit = true)
Definition at line 90 of file planner_switcher.cpp.
{
  desired_planner_ = "GridBased";
  desired_controller_ = "FollowPath";
  if (commit) commitPublish();
}
References commitPublish(), desired_controller_, and desired_planner_.
Referenced by cl_nav2z::WaypointNavigator::sendNextGoal().
setDesiredController()
void cl_nav2z::PlannerSwitcher::setDesiredController (std::string controllerName)
Definition at line 45 of file planner_switcher.cpp.
{
  desired_controller_ = controllerName;
}
References desired_controller_.
setDesiredGlobalPlanner()
void cl_nav2z::PlannerSwitcher::setDesiredGlobalPlanner (std::string plannerName)
Definition at line 40 of file planner_switcher.cpp.
{
  desired_planner_ = plannerName;
}
References desired_planner_.
setForwardPlanner()
void cl_nav2z::PlannerSwitcher::setForwardPlanner (bool commit = true)
Definition at line 70 of file planner_switcher.cpp.
{
  RCLCPP_INFO(getLogger(), "[PlannerSwitcher] Planner Switcher: Trying to set ForwardPlanner");
  desired_planner_ = "ForwardGlobalPlanner";
  desired_controller_ = "ForwardLocalPlanner";
  if (commit) commitPublish();
}
References commitPublish(), desired_controller_, desired_planner_, and smacc2::ISmaccComponent::getLogger().
Referenced by cl_nav2z::CbNavigateForward::onEntry().
setPureSpinningPlanner()
void cl_nav2z::PlannerSwitcher::setPureSpinningPlanner (bool commit = true)
Definition at line 80 of file planner_switcher.cpp.
{
  RCLCPP_INFO(getLogger(), "[PlannerSwitcher] Planner Switcher: Trying to set PureSpinningPlanner");
  desired_planner_ = "ForwardGlobalPlanner";
  desired_controller_ = "PureSpinningLocalPlanner";
  if (commit) commitPublish();
}
References commitPublish(), desired_controller_, desired_planner_, and smacc2::ISmaccComponent::getLogger().
Referenced by cl_nav2z::CbAbsoluteRotate::onEntry(), and cl_nav2z::CbRotate::onEntry().
setUndoPathBackwardPlanner()
void cl_nav2z::PlannerSwitcher::setUndoPathBackwardPlanner (bool commit = true)
Definition at line 50 of file planner_switcher.cpp.
{
  RCLCPP_INFO(getLogger(), "[PlannerSwitcher] Planner Switcher: Trying to set BackwardPlanner");
  desired_planner_ = "UndoPathGlobalPlanner";
  desired_controller_ = "BackwardLocalPlanner";
  if (commit) commitPublish();
}
References commitPublish(), desired_controller_, desired_planner_, and smacc2::ISmaccComponent::getLogger().
Member Data Documentation
controller_selector_pub_
rclcpp::Publisher<std_msgs::msg::String>::SharedPtr cl_nav2z::PlannerSwitcher::controller_selector_pub_ private
Definition at line 66 of file planner_switcher.hpp.
Referenced by commitPublish(), and onInitialize().
desired_controller_
std::string cl_nav2z::PlannerSwitcher::desired_controller_ private
Definition at line 60 of file planner_switcher.hpp.
Referenced by commitPublish(), setBackwardPlanner(), setDefaultPlanners(), setDesiredController(), setForwardPlanner(), setPureSpinningPlanner(), and setUndoPathBackwardPlanner().
desired_planner_
std::string cl_nav2z::PlannerSwitcher::desired_planner_ private
Definition at line 58 of file planner_switcher.hpp.
Referenced by commitPublish(), setBackwardPlanner(), setDefaultPlanners(), setDesiredGlobalPlanner(), setForwardPlanner(), setPureSpinningPlanner(), and setUndoPathBackwardPlanner().
goal_checker_selector_pub_
rclcpp::Publisher<std_msgs::msg::String>::SharedPtr cl_nav2z::PlannerSwitcher::goal_checker_selector_pub_ private
Definition at line 68 of file planner_switcher.hpp.
planner_selector_pub_
rclcpp::Publisher<std_msgs::msg::String>::SharedPtr cl_nav2z::PlannerSwitcher::planner_selector_pub_ private
Definition at line 64 of file planner_switcher.hpp.
Referenced by commitPublish(), and onInitialize().
set_planners_mode_flag_
bool cl_nav2z::PlannerSwitcher::set_planners_mode_flag_ private
Definition at line 62 of file planner_switcher.hpp.
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/components/planner_switcher/planner_switcher.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/components/planner_switcher/planner_switcher.cpp