SMACC2: smacc2::StateReactor Class Reference
smacc2::StateReactor Class Reference abstract
#include <smacc_state_reactor.hpp>
Public Member Functions
StateReactor ()
virtual ~StateReactor ()
virtual void onInitialized ()
virtual void onEntry ()
virtual void onExit ()
virtual void onEventNotified (const std::type_info *eventType)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename T , typename TClass >
void createEventCallback (void(TClass::*callback)(T *), TClass *object)
template<typename T >
void createEventCallback (std::function< void(T *)> callback)
void update ()
virtual bool triggers ()=0
template<typename TEv >
void addInputEvent ()
template<typename TEv >
void setOutputEvent ()
void initialize (ISmaccState *ownerState)
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
Public Attributes
ISmaccState * ownerState
std::function< void()> postEventFn
std::vector< const std::type_info * > eventTypes
std::map< const std::type_info *, std::function< void(void *)> > eventCallbacks_
Private Member Functions
template<typename TEvent >
void notifyEvent (TEvent *ev)
Private Attributes
friend ISmaccStateMachine
Detailed Description
Definition at line 43 of file smacc_state_reactor.hpp.
Constructor & Destructor Documentation
StateReactor()
smacc2::StateReactor::StateReactor ()
Definition at line 29 of file state_reactor.cpp.
{}
~StateReactor()
smacc2::StateReactor::~StateReactor () virtual
Definition at line 31 of file state_reactor.cpp.
{}
Member Function Documentation
addInputEvent()
template<typename TEv > void smacc2::StateReactor::addInputEvent ()
Definition at line 52 of file smacc_state_reactor_impl.hpp.
{
  this->eventTypes.push_back(&typeid(TEv));
}
References eventTypes.
Referenced by smacc2::AddTEventTypeStateReactor< TEventList >::operator()().
createEventCallback() [1/2]
template<typename T > void smacc2::StateReactor::createEventCallback (std::function< void(T *)> callback)
Definition at line 69 of file smacc_state_reactor_impl.hpp.
{
  const auto * eventtype = &typeid(T);
  this->eventCallbacks_[eventtype] = [=](void * msg)
  {
    T * evptr = (T *)msg;
    callback(evptr);
  };
}
References eventCallbacks_.
createEventCallback() [2/2]
template<typename T , typename TClass > void smacc2::StateReactor::createEventCallback (void(TClass::* callback)(T *), TClass * object)
Definition at line 58 of file smacc_state_reactor_impl.hpp.
{
  const auto * eventtype = &typeid(T);
  this->eventCallbacks_[eventtype] = [=](void * msg)
  {
    T * evptr = (T *)msg;
    (object->*callback)(evptr);
  };
}
References eventCallbacks_.
Referenced by smacc2::state_reactors::SrConditional< TEv >::SrConditional().
getLogger()
rclcpp::Logger smacc2::StateReactor::getLogger ()
Definition at line 58 of file state_reactor.cpp.
{ return ownerState->getLogger(); }
References smacc2::ISmaccState::getLogger(), and ownerState.
Referenced by smacc2::state_reactors::SrAllEventsGo::onEventNotified(), smacc2::state_reactors::SrEventCountdown::onEventNotified(), setOutputEvent(), smacc2::state_reactors::SrAllEventsGo::triggers(), smacc2::state_reactors::SrEventCountdown::triggers(), and update().
getNode()
rclcpp::Node::SharedPtr & smacc2::StateReactor::getNode ()
Definition at line 56 of file state_reactor.cpp.
{ return ownerState->getNode(); }
References smacc2::ISmaccState::getNode(), and ownerState.
initialize()
void smacc2::StateReactor::initialize (smacc2::ISmaccState * ownerState)
Definition at line 33 of file state_reactor.cpp.
{
  this->ownerState = ownerState;
  this->onInitialized();
}
References onInitialized(), and ownerState.
notifyEvent()
template<typename TEvent > void smacc2::StateReactor::notifyEvent (TEvent * ev) inline private
Definition at line 97 of file smacc_state_reactor.hpp.
  {
    //the state machine uses this method to notify this state reactor some event happened.
    auto tid = &(typeid(TEvent));
    if (std::find(eventTypes.begin(), eventTypes.end(), tid) != eventTypes.end())
    {
      this->onEventNotified(tid);
      this->update();
      if (eventCallbacks_.count(tid))
      {
        eventCallbacks_[tid]((void *)ev);
      }
    }
  }
References eventCallbacks_, eventTypes, onEventNotified(), and update().
onEntry()
void smacc2::StateReactor::onEntry () virtual
Definition at line 43 of file state_reactor.cpp.
{}
onEventNotified()
void smacc2::StateReactor::onEventNotified (const std::type_info * eventType) virtual
Reimplemented in smacc2::state_reactors::SrAllEventsGo, and smacc2::state_reactors::SrEventCountdown.
Definition at line 41 of file state_reactor.cpp.
{}
Referenced by notifyEvent().
onExit()
void smacc2::StateReactor::onExit () virtual
Definition at line 45 of file state_reactor.cpp.
{}
onInitialized()
void smacc2::StateReactor::onInitialized () virtual
Reimplemented in smacc2::state_reactors::SrAllEventsGo, and smacc2::state_reactors::SrEventCountdown.
Definition at line 39 of file state_reactor.cpp.
{}
Referenced by initialize().
postEvent() [1/2]
template<typename EventType > void smacc2::StateReactor::postEvent ()
Definition at line 34 of file smacc_state_reactor_impl.hpp.
{
  ownerState->postEvent<EventType>();
}
References ownerState, and smacc2::ISmaccState::postEvent().
postEvent() [2/2]
template<typename EventType > void smacc2::StateReactor::postEvent (const EventType & ev)
Definition at line 28 of file smacc_state_reactor_impl.hpp.
{
  ownerState->postEvent(ev);
}
References ownerState, and smacc2::ISmaccState::postEvent().
setOutputEvent()
template<typename TEv > void smacc2::StateReactor::setOutputEvent ()
Definition at line 40 of file smacc_state_reactor_impl.hpp.
{
  this->postEventFn = [this]()
  {
    RCLCPP_INFO_STREAM(
      this->getLogger(), "[State Reactor Base] postingfn posting event: " << demangleSymbol<TEv>());
    auto * ev = new TEv();
    this->ownerState->getStateMachine().postEvent(ev);
  };
}
References smacc2::introspection::demangleSymbol(), getLogger(), smacc2::ISmaccState::getStateMachine(), ownerState, smacc2::ISmaccStateMachine::postEvent(), and postEventFn.
triggers()
virtual bool smacc2::StateReactor::triggers () pure virtual
Implemented in smacc2::state_reactors::SrAllEventsGo, smacc2::state_reactors::SrConditional< TEv >, and smacc2::state_reactors::SrEventCountdown.
Referenced by update().
update()
void smacc2::StateReactor::update ()
Definition at line 47 of file state_reactor.cpp.
{
  if (this->triggers())
  {
    RCLCPP_INFO(getLogger(), "State reactor base REALLY TRIGGERS!!");
    this->postEventFn();
  }
}
References getLogger(), postEventFn, and triggers().
Referenced by notifyEvent().
Member Data Documentation
eventCallbacks_
std::map<const std::type_info *, std::function<void(void *)> > smacc2::StateReactor::eventCallbacks_
Definition at line 49 of file smacc_state_reactor.hpp.
Referenced by createEventCallback(), createEventCallback(), and notifyEvent().
eventTypes
std::vector<const std::type_info *> smacc2::StateReactor::eventTypes
Definition at line 48 of file smacc_state_reactor.hpp.
Referenced by addInputEvent(), notifyEvent(), smacc2::state_reactors::SrAllEventsGo::onInitialized(), and smacc2::state_reactors::SrEventCountdown::onInitialized().
ISmaccStateMachine
friend smacc2::StateReactor::ISmaccStateMachine private
Definition at line 94 of file smacc_state_reactor.hpp.
ownerState
ISmaccState* smacc2::StateReactor::ownerState
Definition at line 46 of file smacc_state_reactor.hpp.
Referenced by getLogger(), getNode(), initialize(), postEvent(), postEvent(), and setOutputEvent().
postEventFn
std::function<void()> smacc2::StateReactor::postEventFn
Definition at line 47 of file smacc_state_reactor.hpp.
Referenced by setOutputEvent(), and update().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/smacc_state_reactor.hpp
smacc2/include/smacc2/impl/smacc_state_reactor_impl.hpp
smacc2/src/smacc2/state_reactor.cpp