SMACC2: smacc2::SmaccEventGenerator Class Reference
smacc2::SmaccEventGenerator Class Reference
#include <smacc_event_generator.hpp>
Public Member Functions
SmaccEventGenerator ()
virtual ~SmaccEventGenerator ()
template<typename TState , typename TSource >
void onStateAllocation ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
void initialize (ISmaccState *ownerState)
virtual void onInitialized ()
Private Attributes
ISmaccState * ownerState_
friend ISmaccStateMachine
Detailed Description
Definition at line 36 of file smacc_event_generator.hpp.
Constructor & Destructor Documentation
SmaccEventGenerator()
smacc2::SmaccEventGenerator::SmaccEventGenerator ()
Definition at line 25 of file smacc_event_generator.cpp.
{}
~SmaccEventGenerator()
smacc2::SmaccEventGenerator::~SmaccEventGenerator () virtual
Definition at line 27 of file smacc_event_generator.cpp.
{}
Member Function Documentation
initialize()
void smacc2::SmaccEventGenerator::initialize (smacc2::ISmaccState * ownerState)
Definition at line 33 of file smacc_event_generator.cpp.
{
  this->ownerState_ = ownerState;
  this->onInitialized();
}
References onInitialized(), and ownerState_.
onEntry()
void smacc2::SmaccEventGenerator::onEntry () virtual
Reimplemented in smacc2::event_generators::EgConditionalGenerator, and smacc2::state_reactors::EgRandomGenerator.
Definition at line 29 of file smacc_event_generator.cpp.
{}
onExit()
void smacc2::SmaccEventGenerator::onExit () virtual
Definition at line 31 of file smacc_event_generator.cpp.
{}
onInitialized()
void smacc2::SmaccEventGenerator::onInitialized () virtual
Definition at line 39 of file smacc_event_generator.cpp.
{}
Referenced by initialize().
onStateAllocation()
template<typename TState , typename TSource > void smacc2::SmaccEventGenerator::onStateAllocation ()
Definition at line 40 of file smacc_event_generator_impl.hpp.
{
}
postEvent() [1/2]
template<typename EventType > void smacc2::SmaccEventGenerator::postEvent ()
Definition at line 34 of file smacc_event_generator_impl.hpp.
{
  ownerState_->postEvent<EventType>();
}
References ownerState_, and smacc2::ISmaccState::postEvent().
Referenced by smacc2::event_generators::EgConditionalGenerator::onStateAllocation(), and smacc2::state_reactors::EgRandomGenerator::onStateAllocation().
postEvent() [2/2]
template<typename EventType > void smacc2::SmaccEventGenerator::postEvent (const EventType & ev)
Definition at line 28 of file smacc_event_generator_impl.hpp.
{
  ownerState_->postEvent(ev);
}
References ownerState_, and smacc2::ISmaccState::postEvent().
Member Data Documentation
ISmaccStateMachine
friend smacc2::SmaccEventGenerator::ISmaccStateMachine private
Definition at line 59 of file smacc_event_generator.hpp.
ownerState_
ISmaccState* smacc2::SmaccEventGenerator::ownerState_ private
Definition at line 58 of file smacc_event_generator.hpp.
Referenced by initialize(), postEvent(), and postEvent().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/smacc_event_generator.hpp
smacc2/include/smacc2/impl/smacc_event_generator_impl.hpp
smacc2/src/smacc2/smacc_event_generator.cpp