SMACC2: cl_move_group_interface::ClMoveGroup Class Reference
cl_move_group_interface::ClMoveGroup Class Reference
#include <cl_movegroup.hpp>
Public Member Functions
ClMoveGroup (std::string groupName)
ClMoveGroup (const moveit::planning_interface::MoveGroupInterface::Options &options)
virtual ~ClMoveGroup ()
void onInitialize () override
void postEventMotionExecutionSucceded ()
void postEventMotionExecutionFailed ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TCallback , typename T >
boost::signals2::connection onMotionExecutionSuccedded (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onMotionExecutionFailed (TCallback callback, T *object)
const moveit::planning_interface::MoveGroupInterface::Options & getOptions () const
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void onInitialize ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Public Attributes
std::shared_ptr< moveit::planning_interface::MoveGroupInterface > moveGroupClientInterface
std::shared_ptr< moveit::planning_interface::PlanningSceneInterface > planningSceneInterface
Private Attributes
std::function< void()> postEventMotionExecutionSucceded_
std::function< void()> postEventMotionExecutionFailed_
smacc2::SmaccSignal< void()> onSucceded_
smacc2::SmaccSignal< void()> onFailed_
moveit::planning_interface::MoveGroupInterface::Options options_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Detailed Description
Definition at line 78 of file cl_movegroup.hpp.
Constructor & Destructor Documentation
ClMoveGroup() [1/2]
cl_move_group_interface::ClMoveGroup::ClMoveGroup (std::string groupName)
Definition at line 36 of file cl_movegroup.cpp.
: options_(groupName) {}
ClMoveGroup() [2/2]
cl_move_group_interface::ClMoveGroup::ClMoveGroup (const moveit::planning_interface::MoveGroupInterface::Options & options)
Definition at line 31 of file cl_movegroup.cpp.
: options_(options)
{
}
~ClMoveGroup()
cl_move_group_interface::ClMoveGroup::~ClMoveGroup () virtual
Definition at line 38 of file cl_movegroup.cpp.
{}
Member Function Documentation
getOptions()
const moveit::planning_interface::MoveGroupInterface::Options & cl_move_group_interface::ClMoveGroup::getOptions () const
Definition at line 58 of file cl_movegroup.cpp.
{
  return options_;
}
References options_.
Referenced by cl_move_group_interface::CbWaitJointState::onEntry().
onInitialize()
void cl_move_group_interface::ClMoveGroup::onInitialize () override virtual
Reimplemented from smacc2::ISmaccClient.
Definition at line 40 of file cl_movegroup.cpp.
{
  moveGroupClientInterface = std::make_shared<MoveGroupInterface>(getNode(), options_);
  planningSceneInterface = std::make_shared<PlanningSceneInterface>(options_.move_group_namespace_);
}
References smacc2::ISmaccClient::getNode(), moveGroupClientInterface, options_, and planningSceneInterface.
onMotionExecutionFailed()
template<typename TCallback , typename T > boost::signals2::connection cl_move_group_interface::ClMoveGroup::onMotionExecutionFailed (TCallback callback, T * object) inline
Definition at line 123 of file cl_movegroup.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onFailed_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClient::getStateMachine(), and onFailed_.
onMotionExecutionSuccedded()
template<typename TCallback , typename T > boost::signals2::connection cl_move_group_interface::ClMoveGroup::onMotionExecutionSuccedded (TCallback callback, T * object) inline
Definition at line 117 of file cl_movegroup.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onSucceded_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClient::getStateMachine(), and onSucceded_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_move_group_interface::ClMoveGroup::onOrthogonalAllocation () inline
Definition at line 101 of file cl_movegroup.hpp.
  {
    postEventMotionExecutionSucceded_ = [=]()
    {
      this->onSucceded_();
      this->postEvent<EvMoveGroupMotionExecutionSucceded<TSourceObject, TOrthogonal>>();
    };
    postEventMotionExecutionFailed_ = [=]()
    {
      this->onFailed_();
      this->postEvent<EvMoveGroupMotionExecutionFailed<TSourceObject, TOrthogonal>>();
    };
  }
References onFailed_, onSucceded_, postEventMotionExecutionFailed_, and postEventMotionExecutionSucceded_.
postEventMotionExecutionFailed()
void cl_move_group_interface::ClMoveGroup::postEventMotionExecutionFailed ()
Definition at line 52 of file cl_movegroup.cpp.
{
  RCLCPP_INFO(getLogger(), "[ClMoveGroup] Post Motion Failure Event");
  postEventMotionExecutionFailed_();
}
References smacc2::ISmaccClient::getLogger(), and postEventMotionExecutionFailed_.
Referenced by cl_move_group_interface::CbMoveJoints::moveJoints(), cl_move_group_interface::CbMoveEndEffectorRelative::moveRelative(), cl_move_group_interface::CbMoveCartesianRelative::moveRelativeCartesian(), cl_move_group_interface::CbMoveEndEffector::moveToAbsolutePose(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry(), and cl_move_group_interface::CbMoveEndEffectorTrajectory::onOrthogonalAllocation().
postEventMotionExecutionSucceded()
void cl_move_group_interface::ClMoveGroup::postEventMotionExecutionSucceded ()
Definition at line 46 of file cl_movegroup.cpp.
{
  RCLCPP_INFO(getLogger(), "[ClMoveGroup] Post Motion Success Event");
  postEventMotionExecutionSucceded_();
}
References smacc2::ISmaccClient::getLogger(), and postEventMotionExecutionSucceded_.
Referenced by cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_move_group_interface::CbMoveJoints::moveJoints(), cl_move_group_interface::CbMoveEndEffectorRelative::moveRelative(), cl_move_group_interface::CbMoveCartesianRelative::moveRelativeCartesian(), and cl_move_group_interface::CbMoveEndEffector::moveToAbsolutePose().
Member Data Documentation
moveGroupClientInterface
std::shared_ptr<moveit::planning_interface::MoveGroupInterface> cl_move_group_interface::ClMoveGroup::moveGroupClientInterface
Definition at line 84 of file cl_movegroup.hpp.
Referenced by cl_move_group_interface::CbCircularPivotMotion::computeCurrentEndEffectorPoseRelativeToPivot(), cl_move_group_interface::CbMoveEndEffectorTrajectory::computeJointSpaceTrajectory(), cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_move_group_interface::CbMoveEndEffectorTrajectory::getCurrentEndEffectorPose(), cl_move_group_interface::CbMoveNamedTarget::getNamedTargetValues(), cl_move_group_interface::CbAttachObject::onEntry(), cl_move_group_interface::CbDetachObject::onEntry(), cl_move_group_interface::CbEndEffectorRotate::onEntry(), cl_move_group_interface::CbMoveCartesianRelative::onEntry(), cl_move_group_interface::CbMoveEndEffector::onEntry(), cl_move_group_interface::CbMoveEndEffectorRelative::onEntry(), cl_move_group_interface::CbMoveJoints::onEntry(), cl_move_group_interface::CbMoveNamedTarget::onEntry(), and onInitialize().
onFailed_
smacc2::SmaccSignal<void()> cl_move_group_interface::ClMoveGroup::onFailed_ private
Definition at line 135 of file cl_movegroup.hpp.
Referenced by onMotionExecutionFailed(), and onOrthogonalAllocation().
onSucceded_
smacc2::SmaccSignal<void()> cl_move_group_interface::ClMoveGroup::onSucceded_ private
Definition at line 134 of file cl_movegroup.hpp.
Referenced by onMotionExecutionSuccedded(), and onOrthogonalAllocation().
options_
moveit::planning_interface::MoveGroupInterface::Options cl_move_group_interface::ClMoveGroup::options_ private
Definition at line 138 of file cl_movegroup.hpp.
Referenced by getOptions(), and onInitialize().
planningSceneInterface
std::shared_ptr<moveit::planning_interface::PlanningSceneInterface> cl_move_group_interface::ClMoveGroup::planningSceneInterface
Definition at line 86 of file cl_movegroup.hpp.
Referenced by cl_move_group_interface::CbAttachObject::onEntry(), cl_move_group_interface::CbDetachObject::onEntry(), and onInitialize().
postEventMotionExecutionFailed_
std::function<void()> cl_move_group_interface::ClMoveGroup::postEventMotionExecutionFailed_ private
Definition at line 132 of file cl_movegroup.hpp.
Referenced by onOrthogonalAllocation(), and postEventMotionExecutionFailed().
postEventMotionExecutionSucceded_
std::function<void()> cl_move_group_interface::ClMoveGroup::postEventMotionExecutionSucceded_ private
Definition at line 131 of file cl_movegroup.hpp.
Referenced by onOrthogonalAllocation(), and postEventMotionExecutionSucceded().
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/cl_movegroup.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/cl_movegroup.cpp