SMACC2: cl_nitrosz::CpSlamToolbox Class Reference
cl_nitrosz::CpSlamToolbox Class Reference
#include <cp_slam_toolbox.hpp>
Public Types
enum class SlamToolboxState { Resumed , Paused }
Public Member Functions
CpSlamToolbox ()
virtual ~CpSlamToolbox ()
SlamToolboxState getState ()
void toogleState ()
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Private Attributes
SlamToolboxState state_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 31 of file cp_slam_toolbox.hpp.
Member Enumeration Documentation
SlamToolboxState
enum class cl_nitrosz::CpSlamToolbox::SlamToolboxState strong
Enumerator
Resumed
Paused
Definition at line 37 of file cp_slam_toolbox.hpp.
  {
    Resumed,
    Paused
  };
Constructor & Destructor Documentation
CpSlamToolbox()
cl_nitrosz::CpSlamToolbox::CpSlamToolbox ()
Definition at line 25 of file cp_slam_toolbox.cpp.
: state_(SlamToolboxState::Resumed) {}
~CpSlamToolbox()
cl_nitrosz::CpSlamToolbox::~CpSlamToolbox () virtual
Definition at line 26 of file cp_slam_toolbox.cpp.
{}
Member Function Documentation
getState()
SlamToolboxState cl_nitrosz::CpSlamToolbox::getState () inline
Definition at line 43 of file cp_slam_toolbox.hpp.
{ return state_; }
References state_.
Referenced by cl_nitrosz::CbPauseSlam::onEntry(), and cl_nitrosz::CbResumeSlam::onEntry().
toogleState()
void cl_nitrosz::CpSlamToolbox::toogleState ()
Definition at line 28 of file cp_slam_toolbox.cpp.
{
  if (state_ == SlamToolboxState::Paused)
  {
    state_ = SlamToolboxState::Resumed;
  }
  else
  {
    state_ = SlamToolboxState::Paused;
  }
}
References Paused, Resumed, and state_.
Referenced by cl_nitrosz::CbPauseSlam::onEntry(), and cl_nitrosz::CbResumeSlam::onEntry().
Member Data Documentation
state_
SlamToolboxState cl_nitrosz::CpSlamToolbox::state_ private
Definition at line 48 of file cp_slam_toolbox.hpp.
Referenced by getState(), and toogleState().
The documentation for this class was generated from the following files:
smacc2_client_library/nitrosz_client/nitrosz_client/include/nitrosz_client/components/slam_toolbox/cp_slam_toolbox.hpp
smacc2_client_library/nitrosz_client/nitrosz_client/src/nitrosz_client/components/slam_toolbox/cp_slam_toolbox.cpp