SMACC2: cl_move_group_interface::CpGraspingComponent Class Reference
cl_move_group_interface::CpGraspingComponent Class Reference
#include <cp_grasping_objects.hpp>
Public Member Functions
bool getGraspingObject (std::string name, moveit_msgs::msg::CollisionObject &object)
void createGraspableBox (std::string frameid, float x, float y, float z, float xl, float yl, float zl)
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Attributes
std::vector< std::string > fingerTipNames
std::string gripperLink_ = "gripper_link"
std::optional< std::string > currentAttachedObjectName
Private Attributes
std::map< std::string, moveit_msgs::msg::CollisionObject > graspingObjects
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 30 of file cp_grasping_objects.hpp.
Member Function Documentation
createGraspableBox()
void cl_move_group_interface::CpGraspingComponent::createGraspableBox (std::string frameid, float x, float y, float z, float xl, float yl, float zl)
Definition at line 39 of file cp_grasping_objects.cpp.
{
  RCLCPP_INFO_STREAM(
    getLogger(), "[" << getName() << "] creating grasping object in planning scene: " << frameid);
  moveit_msgs::msg::CollisionObject collision;
  auto boxname = frameid;
  ;
  collision.id = boxname;
  collision.header.frame_id = frameid;
  collision.primitives.resize(1);
  collision.primitives[0].type = collision.primitives[0].BOX;
  collision.primitives[0].dimensions.resize(3);
  collision.primitives[0].dimensions[0] = xl;
  collision.primitives[0].dimensions[1] = yl;
  collision.primitives[0].dimensions[2] = zl;
  collision.primitive_poses.resize(1);
  collision.primitive_poses[0].position.x = x;
  collision.primitive_poses[0].position.y = y;
  collision.primitive_poses[0].position.z = z;
  collision.primitive_poses[0].orientation.w = 1.0;
  graspingObjects[boxname] = collision;
}
References cl_nav2z::frameid, smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getName(), and graspingObjects.
getGraspingObject()
bool cl_move_group_interface::CpGraspingComponent::getGraspingObject (std::string name, moveit_msgs::msg::CollisionObject & object)
Definition at line 25 of file cp_grasping_objects.cpp.
{
  if (this->graspingObjects.count(name))
  {
    object = this->graspingObjects[name];
    return true;
  }
  else
  {
    return false;
  }
}
References graspingObjects.
Referenced by cl_move_group_interface::CbAttachObject::onEntry().
Member Data Documentation
currentAttachedObjectName
std::optional<std::string> cl_move_group_interface::CpGraspingComponent::currentAttachedObjectName
Definition at line 39 of file cp_grasping_objects.hpp.
Referenced by cl_move_group_interface::CbAttachObject::onEntry(), and cl_move_group_interface::CbDetachObject::onEntry().
fingerTipNames
std::vector<std::string> cl_move_group_interface::CpGraspingComponent::fingerTipNames
Definition at line 36 of file cp_grasping_objects.hpp.
Referenced by cl_move_group_interface::CbAttachObject::onEntry().
graspingObjects
std::map<std::string, moveit_msgs::msg::CollisionObject> cl_move_group_interface::CpGraspingComponent::graspingObjects private
Definition at line 33 of file cp_grasping_objects.hpp.
Referenced by createGraspableBox(), and getGraspingObject().
gripperLink_
std::string cl_move_group_interface::CpGraspingComponent::gripperLink_ = "gripper_link"
Definition at line 37 of file cp_grasping_objects.hpp.
Referenced by cl_move_group_interface::CbAttachObject::onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/components/cp_grasping_objects.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/components/cp_grasping_objects.cpp