SMACC2: cl_nav2z::CbWaitTransform Class Reference
cl_nav2z::CbWaitTransform Class Reference
#include <cb_wait_transform.hpp>
Public Member Functions
CbWaitTransform (std::string targetFrame, std::string referenceFrame, rclcpp::Duration timeout)
virtual ~CbWaitTransform ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onExit ()
Protected Attributes
std::shared_ptr< tf2_ros::Buffer > tfBuffer_
std::shared_ptr< tf2_ros::TransformListener > tfListener_
std::string targetFrame_
std::string referenceFrame_
rclcpp::Duration timeout_
std::optional< tf2::Stamped< tf2::Transform > > result_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 34 of file cb_wait_transform.hpp.
Constructor & Destructor Documentation
CbWaitTransform()
cl_nav2z::CbWaitTransform::CbWaitTransform (std::string targetFrame, std::string referenceFrame, rclcpp::Duration timeout)
Definition at line 24 of file cb_wait_transform.cpp.
: targetFrame_(targetFrame), referenceFrame_(referenceFrame), timeout_(timeout)
{
}
~CbWaitTransform()
cl_nav2z::CbWaitTransform::~CbWaitTransform () virtual
Definition at line 30 of file cb_wait_transform.cpp.
{}
Member Function Documentation
onEntry()
void cl_nav2z::CbWaitTransform::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 32 of file cb_wait_transform.cpp.
{
  RCLCPP_INFO(
    getLogger(), "[CbWaitTransform] ref %s -> target %s", referenceFrame_.c_str(),
    targetFrame_.c_str());
  tfBuffer_ = std::make_shared<tf2_ros::Buffer>(getNode()->get_clock());
  tfListener_ = std::make_shared<tf2_ros::TransformListener>(*tfBuffer_);
  tf2::Stamped<tf2::Transform> transform;
  try
  {
    auto transformstamped =
      tfBuffer_->lookupTransform(targetFrame_, referenceFrame_, getNode()->now(), timeout_);
    tf2::fromMsg(transformstamped, transform);
    result_ = transform;
    RCLCPP_INFO(
      getLogger(), "[CbWaitTransform] Success wait transform ref %s -> target %s",
      referenceFrame_.c_str(), targetFrame_.c_str());
    this->postSuccessEvent();
  }
  catch (tf2::TransformException & ex)
  {
    RCLCPP_ERROR_STREAM(
      getLogger(), "[CbWaitTransform] Failure waiting transform ( ref "
                     << targetFrame_ << "/ target " << referenceFrame_ << " - " << ex.what());
    this->postFailureEvent();
  }
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), referenceFrame_, result_, targetFrame_, tfBuffer_, tfListener_, and timeout_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_nav2z::CbWaitTransform::onOrthogonalAllocation () inline
Definition at line 42 of file cb_wait_transform.hpp.
  {
    smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
  }
References smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation().
Member Data Documentation
referenceFrame_
std::string cl_nav2z::CbWaitTransform::referenceFrame_ protected
Definition at line 55 of file cb_wait_transform.hpp.
Referenced by onEntry().
result_
std::optional<tf2::Stamped<tf2::Transform> > cl_nav2z::CbWaitTransform::result_ protected
Definition at line 58 of file cb_wait_transform.hpp.
Referenced by onEntry().
targetFrame_
std::string cl_nav2z::CbWaitTransform::targetFrame_ protected
Definition at line 54 of file cb_wait_transform.hpp.
Referenced by onEntry().
tfBuffer_
std::shared_ptr<tf2_ros::Buffer> cl_nav2z::CbWaitTransform::tfBuffer_ protected
Definition at line 51 of file cb_wait_transform.hpp.
Referenced by onEntry().
tfListener_
std::shared_ptr<tf2_ros::TransformListener> cl_nav2z::CbWaitTransform::tfListener_ protected
Definition at line 52 of file cb_wait_transform.hpp.
Referenced by onEntry().
timeout_
rclcpp::Duration cl_nav2z::CbWaitTransform::timeout_ protected
Definition at line 56 of file cb_wait_transform.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/client_behaviors/cb_wait_transform.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/client_behaviors/cb_wait_transform.cpp