SMACC2: smacc2::client_behaviors::CbWaitTopicMessage< TMessage > Class Template Reference
smacc2::client_behaviors::CbWaitTopicMessage< TMessage > Class Template Reference
#include <cb_wait_topic_message.hpp>
Public Member Functions
CbWaitTopicMessage (const char *topicname, std::function< bool(const TMessage &)> guardFunction=nullptr)
virtual ~CbWaitTopicMessage ()
void onEntry () override
void onMessageReceived (const typename TMessage::SharedPtr msg)
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Protected Attributes
bool success = false
rclcpp::Subscription< TMessage >::SharedPtr sub_
std::function< bool(const TMessage &)> guardFn_
std::string topicname_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
template<typename TMessage>
class smacc2::client_behaviors::CbWaitTopicMessage< TMessage >
Definition at line 36 of file cb_wait_topic_message.hpp.
Constructor & Destructor Documentation
CbWaitTopicMessage()
template<typename TMessage > smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::CbWaitTopicMessage (const char * topicname, std::function< bool(const TMessage &)> guardFunction = nullptr) inline
Definition at line 39 of file cb_wait_topic_message.hpp.
  {
    topicname_ = topicname;
    guardFn_ = guardFunction;
  }
References smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::guardFn_, and smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::topicname_.
~CbWaitTopicMessage()
template<typename TMessage > virtual smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::~CbWaitTopicMessage () inline virtual
Definition at line 46 of file cb_wait_topic_message.hpp.
{}
Member Function Documentation
onEntry()
template<typename TMessage > void smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onEntry () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 48 of file cb_wait_topic_message.hpp.
  {
    rclcpp::SensorDataQoS qos;
    // qos.reliable();
    // rclcpp::SubscriptionOptions sub_option;
    RCLCPP_INFO_STREAM(
      getLogger(), "[CbWaitTopicMessage] waiting message from topic: "
                     << topicname_ << "[" << demangledTypeName<TMessage>() << "]");
    // sub_ = getNode()->create_subscription<TMessage>(
    //   topicname_, qos,
    //   std::bind(&CbWaitTopicMessage<TMessage>::onMessageReceived, this, std::placeholders::_1),
    //   sub_option);
    std::function<void(typename TMessage::SharedPtr)> fn = [this](auto msg)
    { this->onMessageReceived(msg); };
    auto nh = getNode();
    sub_ = nh->create_subscription<TMessage>(topicname_, qos, fn);
  }
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onMessageReceived(), smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::sub_, and smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::topicname_.
onMessageReceived()
template<typename TMessage > void smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onMessageReceived (const typename TMessage::SharedPtr msg) inline
Definition at line 69 of file cb_wait_topic_message.hpp.
  {
    if (guardFn_ == nullptr || guardFn_(*msg))
    {
      RCLCPP_INFO(getLogger(), "[CbWaitTopicMessage] message received.");
      success = true;
      this->postSuccessEvent();
    }
  }
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::guardFn_, smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), and smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::success.
Referenced by smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onEntry().
Member Data Documentation
guardFn_
template<typename TMessage > std::function<bool(const TMessage &)> smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::guardFn_ protected
Definition at line 82 of file cb_wait_topic_message.hpp.
Referenced by smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::CbWaitTopicMessage(), and smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onMessageReceived().
sub_
template<typename TMessage > rclcpp::Subscription<TMessage>::SharedPtr smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::sub_ protected
Definition at line 81 of file cb_wait_topic_message.hpp.
Referenced by smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onEntry().
success
template<typename TMessage > bool smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::success = false protected
Definition at line 80 of file cb_wait_topic_message.hpp.
Referenced by smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onMessageReceived().
topicname_
template<typename TMessage > std::string smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::topicname_ protected
Definition at line 83 of file cb_wait_topic_message.hpp.
Referenced by smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::CbWaitTopicMessage(), and smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onEntry().
The documentation for this class was generated from the following file:
smacc2/include/smacc2/client_behaviors/cb_wait_topic_message.hpp