SMACC2: cl_http::ssl_http_session Class Reference
cl_http::ssl_http_session Class Reference
#include <ssl_http_session.hpp>
Public Member Functions
ssl_http_session (boost::asio::any_io_executor ioc, boost::asio::ssl::context &ssl_context, const std::function< void(const TResponse &)> response)
virtual ~ssl_http_session ()
void run (const std::string &host, const std::string &target, const boost::beast::http::verb http_method, const int &version) override
std::string getPort () override
Public Member Functions inherited from cl_http::http_session_base
virtual ~http_session_base ()
Private Member Functions
void on_resolve (boost::beast::error_code ec, boost::asio::ip::tcp::resolver::results_type results) override
void fail (boost::beast::error_code ec, const char *what) override
void on_connect (boost::beast::error_code ec, boost::asio::ip::tcp::resolver::results_type::endpoint_type) override
void on_handshake (boost::beast::error_code ec) override
void on_write (boost::beast::error_code ec, std::size_t bytes_transferred) override
void on_read (boost::beast::error_code ec, std::size_t bytes_transferred) override
void on_shutdown (boost::beast::error_code ec) override
void setBody (const std::string &body) override
void setHeaders (const std::unordered_map< std::string, std::string > &headers) override
void appendToHeader (const std::string &key, const std::string &val)
Private Attributes
const std::string kPort = "443"
std::function< void(const TResponse &)> onResponse
boost::asio::ip::tcp::resolver resolver_
boost::beast::ssl_stream< boost::beast::tcp_stream > stream_
boost::beast::flat_buffer buffer_
boost::beast::http::request< boost::beast::http::string_body > req_
TResponse res_
Additional Inherited Members
Public Types inherited from cl_http::http_session_base
using TResponse = boost::beast::http::response< boost::beast::http::string_body >
Detailed Description
Definition at line 37 of file ssl_http_session.hpp.
Constructor & Destructor Documentation
ssl_http_session()
cl_http::ssl_http_session::ssl_http_session (boost::asio::any_io_executor ioc, boost::asio::ssl::context & ssl_context, const std::function< void(const TResponse &)> response)
Definition at line 27 of file ssl_http_session.cpp.
: onResponse{response}, resolver_{ioc}, stream_{ioc, ssl_context}
{
}
~ssl_http_session()
virtual cl_http::ssl_http_session::~ssl_http_session () inline virtual
Definition at line 47 of file ssl_http_session.hpp.
{}
Member Function Documentation
appendToHeader()
void cl_http::ssl_http_session::appendToHeader (const std::string & key, const std::string & val) private
Definition at line 44 of file ssl_http_session.cpp.
{
  req_.set(key, val);
}
References req_.
Referenced by setHeaders().
fail()
void cl_http::ssl_http_session::fail (boost::beast::error_code ec, const char * what) override private virtual
Implements cl_http::http_session_base.
Definition at line 87 of file ssl_http_session.cpp.
{
  std::cout << "Failure!..." << std::endl;
  std::cerr << what << ": " << ec.message() << "\n";
  res_.result(boost::beast::http::status::bad_request);
  res_.reason() = ec.message();
  onResponse(res_);
}
References onResponse, and res_.
Referenced by on_connect(), on_handshake(), on_read(), on_resolve(), and on_write().
getPort()
std::string cl_http::ssl_http_session::getPort () inline override virtual
Implements cl_http::http_session_base.
Definition at line 54 of file ssl_http_session.hpp.
{ return kPort; }
References kPort.
on_connect()
void cl_http::ssl_http_session::on_connect (boost::beast::error_code ec, boost::asio::ip::tcp::resolver::results_type::endpoint_type) override private virtual
Implements cl_http::http_session_base.
Definition at line 96 of file ssl_http_session.cpp.
{
  if (ec) return fail(ec, "connect");
  // Set a timeout on the operation
  boost::beast::get_lowest_layer(stream_).expires_after(std::chrono::seconds(1));
  // Send the HTTP request to the remote host
  stream_.async_handshake(
    boost::asio::ssl::stream_base::client,
    boost::beast::bind_front_handler(&ssl_http_session::on_handshake, shared_from_this()));
}
References fail(), on_handshake(), and stream_.
Referenced by on_resolve().
on_handshake()
void cl_http::ssl_http_session::on_handshake (boost::beast::error_code ec) override private virtual
Reimplemented from cl_http::http_session_base.
Definition at line 110 of file ssl_http_session.cpp.
{
  if (ec) return fail(ec, "handshake");
  // Set a timeout on the operation
  boost::beast::get_lowest_layer(stream_).expires_after(std::chrono::seconds(1));
  // Send the HTTP request to the remote host
  boost::beast::http::async_write(
    stream_, req_,
    boost::beast::bind_front_handler(&ssl_http_session::on_write, shared_from_this()));
}
References fail(), on_write(), req_, and stream_.
Referenced by on_connect().
on_read()
void cl_http::ssl_http_session::on_read (boost::beast::error_code ec, std::size_t bytes_transferred) override private virtual
Implements cl_http::http_session_base.
Definition at line 135 of file ssl_http_session.cpp.
{
  boost::ignore_unused(bytes_transferred);
  if (ec) return fail(ec, "read");
  boost::beast::get_lowest_layer(stream_).expires_after(std::chrono::seconds(1));
  // Gracefully close the socket
  // stream_.socket().shutdown(boost::asio::ip::tcp::socket::shutdown_both, ec);
  stream_.async_shutdown(
    boost::beast::bind_front_handler(&ssl_http_session::on_shutdown, shared_from_this()));
}
References fail(), on_shutdown(), and stream_.
Referenced by on_write().
on_resolve()
void cl_http::ssl_http_session::on_resolve (boost::beast::error_code ec, boost::asio::ip::tcp::resolver::results_type results) override private virtual
Implements cl_http::http_session_base.
Definition at line 74 of file ssl_http_session.cpp.
{
  if (ec) return fail(ec, "resolve");
  // Set a timeout on the operation
  boost::beast::get_lowest_layer(stream_).expires_after(std::chrono::seconds(1));
  // Make the connection on the IP address we get from a lookup
  boost::beast::get_lowest_layer(stream_).async_connect(
    results, boost::beast::bind_front_handler(&ssl_http_session::on_connect, shared_from_this()));
}
References fail(), on_connect(), and stream_.
Referenced by run().
on_shutdown()
void cl_http::ssl_http_session::on_shutdown (boost::beast::error_code ec) override private virtual
Reimplemented from cl_http::http_session_base.
Definition at line 149 of file ssl_http_session.cpp.
{
  // not_connected happens sometimes so don't bother reporting it.
  if (ec == boost::asio::error::eof)
  {
    // Rationale:
    // http://stackoverflow.com/questions/25587403/boost-asio-ssl-async-shutdown-always-finishes-with-an-error
    ec = {};
  }
  // if (ec) return fail(ec, "shutdown");
  // If we get here then the connection is closed gracefully
  onResponse(res_);
}
References onResponse, and res_.
Referenced by on_read().
on_write()
void cl_http::ssl_http_session::on_write (boost::beast::error_code ec, std::size_t bytes_transferred) override private virtual
Implements cl_http::http_session_base.
Definition at line 123 of file ssl_http_session.cpp.
{
  boost::ignore_unused(bytes_transferred);
  if (ec) return fail(ec, "write");
  // Receive the HTTP response
  boost::beast::http::async_read(
    stream_, buffer_, res_,
    boost::beast::bind_front_handler(&ssl_http_session::on_read, shared_from_this()));
}
References buffer_, fail(), on_read(), res_, and stream_.
Referenced by on_handshake().
run()
void cl_http::ssl_http_session::run (const std::string & host, const std::string & target, const boost::beast::http::verb http_method, const int & version) override virtual
Implements cl_http::http_session_base.
Definition at line 49 of file ssl_http_session.cpp.
{
  // Set up an HTTP request
  req_.version(version);
  req_.method(http_method);
  req_.target(target);
  req_.set(boost::beast::http::field::host, host);
  req_.set(boost::beast::http::field::user_agent, BOOST_BEAST_VERSION_STRING);
  // Set an SNI to deal with CDNs
  if (!SSL_set_tlsext_host_name(stream_.native_handle(), host.c_str()))
  {
    boost::system::error_code ec{
      static_cast<int>(::ERR_get_error()), boost::asio::error::get_ssl_category()};
    std::cerr << ec.message() << "\n";
    return;
  }
  // Look up the domain name
  resolver_.async_resolve(
    host.c_str(), kPort.c_str(),
    boost::beast::bind_front_handler(&ssl_http_session::on_resolve, shared_from_this()));
}
References kPort, on_resolve(), req_, resolver_, and stream_.
setBody()
void cl_http::ssl_http_session::setBody (const std::string & body) override private virtual
Implements cl_http::http_session_base.
Definition at line 34 of file ssl_http_session.cpp.
{ req_.body() = body; }
References req_.
setHeaders()
void cl_http::ssl_http_session::setHeaders (const std::unordered_map< std::string, std::string > & headers) override private virtual
Implements cl_http::http_session_base.
Definition at line 36 of file ssl_http_session.cpp.
{
  for (const auto & [key, val] : headers)
  {
    this->appendToHeader(key, val);
  }
}
References appendToHeader().
Member Data Documentation
buffer_
boost::beast::flat_buffer cl_http::ssl_http_session::buffer_ private
Definition at line 78 of file ssl_http_session.hpp.
Referenced by on_write().
kPort
const std::string cl_http::ssl_http_session::kPort = "443" private
Definition at line 57 of file ssl_http_session.hpp.
Referenced by getPort(), and run().
onResponse
std::function<void(const TResponse &)> cl_http::ssl_http_session::onResponse private
Definition at line 73 of file ssl_http_session.hpp.
Referenced by fail(), and on_shutdown().
req_
boost::beast::http::request<boost::beast::http::string_body> cl_http::ssl_http_session::req_ private
Definition at line 79 of file ssl_http_session.hpp.
Referenced by appendToHeader(), on_handshake(), run(), and setBody().
res_
TResponse cl_http::ssl_http_session::res_ private
Definition at line 80 of file ssl_http_session.hpp.
Referenced by fail(), on_shutdown(), and on_write().
resolver_
boost::asio::ip::tcp::resolver cl_http::ssl_http_session::resolver_ private
Definition at line 75 of file ssl_http_session.hpp.
Referenced by run().
stream_
boost::beast::ssl_stream<boost::beast::tcp_stream> cl_http::ssl_http_session::stream_ private
Definition at line 77 of file ssl_http_session.hpp.
Referenced by on_connect(), on_handshake(), on_read(), on_resolve(), on_write(), and run().
The documentation for this class was generated from the following files:
smacc2_client_library/http_client/include/http_client/ssl_http_session.hpp
smacc2_client_library/http_client/src/http_client/ssl_http_session.cpp