SMACC2: smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg > Class Template Reference
smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg > Class Template Reference abstract
#include <cb_subscription_callback_base.hpp>
Public Member Functions
void onEntry () override
virtual void onMessageReceived (const TMsg &msg)=0
Public Member Functions inherited from smacc2::SmaccClientBehavior
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Protected Attributes
smacc2::client_bases::SmaccSubscriberClient< TMsg > * attachedClient_ = nullptr
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
template<typename TMsg>
class smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg >
Definition at line 28 of file cb_subscription_callback_base.hpp.
Member Function Documentation
onEntry()
template<typename TMsg > void smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onEntry () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 31 of file cb_subscription_callback_base.hpp.
  {
    this->requiresClient(attachedClient_);
    attachedClient_->onMessageReceived(&CbSubscriptionCallbackBase::onMessageReceived, this);
  }
References smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg >::attachedClient_, smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onMessageReceived(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), and smacc2::ISmaccClientBehavior::requiresClient().
onMessageReceived()
template<typename TMsg > virtual void smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onMessageReceived (const TMsg & msg) pure virtual
Referenced by smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onEntry().
Member Data Documentation
attachedClient_
template<typename TMsg > smacc2::client_bases::SmaccSubscriberClient<TMsg>* smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg >::attachedClient_ = nullptr protected
Definition at line 40 of file cb_subscription_callback_base.hpp.
Referenced by smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onEntry().
The documentation for this class was generated from the following file:
smacc2/include/smacc2/client_behaviors/cb_subscription_callback_base.hpp