SMACC2: sm_dance_bot_strikes_back::cl_temperature_sensor::CbConditionTemperatureSensor Class Reference
sm_dance_bot_strikes_back::cl_temperature_sensor::CbConditionTemperatureSensor Class Reference
#include <cb_custom_condition_temperature_sensor.hpp>
Public Member Functions
CbConditionTemperatureSensor ()
void onEntry () override
void onMessageCallback (const sensor_msgs::msg::Temperature &msg) override
Public Member Functions inherited from cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >
CbDefaultMultiRoleSensorBehavior ()
void onOrthogonalAllocation ()
void propagateEvent (const TMessageType &)
void propagateEvent2 ()
void onEntry () override
void onExit ()
virtual void onMessageCallback (const TMessageType &)
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Additional Inherited Members
Public Types inherited from cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >
typedef ClientType::TMessageType TMessageType
Static Public Member Functions inherited from cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >
static std::string getEventLabel ()
Public Attributes inherited from cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >
ClTemperatureSensor * sensor_
std::function< void()> deferedEventPropagation
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 35 of file cb_custom_condition_temperature_sensor.hpp.
Constructor & Destructor Documentation
CbConditionTemperatureSensor()
sm_dance_bot_strikes_back::cl_temperature_sensor::CbConditionTemperatureSensor::CbConditionTemperatureSensor () inline
Definition at line 39 of file cb_custom_condition_temperature_sensor.hpp.
{}
Member Function Documentation
onEntry()
void sm_dance_bot_strikes_back::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry () inline override virtual
Reimplemented from smacc2::SmaccClientBehavior.
Definition at line 40 of file cb_custom_condition_temperature_sensor.hpp.
  {
    RCLCPP_INFO(getLogger(), "[CbConditionTemperatureSensor] onEntry");
    cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior<ClTemperatureSensor>::onEntry();
  }
References smacc2::ISmaccClientBehavior::getLogger(), and cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onEntry().
onMessageCallback()
void sm_dance_bot_strikes_back::cl_temperature_sensor::CbConditionTemperatureSensor::onMessageCallback (const sensor_msgs::msg::Temperature & msg) inline override
Definition at line 45 of file cb_custom_condition_temperature_sensor.hpp.
  {
    if (msg.temperature > 40)
    {
      auto ev = new EvCustomTemperatureAlert();
      this->postEvent(ev);
    }
  }
References smacc2::ISmaccClientBehavior::postEvent().
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_dance_bot_strikes_back/include/sm_dance_bot_strikes_back/clients/cl_temperature_sensor/client_behaviors/cb_custom_condition_temperature_sensor.hpp