SMACC2: cl_ros_timer::CbTimer Class Reference
cl_ros_timer::CbTimer Class Reference
#include <cb_ros_timer.hpp>
Public Member Functions
void onEntry () override
void onEntry () override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onClientTimerTickCallback ()
void onEntry () override
void onExit () override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onClientTimerTickCallback ()
Public Member Functions inherited from smacc2::SmaccClientBehavior
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Attributes
ClRosTimer * timerClient_
std::function< void()> postTimerEvent_
boost::signals2::scoped_connection c_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 22 of file cb_ros_timer.hpp.
Member Function Documentation
onClientTimerTickCallback() [1/2]
void cl_ros_timer::CbTimer::onClientTimerTickCallback ()
Definition at line 26 of file cb_timer.cpp.
{ this->postTimerEvent_(); }
References postTimerEvent_.
Referenced by onEntry().
onClientTimerTickCallback() [2/2]
void cl_ros_timer::CbTimer::onClientTimerTickCallback ()
onEntry() [1/3]
void cl_ros_timer::CbTimer::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 19 of file cb_timer.cpp.
{
  this->requiresClient(timerClient_);
  timerClient_->onTimerTick(&CbTimer::onClientTimerTickCallback, this);
}
References onClientTimerTickCallback(), cl_ros_timer::ClRosTimer::onTimerTick(), smacc2::ISmaccClientBehavior::requiresClient(), and timerClient_.
onEntry() [2/3]
void cl_ros_timer::CbTimer::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
onEntry() [3/3]
void cl_ros_timer::CbTimer::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
onExit()
void cl_ros_timer::CbTimer::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 28 of file cb_timer.cpp.
{}
onOrthogonalAllocation() [1/2]
template<typename TOrthogonal , typename TSourceObject > void cl_ros_timer::CbTimer::onOrthogonalAllocation () inline
Definition at line 29 of file cb_ros_timer.hpp.
  {
    this->postTimerEvent_ = [=]()
    { this->template postEvent<EvTimer<TSourceObject, TOrthogonal>>(); };
  }
References smacc2::ISmaccClientBehavior::postEvent(), and postTimerEvent_.
onOrthogonalAllocation() [2/2]
template<typename TOrthogonal , typename TSourceObject > void cl_ros_timer::CbTimer::onOrthogonalAllocation () inline
Definition at line 29 of file cb_ros_timer.hpp.
  {
    this->postTimerEvent_ = [this]()
    { this->template postEvent<EvTimer<TSourceObject, TOrthogonal>>(); };
  }
References smacc2::ISmaccClientBehavior::postEvent(), and postTimerEvent_.
Member Data Documentation
c_
boost::signals2::scoped_connection cl_ros_timer::CbTimer::c_ private
Definition at line 40 of file cb_ros_timer.hpp.
postTimerEvent_
std::function< void()> cl_ros_timer::CbTimer::postTimerEvent_ private
Definition at line 39 of file cb_ros_timer.hpp.
Referenced by onClientTimerTickCallback(), and onOrthogonalAllocation().
timerClient_
ClRosTimer * cl_ros_timer::CbTimer::timerClient_ private
Definition at line 38 of file cb_ros_timer.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/ros_timer_client/include/include/ros_timer_client/client_behaviors/cb_ros_timer.hpp
smacc2_client_library/ros_timer_client/include/ros_timer_client/client_behaviors/cb_ros_timer.hpp
smacc2_client_library/ros_timer_client/src/ros_timer_client/cb_timer.cpp