SMACC2: cl_nav2z::CbNavigateNamedWaypoint Class Reference
cl_nav2z::CbNavigateNamedWaypoint Class Reference
#include <cb_navigate_named_waypoint.hpp>
Public Member Functions
CbNavigateNamedWaypoint (std::string waypointname, std::optional< NavigateNextWaypointOptions > options=std::nullopt)
virtual ~CbNavigateNamedWaypoint ()
void onEntry () override
void onExit () override
Public Member Functions inherited from cl_nav2z::CbNavigateNextWaypoint
CbNavigateNextWaypoint (std::optional< NavigateNextWaypointOptions > options=std::nullopt)
virtual ~CbNavigateNextWaypoint ()
void onEntry () override
void onExit () override
Public Member Functions inherited from cl_nav2z::CbNav2ZClientBehaviorBase
virtual ~CbNav2ZClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Attributes
CpWaypointNavigator * waypointsNavigator_
std::string waypointname_
Additional Inherited Members
Protected Member Functions inherited from cl_nav2z::CbNav2ZClientBehaviorBase
void sendGoal (ClNav2Z::Goal &goal)
void cancelGoal ()
bool isOwnActionResponse (const ClNav2Z::WrappedResult &)
virtual void onNavigationResult (const ClNav2Z::WrappedResult &)
virtual void onNavigationActionSuccess (const ClNav2Z::WrappedResult &)
virtual void onNavigationActionAbort (const ClNav2Z::WrappedResult &)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Attributes inherited from cl_nav2z::CbNavigateNextWaypoint
CpWaypointNavigator * waypointsNavigator_
NavigateNextWaypointOptions options_
cl_nav2z::ClNav2Z::SmaccNavigateResultSignal::SharedPtr navigationCallback_
Protected Attributes inherited from cl_nav2z::CbNav2ZClientBehaviorBase
cl_nav2z::ClNav2Z * nav2zClient_
cl_nav2z::ClNav2Z::SmaccNavigateResultSignal::SharedPtr navigationCallback_
rclcpp_action::ResultCode navigationResult_
std::shared_future< std::shared_ptr< rclcpp_action::ClientGoalHandle< nav2_msgs::action::NavigateToPose > > > goalHandleFuture_
Detailed Description
Definition at line 29 of file cb_navigate_named_waypoint.hpp.
Constructor & Destructor Documentation
CbNavigateNamedWaypoint()
cl_nav2z::CbNavigateNamedWaypoint::CbNavigateNamedWaypoint (std::string waypointname, std::optional< NavigateNextWaypointOptions > options = std::nullopt)
Definition at line 25 of file cb_navigate_named_waypoint.cpp.
: CbNavigateNextWaypoint(options)
{
  waypointname_ = waypointname;
}
References waypointname_.
~CbNavigateNamedWaypoint()
cl_nav2z::CbNavigateNamedWaypoint::~CbNavigateNamedWaypoint () virtual
Definition at line 32 of file cb_navigate_named_waypoint.cpp.
{}
Member Function Documentation
onEntry()
void cl_nav2z::CbNavigateNamedWaypoint::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 34 of file cb_navigate_named_waypoint.cpp.
{
  // waypointsNavigator_ = nav2zClient_->getComponent<CpWaypointNavigator>();
  // waypointsNavigator_->sendNextGoal(options_);
  // auto waypointname = waypointsNavigator_->getCurrentWaypointName();
  // if(waypointname)
  // {
  // RCLCPP_INFO(
  //   getLogger(), "[CbNavigateNamedWaypoint] current iteration waypoints i: %ld with name '%s'",
  //   waypointsNavigator_->getCurrentWaypointIndex(), waypointname->c_str());  }
  // else
  // {
  // RCLCPP_INFO(
  //   getLogger(), "[CbNavigateNamedWaypoint] current iteration waypoints i: %ld",
  //   waypointsNavigator_->getCurrentWaypointIndex());  }
  auto waypointsNavigator_ = nav2zClient_->getComponent<CpWaypointNavigator>();
  waypointsNavigator_->seekName(waypointname_);
  CbNavigateNextWaypoint::onEntry();
}
References smacc2::ISmaccClient::getComponent(), cl_nav2z::CbNav2ZClientBehaviorBase::nav2zClient_, cl_nav2z::CbNavigateNextWaypoint::onEntry(), cl_nav2z::CpWaypointNavigatorBase::seekName(), waypointname_, and waypointsNavigator_.
onExit()
void cl_nav2z::CbNavigateNamedWaypoint::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 57 of file cb_navigate_named_waypoint.cpp.
{ CbNavigateNextWaypoint::onExit(); }
References cl_nav2z::CbNavigateNextWaypoint::onExit().
Member Data Documentation
waypointname_
std::string cl_nav2z::CbNavigateNamedWaypoint::waypointname_
Definition at line 43 of file cb_navigate_named_waypoint.hpp.
Referenced by CbNavigateNamedWaypoint(), and onEntry().
waypointsNavigator_
CpWaypointNavigator* cl_nav2z::CbNavigateNamedWaypoint::waypointsNavigator_
Definition at line 41 of file cb_navigate_named_waypoint.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/client_behaviors/cb_navigate_named_waypoint.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/client_behaviors/cb_navigate_named_waypoint.cpp