SMACC2: cl_nitrosz::CbNav2ZClientBehaviorBase Class Reference
cl_nitrosz::CbNav2ZClientBehaviorBase Class Reference
#include <cb_nitrosz_client_behavior_base.hpp>
Public Member Functions
virtual ~CbNav2ZClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
Protected Member Functions
void sendGoal (ClNitrosZ::Goal &goal)
void cancelGoal ()
bool isOwnActionResponse (const ClNitrosZ::WrappedResult &)
virtual void onNavigationResult (const ClNitrosZ::WrappedResult &)
virtual void onNavigationActionSuccess (const ClNitrosZ::WrappedResult &)
virtual void onNavigationActionAbort (const ClNitrosZ::WrappedResult &)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Protected Attributes
cl_nitrosz::ClNitrosZ * nitroszClient_
cl_nitrosz::ClNitrosZ::SmaccNavigateResultSignal::SharedPtr navigationCallback_
rclcpp_action::ResultCode navigationResult_
std::shared_future< std::shared_ptr< rclcpp_action::ClientGoalHandle< nav2_msgs::action::NavigateToPose > > > goalHandleFuture_
Detailed Description
Definition at line 28 of file cb_nitrosz_client_behavior_base.hpp.
Constructor & Destructor Documentation
~CbNav2ZClientBehaviorBase()
cl_nitrosz::CbNav2ZClientBehaviorBase::~CbNav2ZClientBehaviorBase () virtual
Definition at line 24 of file cb_nitrosz_client_behavior_base.cpp.
{}
Member Function Documentation
cancelGoal()
void cl_nitrosz::CbNav2ZClientBehaviorBase::cancelGoal () protected
Definition at line 43 of file cb_nitrosz_client_behavior_base.cpp.
{ this->nitroszClient_->cancelGoal(); }
References smacc2::client_bases::SmaccActionClientBase< ActionType >::cancelGoal(), and nitroszClient_.
isOwnActionResponse()
bool cl_nitrosz::CbNav2ZClientBehaviorBase::isOwnActionResponse (const ClNitrosZ::WrappedResult & r) protected
Definition at line 45 of file cb_nitrosz_client_behavior_base.cpp.
{
  auto name = getName();
  if (isShutdownRequested())
  {
    RCLCPP_ERROR(
      getLogger(), "[%s] Propagating action client signal skipped. the behavior is shutting down",
      name.c_str());
    return false;
  }
  if (!goalHandleFuture_.valid())
  {
    RCLCPP_ERROR(
      this->getLogger(), "[%s]Propagating action client signal, our goal handle is not valid",
      name.c_str());
    return false;
  }
  auto goalHandle = goalHandleFuture_.get();
  auto goal_uuid_ = goalHandle->get_goal_id();
  if (r.goal_id != goal_uuid_)
  {
    RCLCPP_ERROR(
      getLogger(),
      "[%s] Received a failure event from an action server with a different goal_uuid: %s, "
      "expected: %s",
      smacc2::demangleType(typeid(*this)).c_str(), rclcpp_action::to_string(r.goal_id).c_str(),
      rclcpp_action::to_string(goal_uuid_).c_str());
    return false;
  }
  return true;
}
References smacc2::introspection::demangleType(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), goalHandleFuture_, and smacc2::SmaccAsyncClientBehavior::isShutdownRequested().
onNavigationActionAbort()
void cl_nitrosz::CbNav2ZClientBehaviorBase::onNavigationActionAbort (const ClNitrosZ::WrappedResult & r) protected virtual
Definition at line 112 of file cb_nitrosz_client_behavior_base.cpp.
{
  // if (!isOwnActionResponse(r))
  // {
  //   RCLCPP_WARN(
  //     getLogger(), "[%s] Propagating success event skipped. Action response is not ours.",
  //     getName().c_str());
  //   return;
  // }
  navigationResult_ = r.code;
  auto name = getName();
  RCLCPP_INFO(getLogger(), "[%s] Propagating failure event from action server", name.c_str());
  this->postFailureEvent();
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), navigationResult_, and smacc2::SmaccAsyncClientBehavior::postFailureEvent().
Referenced by onNavigationResult().
onNavigationActionSuccess()
void cl_nitrosz::CbNav2ZClientBehaviorBase::onNavigationActionSuccess (const ClNitrosZ::WrappedResult & r) protected virtual
Reimplemented in cl_nitrosz::CbNavigateNextWaypointUntilReached.
Definition at line 96 of file cb_nitrosz_client_behavior_base.cpp.
{
  // if (!isOwnActionResponse(r))
  // {
  //   RCLCPP_WARN(
  //     getLogger(), "[%s] Propagating success event skipped. Action response is not ours.",
  //     getName().c_str());
  //   return;
  // }
  navigationResult_ = r.code;
  RCLCPP_INFO(getLogger(), "[%s] Propagating success event from action server", getName().c_str());
  this->postSuccessEvent();
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), navigationResult_, and smacc2::SmaccAsyncClientBehavior::postSuccessEvent().
Referenced by onNavigationResult().
onNavigationResult()
void cl_nitrosz::CbNav2ZClientBehaviorBase::onNavigationResult (const ClNitrosZ::WrappedResult & r) protected virtual
Definition at line 81 of file cb_nitrosz_client_behavior_base.cpp.
{
  RCLCPP_DEBUG(
    getLogger(), "[%s] Received result event from action server, result code", getName().c_str());
  if (r.code == rclcpp_action::ResultCode::SUCCEEDED)
  {
    this->onNavigationActionSuccess(r);
  }
  else
  {
    this->onNavigationActionAbort(r);
  }
}
References smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), onNavigationActionAbort(), and onNavigationActionSuccess().
Referenced by cl_nitrosz::CbNavigateNextWaypoint::onEntry(), and sendGoal().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_nitrosz::CbNav2ZClientBehaviorBase::onOrthogonalAllocation () inline
Definition at line 34 of file cb_nitrosz_client_behavior_base.hpp.
  {
    this->requiresClient(nitroszClient_);
    smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
  }
References nitroszClient_, and smacc2::ISmaccClientBehavior::requiresClient().
sendGoal()
void cl_nitrosz::CbNav2ZClientBehaviorBase::sendGoal (ClNitrosZ::Goal & goal) protected
Definition at line 26 of file cb_nitrosz_client_behavior_base.cpp.
{
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] Creating sending goal callback signal.");
  this->navigationCallback_ = std::make_shared<cl_nitrosz::ClNitrosZ::SmaccNavigateResultSignal>();
  this->getStateMachine()->createSignalConnection(
    *navigationCallback_, &CbNav2ZClientBehaviorBase::onNavigationResult, this);
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] Sending goal");
  goalHandleFuture_ = this->nitroszClient_->sendGoal(goal, navigationCallback_);
  RCLCPP_INFO_STREAM(
    getLogger(), "[" << getName() << "] Goal set, future valid: " << goalHandleFuture_.valid());
  // this->goal_uuid_ = gh.get_goal_id () ;
}
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::getStateMachine(), goalHandleFuture_, navigationCallback_, nitroszClient_, onNavigationResult(), and smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
Referenced by cl_nitrosz::CbNavigateGlobalPosition::execute(), cl_nitrosz::CbAbsoluteRotate::onEntry(), cl_nitrosz::CbNavigateBackwards::onEntry(), cl_nitrosz::CbNavigateForward::onEntry(), cl_nitrosz::CbRotate::onEntry(), and cl_nitrosz::CbUndoPathBackwards::onEntry().
Member Data Documentation
goalHandleFuture_
std::shared_future< std::shared_ptr<rclcpp_action::ClientGoalHandle<nav2_msgs::action::NavigateToPose> > > cl_nitrosz::CbNav2ZClientBehaviorBase::goalHandleFuture_ protected
Definition at line 58 of file cb_nitrosz_client_behavior_base.hpp.
Referenced by isOwnActionResponse(), and sendGoal().
navigationCallback_
cl_nitrosz::ClNitrosZ::SmaccNavigateResultSignal::SharedPtr cl_nitrosz::CbNav2ZClientBehaviorBase::navigationCallback_ protected
Definition at line 52 of file cb_nitrosz_client_behavior_base.hpp.
Referenced by sendGoal().
navigationResult_
rclcpp_action::ResultCode cl_nitrosz::CbNav2ZClientBehaviorBase::navigationResult_ protected
Definition at line 55 of file cb_nitrosz_client_behavior_base.hpp.
Referenced by cl_nitrosz::CbUndoPathBackwards::onExit(), onNavigationActionAbort(), onNavigationActionSuccess(), and cl_nitrosz::CbNavigateNextWaypointUntilReached::onNavigationActionSuccess().
nitroszClient_
cl_nitrosz::ClNitrosZ* cl_nitrosz::CbNav2ZClientBehaviorBase::nitroszClient_ protected
Definition at line 51 of file cb_nitrosz_client_behavior_base.hpp.
Referenced by cancelGoal(), cl_nitrosz::CbNavigateGlobalPosition::execute(), cl_nitrosz::CbAbsoluteRotate::onEntry(), cl_nitrosz::CbNavigateBackwards::onEntry(), cl_nitrosz::CbNavigateForward::onEntry(), cl_nitrosz::CbNavigateGlobalPosition::onEntry(), cl_nitrosz::CbNavigateNamedWaypoint::onEntry(), cl_nitrosz::CbNavigateNextWaypoint::onEntry(), cl_nitrosz::CbRotate::onEntry(), cl_nitrosz::CbUndoPathBackwards::onEntry(), cl_nitrosz::CbUndoPathBackwards::onExit(), cl_nitrosz::CbNavigateNextWaypointUntilReached::onNavigationActionSuccess(), cl_nitrosz::CbNavigateNextWaypointUntilReached::onOrthogonalAllocation(), onOrthogonalAllocation(), and sendGoal().
The documentation for this class was generated from the following files:
smacc2_client_library/nitrosz_client/nitrosz_client/include/nitrosz_client/client_behaviors/cb_nitrosz_client_behavior_base.hpp
smacc2_client_library/nitrosz_client/nitrosz_client/src/nitrosz_client/client_behaviors/cb_nitrosz_client_behavior_base.cpp