SMACC2: smacc2::Orthogonal< TOrthogonal > Class Template Reference
smacc2::Orthogonal< TOrthogonal > Class Template Reference
#include <smacc_orthogonal_impl.hpp>
Public Member Functions
template<typename TClient , typename... TArgs>
std::shared_ptr< ClientHandler< TOrthogonal, TClient > > createClient (TArgs... args)
Public Member Functions inherited from smacc2::ISmaccOrthogonal
void setStateMachine (ISmaccStateMachine *value)
ISmaccStateMachine * getStateMachine ()
void initState (ISmaccState *state)
void addClientBehavior (std::shared_ptr< smacc2::ISmaccClientBehavior > clientBehavior)
void runtimeConfigure ()
void onEntry ()
void onExit ()
void onDispose ()
virtual std::string getName () const
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
bool requiresClient (SmaccClientType *&storage)
const std::vector< std::shared_ptr< smacc2::ISmaccClient > > & getClients ()
const std::vector< std::vector< std::shared_ptr< smacc2::ISmaccClientBehavior > > > & getClientBehaviors () const
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename TClientBehavior >
TClientBehavior * getClientBehavior (int index=0)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccOrthogonal
virtual void onInitialize ()
void initializeClients ()
template<typename TOrthogonal , typename TClient >
void assignClientToOrthogonal (TClient *client)
Protected Attributes inherited from smacc2::ISmaccOrthogonal
std::vector< std::shared_ptr< smacc2::ISmaccClient > > clients_
Detailed Description
template<typename TOrthogonal>
class smacc2::Orthogonal< TOrthogonal >
Definition at line 166 of file smacc_orthogonal_impl.hpp.
Member Function Documentation
createClient()
template<typename TOrthogonal > template<typename TClient , typename... TArgs> std::shared_ptr< ClientHandler< TOrthogonal, TClient > > smacc2::Orthogonal< TOrthogonal >::createClient (TArgs... args) inline
Definition at line 170 of file smacc_orthogonal_impl.hpp.
  {
    //static_assert(std::is_base_of<ISmaccOrthogonal, TOrthogonal>::value, "The object Tag must be the orthogonal type where the client was created");
    // if (typeid(*this) != typeid(TOrthogonal))
    // {
    //     RCLCPP_ERROR_STREAM(getLogger(),"Error creating client. The object Tag must be the type of the orthogonal where the client was created:" << demangleType(typeid(*this)) << ". The object creation was skipped and a nullptr was returned");
    //     return nullptr;
    // }
    RCLCPP_INFO(
      getLogger(), "[%s] creating client object, type:'%s' object tag: '%s'",
      demangleType(typeid(*this)).c_str(), demangledTypeName<TClient>().c_str(),
      demangledTypeName<TOrthogonal>().c_str());
    auto client = std::make_shared<ClientHandler<TOrthogonal, TClient>>(args...);
    this->template assignClientToOrthogonal<TOrthogonal, TClient>(client.get());
    // it is stored the client (not the client handler)
    clients_.push_back(client);
    return client;
  }
References smacc2::ISmaccOrthogonal::assignClientToOrthogonal(), smacc2::ISmaccOrthogonal::clients_, smacc2::introspection::demangledTypeName(), smacc2::introspection::demangleType(), and smacc2::ISmaccOrthogonal::getLogger().
The documentation for this class was generated from the following file:
smacc2/include/smacc2/impl/smacc_orthogonal_impl.hpp