SMACC2: cl_http::ClHttp::Server Class Reference
cl_http::ClHttp::Server Class Reference
Public Member Functions
Server (const std::string &server_name)
bool isSSL () const
std::string getPort () const
std::string getServerName () const
Private Attributes
std::string server_name_
bool ssl_
Detailed Description
Definition at line 44 of file http_client.hpp.
Constructor & Destructor Documentation
Server()
cl_http::ClHttp::Server::Server (const std::string & server_name) inline explicit
Definition at line 47 of file http_client.hpp.
                                                   : server_name_{server_name}, ssl_{true}
    {
      if (!server_name_.substr(0, 7).compare("http://"))
      {
        ssl_ = false;
        server_name_.erase(0, 7);
      }
      else if (!server_name_.substr(0, 8).compare("https://"))
      {
        server_name_.erase(0, 8);
        ssl_ = true;
      }
    }
References server_name_, and ssl_.
Member Function Documentation
getPort()
std::string cl_http::ClHttp::Server::getPort () const inline
Definition at line 63 of file http_client.hpp.
{ return ssl_ ? "443" : "80"; }
References ssl_.
Referenced by cl_http::ClHttp::makeRequest().
getServerName()
std::string cl_http::ClHttp::Server::getServerName () const inline
Definition at line 65 of file http_client.hpp.
{ return server_name_; }
References server_name_.
Referenced by cl_http::ClHttp::makeRequest().
isSSL()
bool cl_http::ClHttp::Server::isSSL () const inline
Definition at line 61 of file http_client.hpp.
{ return ssl_; }
References ssl_.
Referenced by cl_http::ClHttp::makeRequest().
Member Data Documentation
server_name_
std::string cl_http::ClHttp::Server::server_name_ private
Definition at line 68 of file http_client.hpp.
Referenced by getServerName(), and Server().
ssl_
bool cl_http::ClHttp::Server::ssl_ private
Definition at line 69 of file http_client.hpp.
Referenced by getPort(), isSSL(), and Server().
The documentation for this class was generated from the following file:
smacc2_client_library/http_client/include/http_client/http_client.hpp