SMACC2: CpOdomTrackerActionServer Class Reference
CpOdomTrackerActionServer Class Reference
Public Member Functions
CpOdomTrackerActionServer ()
void execute (const CpOdomTrackerGoalConstPtr &goal)
void run ()
Public Attributes
std::shared_ptr< Server > as_
CpOdomTracker odomTracker
Detailed Description
Definition at line 30 of file cp_odom_tracker_node.cpp.
Constructor & Destructor Documentation
CpOdomTrackerActionServer()
CpOdomTrackerActionServer::CpOdomTrackerActionServer () inline
Definition at line 36 of file cp_odom_tracker_node.cpp.
: odomTracker("move_base") {}
Member Function Documentation
execute()
void CpOdomTrackerActionServer::execute (const CpOdomTrackerGoalConstPtr & goal) inline
execute()
Definition at line 43 of file cp_odom_tracker_node.cpp.
  {
    try
    {
      switch (goal->command)
      {
        case CpOdomTrackerGoal::RECORD_PATH:
          odomTracker.setWorkingMode(WorkingMode::RECORD_PATH);
          break;
        case CpOdomTrackerGoal::CLEAR_PATH:
          odomTracker.setWorkingMode(WorkingMode::CLEAR_PATH);
          break;
        case CpOdomTrackerGoal::IDLE:
          odomTracker.setWorkingMode(WorkingMode::IDLE);
          break;
        case CpOdomTrackerGoal::START_BROADCAST_PATH:
          odomTracker.setPublishMessages(true);
          break;
        case CpOdomTrackerGoal::STOP_BROADCAST_PATH:
          odomTracker.setPublishMessages(false);
          break;
        case CpOdomTrackerGoal::PUSH_PATH:
          odomTracker.pushPath();
          break;
        case CpOdomTrackerGoal::POP_PATH:
          odomTracker.popPath();
          break;
        default:
          RCLCPP_ERROR(
            getLogger(), "Odom Tracker Node - Action Server execute error: incorrect command - %d",
            goal->command);
          as_->setAborted();
      }
      // never reach succeeded because were are interested in keeping the feedback alive
      as_->setSucceeded();
    }
    catch (std::exception & ex)
    {
      RCLCPP_ERROR(getLogger(), "Odom Tracker Node - Action Server execute error: %s", ex.what());
      as_->setAborted();
    }
  }
References as_, odomTracker, cl_nav2z::odom_tracker::CpOdomTracker::popPath(), cl_nav2z::odom_tracker::CpOdomTracker::pushPath(), cl_nav2z::odom_tracker::CpOdomTracker::setPublishMessages(), and cl_nav2z::odom_tracker::CpOdomTracker::setWorkingMode().
Referenced by run().
run()
void CpOdomTrackerActionServer::run () inline
run()
Definition at line 101 of file cp_odom_tracker_node.cpp.
  {
    rclcpp::Node::SharedPtr n;
    RCLCPP_INFO(getLogger(), "Creating odom tracker action server");
    as_ = std::make_shared<Server>(
      n, "odom_tracker",
      std::bind(&CpOdomTrackerActionServer::execute, this, std::placeholders::_1), false);
    RCLCPP_INFO(getLogger(), "Starting CpOdomTracker Action Server");
    as_->start();
    ros::spin();
  }
References as_, and execute().
Referenced by main().
Member Data Documentation
as_
std::shared_ptr<Server> CpOdomTrackerActionServer::as_
Definition at line 33 of file cp_odom_tracker_node.cpp.
Referenced by execute(), and run().
odomTracker
CpOdomTracker CpOdomTrackerActionServer::odomTracker
Definition at line 34 of file cp_odom_tracker_node.cpp.
Referenced by execute().
The documentation for this class was generated from the following file:
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/components/odom_tracker/cp_odom_tracker_node.cpp