SMACC2: sm_dance_bot::cl_string_publisher::CbStringPublisher Class Reference
sm_dance_bot::cl_string_publisher::CbStringPublisher Class Reference
#include <cb_string_publisher.hpp>
Public Member Functions
CbStringPublisher (std::string msg)
virtual void runtimeConfigure () override
virtual void onEntry ()
void onExit () override
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Attributes
ClStringPublisher * publisherClient_
std::string msg_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 31 of file cb_string_publisher.hpp.
Constructor & Destructor Documentation
CbStringPublisher()
sm_dance_bot::cl_string_publisher::CbStringPublisher::CbStringPublisher (std::string msg) inline
Definition at line 37 of file cb_string_publisher.hpp.
{ msg_ = msg; }
References msg_.
Member Function Documentation
onEntry()
virtual void sm_dance_bot::cl_string_publisher::CbStringPublisher::onEntry () inline virtual
Reimplemented from smacc2::SmaccClientBehavior.
Definition at line 45 of file cb_string_publisher.hpp.
{ this->requiresClient(publisherClient_); }
References smacc2::ISmaccClientBehavior::requiresClient().
onExit()
void sm_dance_bot::cl_string_publisher::CbStringPublisher::onExit () inline override virtual
Reimplemented from smacc2::SmaccClientBehavior.
Definition at line 47 of file cb_string_publisher.hpp.
  {
    std_msgs::msg::String rosmsg;
    rosmsg.data = msg_;
    publisherClient_->publish(rosmsg);
  }
References msg_, smacc2::client_bases::SmaccPublisherClient::publish(), and publisherClient_.
runtimeConfigure()
virtual void sm_dance_bot::cl_string_publisher::CbStringPublisher::runtimeConfigure () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 39 of file cb_string_publisher.hpp.
  {
    RCLCPP_INFO_STREAM(
      getLogger(), "Creating CbStringPublisher behavior with stored message: " << msg_);
  }
References smacc2::ISmaccClientBehavior::getLogger(), and msg_.
Member Data Documentation
msg_
std::string sm_dance_bot::cl_string_publisher::CbStringPublisher::msg_
Definition at line 35 of file cb_string_publisher.hpp.
Referenced by CbStringPublisher(), onExit(), and runtimeConfigure().
publisherClient_
ClStringPublisher* sm_dance_bot::cl_string_publisher::CbStringPublisher::publisherClient_
Definition at line 34 of file cb_string_publisher.hpp.
Referenced by onExit().
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_dance_bot/include/sm_dance_bot/clients/cl_string_publisher/client_behaviors/cb_string_publisher.hpp