SMACC2: smacc2::introspection Namespace Reference
smacc2::introspection Namespace Reference
Classes
struct add_type_wrapper
struct AddSubState
struct AddTransition
struct CheckType
class ClientBehaviorHandler
struct ClientBehaviorInfoEntry
struct EventGeneratorCallbackFunctor
class EventGeneratorHandler
class HasAutomaticTransitionTag
class HasAutomaticTransitionType
class HasEventLabel
class HasOnDefinition
struct SmaccEventGeneratorInfo
struct SmaccEventInfo
class SmaccStateInfo
class SmaccStateMachineInfo
struct SmaccStateReactorInfo
struct SmaccTransitionInfo
struct StateReactorCallbackFunctor
class StateReactorHandler
struct type_
class TypeInfo
struct typelist
struct WalkStatesExecutor
Typedefs
typedef std::allocator< boost::statechart::none > SmaccAllocator
typedef boost::mpl::list< SUCCESS, ABORT, CANCEL, CONTINUELOOP, ENDLOOP > DEFAULT_TRANSITION_TYPES
Enumerations
enum class SmaccStateType { SUPERSTATE = 2 , STATE = 1 , SUPERSTATE_ROUTINE = 1 }
Functions
void transitionInfoToMsg (const SmaccTransitionInfo &transition, smacc2_msgs::msg::SmaccTransition &transitionMsg)
template<class T >
auto optionalNodeHandle (std::shared_ptr< T > &obj) -> T *
template<class T >
auto optionalNodeHandle (boost::intrusive_ptr< T > &obj) -> T *
template<class T >
auto optionalNodeHandle (T *obj) -> T *
std::string demangleSymbol (const std::string &name)
std::string demangleSymbol (const char *name)
template<typename T >
std::string demangleSymbol ()
template<class T >
std::string demangledTypeName ()
std::string demangleType (const std::type_info *tinfo)
std::string demangleType (const std::type_info &tinfo)
template<typename T >
std::enable_if< HasEventLabel< T >::value, void >::type EventLabel (std::string &label)
template<typename T >
std::enable_if<!HasEventLabel< T >::value, void >::type EventLabel (std::string &label)
template<typename T >
std::enable_if< HasAutomaticTransitionTag< T >::value, void >::type automaticTransitionTag (std::string &transition_name)
template<typename T >
std::enable_if<!HasAutomaticTransitionTag< T >::value, void >::type automaticTransitionTag (std::string &transition_name)
template<typename T >
std::enable_if< HasAutomaticTransitionType< T >::value, void >::type automaticTransitionType (std::string &transition_type)
template<typename T >
std::enable_if<!HasAutomaticTransitionType< T >::value, void >::type automaticTransitionType (std::string &transition_type)
template<typename TTransition >
static std::string getTransitionType ()
template<typename T >
disable_if< boost::mpl::is_sequence< T > >::type processSubState (std::shared_ptr< SmaccStateInfo > &parentState)
template<typename T >
enable_if< boost::mpl::is_sequence< T > >::type processSubState (std::shared_ptr< SmaccStateInfo > &parentState)
template<typename T >
enable_if< boost::mpl::is_sequence< T > >::type processTransitions (std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev , typename Dst , typename Tag >
void processTransition (smacc2::Transition< Ev, boost::statechart::deep_history< Dst >, Tag > *, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev , typename Dst , typename Tag >
void processTransition (smacc2::Transition< Ev, Dst, Tag > *t, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev , typename Dst , typename Tag >
void processTransitionAux (smacc2::Transition< Ev, Dst, Tag > *, std::shared_ptr< SmaccStateInfo > &sourceState, bool history, TypeInfo::Ptr &transitionTypeInfo)
template<typename Ev , typename Dst >
void processTransition (statechart::transition< Ev, Dst > *, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename Ev >
void processTransition (statechart::custom_reaction< Ev > *, std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename T >
disable_if< boost::mpl::is_sequence< T > >::type processTransitions (std::shared_ptr< SmaccStateInfo > &sourceState)
template<typename T >
std::enable_if< HasOnDefinition< T >::value, void >::type CallOnDefinition ()
template<typename T >
std::enable_if<!HasOnDefinition< T >::value, void >::type CallOnDefinition ()
bool replace (std::string &str, const std::string &from, const std::string &to)
std::string replace_back (std::string roottype, std::vector< std::pair< std::string, std::string > > &orderedtypesdict)
Variables
rclcpp::Node::SharedPtr globalNh_
Typedef Documentation
DEFAULT_TRANSITION_TYPES
typedef boost::mpl::list<SUCCESS, ABORT, CANCEL, CONTINUELOOP, ENDLOOP> smacc2::introspection::DEFAULT_TRANSITION_TYPES
Definition at line 223 of file introspection.hpp.
SmaccAllocator
typedef std::allocator<boost::statechart::none> smacc2::introspection::SmaccAllocator
Definition at line 52 of file introspection.hpp.
Enumeration Type Documentation
SmaccStateType
enum class smacc2::introspection::SmaccStateType strong
Enumerator
SUPERSTATE
STATE
SUPERSTATE_ROUTINE
Definition at line 164 of file smacc_state_info.hpp.
{
  SUPERSTATE = 2,
  STATE = 1,
  SUPERSTATE_ROUTINE = 1
};
Function Documentation
automaticTransitionTag() [1/2]
template<typename T > std::enable_if< HasAutomaticTransitionTag< T >::value, void >::type smacc2::introspection::automaticTransitionTag (std::string & transition_name)
Definition at line 174 of file introspection.hpp.
{
  transition_name = T::getDefaultTransitionTag();
}
Referenced by processTransitionAux().
automaticTransitionTag() [2/2]
template<typename T > std::enable_if<!HasAutomaticTransitionTag< T >::value, void >::type smacc2::introspection::automaticTransitionTag (std::string & transition_name)
Definition at line 181 of file introspection.hpp.
{
  transition_name = "";
}
automaticTransitionType() [1/2]
template<typename T > std::enable_if< HasAutomaticTransitionType< T >::value, void >::type smacc2::introspection::automaticTransitionType (std::string & transition_type)
Definition at line 208 of file introspection.hpp.
{
  transition_type = T::getDefaultTransitionType();
}
Referenced by processTransitionAux().
automaticTransitionType() [2/2]
template<typename T > std::enable_if<!HasAutomaticTransitionType< T >::value, void >::type smacc2::introspection::automaticTransitionType (std::string & transition_type)
Definition at line 215 of file introspection.hpp.
{
  transition_type = demangledTypeName<DEFAULT>();
}
References demangledTypeName().
CallOnDefinition() [1/2]
template<typename T > std::enable_if< HasOnDefinition< T >::value, void >::type smacc2::introspection::CallOnDefinition ()
Definition at line 348 of file smacc_state_machine_info.hpp.
{
  /* something when T has toString ... */
  RCLCPP_INFO_STREAM(
    globalNh_->get_logger(), "EXECUTING ONDEFINITION: " << demangleSymbol(typeid(T).name()));
  T::staticConfigure();
}
References demangleSymbol(), and globalNh_.
Referenced by smacc2::introspection::WalkStatesExecutor< InitialStateType >::walkStates().
CallOnDefinition() [2/2]
template<typename T > std::enable_if<!HasOnDefinition< T >::value, void >::type smacc2::introspection::CallOnDefinition ()
Definition at line 357 of file smacc_state_machine_info.hpp.
{
  RCLCPP_INFO_STREAM(
    globalNh_->get_logger(),
    "static OnDefinition: dont exist for " << demangleSymbol(typeid(T).name()));
  /* something when T has toString ... */
}
References demangleSymbol(), and globalNh_.
demangledTypeName()
template<class T > std::string smacc2::introspection::demangledTypeName () inline
Definition at line 101 of file introspection.hpp.
{
  return demangleSymbol(typeid(T).name());
}
References demangleSymbol().
Referenced by smacc2::introspection::StateReactorHandler::addInputEvent(), automaticTransitionType(), smacc2::ISmaccState::configure(), smacc2::Orthogonal< TOrthogonal >::createClient(), smacc2::ISmaccClient::createNamedComponent(), smacc2::ISmaccStateMachine::createOrthogonal(), smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::introspection::SmaccStateMachineInfo::createState(), smacc2::introspection::SmaccStateInfo::declareTransition(), smacc2::default_events::EvActionAborted< TSource, TOrthogonal >::getDefaultTransitionTag(), smacc2::default_events::EvActionCancelled< TSource, TOrthogonal >::getDefaultTransitionTag(), smacc2::default_events::EvActionSucceeded< TSource, TOrthogonal >::getDefaultTransitionTag(), smacc2::default_events::EvLoopContinue< TSource >::getDefaultTransitionTag(), smacc2::default_events::EvLoopEnd< TSource >::getDefaultTransitionTag(), smacc2::default_events::EvActionAborted< TSource, TOrthogonal >::getDefaultTransitionType(), smacc2::default_events::EvActionCancelled< TSource, TOrthogonal >::getDefaultTransitionType(), smacc2::default_events::EvActionSucceeded< TSource, TOrthogonal >::getDefaultTransitionType(), smacc2::default_events::EvLoopContinue< TSource >::getDefaultTransitionType(), smacc2::default_events::EvLoopEnd< TSource >::getDefaultTransitionType(), smacc2::ISmaccStateMachine::getOrthogonal(), smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onEntry(), smacc2::introspection::CheckType< TTransition >::operator()(), smacc2::ISmaccOrthogonal::requiresClient(), smacc2::introspection::StateReactorHandler::setOutputEvent(), smacc2::client_bases::SmaccActionClientBase< ActionType >::waitForServer(), and smacc2::introspection::WalkStatesExecutor< InitialStateType >::walkStates().
demangleSymbol() [1/3]
template<typename T > std::string smacc2::introspection::demangleSymbol () inline
Definition at line 95 of file introspection.hpp.
{
  return demangleSymbol(typeid(T).name());
}
References demangleSymbol().
Referenced by smacc2::introspection::SmaccStateMachineInfo::assembleSMStructureMessage(), CallOnDefinition(), smacc2::introspection::SmaccStateInfo::createChildState(), smacc2::ISmaccStateMachine::createSignalConnection(), demangledTypeName(), demangleSymbol(), demangleSymbol(), demangleType(), demangleType(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal(), smacc2::ISmaccState::getClassName(), smacc2::introspection::SmaccStateInfo::getDemangledFullName(), cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::getEventLabel(), smacc2::introspection::SmaccEventInfo::getEventSourceName(), smacc2::introspection::SmaccEventInfo::getEventTypeName(), smacc2::introspection::TypeInfo::getFromStdTypeInfo(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getFullName(), smacc2::ISmaccClient::getName(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccComponent::getName(), smacc2::ISmaccOrthogonal::getName(), smacc2::introspection::SmaccEventInfo::getOrthogonalName(), smacc2::ISmaccStateMachine::getStateMachineName(), smacc2::ISmaccStateMachine::mapBehavior(), smacc2::ISmaccStateMachine::notifyOnStateEntryEnd(), smacc2::ISmaccStateMachine::notifyOnStateEntryStart(), smacc2::ISmaccStateMachine::notifyOnStateExited(), smacc2::ISmaccStateMachine::notifyOnStateExitting(), cl_moveit2z::CbMoveEndEffectorTrajectory::onEntry(), cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onEntry(), smacc2::state_reactors::SrAllEventsGo::onEventNotified(), smacc2::state_reactors::SrEventCountdown::onEventNotified(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onInitialize(), cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onOrthogonalAllocation(), smacc2::ISmaccStateMachine::postEvent(), cl_keyboard::CbDefaultKeyboardBehavior::postKeyEvent(), cl_keyboard::ClKeyboard::postKeyEvent(), smacc2::client_bases::SmaccActionClientBase< ActionType >::postResultEvent(), processTransition(), processTransitionAux(), smacc2::ISmaccStateMachine::propagateEventToStateReactors(), smacc2::ISmaccState::requiresClient(), smacc2::ISmaccComponent::requiresComponent(), smacc2::ISmaccComponent::requiresComponent(), smacc2::ISmaccStateMachine::requiresComponent(), smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), smacc2::StateReactor::setOutputEvent(), and smacc2::client_behaviors::CbSequence::then().
demangleSymbol() [2/3]
std::string smacc2::introspection::demangleSymbol (const char * name) inline
Definition at line 76 of file introspection.hpp.
{
#if (__GNUC__ && __cplusplus && __GNUC__ >= 3)
  int status;
  char * res = abi::__cxa_demangle(name, 0, 0, &status);
  if (res)
  {
    const std::string demangled_name(res);
    std::free(res);
    return demangled_name;
  }
  // Demangling failed, fallback to mangled name
  return std::string(name);
#else
  return std::string(name);
#endif
}
demangleSymbol() [3/3]
std::string smacc2::introspection::demangleSymbol (const std::string & name) inline
Definition at line 74 of file introspection.hpp.
{ return demangleSymbol(name.c_str()); }
References demangleSymbol().
demangleType() [1/2]
std::string smacc2::introspection::demangleType (const std::type_info & tinfo) inline
Definition at line 111 of file introspection.hpp.
{
  return demangleSymbol(tinfo.name());
}
References demangleSymbol().
demangleType() [2/2]
std::string smacc2::introspection::demangleType (const std::type_info * tinfo) inline
Definition at line 106 of file introspection.hpp.
{
  return demangleSymbol(tinfo->name());
}
References demangleSymbol().
Referenced by smacc2::Orthogonal< TOrthogonal >::createClient(), smacc2::SignalDetector::findUpdatableClientsAndComponents(), smacc2::SignalDetector::findUpdatableStateElements(), cl_nav2z::CbNav2ZClientBehaviorBase::isOwnActionResponse(), smacc2::client_behaviors::CbSequence::onEntry(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), and smacc2::SignalDetector::pollOnce().
EventLabel() [1/2]
template<typename T > std::enable_if< HasEventLabel< T >::value, void >::type smacc2::introspection::EventLabel (std::string & label)
Definition at line 142 of file introspection.hpp.
{
  label = T::getEventLabel();
}
Referenced by smacc2::introspection::StateReactorHandler::addInputEvent(), smacc2::introspection::SmaccStateInfo::declareTransition(), smacc2::default_events::EvActionAborted< TSource, TOrthogonal >::getEventLabel(), smacc2::default_events::EvActionCancelled< TSource, TOrthogonal >::getEventLabel(), smacc2::default_events::EvActionSucceeded< TSource, TOrthogonal >::getEventLabel(), and smacc2::AddTEventTypeStateReactorInfo< TEventList >::operator()().
EventLabel() [2/2]
template<typename T > std::enable_if<!HasEventLabel< T >::value, void >::type smacc2::introspection::EventLabel (std::string & label)
Definition at line 148 of file introspection.hpp.
{
  label = "";
}
getTransitionType()
template<typename TTransition > static std::string smacc2::introspection::getTransitionType () static
Definition at line 259 of file introspection.hpp.
{
  std::string output;
  CheckType<TTransition> op(&output);
  using boost::mpl::_1;
  using wrappedList = typename boost::mpl::transform<DEFAULT_TRANSITION_TYPES, _1>::type;
  boost::mpl::for_each<wrappedList>(op);
  return output;
}
Referenced by processTransitionAux().
optionalNodeHandle() [1/3]
template<class T > auto smacc2::introspection::optionalNodeHandle (boost::intrusive_ptr< T > & obj) -> T *
Definition at line 62 of file introspection.hpp.
{
  //return obj->getNode();
  return obj.get();
}
optionalNodeHandle() [2/3]
template<class T > auto smacc2::introspection::optionalNodeHandle (std::shared_ptr< T > & obj) -> T *
Definition at line 55 of file introspection.hpp.
{
  //return obj->getNode();
  return obj.get;
}
optionalNodeHandle() [3/3]
template<class T > auto smacc2::introspection::optionalNodeHandle (T * obj) -> T *
Definition at line 69 of file introspection.hpp.
{
  return obj;
}
processSubState() [1/2]
template<typename T > disable_if< boost::mpl::is_sequence< T > >::type smacc2::introspection::processSubState (std::shared_ptr< SmaccStateInfo > & parentState)
Definition at line 141 of file smacc_state_machine_info.hpp.
{
  WalkStatesExecutor<T>::walkStates(parentState, false);
}
References smacc2::introspection::WalkStatesExecutor< InitialStateType >::walkStates().
Referenced by smacc2::introspection::WalkStatesExecutor< InitialStateType >::walkStates().
processSubState() [2/2]
template<typename T > enable_if< boost::mpl::is_sequence< T > >::type smacc2::introspection::processSubState (std::shared_ptr< SmaccStateInfo > & parentState)
Definition at line 149 of file smacc_state_machine_info.hpp.
{
  using boost::mpl::_1;
  using wrappedList = typename boost::mpl::transform<T, add_type_wrapper<_1>>::type;
  boost::mpl::for_each<wrappedList>(AddSubState(parentState));
}
processTransition() [1/4]
template<typename Ev , typename Dst , typename Tag > void smacc2::introspection::processTransition (smacc2::Transition< Ev, boost::statechart::deep_history< Dst >, Tag > * , std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 172 of file smacc_state_machine_info.hpp.
{
  auto transitionTypeInfo = TypeInfo::getTypeInfoFromType<
    smacc2::Transition<Ev, boost::statechart::deep_history<Dst>, Tag>>();
  smacc2::Transition<Ev, Dst, Tag> * mock = nullptr;
  processTransitionAux(mock, sourceState, true, transitionTypeInfo);
}
References smacc2::introspection::TypeInfo::getTypeInfoFromType(), and processTransitionAux().
Referenced by processTransitions().
processTransition() [2/4]
template<typename Ev , typename Dst , typename Tag > void smacc2::introspection::processTransition (smacc2::Transition< Ev, Dst, Tag > * t, std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 183 of file smacc_state_machine_info.hpp.
{
  auto transitionTypeInfo = TypeInfo::getTypeInfoFromType<smacc2::Transition<Ev, Dst, Tag>>();
  RCLCPP_INFO(
    globalNh_->get_logger(), "State %s Walker transition: %s", sourceState->toShortName().c_str(),
    demangleSymbol(typeid(Ev).name()).c_str());
  processTransitionAux(t, sourceState, false, transitionTypeInfo);
}
References demangleSymbol(), smacc2::introspection::TypeInfo::getTypeInfoFromType(), globalNh_, and processTransitionAux().
processTransition() [3/4]
template<typename Ev > void smacc2::introspection::processTransition (statechart::custom_reaction< Ev > * , std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 328 of file smacc_state_machine_info.hpp.
{
  // RCLCPP_INFO_STREAM(getLogger(),"GOTCHA");
}
processTransition() [4/4]
template<typename Ev , typename Dst > void smacc2::introspection::processTransition (statechart::transition< Ev, Dst > * , std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 321 of file smacc_state_machine_info.hpp.
{
  // RCLCPP_INFO_STREAM(getLogger(),"GOTCHA");
}
processTransitionAux()
template<typename Ev , typename Dst , typename Tag > void smacc2::introspection::processTransitionAux (smacc2::Transition< Ev, Dst, Tag > * , std::shared_ptr< SmaccStateInfo > & sourceState, bool history, TypeInfo::Ptr & transitionTypeInfo)
Definition at line 194 of file smacc_state_machine_info.hpp.
{
  RCLCPP_INFO(
    globalNh_->get_logger(), "State %s Walker transition: %s", sourceState->toShortName().c_str(),
    demangleSymbol(typeid(Ev).name()).c_str());
  std::string transitionTag;
  std::string transitionType;
  if (typeid(Tag) != typeid(default_transition_name))
  {
    transitionTag = demangleSymbol<Tag>();
    transitionType = getTransitionType<Tag>();
    RCLCPP_DEBUG_STREAM(globalNh_->get_logger(), "TRANSITION TYPE:" << transitionType);
  }
  else
  {
    transitionTag = "";
    automaticTransitionTag<Ev>(transitionTag);
    automaticTransitionType<Ev>(transitionType);
  }
  RCLCPP_INFO_STREAM(globalNh_->get_logger(), "Transition tag: " << transitionTag);
  if (!sourceState->stateMachine_->containsState<Dst>())
  {
    auto realparentState = sourceState->stateMachine_->getState<typename Dst::TContext>();
    auto siblingnode = sourceState->stateMachine_->createState<Dst>(realparentState);
    // auto siblingnode = sourceState->stateMachine_->createState<Dst>(sourceState->parentState_);
    WalkStatesExecutor<Dst>::walkStates(siblingnode, true);
    sourceState->declareTransition<Ev>(
      siblingnode, transitionTag, transitionType, history, transitionTypeInfo);
  }
  else
  {
    // auto realparentState = sourceState->stateMachine_->getState<typename Dst::TContext>();
    // auto siblingnode = sourceState->stateMachine_->createState<Dst>(realparentState);
    auto siblingnode = sourceState->stateMachine_->getState<Dst>();
    sourceState->declareTransition<Ev>(
      siblingnode, transitionTag, transitionType, history, transitionTypeInfo);
  }
}
References automaticTransitionTag(), automaticTransitionType(), demangleSymbol(), getTransitionType(), globalNh_, and smacc2::introspection::WalkStatesExecutor< InitialStateType >::walkStates().
Referenced by processTransition(), and processTransition().
processTransitions() [1/2]
template<typename T > enable_if< boost::mpl::is_sequence< T > >::type smacc2::introspection::processTransitions (std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 160 of file smacc_state_machine_info.hpp.
{
  RCLCPP_INFO(
    globalNh_->get_logger(), "State %s Walker has transition list",
    sourceState->fullStateName.c_str());
  using boost::mpl::_1;
  using wrappedList = typename boost::mpl::transform<T, add_type_wrapper<_1>>::type;
  boost::mpl::for_each<wrappedList>(AddTransition(sourceState));
}
References globalNh_.
Referenced by smacc2::introspection::AddTransition::operator()(), smacc2::introspection::AddTransition::operator()(), smacc2::introspection::AddTransition::operator()(), and smacc2::introspection::WalkStatesExecutor< InitialStateType >::walkStates().
processTransitions() [2/2]
template<typename T > disable_if< boost::mpl::is_sequence< T > >::type smacc2::introspection::processTransitions (std::shared_ptr< SmaccStateInfo > & sourceState)
Definition at line 338 of file smacc_state_machine_info.hpp.
{
  // RCLCPP_INFO_STREAM(getLogger(),"state transition from: " << sourceState->demangledStateName <<
  // " of type: " << demangledTypeName<T>());
  T * dummy = nullptr;
  processTransition(dummy, sourceState);
}
References processTransition().
replace()
bool smacc2::introspection::replace (std::string & str, const std::string & from, const std::string & to)
Definition at line 39 of file string_type_walker.cpp.
{
  size_t start_pos = str.find(from);
  if (start_pos == std::string::npos) return false;
  str.replace(start_pos, from.length(), to);
  return true;
}
Referenced by smacc2::introspection::TypeInfo::getTypeInfoFromString(), and replace_back().
replace_back()
std::string smacc2::introspection::replace_back (std::string roottype, std::vector< std::pair< std::string, std::string > > & orderedtypesdict)
Definition at line 47 of file string_type_walker.cpp.
{
  while (roottype.find("$") != std::string::npos)
  {
    for (auto & t : orderedtypesdict)
    {
      auto & tkey = t.first;
      auto & tval = t.second;
      replace(roottype, tkey, tval);
    }
  }
  return roottype;
  //   def replace_back(roottype, typesdict):
  //     # replace back
  //     while "$" in roottype:
  //         #print roottype
  //         for tkey in typesdict:
  //             tval = typesdict[tkey]
  //             roottype = roottype.replace(tkey, tval)
  //     return roottype
}
References replace().
Referenced by smacc2::introspection::TypeInfo::getTypeInfoFromString().
transitionInfoToMsg()
void smacc2::introspection::transitionInfoToMsg (const SmaccTransitionInfo & transition, smacc2_msgs::msg::SmaccTransition & transitionMsg)
Definition at line 30 of file reflection.cpp.
{
  transitionMsg.index = transition.index;
  if (transition.sourceState != nullptr)
  {
    transitionMsg.source_state_name = transition.sourceState->demangledStateName;
  }
  transitionMsg.transition_name = transition.transitionTag;
  transitionMsg.transition_type = transition.transitionType;
  if (transition.eventInfo != nullptr)
  {
    transitionMsg.event.event_type = transition.eventInfo->getEventTypeName();
    transitionMsg.event.event_source = transition.eventInfo->getEventSourceName();
    transitionMsg.event.event_object_tag = transition.eventInfo->getOrthogonalName();
    transitionMsg.event.label = transition.eventInfo->label;
  }
  transitionMsg.history_node = transition.historyNode;
  if (transition.historyNode)
  {
    if (transition.destinyState->parentState_ != nullptr)
    {
      transitionMsg.destiny_state_name = transition.destinyState->parentState_->demangledStateName;
    }
    else
    {
      transitionMsg.destiny_state_name = "";
    }
  }
  else
  {
    transitionMsg.destiny_state_name = transition.destinyState->demangledStateName;
  }
}
References smacc2::introspection::SmaccTransitionInfo::destinyState, smacc2::introspection::SmaccTransitionInfo::eventInfo, smacc2::introspection::SmaccTransitionInfo::historyNode, smacc2::introspection::SmaccTransitionInfo::index, smacc2::introspection::SmaccTransitionInfo::sourceState, smacc2::introspection::SmaccTransitionInfo::transitionTag, and smacc2::introspection::SmaccTransitionInfo::transitionType.
Referenced by smacc2::introspection::SmaccStateMachineInfo::assembleSMStructureMessage(), and smacc2::ISmaccStateMachine::publishTransition().
Variable Documentation
globalNh_
rclcpp::Node::SharedPtr smacc2::introspection::globalNh_
Definition at line 28 of file reflection.cpp.
Referenced by CallOnDefinition(), smacc2::introspection::TypeInfo::getTypeInfoFromString(), smacc2::SmaccStateMachineBase< DerivedStateMachine, InitialStateType >::initiate_impl(), processTransition(), processTransitionAux(), processTransitions(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::static_createStateReactor(), and smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::static_createStateReactor_aux().