SMACC2: cl_nitrosz Namespace Reference
cl_nitrosz Namespace Reference
Namespaces
namespace odom_tracker
Classes
class CbAbortNavigation
class CbAbsoluteRotate
struct CbActiveStop
struct CbLoadWaypointsFile
class CbNav2ZClientBehaviorBase
class CbNavigateBackwards
class CbNavigateForward
struct CbNavigateForwardOptions
class CbNavigateGlobalPosition
struct CbNavigateGlobalPositionOptions
class CbNavigateNamedWaypoint
class CbNavigateNextWaypoint
class CbNavigateNextWaypointFree
class CbNavigateNextWaypointUntilReached
class CbPauseSlam
struct CbPositionControlFreeSpace
struct CbPureSpinning
class CbResumeSlam
class CbRetry
class CbRotate
class CbRotateLookAt
struct CbSaveSlamMap
class CbSeekWaypoint
class CbStopNavigation
class CbUndoPathBackwards
struct CbUndoPathBackwardsOptions
class CbWaitNav2Nodes
class CbWaitPose
class CbWaitTransform
class ClNitrosZ
class CpAmcl
class CpCostmapProxy
class CpCostmapSwitch
class CpGoalCheckerSwitcher
class CpPlannerSwitcher
class CpSlamToolbox
class CpWaypointNavigator
class CpWaypointNavigatorBase
class CpWaypointsVisualizer
struct EvGoalWaypointReached
struct EvWaypointFinal
struct NavigateNextWaypointOptions
class Pose
struct Pose2D
Typedefs
template<typename TService >
using CbServiceCall = smacc2::client_behaviors::CbServiceCall< TService >
typedef smacc2::client_bases::SmaccActionClientBase< nav2_msgs::action::NavigateToPose > Base
typedef Base::WrappedResult WrappedResult
Enumerations
enum class SpinningPlanner { Default , PureSpinning , Forward }
enum class Nav2Nodes {
PlannerServer , ControllerServer , RecoveriesServer , BtNavigator ,
MapServer , None
}
enum class WaitPoseStandardReferenceFrame { Map , Odometry }
enum class StandardReferenceFrames { Map , Odometry }
Functions
std::string toString (Nav2Nodes value)
Nav2Nodes fromString (std::string str)
std::string referenceFrameToString (StandardReferenceFrames referenceFrame)
Variables
const std::string frameid = "map"
Typedef Documentation
Base
typedef smacc2::client_bases::SmaccActionClientBase<nav2_msgs::action::NavigateToPose> cl_nitrosz::Base
Definition at line 28 of file nitrosz_client.cpp.
CbServiceCall
template<typename TService > using cl_nitrosz::CbServiceCall = typedef smacc2::client_behaviors::CbServiceCall<TService>
Definition at line 33 of file cb_save_slam_map.hpp.
WrappedResult
typedef Base::WrappedResult cl_nitrosz::WrappedResult
Definition at line 29 of file nitrosz_client.cpp.
Enumeration Type Documentation
Nav2Nodes
enum class cl_nitrosz::Nav2Nodes strong
Enumerator
PlannerServer
ControllerServer
RecoveriesServer
BtNavigator
MapServer
None
Definition at line 29 of file cb_wait_nitros_nodes.hpp.
{
  PlannerServer,
  ControllerServer,
  RecoveriesServer,
  BtNavigator,
  MapServer,
  None
};
SpinningPlanner
enum class cl_nitrosz::SpinningPlanner strong
Enumerator
Default
PureSpinning
Forward
Definition at line 61 of file cb_nitrosz_client_behavior_base.hpp.
{
  Default,
  PureSpinning,
  Forward
};
StandardReferenceFrames
enum class cl_nitrosz::StandardReferenceFrames strong
Enumerator
Map
Odometry
Definition at line 37 of file cp_pose.hpp.
{
  Map,
  Odometry
};
WaitPoseStandardReferenceFrame
enum class cl_nitrosz::WaitPoseStandardReferenceFrame strong
Enumerator
Map
Odometry
Definition at line 28 of file cb_wait_pose.hpp.
{
  Map,
  Odometry
};
Function Documentation
fromString()
Nav2Nodes cl_nitrosz::fromString (std::string str)
Definition at line 117 of file cb_wait_nitros_nodes.cpp.
{
  if (id == "planner_server")
    return Nav2Nodes::PlannerServer;
  else if (id == "controller_server")
    return Nav2Nodes::ControllerServer;
  else if (id == "behavior_server")
    return Nav2Nodes::RecoveriesServer;
  else if (id == "bt_navigator")
    return Nav2Nodes::BtNavigator;
  else if (id == "map_server")
    return Nav2Nodes::MapServer;
  else
    return Nav2Nodes::None;
}
References BtNavigator, ControllerServer, MapServer, None, PlannerServer, and RecoveriesServer.
Referenced by cl_nitrosz::CbWaitNav2Nodes::onMessageReceived().
referenceFrameToString()
std::string cl_nitrosz::referenceFrameToString (StandardReferenceFrames referenceFrame)
Definition at line 42 of file cp_pose.cpp.
{
  switch (referenceFrame)
  {
    case StandardReferenceFrames::Map:
      return "map";
    case StandardReferenceFrames::Odometry:
      return "odom";
    default:
      return "odom";
  }
}
References Map, and Odometry.
toString()
std::string cl_nitrosz::toString (Nav2Nodes value)
Definition at line 98 of file cb_wait_nitros_nodes.cpp.
{
  switch (value)
  {
    case Nav2Nodes::PlannerServer:
      return "planner_server";
    case Nav2Nodes::ControllerServer:
      return "controller_server";
    case Nav2Nodes::RecoveriesServer:
      return "behavior_server";
    case Nav2Nodes::BtNavigator:
      return "bt_navigator";
    case Nav2Nodes::MapServer:
      return "map_server";
    default:
      return "";
  }
}
References BtNavigator, ControllerServer, MapServer, PlannerServer, and RecoveriesServer.
Referenced by cl_nitrosz::CbWaitNav2Nodes::onEntry(), and cl_nitrosz::CbWaitNav2Nodes::onMessageReceived().
Variable Documentation
frameid
const std::string cl_nitrosz::frameid = "map"
Definition at line 25 of file cp_waypoints_visualizer.cpp.
Referenced by cl_nitrosz::CpWaypointsVisualizer::createMarker(), and cl_nitrosz::CpWaypointsVisualizer::createMarkerLabel().