SMACC2: smacc2::client_bases Namespace Reference
smacc2::client_bases Namespace Reference
Classes
class ClRosLaunch
class ClRosLaunch2
class ISmaccActionClient
struct ProcessInfo
class SmaccActionClientBase
class SmaccPublisherClient
class SmaccServiceClient
class SmaccServiceServerClient
class SmaccSubscriberClient
Functions
ProcessInfo runProcess (const char *command)
void killGrandchildren (pid_t originalPid)
void killProcessesRecursive (pid_t pid)
Function Documentation
killGrandchildren()
void smacc2::client_bases::killGrandchildren (pid_t originalPid)
Definition at line 258 of file smacc_ros_launch_client_2.cpp.
{ killProcessesRecursive(originalPid); }
References killProcessesRecursive().
Referenced by smacc2::client_bases::ClRosLaunch2::executeRosLaunch().
killProcessesRecursive()
void smacc2::client_bases::killProcessesRecursive (pid_t pid)
Definition at line 214 of file smacc_ros_launch_client_2.cpp.
{
  std::string command = "pgrep -P " + std::to_string(pid);
  FILE * pipe = popen(command.c_str(), "r");
  if (!pipe)
  {
    std::cerr << "Error executing pgrep command." << std::endl;
    return;
  }
  char buffer[128];
  std::string result = "";
  while (fgets(buffer, sizeof(buffer), pipe) != NULL)
  {
    result += buffer;
  }
  pclose(pipe);
  std::istringstream iss(result);
  pid_t childPid;
  std::vector<pid_t> childPids;
  while (iss >> childPid)
  {
    childPids.push_back(childPid);
  }
  // Kill child processes before killing the parent process
  for (const pid_t & child : childPids)
  {
    killProcessesRecursive(child);
  }
  // After killing all children, kill the parent process
  int res = kill(pid, SIGTERM);
  if (res == 0)
  {
    RCLCPP_FATAL(rclcpp::get_logger("smacc2"), "Killed process %d", pid);
  }
}
References killProcessesRecursive().
Referenced by killGrandchildren(), and killProcessesRecursive().
runProcess()
ProcessInfo smacc2::client_bases::runProcess (const char * command)
Aditional functions
Definition at line 170 of file smacc_ros_launch_client_2.cpp.
{
  ProcessInfo info;
  info.pid = -1;  // Inicializar el PID a -1 (indicando error)
  info.pipe = nullptr;
  int pipefd[2];  // Descriptor de archivo para el pipe
  if (pipe(pipefd) == -1)
  {
    perror("pipe");
    return info;
  }
  pid_t pid = fork();
  if (pid == 0)
  {
    // Esto se ejecuta en el proceso hijo
    close(pipefd[0]);                // Cerramos el extremo de lectura del pipe en el proceso hijo
    dup2(pipefd[1], STDOUT_FILENO);  // Redireccionamos la salida estándar al pipe
    close(pipefd[1]);                // Cerramos el extremo de escritura del pipe en el proceso hijo
    execl("/bin/sh", "/bin/sh", "-c", command, nullptr);  // Ejecuta el comando dado
    // Si execl retorna, significa que hubo un error
    std::cerr << "Error al ejecutar el comando: " << command << std::endl;
    _exit(1);  // Usar _exit para evitar la ejecución de códigos de salida de manejo de errores
  }
  else if (pid > 0)
  {
    // Esto se ejecuta en el proceso padre
    close(pipefd[1]);  // Cerramos el extremo de escritura del pipe en el proceso padre
    info.pid = pid;
    info.pipe = fdopen(pipefd[0], "r");  // Abrir el descriptor de archivo de lectura en modo texto
  }
  else
  {
    std::cerr << "Error al crear el proceso hijo." << std::endl;
  }
  return info;
}
References smacc2::client_bases::ProcessInfo::pid, and smacc2::client_bases::ProcessInfo::pipe.
Referenced by smacc2::client_bases::ClRosLaunch2::executeRosLaunch().