SMACC2: smacc2 Namespace Reference
smacc2 Namespace Reference
Namespaces
namespace client_bases
namespace client_behaviors
namespace components
namespace default_events
namespace default_transition_tags
namespace event_generators
namespace introspection
namespace state_reactors
namespace utils
Classes
struct AddTEventTypeStateReactor
struct AddTEventTypeStateReactorInfo
class CallbackCounterSemaphore
class CbServiceServerCallbackBase
class ClientHandler
struct ComponentKey
struct EvCbFailure
struct EvCbFinished
struct EvCbSuccess
class HasSpecificNamedOnExit
class HasStandardOnExit
class ISmaccClient
class ISmaccClientBehavior
class ISmaccComponent
class ISmaccOrthogonal
class ISmaccState
class ISmaccStateMachine
class ISmaccUpdatable
class Orthogonal
class SignalDetector
class SmaccAsyncClientBehavior
class SmaccClientBehavior
class SmaccEventGenerator
class SmaccSignal
class SmaccState
struct SmaccStateMachineBase
State Machine.
struct SmExecution
class StateReactor
class Transition
Typedefs
template<class T >
using deep_history = sc::deep_history< T >
Enumerations
enum class SMRunMode { DEBUG , RELEASE }
enum class ExecutionModel { SINGLE_THREAD_SPINNER , MULTI_THREAD_SPINNER }
enum class EventLifeTime { ABSOLUTE , CURRENT_STATE }
enum class StateMachineInternalAction {
STATE_CONFIGURING , STATE_ENTERING , STATE_RUNNING , STATE_EXITING ,
TRANSITIONING
}
Functions
template<typename TState , typename TTransitionTagName >
void specificNamedOnExit (TState &st, TTransitionTagName tn, std::true_type)
template<typename TState , typename TTransitionTagName >
void specificNamedOnExit (TState &, TTransitionTagName, std::false_type)
template<typename TState , typename TTransitionTagName >
void specificNamedOnExit (TState &m, TTransitionTagName tn)
template<typename TState >
void standardOnExit (TState &st, std::true_type)
template<typename TState >
void standardOnExit (TState &, std::false_type)
template<typename TState >
void standardOnExit (TState &m)
void onSigQuit (int sig)
template<typename StateMachineType >
void run (ExecutionModel executionModel=ExecutionModel::SINGLE_THREAD_SPINNER)
template<typename StateMachineType >
SmExecution * run_async ()
Typedef Documentation
deep_history
template<class T > using smacc2::deep_history = typedef sc::deep_history<T>
Definition at line 54 of file common.hpp.
Enumeration Type Documentation
EventLifeTime
enum class smacc2::EventLifeTime strong
Enumerator
ABSOLUTE
CURRENT_STATE
Definition at line 46 of file smacc_state_machine.hpp.
{
  ABSOLUTE,
  CURRENT_STATE /*events are discarded if we are leaving the state it were created. I is used for client behaviors whose lifetime is associated to state*/
};
ExecutionModel
enum class smacc2::ExecutionModel strong
Enumerator
SINGLE_THREAD_SPINNER
MULTI_THREAD_SPINNER
Definition at line 29 of file smacc_signal_detector.hpp.
{
  SINGLE_THREAD_SPINNER,
  MULTI_THREAD_SPINNER
};
SMRunMode
enum class smacc2::SMRunMode strong
Enumerator
DEBUG
RELEASE
Definition at line 68 of file common.hpp.
{
  DEBUG,
  RELEASE
};
StateMachineInternalAction
enum class smacc2::StateMachineInternalAction strong
Enumerator
STATE_CONFIGURING
STATE_ENTERING
STATE_RUNNING
STATE_EXITING
TRANSITIONING
Definition at line 52 of file smacc_state_machine.hpp.
{
  STATE_CONFIGURING,
  STATE_ENTERING,
  STATE_RUNNING,
  STATE_EXITING,
  TRANSITIONING
};
Function Documentation
onSigQuit()
void smacc2::onSigQuit (int sig)
Definition at line 370 of file signal_detector.cpp.
{
  RCLCPP_INFO(rclcpp::get_logger("SMACC"), "SignalDetector: SIGQUIT received");
  exit(0);
}
Referenced by run(), and run_async().
run()
template<typename StateMachineType > void smacc2::run (ExecutionModel executionModel = ExecutionModel::SINGLE_THREAD_SPINNER)
Definition at line 114 of file smacc_signal_detector.hpp.
{
  ::signal(SIGQUIT, onSigQuit);
  // create the asynchronous state machine scheduler
  SmaccFifoScheduler scheduler1(true);
  // create the signalDetector component
  SignalDetector signalDetector(&scheduler1, executionModel);
  // create the asynchronous state machine processor
  SmaccFifoScheduler::processor_handle sm =
    scheduler1.create_processor<StateMachineType>(&signalDetector);
  // initialize the asynchronous state machine processor
  signalDetector.setProcessorHandle(sm);
  scheduler1.initiate_processor(sm);
  //create a thread for the asynchronous state machine processor execution
  boost::thread schedulerThread(boost::bind(&sc::fifo_scheduler<>::operator(), &scheduler1, 0));
  // use the  main thread for the signal detector component (waiting actionclient requests)
  signalDetector.pollingLoop();
}
References onSigQuit(), smacc2::SignalDetector::pollingLoop(), and smacc2::SignalDetector::setProcessorHandle().
run_async()
template<typename StateMachineType > SmExecution * smacc2::run_async ()
Definition at line 150 of file smacc_signal_detector.hpp.
{
  ::signal(SIGQUIT, onSigQuit);
  SmExecution * ret = new SmExecution();
  // create the asynchronous state machine scheduler
  ret->scheduler1 = new SmaccFifoScheduler(true);
  // create the signalDetector component
  ret->signalDetector = new SignalDetector(ret->scheduler1);
  // create the asynchronous state machine processor
  ret->sm = ret->scheduler1->create_processor<StateMachineType>(ret->signalDetector);
  // initialize the asynchronous state machine processor
  ret->signalDetector->setProcessorHandle(ret->sm);
  ret->scheduler1->initiate_processor(ret->sm);
  //create a thread for the asynchronous state machine processor execution
  ret->schedulerThread =
    new boost::thread(boost::bind(&sc::fifo_scheduler<>::operator(), ret->scheduler1, NULL));
  ret->signalDetectorLoop =
    new boost::thread(boost::bind(&SignalDetector::pollingLoop, ret->signalDetector));
  return ret;
}
References onSigQuit(), smacc2::SignalDetector::pollingLoop(), smacc2::SmExecution::scheduler1, smacc2::SmExecution::schedulerThread, smacc2::SignalDetector::setProcessorHandle(), smacc2::SmExecution::signalDetector, smacc2::SmExecution::signalDetectorLoop, and smacc2::SmExecution::sm.
specificNamedOnExit() [1/3]
template<typename TState , typename TTransitionTagName > void smacc2::specificNamedOnExit (TState & , TTransitionTagName , std::false_type)
Definition at line 50 of file state_traits.hpp.
{
}
specificNamedOnExit() [2/3]
template<typename TState , typename TTransitionTagName > void smacc2::specificNamedOnExit (TState & m, TTransitionTagName tn)
Definition at line 55 of file state_traits.hpp.
{
  specificNamedOnExit(
    m, tn,
    std::integral_constant<bool, HasSpecificNamedOnExit<TState, TTransitionTagName>::value>());
}
References specificNamedOnExit().
specificNamedOnExit() [3/3]
template<typename TState , typename TTransitionTagName > void smacc2::specificNamedOnExit (TState & st, TTransitionTagName tn, std::true_type)
Definition at line 44 of file state_traits.hpp.
{
  st.onExit(tn);
}
Referenced by smacc2::Transition< Event, Destination, Tag, TransitionContext, pTransitionAction >::reactions< State >::react_with_action(), smacc2::Transition< Event, Destination, Tag, TransitionContext, pTransitionAction >::reactions< State >::react_without_action(), and specificNamedOnExit().
standardOnExit() [1/3]
template<typename TState > void smacc2::standardOnExit (TState & , std::false_type)
Definition at line 89 of file state_traits.hpp.
{
}
standardOnExit() [2/3]
template<typename TState > void smacc2::standardOnExit (TState & m)
Definition at line 94 of file state_traits.hpp.
{
  standardOnExit(m, std::integral_constant<bool, HasStandardOnExit<TState>::value>());
}
References standardOnExit().
standardOnExit() [3/3]
template<typename TState > void smacc2::standardOnExit (TState & st, std::true_type)
Definition at line 83 of file state_traits.hpp.
{
  st.onExit();
}
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::exit(), and standardOnExit().