SMACC2: cl_nitrosz::odom_tracker Namespace Reference
cl_nitrosz::odom_tracker Namespace Reference
Classes
class CpOdomTracker
Enumerations
enum class WorkingMode : uint8_t { RECORD_PATH = 0 , CLEAR_PATH = 1 , IDLE = 2 }
Functions
double p2pDistance (const geometry_msgs::msg::Point &p1, const geometry_msgs::msg::Point &p2)
template<typename T >
void parameterDeclareAndtryGetOrSet (rclcpp::Node::SharedPtr &node, std::string param_name, T &value)
Enumeration Type Documentation
WorkingMode
enum class cl_nitrosz::odom_tracker::WorkingMode : uint8_t strong
Enumerator
RECORD_PATH
CLEAR_PATH
IDLE
Definition at line 44 of file cp_odom_tracker.hpp.
{
  RECORD_PATH = 0,
  CLEAR_PATH = 1,
  IDLE = 2
};
Function Documentation
p2pDistance()
double cl_nitrosz::odom_tracker::p2pDistance (const geometry_msgs::msg::Point & p1, const geometry_msgs::msg::Point & p2) inline
p2pDistance()
Definition at line 179 of file cp_odom_tracker.hpp.
{
  double dx = (p1.x - p2.x);
  double dy = (p1.y - p2.y);
  double dz = (p2.z - p2.z);
  double dist = sqrt(dx * dx + dy * dy + dz * dz);
  return dist;
}
Referenced by cl_nitrosz::odom_tracker::CpOdomTracker::updateClearPath(), and cl_nitrosz::odom_tracker::CpOdomTracker::updateRecordPath().
parameterDeclareAndtryGetOrSet()
template<typename T > void cl_nitrosz::odom_tracker::parameterDeclareAndtryGetOrSet (rclcpp::Node::SharedPtr & node, std::string param_name, T & value)
Definition at line 42 of file cp_odom_tracker.cpp.
{
  if (!node->get_parameter(param_name, value))
  {
    RCLCPP_INFO_STREAM(
      node->get_logger(), "[CpOdomTracker] autoset " << param_name << ": " << value);
    node->declare_parameter(param_name, value);
  }
  else
  {
    RCLCPP_INFO_STREAM(node->get_logger(), "[CpOdomTracker] " << param_name << ": " << value);
  }
}
Referenced by cl_nitrosz::odom_tracker::CpOdomTracker::onInitialize().