SMACC2: smacc2/src/smacc2/smacc_tracing.cpp File Reference
smacc_tracing.cpp File Reference
#include <smacc2/smacc_tracing/smacc_tracing.hpp>
Macros
#define CONDITIONAL_TP(...)
Functions
void TRACEPOINT (spinOnce)
void TRACEPOINT (smacc2_event, const char *event_type)
void TRACEPOINT (smacc2_state_update_start, const char *updatable_element_name)
void TRACEPOINT (smacc2_state_update_end, const char *updatable_element_name)
void TRACEPOINT (smacc2_state_onRuntimeConfigure_start, const char *state_name)
void TRACEPOINT (smacc2_state_onRuntimeConfigure_end, const char *state_name)
void TRACEPOINT (smacc2_state_onEntry_start, const char *state_name)
void TRACEPOINT (smacc2_state_onEntry_end, const char *state_name)
void TRACEPOINT (smacc2_state_onExit_start, const char *state_name)
void TRACEPOINT (smacc2_state_onExit_end, const char *state_name)
void TRACEPOINT (smacc2_client_behavior_on_entry_start, const char *state_name, const char *orthogonal_name, const char *client_behavior_name)
void TRACEPOINT (smacc2_client_behavior_on_entry_end, const char *state_name, const char *orthogonal_name, const char *client_behavior_name)
void TRACEPOINT (smacc2_client_behavior_on_exit_start, const char *state_name, const char *orthogonal_name, const char *client_behavior_name)
void TRACEPOINT (smacc2_client_behavior_on_exit_end, const char *state_name, const char *orthogonal_name, const char *client_behavior_name)
Macro Definition Documentation
CONDITIONAL_TP
#define CONDITIONAL_TP (...)
Definition at line 27 of file smacc_tracing.cpp.
Referenced by TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), TRACEPOINT(), and TRACEPOINT().
Function Documentation
TRACEPOINT() [1/14]
void TRACEPOINT (smacc2_client_behavior_on_entry_end , const char * state_name, const char * orthogonal_name, const char * client_behavior_name)
Definition at line 82 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(
    smacc2_client_behavior_on_entry_end, state_name, orthogonal_name, client_behavior_name);
}
References CONDITIONAL_TP, orthogonal_name, smacc2_client_behavior_on_entry_end, and state_name.
TRACEPOINT() [2/14]
void TRACEPOINT (smacc2_client_behavior_on_entry_start , const char * state_name, const char * orthogonal_name, const char * client_behavior_name)
Definition at line 74 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(
    smacc2_client_behavior_on_entry_start, state_name, orthogonal_name, client_behavior_name);
}
References CONDITIONAL_TP, orthogonal_name, smacc2_client_behavior_on_entry_start, and state_name.
TRACEPOINT() [3/14]
void TRACEPOINT (smacc2_client_behavior_on_exit_end , const char * state_name, const char * orthogonal_name, const char * client_behavior_name)
Definition at line 98 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(
    smacc2_client_behavior_on_exit_end, state_name, orthogonal_name, client_behavior_name);
}
References CONDITIONAL_TP, orthogonal_name, smacc2_client_behavior_on_exit_end, and state_name.
TRACEPOINT() [4/14]
void TRACEPOINT (smacc2_client_behavior_on_exit_start , const char * state_name, const char * orthogonal_name, const char * client_behavior_name)
Definition at line 90 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(
    smacc2_client_behavior_on_exit_start, state_name, orthogonal_name, client_behavior_name);
}
References CONDITIONAL_TP, orthogonal_name, smacc2_client_behavior_on_exit_start, and state_name.
TRACEPOINT() [5/14]
void TRACEPOINT (smacc2_event , const char * event_type)
Definition at line 32 of file smacc_tracing.cpp.
{ CONDITIONAL_TP(smacc2_event, event_type); }
References CONDITIONAL_TP, and smacc2_event.
TRACEPOINT() [6/14]
void TRACEPOINT (smacc2_state_onEntry_end , const char * state_name)
Definition at line 59 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(smacc2_state_onEntry_end, state_name);
}
References CONDITIONAL_TP, smacc2_state_onEntry_end, and state_name.
TRACEPOINT() [7/14]
void TRACEPOINT (smacc2_state_onEntry_start , const char * state_name)
Definition at line 54 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(smacc2_state_onEntry_start, state_name);
}
References CONDITIONAL_TP, smacc2_state_onEntry_start, and state_name.
TRACEPOINT() [8/14]
void TRACEPOINT (smacc2_state_onExit_end , const char * state_name)
Definition at line 69 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(smacc2_state_onExit_end, state_name);
}
References CONDITIONAL_TP, smacc2_state_onExit_end, and state_name.
TRACEPOINT() [9/14]
void TRACEPOINT (smacc2_state_onExit_start , const char * state_name)
Definition at line 64 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(smacc2_state_onExit_start, state_name);
}
References CONDITIONAL_TP, smacc2_state_onExit_start, and state_name.
TRACEPOINT() [10/14]
void TRACEPOINT (smacc2_state_onRuntimeConfigure_end , const char * state_name)
Definition at line 49 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(smacc2_state_onRuntimeConfigure_end, state_name);
}
References CONDITIONAL_TP, smacc2_state_onRuntimeConfigure_end, and state_name.
TRACEPOINT() [11/14]
void TRACEPOINT (smacc2_state_onRuntimeConfigure_start , const char * state_name)
Definition at line 44 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(smacc2_state_onRuntimeConfigure_start, state_name);
}
References CONDITIONAL_TP, smacc2_state_onRuntimeConfigure_start, and state_name.
TRACEPOINT() [12/14]
void TRACEPOINT (smacc2_state_update_end , const char * updatable_element_name)
Definition at line 39 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(smacc2_state_update_end, updatable_element_name);
}
References CONDITIONAL_TP, and smacc2_state_update_end.
TRACEPOINT() [13/14]
void TRACEPOINT (smacc2_state_update_start , const char * updatable_element_name)
Definition at line 34 of file smacc_tracing.cpp.
{
  CONDITIONAL_TP(smacc2_state_update_start, updatable_element_name);
}
References CONDITIONAL_TP, and smacc2_state_update_start.
TRACEPOINT() [14/14]
void TRACEPOINT (spinOnce)
Definition at line 30 of file smacc_tracing.cpp.
{ CONDITIONAL_TP(spinOnce); }
References CONDITIONAL_TP.
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::exit(), smacc2::ISmaccOrthogonal::onEntry(), smacc2::ISmaccOrthogonal::onExit(), smacc2::SignalDetector::pollOnce(), smacc2::ISmaccStateMachine::postEvent(), and smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::shallow_construct().