SMACC2: smacc2::introspection::AddTransition Struct Reference
smacc2::introspection::AddTransition Struct Reference
#include <smacc_state_machine_info.hpp>
Public Member Functions
AddTransition (std::shared_ptr< SmaccStateInfo > &currentState)
template<template< typename, typename, typename > typename TTransition, typename TevSource , template< typename > typename EvType, typename Tag , typename DestinyState >
void operator() (TTransition< EvType< TevSource >, DestinyState, Tag >)
template<template< typename, typename > typename TTransition, typename TevSource , template< typename > typename EvType, typename DestinyState >
void operator() (TTransition< EvType< TevSource >, DestinyState >)
template<typename T >
void operator() (T)
template<typename TTrans >
void operator() (TTrans)
Public Attributes
std::shared_ptr< SmaccStateInfo > & currentState_
Detailed Description
Definition at line 100 of file smacc_state_machine_info.hpp.
Constructor & Destructor Documentation
AddTransition()
smacc2::introspection::AddTransition::AddTransition (std::shared_ptr< SmaccStateInfo > & currentState) inline explicit
Definition at line 104 of file smacc_state_machine_info.hpp.
  : currentState_(currentState)
  {
  }
Member Function Documentation
operator()() [1/4]
template<typename T > void smacc2::introspection::AddTransition::operator() (T)
operator()() [2/4]
template<typename TTrans > void smacc2::introspection::AddTransition::operator() (TTrans)
Definition at line 413 of file smacc_state_machine_info.hpp.
{
  using type_t = typename TTrans::type;
  processTransitions<type_t>(currentState_);
}
References currentState_, and smacc2::introspection::processTransitions().
operator()() [3/4]
template<template< typename, typename > typename TTransition, typename TevSource , template< typename > typename EvType, typename DestinyState > void smacc2::introspection::AddTransition::operator() (TTransition< EvType< TevSource >, DestinyState >)
Definition at line 407 of file smacc_state_machine_info.hpp.
{
  processTransitions<TTransition<EvType<TevSource>, DestinyState>>(currentState_);
}
References currentState_, and smacc2::introspection::processTransitions().
operator()() [4/4]
template<template< typename, typename, typename > typename TTransition, typename TevSource , template< typename > typename EvType, typename Tag , typename DestinyState > void smacc2::introspection::AddTransition::operator() (TTransition< EvType< TevSource >, DestinyState, Tag >)
Definition at line 397 of file smacc_state_machine_info.hpp.
{
  processTransitions<TTransition<EvType<TevSource>, DestinyState, Tag>>(currentState_);
}
References currentState_, and smacc2::introspection::processTransitions().
Member Data Documentation
currentState_
std::shared_ptr<SmaccStateInfo>& smacc2::introspection::AddTransition::currentState_
Definition at line 102 of file smacc_state_machine_info.hpp.
Referenced by operator()(), operator()(), and operator()().
The documentation for this struct was generated from the following file:
smacc2/include/smacc2/introspection/smacc_state_machine_info.hpp