SMACC2: cl_nav2z::CbLoadWaypointsFile Struct Reference
cl_nav2z::CbLoadWaypointsFile Struct Reference
#include <cb_load_waypoints_file.hpp>
Public Member Functions
CbLoadWaypointsFile (std::string filepath)
CbLoadWaypointsFile (std::string parameter_name, std::string packagenamespace)
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
Public Attributes
std::optional< std::string > filepath_
std::optional< std::string > parameterName_
std::optional< std::string > packageNamespace_
cl_nav2z::CpWaypointNavigatorBase * waypointsNavigator_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 28 of file cb_load_waypoints_file.hpp.
Constructor & Destructor Documentation
CbLoadWaypointsFile() [1/2]
cl_nav2z::CbLoadWaypointsFile::CbLoadWaypointsFile (std::string filepath)
Definition at line 28 of file cb_load_waypoints_file.cpp.
: filepath_(filepath) {}
CbLoadWaypointsFile() [2/2]
cl_nav2z::CbLoadWaypointsFile::CbLoadWaypointsFile (std::string parameter_name, std::string packagenamespace)
Definition at line 30 of file cb_load_waypoints_file.cpp.
: parameterName_(parameter_name), packageNamespace_(packagenamespace)
{
}
Member Function Documentation
onEntry()
void cl_nav2z::CbLoadWaypointsFile::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 35 of file cb_load_waypoints_file.cpp.
{
  requiresComponent(waypointsNavigator_);  // this is a component from the
                                           // nav2z_client library
  if (filepath_)
  {
    this->waypointsNavigator_->loadWayPointsFromFile(filepath_.value());
  }
  else
  {
    RCLCPP_INFO(getLogger(), "Loading waypoints from parameter %s", parameterName_.value().c_str());
    this->waypointsNavigator_->loadWaypointsFromYamlParameter(
      parameterName_.value(), packageNamespace_.value());
  }
  // change this to skip some points of the yaml file, default = 0
  waypointsNavigator_->currentWaypoint_ = 0;
  this->postSuccessEvent();
}
References cl_nav2z::CpWaypointNavigatorBase::currentWaypoint_, filepath_, smacc2::ISmaccClientBehavior::getLogger(), cl_nav2z::CpWaypointNavigatorBase::loadWayPointsFromFile(), cl_nav2z::CpWaypointNavigatorBase::loadWaypointsFromYamlParameter(), packageNamespace_, parameterName_, smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), smacc2::ISmaccClientBehavior::requiresComponent(), and waypointsNavigator_.
onExit()
void cl_nav2z::CbLoadWaypointsFile::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 56 of file cb_load_waypoints_file.cpp.
{}
Member Data Documentation
filepath_
std::optional<std::string> cl_nav2z::CbLoadWaypointsFile::filepath_
Definition at line 39 of file cb_load_waypoints_file.hpp.
Referenced by onEntry().
packageNamespace_
std::optional<std::string> cl_nav2z::CbLoadWaypointsFile::packageNamespace_
Definition at line 42 of file cb_load_waypoints_file.hpp.
Referenced by onEntry().
parameterName_
std::optional<std::string> cl_nav2z::CbLoadWaypointsFile::parameterName_
Definition at line 41 of file cb_load_waypoints_file.hpp.
Referenced by onEntry().
waypointsNavigator_
cl_nav2z::CpWaypointNavigatorBase* cl_nav2z::CbLoadWaypointsFile::waypointsNavigator_
Definition at line 44 of file cb_load_waypoints_file.hpp.
Referenced by onEntry().
The documentation for this struct was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/client_behaviors/cb_load_waypoints_file.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/client_behaviors/cb_load_waypoints_file.cpp