SMACC2: smacc2::introspection::WalkStatesExecutor< InitialStateType > Struct Template Reference
smacc2::introspection::WalkStatesExecutor< InitialStateType > Struct Template Reference
#include <smacc_state_machine_info.hpp>
Static Public Member Functions
static void walkStates (std::shared_ptr< SmaccStateInfo > &currentState, bool rootInitialNode)
Detailed Description
template<typename InitialStateType>
struct smacc2::introspection::WalkStatesExecutor< InitialStateType >
Definition at line 125 of file smacc_state_machine_info.hpp.
Member Function Documentation
walkStates()
template<typename InitialStateType > void smacc2::introspection::WalkStatesExecutor< InitialStateType >::walkStates (std::shared_ptr< SmaccStateInfo > & currentState, bool rootInitialNode) static
Definition at line 427 of file smacc_state_machine_info.hpp.
{
  //rclcpp::Duration(1).sleep();
  auto currentname = demangledTypeName<InitialStateType>();
  std::shared_ptr<SmaccStateInfo> targetState;
  if (!rootInitialNode)
  {
    if (parentState->stateMachine_->containsState<InitialStateType>())
    {
      // it already exist: break;
      return;
    }
    targetState = parentState->createChildState<InitialStateType>();
  }
  else
  {
    targetState = parentState;
  }
  CallOnDefinition<InitialStateType>();
  typedef
    typename std::remove_pointer<decltype(InitialStateType::smacc_inner_type)>::type InnerType;
  processSubState<InnerType>(targetState);
  // -------------------- REACTIONS --------------------
  typedef typename InitialStateType::reactions reactions;
  // RCLCPP_INFO_STREAM(getLogger(),"state machine initial state reactions: "
  // << demangledTypeName<reactions>());
  processTransitions<reactions>(targetState);
}
References smacc2::introspection::CallOnDefinition(), smacc2::introspection::demangledTypeName(), smacc2::introspection::processSubState(), and smacc2::introspection::processTransitions().
Referenced by smacc2::introspection::SmaccStateMachineInfo::buildStateMachineInfo(), smacc2::introspection::AddSubState::operator()(), smacc2::introspection::processSubState(), and smacc2::introspection::processTransitionAux().
The documentation for this struct was generated from the following file:
smacc2/include/smacc2/introspection/smacc_state_machine_info.hpp