SMACC2: cl_nav2z::CbActiveStop Struct Reference
cl_nav2z::CbActiveStop Struct Reference
#include <cb_active_stop.hpp>
Public Member Functions
CbActiveStop ()
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
Private Attributes
rclcpp::Publisher< geometry_msgs::msg::Twist >::SharedPtr cmd_vel_pub_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 28 of file cb_active_stop.hpp.
Constructor & Destructor Documentation
CbActiveStop()
cl_nav2z::CbActiveStop::CbActiveStop ()
Definition at line 29 of file cb_active_stop.cpp.
{}
Member Function Documentation
onEntry()
void cl_nav2z::CbActiveStop::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 31 of file cb_active_stop.cpp.
{
  auto nh = this->getNode();
  cmd_vel_pub_ = nh->create_publisher<geometry_msgs::msg::Twist>("/cmd_vel", rclcpp::QoS(1));
  rclcpp::Rate loop_rate(5);
  geometry_msgs::msg::Twist cmd_vel_msg;
  while (!this->isShutdownRequested())
  {
    cmd_vel_msg.linear.x = 0;
    cmd_vel_msg.angular.z = 0;
    cmd_vel_pub_->publish(cmd_vel_msg);
    loop_rate.sleep();
  }
  RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] Finished behavior execution");
  this->postSuccessEvent();
}
References cmd_vel_pub_, smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::getNode(), smacc2::SmaccAsyncClientBehavior::isShutdownRequested(), and smacc2::SmaccAsyncClientBehavior::postSuccessEvent().
onExit()
void cl_nav2z::CbActiveStop::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 51 of file cb_active_stop.cpp.
{}
Member Data Documentation
cmd_vel_pub_
rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr cl_nav2z::CbActiveStop::cmd_vel_pub_ private
Definition at line 31 of file cb_active_stop.hpp.
Referenced by onEntry().
The documentation for this struct was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/client_behaviors/cb_active_stop.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/client_behaviors/cb_active_stop.cpp