SMACC2: smacc2::default_events::EvActionSucceeded< TSource, TOrthogonal > Struct Template Reference
smacc2::default_events::EvActionSucceeded< TSource, TOrthogonal > Struct Template Reference
#include <smacc_default_events.hpp>
Static Public Member Functions
static std::string getEventLabel ()
static std::string getDefaultTransitionTag ()
static std::string getDefaultTransitionType ()
Public Attributes
TSource::WrappedResult resultMessage
Detailed Description
template<typename TSource, typename TOrthogonal>
struct smacc2::default_events::EvActionSucceeded< TSource, TOrthogonal >
Definition at line 54 of file smacc_default_events.hpp.
Member Function Documentation
getDefaultTransitionTag()
template<typename TSource , typename TOrthogonal > static std::string smacc2::default_events::EvActionSucceeded< TSource, TOrthogonal >::getDefaultTransitionTag () inline static
Definition at line 66 of file smacc_default_events.hpp.
{ return demangledTypeName<SUCCESS>(); }
References smacc2::introspection::demangledTypeName().
getDefaultTransitionType()
template<typename TSource , typename TOrthogonal > static std::string smacc2::default_events::EvActionSucceeded< TSource, TOrthogonal >::getDefaultTransitionType () inline static
Definition at line 68 of file smacc_default_events.hpp.
{ return demangledTypeName<SUCCESS>(); }
References smacc2::introspection::demangledTypeName().
getEventLabel()
template<typename TSource , typename TOrthogonal > static std::string smacc2::default_events::EvActionSucceeded< TSource, TOrthogonal >::getEventLabel () inline static
Definition at line 58 of file smacc_default_events.hpp.
  {
    // show ros message type
    std::string label;
    EventLabel<TSource>(label);
    return label;
  }
References smacc2::introspection::EventLabel().
Member Data Documentation
resultMessage
template<typename TSource , typename TOrthogonal > TSource::WrappedResult smacc2::default_events::EvActionSucceeded< TSource, TOrthogonal >::resultMessage
Definition at line 56 of file smacc_default_events.hpp.
The documentation for this struct was generated from the following file:
smacc2/include/smacc2/smacc_default_events.hpp