SMACC2: smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode > Class Template Reference
smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode > Class Template Reference
#include <smacc_state_base.hpp>
Classes
struct my_context
Public Types
typedef Context TContext
typedef Context::inner_context_type context_type
typedef context_type::state_iterator state_iterator
typedef InnerInitial LastDeepState
typedef base_type::outermost_context_base_type outermost_context_base_type
typedef base_type::inner_context_ptr_type inner_context_ptr_type
typedef base_type::context_ptr_type context_ptr_type
typedef base_type::inner_initial_list inner_initial_list
Public Member Functions
SmaccState ()=delete
SmaccState (my_context ctx)
virtual ~SmaccState ()
const smacc2::introspection::SmaccStateInfo * getStateInfo ()
std::string getFullName ()
std::string getShortName ()
virtual ISmaccState * getParentState ()
void exit ()
void runtimeConfigure ()
void onEntry ()
void onExit ()
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
virtual ISmaccStateMachine & getStateMachine ()
void checkWhileLoopConditionAndThrowEvent (bool(MostDerived::*conditionFn)())
void throwSequenceFinishedEvent ()
Public Member Functions inherited from smacc2::ISmaccState
virtual ISmaccStateMachine & getStateMachine ()=0
ISmaccState * getParentState ()
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc2::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
void param (std::string param_name)
template<typename T >
void param (std::string param_name, T default_value)
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Static Public Member Functions
template<typename TOrthogonal , typename TBehavior >
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh, MostDerived &)> initializationFunction)
template<typename TOrthogonal , typename TBehavior >
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh)> initializationFunction)
template<typename TOrthogonal , typename TBehavior , typename... Args>
static void configure_orthogonal (Args &&... args)
template<typename TStateReactor , typename TOutputEvent , typename TInputEventList , typename... TArgs>
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor (TArgs... args)
template<typename TEventGenerator , typename... TUArgs>
static std::shared_ptr< smacc2::introspection::EventGeneratorHandler > static_createEventGenerator (TUArgs... args)
template<typename TStateReactor , typename... TUArgs>
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor_aux (TUArgs... args)
static void initial_deep_construct (outermost_context_base_type &outermostContextBase)
static void deep_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
static inner_context_ptr_type shallow_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
Public Attributes
bool finishStateThrown
InnerInitial * smacc_inner_type
Public Attributes inherited from smacc2::ISmaccState
rclcpp::Node::SharedPtr stateNode_
Private Types
typedef sc::simple_state< MostDerived, Context, InnerInitial, historyMode > base_type
Private Member Functions
void entryStateInternal ()
Static Private Member Functions
template<typename TOrthogonal , typename TBehavior >
static void configure_orthogonal_internal (std::function< void(ISmaccState *state)> initializationFunction)
Additional Inherited Members
Protected Attributes inherited from smacc2::ISmaccState
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc2::SmaccEventGenerator > > eventGenerators_
rclcpp::Node::SharedPtr contextNh
ISmaccState * parentState_
const smacc2::introspection::SmaccStateInfo * stateInfo_
Detailed Description
template<class MostDerived, class Context, class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history>
class smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >
Definition at line 37 of file smacc_state_base.hpp.
Member Typedef Documentation
base_type
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef sc::simple_state<MostDerived, Context, InnerInitial, historyMode> smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::base_type private
Definition at line 40 of file smacc_state_base.hpp.
context_ptr_type
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef base_type::context_ptr_type smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::context_ptr_type
Definition at line 367 of file smacc_state_base.hpp.
context_type
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef Context::inner_context_type smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::context_type
Definition at line 44 of file smacc_state_base.hpp.
inner_context_ptr_type
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef base_type::inner_context_ptr_type smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::inner_context_ptr_type
Definition at line 366 of file smacc_state_base.hpp.
inner_initial_list
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef base_type::inner_initial_list smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::inner_initial_list
Definition at line 368 of file smacc_state_base.hpp.
LastDeepState
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef InnerInitial smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::LastDeepState
Definition at line 47 of file smacc_state_base.hpp.
outermost_context_base_type
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef base_type::outermost_context_base_type smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::outermost_context_base_type
Definition at line 365 of file smacc_state_base.hpp.
state_iterator
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef context_type::state_iterator smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::state_iterator
Definition at line 45 of file smacc_state_base.hpp.
TContext
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> typedef Context smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::TContext
Definition at line 43 of file smacc_state_base.hpp.
Constructor & Destructor Documentation
SmaccState() [1/2]
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState () delete
SmaccState() [2/2]
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState (my_context ctx) inline
Definition at line 63 of file smacc_state_base.hpp.
  {
#define STATE_NAME (demangleSymbol(typeid(MostDerived).name()).c_str())
    static_assert(
      std::is_base_of<ISmaccState, Context>::value ||
        std::is_base_of<ISmaccStateMachine, Context>::value,
      "The context class must be a SmaccState or a SmaccStateMachine");
    static_assert(
      !std::is_same<MostDerived, Context>::value,
      "The context must be a different state or state machine "
      "than the current state");
    // auto sm = dynamic_cast<ISmaccStateMachine*>(ctx.pContext_);
    // if(sm!=nullptr)
    // {
    //   this->contextNh = sm->getNode();
    // }
    // else
    // {
    //   auto st = dynamic_cast<ISmaccState*>(ctx.pContext_);
    //   this->contextNh = st->getNode();
    // }
    this->contextNh = static_cast<Context *>(optionalNodeHandle(ctx.pContext_))
                        ->getNode();  // static_cast<Context*>(ctx.pContext_.get())->getNode();
    // stateNode_ = contextNh->create_sub_node(smacc2::utils::cleanShortTypeName(typeid(MostDerived)));
    stateNode_ = rclcpp::Node::make_shared(
      smacc2::utils::cleanShortTypeName(typeid(MostDerived)),
      std::string(this->contextNh->get_fully_qualified_name()));
    RCLCPP_WARN(getNode()->get_logger(), "[%s] creating ", STATE_NAME);
    this->set_context(ctx.pContext_);
    this->stateInfo_ = getStateInfo();
    // storing a reference to the parent state
    auto & ps = this->template context<Context>();
    parentState_ = dynamic_cast<ISmaccState *>(&ps);
    finishStateThrown = false;
    // this->contextNh = optionalNodeHandle(ctx.pContext_);
    // RCLCPP_DEBUG(getNode()->get_logger(),"[%s] Ros node handle namespace for this state: %s", STATE_NAME,
    // contextNh->get_namespace()); if (std::string(contextNh->get_namespace()) == "/")
    // {
    //   auto nhname = smacc2::utils::cleanShortTypeName(typeid(Context));
    //   RCLCPP_INFO(getNode()->get_logger(), "[%s] Creating ros NodeHandle for this state: %s", STATE_NAME,
    //   nhname.c_str()); contextNh = rclcpp::Node::make_shared(nhname);
    // }
  }
References smacc2::utils::cleanShortTypeName(), smacc2::ISmaccState::contextNh, smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::finishStateThrown, smacc2::ISmaccState::getNode(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getStateInfo(), smacc2::introspection::optionalNodeHandle(), smacc2::ISmaccState::parentState_, smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::my_context::pContext_, STATE_NAME, smacc2::ISmaccState::stateInfo_, and smacc2::ISmaccState::stateNode_.
~SmaccState()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> virtual smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::~SmaccState () inline virtual
Definition at line 114 of file smacc_state_base.hpp.
{}
Member Function Documentation
checkWhileLoopConditionAndThrowEvent()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::checkWhileLoopConditionAndThrowEvent (bool(MostDerived::*)() conditionFn) inline
Definition at line 339 of file smacc_state_base.hpp.
  {
#define STATE_NAME (demangleSymbol(typeid(MostDerived).name()).c_str())
    auto * thisobject = static_cast<MostDerived *>(this);
    auto condition = boost::bind(conditionFn, thisobject);
    bool conditionResult = condition();
    // RCLCPP_INFO("LOOP EVENT CONDITION: %d", conditionResult);
    if (conditionResult)
    {
      this->postEvent<EvLoopContinue<MostDerived>>();
    }
    else
    {
      this->postEvent<EvLoopEnd<MostDerived>>();
    }
    RCLCPP_INFO(getNode()->get_logger(), "[%s] POST THROW CONDITION", STATE_NAME);
  }
References smacc2::ISmaccState::getNode(), and STATE_NAME.
configure_orthogonal()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename TOrthogonal , typename TBehavior , typename... Args> static void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::configure_orthogonal (Args &&... args) inline static
Definition at line 219 of file smacc_state_base.hpp.
  {
    configure_orthogonal_internal<TOrthogonal, TBehavior>([=](ISmaccState * state) {
      // auto bh = std::make_shared<TBehavior>(args...);
      state->configure<TOrthogonal, TBehavior>(args...);
    });
  }
References generate_debs::args, and smacc2::ISmaccState::configure().
configure_orthogonal_internal()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename TOrthogonal , typename TBehavior > static void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::configure_orthogonal_internal (std::function< void(ISmaccState< MostDerived, Context, InnerInitial, historyMode > *state)> initializationFunction) inline static private
Definition at line 403 of file smacc_state_base.hpp.
  {
    ClientBehaviorInfoEntry bhinfo;
    bhinfo.factoryFunction = initializationFunction;
    bhinfo.behaviorType = &(typeid(TBehavior));
    bhinfo.orthogonalType = &(typeid(TOrthogonal));
    const std::type_info * tindex = &(typeid(MostDerived));
    if (!SmaccStateInfo::staticBehaviorInfo.count(tindex))
      SmaccStateInfo::staticBehaviorInfo[tindex] = std::vector<ClientBehaviorInfoEntry>();
    SmaccStateInfo::staticBehaviorInfo[tindex].push_back(bhinfo);
    RCLCPP_INFO_STREAM(
      rclcpp::get_logger("static"), "[states walking] State "
                                      << smacc2::utils::cleanShortTypeName(*tindex)
                                      << "client behavior count: "
                                      << SmaccStateInfo::staticBehaviorInfo[tindex].size());
  }
References smacc2::introspection::ClientBehaviorInfoEntry::behaviorType, smacc2::utils::cleanShortTypeName(), sm_atomic_performance_test::count, smacc2::introspection::ClientBehaviorInfoEntry::factoryFunction, smacc2::introspection::ClientBehaviorInfoEntry::orthogonalType, and smacc2::introspection::SmaccStateInfo::staticBehaviorInfo.
configure_orthogonal_runtime() [1/2]
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename TOrthogonal , typename TBehavior > static void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::configure_orthogonal_runtime (std::function< void(TBehavior &bh)> initializationFunction) inline static
Definition at line 208 of file smacc_state_base.hpp.
  {
    configure_orthogonal_internal<TOrthogonal, TBehavior>([=](ISmaccState * state) {
      // auto bh = std::make_shared<TBehavior>(args...);
      auto bh = state->configure<TOrthogonal, TBehavior>();
      initializationFunction(*bh);
    });
  }
References smacc2::ISmaccState::configure().
configure_orthogonal_runtime() [2/2]
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename TOrthogonal , typename TBehavior > static void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::configure_orthogonal_runtime (std::function< void(TBehavior &bh, MostDerived &)> initializationFunction) inline static
Definition at line 197 of file smacc_state_base.hpp.
  {
    configure_orthogonal_internal<TOrthogonal, TBehavior>([=](ISmaccState * state) {
      // auto bh = std::make_shared<TBehavior>(args...);
      auto bh = state->configure<TOrthogonal, TBehavior>();
      initializationFunction(*bh, *(static_cast<MostDerived *>(state)));
    });
  }
References smacc2::ISmaccState::configure().
deep_construct()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> static void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::deep_construct (const context_ptr_type & pContext, outermost_context_base_type & outermostContextBase) inline static
Definition at line 376 of file smacc_state_base.hpp.
  {
    const inner_context_ptr_type pInnerContext(shallow_construct(pContext, outermostContextBase));
    base_type::template deep_construct_inner<inner_initial_list>(
      pInnerContext, outermostContextBase);
  }
References smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::shallow_construct().
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::initial_deep_construct().
entryStateInternal()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal () inline private
Definition at line 424 of file smacc_state_base.hpp.
  {
#define STATE_NAME (demangleSymbol(typeid(MostDerived).name()).c_str())
    // finally we go to the derived state onEntry Function
    RCLCPP_INFO(
      getNode()->get_logger(), "[%s] State object created. Initializating...", STATE_NAME);
    this->getStateMachine().notifyOnStateEntryStart(static_cast<MostDerived *>(this));
    // TODO: make this static to build the parameter tree at startup
    // this->getNode() = rclcpp::Node::make_shared(std::string(contextNh->get_namespace()) + std::string("/") +
    // smacc2::utils::cleanShortTypeName(typeid(MostDerived)).c_str());
    RCLCPP_INFO_STREAM(
      this->getNode()->get_logger(),
      "[" << smacc2::utils::cleanShortTypeName(typeid(MostDerived)).c_str()
          << "] creating ros subnode");
    RCLCPP_DEBUG(
      getNode()->get_logger(), "[%s] nodehandle namespace: %s", STATE_NAME,
      getNode()->get_namespace());
    bool created;
    if (!this->getParam("visited", created))
    {
      this->param("visited");
      this->setParam("visited", true);
    }
    // before dynamic runtimeConfigure, we execute the staticConfigure behavior configurations
    {
      RCLCPP_INFO(getNode()->get_logger(), "[%s] -- STATIC STATE DESCRIPTION --", STATE_NAME);
      for (const auto & stateReactorsVector : SmaccStateInfo::staticBehaviorInfo)
      {
        RCLCPP_DEBUG(
          getNode()->get_logger(), "[%s] state reactor info: %s", STATE_NAME,
          demangleSymbol(stateReactorsVector.first->name()).c_str());
        for (auto & srinfo : stateReactorsVector.second)
        {
          RCLCPP_DEBUG(
            getNode()->get_logger(), "[%s] state reactor: %s", STATE_NAME,
            demangleSymbol(srinfo.behaviorType->name()).c_str());
        }
      }
      const std::type_info * tindex = &(typeid(MostDerived));
      auto & staticDefinedBehaviors = SmaccStateInfo::staticBehaviorInfo[tindex];
      auto & staticDefinedStateReactors = SmaccStateInfo::stateReactorsInfo[tindex];
      auto & staticDefinedEventGenerators = SmaccStateInfo::eventGeneratorsInfo[tindex];
      RCLCPP_DEBUG_STREAM(
        getNode()->get_logger(), "finding static client behaviors. State Database: "
                                   << SmaccStateInfo::staticBehaviorInfo.size()
                                   << ". Current state " << cleanShortTypeName(*tindex) << " cbs: "
                                   << SmaccStateInfo::staticBehaviorInfo[tindex].size());
      for (auto & bhinfo : staticDefinedBehaviors)
      {
        RCLCPP_INFO(
          getNode()->get_logger(), "[%s] Creating static client behavior: %s", STATE_NAME,
          demangleSymbol(bhinfo.behaviorType->name()).c_str());
        bhinfo.factoryFunction(this);
      }
      for (auto & sr : staticDefinedStateReactors)
      {
        RCLCPP_INFO(
          getNode()->get_logger(), "[%s] Creating static state reactor: %s", STATE_NAME,
          sr->stateReactorType->getFullName().c_str());
        sr->factoryFunction(this);
      }
      for (auto & eg : staticDefinedEventGenerators)
      {
        RCLCPP_INFO(
          getNode()->get_logger(), "[%s] Creating static event generator: %s", STATE_NAME,
          eg->eventGeneratorType->getFullName().c_str());
        eg->factoryFunction(this);
      }
      RCLCPP_INFO(getNode()->get_logger(), "[%s] ---- END STATIC DESCRIPTION", STATE_NAME);
    }
    RCLCPP_INFO(getNode()->get_logger(), "[%s] State runtime configuration", STATE_NAME);
    auto * derivedthis = static_cast<MostDerived *>(this);
    // second the orthogonals are internally configured
    this->getStateMachine().notifyOnRuntimeConfigured(derivedthis);
    TRACEPOINT(smacc2_state_onRuntimeConfigure_start, STATE_NAME);
    // first we runtime configure the state, where we create client behaviors
    static_cast<MostDerived *>(this)->runtimeConfigure();
    TRACEPOINT(smacc2_state_onRuntimeConfigure_end, STATE_NAME);
    this->getStateMachine().notifyOnRuntimeConfigurationFinished(derivedthis);
    RCLCPP_INFO(getNode()->get_logger(), "[%s] State OnEntry", STATE_NAME);
    static_cast<MostDerived *>(this)->onEntry();
    // here orthogonals and client behaviors are entered OnEntry
    this->getStateMachine().notifyOnStateEntryEnd(derivedthis);
  }
References smacc2::utils::cleanShortTypeName(), smacc2::introspection::demangleSymbol(), smacc2::introspection::SmaccStateInfo::eventGeneratorsInfo, smacc2::ISmaccState::getNode(), smacc2::ISmaccState::getParam(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getStateMachine(), smacc2::ISmaccStateMachine::notifyOnRuntimeConfigurationFinished(), smacc2::ISmaccStateMachine::notifyOnRuntimeConfigured(), smacc2::ISmaccStateMachine::notifyOnStateEntryEnd(), smacc2::ISmaccStateMachine::notifyOnStateEntryStart(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::onEntry(), smacc2::ISmaccState::param(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::runtimeConfigure(), smacc2::ISmaccState::setParam(), smacc2_state_onRuntimeConfigure_end, smacc2_state_onRuntimeConfigure_start, STATE_NAME, smacc2::introspection::SmaccStateInfo::stateReactorsInfo, smacc2::introspection::SmaccStateInfo::staticBehaviorInfo, and TRACEPOINT().
exit()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::exit () inline
Definition at line 143 of file smacc_state_base.hpp.
  {
#define STATE_NAME (demangleSymbol(typeid(MostDerived).name()).c_str())
    auto * derivedThis = static_cast<MostDerived *>(this);
    this->getStateMachine().notifyOnStateExitting(derivedThis);
    try
    {
      TRACEPOINT(smacc2_state_onExit_start, STATE_NAME);
      // static_cast<MostDerived *>(this)->onExit();
      standardOnExit(*derivedThis);
      TRACEPOINT(smacc2_state_onExit_end, STATE_NAME);
    }
    catch (...)
    {
    }
    this->getStateMachine().notifyOnStateExited(derivedThis);
  }
References smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getStateMachine(), smacc2::ISmaccStateMachine::notifyOnStateExited(), smacc2::ISmaccStateMachine::notifyOnStateExitting(), smacc2_state_onExit_end, smacc2_state_onExit_start, smacc2::standardOnExit(), STATE_NAME, and TRACEPOINT().
getFullName()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> std::string smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getFullName () inline
Definition at line 131 of file smacc_state_base.hpp.
{ return demangleSymbol(typeid(MostDerived).name()); }
References smacc2::introspection::demangleSymbol().
getGlobalSMData()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename T > bool smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getGlobalSMData (std::string name, T & ret) inline
Definition at line 176 of file smacc_state_base.hpp.
  {
    return base_type::outermost_context().getGlobalSMData(name, ret);
  }
getParentState()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> virtual ISmaccState * smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getParentState () inline virtual
Definition at line 135 of file smacc_state_base.hpp.
  {
    // auto* ctx = dynamic_cast<ISmaccState*>(this->template context<Context *>());
    return parentState_;
  }
References smacc2::ISmaccState::parentState_.
getShortName()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> std::string smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getShortName () inline
Definition at line 133 of file smacc_state_base.hpp.
{ return smacc2::utils::cleanShortTypeName(typeid(MostDerived)); }
References smacc2::utils::cleanShortTypeName().
getStateInfo()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> const smacc2::introspection::SmaccStateInfo * smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getStateInfo () inline
Definition at line 116 of file smacc_state_base.hpp.
  {
    auto smInfo = this->getStateMachine().getStateMachineInfo();
    auto key = typeid(MostDerived).name();
    if (smInfo.states.count(key))
    {
      return smInfo.states[key].get();
    }
    else
    {
      return nullptr;
    }
  }
References smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getStateMachine(), smacc2::ISmaccStateMachine::getStateMachineInfo(), and smacc2::introspection::SmaccStateMachineInfo::states.
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().
getStateMachine()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> virtual ISmaccStateMachine & smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getStateMachine () inline virtual
Implements smacc2::ISmaccState.
Definition at line 194 of file smacc_state_base.hpp.
{ return base_type::outermost_context(); }
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::exit(), and smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getStateInfo().
initial_deep_construct()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> static void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::initial_deep_construct (outermost_context_base_type & outermostContextBase) inline static
Definition at line 370 of file smacc_state_base.hpp.
  {
    deep_construct(&outermostContextBase, outermostContextBase);
  }
References smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::deep_construct().
onEntry()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::onEntry () inline
Definition at line 169 of file smacc_state_base.hpp.
{}
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal().
onExit()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::onExit () inline
Definition at line 173 of file smacc_state_base.hpp.
{}
requiresComponent()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename SmaccComponentType > void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::requiresComponent (SmaccComponentType *& storage) inline
Definition at line 189 of file smacc_state_base.hpp.
  {
    base_type::outermost_context().requiresComponent(storage);
  }
runtimeConfigure()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::runtimeConfigure () inline
Definition at line 165 of file smacc_state_base.hpp.
{}
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal().
setGlobalSMData()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename T > void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::setGlobalSMData (std::string name, T value) inline
Definition at line 183 of file smacc_state_base.hpp.
  {
    base_type::outermost_context().setGlobalSMData(name, value);
  }
shallow_construct()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> static inner_context_ptr_type smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::shallow_construct (const context_ptr_type & pContext, outermost_context_base_type & outermostContextBase) inline static
Definition at line 384 of file smacc_state_base.hpp.
  {
#define STATE_NAME (demangleSymbol(typeid(MostDerived).name()).c_str())
    // allocating in memory
    auto state = new MostDerived(
      SmaccState<MostDerived, Context, InnerInitial, historyMode>::my_context(pContext));
    const inner_context_ptr_type pInnerContext(state);
    TRACEPOINT(smacc2_state_onEntry_start, STATE_NAME);
    state->entryStateInternal();
    TRACEPOINT(smacc2_state_onEntry_end, STATE_NAME);
    outermostContextBase.add(pInnerContext);
    return pInnerContext;
  }
References smacc2_state_onEntry_end, smacc2_state_onEntry_start, STATE_NAME, and TRACEPOINT().
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::deep_construct().
static_createEventGenerator()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename TEventGenerator , typename... TUArgs> static std::shared_ptr< smacc2::introspection::EventGeneratorHandler > smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::static_createEventGenerator (TUArgs... args) inline static
Definition at line 282 of file smacc_state_base.hpp.
  {
    auto egh = std::make_shared<smacc2::introspection::EventGeneratorHandler>();
    auto eginfo = std::make_shared<SmaccEventGeneratorInfo>();
    eginfo->eventGeneratorType = TypeInfo::getTypeInfoFromType<TEventGenerator>();
    eginfo->egh = egh;
    egh->egInfo_ = eginfo;
    const std::type_info * tindex = &(typeid(MostDerived));  // get identifier of the current state
    if (!SmaccStateInfo::eventGeneratorsInfo.count(tindex))
      SmaccStateInfo::eventGeneratorsInfo[tindex] =
        std::vector<std::shared_ptr<SmaccEventGeneratorInfo>>();
    eginfo->factoryFunction = [&, egh, args...](ISmaccState * state) {
      auto eg = state->createEventGenerator<TEventGenerator>(args...);
      egh->configureEventGenerator(eg);
      eg->initialize(state);
      eg->template onStateAllocation<MostDerived, TEventGenerator>();
      return eg;
    };
    SmaccStateInfo::eventGeneratorsInfo[tindex].push_back(eginfo);
    return egh;
  }
References generate_debs::args, sm_atomic_performance_test::count, and smacc2::introspection::SmaccStateInfo::eventGeneratorsInfo.
static_createStateReactor()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename TStateReactor , typename TOutputEvent , typename TInputEventList , typename... TArgs> static std::shared_ptr< smacc2::introspection::StateReactorHandler > smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::static_createStateReactor (TArgs... args) inline static
Definition at line 229 of file smacc_state_base.hpp.
  {
    auto srh = std::make_shared<smacc2::introspection::StateReactorHandler>(globalNh_);
    auto srinfo = std::make_shared<SmaccStateReactorInfo>();
    srinfo->stateReactorType = TypeInfo::getTypeInfoFromType<TStateReactor>();
    srinfo->outputEventType = TypeInfo::getTypeInfoFromType<TOutputEvent>();
    if (srinfo->outputEventType->templateParameters.size() == 2)
    {
      srinfo->objectTagType = srinfo->outputEventType->templateParameters[1];
    }
    else if (srinfo->outputEventType->templateParameters.size() == 1)
    {
      srinfo->objectTagType = TypeInfo::getTypeInfoFromType<state_reactors::EmptyObjectTag>();
    }
    else
    {
      assert(
        false &&
        "state reactor output events should have one or two parameters (SourceType, ObjectTag)");
    }
    // iterate statically on all event sources
    using boost::mpl::_1;
    using wrappedList = typename boost::mpl::transform<TInputEventList, _1>::type;
    AddTEventTypeStateReactorInfo<TInputEventList> op(srinfo.get());
    boost::mpl::for_each<wrappedList>(op);
    srinfo->srh = srh;
    srh->srInfo_ = srinfo;
    const std::type_info * tindex = &(typeid(MostDerived));  // get identifier of the current state
    if (!SmaccStateInfo::stateReactorsInfo.count(tindex))
      SmaccStateInfo::stateReactorsInfo[tindex] =
        std::vector<std::shared_ptr<SmaccStateReactorInfo>>();
    srinfo->factoryFunction = [&, srh, args...](ISmaccState * state) {
      auto sr =
        state->createStateReactor<TStateReactor, TOutputEvent, TInputEventList, TArgs...>(args...);
      srh->configureStateReactor(sr);
      sr->initialize(state);
      return sr;
    };
    SmaccStateInfo::stateReactorsInfo[tindex].push_back(srinfo);
    return srh;
  }
References generate_debs::args, sm_atomic_performance_test::count, smacc2::introspection::globalNh_, smacc2::introspection::SmaccStateInfo::stateReactorsInfo, and generate_debs::type.
static_createStateReactor_aux()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> template<typename TStateReactor , typename... TUArgs> static std::shared_ptr< smacc2::introspection::StateReactorHandler > smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::static_createStateReactor_aux (TUArgs... args) inline static
Definition at line 311 of file smacc_state_base.hpp.
  {
    auto srh = std::make_shared<smacc2::introspection::StateReactorHandler>(globalNh_);
    auto srinfo = std::make_shared<SmaccStateReactorInfo>();
    srinfo->stateReactorType = TypeInfo::getTypeInfoFromType<TStateReactor>();
    srinfo->srh = srh;
    srh->srInfo_ = srinfo;
    const std::type_info * tindex = &(typeid(MostDerived));  // get identifier of the current state
    if (!SmaccStateInfo::stateReactorsInfo.count(tindex))
      SmaccStateInfo::stateReactorsInfo[tindex] =
        std::vector<std::shared_ptr<SmaccStateReactorInfo>>();
    srinfo->factoryFunction = [&, srh, args...](ISmaccState * state) {
      auto sr = state->createStateReactor<TStateReactor>(args...);
      srh->configureStateReactor(sr);
      sr->initialize(state);
      return sr;
    };
    SmaccStateInfo::stateReactorsInfo[tindex].push_back(srinfo);
    return srh;
  }
References generate_debs::args, sm_atomic_performance_test::count, smacc2::introspection::globalNh_, and smacc2::introspection::SmaccStateInfo::stateReactorsInfo.
throwSequenceFinishedEvent()
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> void smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::throwSequenceFinishedEvent () inline
Definition at line 358 of file smacc_state_base.hpp.
{ this->postEvent<EvSequenceFinished<MostDerived>>(); }
Member Data Documentation
finishStateThrown
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> bool smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::finishStateThrown
Definition at line 49 of file smacc_state_base.hpp.
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().
smacc_inner_type
template<class MostDerived , class Context , class InnerInitial = mpl::list<>, sc::history_mode historyMode = sc::has_deep_history> InnerInitial* smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::smacc_inner_type
Definition at line 50 of file smacc_state_base.hpp.
The documentation for this class was generated from the following file:
smacc2/include/smacc2/smacc_state_base.hpp