SMACC2: cl_move_base_z::CbRotate Class Reference
cl_move_base_z::CbRotate Class Reference
#include <cb_rotate.hpp>
Public Member Functions
CbRotate ()
CbRotate (float rotate_degree)
void onEntry () override
Public Member Functions inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
virtual ~CbMoveBaseClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Public Attributes
std::optional< float > rotateDegree
std::optional< std::string > goalChecker_
Private Attributes
std::shared_ptr< tf2_ros::Buffer > listener
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void executeOnEntry () override
void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Protected Attributes inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
cl_move_base_z::ClMoveBaseZ * moveBaseClient_
Detailed Description
Definition at line 28 of file cb_rotate.hpp.
Constructor & Destructor Documentation
CbRotate() [1/2]
cl_move_base_z::CbRotate::CbRotate ()
Definition at line 29 of file cb_rotate.cpp.
{}
CbRotate() [2/2]
cl_move_base_z::CbRotate::CbRotate (float rotate_degree)
Definition at line 31 of file cb_rotate.cpp.
{ rotateDegree = rotate_degree; }
References rotateDegree.
Member Function Documentation
onEntry()
void cl_move_base_z::CbRotate::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 33 of file cb_rotate.cpp.
{
  double angle_increment_degree = 45.0;
  if (!rotateDegree)
  {
    this->getCurrentState()->getParam("angle_increment_degree", angle_increment_degree);
  }
  else
  {
    angle_increment_degree = *rotateDegree;
  }
  auto plannerSwitcher = moveBaseClient_->getComponent<PlannerSwitcher>();
  // this should work better with a coroutine and await
  // this->plannerSwitcher_->setForwardPlanner();
  plannerSwitcher->setDefaultPlanners();
  auto p = moveBaseClient_->getComponent<cl_move_base_z::Pose>();
  auto referenceFrame = p->getReferenceFrame();
  auto currentPoseMsg = p->toPoseMsg();
  tf2::Transform currentPose;
  tf2::fromMsg(currentPoseMsg, currentPose);
  auto odomTracker = moveBaseClient_->getComponent<odom_tracker::OdomTracker>();
  ClMoveBaseZ::Goal goal;
  goal.pose.header.frame_id = referenceFrame;
  goal.pose.header.stamp = getNode()->now();
  auto currentAngle = tf2::getYaw(currentPoseMsg.orientation);
  auto targetAngle = currentAngle + angle_increment_degree * M_PI / 180.0;
  goal.pose.pose.position = currentPoseMsg.position;
  tf2::Quaternion q;
  q.setRPY(0, 0, targetAngle);
  goal.pose.pose.orientation = tf2::toMsg(q);
  geometry_msgs::msg::PoseStamped stampedCurrentPoseMsg;
  stampedCurrentPoseMsg.header.frame_id = referenceFrame;
  stampedCurrentPoseMsg.header.stamp = getNode()->now();
  stampedCurrentPoseMsg.pose = currentPoseMsg;
  this->requiresClient(moveBaseClient_);
  odomTracker->pushPath();
  odomTracker->setStartPoint(stampedCurrentPoseMsg);
  odomTracker->setWorkingMode(odom_tracker::WorkingMode::RECORD_PATH);
  RCLCPP_INFO_STREAM(getLogger(), "current pose: " << currentPoseMsg);
  RCLCPP_INFO_STREAM(getLogger(), "goal pose: " << goal.pose.pose);
  moveBaseClient_->sendGoal(goal);
}
References smacc2::ISmaccClient::getComponent(), smacc2::ISmaccClientBehavior::getCurrentState(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), smacc2::ISmaccState::getParam(), cl_move_base_z::Pose::getReferenceFrame(), cl_move_base_z::CbMoveBaseClientBehaviorBase::moveBaseClient_, cl_move_base_z::odom_tracker::RECORD_PATH, smacc2::ISmaccClientBehavior::requiresClient(), rotateDegree, smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), and cl_move_base_z::PlannerSwitcher::setDefaultPlanners().
Member Data Documentation
goalChecker_
std::optional<std::string> cl_move_base_z::CbRotate::goalChecker_
Definition at line 33 of file cb_rotate.hpp.
listener
std::shared_ptr<tf2_ros::Buffer> cl_move_base_z::CbRotate::listener private
Definition at line 42 of file cb_rotate.hpp.
rotateDegree
std::optional<float> cl_move_base_z::CbRotate::rotateDegree
Definition at line 31 of file cb_rotate.hpp.
Referenced by CbRotate(), and onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_rotate.hpp
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/client_behaviors/cb_rotate.cpp