SMACC2: smacc2::components::CpTopicSubscriber< MessageType > Class Template Reference
smacc2::components::CpTopicSubscriber< MessageType > Class Template Reference
#include <cp_topic_subscriber.hpp>
Public Types
typedef MessageType TMessageType
Public Member Functions
CpTopicSubscriber ()
CpTopicSubscriber (std::string topicname)
virtual ~CpTopicSubscriber ()
template<typename T >
boost::signals2::connection onMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename T >
boost::signals2::connection onFirstMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual void initialize ()
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Attributes
std::optional< std::string > topicName
std::optional< int > queueSize
smacc2::SmaccSignal< void(const MessageType &)> onFirstMessageReceived_
smacc2::SmaccSignal< void(const MessageType &)> onMessageReceived_
std::function< void(const MessageType &)> postMessageEvent
std::function< void(const MessageType &)> postInitialMessageEvent
Protected Member Functions
rclcpp::Node::SharedPtr getNode ()
Protected Member Functions inherited from smacc2::ISmaccComponent
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Private Member Functions
void messageCallback (const MessageType &msg)
Private Attributes
ros::Subscriber sub_
bool firstMessage_
bool initialized_
std::string topicName_
Additional Inherited Members
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
template<typename MessageType>
class smacc2::components::CpTopicSubscriber< MessageType >
Definition at line 28 of file cp_topic_subscriber.hpp.
Member Typedef Documentation
TMessageType
template<typename MessageType > typedef MessageType smacc2::components::CpTopicSubscriber< MessageType >::TMessageType
Definition at line 34 of file cp_topic_subscriber.hpp.
Constructor & Destructor Documentation
CpTopicSubscriber() [1/2]
template<typename MessageType > smacc2::components::CpTopicSubscriber< MessageType >::CpTopicSubscriber () inline
Definition at line 36 of file cp_topic_subscriber.hpp.
{ initialized_ = false; }
References smacc2::components::CpTopicSubscriber< MessageType >::initialized_.
CpTopicSubscriber() [2/2]
template<typename MessageType > smacc2::components::CpTopicSubscriber< MessageType >::CpTopicSubscriber (std::string topicname) inline
Definition at line 38 of file cp_topic_subscriber.hpp.
{ topicName = topicname; }
References smacc2::components::CpTopicSubscriber< MessageType >::topicName.
~CpTopicSubscriber()
template<typename MessageType > virtual smacc2::components::CpTopicSubscriber< MessageType >::~CpTopicSubscriber () inline virtual
Definition at line 40 of file cp_topic_subscriber.hpp.
{ sub_.shutdown(); }
References smacc2::components::CpTopicSubscriber< MessageType >::sub_.
Member Function Documentation
getNode()
template<typename MessageType > rclcpp::Node::SharedPtr smacc2::components::CpTopicSubscriber< MessageType >::getNode () protected
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::initialize().
initialize()
template<typename MessageType > virtual void smacc2::components::CpTopicSubscriber< MessageType >::initialize () inline virtual
Definition at line 79 of file cp_topic_subscriber.hpp.
  {
    if (!initialized_)
    {
      firstMessage_ = true;
      if (!queueSize) queueSize = 1;
      if (!topicName)
      {
        RCLCPP_ERROR(getLogger(), "topic client with no topic name set. Skipping subscribing");
      }
      else
      {
        RCLCPP_INFO_STREAM(
          getLogger(), "[" << this->getName() << "] Subscribing to topic: " << topicName);
        sub_ = getNode()->subscribe(
          *topicName, *queueSize, &CpTopicSubscriber<MessageType>::messageCallback, this);
        this->initialized_ = true;
      }
    }
  }
References smacc2::components::CpTopicSubscriber< MessageType >::firstMessage_, smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getName(), smacc2::components::CpTopicSubscriber< MessageType >::getNode(), smacc2::components::CpTopicSubscriber< MessageType >::initialized_, smacc2::components::CpTopicSubscriber< MessageType >::queueSize, smacc2::components::CpTopicSubscriber< MessageType >::sub_, and smacc2::components::CpTopicSubscriber< MessageType >::topicName.
messageCallback()
template<typename MessageType > void smacc2::components::CpTopicSubscriber< MessageType >::messageCallback (const MessageType & msg) inline private
Definition at line 112 of file cp_topic_subscriber.hpp.
  {
    if (firstMessage_)
    {
      postInitialMessageEvent(msg);
      onFirstMessageReceived_(msg);
      firstMessage_ = false;
    }
    postMessageEvent(msg);
    onMessageReceived_(msg);
  }
References smacc2::components::CpTopicSubscriber< MessageType >::firstMessage_, smacc2::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived_, smacc2::components::CpTopicSubscriber< MessageType >::onMessageReceived_, smacc2::components::CpTopicSubscriber< MessageType >::postInitialMessageEvent, and smacc2::components::CpTopicSubscriber< MessageType >::postMessageEvent.
onFirstMessageReceived()
template<typename MessageType > template<typename T > boost::signals2::connection smacc2::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived (void(T::*)(const MessageType &) callback, T * object) inline
Definition at line 56 of file cp_topic_subscriber.hpp.
  {
    return this->getStateMachine()->createSignalConnection(
      onFirstMessageReceived_, callback, object);
  }
References smacc2::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived_.
onMessageReceived()
template<typename MessageType > template<typename T > boost::signals2::connection smacc2::components::CpTopicSubscriber< MessageType >::onMessageReceived (void(T::*)(const MessageType &) callback, T * object) inline
Definition at line 49 of file cp_topic_subscriber.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onMessageReceived_, callback, object);
  }
References smacc2::components::CpTopicSubscriber< MessageType >::onMessageReceived_.
onOrthogonalAllocation()
template<typename MessageType > template<typename TOrthogonal , typename TSourceObject > void smacc2::components::CpTopicSubscriber< MessageType >::onOrthogonalAllocation () inline
Definition at line 64 of file cp_topic_subscriber.hpp.
  {
    this->postMessageEvent = [=](auto msg) {
      auto event = new EvTopicMessage<TSourceObject, TOrthogonal>();
      event->msgData = msg;
      this->postEvent(event);
    };
    this->postInitialMessageEvent = [=](auto msg) {
      auto event = new EvTopicInitialMessage<TSourceObject, TOrthogonal>();
      event->msgData = msg;
      this->postEvent(event);
    };
  }
References smacc2::ISmaccComponent::postEvent().
Member Data Documentation
firstMessage_
template<typename MessageType > bool smacc2::components::CpTopicSubscriber< MessageType >::firstMessage_ private
Definition at line 108 of file cp_topic_subscriber.hpp.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::initialize(), and smacc2::components::CpTopicSubscriber< MessageType >::messageCallback().
initialized_
template<typename MessageType > bool smacc2::components::CpTopicSubscriber< MessageType >::initialized_ private
Definition at line 109 of file cp_topic_subscriber.hpp.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::CpTopicSubscriber(), and smacc2::components::CpTopicSubscriber< MessageType >::initialize().
onFirstMessageReceived_
template<typename MessageType > smacc2::SmaccSignal<void(const MessageType &)> smacc2::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived_
Definition at line 42 of file cp_topic_subscriber.hpp.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::messageCallback(), and smacc2::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived().
onMessageReceived_
template<typename MessageType > smacc2::SmaccSignal<void(const MessageType &)> smacc2::components::CpTopicSubscriber< MessageType >::onMessageReceived_
Definition at line 43 of file cp_topic_subscriber.hpp.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::messageCallback(), and smacc2::components::CpTopicSubscriber< MessageType >::onMessageReceived().
postInitialMessageEvent
template<typename MessageType > std::function<void(const MessageType &)> smacc2::components::CpTopicSubscriber< MessageType >::postInitialMessageEvent
Definition at line 46 of file cp_topic_subscriber.hpp.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::messageCallback().
postMessageEvent
template<typename MessageType > std::function<void(const MessageType &)> smacc2::components::CpTopicSubscriber< MessageType >::postMessageEvent
Definition at line 45 of file cp_topic_subscriber.hpp.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::messageCallback().
queueSize
template<typename MessageType > std::optional<int> smacc2::components::CpTopicSubscriber< MessageType >::queueSize
Definition at line 32 of file cp_topic_subscriber.hpp.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::initialize().
sub_
template<typename MessageType > ros::Subscriber smacc2::components::CpTopicSubscriber< MessageType >::sub_ private
Definition at line 107 of file cp_topic_subscriber.hpp.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::initialize(), and smacc2::components::CpTopicSubscriber< MessageType >::~CpTopicSubscriber().
topicName
template<typename MessageType > std::optional<std::string> smacc2::components::CpTopicSubscriber< MessageType >::topicName
Definition at line 31 of file cp_topic_subscriber.hpp.
Referenced by smacc2::components::CpTopicSubscriber< MessageType >::CpTopicSubscriber(), and smacc2::components::CpTopicSubscriber< MessageType >::initialize().
topicName_
template<typename MessageType > std::string smacc2::components::CpTopicSubscriber< MessageType >::topicName_ private
Definition at line 110 of file cp_topic_subscriber.hpp.
The documentation for this class was generated from the following file:
smacc2/include/smacc2/client_base_components/cp_topic_subscriber.hpp