SMACC2: smacc2::state_reactors::SrEventCountdown Class Reference
smacc2::state_reactors::SrEventCountdown Class Reference
#include <sr_event_countdown.hpp>
Public Member Functions
SrEventCountdown (int eventCount)
virtual void onInitialized () override
virtual void onEventNotified (const std::type_info *eventType) override
virtual bool triggers () override
Public Member Functions inherited from smacc2::StateReactor
StateReactor ()
virtual ~StateReactor ()
virtual void onInitialized ()
virtual void onEntry ()
virtual void onExit ()
virtual void onEventNotified (const std::type_info *eventType)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename T , typename TClass >
void createEventCallback (void(TClass::*callback)(T *), TClass *object)
template<typename T >
void createEventCallback (std::function< void(T *)> callback)
void update ()
virtual bool triggers ()=0
template<typename TEv >
void addInputEvent ()
template<typename TEv >
void setOutputEvent ()
void initialize (ISmaccState *ownerState)
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
Private Attributes
std::map< const std::type_info *, bool > triggeredEvents
int eventCount_
Additional Inherited Members
Public Attributes inherited from smacc2::StateReactor
ISmaccState * ownerState
std::function< void()> postEventFn
std::vector< const std::type_info * > eventTypes
std::map< const std::type_info *, std::function< void(void *)> > eventCallbacks_
Detailed Description
Definition at line 32 of file sr_event_countdown.hpp.
Constructor & Destructor Documentation
SrEventCountdown()
smacc2::state_reactors::SrEventCountdown::SrEventCountdown (int eventCount)
Definition at line 24 of file sr_event_countdown.cpp.
: eventCount_(eventCount) {}
Member Function Documentation
onEventNotified()
void smacc2::state_reactors::SrEventCountdown::onEventNotified (const std::type_info * eventType) override virtual
Reimplemented from smacc2::StateReactor.
Definition at line 34 of file sr_event_countdown.cpp.
{
  eventCount_--;
  RCLCPP_INFO_STREAM(
    getLogger(), "SB COUNTDOWN (" << eventCount_ << ") RECEIVED EVENT OF TYPE:"
                                  << demangleSymbol(eventType->name()));
  // RCLCPP_INFO_STREAM(getLogger(),"SB ALL RECEIVED EVENT OF TYPE:" << demangleSymbol(eventType->name()));
  // triggeredEvents[eventType] = true;
  // for (auto &entry : triggeredEvents)
  // {
  //     RCLCPP_INFO_STREAM(getLogger(),demangleSymbol(entry.first->name()) << " = " << entry.second);
  // }
}
References smacc2::introspection::demangleSymbol(), eventCount_, and smacc2::StateReactor::getLogger().
onInitialized()
void smacc2::state_reactors::SrEventCountdown::onInitialized () override virtual
Reimplemented from smacc2::StateReactor.
Definition at line 26 of file sr_event_countdown.cpp.
{
  for (auto type : eventTypes)
  {
    triggeredEvents[type] = false;
  }
}
References smacc2::StateReactor::eventTypes, and triggeredEvents.
triggers()
bool smacc2::state_reactors::SrEventCountdown::triggers () override virtual
Implements smacc2::StateReactor.
Definition at line 50 of file sr_event_countdown.cpp.
{
  if (eventCount_ == 0)
  {
    RCLCPP_INFO_STREAM(getLogger(), "SB COUNTDOWN (" << eventCount_ << ") TRIGGERS!");
    return true;
  }
  else
  {
    return false;
  }
  // RCLCPP_INFO(getLogger(),"SB All TRIGGERS?");
  // for (auto &entry : triggeredEvents)
  // {
  //     if (!entry.second)
  //         return false;
  // }
  // RCLCPP_INFO(getLogger(),"SB ALL TRIGGERED");
  // return true;
}
References eventCount_, and smacc2::StateReactor::getLogger().
Member Data Documentation
eventCount_
int smacc2::state_reactors::SrEventCountdown::eventCount_ private
Definition at line 36 of file sr_event_countdown.hpp.
Referenced by onEventNotified(), and triggers().
triggeredEvents
std::map<const std::type_info *, bool> smacc2::state_reactors::SrEventCountdown::triggeredEvents private
Definition at line 35 of file sr_event_countdown.hpp.
Referenced by onInitialized().
The documentation for this class was generated from the following files:
smacc2_state_reactor_library/sr_event_countdown/include/sr_event_countdown/sr_event_countdown.hpp
smacc2_state_reactor_library/sr_event_countdown/src/sr_event_countdown/sr_event_countdown.cpp