SMACC2: sm_dance_bot_strikes_back::OrNavigation Class Reference
sm_dance_bot_strikes_back::OrNavigation Class Reference
#include <or_navigation.hpp>
Public Member Functions
void onInitialize () override
void loadWaypointsFromYaml (WaypointNavigator *waypointsNavigator)
Public Member Functions inherited from smacc2::Orthogonal< OrNavigation >
std::shared_ptr< ClientHandler< OrNavigation, TClient > > createClient (TArgs... args)
Public Member Functions inherited from smacc2::ISmaccOrthogonal
void setStateMachine (ISmaccStateMachine *value)
ISmaccStateMachine * getStateMachine ()
void addClientBehavior (std::shared_ptr< smacc2::ISmaccClientBehavior > clientBehavior)
void runtimeConfigure ()
void onEntry ()
void onExit ()
virtual std::string getName () const
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
bool requiresClient (SmaccClientType *&storage)
const std::vector< std::shared_ptr< smacc2::ISmaccClient > > & getClients ()
const std::vector< std::shared_ptr< smacc2::ISmaccClientBehavior > > & getClientBehaviors () const
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename TClientBehavior >
TClientBehavior * getClientBehavior ()
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccOrthogonal
virtual void onInitialize ()
void initializeClients ()
template<typename TOrthogonal , typename TClient >
void assignClientToOrthogonal (TClient *client)
Protected Attributes inherited from smacc2::ISmaccOrthogonal
std::vector< std::shared_ptr< smacc2::ISmaccClient > > clients_
Detailed Description
Definition at line 31 of file or_navigation.hpp.
Member Function Documentation
loadWaypointsFromYaml()
void sm_dance_bot_strikes_back::OrNavigation::loadWaypointsFromYaml (WaypointNavigator * waypointsNavigator) inline
Definition at line 58 of file or_navigation.hpp.
  {
    // if it is the first time and the waypoints navigator is not configured
    std::string planfilepath;
    RCLCPP_INFO_STREAM(getLogger(), "Reasing parameter file from node: " << getNode()->get_name());
    getNode()->declare_parameter("waypoints_plan");
    if (getNode()->get_parameter("waypoints_plan", planfilepath))
    {
      std::string package_share_directory =
        ament_index_cpp::get_package_share_directory("sm_dance_bot");
      boost::replace_all(planfilepath, "$(pkg_share)", package_share_directory);
      waypointsNavigator->loadWayPointsFromFile(planfilepath);
      RCLCPP_INFO(getLogger(), "waypoints plan: %s", planfilepath.c_str());
    }
    else
    {
      RCLCPP_ERROR(getLogger(), "waypoints plan file not found: NONE");
    }
  }
References smacc2::ISmaccOrthogonal::getLogger(), smacc2::ISmaccOrthogonal::getNode(), and cl_move_base_z::WaypointNavigator::loadWayPointsFromFile().
Referenced by onInitialize().
onInitialize()
void sm_dance_bot_strikes_back::OrNavigation::onInitialize () inline override virtual
Reimplemented from smacc2::ISmaccOrthogonal.
Definition at line 34 of file or_navigation.hpp.
  {
    auto movebaseClient = this->createClient<ClMoveBaseZ>();
    // create pose component
    movebaseClient->createComponent<cl_move_base_z::Pose>();
    // create planner switcher
    movebaseClient->createComponent<PlannerSwitcher>();
    // create goal checker switcher
    movebaseClient->createComponent<cl_move_base_z::GoalCheckerSwitcher>();
    // create odom tracker
    movebaseClient->createComponent<cl_move_base_z::odom_tracker::OdomTracker>();
    // create waypoints navigator component
    auto waypointsNavigator = movebaseClient->createComponent<WaypointNavigator>();
    loadWaypointsFromYaml(waypointsNavigator);
    // change this to skip some points of the yaml file, default = 0
    waypointsNavigator->currentWaypoint_ = 0;
  }
References loadWaypointsFromYaml().
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_dance_bot_strikes_back/include/sm_dance_bot_strikes_back/orthogonals/or_navigation.hpp