SMACC2: keyboard_server_node.KeyboardPublisher Class Reference
keyboard_server_node.KeyboardPublisher Class Reference
Public Member Functions
def __init__ (self)
def timer_update (self)
Public Attributes
pub
timer
i
Detailed Description
Definition at line 39 of file keyboard_server_node.py.
Constructor & Destructor Documentation
__init__()
def keyboard_server_node.KeyboardPublisher.__init__ (self)
Definition at line 40 of file keyboard_server_node.py.
    def __init__(self):
        super().__init__("keyboard_node")
        self.pub = self.create_publisher(UInt16, "keyboard_unicode", 1)
        timer_period = 0.20  # seconds
        self.timer = self.create_timer(timer_period, self.timer_update)
        self.i = 0
References keyboard_server_node.KeyboardPublisher.__init__().
Referenced by keyboard_server_node.KeyboardPublisher.__init__().
Member Function Documentation
timer_update()
def keyboard_server_node.KeyboardPublisher.timer_update (self)
Definition at line 47 of file keyboard_server_node.py.
    def timer_update(self):
        try:
            key = getKey()
            # rospy.loginfo(type(key))
            msg = UInt16()
            msg.data = ord(key)
            self.pub.publish(msg)
        except Exception as e:
            print(e)
        finally:
            termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
References keyboard_server_node.getKey(), keyboard_server_node.KeyboardPublisher.pub, and keyboard_server_node.KeyboardPublisher.timer_update().
Referenced by keyboard_server_node.KeyboardPublisher.timer_update().
Member Data Documentation
i
keyboard_server_node.KeyboardPublisher.i
Definition at line 45 of file keyboard_server_node.py.
pub
keyboard_server_node.KeyboardPublisher.pub
Definition at line 42 of file keyboard_server_node.py.
Referenced by keyboard_server_node.KeyboardPublisher.timer_update().
timer
keyboard_server_node.KeyboardPublisher.timer
Definition at line 44 of file keyboard_server_node.py.
The documentation for this class was generated from the following file:
smacc2_client_library/keyboard_client/servers/keyboard_server_node.py