SMACC2: sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior Class Reference
sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior Class Reference
#include <cb_my_subscriber_behavior.hpp>
Public Member Functions
void onEntry ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onMessageReceived (const std_msgs::msg::Float32 &msg)
Public Member Functions inherited from smacc2::SmaccClientBehavior
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Attributes
std::function< void()> postMyEvent_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 27 of file cb_my_subscriber_behavior.hpp.
Member Function Documentation
onEntry()
void sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior::onEntry () inline virtual
Reimplemented from smacc2::SmaccClientBehavior.
Definition at line 30 of file cb_my_subscriber_behavior.hpp.
  {
    ClSubscriber * client;
    this->requiresClient(client);
    client->onMessageReceived(&CbMySubscriberBehavior::onMessageReceived, this);
  }
References onMessageReceived(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), and smacc2::ISmaccClientBehavior::requiresClient().
onMessageReceived()
void sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior::onMessageReceived (const std_msgs::msg::Float32 & msg) inline
Definition at line 44 of file cb_my_subscriber_behavior.hpp.
  {
    if (msg.data > 30)
    {
      RCLCPP_INFO(
        getLogger(),
        "[CbMySubscriberBehavior] received message from topic with value > 30. "
        "Posting event!");
      this->postMyEvent_();
    }
  }
References smacc2::ISmaccClientBehavior::getLogger(), and postMyEvent_.
Referenced by onEntry().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior::onOrthogonalAllocation () inline
Definition at line 39 of file cb_my_subscriber_behavior.hpp.
  {
    postMyEvent_ = [=] { this->postEvent<EvMyBehavior<TSourceObject, TOrthogonal>>(); };
  }
References postMyEvent_.
Member Data Documentation
postMyEvent_
std::function<void()> sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior::postMyEvent_
Definition at line 56 of file cb_my_subscriber_behavior.hpp.
Referenced by onMessageReceived(), and onOrthogonalAllocation().
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_pubsub_1/include/sm_pubsub_1/clients/cl_subscriber/client_behaviors/cb_my_subscriber_behavior.hpp