SMACC2: smacc2::client_bases::SmaccSubscriberClient< MessageType > Class Template Reference
smacc2::client_bases::SmaccSubscriberClient< MessageType > Class Template Reference
#include <smacc_subscriber_client.hpp>
Public Types
typedef MessageType TMessageType
Public Member Functions
SmaccSubscriberClient ()
SmaccSubscriberClient (std::string topicname)
virtual ~SmaccSubscriberClient ()
template<typename T >
boost::signals2::connection onMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename T >
boost::signals2::connection onFirstMessageReceived (void(T::*callback)(const MessageType &), T *object)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Public Attributes
std::optional< std::string > topicName
std::optional< int > queueSize
smacc2::SmaccSignal< void(const MessageType &)> onFirstMessageReceived_
smacc2::SmaccSignal< void(const MessageType &)> onMessageReceived_
std::function< void(const MessageType &)> postMessageEvent
std::function< void(const MessageType &)> postInitialMessageEvent
Protected Member Functions
void onInitialize () override
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Private Member Functions
void messageCallback (const MessageType &msg)
Private Attributes
rclcpp::Subscription< MessageType >::SharedPtr sub_
bool firstMessage_
bool initialized_
Additional Inherited Members
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Detailed Description
template<typename MessageType>
class smacc2::client_bases::SmaccSubscriberClient< MessageType >
Definition at line 38 of file smacc_subscriber_client.hpp.
Member Typedef Documentation
TMessageType
template<typename MessageType > typedef MessageType smacc2::client_bases::SmaccSubscriberClient< MessageType >::TMessageType
Definition at line 44 of file smacc_subscriber_client.hpp.
Constructor & Destructor Documentation
SmaccSubscriberClient() [1/2]
template<typename MessageType > smacc2::client_bases::SmaccSubscriberClient< MessageType >::SmaccSubscriberClient () inline
Definition at line 46 of file smacc_subscriber_client.hpp.
{ initialized_ = false; }
References smacc2::client_bases::SmaccSubscriberClient< MessageType >::initialized_.
SmaccSubscriberClient() [2/2]
template<typename MessageType > smacc2::client_bases::SmaccSubscriberClient< MessageType >::SmaccSubscriberClient (std::string topicname) inline
Definition at line 48 of file smacc_subscriber_client.hpp.
{ topicName = topicname; }
References smacc2::client_bases::SmaccSubscriberClient< MessageType >::topicName.
~SmaccSubscriberClient()
template<typename MessageType > virtual smacc2::client_bases::SmaccSubscriberClient< MessageType >::~SmaccSubscriberClient () inline virtual
Definition at line 50 of file smacc_subscriber_client.hpp.
{}
Member Function Documentation
messageCallback()
template<typename MessageType > void smacc2::client_bases::SmaccSubscriberClient< MessageType >::messageCallback (const MessageType & msg) inline private
Definition at line 126 of file smacc_subscriber_client.hpp.
  {
    if (firstMessage_)
    {
      postInitialMessageEvent(msg);
      onFirstMessageReceived_(msg);
      firstMessage_ = false;
    }
    postMessageEvent(msg);
    onMessageReceived_(msg);
  }
References smacc2::client_bases::SmaccSubscriberClient< MessageType >::firstMessage_, smacc2::client_bases::SmaccSubscriberClient< MessageType >::onFirstMessageReceived_, smacc2::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived_, smacc2::client_bases::SmaccSubscriberClient< MessageType >::postInitialMessageEvent, and smacc2::client_bases::SmaccSubscriberClient< MessageType >::postMessageEvent.
Referenced by smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize().
onFirstMessageReceived()
template<typename MessageType > template<typename T > boost::signals2::connection smacc2::client_bases::SmaccSubscriberClient< MessageType >::onFirstMessageReceived (void(T::*)(const MessageType &) callback, T * object) inline
Definition at line 66 of file smacc_subscriber_client.hpp.
  {
    return this->getStateMachine()->createSignalConnection(
      onFirstMessageReceived_, callback, object);
  }
References callback(), smacc2::ISmaccStateMachine::createSignalConnection(), and smacc2::ISmaccClient::getStateMachine().
onInitialize()
template<typename MessageType > void smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize () inline override protected virtual
Reimplemented from smacc2::ISmaccClient.
Reimplemented in cl_multirole_sensor::ClMultiroleSensor< MessageType >, cl_multirole_sensor::ClMultiroleSensor< sensor_msgs::msg::LaserScan >, and cl_multirole_sensor::ClMultiroleSensor< sensor_msgs::msg::Temperature >.
Definition at line 92 of file smacc_subscriber_client.hpp.
  {
    if (!initialized_)
    {
      firstMessage_ = true;
      if (!queueSize) queueSize = 1;
      if (!topicName)
      {
        RCLCPP_ERROR(getLogger(), "topic client with no topic name set. Skipping subscribing");
      }
      else
      {
        RCLCPP_INFO_STREAM(
          getLogger(), "[" << this->getName() << "] Subscribing to topic: " << *topicName);
        rclcpp::SensorDataQoS qos;
        if (queueSize) qos.keep_last(*queueSize);
        std::function<void(typename MessageType::SharedPtr)> fn = [this](auto msg) {
          this->messageCallback(*msg);
        };
        sub_ = getNode()->create_subscription<MessageType>(*topicName, qos, fn);
        this->initialized_ = true;
      }
    }
  }
References smacc2::client_bases::SmaccSubscriberClient< MessageType >::firstMessage_, smacc2::ISmaccClient::getLogger(), smacc2::ISmaccClient::getName(), smacc2::ISmaccClient::getNode(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::initialized_, smacc2::client_bases::SmaccSubscriberClient< MessageType >::messageCallback(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::queueSize, smacc2::client_bases::SmaccSubscriberClient< MessageType >::sub_, and smacc2::client_bases::SmaccSubscriberClient< MessageType >::topicName.
Referenced by cl_multirole_sensor::ClMultiroleSensor< MessageType >::onInitialize().
onMessageReceived()
template<typename MessageType > template<typename T > boost::signals2::connection smacc2::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived (void(T::*)(const MessageType &) callback, T * object) inline
Definition at line 59 of file smacc_subscriber_client.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onMessageReceived_, callback, object);
  }
References callback(), smacc2::ISmaccStateMachine::createSignalConnection(), and smacc2::ISmaccClient::getStateMachine().
Referenced by sm_ferrari::cl_subscriber::CbMySubscriberBehavior::onEntry(), sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior::onEntry(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::onInitialize(), sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::onInitialize(), sm_dance_bot_warehouse::cl_lidar::CpForwardObstacleDetector::onInitialize(), sm_dance_bot_warehouse_2::cl_lidar::CpForwardObstacleDetector::onInitialize(), and sm_dance_bot_warehouse_3::cl_lidar::CpForwardObstacleDetector::onInitialize().
onOrthogonalAllocation()
template<typename MessageType > template<typename TOrthogonal , typename TSourceObject > void smacc2::client_bases::SmaccSubscriberClient< MessageType >::onOrthogonalAllocation () inline
Definition at line 74 of file smacc_subscriber_client.hpp.
  {
    // ros topic message received smacc event callback
    this->postMessageEvent = [this](auto msg) {
      auto event = new EvTopicMessage<TSourceObject, TOrthogonal>();
      event->msgData = msg;
      this->postEvent(event);
    };
    // initial ros topic message received smacc event callback
    this->postInitialMessageEvent = [this](auto msg) {
      auto event = new EvTopicInitialMessage<TSourceObject, TOrthogonal>();
      event->msgData = msg;
      this->postEvent(event);
    };
  }
References smacc2::ISmaccClient::postEvent().
Member Data Documentation
firstMessage_
template<typename MessageType > bool smacc2::client_bases::SmaccSubscriberClient< MessageType >::firstMessage_ private
Definition at line 123 of file smacc_subscriber_client.hpp.
Referenced by smacc2::client_bases::SmaccSubscriberClient< MessageType >::messageCallback(), and smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize().
initialized_
template<typename MessageType > bool smacc2::client_bases::SmaccSubscriberClient< MessageType >::initialized_ private
Definition at line 124 of file smacc_subscriber_client.hpp.
Referenced by smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize(), and smacc2::client_bases::SmaccSubscriberClient< MessageType >::SmaccSubscriberClient().
onFirstMessageReceived_
template<typename MessageType > smacc2::SmaccSignal<void(const MessageType &)> smacc2::client_bases::SmaccSubscriberClient< MessageType >::onFirstMessageReceived_
Definition at line 52 of file smacc_subscriber_client.hpp.
Referenced by smacc2::client_bases::SmaccSubscriberClient< MessageType >::messageCallback().
onMessageReceived_
template<typename MessageType > smacc2::SmaccSignal<void(const MessageType &)> smacc2::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived_
Definition at line 53 of file smacc_subscriber_client.hpp.
Referenced by smacc2::client_bases::SmaccSubscriberClient< MessageType >::messageCallback().
postInitialMessageEvent
template<typename MessageType > std::function<void(const MessageType &)> smacc2::client_bases::SmaccSubscriberClient< MessageType >::postInitialMessageEvent
Definition at line 56 of file smacc_subscriber_client.hpp.
Referenced by smacc2::client_bases::SmaccSubscriberClient< MessageType >::messageCallback().
postMessageEvent
template<typename MessageType > std::function<void(const MessageType &)> smacc2::client_bases::SmaccSubscriberClient< MessageType >::postMessageEvent
Definition at line 55 of file smacc_subscriber_client.hpp.
Referenced by smacc2::client_bases::SmaccSubscriberClient< MessageType >::messageCallback().
queueSize
template<typename MessageType > std::optional<int> smacc2::client_bases::SmaccSubscriberClient< MessageType >::queueSize
Definition at line 42 of file smacc_subscriber_client.hpp.
Referenced by smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize().
sub_
template<typename MessageType > rclcpp::Subscription<MessageType>::SharedPtr smacc2::client_bases::SmaccSubscriberClient< MessageType >::sub_ private
Definition at line 122 of file smacc_subscriber_client.hpp.
Referenced by smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize().
topicName
template<typename MessageType > std::optional<std::string> smacc2::client_bases::SmaccSubscriberClient< MessageType >::topicName
Definition at line 41 of file smacc_subscriber_client.hpp.
Referenced by smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize(), and smacc2::client_bases::SmaccSubscriberClient< MessageType >::SmaccSubscriberClient().
The documentation for this class was generated from the following file:
smacc2/include/smacc2/client_bases/smacc_subscriber_client.hpp