SMACC2: cl_ros_timer::CbTimerCountdownLoop Class Reference
cl_ros_timer::CbTimerCountdownLoop Class Reference
#include <cb_timer_countdown_loop.hpp>
Public Member Functions
CbTimerCountdownLoop (unsigned long triggerTickCount)
void onEntry () override
void onEntry () override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename T >
boost::signals2::connection onTimerTick (void(T::*callback)(), T *object)
CbTimerCountdownLoop (unsigned long triggerTickCount)
void onEntry () override
void onExit () override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename T >
boost::signals2::connection onTimerTick (void(T::*callback)(), T *object)
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Member Functions
void onClientTimerTickCallback ()
void onClientTimerTickCallback ()
Private Attributes
unsigned long tickTriggerCount_
unsigned long tickCounter_
ClRosTimer * timerClient_
std::function< void()> postCountDownEvent_
smacc2::SmaccSignal< void()> onTimerTick_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 22 of file cb_timer_countdown_loop.hpp.
Constructor & Destructor Documentation
CbTimerCountdownLoop() [1/2]
cl_ros_timer::CbTimerCountdownLoop::CbTimerCountdownLoop (unsigned long triggerTickCount)
Definition at line 19 of file cb_timer_countdown_loop.cpp.
: tickTriggerCount_(triggerTickCount), tickCounter_(0)
{
}
CbTimerCountdownLoop() [2/2]
cl_ros_timer::CbTimerCountdownLoop::CbTimerCountdownLoop (unsigned long triggerTickCount) explicit
Member Function Documentation
onClientTimerTickCallback() [1/2]
void cl_ros_timer::CbTimerCountdownLoop::onClientTimerTickCallback () private
Definition at line 24 of file cb_timer_countdown_loop.cpp.
{
  tickCounter_++;
  if (tickCounter_ % tickTriggerCount_ == 0)
  {
    onTimerTick_();
    postCountDownEvent_();
  }
}
References onTimerTick_, postCountDownEvent_, tickCounter_, and tickTriggerCount_.
Referenced by onEntry().
onClientTimerTickCallback() [2/2]
void cl_ros_timer::CbTimerCountdownLoop::onClientTimerTickCallback () private
onEntry() [1/3]
void cl_ros_timer::CbTimerCountdownLoop::onEntry () override virtual
Reimplemented from smacc2::SmaccClientBehavior.
Definition at line 35 of file cb_timer_countdown_loop.cpp.
{
  this->requiresClient(timerClient_);
  timerClient_->onTimerTick(&CbTimerCountdownLoop::onClientTimerTickCallback, this);
}
References onClientTimerTickCallback(), cl_ros_timer::ClRosTimer::onTimerTick(), smacc2::ISmaccClientBehavior::requiresClient(), and timerClient_.
onEntry() [2/3]
void cl_ros_timer::CbTimerCountdownLoop::onEntry () override virtual
Reimplemented from smacc2::SmaccClientBehavior.
onEntry() [3/3]
void cl_ros_timer::CbTimerCountdownLoop::onEntry () override virtual
Reimplemented from smacc2::SmaccClientBehavior.
onExit()
void cl_ros_timer::CbTimerCountdownLoop::onExit () override virtual
Reimplemented from smacc2::SmaccClientBehavior.
Definition at line 41 of file cb_timer_countdown_loop.cpp.
{}
onOrthogonalAllocation() [1/2]
template<typename TOrthogonal , typename TSourceObject > void cl_ros_timer::CbTimerCountdownLoop::onOrthogonalAllocation () inline
Definition at line 31 of file cb_timer_countdown_loop.hpp.
  {
    this->postCountDownEvent_ = [=]() {
      this->template postEvent<EvTimer<TSourceObject, TOrthogonal>>();
    };
  }
References postCountDownEvent_.
onOrthogonalAllocation() [2/2]
template<typename TOrthogonal , typename TSourceObject > void cl_ros_timer::CbTimerCountdownLoop::onOrthogonalAllocation () inline
Definition at line 32 of file cb_timer_countdown_loop.hpp.
  {
    this->postCountDownEvent_ = [=]() {
      this->template postEvent<EvTimer<TSourceObject, TOrthogonal>>();
    };
  }
References postCountDownEvent_.
onTimerTick() [1/2]
template<typename T > boost::signals2::connection cl_ros_timer::CbTimerCountdownLoop::onTimerTick (void(T::*)() callback, T * object) inline
Definition at line 39 of file cb_timer_countdown_loop.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onTimerTick_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClientBehavior::getStateMachine(), and onTimerTick_.
onTimerTick() [2/2]
template<typename T > boost::signals2::connection cl_ros_timer::CbTimerCountdownLoop::onTimerTick (void(T::*)() callback, T * object) inline
Definition at line 40 of file cb_timer_countdown_loop.hpp.
  {
    return this->getStateMachine()->createSignalConnection(onTimerTick_, callback, object);
  }
References smacc2::ISmaccStateMachine::createSignalConnection(), smacc2::ISmaccClientBehavior::getStateMachine(), and onTimerTick_.
Member Data Documentation
onTimerTick_
smacc2::SmaccSignal< void()> cl_ros_timer::CbTimerCountdownLoop::onTimerTick_ private
Definition at line 50 of file cb_timer_countdown_loop.hpp.
Referenced by onClientTimerTickCallback(), and onTimerTick().
postCountDownEvent_
std::function< void()> cl_ros_timer::CbTimerCountdownLoop::postCountDownEvent_ private
Definition at line 49 of file cb_timer_countdown_loop.hpp.
Referenced by onClientTimerTickCallback(), and onOrthogonalAllocation().
tickCounter_
unsigned long cl_ros_timer::CbTimerCountdownLoop::tickCounter_ private
Definition at line 46 of file cb_timer_countdown_loop.hpp.
Referenced by onClientTimerTickCallback().
tickTriggerCount_
unsigned long cl_ros_timer::CbTimerCountdownLoop::tickTriggerCount_ private
Definition at line 45 of file cb_timer_countdown_loop.hpp.
Referenced by onClientTimerTickCallback().
timerClient_
ClRosTimer * cl_ros_timer::CbTimerCountdownLoop::timerClient_ private
Definition at line 48 of file cb_timer_countdown_loop.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/ros_timer_client/include/include/ros_timer_client/client_behaviors/cb_timer_countdown_loop.hpp
smacc2_client_library/ros_timer_client/include/ros_timer_client/client_behaviors/cb_timer_countdown_loop.hpp
smacc2_client_library/ros_timer_client/src/ros_timer_client/cb_timer_countdown_loop.cpp