SMACC2: sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData Class Reference
sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData Class Reference
#include <cp_lidar_data.hpp>
Public Member Functions
void onInitialize () override
void MessageCallbackStoreDistanceToWall (const sensor_msgs::msg::LaserScan &scanmsg)
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Attributes
sensor_msgs::msg::LaserScan lastMessage_
float forwardObstacleDistance
const float SECURITY_DISTANCE = 1
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 29 of file cp_lidar_data.hpp.
Member Function Documentation
MessageCallbackStoreDistanceToWall()
void sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::MessageCallbackStoreDistanceToWall (const sensor_msgs::msg::LaserScan & scanmsg) inline
Definition at line 45 of file cp_lidar_data.hpp.
  {
    this->lastMessage_ = scanmsg;
    //auto fwdist = scanmsg.ranges[scanmsg.ranges.size() / 2] /*meter*/;
    auto fwdist = scanmsg.ranges[0] /*meter*/;
    /*if the distance is infinity or nan, use max range distance*/
    if (fwdist == std::numeric_limits<float>::infinity() || fwdist != fwdist)
    {
      this->forwardObstacleDistance = scanmsg.range_max - SECURITY_DISTANCE /*meters*/;
      RCLCPP_INFO_THROTTLE(
        getLogger(), *(getNode()->get_clock()), 1000,
        "[CpLidarSensorData] Distance to forward obstacle is not a number, setting default value "
        "to: %lf",
        scanmsg.range_max);
    }
    else
    {
      this->forwardObstacleDistance = std::max(fwdist - SECURITY_DISTANCE, 0.0F);
    }
  }
References smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getNode(), and SECURITY_DISTANCE.
Referenced by onInitialize().
onInitialize()
void sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::onInitialize () inline override virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 37 of file cp_lidar_data.hpp.
  {
    auto client_ =
      dynamic_cast<smacc2::client_bases::SmaccSubscriberClient<sensor_msgs::msg::LaserScan> *>(
        owner_);
    client_->onMessageReceived(&CpLidarSensorData::MessageCallbackStoreDistanceToWall, this);
  }
References MessageCallbackStoreDistanceToWall(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), and smacc2::ISmaccComponent::owner_.
Member Data Documentation
forwardObstacleDistance
float sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::forwardObstacleDistance
Definition at line 33 of file cp_lidar_data.hpp.
lastMessage_
sensor_msgs::msg::LaserScan sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::lastMessage_
Definition at line 32 of file cp_lidar_data.hpp.
SECURITY_DISTANCE
const float sm_dance_bot_strikes_back::cl_lidar::CpLidarSensorData::SECURITY_DISTANCE = 1
Definition at line 35 of file cp_lidar_data.hpp.
Referenced by MessageCallbackStoreDistanceToWall().
The documentation for this class was generated from the following files:
smacc2_sm_reference_library/sm_dance_bot_strikes_back/include/sm_dance_bot_strikes_back/clients/cl_lidar/components/cp_lidar_data.hpp
smacc2_sm_reference_library/sm_dance_bot_strikes_back/src/sm_dance_bot_strikes_back/clients/cl_lidar/cp_lidar_data.cpp