SMACC2: cl_move_group_interface::CbWaitJointState Class Reference
cl_move_group_interface::CbWaitJointState Class Reference
#include <cb_wait_joint_states.hpp>
Public Member Functions
CbWaitJointState ()
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Private Member Functions
void onMessageReceived (const sensor_msgs::msg::JointState &msg)
Private Attributes
bool triggered = false
std::mutex mutex
rclcpp::Subscription< sensor_msgs::msg::JointState >::SharedPtr sub_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 32 of file cb_wait_joint_states.hpp.
Constructor & Destructor Documentation
CbWaitJointState()
cl_move_group_interface::CbWaitJointState::CbWaitJointState () inline
Definition at line 35 of file cb_wait_joint_states.hpp.
  {
  }
Member Function Documentation
onEntry()
void cl_move_group_interface::CbWaitJointState::onEntry () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 40 of file cb_wait_joint_states.hpp.
  {
    ClMoveGroup * movegroupClient_;
    requiresClient(movegroupClient_);
    //auto group_name = movegroupClient_->getOptions().group_name_;
    std::string ns =  movegroupClient_->getOptions().move_group_namespace_;
    //auto topicname = "/joint_state_broadcaster_"UR5PREFIX"/joint_states";
    std::string topicname = "/joint_states";
    if (!ns.empty())
    {
        topicname = ns + "/" + topicname;
    }
    //rclcpp::SensorDataQoS qos;
    rclcpp::SubscriptionOptions sub_option;
    sub_ = getNode()->create_subscription<sensor_msgs::msg::JointState>(
        topicname, 20, std::bind(&CbWaitJointState::onMessageReceived, this, std::placeholders::_1),
        sub_option);
        mutex.lock();
    }
References smacc2::ISmaccClientBehavior::getNode(), cl_move_group_interface::ClMoveGroup::getOptions(), mutex, onMessageReceived(), smacc2::ISmaccClientBehavior::requiresClient(), and sub_.
onMessageReceived()
void cl_move_group_interface::CbWaitJointState::onMessageReceived (const sensor_msgs::msg::JointState & msg) inline private
Definition at line 67 of file cb_wait_joint_states.hpp.
  {
      postSuccessEvent();
      mutex.unlock();
      sub_ = nullptr; // unsuscribe
  }
References mutex, smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), and sub_.
Referenced by onEntry().
Member Data Documentation
mutex
std::mutex cl_move_group_interface::CbWaitJointState::mutex private
Definition at line 75 of file cb_wait_joint_states.hpp.
Referenced by onEntry(), and onMessageReceived().
sub_
rclcpp::Subscription<sensor_msgs::msg::JointState>::SharedPtr cl_move_group_interface::CbWaitJointState::sub_ private
Definition at line 76 of file cb_wait_joint_states.hpp.
Referenced by onEntry(), and onMessageReceived().
triggered
bool cl_move_group_interface::CbWaitJointState::triggered = false private
Definition at line 74 of file cb_wait_joint_states.hpp.
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_multi_ur5_sim/include/sm_multi_ur5_sim/clients/move_group/client_behaviors/cb_wait_joint_states.hpp