SMACC2: smacc2::ISmaccClient Class Reference
smacc2::ISmaccClient Class Reference
#include <smacc_client.hpp>
Public Member Functions
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void onInitialize ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Protected Member Functions
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Private Member Functions
void initialize ()
void setStateMachine (ISmaccStateMachine *stateMachine)
void setOrthogonal (ISmaccOrthogonal *orthogonal)
Private Attributes
ISmaccStateMachine * stateMachine_
ISmaccOrthogonal * orthogonal_
Friends
class ISmaccOrthogonal
class ISmaccComponent
Detailed Description
Definition at line 44 of file smacc_client.hpp.
Constructor & Destructor Documentation
ISmaccClient()
smacc2::ISmaccClient::ISmaccClient ()
Definition at line 26 of file client.cpp.
{}
~ISmaccClient()
smacc2::ISmaccClient::~ISmaccClient () virtual
Definition at line 28 of file client.cpp.
{}
Member Function Documentation
connectSignal()
template<typename TSmaccSignal , typename T > void smacc2::ISmaccClient::connectSignal (TSmaccSignal & signal, void(T::*)() callback, T * object)
Definition at line 138 of file smacc_client_impl.hpp.
{
  return this->getStateMachine()->createSignalConnection(signal, callback, object);
}
References callback(), smacc2::ISmaccStateMachine::createSignalConnection(), and getStateMachine().
createComponent()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs> SmaccComponentType * smacc2::ISmaccClient::createComponent (TArgs... targs) protected
Definition at line 131 of file smacc_client_impl.hpp.
{
  return this->createNamedComponent<SmaccComponentType, TOrthogonal, TClient>(
    std::string(), targs...);
}
Referenced by smacc2::ClientHandler< TOrthogonal, TClient >::createComponent(), and smacc2::ISmaccComponent::createSiblingComponent().
createNamedComponent()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs> SmaccComponentType * smacc2::ISmaccClient::createNamedComponent (std::string name, TArgs... targs) protected
Definition at line 91 of file smacc_client_impl.hpp.
{
  ComponentKey componentkey(&typeid(SmaccComponentType), name);
  std::shared_ptr<SmaccComponentType> ret;
  auto it = this->components_.find(componentkey);
  if (it == this->components_.end())
  {
    auto tname = demangledTypeName<SmaccComponentType>();
    RCLCPP_INFO(
      getLogger(),
      "Creating a new component of type %s smacc component is required by client '%s'. Creating a "
      "new instance %s",
      this->getName().c_str(), demangledTypeName<SmaccComponentType>().c_str(), tname.c_str());
    ret = std::shared_ptr<SmaccComponentType>(new SmaccComponentType(targs...));
    ret->setStateMachine(this->getStateMachine());
    ret->owner_ = this;
    ret->initialize(this);
    this->components_[componentkey] =
      ret;  //std::dynamic_pointer_cast<smacc2::ISmaccComponent>(ret);
    RCLCPP_DEBUG(getLogger(), "%s resource is required. Done.", tname.c_str());
  }
  else
  {
    RCLCPP_INFO(
      getLogger(), "%s resource is required. Found resource in cache.",
      demangledTypeName<SmaccComponentType>().c_str());
    ret = dynamic_pointer_cast<SmaccComponentType>(it->second);
  }
  ret->template onOrthogonalAllocation<TOrthogonal, TClient>();
  return ret.get();
}
References components_, getLogger(), getName(), and getStateMachine().
Referenced by smacc2::ClientHandler< TOrthogonal, TClient >::createNamedComponent(), and smacc2::ISmaccComponent::createSiblingNamedComponent().
getComponent() [1/3]
template<typename TComponent > TComponent * smacc2::ISmaccClient::getComponent
Definition at line 41 of file smacc_client_impl.hpp.
{
  return this->getComponent<TComponent>(std::string());
}
Referenced by cl_nav2z::CbNavigateGlobalPosition::execute(), cl_nav2z::CbAbsoluteRotate::onEntry(), cl_nav2z::CbNavigateBackwards::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbNavigateGlobalPosition::onEntry(), cl_nav2z::CbNavigateNamedWaypoint::onEntry(), cl_nav2z::CbNavigateNextWaypoint::onEntry(), cl_nav2z::CbRotate::onEntry(), cl_nav2z::CbSeekWaypoint::onEntry(), cl_nav2z::CbUndoPathBackwards::onEntry(), cl_nav2z::CbWaitPose::onEntry(), sm_dance_bot::radial_motion_states::StiRadialReturn::onExit(), sm_dance_bot_strikes_back::radial_motion_states::StiRadialReturn::onExit(), cl_nav2z::CbUndoPathBackwards::onExit(), sm_autoware_avp::clients::ClAutoware::onInitialize(), cl_nav2z::CbNavigateNextWaypointUntilReached::onNavigationActionSuccess(), smacc2::ISmaccComponent::requiresComponent(), sm_dance_bot_strikes_back::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_strikes_back::radial_motion_states::StiRadialEndPoint::runtimeConfigure(), sm_dance_bot_strikes_back::s_pattern_states::StiSPatternForward2::runtimeConfigure(), sm_dance_bot_strikes_back::s_pattern_states::StiSPatternForward4::runtimeConfigure(), sm_dance_bot_warehouse::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternForward1::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternForward2::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternForward3::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternForward4::runtimeConfigure(), sm_dance_bot_warehouse_2::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternForward1::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternForward2::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternForward3::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternForward4::runtimeConfigure(), sm_husky_barrel_search_1::StFire::runtimeConfigure(), and cl_nav2z::WaypointNavigator::sendNextGoal().
getComponent() [2/3]
template<typename TComponent > TComponent * smacc2::ISmaccClient::getComponent (int index)
Definition at line 47 of file smacc_client_impl.hpp.
{
  int count = 0;
  for (auto & component : components_)
  {
    auto * tcomponent = dynamic_cast<TComponent *>(component.second.get());
    if (tcomponent != nullptr)
    {
      if (count == index)
      {
        return tcomponent;
      }
      else
      {
        count++;
        continue;
      }
    }
  }
  return nullptr;
}
References components_.
getComponent() [3/3]
template<typename TComponent > TComponent * smacc2::ISmaccClient::getComponent (std::string name)
Definition at line 71 of file smacc_client_impl.hpp.
{
  for (auto & component : components_)
  {
    if (!name.empty() && component.first.name != name) continue;
    auto * tcomponent = dynamic_cast<TComponent *>(component.second.get());
    if (tcomponent != nullptr)
    {
      return tcomponent;
    }
  }
  return nullptr;
}
References components_.
getComponents()
void smacc2::ISmaccClient::getComponents (std::vector< std::shared_ptr< ISmaccComponent > > & components)
Definition at line 34 of file client.cpp.
{
  for (auto & ce : components_)
  {
    components.push_back(ce.second);
  }
}
References components_.
Referenced by smacc2::ISmaccComponent::requiresComponent().
getLogger()
rclcpp::Logger smacc2::ISmaccClient::getLogger () inline protected
Definition at line 105 of file smacc_client.hpp.
{ return getNode()->get_logger(); }
References getNode().
Referenced by sm_autoware_avp::clients::ClAutoware::checkGoalReached(), smacc2::client_bases::SmaccPublisherClient::configure(), createNamedComponent(), smacc2::ISmaccComponent::getLogger(), sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception::MessageCallback(), smacc2::client_bases::SmaccServiceClient< ServiceType >::onInitialize(), smacc2::client_bases::SmaccServiceServerClient< TService >::onInitialize(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::onInitialize(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), cl_keyboard::ClKeyboard::onOrthogonalAllocation(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onResult(), cl_move_group_interface::ClMoveGroup::postEventMotionExecutionFailed(), cl_move_group_interface::ClMoveGroup::postEventMotionExecutionSucceded(), cl_keyboard::ClKeyboard::postKeyEvent(), smacc2::client_bases::SmaccActionClientBase< ActionType >::postResultEvent(), and smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
getName()
std::string smacc2::ISmaccClient::getName () const virtual
Reimplemented in smacc2::client_bases::ISmaccActionClient, sm_dance_bot::cl_led::ClLED, sm_dance_bot_strikes_back::cl_led::ClLED, sm_dance_bot_warehouse::cl_led::ClLED, sm_dance_bot_warehouse_2::cl_led::ClLED, and sm_dance_bot_warehouse_3::cl_led::ClLED.
Definition at line 42 of file client.cpp.
{
  std::string keyname = demangleSymbol(typeid(*this).name());
  return keyname;
}
References smacc2::introspection::demangleSymbol().
Referenced by sm_autoware_avp::clients::ClAutoware::checkGoalReached(), smacc2::client_bases::SmaccPublisherClient::configure(), createNamedComponent(), smacc2::client_bases::SmaccServiceClient< ServiceType >::onInitialize(), smacc2::client_bases::SmaccServiceServerClient< TService >::onInitialize(), and smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize().
getNode()
rclcpp::Node::SharedPtr smacc2::ISmaccClient::getNode () protected
Definition at line 60 of file client.cpp.
{ return this->getStateMachine()->getNode(); }
References smacc2::ISmaccStateMachine::getNode(), and getStateMachine().
Referenced by sm_autoware_avp::clients::ClAutoware::checkGoalReached(), smacc2::client_bases::SmaccPublisherClient::configure(), getLogger(), smacc2::ISmaccComponent::getNode(), sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception::MessageCallback(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onInitialize(), smacc2::client_bases::SmaccServiceClient< ServiceType >::onInitialize(), smacc2::client_bases::SmaccServiceServerClient< TService >::onInitialize(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize(), cl_move_group_interface::ClMoveGroup::onInitialize(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::onInitialize(), and cl_ros_timer::ClRosTimer::onInitialize().
getStateMachine()
ISmaccStateMachine * smacc2::ISmaccClient::getStateMachine () inline
Definition at line 88 of file smacc_client_impl.hpp.
{ return this->stateMachine_; }
References stateMachine_.
Referenced by connectSignal(), createNamedComponent(), getNode(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onAborted(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onCancelled(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onFirstMessageReceived(), cl_keyboard::ClKeyboard::OnKeyPress(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::onMessageTimeout(), cl_move_group_interface::ClMoveGroup::onMotionExecutionFailed(), cl_move_group_interface::ClMoveGroup::onMotionExecutionSuccedded(), smacc2::client_bases::SmaccServiceServerClient< TService >::onServiceRequestReceived(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), cl_ros_timer::ClRosTimer::onTimerTick(), and cl_nav2z::WaypointNavigator::sendNextGoal().
getType()
smacc2::introspection::TypeInfo::Ptr smacc2::ISmaccClient::getType () virtual
Definition at line 55 of file client.cpp.
{
  return smacc2::introspection::TypeInfo::getFromStdTypeInfo(typeid(*this));
}
References smacc2::introspection::TypeInfo::getFromStdTypeInfo().
initialize()
void smacc2::ISmaccClient::initialize () private
Definition at line 30 of file client.cpp.
{ this->onInitialize(); }
References onInitialize().
iterateComponents()
const std::vector< std::shared_ptr< ISmaccComponent > > & smacc2::ISmaccClient::iterateComponents () const
onInitialize()
void smacc2::ISmaccClient::onInitialize () virtual
Reimplemented in smacc2::client_bases::SmaccActionClientBase< ActionType >, smacc2::client_bases::SmaccActionClientBase< nav2_msgs::action::NavigateToPose >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot::action::LEDControl >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_strikes_back::action::LEDControl >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_warehouse::action::LEDControl >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_warehouse_2::action::LEDControl >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_warehouse_3::action::LEDControl >, smacc2::client_bases::SmaccServiceClient< ServiceType >, smacc2::client_bases::SmaccServiceClient< std_srvs::srv::Empty >, smacc2::client_bases::SmaccServiceClient< std_srvs::srv::SetBool >, smacc2::client_bases::SmaccServiceServerClient< TService >, smacc2::client_bases::SmaccServiceServerClient< std_srvs::srv::Empty >, smacc2::client_bases::SmaccSubscriberClient< MessageType >, smacc2::client_bases::SmaccSubscriberClient< std_msgs::msg::UInt16 >, smacc2::client_bases::SmaccSubscriberClient< sensor_msgs::msg::LaserScan >, smacc2::client_bases::SmaccSubscriberClient< sensor_msgs::msg::Temperature >, smacc2::client_bases::SmaccSubscriberClient< std_msgs::msg::Float32 >, smacc2::client_bases::SmaccSubscriberClient< sm_husky_barrel_search_1::msg::DetectedObjects >, smacc2::client_bases::SmaccSubscriberClient< TMsg >, cl_keyboard::ClKeyboard, cl_move_group_interface::ClMoveGroup, cl_multirole_sensor::ClMultiroleSensor< MessageType >, cl_multirole_sensor::ClMultiroleSensor< sensor_msgs::msg::LaserScan >, cl_multirole_sensor::ClMultiroleSensor< sensor_msgs::msg::Temperature >, cl_ros_timer::ClRosTimer, sm_autoware_avp::clients::ClAutoware, sm_dance_bot::cl_string_publisher::ClStringPublisher, sm_dance_bot_strikes_back::cl_string_publisher::ClStringPublisher, sm_dance_bot_warehouse::cl_string_publisher::ClStringPublisher, sm_dance_bot_warehouse_2::cl_string_publisher::ClStringPublisher, sm_dance_bot_warehouse_3::cl_string_publisher::ClStringPublisher, sm_husky_barrel_search_1::cl_led_array::ClLedArray, and sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception.
Definition at line 32 of file client.cpp.
{}
Referenced by initialize().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc2::ISmaccClient::onOrthogonalAllocation () inline protected
Definition at line 90 of file smacc_client.hpp.
  {
  }
postEvent() [1/2]
template<typename EventType > void smacc2::ISmaccClient::postEvent
Definition at line 35 of file smacc_client_impl.hpp.
{
  stateMachine_->postEvent<EventType>();
}
References smacc2::ISmaccStateMachine::postEvent(), and stateMachine_.
Referenced by smacc2::client_bases::SmaccActionClientBase< ActionType >::onOrthogonalAllocation(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onOrthogonalAllocation(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::onOrthogonalAllocation(), sm_autoware_avp::clients::ClAutoware::onOrthogonalAllocation(), and smacc2::client_bases::SmaccActionClientBase< ActionType >::postResultEvent().
postEvent() [2/2]
template<typename EventType > void smacc2::ISmaccClient::postEvent (const EventType & ev)
Definition at line 29 of file smacc_client_impl.hpp.
{
  stateMachine_->postEvent(ev);
}
References smacc2::ISmaccStateMachine::postEvent(), and stateMachine_.
requiresClient()
template<typename SmaccClientType > void smacc2::ISmaccClient::requiresClient (SmaccClientType *& storage)
Definition at line 144 of file smacc_client_impl.hpp.
{
  this->orthogonal_->requiresClient(storage);
}
References orthogonal_, and smacc2::ISmaccOrthogonal::requiresClient().
Referenced by smacc2::ISmaccComponent::requiresClient().
setOrthogonal()
void smacc2::ISmaccClient::setOrthogonal (ISmaccOrthogonal * orthogonal) private
Definition at line 53 of file client.cpp.
{ orthogonal_ = orthogonal; }
References orthogonal_.
setStateMachine()
void smacc2::ISmaccClient::setStateMachine (ISmaccStateMachine * stateMachine) private
Definition at line 48 of file client.cpp.
{
  stateMachine_ = stateMachine;
}
References stateMachine_.
Friends And Related Function Documentation
ISmaccComponent
friend class ISmaccComponent friend
Definition at line 123 of file smacc_client.hpp.
ISmaccOrthogonal
friend class ISmaccOrthogonal friend
Definition at line 122 of file smacc_client.hpp.
Member Data Documentation
components_
std::map<ComponentKey, std::shared_ptr<smacc2::ISmaccComponent> > smacc2::ISmaccClient::components_ protected
Definition at line 95 of file smacc_client.hpp.
Referenced by createNamedComponent(), getComponent(), and getComponents().
orthogonal_
ISmaccOrthogonal* smacc2::ISmaccClient::orthogonal_ private
Definition at line 110 of file smacc_client.hpp.
Referenced by requiresClient(), and setOrthogonal().
stateMachine_
ISmaccStateMachine* smacc2::ISmaccClient::stateMachine_ private
Definition at line 109 of file smacc_client.hpp.
Referenced by getStateMachine(), postEvent(), and setStateMachine().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/smacc_client.hpp
smacc2/include/smacc2/impl/smacc_client_impl.hpp
smacc2/src/smacc2/client.cpp