SMACC2: LEDActionServer Class Reference
LEDActionServer Class Reference
Public Types
using GoalHandleLEDControl = rclcpp_action::ServerGoalHandle< sm_dance_bot::action::LEDControl >
using GoalHandleLEDControl = rclcpp_action::ServerGoalHandle< sm_dance_bot_strikes_back::action::LEDControl >
using GoalHandleLEDControl = rclcpp_action::ServerGoalHandle< sm_dance_bot_warehouse::action::LEDControl >
using GoalHandleLEDControl = rclcpp_action::ServerGoalHandle< sm_dance_bot_warehouse_2::action::LEDControl >
using GoalHandleLEDControl = rclcpp_action::ServerGoalHandle< sm_dance_bot_warehouse_3::action::LEDControl >
Public Member Functions
LEDActionServer (const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
void execute (const std::shared_ptr< GoalHandleLEDControl > gh)
rclcpp_action::GoalResponse handle_goal (const rclcpp_action::GoalUUID &, std::shared_ptr< const sm_dance_bot::action::LEDControl::Goal >)
rclcpp_action::CancelResponse handle_cancel (const std::shared_ptr< GoalHandleLEDControl >)
void handle_accepted (const std::shared_ptr< GoalHandleLEDControl > goal_handle)
void run ()
void publishStateMarker ()
LEDActionServer (const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
void execute (const std::shared_ptr< GoalHandleLEDControl > gh)
rclcpp_action::GoalResponse handle_goal (const rclcpp_action::GoalUUID &, std::shared_ptr< const sm_dance_bot_strikes_back::action::LEDControl::Goal >)
rclcpp_action::CancelResponse handle_cancel (const std::shared_ptr< GoalHandleLEDControl >)
void handle_accepted (const std::shared_ptr< GoalHandleLEDControl > goal_handle)
void run ()
void publishStateMarker ()
LEDActionServer (const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
void execute (const std::shared_ptr< GoalHandleLEDControl > gh)
rclcpp_action::GoalResponse handle_goal (const rclcpp_action::GoalUUID &, std::shared_ptr< const sm_dance_bot_warehouse::action::LEDControl::Goal >)
rclcpp_action::CancelResponse handle_cancel (const std::shared_ptr< GoalHandleLEDControl >)
void handle_accepted (const std::shared_ptr< GoalHandleLEDControl > goal_handle)
void run ()
void publishStateMarker ()
LEDActionServer (const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
void execute (const std::shared_ptr< GoalHandleLEDControl > gh)
rclcpp_action::GoalResponse handle_goal (const rclcpp_action::GoalUUID &, std::shared_ptr< const sm_dance_bot_warehouse_2::action::LEDControl::Goal >)
rclcpp_action::CancelResponse handle_cancel (const std::shared_ptr< GoalHandleLEDControl >)
void handle_accepted (const std::shared_ptr< GoalHandleLEDControl > goal_handle)
void run ()
void publishStateMarker ()
LEDActionServer (const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
void execute (const std::shared_ptr< GoalHandleLEDControl > gh)
rclcpp_action::GoalResponse handle_goal (const rclcpp_action::GoalUUID &, std::shared_ptr< const sm_dance_bot_warehouse_3::action::LEDControl::Goal >)
rclcpp_action::CancelResponse handle_cancel (const std::shared_ptr< GoalHandleLEDControl >)
void handle_accepted (const std::shared_ptr< GoalHandleLEDControl > goal_handle)
void run ()
void publishStateMarker ()
Public Attributes
std::shared_ptr< rclcpp_action::Server< sm_dance_bot::action::LEDControl > > as_
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr stateMarkerPublisher_
uint8_t cmd
uint8_t currentState_
std::shared_ptr< rclcpp_action::Server< sm_dance_bot_strikes_back::action::LEDControl > > as_
std::shared_ptr< rclcpp_action::Server< sm_dance_bot_warehouse::action::LEDControl > > as_
std::shared_ptr< rclcpp_action::Server< sm_dance_bot_warehouse_2::action::LEDControl > > as_
std::shared_ptr< rclcpp_action::Server< sm_dance_bot_warehouse_3::action::LEDControl > > as_
Detailed Description
Definition at line 39 of file led_action_server_node.cpp.
Member Typedef Documentation
GoalHandleLEDControl [1/5]
using LEDActionServer::GoalHandleLEDControl = rclcpp_action::ServerGoalHandle<sm_dance_bot::action::LEDControl>
Definition at line 43 of file led_action_server_node.cpp.
GoalHandleLEDControl [2/5]
using LEDActionServer::GoalHandleLEDControl = rclcpp_action::ServerGoalHandle<sm_dance_bot_strikes_back::action::LEDControl>
Definition at line 43 of file led_action_server_node.cpp.
GoalHandleLEDControl [3/5]
using LEDActionServer::GoalHandleLEDControl = rclcpp_action::ServerGoalHandle<sm_dance_bot_warehouse::action::LEDControl>
Definition at line 43 of file led_action_server_node.cpp.
GoalHandleLEDControl [4/5]
using LEDActionServer::GoalHandleLEDControl = rclcpp_action::ServerGoalHandle<sm_dance_bot_warehouse_2::action::LEDControl>
Definition at line 43 of file led_action_server_node.cpp.
GoalHandleLEDControl [5/5]
using LEDActionServer::GoalHandleLEDControl = rclcpp_action::ServerGoalHandle<sm_dance_bot_warehouse_3::action::LEDControl>
Definition at line 43 of file led_action_server_node.cpp.
Constructor & Destructor Documentation
LEDActionServer() [1/5]
LEDActionServer::LEDActionServer (const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) inline
constructor()
Definition at line 57 of file led_action_server_node.cpp.
  : Node("led_action_server_node", options)
  {
    currentState_ = sm_dance_bot::action::LEDControl::Result::STATE_UNKNOWN;
  }
References currentState_.
LEDActionServer() [2/5]
LEDActionServer::LEDActionServer (const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) inline
constructor()
Definition at line 57 of file led_action_server_node.cpp.
  : Node("led_action_server_node", options)
  {
    currentState_ = sm_dance_bot_strikes_back::action::LEDControl::Result::STATE_UNKNOWN;
  }
References currentState_.
LEDActionServer() [3/5]
LEDActionServer::LEDActionServer (const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) inline
constructor()
Definition at line 57 of file led_action_server_node.cpp.
  : Node("led_action_server_node", options)
  {
    currentState_ = sm_dance_bot_warehouse::action::LEDControl::Result::STATE_UNKNOWN;
  }
References currentState_.
LEDActionServer() [4/5]
LEDActionServer::LEDActionServer (const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) inline
constructor()
Definition at line 57 of file led_action_server_node.cpp.
  : Node("led_action_server_node", options)
  {
    currentState_ = sm_dance_bot_warehouse_2::action::LEDControl::Result::STATE_UNKNOWN;
  }
References currentState_.
LEDActionServer() [5/5]
LEDActionServer::LEDActionServer (const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) inline
constructor()
Definition at line 57 of file led_action_server_node.cpp.
  : Node("led_action_server_node", options)
  {
    currentState_ = sm_dance_bot_warehouse_3::action::LEDControl::Result::STATE_UNKNOWN;
  }
References currentState_.
Member Function Documentation
execute() [1/5]
void LEDActionServer::execute (const std::shared_ptr< GoalHandleLEDControl > gh) inline
execute()
Definition at line 68 of file led_action_server_node.cpp.
  {
    auto goal = gh->get_goal();
    RCLCPP_INFO_STREAM(get_logger(), "Tool action server request: " << goal->command);
    cmd = goal->command;
    if (goal->command == sm_dance_bot::action::LEDControl_Goal::CMD_ON)
    {
      RCLCPP_INFO(this->get_logger(), "ON");
      currentState_ = sm_dance_bot::action::LEDControl_Result::STATE_RUNNING;
    }
    else if (goal->command == sm_dance_bot::action::LEDControl_Goal::CMD_OFF)
    {
      RCLCPP_INFO(this->get_logger(), "OFF");
      currentState_ = sm_dance_bot::action::LEDControl_Result::STATE_IDLE;
    }
    auto feedback_msg = std::make_shared<sm_dance_bot::action::LEDControl::Feedback>();
    // 10Hz internal loop
    rclcpp::Rate rate(20);
    while (rclcpp::ok())
    {
      gh->publish_feedback(feedback_msg);
      publishStateMarker();
      rate.sleep();
      RCLCPP_INFO_THROTTLE(this->get_logger(), *(this->get_clock()), 2000, "Loop feedback");
    }
    auto result = std::make_shared<sm_dance_bot::action::LEDControl::Result>();
    result->state = this->currentState_;
    // never reach succeeded because were are interested in keeping the feedback alive
    //as_->setSucceeded();
    gh->succeed(result);
  }
References cmd, currentState_, and publishStateMarker().
Referenced by handle_accepted().
execute() [2/5]
void LEDActionServer::execute (const std::shared_ptr< GoalHandleLEDControl > gh) inline
execute()
Definition at line 68 of file led_action_server_node.cpp.
  {
    auto goal = gh->get_goal();
    RCLCPP_INFO_STREAM(get_logger(), "Tool action server request: " << goal->command);
    cmd = goal->command;
    if (goal->command == sm_dance_bot_strikes_back::action::LEDControl_Goal::CMD_ON)
    {
      RCLCPP_INFO(this->get_logger(), "ON");
      currentState_ = sm_dance_bot_strikes_back::action::LEDControl_Result::STATE_RUNNING;
    }
    else if (goal->command == sm_dance_bot_strikes_back::action::LEDControl_Goal::CMD_OFF)
    {
      RCLCPP_INFO(this->get_logger(), "OFF");
      currentState_ = sm_dance_bot_strikes_back::action::LEDControl_Result::STATE_IDLE;
    }
    auto feedback_msg = std::make_shared<sm_dance_bot_strikes_back::action::LEDControl::Feedback>();
    // 10Hz internal loop
    rclcpp::Rate rate(20);
    while (rclcpp::ok())
    {
      gh->publish_feedback(feedback_msg);
      publishStateMarker();
      rate.sleep();
      RCLCPP_INFO_THROTTLE(this->get_logger(), *(this->get_clock()), 2000, "Loop feedback");
    }
    auto result = std::make_shared<sm_dance_bot_strikes_back::action::LEDControl::Result>();
    result->state = this->currentState_;
    // never reach succeeded because were are interested in keeping the feedback alive
    //as_->setSucceeded();
    gh->succeed(result);
  }
References cmd, currentState_, and publishStateMarker().
execute() [3/5]
void LEDActionServer::execute (const std::shared_ptr< GoalHandleLEDControl > gh) inline
execute()
Definition at line 68 of file led_action_server_node.cpp.
  {
    auto goal = gh->get_goal();
    RCLCPP_INFO_STREAM(get_logger(), "Tool action server request: " << goal->command);
    cmd = goal->command;
    if (goal->command == sm_dance_bot_warehouse::action::LEDControl_Goal::CMD_ON)
    {
      RCLCPP_INFO(this->get_logger(), "ON");
      currentState_ = sm_dance_bot_warehouse::action::LEDControl_Result::STATE_RUNNING;
    }
    else if (goal->command == sm_dance_bot_warehouse::action::LEDControl_Goal::CMD_OFF)
    {
      RCLCPP_INFO(this->get_logger(), "OFF");
      currentState_ = sm_dance_bot_warehouse::action::LEDControl_Result::STATE_IDLE;
    }
    auto feedback_msg = std::make_shared<sm_dance_bot_warehouse::action::LEDControl::Feedback>();
    // 10Hz internal loop
    rclcpp::Rate rate(20);
    while (rclcpp::ok())
    {
      gh->publish_feedback(feedback_msg);
      publishStateMarker();
      rate.sleep();
      RCLCPP_INFO_THROTTLE(this->get_logger(), *(this->get_clock()), 2000, "Loop feedback");
    }
    auto result = std::make_shared<sm_dance_bot_warehouse::action::LEDControl::Result>();
    result->state = this->currentState_;
    // never reach succeeded because were are interested in keeping the feedback alive
    //as_->setSucceeded();
    gh->succeed(result);
  }
References cmd, currentState_, and publishStateMarker().
execute() [4/5]
void LEDActionServer::execute (const std::shared_ptr< GoalHandleLEDControl > gh) inline
execute()
Definition at line 68 of file led_action_server_node.cpp.
  {
    auto goal = gh->get_goal();
    RCLCPP_INFO_STREAM(get_logger(), "Tool action server request: " << goal->command);
    cmd = goal->command;
    if (goal->command == sm_dance_bot_warehouse_2::action::LEDControl_Goal::CMD_ON)
    {
      RCLCPP_INFO(this->get_logger(), "ON");
      currentState_ = sm_dance_bot_warehouse_2::action::LEDControl_Result::STATE_RUNNING;
    }
    else if (goal->command == sm_dance_bot_warehouse_2::action::LEDControl_Goal::CMD_OFF)
    {
      RCLCPP_INFO(this->get_logger(), "OFF");
      currentState_ = sm_dance_bot_warehouse_2::action::LEDControl_Result::STATE_IDLE;
    }
    auto feedback_msg = std::make_shared<sm_dance_bot_warehouse_2::action::LEDControl::Feedback>();
    // 10Hz internal loop
    rclcpp::Rate rate(20);
    while (rclcpp::ok())
    {
      gh->publish_feedback(feedback_msg);
      publishStateMarker();
      rate.sleep();
      RCLCPP_INFO_THROTTLE(this->get_logger(), *(this->get_clock()), 2000, "Loop feedback");
    }
    auto result = std::make_shared<sm_dance_bot_warehouse_2::action::LEDControl::Result>();
    result->state = this->currentState_;
    // never reach succeeded because were are interested in keeping the feedback alive
    //as_->setSucceeded();
    gh->succeed(result);
  }
References cmd, currentState_, and publishStateMarker().
execute() [5/5]
void LEDActionServer::execute (const std::shared_ptr< GoalHandleLEDControl > gh) inline
execute()
Definition at line 68 of file led_action_server_node.cpp.
  {
    auto goal = gh->get_goal();
    RCLCPP_INFO_STREAM(get_logger(), "Tool action server request: " << goal->command);
    cmd = goal->command;
    if (goal->command == sm_dance_bot_warehouse_3::action::LEDControl_Goal::CMD_ON)
    {
      RCLCPP_INFO(this->get_logger(), "ON");
      currentState_ = sm_dance_bot_warehouse_3::action::LEDControl_Result::STATE_RUNNING;
    }
    else if (goal->command == sm_dance_bot_warehouse_3::action::LEDControl_Goal::CMD_OFF)
    {
      RCLCPP_INFO(this->get_logger(), "OFF");
      currentState_ = sm_dance_bot_warehouse_3::action::LEDControl_Result::STATE_IDLE;
    }
    auto feedback_msg = std::make_shared<sm_dance_bot_warehouse_3::action::LEDControl::Feedback>();
    // 10Hz internal loop
    rclcpp::Rate rate(20);
    while (rclcpp::ok())
    {
      gh->publish_feedback(feedback_msg);
      publishStateMarker();
      rate.sleep();
      RCLCPP_INFO_THROTTLE(this->get_logger(), *(this->get_clock()), 2000, "Loop feedback");
    }
    auto result = std::make_shared<sm_dance_bot_warehouse_3::action::LEDControl::Result>();
    result->state = this->currentState_;
    // never reach succeeded because were are interested in keeping the feedback alive
    //as_->setSucceeded();
    gh->succeed(result);
  }
References cmd, currentState_, and publishStateMarker().
handle_accepted() [1/5]
void LEDActionServer::handle_accepted (const std::shared_ptr< GoalHandleLEDControl > goal_handle) inline
Definition at line 132 of file led_action_server_node.cpp.
  {
    // this needs to return quickly to avoid blocking the executor, so spin up a new thread
    std::thread{std::bind(&LEDActionServer::execute, this, std::placeholders::_1), goal_handle}
      .detach();
  }
References execute().
Referenced by run().
handle_accepted() [2/5]
void LEDActionServer::handle_accepted (const std::shared_ptr< GoalHandleLEDControl > goal_handle) inline
Definition at line 132 of file led_action_server_node.cpp.
  {
    // this needs to return quickly to avoid blocking the executor, so spin up a new thread
    std::thread{std::bind(&LEDActionServer::execute, this, std::placeholders::_1), goal_handle}
      .detach();
  }
References execute().
handle_accepted() [3/5]
void LEDActionServer::handle_accepted (const std::shared_ptr< GoalHandleLEDControl > goal_handle) inline
Definition at line 132 of file led_action_server_node.cpp.
  {
    // this needs to return quickly to avoid blocking the executor, so spin up a new thread
    std::thread{std::bind(&LEDActionServer::execute, this, std::placeholders::_1), goal_handle}
      .detach();
  }
References execute().
handle_accepted() [4/5]
void LEDActionServer::handle_accepted (const std::shared_ptr< GoalHandleLEDControl > goal_handle) inline
Definition at line 132 of file led_action_server_node.cpp.
  {
    // this needs to return quickly to avoid blocking the executor, so spin up a new thread
    std::thread{std::bind(&LEDActionServer::execute, this, std::placeholders::_1), goal_handle}
      .detach();
  }
References execute().
handle_accepted() [5/5]
void LEDActionServer::handle_accepted (const std::shared_ptr< GoalHandleLEDControl > goal_handle) inline
Definition at line 132 of file led_action_server_node.cpp.
  {
    // this needs to return quickly to avoid blocking the executor, so spin up a new thread
    std::thread{std::bind(&LEDActionServer::execute, this, std::placeholders::_1), goal_handle}
      .detach();
  }
References execute().
handle_cancel() [1/5]
rclcpp_action::CancelResponse LEDActionServer::handle_cancel (const std::shared_ptr< GoalHandleLEDControl >) inline
Definition at line 124 of file led_action_server_node.cpp.
  {
    RCLCPP_INFO(rclcpp::get_logger("server"), "Got request to cancel goal");
    //(void)goal_handle;
    return rclcpp_action::CancelResponse::ACCEPT;
  }
Referenced by run().
handle_cancel() [2/5]
rclcpp_action::CancelResponse LEDActionServer::handle_cancel (const std::shared_ptr< GoalHandleLEDControl >) inline
Definition at line 124 of file led_action_server_node.cpp.
  {
    RCLCPP_INFO(rclcpp::get_logger("server"), "Got request to cancel goal");
    //(void)goal_handle;
    return rclcpp_action::CancelResponse::ACCEPT;
  }
handle_cancel() [3/5]
rclcpp_action::CancelResponse LEDActionServer::handle_cancel (const std::shared_ptr< GoalHandleLEDControl >) inline
Definition at line 124 of file led_action_server_node.cpp.
  {
    RCLCPP_INFO(rclcpp::get_logger("server"), "Got request to cancel goal");
    //(void)goal_handle;
    return rclcpp_action::CancelResponse::ACCEPT;
  }
handle_cancel() [4/5]
rclcpp_action::CancelResponse LEDActionServer::handle_cancel (const std::shared_ptr< GoalHandleLEDControl >) inline
Definition at line 124 of file led_action_server_node.cpp.
  {
    RCLCPP_INFO(rclcpp::get_logger("server"), "Got request to cancel goal");
    //(void)goal_handle;
    return rclcpp_action::CancelResponse::ACCEPT;
  }
handle_cancel() [5/5]
rclcpp_action::CancelResponse LEDActionServer::handle_cancel (const std::shared_ptr< GoalHandleLEDControl >) inline
Definition at line 124 of file led_action_server_node.cpp.
  {
    RCLCPP_INFO(rclcpp::get_logger("server"), "Got request to cancel goal");
    //(void)goal_handle;
    return rclcpp_action::CancelResponse::ACCEPT;
  }
handle_goal() [1/5]
rclcpp_action::GoalResponse LEDActionServer::handle_goal (const rclcpp_action::GoalUUID & , std::shared_ptr< const sm_dance_bot::action::LEDControl::Goal >) inline
Definition at line 109 of file led_action_server_node.cpp.
  {
    // (void)uuid;
    // // Let's reject sequences that are over 9000
    // if (goal->order > 9000) {
    //   return rclcpp_action::GoalResponse::REJECT;
    // }
    // lets accept everything
    RCLCPP_INFO(this->get_logger(), "Handle goal");
    return rclcpp_action::GoalResponse::ACCEPT_AND_EXECUTE;
  }
Referenced by run().
handle_goal() [2/5]
rclcpp_action::GoalResponse LEDActionServer::handle_goal (const rclcpp_action::GoalUUID & , std::shared_ptr< const sm_dance_bot_strikes_back::action::LEDControl::Goal >) inline
Definition at line 109 of file led_action_server_node.cpp.
  {
    // (void)uuid;
    // // Let's reject sequences that are over 9000
    // if (goal->order > 9000) {
    //   return rclcpp_action::GoalResponse::REJECT;
    // }
    // lets accept everything
    RCLCPP_INFO(this->get_logger(), "Handle goal");
    return rclcpp_action::GoalResponse::ACCEPT_AND_EXECUTE;
  }
handle_goal() [3/5]
rclcpp_action::GoalResponse LEDActionServer::handle_goal (const rclcpp_action::GoalUUID & , std::shared_ptr< const sm_dance_bot_warehouse::action::LEDControl::Goal >) inline
Definition at line 109 of file led_action_server_node.cpp.
  {
    // (void)uuid;
    // // Let's reject sequences that are over 9000
    // if (goal->order > 9000) {
    //   return rclcpp_action::GoalResponse::REJECT;
    // }
    // lets accept everything
    RCLCPP_INFO(this->get_logger(), "Handle goal");
    return rclcpp_action::GoalResponse::ACCEPT_AND_EXECUTE;
  }
handle_goal() [4/5]
rclcpp_action::GoalResponse LEDActionServer::handle_goal (const rclcpp_action::GoalUUID & , std::shared_ptr< const sm_dance_bot_warehouse_2::action::LEDControl::Goal >) inline
Definition at line 109 of file led_action_server_node.cpp.
  {
    // (void)uuid;
    // // Let's reject sequences that are over 9000
    // if (goal->order > 9000) {
    //   return rclcpp_action::GoalResponse::REJECT;
    // }
    // lets accept everything
    RCLCPP_INFO(this->get_logger(), "Handle goal");
    return rclcpp_action::GoalResponse::ACCEPT_AND_EXECUTE;
  }
handle_goal() [5/5]
rclcpp_action::GoalResponse LEDActionServer::handle_goal (const rclcpp_action::GoalUUID & , std::shared_ptr< const sm_dance_bot_warehouse_3::action::LEDControl::Goal >) inline
Definition at line 109 of file led_action_server_node.cpp.
  {
    // (void)uuid;
    // // Let's reject sequences that are over 9000
    // if (goal->order > 9000) {
    //   return rclcpp_action::GoalResponse::REJECT;
    // }
    // lets accept everything
    RCLCPP_INFO(this->get_logger(), "Handle goal");
    return rclcpp_action::GoalResponse::ACCEPT_AND_EXECUTE;
  }
publishStateMarker() [1/5]
void LEDActionServer::publishStateMarker () inline
publishStateMarker()
Definition at line 165 of file led_action_server_node.cpp.
  {
    visualization_msgs::msg::Marker marker;
    marker.header.frame_id = "base_link";
    marker.header.stamp = this->now();
    marker.ns = "tool_namespace";
    marker.id = 0;
    marker.type = visualization_msgs::msg::Marker::SPHERE;
    marker.action = visualization_msgs::msg::Marker::ADD;
    marker.scale.x = 0.2;
    marker.scale.y = 0.2;
    marker.scale.z = 0.2;
    marker.color.a = 1;
    if (currentState_ == sm_dance_bot::action::LEDControl::Result::STATE_RUNNING)
    {
      // show green ball
      marker.color.r = 0;
      marker.color.g = 1;
      marker.color.b = 0;
    }
    else if (currentState_ == sm_dance_bot::action::LEDControl::Result::STATE_IDLE)
    {
      // show gray ball
      marker.color.r = 0.7;
      marker.color.g = 0.7;
      marker.color.b = 0.7;
    }
    else
    {
      // show black ball
      marker.color.r = 0;
      marker.color.g = 0;
      marker.color.b = 0;
    }
    marker.pose.orientation.w = 1;
    marker.pose.position.x = 0;
    marker.pose.position.y = 0;
    marker.pose.position.z = 1;
    visualization_msgs::msg::MarkerArray ma;
    ma.markers.push_back(marker);
    stateMarkerPublisher_->publish(ma);
  }
References currentState_, and stateMarkerPublisher_.
Referenced by execute().
publishStateMarker() [2/5]
void LEDActionServer::publishStateMarker () inline
publishStateMarker()
Definition at line 165 of file led_action_server_node.cpp.
  {
    visualization_msgs::msg::Marker marker;
    marker.header.frame_id = "base_link";
    marker.header.stamp = this->now();
    marker.ns = "tool_namespace";
    marker.id = 0;
    marker.type = visualization_msgs::msg::Marker::SPHERE;
    marker.action = visualization_msgs::msg::Marker::ADD;
    marker.scale.x = 0.2;
    marker.scale.y = 0.2;
    marker.scale.z = 0.2;
    marker.color.a = 1;
    if (currentState_ == sm_dance_bot_strikes_back::action::LEDControl::Result::STATE_RUNNING)
    {
      // show green ball
      marker.color.r = 0;
      marker.color.g = 1;
      marker.color.b = 0;
    }
    else if (currentState_ == sm_dance_bot_strikes_back::action::LEDControl::Result::STATE_IDLE)
    {
      // show gray ball
      marker.color.r = 0.7;
      marker.color.g = 0.7;
      marker.color.b = 0.7;
    }
    else
    {
      // show black ball
      marker.color.r = 0;
      marker.color.g = 0;
      marker.color.b = 0;
    }
    marker.pose.orientation.w = 1;
    marker.pose.position.x = 0;
    marker.pose.position.y = 0;
    marker.pose.position.z = 1;
    visualization_msgs::msg::MarkerArray ma;
    ma.markers.push_back(marker);
    stateMarkerPublisher_->publish(ma);
  }
References currentState_, and stateMarkerPublisher_.
publishStateMarker() [3/5]
void LEDActionServer::publishStateMarker () inline
publishStateMarker()
Definition at line 165 of file led_action_server_node.cpp.
  {
    visualization_msgs::msg::Marker marker;
    marker.header.frame_id = "base_link";
    marker.header.stamp = this->now();
    marker.ns = "tool_namespace";
    marker.id = 0;
    marker.type = visualization_msgs::msg::Marker::SPHERE;
    marker.action = visualization_msgs::msg::Marker::ADD;
    marker.scale.x = 0.2;
    marker.scale.y = 0.2;
    marker.scale.z = 0.2;
    marker.color.a = 1;
    if (currentState_ == sm_dance_bot_warehouse::action::LEDControl::Result::STATE_RUNNING)
    {
      // show green ball
      marker.color.r = 0;
      marker.color.g = 1;
      marker.color.b = 0;
    }
    else if (currentState_ == sm_dance_bot_warehouse::action::LEDControl::Result::STATE_IDLE)
    {
      // show gray ball
      marker.color.r = 0.7;
      marker.color.g = 0.7;
      marker.color.b = 0.7;
    }
    else
    {
      // show black ball
      marker.color.r = 0;
      marker.color.g = 0;
      marker.color.b = 0;
    }
    marker.pose.orientation.w = 1;
    marker.pose.position.x = 0;
    marker.pose.position.y = 0;
    marker.pose.position.z = 1;
    visualization_msgs::msg::MarkerArray ma;
    ma.markers.push_back(marker);
    stateMarkerPublisher_->publish(ma);
  }
References currentState_, and stateMarkerPublisher_.
publishStateMarker() [4/5]
void LEDActionServer::publishStateMarker () inline
publishStateMarker()
Definition at line 165 of file led_action_server_node.cpp.
  {
    visualization_msgs::msg::Marker marker;
    marker.header.frame_id = "base_link";
    marker.header.stamp = this->now();
    marker.ns = "tool_namespace";
    marker.id = 0;
    marker.type = visualization_msgs::msg::Marker::SPHERE;
    marker.action = visualization_msgs::msg::Marker::ADD;
    marker.scale.x = 0.2;
    marker.scale.y = 0.2;
    marker.scale.z = 0.2;
    marker.color.a = 1;
    if (currentState_ == sm_dance_bot_warehouse_2::action::LEDControl::Result::STATE_RUNNING)
    {
      // show green ball
      marker.color.r = 0;
      marker.color.g = 1;
      marker.color.b = 0;
    }
    else if (currentState_ == sm_dance_bot_warehouse_2::action::LEDControl::Result::STATE_IDLE)
    {
      // show gray ball
      marker.color.r = 0.7;
      marker.color.g = 0.7;
      marker.color.b = 0.7;
    }
    else
    {
      // show black ball
      marker.color.r = 0;
      marker.color.g = 0;
      marker.color.b = 0;
    }
    marker.pose.orientation.w = 1;
    marker.pose.position.x = 0;
    marker.pose.position.y = 0;
    marker.pose.position.z = 1;
    visualization_msgs::msg::MarkerArray ma;
    ma.markers.push_back(marker);
    stateMarkerPublisher_->publish(ma);
  }
References currentState_, and stateMarkerPublisher_.
publishStateMarker() [5/5]
void LEDActionServer::publishStateMarker () inline
publishStateMarker()
Definition at line 165 of file led_action_server_node.cpp.
  {
    visualization_msgs::msg::Marker marker;
    marker.header.frame_id = "base_link";
    marker.header.stamp = this->now();
    marker.ns = "tool_namespace";
    marker.id = 0;
    marker.type = visualization_msgs::msg::Marker::SPHERE;
    marker.action = visualization_msgs::msg::Marker::ADD;
    marker.scale.x = 0.2;
    marker.scale.y = 0.2;
    marker.scale.z = 0.2;
    marker.color.a = 1;
    if (currentState_ == sm_dance_bot_warehouse_3::action::LEDControl::Result::STATE_RUNNING)
    {
      // show green ball
      marker.color.r = 0;
      marker.color.g = 1;
      marker.color.b = 0;
    }
    else if (currentState_ == sm_dance_bot_warehouse_3::action::LEDControl::Result::STATE_IDLE)
    {
      // show gray ball
      marker.color.r = 0.7;
      marker.color.g = 0.7;
      marker.color.b = 0.7;
    }
    else
    {
      // show black ball
      marker.color.r = 0;
      marker.color.g = 0;
      marker.color.b = 0;
    }
    marker.pose.orientation.w = 1;
    marker.pose.position.x = 0;
    marker.pose.position.y = 0;
    marker.pose.position.z = 1;
    visualization_msgs::msg::MarkerArray ma;
    ma.markers.push_back(marker);
    stateMarkerPublisher_->publish(ma);
  }
References currentState_, and stateMarkerPublisher_.
run() [1/5]
void LEDActionServer::run () inline
run()
Definition at line 144 of file led_action_server_node.cpp.
  {
    RCLCPP_INFO(this->get_logger(), "Creating tool action server");
    //as_ = std::make_shared<Server>(n, "led_action_server", boost::bind(&LEDActionServer::execute, this,  _1), false);
    this->as_ = rclcpp_action::create_server<sm_dance_bot::action::LEDControl>(
      this, "led_action_server",
      std::bind(&LEDActionServer::handle_goal, this, std::placeholders::_1, std::placeholders::_2),
      std::bind(&LEDActionServer::handle_cancel, this, std::placeholders::_1),
      std::bind(&LEDActionServer::handle_accepted, this, std::placeholders::_1));
    RCLCPP_INFO(get_logger(), "Starting Tool Action Server");
    stateMarkerPublisher_ =
      this->create_publisher<visualization_msgs::msg::MarkerArray>("tool_markers", 1);
  }
References handle_accepted(), handle_cancel(), handle_goal(), and stateMarkerPublisher_.
run() [2/5]
void LEDActionServer::run () inline
run()
Definition at line 144 of file led_action_server_node.cpp.
  {
    RCLCPP_INFO(this->get_logger(), "Creating tool action server");
    //as_ = std::make_shared<Server>(n, "led_action_server", boost::bind(&LEDActionServer::execute, this,  _1), false);
    this->as_ = rclcpp_action::create_server<sm_dance_bot_strikes_back::action::LEDControl>(
      this, "led_action_server",
      std::bind(&LEDActionServer::handle_goal, this, std::placeholders::_1, std::placeholders::_2),
      std::bind(&LEDActionServer::handle_cancel, this, std::placeholders::_1),
      std::bind(&LEDActionServer::handle_accepted, this, std::placeholders::_1));
    RCLCPP_INFO(get_logger(), "Starting Tool Action Server");
    stateMarkerPublisher_ =
      this->create_publisher<visualization_msgs::msg::MarkerArray>("tool_markers", 1);
  }
References handle_accepted(), handle_cancel(), handle_goal(), and stateMarkerPublisher_.
run() [3/5]
void LEDActionServer::run () inline
run()
Definition at line 144 of file led_action_server_node.cpp.
  {
    RCLCPP_INFO(this->get_logger(), "Creating tool action server");
    //as_ = std::make_shared<Server>(n, "led_action_server", boost::bind(&LEDActionServer::execute, this,  _1), false);
    this->as_ = rclcpp_action::create_server<sm_dance_bot_warehouse::action::LEDControl>(
      this, "led_action_server",
      std::bind(&LEDActionServer::handle_goal, this, std::placeholders::_1, std::placeholders::_2),
      std::bind(&LEDActionServer::handle_cancel, this, std::placeholders::_1),
      std::bind(&LEDActionServer::handle_accepted, this, std::placeholders::_1));
    RCLCPP_INFO(get_logger(), "Starting Tool Action Server");
    stateMarkerPublisher_ =
      this->create_publisher<visualization_msgs::msg::MarkerArray>("tool_markers", 1);
  }
References handle_accepted(), handle_cancel(), handle_goal(), and stateMarkerPublisher_.
run() [4/5]
void LEDActionServer::run () inline
run()
Definition at line 144 of file led_action_server_node.cpp.
  {
    RCLCPP_INFO(this->get_logger(), "Creating tool action server");
    //as_ = std::make_shared<Server>(n, "led_action_server", boost::bind(&LEDActionServer::execute, this,  _1), false);
    this->as_ = rclcpp_action::create_server<sm_dance_bot_warehouse_2::action::LEDControl>(
      this, "led_action_server",
      std::bind(&LEDActionServer::handle_goal, this, std::placeholders::_1, std::placeholders::_2),
      std::bind(&LEDActionServer::handle_cancel, this, std::placeholders::_1),
      std::bind(&LEDActionServer::handle_accepted, this, std::placeholders::_1));
    RCLCPP_INFO(get_logger(), "Starting Tool Action Server");
    stateMarkerPublisher_ =
      this->create_publisher<visualization_msgs::msg::MarkerArray>("tool_markers", 1);
  }
References handle_accepted(), handle_cancel(), handle_goal(), and stateMarkerPublisher_.
run() [5/5]
void LEDActionServer::run () inline
run()
Definition at line 144 of file led_action_server_node.cpp.
  {
    RCLCPP_INFO(this->get_logger(), "Creating tool action server");
    //as_ = std::make_shared<Server>(n, "led_action_server", boost::bind(&LEDActionServer::execute, this,  _1), false);
    this->as_ = rclcpp_action::create_server<sm_dance_bot_warehouse_3::action::LEDControl>(
      this, "led_action_server",
      std::bind(&LEDActionServer::handle_goal, this, std::placeholders::_1, std::placeholders::_2),
      std::bind(&LEDActionServer::handle_cancel, this, std::placeholders::_1),
      std::bind(&LEDActionServer::handle_accepted, this, std::placeholders::_1));
    RCLCPP_INFO(get_logger(), "Starting Tool Action Server");
    stateMarkerPublisher_ =
      this->create_publisher<visualization_msgs::msg::MarkerArray>("tool_markers", 1);
  }
References handle_accepted(), handle_cancel(), handle_goal(), and stateMarkerPublisher_.
Member Data Documentation
as_ [1/5]
std::shared_ptr<rclcpp_action::Server<sm_dance_bot::action::LEDControl> > LEDActionServer::as_
Definition at line 42 of file led_action_server_node.cpp.
as_ [2/5]
std::shared_ptr<rclcpp_action::Server<sm_dance_bot_strikes_back::action::LEDControl> > LEDActionServer::as_
Definition at line 42 of file led_action_server_node.cpp.
as_ [3/5]
std::shared_ptr<rclcpp_action::Server<sm_dance_bot_warehouse::action::LEDControl> > LEDActionServer::as_
Definition at line 42 of file led_action_server_node.cpp.
as_ [4/5]
std::shared_ptr<rclcpp_action::Server<sm_dance_bot_warehouse_2::action::LEDControl> > LEDActionServer::as_
Definition at line 42 of file led_action_server_node.cpp.
as_ [5/5]
std::shared_ptr<rclcpp_action::Server<sm_dance_bot_warehouse_3::action::LEDControl> > LEDActionServer::as_
Definition at line 42 of file led_action_server_node.cpp.
cmd
uint8_t LEDActionServer::cmd
Definition at line 48 of file led_action_server_node.cpp.
Referenced by execute().
currentState_
uint8_t LEDActionServer::currentState_
Definition at line 50 of file led_action_server_node.cpp.
Referenced by execute(), LEDActionServer(), and publishStateMarker().
stateMarkerPublisher_
rclcpp::Publisher< visualization_msgs::msg::MarkerArray >::SharedPtr LEDActionServer::stateMarkerPublisher_
Definition at line 46 of file led_action_server_node.cpp.
Referenced by publishStateMarker(), and run().
The documentation for this class was generated from the following files:
smacc2_sm_reference_library/sm_dance_bot/servers/led_action_server/src/led_action_server_node.cpp
smacc2_sm_reference_library/sm_dance_bot_strikes_back/servers/led_action_server/src/led_action_server_node.cpp
smacc2_sm_reference_library/sm_dance_bot_warehouse/servers/led_action_server/src/led_action_server_node.cpp
smacc2_sm_reference_library/sm_dance_bot_warehouse_2/servers/led_action_server/src/led_action_server_node.cpp
smacc2_sm_reference_library/sm_dance_bot_warehouse_3/servers/led_action_server/src/led_action_server_node.cpp