SMACC2: sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception Class Reference
sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception Class Reference
#include <cl_opencv_perception_client.hpp>
Public Member Functions
ClOpenCVPerception (std::string topicname="/detected_objects")
virtual ~ClOpenCVPerception ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void MessageCallback (const sm_husky_barrel_search_1::msg::DetectedObjects &detectedMsg)
void onInitialize () override
Public Member Functions inherited from smacc2::client_bases::SmaccSubscriberClient< sm_husky_barrel_search_1::msg::DetectedObjects >
SmaccSubscriberClient ()
SmaccSubscriberClient (std::string topicname)
virtual ~SmaccSubscriberClient ()
boost::signals2::connection onMessageReceived (void(T::*callback)(const sm_husky_barrel_search_1::msg::DetectedObjects &), T *object)
boost::signals2::connection onFirstMessageReceived (void(T::*callback)(const sm_husky_barrel_search_1::msg::DetectedObjects &), T *object)
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void onInitialize ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Private Attributes
std::function< void()> postEvEnemyDetected
std::function< void()> postEvEnemyClusterDetected
std::function< void()> postEvEnemyClusterFireDistance
Additional Inherited Members
Public Types inherited from smacc2::client_bases::SmaccSubscriberClient< sm_husky_barrel_search_1::msg::DetectedObjects >
typedef sm_husky_barrel_search_1::msg::DetectedObjects TMessageType
Public Attributes inherited from smacc2::client_bases::SmaccSubscriberClient< sm_husky_barrel_search_1::msg::DetectedObjects >
std::optional< std::string > topicName
std::optional< int > queueSize
smacc2::SmaccSignal< void(const sm_husky_barrel_search_1::msg::DetectedObjects &)> onFirstMessageReceived_
smacc2::SmaccSignal< void(const sm_husky_barrel_search_1::msg::DetectedObjects &)> onMessageReceived_
std::function< void(const sm_husky_barrel_search_1::msg::DetectedObjects &)> postMessageEvent
std::function< void(const sm_husky_barrel_search_1::msg::DetectedObjects &)> postInitialMessageEvent
Protected Member Functions inherited from smacc2::client_bases::SmaccSubscriberClient< sm_husky_barrel_search_1::msg::DetectedObjects >
void onInitialize () override
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Detailed Description
Definition at line 51 of file cl_opencv_perception_client.hpp.
Constructor & Destructor Documentation
ClOpenCVPerception()
sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception::ClOpenCVPerception (std::string topicname = "/detected_objects") inline
Definition at line 55 of file cl_opencv_perception_client.hpp.
    : smacc2::client_bases::SmaccSubscriberClient<sm_husky_barrel_search_1::msg::DetectedObjects>(topicname)
  {
  }
~ClOpenCVPerception()
virtual sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception::~ClOpenCVPerception () inline virtual
Definition at line 60 of file cl_opencv_perception_client.hpp.
  {
  }
Member Function Documentation
MessageCallback()
void sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception::MessageCallback (const sm_husky_barrel_search_1::msg::DetectedObjects & detectedMsg) inline
Definition at line 81 of file cl_opencv_perception_client.hpp.
  {
    int totalEnemies = 0;
    int totalEnemiesFireDistance = 0;
    for (auto detectedObject : detectedMsg.detected_objects)
    {
      size_t found = detectedObject.name.find("enemy");
      if (found != std::string::npos)
      {
        this->postEvEnemyDetected();
        totalEnemies++;
        if(detectedObject.blob_area >= 50)
        {
          totalEnemiesFireDistance++;
        }
      }
    }
    if (totalEnemies >= 3)
    {
      this->postEvEnemyClusterDetected();
    }
    if (totalEnemiesFireDistance > 0)
    {
      RCLCPP_INFO_THROTTLE(this->getLogger(), *(getNode()->get_clock()) ,  1000, "Enemies in fire distance: %d", totalEnemiesFireDistance);
    }
    if(totalEnemiesFireDistance >= 3)
    {
      this->postEvEnemyClusterFireDistance();
    }
  }
References smacc2::ISmaccClient::getLogger(), smacc2::ISmaccClient::getNode(), postEvEnemyClusterDetected, postEvEnemyClusterFireDistance, and postEvEnemyDetected.
Referenced by onInitialize().
onInitialize()
void sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception::onInitialize () inline override virtual
Reimplemented from smacc2::ISmaccClient.
Definition at line 120 of file cl_opencv_perception_client.hpp.
  {
    smacc2::client_bases::SmaccSubscriberClient<sm_husky_barrel_search_1::msg::DetectedObjects>::onInitialize();
    this->onMessageReceived(&ClOpenCVPerception::MessageCallback, this);
  }
References MessageCallback(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onInitialize(), and smacc2::client_bases::SmaccSubscriberClient< sm_husky_barrel_search_1::msg::DetectedObjects >::onMessageReceived().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception::onOrthogonalAllocation () inline
Definition at line 65 of file cl_opencv_perception_client.hpp.
  {
    smacc2::client_bases::SmaccSubscriberClient<sm_husky_barrel_search_1::msg::DetectedObjects>::onOrthogonalAllocation<
        TOrthogonal, TSourceObject>();
    this->postEvEnemyDetected = [this]() { this->postEvent<EvEnemyDetected<TSourceObject, TOrthogonal>>(); };
    this->postEvEnemyClusterDetected = [this]() {
      this->postEvent<EvEnemyClusterDetected<TSourceObject, TOrthogonal>>();
    };
    this->postEvEnemyClusterFireDistance = [this]() {
      this->postEvent<EvEnemyClusterFireDistance<TSourceObject, TOrthogonal>>();
    };
  }
References postEvEnemyClusterDetected, postEvEnemyClusterFireDistance, and postEvEnemyDetected.
Member Data Documentation
postEvEnemyClusterDetected
std::function<void()> sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception::postEvEnemyClusterDetected private
Definition at line 128 of file cl_opencv_perception_client.hpp.
Referenced by MessageCallback(), and onOrthogonalAllocation().
postEvEnemyClusterFireDistance
std::function<void()> sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception::postEvEnemyClusterFireDistance private
Definition at line 129 of file cl_opencv_perception_client.hpp.
Referenced by MessageCallback(), and onOrthogonalAllocation().
postEvEnemyDetected
std::function<void()> sm_husky_barrel_search_1::cl_opencv_perception::ClOpenCVPerception::postEvEnemyDetected private
Definition at line 127 of file cl_opencv_perception_client.hpp.
Referenced by MessageCallback(), and onOrthogonalAllocation().
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_husky_barrel_search_1/include/sm_husky_barrel_search_1/clients/opencv_perception_client/cl_opencv_perception_client.hpp