SMACC2: smacc2::LedSetting Class Reference
smacc2::LedSetting Class Reference
Internal data class to hold individual LED light settings.
#include <LedPlugin.hh>
Public Member Functions
LedSetting (const sdf::ElementPtr &_sdf, const gazebo::physics::ModelPtr &_model, const gazebo::common::Time &_currentTime, gazebo_ros::Node::SharedPtr rosnode)
Constructor.
virtual ~LedSetting ()
Destructor.
virtual void InitPubVisual (const gazebo::transport::PublisherPtr &_pubVisual) final
Set the publisher and send an initial visual command.
Public Member Functions inherited from smacc2::FlashLightSetting
FlashLightSetting (const sdf::ElementPtr &_sdf, const gazebo::physics::ModelPtr &_model, const gazebo::common::Time &_currentTime, gazebo_ros::Node::SharedPtr node)
Constructor. Initialize the setting by the data given to the base plugin.
virtual ~FlashLightSetting ()
Destructor.
virtual void InitPubLight (const gazebo::transport::PublisherPtr &_pubLight) final
Set the publisher and send an initial light command.
virtual void UpdateLightInEnv (const gazebo::common::Time &_currentTime) final
Update the light based on the given time.
virtual const std::string Name () const final
Getter of name.
virtual const gazebo::physics::LinkPtr Link () const final
Getter of link.
virtual void SwitchOn () final
Switch on (enable the flashlight).
virtual void SwitchOff () final
Switch off (disable the flashlight).
virtual void SetDuration (const double _duration, const int _index) final
Set the duration time for the specified block.
virtual void SetDuration (const double _duration) final
Set the duration time for all the blocks.
virtual void SetInterval (const double _interval, const int _index) final
Set the interval time for the specified block.
virtual void SetInterval (const double _interval) final
Set the interval time for all the blocks.
virtual void SetColor (const ignition::math::Color &_color, const int _index) final
Set the color for the specified block.
virtual void SetColor (const ignition::math::Color &_color) final
Set the color for all the blocks.
virtual unsigned int BlockCount () final
Get the number of blocks.
virtual bool RemoveBlock (const int _index) final
Remove a specified block.
virtual void InsertBlock (const double _duration, const double _interval, const ignition::math::Color &_color, const int _index) final
Insert a block. Create a block with specified parameters. If the index is out of range, the block will be appended at the end of the list.
Protected Member Functions
virtual void Flash ()
Flash the light This function is internally used to update the light in the environment.
virtual void Dim ()
Dim the light This function is internally used to update the light in the environment.
Protected Member Functions inherited from smacc2::FlashLightSetting
virtual ignition::math::Color CurrentColor () final
Get the current color of the light. This is to be used by an inheriting class of FlashLightSetting class.
Private Attributes
std::unique_ptr< LedSettingPrivate > dataPtr
Pointer to private data.
Detailed Description
Internal data class to hold individual LED light settings.
Definition at line 38 of file LedPlugin.hh.
Constructor & Destructor Documentation
LedSetting()
smacc2::LedSetting::LedSetting (const sdf::ElementPtr & _sdf, const gazebo::physics::ModelPtr & _model, const gazebo::common::Time & _currentTime, gazebo_ros::Node::SharedPtr rosnode)
Constructor.
Definition at line 75 of file LedPlugin.cc.
  : FlashLightSetting(_sdf, _model, _currentTime, rosnode),
  dataPtr(new LedSettingPrivate)
{
  // check if the visual element exists.
  this->dataPtr->visualExists = false;
  msgs::Link msg;
  this->Link()->FillMsg(msg);
  for (auto visualMsg : msg.visual())
  {
    if (visualMsg.name()
      == this->Link()->GetScopedName() + "::" + this->Name())
    {
      if (visualMsg.has_transparency())
      {
        this->dataPtr->transparency = visualMsg.transparency();
      }
      if (visualMsg.has_material()
        && visualMsg.material().has_emissive())
      {
        this->dataPtr->defaultEmissiveColor
          = msgs::Convert(visualMsg.material().emissive());
      }
      this->dataPtr->visualExists = true;
      break;
    }
  }
}
References dataPtr, and smacc2::FlashLightSetting::Link().
~LedSetting()
smacc2::LedSetting::~LedSetting () virtual
Destructor.
Definition at line 111 of file LedPlugin.cc.
{
}
Member Function Documentation
Dim()
void smacc2::LedSetting::Dim () protected virtual
Dim the light This function is internally used to update the light in the environment.
Reimplemented from smacc2::FlashLightSetting.
Definition at line 174 of file LedPlugin.cc.
{
  // Call the function of the parent class.
  FlashLightSetting::Dim();
  // Make the appearance darker.
  this->dataPtr->msg.set_transparency(this->dataPtr->transparency);
  msgs::Set(this->dataPtr->msg.mutable_material()->mutable_emissive(),
    ignition::math::Color(0, 0, 0));
  // Send the message.
  if (this->dataPtr->visualExists)
  {
    // NOTE: this if statement is to make sure that a visual object to update
    // has been created in the environment before publishing a message.
    // Otherwise, a duplicate object will be created and the original one will
    // never be updated.
    // This problem is solved by the patch (Pull Request # 2983), which has
    // been merged into gazebo7 as of July 16, 2018. This if statement should be
    // removed once the patch is forwarded up to gazebo9.
    if (this->Link()->GetWorld()->SimTime() > 2.0)
      this->dataPtr->pubVisual->Publish(this->dataPtr->msg);
  }
}
References dataPtr, smacc2::FlashLightSetting::Dim(), and smacc2::FlashLightSetting::Link().
Flash()
void smacc2::LedSetting::Flash () protected virtual
Flash the light This function is internally used to update the light in the environment.
Reimplemented from smacc2::FlashLightSetting.
Definition at line 134 of file LedPlugin.cc.
{
  // Call the function of the parent class.
  FlashLightSetting::Flash();
  // Make the appearance brighter.
  this->dataPtr->msg.set_transparency(0.0);
  ignition::math::Color color = this->CurrentColor();
  if (color != ignition::math::Color::Black)
  {
    // If the base class is using a specific color rather than the default,
    // apply it to the visual object.
    msgs::Set(this->dataPtr->msg.mutable_material()->mutable_diffuse(), color);
    msgs::Set(this->dataPtr->msg.mutable_material()->mutable_emissive(), color);
    msgs::Set(this->dataPtr->msg.mutable_material()->mutable_specular(), color);
    msgs::Set(this->dataPtr->msg.mutable_material()->mutable_ambient(), color);
  }
  else
  {
    // Otherwise, just apply the default color.
    msgs::Set(this->dataPtr->msg.mutable_material()->mutable_emissive(),
      this->dataPtr->defaultEmissiveColor);
  }
  // Send the message.
  if (this->dataPtr->visualExists)
  {
    // NOTE: this if statement is to make sure that a visual object to update
    // has been created in the environment before publishing a message.
    // Otherwise, a duplicate object will be created and the original one will
    // never be updated.
    // This problem is solved by the patch (Pull Request # 2983), which has
    // been merged into gazebo7 as of July 16, 2018. This if statement should be
    // removed once the patch is forwarded up to gazebo9.
    if (this->Link()->GetWorld()->SimTime() > 2.0)
      this->dataPtr->pubVisual->Publish(this->dataPtr->msg);
  }
}
References smacc2::FlashLightSetting::CurrentColor(), dataPtr, smacc2::FlashLightSetting::Flash(), and smacc2::FlashLightSetting::Link().
InitPubVisual()
void smacc2::LedSetting::InitPubVisual (const gazebo::transport::PublisherPtr & _pubVisual) final virtual
Set the publisher and send an initial visual command.
Parameters
[in] _pubVisual The publisher to send a message
Definition at line 116 of file LedPlugin.cc.
{
  // The PublisherPtr
  this->dataPtr->pubVisual = _pubVisual;
  if (this->dataPtr->visualExists)
  {
    // Make a message
    this->dataPtr->msg.set_name(
      this->Link()->GetScopedName() + "::" + this->Name());
    this->dataPtr->msg.set_parent_name(this->Link()->GetScopedName());
    uint32_t id;
    this->Link()->VisualId(this->Name(), id);
    this->dataPtr->msg.set_id(id);
  }
}
References dataPtr, smacc2::FlashLightSetting::Link(), and smacc2::FlashLightSetting::Name().
Member Data Documentation
dataPtr
std::unique_ptr<LedSettingPrivate> smacc2::LedSetting::dataPtr private
Pointer to private data.
Definition at line 62 of file LedPlugin.hh.
Referenced by Dim(), Flash(), InitPubVisual(), and LedSetting().
The documentation for this class was generated from the following files:
smacc2_sm_reference_library/sm_husky_barrel_search_1/src/sm_husky_barrel_search_1/gz_plugins/LedPlugin.hh
smacc2_sm_reference_library/sm_husky_barrel_search_1/src/sm_husky_barrel_search_1/gz_plugins/LedPlugin.cc