SMACC2: smacc2::ISmaccState Class Reference
smacc2::ISmaccState Class Reference abstract
#include <smacc_state.hpp>
Inherited by smacc2::SmaccState< State1, $SmName$ >, smacc2::SmaccState< State2, $SmName$ >, smacc2::SmaccState< MsRecover, SmAdvancedRecovery1, StRecoverStep1 >, smacc2::SmaccState< MsRun, SmAdvancedRecovery1, StObserve >, smacc2::SmaccState< SsACycle, MsRun, StiACycleLoop >, smacc2::SmaccState< SsBCycle, MsRun, StiBCycleLoop >, smacc2::SmaccState< SsCCycle, MsRun, StiCCycleLoop >, smacc2::SmaccState< StObserve, MsRun >, smacc2::SmaccState< StRecoverStep1, MsRecover >, smacc2::SmaccState< StRecoverStep2, MsRecover >, smacc2::SmaccState< StRecoverStep3, MsRecover >, smacc2::SmaccState< StRecoverStep4, MsRecover >, smacc2::SmaccState< StRecoverStep5, MsRecover >, smacc2::SmaccState< StRecoverStep6, MsRecover >, smacc2::SmaccState< StRecoverStep7, MsRecover >, smacc2::SmaccState< StiACycleLoop, SsACycle >, smacc2::SmaccState< StiACycleStep1, SsACycle >, smacc2::SmaccState< StiACycleStep2, SsACycle >, smacc2::SmaccState< StiACycleStep3, SsACycle >, smacc2::SmaccState< StiACycleStep4, SsACycle >, smacc2::SmaccState< StiACycleStep5, SsACycle >, smacc2::SmaccState< StiACycleStep6, SsACycle >, smacc2::SmaccState< StiACycleStep7, SsACycle >, smacc2::SmaccState< StiACycleStep8, SsACycle >, smacc2::SmaccState< StiACycleStep9, SsACycle >, smacc2::SmaccState< StiBCycleLoop, SsBCycle >, smacc2::SmaccState< StiBCycleStep1, SsBCycle >, smacc2::SmaccState< StiBCycleStep2, SsBCycle >, smacc2::SmaccState< StiBCycleStep3, SsBCycle >, smacc2::SmaccState< StiBCycleStep4, SsBCycle >, smacc2::SmaccState< StiBCycleStep5, SsBCycle >, smacc2::SmaccState< StiBCycleStep6, SsBCycle >, smacc2::SmaccState< StiBCycleStep7, SsBCycle >, smacc2::SmaccState< StiBCycleStep8, SsBCycle >, smacc2::SmaccState< StiBCycleStep9, SsBCycle >, smacc2::SmaccState< StiCCycleLoop, SsCCycle >, smacc2::SmaccState< StiCCycleStep1, SsCCycle >, smacc2::SmaccState< StiCCycleStep2, SsCCycle >, smacc2::SmaccState< StiCCycleStep3, SsCCycle >, smacc2::SmaccState< StiCCycleStep4, SsCCycle >, smacc2::SmaccState< StiCCycleStep5, SsCCycle >, smacc2::SmaccState< StiCCycleStep6, SsCCycle >, smacc2::SmaccState< StiCCycleStep7, SsCCycle >, smacc2::SmaccState< StiCCycleStep8, SsCCycle >, smacc2::SmaccState< StiCCycleStep9, SsCCycle >, smacc2::SmaccState< State1, SmAtomic >, smacc2::SmaccState< State2, SmAtomic >, smacc2::SmaccState< State1, SmAtomic24Hr >, smacc2::SmaccState< State2, SmAtomic24Hr >, smacc2::SmaccState< State1, SmAtomicHierarchy, StiState1 >, smacc2::SmaccState< State2, SmAtomicHierarchy >, smacc2::SmaccState< StiState1, State1 >, smacc2::SmaccState< State1, SmAtomicPerformanceTrace1 >, smacc2::SmaccState< State2, SmAtomicPerformanceTrace1 >, smacc2::SmaccState< State1, SmAtomicSubscribersPerformanceTest >, smacc2::SmaccState< State2, SmAtomicSubscribersPerformanceTest >, smacc2::SmaccState< StAcquireSensors, SmAutowareAvp >, smacc2::SmaccState< StFirstPause, SmAutowareAvp >, smacc2::SmaccState< StNavigateWaypoint1, SmAutowareAvp >, smacc2::SmaccState< StNavigateWaypoint2, SmAutowareAvp >, smacc2::SmaccState< StSecondPause, SmAutowareAvp >, smacc2::SmaccState< StSetupInitialLocationEstimation, SmAutowareAvp >, smacc2::SmaccState< StAcquireSensors, SmAwsWarehouseNavigation >, smacc2::SmaccState< StCheckPoint1, SmAwsWarehouseNavigation >, smacc2::SmaccState< StInitialNavigateForward, SmAwsWarehouseNavigation >, smacc2::SmaccState< StRotateMainAisle, SmAwsWarehouseNavigation >, smacc2::SmaccState< StStartNavigation, SmAwsWarehouseNavigation >, smacc2::SmaccState< State1, SmBranching >, smacc2::SmaccState< State2, SmBranching >, smacc2::SmaccState< State2b, SmBranching >, smacc2::SmaccState< State2c, SmBranching >, smacc2::SmaccState< State3, SmBranching >, smacc2::SmaccState< State3b, SmBranching >, smacc2::SmaccState< State3c, SmBranching >, smacc2::SmaccState< State4, SmBranching >, smacc2::SmaccState< State4c, SmBranching >, smacc2::SmaccState< State5, SmBranching >, smacc2::SmaccState< State5b, SmBranching >, smacc2::SmaccState< State6, SmBranching >, smacc2::SmaccState< State1, SmCoretestTransitionSpeed1 >, smacc2::SmaccState< State2, SmCoretestTransitionSpeed1 >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBot >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBot, StAcquireSensors >, smacc2::SmaccState< SsRadialPattern1, MsDanceBotRunMode, StiRadialLoopStart >, smacc2::SmaccState< SsRadialPattern2, MsDanceBotRunMode, StiRadialLoopStart >, smacc2::SmaccState< SsRadialPattern3, MsDanceBotRunMode, StiRadialLoopStart >, smacc2::SmaccState< SsFPattern1, MsDanceBotRunMode, StiFPatternStartLoop< SsFPattern1 > >, smacc2::SmaccState< StiFPatternStartLoop< SsFPattern1 >, SsFPattern1 >, smacc2::SmaccState< SsSPattern1, MsDanceBotRunMode, StiSPatternLoopStart >, smacc2::SmaccState< StAcquireSensors, MsDanceBotRunMode >, smacc2::SmaccState< StEventCountDown, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateForward1, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateForward2, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse1, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse2, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse3, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse4, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypoint1, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypointsX, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees1, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees2, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees3, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees4, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees5, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees6, MsDanceBotRunMode >, smacc2::SmaccState< StiFPatternForward1< SS >, SS >, smacc2::SmaccState< StiFPatternForward2< SS >, SS >, smacc2::SmaccState< StiFPatternReturn1< SS >, SS >, smacc2::SmaccState< StiFPatternRotate1< SS >, SS >, smacc2::SmaccState< StiFPatternRotate2< SS >, SS >, smacc2::SmaccState< StiFPatternStartLoop< SS >, SS >, smacc2::SmaccState< StiRadialEndPoint, SS >, smacc2::SmaccState< StiRadialLoopStart, SS >, smacc2::SmaccState< StiRadialReturn, SS >, smacc2::SmaccState< StiRadialRotate, SS >, smacc2::SmaccState< TDerived, TContext >, smacc2::SmaccState< StiSPatternForward1, SS >, smacc2::SmaccState< StiSPatternForward2, SS >, smacc2::SmaccState< StiSPatternForward3, SS >, smacc2::SmaccState< StiSPatternForward4, SS >, smacc2::SmaccState< StiSPatternLoopStart, SS >, smacc2::SmaccState< StiSPatternRotate1, SS >, smacc2::SmaccState< StiSPatternRotate2, SS >, smacc2::SmaccState< StiSPatternRotate3, SS >, smacc2::SmaccState< StiSPatternRotate4, SS >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotStrikesBack >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotStrikesBack, StAcquireSensors >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotWarehouse >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotWarehouse, StAcquireSensors >, smacc2::SmaccState< SsSPattern2, MsDanceBotRunMode, StiSPatternLoopStart >, smacc2::SmaccState< StiFPatternRetryRelativeForward1< SS >, SS >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotWareHouse2 >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotWareHouse2, StAcquireSensors >, smacc2::SmaccState< StForwardAisle, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateNextWaypoint, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateUndoMotion, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateUndoMotion2, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateUndoMotionLeaf, MsDanceBotRunMode >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotWareHouse3 >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotWareHouse3, StAcquireSensors >, smacc2::SmaccState< StInitialSpinning, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypoint1Recovery, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypointsX2, MsDanceBotRunMode >, smacc2::SmaccState< StiRadialEndPointRecovery, SS >, smacc2::SmaccState< MsRecover, SmFerrari >, smacc2::SmaccState< MsRun, SmFerrari, StState1 >, smacc2::SmaccState< Ss1, MsRun, StiState1 >, smacc2::SmaccState< Ss2, MsRun, StiState1 >, smacc2::SmaccState< StState1, MsRun >, smacc2::SmaccState< StState2, MsRun >, smacc2::SmaccState< StState3, MsRun >, smacc2::SmaccState< StState4, MsRun >, smacc2::SmaccState< StiState1, SS >, smacc2::SmaccState< StiState2, SS >, smacc2::SmaccState< StiState3, SS >, smacc2::SmaccState< SsSPattern1, SmHuskyBarrelSearch1, StiSPatternLoopStart >, smacc2::SmaccState< SsSearchMineSPattern1, SmHuskyBarrelSearch1, StiSPatternLoopStart >, smacc2::SmaccState< StAcquireSensors, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StCrossMineFieldSlowly, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StDeactivateMine, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StDetectItems, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StEvasionMotion, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StExploreAndRetreat, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StMoveBackwardsBlinking, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StNavigateToWaypointX, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StSatelliteComunications, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StSelfDestruction, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StUndoRetreat, SmHuskyBarrelSearch1 >, smacc2::SmaccState< Mode1SequenceALoop, MsMode1 >, smacc2::SmaccState< Mode1SequenceBLoop, MsMode1 >, smacc2::SmaccState< Mode1StObserve, MsMode1 >, smacc2::SmaccState< Mode2SequenceALoop, MsMode2 >, smacc2::SmaccState< Mode2SequenceBLoop, MsMode2 >, smacc2::SmaccState< Mode2StObserve, MsMode2 >, smacc2::SmaccState< Mode3SequenceALoop, MsMode3 >, smacc2::SmaccState< Mode3SequenceBLoop, MsMode3 >, smacc2::SmaccState< Mode3StObserve, MsMode3 >, smacc2::SmaccState< Mode4SequenceALoop, MsMode4 >, smacc2::SmaccState< Mode4SequenceB, MsMode4 >, smacc2::SmaccState< Mode4SequenceCLoop, MsMode4 >, smacc2::SmaccState< Mode4SequenceDLoop, MsMode4 >, smacc2::SmaccState< Mode4StObserve, MsMode4 >, smacc2::SmaccState< Mode5SequenceALoop, MsMode5 >, smacc2::SmaccState< Mode5SequenceBLoop, MsMode5 >, smacc2::SmaccState< Mode5StObserve, MsMode5 >, smacc2::SmaccState< MsMode1, SmMultiStage1, Mode1StObserve >, smacc2::SmaccState< MsMode2, SmMultiStage1, Mode2StObserve >, smacc2::SmaccState< MsMode3, SmMultiStage1, Mode3StObserve >, smacc2::SmaccState< MsMode4, SmMultiStage1, Mode4StObserve >, smacc2::SmaccState< MsMode5, SmMultiStage1, Mode5StObserve >, smacc2::SmaccState< MsRecovery1, SmMultiStage1, StRecoveryAnalyze1 >, smacc2::SmaccState< MsRecovery2, SmMultiStage1, StRecoveryAnalyze2 >, smacc2::SmaccState< SsMode1SequenceA, MsMode1, StiMode1SequenceALoop >, smacc2::SmaccState< SsMode1SequenceB, MsMode1, StiMode1SequenceBLoop >, smacc2::SmaccState< SsMode2SequenceA, MsMode2, StiMode2SequenceALoop >, smacc2::SmaccState< SsMode2SequenceB, MsMode2, StiMode2SequenceBLoop >, smacc2::SmaccState< SsMode3SequenceA, MsMode3, StiMode3SequenceALoop >, smacc2::SmaccState< SsMode3SequenceB, MsMode3, StiMode3SequenceBLoop >, smacc2::SmaccState< SsMode4SequenceA, MsMode4, StiMode4SequenceALoop >, smacc2::SmaccState< SsMode4SequenceB, MsMode4, StiMode4SequenceB >, smacc2::SmaccState< SsMode4SequenceC, MsMode4, StiMode4SequenceCLoop >, smacc2::SmaccState< SsMode4SequenceD, MsMode4, StiMode4SequenceDLoop >, smacc2::SmaccState< SsMode5SequenceA, MsMode5, StiMode5SequenceALoop >, smacc2::SmaccState< SsMode5SequenceB, MsMode5, StiMode5SequenceBLoop >, smacc2::SmaccState< StRecoveryAnalyze1, MsRecovery1 >, smacc2::SmaccState< StRecoveryAnalyze2, MsRecovery2 >, smacc2::SmaccState< StRecoveryBifurcate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryBifurcate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryCalculate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryCalculate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryDeliberate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryDeliberate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryEvaluate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryEvaluate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryGenerate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryGenerate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryInnervate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryInnervate2, MsRecovery2 >, smacc2::SmaccState< StiMode1SequenceALoop, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep1, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep2, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep3, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep4, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep5, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep6, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep7, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep8, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep9, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceBLoop, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep1, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep2, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep3, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep4, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep5, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep6, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep7, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep8, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep9, SsMode1SequenceB >, smacc2::SmaccState< StiMode2SequenceALoop, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep1, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep2, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep3, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep4, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep5, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep6, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep7, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep8, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep9, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceBLoop, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep1, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep2, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep3, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep4, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep5, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep6, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep7, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep8, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep9, SsMode2SequenceB >, smacc2::SmaccState< StiMode3SequenceALoop, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep1, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep2, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep3, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep4, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep5, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep6, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep7, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep8, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep9, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceBLoop, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep1, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep2, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep3, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep4, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep5, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep6, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep7, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep8, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep9, SsMode3SequenceB >, smacc2::SmaccState< StiMode4SequenceALoop, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep1, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep2, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep3, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep4, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep5, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep6, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep7, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep8, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep9, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceB, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep1, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep2, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep3, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep4, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep5, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep6, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep7, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep8, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep9, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceCLoop, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep1, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep2, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep3, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep4, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep5, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep6, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep7, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep8, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep9, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceDLoop, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep1, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep2, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep3, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep4, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep5, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep6, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep7, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep8, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep9, SsMode4SequenceD >, smacc2::SmaccState< StiMode5SequenceALoop, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep1, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep2, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep3, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep4, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep5, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep6, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep7, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep8, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep9, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceBLoop, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep1, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep2, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep3, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep4, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep5, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep6, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep7, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep8, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep9, SsMode5SequenceB >, smacc2::SmaccState< StAcquireSensors, SmTestMoveitUr5Sim >, smacc2::SmaccState< StAttachObject, SmTestMoveitUr5Sim >, smacc2::SmaccState< StCircularPivotMotion, SmTestMoveitUr5Sim >, smacc2::SmaccState< StDetatchObject, SmTestMoveitUr5Sim >, smacc2::SmaccState< StEndEffectorRotate, SmTestMoveitUr5Sim >, smacc2::SmaccState< StExecuteLastTrajectory, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveCartesianRelative, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveCartesianRelative2, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveEndEffector, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveJoints, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveKnownState, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveLastTrajectoryInitialState, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveNamedTarget, SmTestMoveitUr5Sim >, smacc2::SmaccState< StPouringMotion, SmTestMoveitUr5Sim >, smacc2::SmaccState< StUndoLastTrajectory, SmTestMoveitUr5Sim >, smacc2::SmaccState< CompletingSequenceALoop, MsCompleting >, smacc2::SmaccState< CompletingSequenceBLoop, MsCompleting >, smacc2::SmaccState< CompletingStObserve, MsCompleting >, smacc2::SmaccState< DsClearing, JsActive >, smacc2::SmaccState< DsRun, JsActive, MsIdle >, smacc2::SmaccState< DsStopped, JsActive >, smacc2::SmaccState< DsStopping, JsActive >, smacc2::SmaccState< ExecuteSequenceALoop, MsExecute >, smacc2::SmaccState< ExecuteSequenceBLoop, MsExecute >, smacc2::SmaccState< ExecuteStObserve, MsExecute >, smacc2::SmaccState< HoldingSequenceALoop, MsHolding >, smacc2::SmaccState< HoldingSequenceBLoop, MsHolding >, smacc2::SmaccState< HoldingStObserve, MsHolding >, smacc2::SmaccState< JsAborted, SmPackMl1 >, smacc2::SmaccState< JsAborting, SmPackMl1 >, smacc2::SmaccState< JsActive, SmPackMl1, DsRun >, smacc2::SmaccState< MsComplete, DsRun >, smacc2::SmaccState< MsCompleting, DsRun, CompletingStObserve >, smacc2::SmaccState< MsExecute, DsRun, ExecuteStObserve >, smacc2::SmaccState< MsHeld, DsRun >, smacc2::SmaccState< MsHolding, DsRun, HoldingStObserve >, smacc2::SmaccState< MsIdle, DsRun >, smacc2::SmaccState< MsResetting, DsRun >, smacc2::SmaccState< MsStarting, DsRun, StartStObserve >, smacc2::SmaccState< MsSuspended, DsRun >, smacc2::SmaccState< MsSuspending, DsRun, SuspendingStObserve >, smacc2::SmaccState< MsUnholding, DsRun >, smacc2::SmaccState< MsUnsuspending, DsRun >, smacc2::SmaccState< SsCompletingSequenceA, MsCompleting, StiCompletingSequenceALoop >, smacc2::SmaccState< SsCompletingSequenceB, MsCompleting, StiCompletingSequenceBLoop >, smacc2::SmaccState< SsExecuteSequenceA, MsExecute, StiExecuteSequenceALoop >, smacc2::SmaccState< SsExecuteSequenceB, MsExecute, StiExecuteSequenceBLoop >, smacc2::SmaccState< SsHoldingSequenceA, MsHolding, StiHoldingSequenceALoop >, smacc2::SmaccState< SsHoldingSequenceB, MsHolding, StiHoldingSequenceBLoop >, smacc2::SmaccState< SsStartSequenceA, MsStarting, StiStartSequenceALoop >, smacc2::SmaccState< SsStartSequenceB, MsStarting, StiStartSequenceBLoop >, smacc2::SmaccState< SsSuspendingSequenceA, MsSuspending, StiSuspendingSequenceALoop >, smacc2::SmaccState< SsSuspendingSequenceB, MsSuspending, StiSuspendingSequenceB >, smacc2::SmaccState< SsSuspendingSequenceC, MsSuspending, StiSuspendingSequenceCLoop >, smacc2::SmaccState< SsSuspendingSequenceD, MsSuspending, StiSuspendingSequenceDLoop >, smacc2::SmaccState< StartSequenceALoop, MsStarting >, smacc2::SmaccState< StartSequenceBLoop, MsStarting >, smacc2::SmaccState< StartStObserve, MsStarting >, smacc2::SmaccState< SuspendingSequenceALoop, MsSuspending >, smacc2::SmaccState< SuspendingSequenceB, MsSuspending >, smacc2::SmaccState< SuspendingSequenceCLoop, MsSuspending >, smacc2::SmaccState< SuspendingSequenceDLoop, MsSuspending >, smacc2::SmaccState< SuspendingStObserve, MsSuspending >, smacc2::SmaccState< StiCompletingSequenceALoop, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep1, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep2, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep3, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep4, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep5, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep6, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep7, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep8, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep9, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceBLoop, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep1, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep2, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep3, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep4, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep5, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep6, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep7, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep8, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep9, SsCompletingSequenceB >, smacc2::SmaccState< StiExecuteSequenceALoop, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep1, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep2, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep3, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep4, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep5, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep6, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep7, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep8, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep9, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceBLoop, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep1, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep2, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep3, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep4, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep5, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep6, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep7, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep8, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep9, SsExecuteSequenceB >, smacc2::SmaccState< StiHoldingSequenceALoop, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep1, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep2, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep3, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep4, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep5, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep6, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep7, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep8, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep9, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceBLoop, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep1, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep2, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep3, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep4, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep5, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep6, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep7, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep8, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep9, SsHoldingSequenceB >, smacc2::SmaccState< StiStartSequenceALoop, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep1, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep2, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep3, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep4, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep5, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep6, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep7, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep8, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep9, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceBLoop, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep1, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep2, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep3, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep4, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep5, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep6, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep7, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep8, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep9, SsStartSequenceB >, smacc2::SmaccState< StiSuspendingSequenceALoop, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep1, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep2, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep3, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep4, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep5, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep6, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep7, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep8, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep9, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceB, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep1, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep2, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep3, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep4, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep5, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep6, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep7, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep8, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep9, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceCLoop, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep1, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep2, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep3, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep4, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep5, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep6, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep7, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep8, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep9, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceDLoop, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep1, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep2, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep3, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep4, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep5, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep6, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep7, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep8, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep9, SsSuspendingSequenceD >, smacc2::SmaccState< MsRecover, SmPubsub1 >, smacc2::SmaccState< MsRun, SmPubsub1, StState1 >, smacc2::SmaccState< MsCalibration, SmRespira1, StCalibrationStep1 >, smacc2::SmaccState< MsLeakyLung, SmRespira1, StLeakyLungStep1 >, smacc2::SmaccState< MsPatientObstruction, SmRespira1, StPatientObstructionStep1 >, smacc2::SmaccState< MsRun, SmRespira1, StObserve >, smacc2::SmaccState< MsShutdown, SmRespira1, StSystemShutdown >, smacc2::SmaccState< SsACCycle, MsRun, StiACCycleLoop >, smacc2::SmaccState< SsCMVCycle, MsRun, StiCMVCycleLoop >, smacc2::SmaccState< SsPCCycle, MsRun, StiPCCycleLoop >, smacc2::SmaccState< SsPSCycle, MsRun, StiPSCycleLoop >, smacc2::SmaccState< StCalibrationStep1, MsCalibration >, smacc2::SmaccState< StLeakyLungStep1, MsLeakyLung >, smacc2::SmaccState< StLeakyLungStep2, MsLeakyLung >, smacc2::SmaccState< StLeakyLungStep3, MsLeakyLung >, smacc2::SmaccState< StPatientObstructionStep1, MsPatientObstruction >, smacc2::SmaccState< StPatientObstructionStep2, MsPatientObstruction >, smacc2::SmaccState< StSystemShutdown, MsShutdown >, smacc2::SmaccState< StiACCycleDwell, SsACCycle >, smacc2::SmaccState< StiACCycleExpire, SsACCycle >, smacc2::SmaccState< StiACCycleInspire, SsACCycle >, smacc2::SmaccState< StiACCycleLoop, SsACCycle >, smacc2::SmaccState< StiACCyclePlateau, SsACCycle >, smacc2::SmaccState< StiCMVCycleDwell, SsCMVCycle >, smacc2::SmaccState< StiCMVCycleExpire, SsCMVCycle >, smacc2::SmaccState< StiCMVCycleInspire, SsCMVCycle >, smacc2::SmaccState< StiCMVCycleLoop, SsCMVCycle >, smacc2::SmaccState< StiCMVCyclePlateau, SsCMVCycle >, smacc2::SmaccState< StiPCCycleDwell, SsPCCycle >, smacc2::SmaccState< StiPCCycleExpire, SsPCCycle >, smacc2::SmaccState< StiPCCycleInspire, SsPCCycle >, smacc2::SmaccState< StiPCCycleLoop, SsPCCycle >, smacc2::SmaccState< StiPCCyclePlateau, SsPCCycle >, smacc2::SmaccState< StiPSCycleDwell, SsPSCycle >, smacc2::SmaccState< StiPSCycleExpire, SsPSCycle >, smacc2::SmaccState< StiPSCycleInspire, SsPSCycle >, smacc2::SmaccState< StiPSCycleLoop, SsPSCycle >, smacc2::SmaccState< StiPSCyclePlateau, SsPSCycle >, smacc2::SmaccState< MsRecover, SmThreeSome >, smacc2::SmaccState< MsRun, SmThreeSome, StState1 >, and smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >.
Public Member Functions
virtual ISmaccStateMachine & getStateMachine ()=0
virtual std::string getName ()=0
ISmaccState * getParentState ()
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc2::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Protected Attributes
rclcpp::Node::SharedPtr node_
std::shared_ptr< rclcpp::Logger > logger_
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc2::SmaccEventGenerator > > eventGenerators_
ISmaccState * parentState_
const smacc2::introspection::SmaccStateInfo * stateInfo_
Detailed Description
Definition at line 25 of file smacc_state.hpp.
Member Function Documentation
configure()
template<typename TOrthogonal , typename TBehavior , typename... Args> std::shared_ptr< TBehavior > smacc2::ISmaccState::configure (Args &&... args)
Definition at line 37 of file smacc_state_impl.hpp.
{
  std::string orthogonalkey = demangledTypeName<TOrthogonal>();
  RCLCPP_INFO(
    getLogger(), "[%s] Configuring orthogonal: %s", THIS_STATE_NAME, orthogonalkey.c_str());
  TOrthogonal * orthogonal = this->getOrthogonal<TOrthogonal>();
  if (orthogonal != nullptr)
  {
    auto clientBehavior = std::shared_ptr<TBehavior>(new TBehavior(
      args...));  // is there an error here? are the behavior constructor parameters right?
    clientBehavior->currentState = this;
    orthogonal->addClientBehavior(clientBehavior);
    clientBehavior->template onOrthogonalAllocation<TOrthogonal, TBehavior>();
    return clientBehavior;
  }
  else
  {
    RCLCPP_ERROR(
      getLogger(), "[%s] Skipping client behavior creation in orthogonal [%s]. It does not exist.",
      THIS_STATE_NAME, orthogonalkey.c_str());
    return nullptr;
  }
}
References generate_debs::args, getLogger(), and THIS_STATE_NAME.
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::configure_orthogonal(), and smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::configure_orthogonal_runtime().
createEventGenerator()
template<typename TEventGenerator , typename... TEvArgs> std::shared_ptr< TEventGenerator > smacc2::ISmaccState::createEventGenerator (TEvArgs... args)
Definition at line 116 of file smacc_state_impl.hpp.
{
  auto eg = std::make_shared<TEventGenerator>(args...);
  eventGenerators_.push_back(eg);
  return eg;
}
References generate_debs::args, and eventGenerators_.
createStateReactor() [1/2]
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs> std::shared_ptr< TStateReactor > smacc2::ISmaccState::createStateReactor (TEvArgs... args)
Definition at line 155 of file smacc_state_impl.hpp.
{
  auto sr = std::make_shared<TStateReactor>(args...);
  sr->initialize(this);
  sr->template setOutputEvent<TTriggerEvent>();
  using boost::mpl::_1;
  using wrappedList = typename boost::mpl::transform<TEventList, _1>::type;
  AddTEventTypeStateReactor<TEventList> op(sr.get());
  boost::mpl::for_each<wrappedList>(op);
  stateReactors_.push_back(sr);
  return sr;
}
References generate_debs::args, stateReactors_, and generate_debs::type.
createStateReactor() [2/2]
template<typename TStateReactor , typename... TEvArgs> std::shared_ptr< TStateReactor > smacc2::ISmaccState::createStateReactor (TEvArgs... args)
Definition at line 106 of file smacc_state_impl.hpp.
{
  auto sr = std::make_shared<TStateReactor>(args...);
  //sb->initialize(this, mock);
  //sb->setOutputEvent(typelist<TTriggerEvent>());
  stateReactors_.push_back(sr);
  return sr;
}
References generate_debs::args, and stateReactors_.
getClassName()
std::string smacc2::ISmaccState::getClassName () virtual
Definition at line 26 of file smacc_state.cpp.
{ return demangleSymbol(typeid(*this).name()); }
References smacc2::introspection::demangleSymbol().
Referenced by smacc2::ISmaccStateMachine::propagateEventToStateReactors().
getEventGenerator()
template<typename TEventGenerator > TEventGenerator * smacc2::ISmaccState::getEventGenerator
Definition at line 177 of file smacc_state_impl.hpp.
{
  TEventGenerator * ret = nullptr;
  for (auto & evg : this->eventGenerators_)
  {
    ret = dynamic_cast<TEventGenerator *>(evg.get());
    if (ret != nullptr) break;
  }
  return ret;
}
References eventGenerators_.
getEventGenerators()
std::vector< std::shared_ptr< SmaccEventGenerator > > & smacc2::ISmaccState::getEventGenerators () inline
Definition at line 82 of file smacc_state.hpp.
  {
    return eventGenerators_;
  }
References eventGenerators_.
Referenced by smacc2::SignalDetector::findUpdatableStateElements(), and smacc2::ISmaccStateMachine::notifyOnStateEntryEnd().
getGlobalSMData()
template<typename T > bool smacc2::ISmaccState::getGlobalSMData (std::string name, T & ret)
Definition at line 91 of file smacc_state_impl.hpp.
{
  return this->getStateMachine().getGlobalSMData(name, ret);
}
References smacc2::ISmaccStateMachine::getGlobalSMData(), and getStateMachine().
getLogger()
rclcpp::Logger smacc2::ISmaccState::getLogger () inline
Definition at line 36 of file smacc_state.hpp.
{ return *logger_; }
References logger_.
Referenced by smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::checkWhileLoopConditionAndThrowEvent(), configure(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::entryStateInternal(), smacc2::StateReactor::getLogger(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleLoop::loopWhileCondition(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleLoop::loopWhileCondition(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleLoop::loopWhileCondition(), sm_dance_bot::radial_motion_states::StiRadialLoopStart::loopWhileCondition(), sm_dance_bot_strikes_back::radial_motion_states::StiRadialLoopStart::loopWhileCondition(), sm_dance_bot_warehouse::radial_motion_states::StiRadialLoopStart::loopWhileCondition(), sm_dance_bot_warehouse_2::radial_motion_states::StiRadialLoopStart::loopWhileCondition(), sm_dance_bot_warehouse_3::radial_motion_states::StiRadialLoopStart::loopWhileCondition(), sm_ferrari::inner_states::StiState1::loopWhileCondition(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceALoop::loopWhileCondition(), sm_multi_stage_1::Mode1SequenceALoop::loopWhileCondition(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBLoop::loopWhileCondition(), sm_multi_stage_1::Mode1SequenceBLoop::loopWhileCondition(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceALoop::loopWhileCondition(), sm_multi_stage_1::Mode2SequenceALoop::loopWhileCondition(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBLoop::loopWhileCondition(), sm_multi_stage_1::Mode2SequenceBLoop::loopWhileCondition(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceALoop::loopWhileCondition(), sm_multi_stage_1::Mode3SequenceALoop::loopWhileCondition(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBLoop::loopWhileCondition(), sm_multi_stage_1::Mode3SequenceBLoop::loopWhileCondition(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceALoop::loopWhileCondition(), sm_multi_stage_1::Mode4SequenceALoop::loopWhileCondition(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceB::loopWhileCondition(), sm_multi_stage_1::Mode4SequenceB::loopWhileCondition(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCLoop::loopWhileCondition(), sm_multi_stage_1::Mode4SequenceCLoop::loopWhileCondition(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDLoop::loopWhileCondition(), sm_multi_stage_1::Mode4SequenceDLoop::loopWhileCondition(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceALoop::loopWhileCondition(), sm_multi_stage_1::Mode5SequenceALoop::loopWhileCondition(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBLoop::loopWhileCondition(), sm_multi_stage_1::Mode5SequenceBLoop::loopWhileCondition(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceALoop::loopWhileCondition(), sm_pack_ml::CompletingSequenceALoop::loopWhileCondition(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBLoop::loopWhileCondition(), sm_pack_ml::CompletingSequenceBLoop::loopWhileCondition(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceALoop::loopWhileCondition(), sm_pack_ml::ExecuteSequenceALoop::loopWhileCondition(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBLoop::loopWhileCondition(), sm_pack_ml::ExecuteSequenceBLoop::loopWhileCondition(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceALoop::loopWhileCondition(), sm_pack_ml::HoldingSequenceALoop::loopWhileCondition(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBLoop::loopWhileCondition(), sm_pack_ml::HoldingSequenceBLoop::loopWhileCondition(), sm_pack_ml::start_sequence_a::StiStartSequenceALoop::loopWhileCondition(), sm_pack_ml::StartSequenceALoop::loopWhileCondition(), sm_pack_ml::start_sequence_b::StiStartSequenceBLoop::loopWhileCondition(), sm_pack_ml::StartSequenceBLoop::loopWhileCondition(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceALoop::loopWhileCondition(), sm_pack_ml::SuspendingSequenceALoop::loopWhileCondition(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceB::loopWhileCondition(), sm_pack_ml::SuspendingSequenceB::loopWhileCondition(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCLoop::loopWhileCondition(), sm_pack_ml::SuspendingSequenceCLoop::loopWhileCondition(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDLoop::loopWhileCondition(), sm_pack_ml::SuspendingSequenceDLoop::loopWhileCondition(), sm_pubsub_1::inner_states::StiState1::loopWhileCondition(), sm_respira_1::ac_cycle_inner_states::StiACCycleLoop::loopWhileCondition(), sm_respira_1::cmv_cycle_inner_states::StiCMVCycleLoop::loopWhileCondition(), sm_respira_1::pc_cycle_inner_states::StiPCCycleLoop::loopWhileCondition(), sm_respira_1::ps_cycle_inner_states::StiPSCycleLoop::loopWhileCondition(), sm_three_some::inner_states::StiState1::loopWhileCondition(), notifyTransitionFromTransitionTypeInfo(), sm_dance_bot::StNavigateForward1::onActionClientSucceeded(), sm_dance_bot_strikes_back::StNavigateForward1::onActionClientSucceeded(), sm_dance_bot_warehouse::StNavigateForward1::onActionClientSucceeded(), $sm_name$::State1::onEntry(), $sm_name$::State2::onEntry(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleLoop::onEntry(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep1::onEntry(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep2::onEntry(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep3::onEntry(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep4::onEntry(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep5::onEntry(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep6::onEntry(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep7::onEntry(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep8::onEntry(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep9::onEntry(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleLoop::onEntry(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep1::onEntry(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep2::onEntry(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep3::onEntry(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep4::onEntry(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep5::onEntry(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep6::onEntry(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep7::onEntry(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep8::onEntry(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep9::onEntry(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleLoop::onEntry(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep1::onEntry(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep2::onEntry(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep3::onEntry(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep4::onEntry(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep5::onEntry(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep6::onEntry(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep7::onEntry(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep8::onEntry(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep9::onEntry(), sm_advanced_recovery_1::StRecoverStep1::onEntry(), sm_advanced_recovery_1::StRecoverStep2::onEntry(), sm_advanced_recovery_1::StRecoverStep3::onEntry(), sm_advanced_recovery_1::StRecoverStep4::onEntry(), sm_advanced_recovery_1::StRecoverStep5::onEntry(), sm_advanced_recovery_1::StRecoverStep6::onEntry(), sm_advanced_recovery_1::StRecoverStep7::onEntry(), sm_advanced_recovery_1::StObserve::onEntry(), sm_atomic::State1::onEntry(), sm_atomic::State2::onEntry(), sm_atomic_24hr::State1::onEntry(), sm_atomic_24hr::State2::onEntry(), sm_atomic_hierarchy::State1::onEntry(), sm_atomic_hierarchy::State2::onEntry(), sm_atomic_hierarchy::StiState1::onEntry(), sm_autoware_avp::StAcquireSensors::onEntry(), sm_autoware_avp::StFirstPause::onEntry(), sm_autoware_avp::StNavigateWaypoint1::onEntry(), sm_autoware_avp::StNavigateWaypoint2::onEntry(), sm_autoware_avp::StSecondPause::onEntry(), sm_autoware_avp::StSetupInitialLocationEstimation::onEntry(), sm_branching::State1::onEntry(), sm_branching::State2::onEntry(), sm_branching::State2b::onEntry(), sm_branching::State2c::onEntry(), sm_branching::State3::onEntry(), sm_branching::State3b::onEntry(), sm_branching::State3c::onEntry(), sm_branching::State4::onEntry(), sm_branching::State4c::onEntry(), sm_branching::State5::onEntry(), sm_branching::State5b::onEntry(), sm_branching::State6::onEntry(), sm_dance_bot::radial_motion_states::StiRadialLoopStart::onEntry(), sm_dance_bot_strikes_back::radial_motion_states::StiRadialLoopStart::onEntry(), sm_dance_bot_warehouse::radial_motion_states::StiRadialLoopStart::onEntry(), sm_dance_bot_warehouse_2::radial_motion_states::StiRadialLoopStart::onEntry(), sm_dance_bot_warehouse_3::radial_motion_states::StiRadialLoopStart::onEntry(), sm_ferrari::inner_states::StiState1::onEntry(), sm_ferrari::inner_states::StiState2::onEntry(), sm_ferrari::inner_states::StiState3::onEntry(), sm_ferrari::StState1::onEntry(), sm_ferrari::StState2::onEntry(), sm_ferrari::StState3::onEntry(), sm_ferrari::StState4::onEntry(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceALoop::onEntry(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep1::onEntry(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep2::onEntry(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep3::onEntry(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep4::onEntry(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep5::onEntry(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep6::onEntry(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep7::onEntry(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep8::onEntry(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep9::onEntry(), sm_multi_stage_1::Mode1SequenceALoop::onEntry(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBLoop::onEntry(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep1::onEntry(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep2::onEntry(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep3::onEntry(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep4::onEntry(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep5::onEntry(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep6::onEntry(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep7::onEntry(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep8::onEntry(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep9::onEntry(), sm_multi_stage_1::Mode1SequenceBLoop::onEntry(), sm_multi_stage_1::Mode1StObserve::onEntry(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceALoop::onEntry(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep1::onEntry(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep2::onEntry(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep3::onEntry(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep4::onEntry(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep5::onEntry(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep6::onEntry(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep7::onEntry(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep8::onEntry(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep9::onEntry(), sm_multi_stage_1::Mode2SequenceALoop::onEntry(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBLoop::onEntry(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep1::onEntry(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep2::onEntry(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep3::onEntry(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep4::onEntry(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep5::onEntry(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep6::onEntry(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep7::onEntry(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep8::onEntry(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep9::onEntry(), sm_multi_stage_1::Mode2SequenceBLoop::onEntry(), sm_multi_stage_1::Mode2StObserve::onEntry(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceALoop::onEntry(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep1::onEntry(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep2::onEntry(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep3::onEntry(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep4::onEntry(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep5::onEntry(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep6::onEntry(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep7::onEntry(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep8::onEntry(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep9::onEntry(), sm_multi_stage_1::Mode3SequenceALoop::onEntry(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBLoop::onEntry(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep1::onEntry(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep2::onEntry(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep3::onEntry(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep4::onEntry(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep5::onEntry(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep6::onEntry(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep7::onEntry(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep8::onEntry(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep9::onEntry(), sm_multi_stage_1::Mode3SequenceBLoop::onEntry(), sm_multi_stage_1::Mode3StObserve::onEntry(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceALoop::onEntry(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep1::onEntry(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep2::onEntry(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep3::onEntry(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep4::onEntry(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep5::onEntry(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep6::onEntry(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep7::onEntry(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep8::onEntry(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep9::onEntry(), sm_multi_stage_1::Mode4SequenceALoop::onEntry(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceB::onEntry(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep1::onEntry(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep2::onEntry(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep3::onEntry(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep4::onEntry(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep5::onEntry(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep6::onEntry(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep7::onEntry(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep8::onEntry(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep9::onEntry(), sm_multi_stage_1::Mode4SequenceB::onEntry(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCLoop::onEntry(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep1::onEntry(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep2::onEntry(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep3::onEntry(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep4::onEntry(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep5::onEntry(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep6::onEntry(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep7::onEntry(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep8::onEntry(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep9::onEntry(), sm_multi_stage_1::Mode4SequenceCLoop::onEntry(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDLoop::onEntry(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep1::onEntry(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep2::onEntry(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep3::onEntry(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep4::onEntry(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep5::onEntry(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep6::onEntry(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep7::onEntry(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep8::onEntry(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep9::onEntry(), sm_multi_stage_1::Mode4SequenceDLoop::onEntry(), sm_multi_stage_1::Mode4StObserve::onEntry(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceALoop::onEntry(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep1::onEntry(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep2::onEntry(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep3::onEntry(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep4::onEntry(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep5::onEntry(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep6::onEntry(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep7::onEntry(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep8::onEntry(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep9::onEntry(), sm_multi_stage_1::Mode5SequenceALoop::onEntry(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBLoop::onEntry(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep1::onEntry(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep2::onEntry(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep3::onEntry(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep4::onEntry(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep5::onEntry(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep6::onEntry(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep7::onEntry(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep8::onEntry(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep9::onEntry(), sm_multi_stage_1::Mode5SequenceBLoop::onEntry(), sm_multi_stage_1::Mode5StObserve::onEntry(), sm_multi_stage_1::StRecoveryAnalyze1::onEntry(), sm_multi_stage_1::StRecoveryBifurcate1::onEntry(), sm_multi_stage_1::StRecoveryCalculate1::onEntry(), sm_multi_stage_1::StRecoveryDeliberate1::onEntry(), sm_multi_stage_1::StRecoveryEvaluate1::onEntry(), sm_multi_stage_1::StRecoveryGenerate1::onEntry(), sm_multi_stage_1::StRecoveryInnervate1::onEntry(), sm_multi_stage_1::StRecoveryAnalyze2::onEntry(), sm_multi_stage_1::StRecoveryBifurcate2::onEntry(), sm_multi_stage_1::StRecoveryCalculate2::onEntry(), sm_multi_stage_1::StRecoveryDeliberate2::onEntry(), sm_multi_stage_1::StRecoveryEvaluate2::onEntry(), sm_multi_stage_1::StRecoveryGenerate2::onEntry(), sm_multi_stage_1::StRecoveryInnervate2::onEntry(), sm_multi_ur5_sim::StAttachObject::onEntry(), sm_multi_ur5_sim::StCircularPivotMotion::onEntry(), sm_multi_ur5_sim::StDetatchObject::onEntry(), sm_multi_ur5_sim::StEndEffectorRotate::onEntry(), sm_multi_ur5_sim::StExecuteLastTrajectory::onEntry(), sm_multi_ur5_sim::StMoveCartesianRelative::onEntry(), sm_multi_ur5_sim::StMoveCartesianRelative2::onEntry(), sm_multi_ur5_sim::StMoveEndEffector::onEntry(), sm_multi_ur5_sim::StMoveKnownState::onEntry(), sm_multi_ur5_sim::StMoveLastTrajectoryInitialState::onEntry(), sm_multi_ur5_sim::StMoveNamedTarget::onEntry(), sm_multi_ur5_sim::StPouringMotion::onEntry(), sm_multi_ur5_sim::StUndoLastTrajectory::onEntry(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceALoop::onEntry(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep1::onEntry(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep2::onEntry(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep3::onEntry(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep4::onEntry(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep5::onEntry(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep6::onEntry(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep7::onEntry(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep8::onEntry(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep9::onEntry(), sm_pack_ml::CompletingSequenceALoop::onEntry(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBLoop::onEntry(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep1::onEntry(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep2::onEntry(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep3::onEntry(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep4::onEntry(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep5::onEntry(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep6::onEntry(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep7::onEntry(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep8::onEntry(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep9::onEntry(), sm_pack_ml::CompletingSequenceBLoop::onEntry(), sm_pack_ml::CompletingStObserve::onEntry(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceALoop::onEntry(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep1::onEntry(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep2::onEntry(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep3::onEntry(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep4::onEntry(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep5::onEntry(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep6::onEntry(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep7::onEntry(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep8::onEntry(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep9::onEntry(), sm_pack_ml::ExecuteSequenceALoop::onEntry(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBLoop::onEntry(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep1::onEntry(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep2::onEntry(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep3::onEntry(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep4::onEntry(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep5::onEntry(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep6::onEntry(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep7::onEntry(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep8::onEntry(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep9::onEntry(), sm_pack_ml::ExecuteSequenceBLoop::onEntry(), sm_pack_ml::ExecuteStObserve::onEntry(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceALoop::onEntry(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep1::onEntry(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep2::onEntry(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep3::onEntry(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep4::onEntry(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep5::onEntry(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep6::onEntry(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep7::onEntry(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep8::onEntry(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep9::onEntry(), sm_pack_ml::HoldingSequenceALoop::onEntry(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBLoop::onEntry(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep1::onEntry(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep2::onEntry(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep3::onEntry(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep4::onEntry(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep5::onEntry(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep6::onEntry(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep7::onEntry(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep8::onEntry(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep9::onEntry(), sm_pack_ml::HoldingSequenceBLoop::onEntry(), sm_pack_ml::HoldingStObserve::onEntry(), sm_pack_ml::StRecoveryAnalyze1::onEntry(), sm_pack_ml::StRecoveryBifurcate1::onEntry(), sm_pack_ml::StRecoveryCalculate1::onEntry(), sm_pack_ml::StRecoveryDeliberate1::onEntry(), sm_pack_ml::StRecoveryEvaluate1::onEntry(), sm_pack_ml::StRecoveryGenerate1::onEntry(), sm_pack_ml::StRecoveryInnervate1::onEntry(), sm_pack_ml::StRecoveryAnalyze2::onEntry(), sm_pack_ml::StRecoveryBifurcate2::onEntry(), sm_pack_ml::StRecoveryCalculate2::onEntry(), sm_pack_ml::StRecoveryDeliberate2::onEntry(), sm_pack_ml::StRecoveryEvaluate2::onEntry(), sm_pack_ml::StRecoveryGenerate2::onEntry(), sm_pack_ml::StRecoveryInnervate2::onEntry(), sm_pack_ml::start_sequence_a::StiStartSequenceALoop::onEntry(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep1::onEntry(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep2::onEntry(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep3::onEntry(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep4::onEntry(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep5::onEntry(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep6::onEntry(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep7::onEntry(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep8::onEntry(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep9::onEntry(), sm_pack_ml::StartSequenceALoop::onEntry(), sm_pack_ml::start_sequence_b::StiStartSequenceBLoop::onEntry(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep1::onEntry(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep2::onEntry(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep3::onEntry(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep4::onEntry(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep5::onEntry(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep6::onEntry(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep7::onEntry(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep8::onEntry(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep9::onEntry(), sm_pack_ml::StartSequenceBLoop::onEntry(), sm_pack_ml::StartStObserve::onEntry(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceALoop::onEntry(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep1::onEntry(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep2::onEntry(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep3::onEntry(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep4::onEntry(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep5::onEntry(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep6::onEntry(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep7::onEntry(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep8::onEntry(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep9::onEntry(), sm_pack_ml::SuspendingSequenceALoop::onEntry(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceB::onEntry(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep1::onEntry(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep2::onEntry(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep3::onEntry(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep4::onEntry(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep5::onEntry(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep6::onEntry(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep7::onEntry(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep8::onEntry(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep9::onEntry(), sm_pack_ml::SuspendingSequenceB::onEntry(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCLoop::onEntry(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep1::onEntry(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep2::onEntry(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep3::onEntry(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep4::onEntry(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep5::onEntry(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep6::onEntry(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep7::onEntry(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep8::onEntry(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep9::onEntry(), sm_pack_ml::SuspendingSequenceCLoop::onEntry(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDLoop::onEntry(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep1::onEntry(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep2::onEntry(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep3::onEntry(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep4::onEntry(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep5::onEntry(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep6::onEntry(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep7::onEntry(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep8::onEntry(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep9::onEntry(), sm_pack_ml::SuspendingSequenceDLoop::onEntry(), sm_pack_ml::SuspendingStObserve::onEntry(), sm_pubsub_1::inner_states::StiState1::onEntry(), sm_pubsub_1::inner_states::StiState2::onEntry(), sm_pubsub_1::inner_states::StiState3::onEntry(), sm_pubsub_1::StState1::onEntry(), sm_pubsub_1::StState2::onEntry(), sm_pubsub_1::StState3::onEntry(), sm_pubsub_1::StState4::onEntry(), sm_respira_1::ac_cycle_inner_states::StiACCycleDwell::onEntry(), sm_respira_1::ac_cycle_inner_states::StiACCycleExpire::onEntry(), sm_respira_1::ac_cycle_inner_states::StiACCycleInspire::onEntry(), sm_respira_1::ac_cycle_inner_states::StiACCycleLoop::onEntry(), sm_respira_1::ac_cycle_inner_states::StiACCyclePlateau::onEntry(), sm_respira_1::cmv_cycle_inner_states::StiCMVCycleDwell::onEntry(), sm_respira_1::cmv_cycle_inner_states::StiCMVCycleExpire::onEntry(), sm_respira_1::cmv_cycle_inner_states::StiCMVCycleInspire::onEntry(), sm_respira_1::cmv_cycle_inner_states::StiCMVCycleLoop::onEntry(), sm_respira_1::cmv_cycle_inner_states::StiCMVCyclePlateau::onEntry(), sm_respira_1::StCalibrationStep1::onEntry(), sm_respira_1::StLeakyLungStep1::onEntry(), sm_respira_1::StLeakyLungStep2::onEntry(), sm_respira_1::StLeakyLungStep3::onEntry(), sm_respira_1::StPatientObstructionStep1::onEntry(), sm_respira_1::StPatientObstructionStep2::onEntry(), sm_respira_1::StSystemShutdown::onEntry(), sm_respira_1::pc_cycle_inner_states::StiPCCycleDwell::onEntry(), sm_respira_1::pc_cycle_inner_states::StiPCCycleExpire::onEntry(), sm_respira_1::pc_cycle_inner_states::StiPCCycleInspire::onEntry(), sm_respira_1::pc_cycle_inner_states::StiPCCycleLoop::onEntry(), sm_respira_1::pc_cycle_inner_states::StiPCCyclePlateau::onEntry(), sm_respira_1::ps_cycle_inner_states::StiPSCycleDwell::onEntry(), sm_respira_1::ps_cycle_inner_states::StiPSCycleExpire::onEntry(), sm_respira_1::ps_cycle_inner_states::StiPSCycleInspire::onEntry(), sm_respira_1::ps_cycle_inner_states::StiPSCycleLoop::onEntry(), sm_respira_1::ps_cycle_inner_states::StiPSCyclePlateau::onEntry(), sm_respira_1::StObserve::onEntry(), sm_test_moveit_ur5_sim::StAttachObject::onEntry(), sm_test_moveit_ur5_sim::StCircularPivotMotion::onEntry(), sm_test_moveit_ur5_sim::StDetatchObject::onEntry(), sm_test_moveit_ur5_sim::StEndEffectorRotate::onEntry(), sm_test_moveit_ur5_sim::StExecuteLastTrajectory::onEntry(), sm_test_moveit_ur5_sim::StMoveCartesianRelative::onEntry(), sm_test_moveit_ur5_sim::StMoveCartesianRelative2::onEntry(), sm_test_moveit_ur5_sim::StMoveEndEffector::onEntry(), sm_test_moveit_ur5_sim::StMoveKnownState::onEntry(), sm_test_moveit_ur5_sim::StMoveLastTrajectoryInitialState::onEntry(), sm_test_moveit_ur5_sim::StMoveNamedTarget::onEntry(), sm_test_moveit_ur5_sim::StPouringMotion::onEntry(), sm_test_moveit_ur5_sim::StUndoLastTrajectory::onEntry(), sm_three_some::inner_states::StiState1::onEntry(), sm_three_some::inner_states::StiState2::onEntry(), sm_three_some::inner_states::StiState3::onEntry(), sm_three_some::StState1::onEntry(), sm_three_some::StState2::onEntry(), sm_three_some::StState3::onEntry(), sm_three_some::StState4::onEntry(), $sm_name$::State1::onExit(), $sm_name$::State2::onExit(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep1::onExit(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep2::onExit(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep3::onExit(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep4::onExit(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep5::onExit(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep6::onExit(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep7::onExit(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep8::onExit(), sm_advanced_recovery_1::a_cycle_inner_states::StiACycleStep9::onExit(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep1::onExit(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep2::onExit(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep3::onExit(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep4::onExit(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep5::onExit(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep6::onExit(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep7::onExit(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep8::onExit(), sm_advanced_recovery_1::b_cyclenner_states::StiBCycleStep9::onExit(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep1::onExit(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep2::onExit(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep3::onExit(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep4::onExit(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep5::onExit(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep6::onExit(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep7::onExit(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep8::onExit(), sm_advanced_recovery_1::c_cycle_inner_states::StiCCycleStep9::onExit(), sm_advanced_recovery_1::StRecoverStep1::onExit(), sm_advanced_recovery_1::StRecoverStep2::onExit(), sm_advanced_recovery_1::StRecoverStep3::onExit(), sm_advanced_recovery_1::StRecoverStep4::onExit(), sm_advanced_recovery_1::StRecoverStep5::onExit(), sm_advanced_recovery_1::StRecoverStep6::onExit(), sm_advanced_recovery_1::StRecoverStep7::onExit(), sm_advanced_recovery_1::StObserve::onExit(), sm_atomic::State1::onExit(), sm_atomic::State2::onExit(), sm_atomic_24hr::State1::onExit(), sm_atomic_24hr::State2::onExit(), sm_atomic_hierarchy::State1::onExit(), sm_atomic_hierarchy::State2::onExit(), sm_atomic_hierarchy::StiState1::onExit(), sm_autoware_avp::StAcquireSensors::onExit(), sm_autoware_avp::StFirstPause::onExit(), sm_autoware_avp::StNavigateWaypoint1::onExit(), sm_autoware_avp::StNavigateWaypoint2::onExit(), sm_autoware_avp::StSecondPause::onExit(), sm_autoware_avp::StSetupInitialLocationEstimation::onExit(), sm_branching::State1::onExit(), sm_branching::State2::onExit(), sm_branching::State2b::onExit(), sm_branching::State2c::onExit(), sm_branching::State3::onExit(), sm_branching::State3b::onExit(), sm_branching::State3c::onExit(), sm_branching::State4::onExit(), sm_branching::State4c::onExit(), sm_branching::State5::onExit(), sm_branching::State5b::onExit(), sm_branching::State6::onExit(), sm_dance_bot::SS2::SsRadialPattern2::onExit(), sm_dance_bot_strikes_back::SS2::SsRadialPattern2::onExit(), sm_dance_bot_warehouse::SS2::SsRadialPattern2::onExit(), sm_dance_bot_warehouse_2::SS2::SsRadialPattern2::onExit(), sm_dance_bot_warehouse_3::StNavigateUndoMotion::onExit(), sm_ferrari::inner_states::StiState1::onExit(), sm_ferrari::inner_states::StiState2::onExit(), sm_ferrari::inner_states::StiState3::onExit(), sm_ferrari::StState1::onExit(), sm_ferrari::StState2::onExit(), sm_ferrari::StState3::onExit(), sm_ferrari::StState4::onExit(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep1::onExit(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep2::onExit(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep3::onExit(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep4::onExit(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep5::onExit(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep6::onExit(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep7::onExit(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep8::onExit(), sm_multi_stage_1::mode_1_sequence_a::StiMode1SequenceAStep9::onExit(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep1::onExit(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep2::onExit(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep3::onExit(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep4::onExit(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep5::onExit(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep6::onExit(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep7::onExit(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep8::onExit(), sm_multi_stage_1::mode_1_sequence_b::StiMode1SequenceBStep9::onExit(), sm_multi_stage_1::Mode1StObserve::onExit(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep1::onExit(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep2::onExit(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep3::onExit(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep4::onExit(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep5::onExit(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep6::onExit(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep7::onExit(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep8::onExit(), sm_multi_stage_1::mode_2_sequence_a::StiMode2SequenceAStep9::onExit(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep1::onExit(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep2::onExit(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep3::onExit(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep4::onExit(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep5::onExit(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep6::onExit(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep7::onExit(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep8::onExit(), sm_multi_stage_1::mode_2_sequence_b::StiMode2SequenceBStep9::onExit(), sm_multi_stage_1::Mode2StObserve::onExit(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep1::onExit(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep2::onExit(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep3::onExit(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep4::onExit(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep5::onExit(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep6::onExit(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep7::onExit(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep8::onExit(), sm_multi_stage_1::mode_3_sequence_a::StiMode3SequenceAStep9::onExit(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep1::onExit(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep2::onExit(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep3::onExit(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep4::onExit(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep5::onExit(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep6::onExit(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep7::onExit(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep8::onExit(), sm_multi_stage_1::mode_3_sequence_b::StiMode3SequenceBStep9::onExit(), sm_multi_stage_1::Mode3StObserve::onExit(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep1::onExit(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep2::onExit(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep3::onExit(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep4::onExit(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep5::onExit(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep6::onExit(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep7::onExit(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep8::onExit(), sm_multi_stage_1::mode_4_sequence_a::StiMode4SequenceAStep9::onExit(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep1::onExit(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep2::onExit(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep3::onExit(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep4::onExit(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep5::onExit(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep6::onExit(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep7::onExit(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep8::onExit(), sm_multi_stage_1::mode_4_sequence_b::StiMode4SequenceBStep9::onExit(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep1::onExit(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep2::onExit(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep3::onExit(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep4::onExit(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep5::onExit(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep6::onExit(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep7::onExit(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep8::onExit(), sm_multi_stage_1::mode_4_sequence_c::StiMode4SequenceCStep9::onExit(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep1::onExit(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep2::onExit(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep3::onExit(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep4::onExit(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep5::onExit(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep6::onExit(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep7::onExit(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep8::onExit(), sm_multi_stage_1::mode_4_sequence_d::StiMode4SequenceDStep9::onExit(), sm_multi_stage_1::Mode4StObserve::onExit(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep1::onExit(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep2::onExit(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep3::onExit(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep4::onExit(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep5::onExit(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep6::onExit(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep7::onExit(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep8::onExit(), sm_multi_stage_1::mode_5_sequence_a::StiMode5SequenceAStep9::onExit(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep1::onExit(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep2::onExit(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep3::onExit(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep4::onExit(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep5::onExit(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep6::onExit(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep7::onExit(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep8::onExit(), sm_multi_stage_1::mode_5_sequence_b::StiMode5SequenceBStep9::onExit(), sm_multi_stage_1::Mode5StObserve::onExit(), sm_multi_stage_1::StRecoveryAnalyze1::onExit(), sm_multi_stage_1::StRecoveryBifurcate1::onExit(), sm_multi_stage_1::StRecoveryCalculate1::onExit(), sm_multi_stage_1::StRecoveryDeliberate1::onExit(), sm_multi_stage_1::StRecoveryEvaluate1::onExit(), sm_multi_stage_1::StRecoveryGenerate1::onExit(), sm_multi_stage_1::StRecoveryInnervate1::onExit(), sm_multi_stage_1::StRecoveryAnalyze2::onExit(), sm_multi_stage_1::StRecoveryBifurcate2::onExit(), sm_multi_stage_1::StRecoveryCalculate2::onExit(), sm_multi_stage_1::StRecoveryDeliberate2::onExit(), sm_multi_stage_1::StRecoveryEvaluate2::onExit(), sm_multi_stage_1::StRecoveryGenerate2::onExit(), sm_multi_stage_1::StRecoveryInnervate2::onExit(), sm_multi_ur5_sim::StAttachObject::onExit(), sm_multi_ur5_sim::StCircularPivotMotion::onExit(), sm_multi_ur5_sim::StDetatchObject::onExit(), sm_multi_ur5_sim::StEndEffectorRotate::onExit(), sm_multi_ur5_sim::StExecuteLastTrajectory::onExit(), sm_multi_ur5_sim::StMoveCartesianRelative::onExit(), sm_multi_ur5_sim::StMoveEndEffector::onExit(), sm_multi_ur5_sim::StMoveKnownState::onExit(), sm_multi_ur5_sim::StMoveLastTrajectoryInitialState::onExit(), sm_multi_ur5_sim::StMoveNamedTarget::onExit(), sm_multi_ur5_sim::StPouringMotion::onExit(), sm_multi_ur5_sim::StUndoLastTrajectory::onExit(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep1::onExit(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep2::onExit(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep3::onExit(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep4::onExit(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep5::onExit(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep6::onExit(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep7::onExit(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep8::onExit(), sm_pack_ml::completing_sequence_a::StiCompletingSequenceAStep9::onExit(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep1::onExit(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep2::onExit(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep3::onExit(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep4::onExit(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep5::onExit(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep6::onExit(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep7::onExit(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep8::onExit(), sm_pack_ml::completing_sequence_b::StiCompletingSequenceBStep9::onExit(), sm_pack_ml::CompletingStObserve::onExit(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep1::onExit(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep2::onExit(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep3::onExit(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep4::onExit(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep5::onExit(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep6::onExit(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep7::onExit(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep8::onExit(), sm_pack_ml::execute_sequence_a::StiExecuteSequenceAStep9::onExit(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep1::onExit(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep2::onExit(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep3::onExit(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep4::onExit(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep5::onExit(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep6::onExit(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep7::onExit(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep8::onExit(), sm_pack_ml::execute_sequence_b::StiExecuteSequenceBStep9::onExit(), sm_pack_ml::ExecuteStObserve::onExit(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep1::onExit(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep2::onExit(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep3::onExit(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep4::onExit(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep5::onExit(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep6::onExit(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep7::onExit(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep8::onExit(), sm_pack_ml::holding_sequence_a::StiHoldingSequenceAStep9::onExit(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep1::onExit(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep2::onExit(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep3::onExit(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep4::onExit(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep5::onExit(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep6::onExit(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep7::onExit(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep8::onExit(), sm_pack_ml::holding_sequence_b::StiHoldingSequenceBStep9::onExit(), sm_pack_ml::HoldingStObserve::onExit(), sm_pack_ml::StRecoveryAnalyze1::onExit(), sm_pack_ml::StRecoveryBifurcate1::onExit(), sm_pack_ml::StRecoveryCalculate1::onExit(), sm_pack_ml::StRecoveryDeliberate1::onExit(), sm_pack_ml::StRecoveryEvaluate1::onExit(), sm_pack_ml::StRecoveryGenerate1::onExit(), sm_pack_ml::StRecoveryInnervate1::onExit(), sm_pack_ml::StRecoveryAnalyze2::onExit(), sm_pack_ml::StRecoveryBifurcate2::onExit(), sm_pack_ml::StRecoveryCalculate2::onExit(), sm_pack_ml::StRecoveryDeliberate2::onExit(), sm_pack_ml::StRecoveryEvaluate2::onExit(), sm_pack_ml::StRecoveryGenerate2::onExit(), sm_pack_ml::StRecoveryInnervate2::onExit(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep1::onExit(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep2::onExit(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep3::onExit(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep4::onExit(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep5::onExit(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep6::onExit(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep7::onExit(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep8::onExit(), sm_pack_ml::start_sequence_a::StiStartSequenceAStep9::onExit(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep1::onExit(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep2::onExit(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep3::onExit(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep4::onExit(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep5::onExit(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep6::onExit(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep7::onExit(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep8::onExit(), sm_pack_ml::start_sequence_b::StiStartSequenceBStep9::onExit(), sm_pack_ml::StartStObserve::onExit(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep1::onExit(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep2::onExit(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep3::onExit(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep4::onExit(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep5::onExit(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep6::onExit(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep7::onExit(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep8::onExit(), sm_pack_ml::suspending_sequence_a::StiSuspendingSequenceAStep9::onExit(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep1::onExit(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep2::onExit(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep3::onExit(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep4::onExit(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep5::onExit(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep6::onExit(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep7::onExit(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep8::onExit(), sm_pack_ml::suspending_sequence_b::StiSuspendingSequenceBStep9::onExit(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep1::onExit(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep2::onExit(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep3::onExit(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep4::onExit(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep5::onExit(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep6::onExit(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep7::onExit(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep8::onExit(), sm_pack_ml::suspending_sequence_c::StiSuspendingSequenceCStep9::onExit(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep1::onExit(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep2::onExit(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep3::onExit(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep4::onExit(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep5::onExit(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep6::onExit(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep7::onExit(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep8::onExit(), sm_pack_ml::suspending_sequence_d::StiSuspendingSequenceDStep9::onExit(), sm_pack_ml::SuspendingStObserve::onExit(), sm_pubsub_1::inner_states::StiState1::onExit(), sm_pubsub_1::inner_states::StiState2::onExit(), sm_pubsub_1::inner_states::StiState3::onExit(), sm_pubsub_1::StState1::onExit(), sm_pubsub_1::StState2::onExit(), sm_pubsub_1::StState3::onExit(), sm_pubsub_1::StState4::onExit(), sm_respira_1::ac_cycle_inner_states::StiACCycleDwell::onExit(), sm_respira_1::ac_cycle_inner_states::StiACCycleExpire::onExit(), sm_respira_1::ac_cycle_inner_states::StiACCycleInspire::onExit(), sm_respira_1::ac_cycle_inner_states::StiACCyclePlateau::onExit(), sm_respira_1::cmv_cycle_inner_states::StiCMVCycleDwell::onExit(), sm_respira_1::cmv_cycle_inner_states::StiCMVCycleExpire::onExit(), sm_respira_1::cmv_cycle_inner_states::StiCMVCycleInspire::onExit(), sm_respira_1::cmv_cycle_inner_states::StiCMVCyclePlateau::onExit(), sm_respira_1::StCalibrationStep1::onExit(), sm_respira_1::StLeakyLungStep1::onExit(), sm_respira_1::StLeakyLungStep2::onExit(), sm_respira_1::StLeakyLungStep3::onExit(), sm_respira_1::StPatientObstructionStep1::onExit(), sm_respira_1::StPatientObstructionStep2::onExit(), sm_respira_1::StSystemShutdown::onExit(), sm_respira_1::pc_cycle_inner_states::StiPCCycleDwell::onExit(), sm_respira_1::pc_cycle_inner_states::StiPCCycleExpire::onExit(), sm_respira_1::pc_cycle_inner_states::StiPCCycleInspire::onExit(), sm_respira_1::pc_cycle_inner_states::StiPCCyclePlateau::onExit(), sm_respira_1::ps_cycle_inner_states::StiPSCycleDwell::onExit(), sm_respira_1::ps_cycle_inner_states::StiPSCycleExpire::onExit(), sm_respira_1::ps_cycle_inner_states::StiPSCycleInspire::onExit(), sm_respira_1::ps_cycle_inner_states::StiPSCyclePlateau::onExit(), sm_respira_1::StObserve::onExit(), sm_test_moveit_ur5_sim::StAttachObject::onExit(), sm_test_moveit_ur5_sim::StCircularPivotMotion::onExit(), sm_test_moveit_ur5_sim::StDetatchObject::onExit(), sm_test_moveit_ur5_sim::StEndEffectorRotate::onExit(), sm_test_moveit_ur5_sim::StExecuteLastTrajectory::onExit(), sm_test_moveit_ur5_sim::StMoveCartesianRelative::onExit(), sm_test_moveit_ur5_sim::StMoveEndEffector::onExit(), sm_test_moveit_ur5_sim::StMoveKnownState::onExit(), sm_test_moveit_ur5_sim::StMoveLastTrajectoryInitialState::onExit(), sm_test_moveit_ur5_sim::StMoveNamedTarget::onExit(), sm_test_moveit_ur5_sim::StPouringMotion::onExit(), sm_test_moveit_ur5_sim::StUndoLastTrajectory::onExit(), sm_three_some::inner_states::StiState1::onExit(), sm_three_some::inner_states::StiState2::onExit(), sm_three_some::inner_states::StiState3::onExit(), sm_three_some::StState1::onExit(), sm_three_some::StState2::onExit(), sm_three_some::StState3::onExit(), sm_three_some::StState4::onExit(), sm_multi_ur5_sim::StMoveCartesianRelative2::onExit(), sm_test_moveit_ur5_sim::StMoveCartesianRelative2::onExit(), requiresClient(), $sm_name$::State2::runtimeConfigure(), sm_atomic::State2::runtimeConfigure(), sm_atomic_24hr::State2::runtimeConfigure(), sm_atomic_hierarchy::State2::runtimeConfigure(), sm_atomic_hierarchy::StiState1::runtimeConfigure(), sm_autoware_avp::StFirstPause::runtimeConfigure(), sm_autoware_avp::StNavigateWaypoint1::runtimeConfigure(), sm_autoware_avp::StNavigateWaypoint2::runtimeConfigure(), sm_autoware_avp::StSecondPause::runtimeConfigure(), sm_autoware_avp::StSetupInitialLocationEstimation::runtimeConfigure(), sm_branching::State2::runtimeConfigure(), sm_branching::State2b::runtimeConfigure(), sm_branching::State2c::runtimeConfigure(), sm_branching::State3::runtimeConfigure(), sm_branching::State3b::runtimeConfigure(), sm_branching::State3c::runtimeConfigure(), sm_branching::State4::runtimeConfigure(), sm_branching::State4c::runtimeConfigure(), sm_branching::State5::runtimeConfigure(), sm_branching::State5b::runtimeConfigure(), sm_branching::State6::runtimeConfigure(), sm_dance_bot::s_pattern_states::StiSPatternRotate2::runtimeConfigure(), sm_dance_bot::s_pattern_states::StiSPatternRotate3::runtimeConfigure(), sm_dance_bot::s_pattern_states::StiSPatternRotate4::runtimeConfigure(), sm_dance_bot_strikes_back::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_strikes_back::s_pattern_states::StiSPatternRotate2::runtimeConfigure(), sm_dance_bot_strikes_back::s_pattern_states::StiSPatternRotate3::runtimeConfigure(), sm_dance_bot_strikes_back::s_pattern_states::StiSPatternRotate4::runtimeConfigure(), sm_dance_bot_warehouse::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternRotate2::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternRotate3::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternRotate4::runtimeConfigure(), sm_dance_bot_warehouse_2::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternRotate2::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternRotate3::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternRotate4::runtimeConfigure(), sm_husky_barrel_search_1::s_pattern_states::StiSPatternRotate2::runtimeConfigure(), sm_husky_barrel_search_1::s_pattern_states::StiSPatternRotate3::runtimeConfigure(), sm_husky_barrel_search_1::s_pattern_states::StiSPatternRotate4::runtimeConfigure(), sm_multi_ur5_sim::StAttachObject::runtimeConfigure(), sm_multi_ur5_sim::StCircularPivotMotion::runtimeConfigure(), sm_multi_ur5_sim::StDetatchObject::runtimeConfigure(), sm_multi_ur5_sim::StEndEffectorRotate::runtimeConfigure(), sm_multi_ur5_sim::StExecuteLastTrajectory::runtimeConfigure(), sm_multi_ur5_sim::StMoveCartesianRelative::runtimeConfigure(), sm_multi_ur5_sim::StMoveCartesianRelative2::runtimeConfigure(), sm_multi_ur5_sim::StMoveEndEffector::runtimeConfigure(), sm_multi_ur5_sim::StMoveKnownState::runtimeConfigure(), sm_multi_ur5_sim::StMoveLastTrajectoryInitialState::runtimeConfigure(), sm_multi_ur5_sim::StMoveNamedTarget::runtimeConfigure(), sm_multi_ur5_sim::StPouringMotion::runtimeConfigure(), sm_multi_ur5_sim::StUndoLastTrajectory::runtimeConfigure(), sm_test_moveit_ur5_sim::StAttachObject::runtimeConfigure(), sm_test_moveit_ur5_sim::StCircularPivotMotion::runtimeConfigure(), sm_test_moveit_ur5_sim::StDetatchObject::runtimeConfigure(), sm_test_moveit_ur5_sim::StEndEffectorRotate::runtimeConfigure(), sm_test_moveit_ur5_sim::StExecuteLastTrajectory::runtimeConfigure(), sm_test_moveit_ur5_sim::StMoveCartesianRelative::runtimeConfigure(), sm_test_moveit_ur5_sim::StMoveCartesianRelative2::runtimeConfigure(), sm_test_moveit_ur5_sim::StMoveEndEffector::runtimeConfigure(), sm_test_moveit_ur5_sim::StMoveKnownState::runtimeConfigure(), sm_test_moveit_ur5_sim::StMoveLastTrajectoryInitialState::runtimeConfigure(), sm_test_moveit_ur5_sim::StMoveNamedTarget::runtimeConfigure(), sm_test_moveit_ur5_sim::StPouringMotion::runtimeConfigure(), sm_test_moveit_ur5_sim::StUndoLastTrajectory::runtimeConfigure(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState(), sm_ferrari::StState2::update(), and sm_pubsub_1::StState2::update().
getName()
virtual std::string smacc2::ISmaccState::getName () pure virtual
Implemented in smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >, smacc2::SmaccState< State1, $SmName$ >, smacc2::SmaccState< State2, $SmName$ >, smacc2::SmaccState< MsRecover, SmAdvancedRecovery1, StRecoverStep1 >, smacc2::SmaccState< MsRun, SmAdvancedRecovery1, StObserve >, smacc2::SmaccState< SsACycle, MsRun, StiACycleLoop >, smacc2::SmaccState< SsBCycle, MsRun, StiBCycleLoop >, smacc2::SmaccState< SsCCycle, MsRun, StiCCycleLoop >, smacc2::SmaccState< StObserve, MsRun >, smacc2::SmaccState< StRecoverStep1, MsRecover >, smacc2::SmaccState< StRecoverStep2, MsRecover >, smacc2::SmaccState< StRecoverStep3, MsRecover >, smacc2::SmaccState< StRecoverStep4, MsRecover >, smacc2::SmaccState< StRecoverStep5, MsRecover >, smacc2::SmaccState< StRecoverStep6, MsRecover >, smacc2::SmaccState< StRecoverStep7, MsRecover >, smacc2::SmaccState< StiACycleLoop, SsACycle >, smacc2::SmaccState< StiACycleStep1, SsACycle >, smacc2::SmaccState< StiACycleStep2, SsACycle >, smacc2::SmaccState< StiACycleStep3, SsACycle >, smacc2::SmaccState< StiACycleStep4, SsACycle >, smacc2::SmaccState< StiACycleStep5, SsACycle >, smacc2::SmaccState< StiACycleStep6, SsACycle >, smacc2::SmaccState< StiACycleStep7, SsACycle >, smacc2::SmaccState< StiACycleStep8, SsACycle >, smacc2::SmaccState< StiACycleStep9, SsACycle >, smacc2::SmaccState< StiBCycleLoop, SsBCycle >, smacc2::SmaccState< StiBCycleStep1, SsBCycle >, smacc2::SmaccState< StiBCycleStep2, SsBCycle >, smacc2::SmaccState< StiBCycleStep3, SsBCycle >, smacc2::SmaccState< StiBCycleStep4, SsBCycle >, smacc2::SmaccState< StiBCycleStep5, SsBCycle >, smacc2::SmaccState< StiBCycleStep6, SsBCycle >, smacc2::SmaccState< StiBCycleStep7, SsBCycle >, smacc2::SmaccState< StiBCycleStep8, SsBCycle >, smacc2::SmaccState< StiBCycleStep9, SsBCycle >, smacc2::SmaccState< StiCCycleLoop, SsCCycle >, smacc2::SmaccState< StiCCycleStep1, SsCCycle >, smacc2::SmaccState< StiCCycleStep2, SsCCycle >, smacc2::SmaccState< StiCCycleStep3, SsCCycle >, smacc2::SmaccState< StiCCycleStep4, SsCCycle >, smacc2::SmaccState< StiCCycleStep5, SsCCycle >, smacc2::SmaccState< StiCCycleStep6, SsCCycle >, smacc2::SmaccState< StiCCycleStep7, SsCCycle >, smacc2::SmaccState< StiCCycleStep8, SsCCycle >, smacc2::SmaccState< StiCCycleStep9, SsCCycle >, smacc2::SmaccState< State1, SmAtomic >, smacc2::SmaccState< State2, SmAtomic >, smacc2::SmaccState< State1, SmAtomic24Hr >, smacc2::SmaccState< State2, SmAtomic24Hr >, smacc2::SmaccState< State1, SmAtomicHierarchy, StiState1 >, smacc2::SmaccState< State2, SmAtomicHierarchy >, smacc2::SmaccState< StiState1, State1 >, smacc2::SmaccState< State1, SmAtomicPerformanceTrace1 >, smacc2::SmaccState< State2, SmAtomicPerformanceTrace1 >, smacc2::SmaccState< State1, SmAtomicSubscribersPerformanceTest >, smacc2::SmaccState< State2, SmAtomicSubscribersPerformanceTest >, smacc2::SmaccState< StAcquireSensors, SmAutowareAvp >, smacc2::SmaccState< StFirstPause, SmAutowareAvp >, smacc2::SmaccState< StNavigateWaypoint1, SmAutowareAvp >, smacc2::SmaccState< StNavigateWaypoint2, SmAutowareAvp >, smacc2::SmaccState< StSecondPause, SmAutowareAvp >, smacc2::SmaccState< StSetupInitialLocationEstimation, SmAutowareAvp >, smacc2::SmaccState< StAcquireSensors, SmAwsWarehouseNavigation >, smacc2::SmaccState< StCheckPoint1, SmAwsWarehouseNavigation >, smacc2::SmaccState< StInitialNavigateForward, SmAwsWarehouseNavigation >, smacc2::SmaccState< StRotateMainAisle, SmAwsWarehouseNavigation >, smacc2::SmaccState< StStartNavigation, SmAwsWarehouseNavigation >, smacc2::SmaccState< State1, SmBranching >, smacc2::SmaccState< State2, SmBranching >, smacc2::SmaccState< State2b, SmBranching >, smacc2::SmaccState< State2c, SmBranching >, smacc2::SmaccState< State3, SmBranching >, smacc2::SmaccState< State3b, SmBranching >, smacc2::SmaccState< State3c, SmBranching >, smacc2::SmaccState< State4, SmBranching >, smacc2::SmaccState< State4c, SmBranching >, smacc2::SmaccState< State5, SmBranching >, smacc2::SmaccState< State5b, SmBranching >, smacc2::SmaccState< State6, SmBranching >, smacc2::SmaccState< State1, SmCoretestTransitionSpeed1 >, smacc2::SmaccState< State2, SmCoretestTransitionSpeed1 >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBot >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBot, StAcquireSensors >, smacc2::SmaccState< SsRadialPattern1, MsDanceBotRunMode, StiRadialLoopStart >, smacc2::SmaccState< SsRadialPattern2, MsDanceBotRunMode, StiRadialLoopStart >, smacc2::SmaccState< SsRadialPattern3, MsDanceBotRunMode, StiRadialLoopStart >, smacc2::SmaccState< SsFPattern1, MsDanceBotRunMode, StiFPatternStartLoop< SsFPattern1 > >, smacc2::SmaccState< StiFPatternStartLoop< SsFPattern1 >, SsFPattern1 >, smacc2::SmaccState< SsSPattern1, MsDanceBotRunMode, StiSPatternLoopStart >, smacc2::SmaccState< StAcquireSensors, MsDanceBotRunMode >, smacc2::SmaccState< StEventCountDown, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateForward1, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateForward2, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse1, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse2, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse3, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse4, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypoint1, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypointsX, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees1, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees2, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees3, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees4, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees5, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees6, MsDanceBotRunMode >, smacc2::SmaccState< StiFPatternForward1< SS >, SS >, smacc2::SmaccState< StiFPatternForward2< SS >, SS >, smacc2::SmaccState< StiFPatternReturn1< SS >, SS >, smacc2::SmaccState< StiFPatternRotate1< SS >, SS >, smacc2::SmaccState< StiFPatternRotate2< SS >, SS >, smacc2::SmaccState< StiFPatternStartLoop< SS >, SS >, smacc2::SmaccState< StiRadialEndPoint, SS >, smacc2::SmaccState< StiRadialLoopStart, SS >, smacc2::SmaccState< StiRadialReturn, SS >, smacc2::SmaccState< StiRadialRotate, SS >, smacc2::SmaccState< TDerived, TContext >, smacc2::SmaccState< StiSPatternForward1, SS >, smacc2::SmaccState< StiSPatternForward2, SS >, smacc2::SmaccState< StiSPatternForward3, SS >, smacc2::SmaccState< StiSPatternForward4, SS >, smacc2::SmaccState< StiSPatternLoopStart, SS >, smacc2::SmaccState< StiSPatternRotate1, SS >, smacc2::SmaccState< StiSPatternRotate2, SS >, smacc2::SmaccState< StiSPatternRotate3, SS >, smacc2::SmaccState< StiSPatternRotate4, SS >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotStrikesBack >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotStrikesBack, StAcquireSensors >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotWarehouse >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotWarehouse, StAcquireSensors >, smacc2::SmaccState< SsSPattern2, MsDanceBotRunMode, StiSPatternLoopStart >, smacc2::SmaccState< StiFPatternRetryRelativeForward1< SS >, SS >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotWareHouse2 >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotWareHouse2, StAcquireSensors >, smacc2::SmaccState< StForwardAisle, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateNextWaypoint, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateUndoMotion, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateUndoMotion2, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateUndoMotionLeaf, MsDanceBotRunMode >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotWareHouse3 >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotWareHouse3, StAcquireSensors >, smacc2::SmaccState< StInitialSpinning, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypoint1Recovery, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypointsX2, MsDanceBotRunMode >, smacc2::SmaccState< StiRadialEndPointRecovery, SS >, smacc2::SmaccState< MsRecover, SmFerrari >, smacc2::SmaccState< MsRun, SmFerrari, StState1 >, smacc2::SmaccState< Ss1, MsRun, StiState1 >, smacc2::SmaccState< Ss2, MsRun, StiState1 >, smacc2::SmaccState< StState1, MsRun >, smacc2::SmaccState< StState2, MsRun >, smacc2::SmaccState< StState3, MsRun >, smacc2::SmaccState< StState4, MsRun >, smacc2::SmaccState< StiState1, SS >, smacc2::SmaccState< StiState2, SS >, smacc2::SmaccState< StiState3, SS >, smacc2::SmaccState< SsSPattern1, SmHuskyBarrelSearch1, StiSPatternLoopStart >, smacc2::SmaccState< SsSearchMineSPattern1, SmHuskyBarrelSearch1, StiSPatternLoopStart >, smacc2::SmaccState< StAcquireSensors, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StCrossMineFieldSlowly, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StDeactivateMine, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StDetectItems, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StEvasionMotion, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StExploreAndRetreat, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StMoveBackwardsBlinking, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StNavigateToWaypointX, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StSatelliteComunications, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StSelfDestruction, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StUndoRetreat, SmHuskyBarrelSearch1 >, smacc2::SmaccState< Mode1SequenceALoop, MsMode1 >, smacc2::SmaccState< Mode1SequenceBLoop, MsMode1 >, smacc2::SmaccState< Mode1StObserve, MsMode1 >, smacc2::SmaccState< Mode2SequenceALoop, MsMode2 >, smacc2::SmaccState< Mode2SequenceBLoop, MsMode2 >, smacc2::SmaccState< Mode2StObserve, MsMode2 >, smacc2::SmaccState< Mode3SequenceALoop, MsMode3 >, smacc2::SmaccState< Mode3SequenceBLoop, MsMode3 >, smacc2::SmaccState< Mode3StObserve, MsMode3 >, smacc2::SmaccState< Mode4SequenceALoop, MsMode4 >, smacc2::SmaccState< Mode4SequenceB, MsMode4 >, smacc2::SmaccState< Mode4SequenceCLoop, MsMode4 >, smacc2::SmaccState< Mode4SequenceDLoop, MsMode4 >, smacc2::SmaccState< Mode4StObserve, MsMode4 >, smacc2::SmaccState< Mode5SequenceALoop, MsMode5 >, smacc2::SmaccState< Mode5SequenceBLoop, MsMode5 >, smacc2::SmaccState< Mode5StObserve, MsMode5 >, smacc2::SmaccState< MsMode1, SmMultiStage1, Mode1StObserve >, smacc2::SmaccState< MsMode2, SmMultiStage1, Mode2StObserve >, smacc2::SmaccState< MsMode3, SmMultiStage1, Mode3StObserve >, smacc2::SmaccState< MsMode4, SmMultiStage1, Mode4StObserve >, smacc2::SmaccState< MsMode5, SmMultiStage1, Mode5StObserve >, smacc2::SmaccState< MsRecovery1, SmMultiStage1, StRecoveryAnalyze1 >, smacc2::SmaccState< MsRecovery2, SmMultiStage1, StRecoveryAnalyze2 >, smacc2::SmaccState< SsMode1SequenceA, MsMode1, StiMode1SequenceALoop >, smacc2::SmaccState< SsMode1SequenceB, MsMode1, StiMode1SequenceBLoop >, smacc2::SmaccState< SsMode2SequenceA, MsMode2, StiMode2SequenceALoop >, smacc2::SmaccState< SsMode2SequenceB, MsMode2, StiMode2SequenceBLoop >, smacc2::SmaccState< SsMode3SequenceA, MsMode3, StiMode3SequenceALoop >, smacc2::SmaccState< SsMode3SequenceB, MsMode3, StiMode3SequenceBLoop >, smacc2::SmaccState< SsMode4SequenceA, MsMode4, StiMode4SequenceALoop >, smacc2::SmaccState< SsMode4SequenceB, MsMode4, StiMode4SequenceB >, smacc2::SmaccState< SsMode4SequenceC, MsMode4, StiMode4SequenceCLoop >, smacc2::SmaccState< SsMode4SequenceD, MsMode4, StiMode4SequenceDLoop >, smacc2::SmaccState< SsMode5SequenceA, MsMode5, StiMode5SequenceALoop >, smacc2::SmaccState< SsMode5SequenceB, MsMode5, StiMode5SequenceBLoop >, smacc2::SmaccState< StRecoveryAnalyze1, MsRecovery1 >, smacc2::SmaccState< StRecoveryAnalyze2, MsRecovery2 >, smacc2::SmaccState< StRecoveryBifurcate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryBifurcate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryCalculate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryCalculate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryDeliberate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryDeliberate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryEvaluate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryEvaluate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryGenerate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryGenerate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryInnervate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryInnervate2, MsRecovery2 >, smacc2::SmaccState< StiMode1SequenceALoop, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep1, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep2, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep3, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep4, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep5, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep6, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep7, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep8, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep9, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceBLoop, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep1, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep2, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep3, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep4, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep5, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep6, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep7, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep8, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep9, SsMode1SequenceB >, smacc2::SmaccState< StiMode2SequenceALoop, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep1, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep2, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep3, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep4, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep5, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep6, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep7, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep8, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep9, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceBLoop, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep1, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep2, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep3, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep4, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep5, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep6, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep7, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep8, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep9, SsMode2SequenceB >, smacc2::SmaccState< StiMode3SequenceALoop, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep1, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep2, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep3, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep4, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep5, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep6, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep7, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep8, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep9, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceBLoop, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep1, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep2, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep3, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep4, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep5, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep6, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep7, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep8, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep9, SsMode3SequenceB >, smacc2::SmaccState< StiMode4SequenceALoop, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep1, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep2, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep3, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep4, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep5, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep6, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep7, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep8, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep9, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceB, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep1, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep2, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep3, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep4, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep5, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep6, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep7, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep8, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep9, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceCLoop, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep1, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep2, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep3, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep4, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep5, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep6, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep7, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep8, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep9, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceDLoop, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep1, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep2, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep3, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep4, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep5, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep6, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep7, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep8, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep9, SsMode4SequenceD >, smacc2::SmaccState< StiMode5SequenceALoop, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep1, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep2, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep3, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep4, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep5, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep6, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep7, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep8, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep9, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceBLoop, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep1, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep2, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep3, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep4, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep5, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep6, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep7, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep8, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep9, SsMode5SequenceB >, smacc2::SmaccState< StAcquireSensors, SmTestMoveitUr5Sim >, smacc2::SmaccState< StAttachObject, SmTestMoveitUr5Sim >, smacc2::SmaccState< StCircularPivotMotion, SmTestMoveitUr5Sim >, smacc2::SmaccState< StDetatchObject, SmTestMoveitUr5Sim >, smacc2::SmaccState< StEndEffectorRotate, SmTestMoveitUr5Sim >, smacc2::SmaccState< StExecuteLastTrajectory, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveCartesianRelative, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveCartesianRelative2, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveEndEffector, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveJoints, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveKnownState, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveLastTrajectoryInitialState, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveNamedTarget, SmTestMoveitUr5Sim >, smacc2::SmaccState< StPouringMotion, SmTestMoveitUr5Sim >, smacc2::SmaccState< StUndoLastTrajectory, SmTestMoveitUr5Sim >, smacc2::SmaccState< CompletingSequenceALoop, MsCompleting >, smacc2::SmaccState< CompletingSequenceBLoop, MsCompleting >, smacc2::SmaccState< CompletingStObserve, MsCompleting >, smacc2::SmaccState< DsClearing, JsActive >, smacc2::SmaccState< DsRun, JsActive, MsIdle >, smacc2::SmaccState< DsStopped, JsActive >, smacc2::SmaccState< DsStopping, JsActive >, smacc2::SmaccState< ExecuteSequenceALoop, MsExecute >, smacc2::SmaccState< ExecuteSequenceBLoop, MsExecute >, smacc2::SmaccState< ExecuteStObserve, MsExecute >, smacc2::SmaccState< HoldingSequenceALoop, MsHolding >, smacc2::SmaccState< HoldingSequenceBLoop, MsHolding >, smacc2::SmaccState< HoldingStObserve, MsHolding >, smacc2::SmaccState< JsAborted, SmPackMl1 >, smacc2::SmaccState< JsAborting, SmPackMl1 >, smacc2::SmaccState< JsActive, SmPackMl1, DsRun >, smacc2::SmaccState< MsComplete, DsRun >, smacc2::SmaccState< MsCompleting, DsRun, CompletingStObserve >, smacc2::SmaccState< MsExecute, DsRun, ExecuteStObserve >, smacc2::SmaccState< MsHeld, DsRun >, smacc2::SmaccState< MsHolding, DsRun, HoldingStObserve >, smacc2::SmaccState< MsIdle, DsRun >, smacc2::SmaccState< MsResetting, DsRun >, smacc2::SmaccState< MsStarting, DsRun, StartStObserve >, smacc2::SmaccState< MsSuspended, DsRun >, smacc2::SmaccState< MsSuspending, DsRun, SuspendingStObserve >, smacc2::SmaccState< MsUnholding, DsRun >, smacc2::SmaccState< MsUnsuspending, DsRun >, smacc2::SmaccState< SsCompletingSequenceA, MsCompleting, StiCompletingSequenceALoop >, smacc2::SmaccState< SsCompletingSequenceB, MsCompleting, StiCompletingSequenceBLoop >, smacc2::SmaccState< SsExecuteSequenceA, MsExecute, StiExecuteSequenceALoop >, smacc2::SmaccState< SsExecuteSequenceB, MsExecute, StiExecuteSequenceBLoop >, smacc2::SmaccState< SsHoldingSequenceA, MsHolding, StiHoldingSequenceALoop >, smacc2::SmaccState< SsHoldingSequenceB, MsHolding, StiHoldingSequenceBLoop >, smacc2::SmaccState< SsStartSequenceA, MsStarting, StiStartSequenceALoop >, smacc2::SmaccState< SsStartSequenceB, MsStarting, StiStartSequenceBLoop >, smacc2::SmaccState< SsSuspendingSequenceA, MsSuspending, StiSuspendingSequenceALoop >, smacc2::SmaccState< SsSuspendingSequenceB, MsSuspending, StiSuspendingSequenceB >, smacc2::SmaccState< SsSuspendingSequenceC, MsSuspending, StiSuspendingSequenceCLoop >, smacc2::SmaccState< SsSuspendingSequenceD, MsSuspending, StiSuspendingSequenceDLoop >, smacc2::SmaccState< StartSequenceALoop, MsStarting >, smacc2::SmaccState< StartSequenceBLoop, MsStarting >, smacc2::SmaccState< StartStObserve, MsStarting >, smacc2::SmaccState< SuspendingSequenceALoop, MsSuspending >, smacc2::SmaccState< SuspendingSequenceB, MsSuspending >, smacc2::SmaccState< SuspendingSequenceCLoop, MsSuspending >, smacc2::SmaccState< SuspendingSequenceDLoop, MsSuspending >, smacc2::SmaccState< SuspendingStObserve, MsSuspending >, smacc2::SmaccState< StiCompletingSequenceALoop, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep1, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep2, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep3, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep4, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep5, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep6, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep7, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep8, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep9, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceBLoop, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep1, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep2, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep3, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep4, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep5, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep6, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep7, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep8, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep9, SsCompletingSequenceB >, smacc2::SmaccState< StiExecuteSequenceALoop, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep1, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep2, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep3, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep4, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep5, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep6, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep7, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep8, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep9, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceBLoop, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep1, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep2, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep3, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep4, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep5, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep6, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep7, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep8, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep9, SsExecuteSequenceB >, smacc2::SmaccState< StiHoldingSequenceALoop, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep1, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep2, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep3, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep4, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep5, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep6, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep7, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep8, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep9, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceBLoop, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep1, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep2, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep3, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep4, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep5, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep6, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep7, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep8, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep9, SsHoldingSequenceB >, smacc2::SmaccState< StiStartSequenceALoop, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep1, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep2, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep3, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep4, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep5, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep6, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep7, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep8, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep9, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceBLoop, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep1, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep2, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep3, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep4, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep5, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep6, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep7, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep8, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep9, SsStartSequenceB >, smacc2::SmaccState< StiSuspendingSequenceALoop, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep1, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep2, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep3, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep4, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep5, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep6, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep7, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep8, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep9, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceB, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep1, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep2, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep3, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep4, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep5, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep6, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep7, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep8, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep9, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceCLoop, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep1, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep2, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep3, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep4, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep5, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep6, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep7, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep8, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep9, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceDLoop, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep1, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep2, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep3, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep4, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep5, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep6, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep7, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep8, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep9, SsSuspendingSequenceD >, smacc2::SmaccState< MsRecover, SmPubsub1 >, smacc2::SmaccState< MsRun, SmPubsub1, StState1 >, smacc2::SmaccState< MsCalibration, SmRespira1, StCalibrationStep1 >, smacc2::SmaccState< MsLeakyLung, SmRespira1, StLeakyLungStep1 >, smacc2::SmaccState< MsPatientObstruction, SmRespira1, StPatientObstructionStep1 >, smacc2::SmaccState< MsRun, SmRespira1, StObserve >, smacc2::SmaccState< MsShutdown, SmRespira1, StSystemShutdown >, smacc2::SmaccState< SsACCycle, MsRun, StiACCycleLoop >, smacc2::SmaccState< SsCMVCycle, MsRun, StiCMVCycleLoop >, smacc2::SmaccState< SsPCCycle, MsRun, StiPCCycleLoop >, smacc2::SmaccState< SsPSCycle, MsRun, StiPSCycleLoop >, smacc2::SmaccState< StCalibrationStep1, MsCalibration >, smacc2::SmaccState< StLeakyLungStep1, MsLeakyLung >, smacc2::SmaccState< StLeakyLungStep2, MsLeakyLung >, smacc2::SmaccState< StLeakyLungStep3, MsLeakyLung >, smacc2::SmaccState< StPatientObstructionStep1, MsPatientObstruction >, smacc2::SmaccState< StPatientObstructionStep2, MsPatientObstruction >, smacc2::SmaccState< StSystemShutdown, MsShutdown >, smacc2::SmaccState< StiACCycleDwell, SsACCycle >, smacc2::SmaccState< StiACCycleExpire, SsACCycle >, smacc2::SmaccState< StiACCycleInspire, SsACCycle >, smacc2::SmaccState< StiACCycleLoop, SsACCycle >, smacc2::SmaccState< StiACCyclePlateau, SsACCycle >, smacc2::SmaccState< StiCMVCycleDwell, SsCMVCycle >, smacc2::SmaccState< StiCMVCycleExpire, SsCMVCycle >, smacc2::SmaccState< StiCMVCycleInspire, SsCMVCycle >, smacc2::SmaccState< StiCMVCycleLoop, SsCMVCycle >, smacc2::SmaccState< StiCMVCyclePlateau, SsCMVCycle >, smacc2::SmaccState< StiPCCycleDwell, SsPCCycle >, smacc2::SmaccState< StiPCCycleExpire, SsPCCycle >, smacc2::SmaccState< StiPCCycleInspire, SsPCCycle >, smacc2::SmaccState< StiPCCycleLoop, SsPCCycle >, smacc2::SmaccState< StiPCCyclePlateau, SsPCCycle >, smacc2::SmaccState< StiPSCycleDwell, SsPSCycle >, smacc2::SmaccState< StiPSCycleExpire, SsPSCycle >, smacc2::SmaccState< StiPSCycleInspire, SsPSCycle >, smacc2::SmaccState< StiPSCycleLoop, SsPSCycle >, smacc2::SmaccState< StiPSCyclePlateau, SsPSCycle >, smacc2::SmaccState< MsRecover, SmThreeSome >, and smacc2::SmaccState< MsRun, SmThreeSome, StState1 >.
Referenced by cl_nav2z::CbAbsoluteRotate::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbNavigateGlobalPosition::onEntry(), cl_nav2z::CbRotate::onEntry(), and cl_nav2z::WaypointNavigator::sendNextGoal().
getNode()
rclcpp::Node::SharedPtr & smacc2::ISmaccState::getNode () inline
Definition at line 34 of file smacc_state.hpp.
{ return node_; }
References node_.
Referenced by smacc2::StateReactor::getNode(), $sm_name$::State1::onEntry(), sm_aws_warehouse_navigation::StAcquireSensors::sendInitialPoseEstimation(), and sm_aws_warehouse_navigation::StStartNavigation::sendInitialPoseEstimation().
getOrthogonal()
template<typename TOrthogonal > TOrthogonal * smacc2::ISmaccState::getOrthogonal
Definition at line 171 of file smacc_state_impl.hpp.
{
  return this->getStateMachine().getOrthogonal<TOrthogonal>();
}
References smacc2::ISmaccStateMachine::getOrthogonal(), and getStateMachine().
getParentState()
ISmaccState * smacc2::ISmaccState::getParentState () inline
Definition at line 32 of file smacc_state.hpp.
{ return parentState_; }
References parentState_.
Referenced by smacc2::ISmaccStateMachine::propagateEventToStateReactors().
getStateMachine()
virtual ISmaccStateMachine & smacc2::ISmaccState::getStateMachine () pure virtual
Implemented in smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >, smacc2::SmaccState< State1, $SmName$ >, smacc2::SmaccState< State2, $SmName$ >, smacc2::SmaccState< MsRecover, SmAdvancedRecovery1, StRecoverStep1 >, smacc2::SmaccState< MsRun, SmAdvancedRecovery1, StObserve >, smacc2::SmaccState< SsACycle, MsRun, StiACycleLoop >, smacc2::SmaccState< SsBCycle, MsRun, StiBCycleLoop >, smacc2::SmaccState< SsCCycle, MsRun, StiCCycleLoop >, smacc2::SmaccState< StObserve, MsRun >, smacc2::SmaccState< StRecoverStep1, MsRecover >, smacc2::SmaccState< StRecoverStep2, MsRecover >, smacc2::SmaccState< StRecoverStep3, MsRecover >, smacc2::SmaccState< StRecoverStep4, MsRecover >, smacc2::SmaccState< StRecoverStep5, MsRecover >, smacc2::SmaccState< StRecoverStep6, MsRecover >, smacc2::SmaccState< StRecoverStep7, MsRecover >, smacc2::SmaccState< StiACycleLoop, SsACycle >, smacc2::SmaccState< StiACycleStep1, SsACycle >, smacc2::SmaccState< StiACycleStep2, SsACycle >, smacc2::SmaccState< StiACycleStep3, SsACycle >, smacc2::SmaccState< StiACycleStep4, SsACycle >, smacc2::SmaccState< StiACycleStep5, SsACycle >, smacc2::SmaccState< StiACycleStep6, SsACycle >, smacc2::SmaccState< StiACycleStep7, SsACycle >, smacc2::SmaccState< StiACycleStep8, SsACycle >, smacc2::SmaccState< StiACycleStep9, SsACycle >, smacc2::SmaccState< StiBCycleLoop, SsBCycle >, smacc2::SmaccState< StiBCycleStep1, SsBCycle >, smacc2::SmaccState< StiBCycleStep2, SsBCycle >, smacc2::SmaccState< StiBCycleStep3, SsBCycle >, smacc2::SmaccState< StiBCycleStep4, SsBCycle >, smacc2::SmaccState< StiBCycleStep5, SsBCycle >, smacc2::SmaccState< StiBCycleStep6, SsBCycle >, smacc2::SmaccState< StiBCycleStep7, SsBCycle >, smacc2::SmaccState< StiBCycleStep8, SsBCycle >, smacc2::SmaccState< StiBCycleStep9, SsBCycle >, smacc2::SmaccState< StiCCycleLoop, SsCCycle >, smacc2::SmaccState< StiCCycleStep1, SsCCycle >, smacc2::SmaccState< StiCCycleStep2, SsCCycle >, smacc2::SmaccState< StiCCycleStep3, SsCCycle >, smacc2::SmaccState< StiCCycleStep4, SsCCycle >, smacc2::SmaccState< StiCCycleStep5, SsCCycle >, smacc2::SmaccState< StiCCycleStep6, SsCCycle >, smacc2::SmaccState< StiCCycleStep7, SsCCycle >, smacc2::SmaccState< StiCCycleStep8, SsCCycle >, smacc2::SmaccState< StiCCycleStep9, SsCCycle >, smacc2::SmaccState< State1, SmAtomic >, smacc2::SmaccState< State2, SmAtomic >, smacc2::SmaccState< State1, SmAtomic24Hr >, smacc2::SmaccState< State2, SmAtomic24Hr >, smacc2::SmaccState< State1, SmAtomicHierarchy, StiState1 >, smacc2::SmaccState< State2, SmAtomicHierarchy >, smacc2::SmaccState< StiState1, State1 >, smacc2::SmaccState< State1, SmAtomicPerformanceTrace1 >, smacc2::SmaccState< State2, SmAtomicPerformanceTrace1 >, smacc2::SmaccState< State1, SmAtomicSubscribersPerformanceTest >, smacc2::SmaccState< State2, SmAtomicSubscribersPerformanceTest >, smacc2::SmaccState< StAcquireSensors, SmAutowareAvp >, smacc2::SmaccState< StFirstPause, SmAutowareAvp >, smacc2::SmaccState< StNavigateWaypoint1, SmAutowareAvp >, smacc2::SmaccState< StNavigateWaypoint2, SmAutowareAvp >, smacc2::SmaccState< StSecondPause, SmAutowareAvp >, smacc2::SmaccState< StSetupInitialLocationEstimation, SmAutowareAvp >, smacc2::SmaccState< StAcquireSensors, SmAwsWarehouseNavigation >, smacc2::SmaccState< StCheckPoint1, SmAwsWarehouseNavigation >, smacc2::SmaccState< StInitialNavigateForward, SmAwsWarehouseNavigation >, smacc2::SmaccState< StRotateMainAisle, SmAwsWarehouseNavigation >, smacc2::SmaccState< StStartNavigation, SmAwsWarehouseNavigation >, smacc2::SmaccState< State1, SmBranching >, smacc2::SmaccState< State2, SmBranching >, smacc2::SmaccState< State2b, SmBranching >, smacc2::SmaccState< State2c, SmBranching >, smacc2::SmaccState< State3, SmBranching >, smacc2::SmaccState< State3b, SmBranching >, smacc2::SmaccState< State3c, SmBranching >, smacc2::SmaccState< State4, SmBranching >, smacc2::SmaccState< State4c, SmBranching >, smacc2::SmaccState< State5, SmBranching >, smacc2::SmaccState< State5b, SmBranching >, smacc2::SmaccState< State6, SmBranching >, smacc2::SmaccState< State1, SmCoretestTransitionSpeed1 >, smacc2::SmaccState< State2, SmCoretestTransitionSpeed1 >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBot >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBot, StAcquireSensors >, smacc2::SmaccState< SsRadialPattern1, MsDanceBotRunMode, StiRadialLoopStart >, smacc2::SmaccState< SsRadialPattern2, MsDanceBotRunMode, StiRadialLoopStart >, smacc2::SmaccState< SsRadialPattern3, MsDanceBotRunMode, StiRadialLoopStart >, smacc2::SmaccState< SsFPattern1, MsDanceBotRunMode, StiFPatternStartLoop< SsFPattern1 > >, smacc2::SmaccState< StiFPatternStartLoop< SsFPattern1 >, SsFPattern1 >, smacc2::SmaccState< SsSPattern1, MsDanceBotRunMode, StiSPatternLoopStart >, smacc2::SmaccState< StAcquireSensors, MsDanceBotRunMode >, smacc2::SmaccState< StEventCountDown, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateForward1, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateForward2, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse1, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse2, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse3, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateReverse4, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypoint1, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypointsX, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees1, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees2, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees3, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees4, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees5, MsDanceBotRunMode >, smacc2::SmaccState< StRotateDegrees6, MsDanceBotRunMode >, smacc2::SmaccState< StiFPatternForward1< SS >, SS >, smacc2::SmaccState< StiFPatternForward2< SS >, SS >, smacc2::SmaccState< StiFPatternReturn1< SS >, SS >, smacc2::SmaccState< StiFPatternRotate1< SS >, SS >, smacc2::SmaccState< StiFPatternRotate2< SS >, SS >, smacc2::SmaccState< StiFPatternStartLoop< SS >, SS >, smacc2::SmaccState< StiRadialEndPoint, SS >, smacc2::SmaccState< StiRadialLoopStart, SS >, smacc2::SmaccState< StiRadialReturn, SS >, smacc2::SmaccState< StiRadialRotate, SS >, smacc2::SmaccState< TDerived, TContext >, smacc2::SmaccState< StiSPatternForward1, SS >, smacc2::SmaccState< StiSPatternForward2, SS >, smacc2::SmaccState< StiSPatternForward3, SS >, smacc2::SmaccState< StiSPatternForward4, SS >, smacc2::SmaccState< StiSPatternLoopStart, SS >, smacc2::SmaccState< StiSPatternRotate1, SS >, smacc2::SmaccState< StiSPatternRotate2, SS >, smacc2::SmaccState< StiSPatternRotate3, SS >, smacc2::SmaccState< StiSPatternRotate4, SS >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotStrikesBack >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotStrikesBack, StAcquireSensors >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotWarehouse >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotWarehouse, StAcquireSensors >, smacc2::SmaccState< SsSPattern2, MsDanceBotRunMode, StiSPatternLoopStart >, smacc2::SmaccState< StiFPatternRetryRelativeForward1< SS >, SS >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotWareHouse2 >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotWareHouse2, StAcquireSensors >, smacc2::SmaccState< StForwardAisle, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateNextWaypoint, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateUndoMotion, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateUndoMotion2, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateUndoMotionLeaf, MsDanceBotRunMode >, smacc2::SmaccState< MsDanceBotRecoveryMode, SmDanceBotWareHouse3 >, smacc2::SmaccState< MsDanceBotRunMode, SmDanceBotWareHouse3, StAcquireSensors >, smacc2::SmaccState< StInitialSpinning, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypoint1Recovery, MsDanceBotRunMode >, smacc2::SmaccState< StNavigateToWaypointsX2, MsDanceBotRunMode >, smacc2::SmaccState< StiRadialEndPointRecovery, SS >, smacc2::SmaccState< MsRecover, SmFerrari >, smacc2::SmaccState< MsRun, SmFerrari, StState1 >, smacc2::SmaccState< Ss1, MsRun, StiState1 >, smacc2::SmaccState< Ss2, MsRun, StiState1 >, smacc2::SmaccState< StState1, MsRun >, smacc2::SmaccState< StState2, MsRun >, smacc2::SmaccState< StState3, MsRun >, smacc2::SmaccState< StState4, MsRun >, smacc2::SmaccState< StiState1, SS >, smacc2::SmaccState< StiState2, SS >, smacc2::SmaccState< StiState3, SS >, smacc2::SmaccState< SsSPattern1, SmHuskyBarrelSearch1, StiSPatternLoopStart >, smacc2::SmaccState< SsSearchMineSPattern1, SmHuskyBarrelSearch1, StiSPatternLoopStart >, smacc2::SmaccState< StAcquireSensors, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StCrossMineFieldSlowly, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StDeactivateMine, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StDetectItems, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StEvasionMotion, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StExploreAndRetreat, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StMoveBackwardsBlinking, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StNavigateToWaypointX, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StSatelliteComunications, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StSelfDestruction, SmHuskyBarrelSearch1 >, smacc2::SmaccState< StUndoRetreat, SmHuskyBarrelSearch1 >, smacc2::SmaccState< Mode1SequenceALoop, MsMode1 >, smacc2::SmaccState< Mode1SequenceBLoop, MsMode1 >, smacc2::SmaccState< Mode1StObserve, MsMode1 >, smacc2::SmaccState< Mode2SequenceALoop, MsMode2 >, smacc2::SmaccState< Mode2SequenceBLoop, MsMode2 >, smacc2::SmaccState< Mode2StObserve, MsMode2 >, smacc2::SmaccState< Mode3SequenceALoop, MsMode3 >, smacc2::SmaccState< Mode3SequenceBLoop, MsMode3 >, smacc2::SmaccState< Mode3StObserve, MsMode3 >, smacc2::SmaccState< Mode4SequenceALoop, MsMode4 >, smacc2::SmaccState< Mode4SequenceB, MsMode4 >, smacc2::SmaccState< Mode4SequenceCLoop, MsMode4 >, smacc2::SmaccState< Mode4SequenceDLoop, MsMode4 >, smacc2::SmaccState< Mode4StObserve, MsMode4 >, smacc2::SmaccState< Mode5SequenceALoop, MsMode5 >, smacc2::SmaccState< Mode5SequenceBLoop, MsMode5 >, smacc2::SmaccState< Mode5StObserve, MsMode5 >, smacc2::SmaccState< MsMode1, SmMultiStage1, Mode1StObserve >, smacc2::SmaccState< MsMode2, SmMultiStage1, Mode2StObserve >, smacc2::SmaccState< MsMode3, SmMultiStage1, Mode3StObserve >, smacc2::SmaccState< MsMode4, SmMultiStage1, Mode4StObserve >, smacc2::SmaccState< MsMode5, SmMultiStage1, Mode5StObserve >, smacc2::SmaccState< MsRecovery1, SmMultiStage1, StRecoveryAnalyze1 >, smacc2::SmaccState< MsRecovery2, SmMultiStage1, StRecoveryAnalyze2 >, smacc2::SmaccState< SsMode1SequenceA, MsMode1, StiMode1SequenceALoop >, smacc2::SmaccState< SsMode1SequenceB, MsMode1, StiMode1SequenceBLoop >, smacc2::SmaccState< SsMode2SequenceA, MsMode2, StiMode2SequenceALoop >, smacc2::SmaccState< SsMode2SequenceB, MsMode2, StiMode2SequenceBLoop >, smacc2::SmaccState< SsMode3SequenceA, MsMode3, StiMode3SequenceALoop >, smacc2::SmaccState< SsMode3SequenceB, MsMode3, StiMode3SequenceBLoop >, smacc2::SmaccState< SsMode4SequenceA, MsMode4, StiMode4SequenceALoop >, smacc2::SmaccState< SsMode4SequenceB, MsMode4, StiMode4SequenceB >, smacc2::SmaccState< SsMode4SequenceC, MsMode4, StiMode4SequenceCLoop >, smacc2::SmaccState< SsMode4SequenceD, MsMode4, StiMode4SequenceDLoop >, smacc2::SmaccState< SsMode5SequenceA, MsMode5, StiMode5SequenceALoop >, smacc2::SmaccState< SsMode5SequenceB, MsMode5, StiMode5SequenceBLoop >, smacc2::SmaccState< StRecoveryAnalyze1, MsRecovery1 >, smacc2::SmaccState< StRecoveryAnalyze2, MsRecovery2 >, smacc2::SmaccState< StRecoveryBifurcate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryBifurcate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryCalculate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryCalculate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryDeliberate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryDeliberate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryEvaluate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryEvaluate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryGenerate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryGenerate2, MsRecovery2 >, smacc2::SmaccState< StRecoveryInnervate1, MsRecovery1 >, smacc2::SmaccState< StRecoveryInnervate2, MsRecovery2 >, smacc2::SmaccState< StiMode1SequenceALoop, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep1, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep2, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep3, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep4, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep5, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep6, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep7, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep8, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceAStep9, SsMode1SequenceA >, smacc2::SmaccState< StiMode1SequenceBLoop, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep1, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep2, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep3, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep4, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep5, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep6, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep7, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep8, SsMode1SequenceB >, smacc2::SmaccState< StiMode1SequenceBStep9, SsMode1SequenceB >, smacc2::SmaccState< StiMode2SequenceALoop, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep1, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep2, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep3, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep4, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep5, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep6, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep7, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep8, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceAStep9, SsMode2SequenceA >, smacc2::SmaccState< StiMode2SequenceBLoop, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep1, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep2, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep3, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep4, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep5, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep6, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep7, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep8, SsMode2SequenceB >, smacc2::SmaccState< StiMode2SequenceBStep9, SsMode2SequenceB >, smacc2::SmaccState< StiMode3SequenceALoop, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep1, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep2, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep3, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep4, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep5, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep6, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep7, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep8, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceAStep9, SsMode3SequenceA >, smacc2::SmaccState< StiMode3SequenceBLoop, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep1, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep2, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep3, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep4, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep5, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep6, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep7, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep8, SsMode3SequenceB >, smacc2::SmaccState< StiMode3SequenceBStep9, SsMode3SequenceB >, smacc2::SmaccState< StiMode4SequenceALoop, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep1, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep2, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep3, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep4, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep5, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep6, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep7, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep8, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceAStep9, SsMode4SequenceA >, smacc2::SmaccState< StiMode4SequenceB, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep1, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep2, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep3, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep4, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep5, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep6, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep7, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep8, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceBStep9, SsMode4SequenceB >, smacc2::SmaccState< StiMode4SequenceCLoop, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep1, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep2, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep3, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep4, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep5, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep6, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep7, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep8, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceCStep9, SsMode4SequenceC >, smacc2::SmaccState< StiMode4SequenceDLoop, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep1, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep2, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep3, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep4, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep5, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep6, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep7, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep8, SsMode4SequenceD >, smacc2::SmaccState< StiMode4SequenceDStep9, SsMode4SequenceD >, smacc2::SmaccState< StiMode5SequenceALoop, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep1, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep2, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep3, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep4, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep5, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep6, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep7, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep8, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceAStep9, SsMode5SequenceA >, smacc2::SmaccState< StiMode5SequenceBLoop, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep1, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep2, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep3, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep4, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep5, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep6, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep7, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep8, SsMode5SequenceB >, smacc2::SmaccState< StiMode5SequenceBStep9, SsMode5SequenceB >, smacc2::SmaccState< StAcquireSensors, SmTestMoveitUr5Sim >, smacc2::SmaccState< StAttachObject, SmTestMoveitUr5Sim >, smacc2::SmaccState< StCircularPivotMotion, SmTestMoveitUr5Sim >, smacc2::SmaccState< StDetatchObject, SmTestMoveitUr5Sim >, smacc2::SmaccState< StEndEffectorRotate, SmTestMoveitUr5Sim >, smacc2::SmaccState< StExecuteLastTrajectory, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveCartesianRelative, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveCartesianRelative2, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveEndEffector, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveJoints, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveKnownState, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveLastTrajectoryInitialState, SmTestMoveitUr5Sim >, smacc2::SmaccState< StMoveNamedTarget, SmTestMoveitUr5Sim >, smacc2::SmaccState< StPouringMotion, SmTestMoveitUr5Sim >, smacc2::SmaccState< StUndoLastTrajectory, SmTestMoveitUr5Sim >, smacc2::SmaccState< CompletingSequenceALoop, MsCompleting >, smacc2::SmaccState< CompletingSequenceBLoop, MsCompleting >, smacc2::SmaccState< CompletingStObserve, MsCompleting >, smacc2::SmaccState< DsClearing, JsActive >, smacc2::SmaccState< DsRun, JsActive, MsIdle >, smacc2::SmaccState< DsStopped, JsActive >, smacc2::SmaccState< DsStopping, JsActive >, smacc2::SmaccState< ExecuteSequenceALoop, MsExecute >, smacc2::SmaccState< ExecuteSequenceBLoop, MsExecute >, smacc2::SmaccState< ExecuteStObserve, MsExecute >, smacc2::SmaccState< HoldingSequenceALoop, MsHolding >, smacc2::SmaccState< HoldingSequenceBLoop, MsHolding >, smacc2::SmaccState< HoldingStObserve, MsHolding >, smacc2::SmaccState< JsAborted, SmPackMl1 >, smacc2::SmaccState< JsAborting, SmPackMl1 >, smacc2::SmaccState< JsActive, SmPackMl1, DsRun >, smacc2::SmaccState< MsComplete, DsRun >, smacc2::SmaccState< MsCompleting, DsRun, CompletingStObserve >, smacc2::SmaccState< MsExecute, DsRun, ExecuteStObserve >, smacc2::SmaccState< MsHeld, DsRun >, smacc2::SmaccState< MsHolding, DsRun, HoldingStObserve >, smacc2::SmaccState< MsIdle, DsRun >, smacc2::SmaccState< MsResetting, DsRun >, smacc2::SmaccState< MsStarting, DsRun, StartStObserve >, smacc2::SmaccState< MsSuspended, DsRun >, smacc2::SmaccState< MsSuspending, DsRun, SuspendingStObserve >, smacc2::SmaccState< MsUnholding, DsRun >, smacc2::SmaccState< MsUnsuspending, DsRun >, smacc2::SmaccState< SsCompletingSequenceA, MsCompleting, StiCompletingSequenceALoop >, smacc2::SmaccState< SsCompletingSequenceB, MsCompleting, StiCompletingSequenceBLoop >, smacc2::SmaccState< SsExecuteSequenceA, MsExecute, StiExecuteSequenceALoop >, smacc2::SmaccState< SsExecuteSequenceB, MsExecute, StiExecuteSequenceBLoop >, smacc2::SmaccState< SsHoldingSequenceA, MsHolding, StiHoldingSequenceALoop >, smacc2::SmaccState< SsHoldingSequenceB, MsHolding, StiHoldingSequenceBLoop >, smacc2::SmaccState< SsStartSequenceA, MsStarting, StiStartSequenceALoop >, smacc2::SmaccState< SsStartSequenceB, MsStarting, StiStartSequenceBLoop >, smacc2::SmaccState< SsSuspendingSequenceA, MsSuspending, StiSuspendingSequenceALoop >, smacc2::SmaccState< SsSuspendingSequenceB, MsSuspending, StiSuspendingSequenceB >, smacc2::SmaccState< SsSuspendingSequenceC, MsSuspending, StiSuspendingSequenceCLoop >, smacc2::SmaccState< SsSuspendingSequenceD, MsSuspending, StiSuspendingSequenceDLoop >, smacc2::SmaccState< StartSequenceALoop, MsStarting >, smacc2::SmaccState< StartSequenceBLoop, MsStarting >, smacc2::SmaccState< StartStObserve, MsStarting >, smacc2::SmaccState< SuspendingSequenceALoop, MsSuspending >, smacc2::SmaccState< SuspendingSequenceB, MsSuspending >, smacc2::SmaccState< SuspendingSequenceCLoop, MsSuspending >, smacc2::SmaccState< SuspendingSequenceDLoop, MsSuspending >, smacc2::SmaccState< SuspendingStObserve, MsSuspending >, smacc2::SmaccState< StiCompletingSequenceALoop, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep1, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep2, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep3, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep4, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep5, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep6, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep7, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep8, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceAStep9, SsCompletingSequenceA >, smacc2::SmaccState< StiCompletingSequenceBLoop, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep1, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep2, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep3, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep4, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep5, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep6, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep7, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep8, SsCompletingSequenceB >, smacc2::SmaccState< StiCompletingSequenceBStep9, SsCompletingSequenceB >, smacc2::SmaccState< StiExecuteSequenceALoop, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep1, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep2, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep3, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep4, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep5, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep6, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep7, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep8, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceAStep9, SsExecuteSequenceA >, smacc2::SmaccState< StiExecuteSequenceBLoop, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep1, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep2, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep3, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep4, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep5, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep6, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep7, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep8, SsExecuteSequenceB >, smacc2::SmaccState< StiExecuteSequenceBStep9, SsExecuteSequenceB >, smacc2::SmaccState< StiHoldingSequenceALoop, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep1, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep2, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep3, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep4, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep5, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep6, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep7, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep8, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceAStep9, SsHoldingSequenceA >, smacc2::SmaccState< StiHoldingSequenceBLoop, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep1, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep2, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep3, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep4, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep5, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep6, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep7, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep8, SsHoldingSequenceB >, smacc2::SmaccState< StiHoldingSequenceBStep9, SsHoldingSequenceB >, smacc2::SmaccState< StiStartSequenceALoop, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep1, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep2, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep3, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep4, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep5, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep6, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep7, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep8, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceAStep9, SsStartSequenceA >, smacc2::SmaccState< StiStartSequenceBLoop, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep1, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep2, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep3, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep4, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep5, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep6, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep7, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep8, SsStartSequenceB >, smacc2::SmaccState< StiStartSequenceBStep9, SsStartSequenceB >, smacc2::SmaccState< StiSuspendingSequenceALoop, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep1, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep2, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep3, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep4, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep5, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep6, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep7, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep8, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceAStep9, SsSuspendingSequenceA >, smacc2::SmaccState< StiSuspendingSequenceB, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep1, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep2, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep3, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep4, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep5, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep6, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep7, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep8, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceBStep9, SsSuspendingSequenceB >, smacc2::SmaccState< StiSuspendingSequenceCLoop, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep1, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep2, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep3, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep4, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep5, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep6, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep7, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep8, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceCStep9, SsSuspendingSequenceC >, smacc2::SmaccState< StiSuspendingSequenceDLoop, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep1, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep2, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep3, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep4, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep5, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep6, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep7, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep8, SsSuspendingSequenceD >, smacc2::SmaccState< StiSuspendingSequenceDStep9, SsSuspendingSequenceD >, smacc2::SmaccState< MsRecover, SmPubsub1 >, smacc2::SmaccState< MsRun, SmPubsub1, StState1 >, smacc2::SmaccState< MsCalibration, SmRespira1, StCalibrationStep1 >, smacc2::SmaccState< MsLeakyLung, SmRespira1, StLeakyLungStep1 >, smacc2::SmaccState< MsPatientObstruction, SmRespira1, StPatientObstructionStep1 >, smacc2::SmaccState< MsRun, SmRespira1, StObserve >, smacc2::SmaccState< MsShutdown, SmRespira1, StSystemShutdown >, smacc2::SmaccState< SsACCycle, MsRun, StiACCycleLoop >, smacc2::SmaccState< SsCMVCycle, MsRun, StiCMVCycleLoop >, smacc2::SmaccState< SsPCCycle, MsRun, StiPCCycleLoop >, smacc2::SmaccState< SsPSCycle, MsRun, StiPSCycleLoop >, smacc2::SmaccState< StCalibrationStep1, MsCalibration >, smacc2::SmaccState< StLeakyLungStep1, MsLeakyLung >, smacc2::SmaccState< StLeakyLungStep2, MsLeakyLung >, smacc2::SmaccState< StLeakyLungStep3, MsLeakyLung >, smacc2::SmaccState< StPatientObstructionStep1, MsPatientObstruction >, smacc2::SmaccState< StPatientObstructionStep2, MsPatientObstruction >, smacc2::SmaccState< StSystemShutdown, MsShutdown >, smacc2::SmaccState< StiACCycleDwell, SsACCycle >, smacc2::SmaccState< StiACCycleExpire, SsACCycle >, smacc2::SmaccState< StiACCycleInspire, SsACCycle >, smacc2::SmaccState< StiACCycleLoop, SsACCycle >, smacc2::SmaccState< StiACCyclePlateau, SsACCycle >, smacc2::SmaccState< StiCMVCycleDwell, SsCMVCycle >, smacc2::SmaccState< StiCMVCycleExpire, SsCMVCycle >, smacc2::SmaccState< StiCMVCycleInspire, SsCMVCycle >, smacc2::SmaccState< StiCMVCycleLoop, SsCMVCycle >, smacc2::SmaccState< StiCMVCyclePlateau, SsCMVCycle >, smacc2::SmaccState< StiPCCycleDwell, SsPCCycle >, smacc2::SmaccState< StiPCCycleExpire, SsPCCycle >, smacc2::SmaccState< StiPCCycleInspire, SsPCCycle >, smacc2::SmaccState< StiPCCycleLoop, SsPCCycle >, smacc2::SmaccState< StiPCCyclePlateau, SsPCCycle >, smacc2::SmaccState< StiPSCycleDwell, SsPSCycle >, smacc2::SmaccState< StiPSCycleExpire, SsPSCycle >, smacc2::SmaccState< StiPSCycleInspire, SsPSCycle >, smacc2::SmaccState< StiPSCycleLoop, SsPSCycle >, smacc2::SmaccState< StiPSCyclePlateau, SsPSCycle >, smacc2::SmaccState< MsRecover, SmThreeSome >, and smacc2::SmaccState< MsRun, SmThreeSome, StState1 >.
Referenced by getGlobalSMData(), getOrthogonal(), notifyTransitionFromTransitionTypeInfo(), postEvent(), requiresClient(), requiresComponent(), setGlobalSMData(), and smacc2::StateReactor::setOutputEvent().
getStateReactor()
template<typename TStateReactor > TStateReactor * smacc2::ISmaccState::getStateReactor
Definition at line 189 of file smacc_state_impl.hpp.
{
  TStateReactor * ret = nullptr;
  for (auto & sr : this->eventGenerators_)
  {
    ret = dynamic_cast<TStateReactor *>(sr.get());
    if (ret != nullptr) break;
  }
  return ret;
}
References eventGenerators_.
getStateReactors()
std::vector< std::shared_ptr< StateReactor > > & smacc2::ISmaccState::getStateReactors () inline
Definition at line 80 of file smacc_state.hpp.
{ return stateReactors_; }
References stateReactors_.
Referenced by smacc2::SignalDetector::findUpdatableStateElements(), smacc2::ISmaccStateMachine::notifyOnStateEntryEnd(), and smacc2::ISmaccStateMachine::propagateEventToStateReactors().
notifyTransition()
template<typename TransitionType > void smacc2::ISmaccState::notifyTransition
Definition at line 226 of file smacc_state_impl.hpp.
{
  auto transitionType = TypeInfo::getTypeInfoFromType<TransitionType>();
  this->notifyTransitionFromTransitionTypeInfo(transitionType);
}
References notifyTransitionFromTransitionTypeInfo().
notifyTransitionFromTransitionTypeInfo()
void smacc2::ISmaccState::notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc2::introspection::TypeInfo > & transitionTypeInfo)
Definition at line 28 of file smacc_state.cpp.
{
  RCLCPP_INFO_STREAM(getLogger(), "TRANSITION RULE TRIGGERED: " << transitionType->getFullName());
  //auto currstateinfo = this->getStateMachine().getCurrentStateInfo();
  auto currstateinfo = this->stateInfo_;
  if (currstateinfo != nullptr)
  {
    //RCLCPP_ERROR_STREAM(getLogger(),"CURRENT STATE INFO: " << currstateinfo->fullStateName);
    for (auto & transition : currstateinfo->transitions_)
    {
      std::string transitionCandidateName = transition.transitionTypeInfo->getFullName();
      //RCLCPP_ERROR_STREAM(getLogger(),"candidate transition: " << transitionCandidateName);
      if (transitionType->getFullName() == transitionCandidateName)
      {
        this->getStateMachine().publishTransition(transition);
        return;
      }
    }
    // debug information if not found
    RCLCPP_ERROR_STREAM(
      getLogger(),
      "Transition happened, from current state "
        << currstateinfo->getDemangledFullName()
        << " but there is not any transitioninfo match available to publish transition: "
        << transitionType->getFullName());
    std::stringstream ss;
    auto stateinfo = currstateinfo;
    for (auto & transition : currstateinfo->transitions_)
    {
      std::string transitionCandidateName = transition.transitionTypeInfo->getFullName();
      RCLCPP_ERROR_STREAM(getLogger(), "- candidate transition: " << transitionCandidateName);
    }
    RCLCPP_ERROR(getLogger(), "Ancestors candidates: ");
    std::list<const SmaccStateInfo *> ancestors;
    stateinfo->getAncestors(ancestors);
    for (auto & ancestor : ancestors)
    {
      RCLCPP_ERROR_STREAM(getLogger(), " * Ancestor " << ancestor->getDemangledFullName() << ":");
      for (auto & transition : ancestor->transitions_)
      {
        std::string transitionCandidateName = transition.transitionTypeInfo->getFullName();
        RCLCPP_ERROR_STREAM(getLogger(), "- candidate transition: " << transitionCandidateName);
        if (transitionType->getFullName() == transitionCandidateName)
        {
          RCLCPP_ERROR(getLogger(), "GOTCHA");
        }
      }
    }
  }
  else
  {
    RCLCPP_ERROR_STREAM(
      getLogger(), "Transition happened, but current state was not set. Transition candidates:");
  }
}
References getLogger(), getStateMachine(), smacc2::ISmaccStateMachine::publishTransition(), and stateInfo_.
Referenced by notifyTransition().
postEvent() [1/2]
template<typename EventType > void smacc2::ISmaccState::postEvent
Definition at line 219 of file smacc_state_impl.hpp.
{
  getStateMachine().postEvent<EventType>();
}
References getStateMachine(), and smacc2::ISmaccStateMachine::postEvent().
postEvent() [2/2]
template<typename EventType > void smacc2::ISmaccState::postEvent (const EventType & ev)
Definition at line 213 of file smacc_state_impl.hpp.
{
  getStateMachine().postEvent(ev);
}
References getStateMachine(), and smacc2::ISmaccStateMachine::postEvent().
Referenced by smacc2::SmaccEventGenerator::postEvent(), and smacc2::StateReactor::postEvent().
requiresClient()
template<typename SmaccClientType > void smacc2::ISmaccState::requiresClient (SmaccClientType *& storage)
Definition at line 71 of file smacc_state_impl.hpp.
{
  const char * sname = (demangleSymbol(typeid(*this).name()).c_str());
  storage = nullptr;
  auto & orthogonals = this->getStateMachine().getOrthogonals();
  for (auto & ortho : orthogonals)
  {
    ortho.second->requiresClient(storage);
    if (storage != nullptr) return;
  }
  RCLCPP_ERROR(
    getLogger(),
    "[%s] Client of type '%s' not found in any orthogonal of the current state machine. This may "
    "produce a segmentation fault if the returned reference is used.",
    sname, demangleSymbol<SmaccClientType>().c_str());
}
References smacc2::introspection::demangleSymbol(), getLogger(), smacc2::ISmaccStateMachine::getOrthogonals(), and getStateMachine().
Referenced by sm_dance_bot_warehouse::s_pattern_states::StiSPatternLoopStart::loopCondition(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternLoopStart::loopCondition(), sm_dance_bot::radial_motion_states::StiRadialReturn::onExit(), sm_dance_bot_strikes_back::radial_motion_states::StiRadialReturn::onExit(), sm_dance_bot_warehouse::radial_motion_states::StiRadialReturn::onExit(), sm_dance_bot_warehouse_2::radial_motion_states::StiRadialReturn::onExit(), sm_dance_bot_warehouse_3::radial_motion_states::StiRadialReturn::onExit(), sm_dance_bot::StNavigateForward1::runtimeConfigure(), sm_dance_bot_strikes_back::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_strikes_back::radial_motion_states::StiRadialEndPoint::runtimeConfigure(), sm_dance_bot_strikes_back::s_pattern_states::StiSPatternForward2::runtimeConfigure(), sm_dance_bot_strikes_back::s_pattern_states::StiSPatternForward4::runtimeConfigure(), sm_dance_bot_strikes_back::StNavigateForward1::runtimeConfigure(), sm_dance_bot_warehouse::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_warehouse::radial_motion_states::StiRadialEndPoint::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternForward1::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternForward2::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternForward3::runtimeConfigure(), sm_dance_bot_warehouse::s_pattern_states::StiSPatternForward4::runtimeConfigure(), sm_dance_bot_warehouse::StNavigateForward1::runtimeConfigure(), sm_dance_bot_warehouse_2::f_pattern_states::StiFPatternForward1< SS >::runtimeConfigure(), sm_dance_bot_warehouse_2::radial_motion_states::StiRadialEndPoint::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternForward1::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternForward2::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternForward3::runtimeConfigure(), sm_dance_bot_warehouse_2::s_pattern_states::StiSPatternForward4::runtimeConfigure(), sm_dance_bot_warehouse_3::radial_motion_states::StiRadialEndPoint::runtimeConfigure(), sm_multi_ur5_sim::StAttachObject::runtimeConfigure(), sm_multi_ur5_sim::StMoveJoints::runtimeConfigure(), sm_test_moveit_ur5_sim::StAttachObject::runtimeConfigure(), and sm_test_moveit_ur5_sim::StMoveJoints::runtimeConfigure().
requiresComponent()
template<typename SmaccComponentType > void smacc2::ISmaccState::requiresComponent (SmaccComponentType *& storage)
Definition at line 64 of file smacc_state_impl.hpp.
{
  this->getStateMachine().requiresComponent(storage);
}
References getStateMachine(), and smacc2::ISmaccStateMachine::requiresComponent().
setGlobalSMData()
template<typename T > void smacc2::ISmaccState::setGlobalSMData (std::string name, T value)
Definition at line 99 of file smacc_state_impl.hpp.
{
  this->getStateMachine().setGlobalSMData(name, value);
}
References getStateMachine(), and smacc2::ISmaccStateMachine::setGlobalSMData().
Member Data Documentation
eventGenerators_
std::vector<std::shared_ptr<smacc2::SmaccEventGenerator> > smacc2::ISmaccState::eventGenerators_ protected
Definition at line 100 of file smacc_state.hpp.
Referenced by createEventGenerator(), getEventGenerator(), getEventGenerators(), and getStateReactor().
logger_
std::shared_ptr<rclcpp::Logger> smacc2::ISmaccState::logger_ protected
Definition at line 98 of file smacc_state.hpp.
Referenced by getLogger(), and smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().
node_
rclcpp::Node::SharedPtr smacc2::ISmaccState::node_ protected
Definition at line 97 of file smacc_state.hpp.
Referenced by getNode(), and smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().
parentState_
ISmaccState* smacc2::ISmaccState::parentState_ protected
Definition at line 102 of file smacc_state.hpp.
Referenced by getParentState(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::getParentState(), and smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().
stateInfo_
const smacc2::introspection::SmaccStateInfo* smacc2::ISmaccState::stateInfo_ protected
Definition at line 104 of file smacc_state.hpp.
Referenced by notifyTransitionFromTransitionTypeInfo(), and smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >::SmaccState().
stateReactors_
std::vector<std::shared_ptr<StateReactor> > smacc2::ISmaccState::stateReactors_ protected
Definition at line 99 of file smacc_state.hpp.
Referenced by createStateReactor(), and getStateReactors().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/smacc_state.hpp
smacc2/include/smacc2/impl/smacc_state_impl.hpp
smacc2/src/smacc2/smacc_state.cpp