SMACC2: cl_move_group_interface::CbAttachObject Class Reference
cl_move_group_interface::CbAttachObject Class Reference
#include <cb_attach_object.hpp>
Public Member Functions
CbAttachObject (std::string targetObjectName)
CbAttachObject ()
virtual void onEntry () override
virtual void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Attributes
std::string targetObjectName_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 28 of file cb_attach_object.hpp.
Constructor & Destructor Documentation
CbAttachObject() [1/2]
cl_move_group_interface::CbAttachObject::CbAttachObject (std::string targetObjectName)
Definition at line 26 of file cb_attach_object.cpp.
                                                         : targetObjectName_(targetObjectName)
{
}
CbAttachObject() [2/2]
cl_move_group_interface::CbAttachObject::CbAttachObject ()
Definition at line 30 of file cb_attach_object.cpp.
{}
Member Function Documentation
onEntry()
void cl_move_group_interface::CbAttachObject::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 32 of file cb_attach_object.cpp.
{
  cl_move_group_interface::ClMoveGroup * moveGroup;
  this->requiresClient(moveGroup);
  cl_move_group_interface::CpGraspingComponent * graspingComponent;
  this->requiresComponent(graspingComponent);
  // auto cubepos = cubeinfo->pose_->toPoseStampedMsg();
  moveit_msgs::msg::CollisionObject targetCollisionObject;
  bool found = graspingComponent->getGraspingObject(targetObjectName_, targetCollisionObject);
  if (found)
  {
    targetCollisionObject.operation = moveit_msgs::msg::CollisionObject::ADD;
    targetCollisionObject.header.stamp = getNode()->now();
    moveGroup->planningSceneInterface->applyCollisionObject(targetCollisionObject);
    // collisionObjects.push_back(cubeCollision);
    graspingComponent->currentAttachedObjectName = targetObjectName_;
    moveGroup->moveGroupClientInterface->attachObject(
      targetObjectName_, graspingComponent->gripperLink_, graspingComponent->fingerTipNames);
    RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << "] Grasping objectfound. attach request.");
    this->postSuccessEvent();
  }
  else
  {
    RCLCPP_WARN_STREAM(
      getLogger(), "[" << getName() << "] Grasping object was not found. Ignoring attach request.");
    this->postFailureEvent();
  }
}
References cl_move_group_interface::CpGraspingComponent::currentAttachedObjectName, cl_move_group_interface::CpGraspingComponent::fingerTipNames, cl_move_group_interface::CpGraspingComponent::getGraspingObject(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), smacc2::ISmaccClientBehavior::getNode(), cl_move_group_interface::CpGraspingComponent::gripperLink_, cl_move_group_interface::ClMoveGroup::moveGroupClientInterface, cl_move_group_interface::ClMoveGroup::planningSceneInterface, smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), smacc2::ISmaccClientBehavior::requiresClient(), smacc2::ISmaccClientBehavior::requiresComponent(), and targetObjectName_.
onExit()
void cl_move_group_interface::CbAttachObject::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 71 of file cb_attach_object.cpp.
{}
Member Data Documentation
targetObjectName_
std::string cl_move_group_interface::CbAttachObject::targetObjectName_
Definition at line 39 of file cb_attach_object.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_attach_object.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_attach_object.cpp