SMACC2: cl_move_base_z::CbNavigateGlobalPosition Class Reference
cl_move_base_z::CbNavigateGlobalPosition Class Reference
#include <cb_navigate_global_position.hpp>
Public Member Functions
CbNavigateGlobalPosition ()
CbNavigateGlobalPosition (float x, float y, float yaw)
void setGoal (const geometry_msgs::msg::Pose &pose)
virtual void onEntry () override
void onExit () override
void execute ()
Public Member Functions inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
virtual ~CbMoveBaseClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Public Attributes
std::optional< geometry_msgs::msg::Point > goalPosition
std::optional< float > goalYaw
std::optional< float > yawTolerance
std::optional< float > yawToleranceX
std::optional< float > yawToleranceY
std::optional< std::string > goalChecker_
Private Member Functions
void readStartPoseFromParameterServer (ClMoveBaseZ::Goal &goal)
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void executeOnEntry () override
void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Protected Attributes inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
cl_move_base_z::ClMoveBaseZ * moveBaseClient_
Detailed Description
Definition at line 30 of file cb_navigate_global_position.hpp.
Constructor & Destructor Documentation
CbNavigateGlobalPosition() [1/2]
cl_move_base_z::CbNavigateGlobalPosition::CbNavigateGlobalPosition ()
Definition at line 32 of file cb_navigate_global_position.cpp.
{}
CbNavigateGlobalPosition() [2/2]
cl_move_base_z::CbNavigateGlobalPosition::CbNavigateGlobalPosition (float x, float y, float yaw)
Definition at line 34 of file cb_navigate_global_position.cpp.
{
  auto p = geometry_msgs::msg::Point();
  p.x = x;
  p.y = y;
  goalPosition = p;
  goalYaw = yaw;
}
References goalPosition, and goalYaw.
Member Function Documentation
execute()
void cl_move_base_z::CbNavigateGlobalPosition::execute ()
Definition at line 71 of file cb_navigate_global_position.cpp.
{
  auto p = moveBaseClient_->getComponent<cl_move_base_z::Pose>();
  auto referenceFrame = p->getReferenceFrame();
  // auto currentPoseMsg = p->toPoseMsg();
  RCLCPP_INFO(getLogger(), "Sending Goal to MoveBase");
  ClMoveBaseZ::Goal goal;
  goal.pose.header.frame_id = referenceFrame;
  goal.pose.header.stamp = getNode()->now();
  readStartPoseFromParameterServer(goal);
  // store the start pose on the state machine storage so that it can
  // be referenced from other states (for example return to radial start)
  this->getStateMachine()->setGlobalSMData("radial_start_pose", goal.pose);
  moveBaseClient_->sendGoal(goal);
}
References smacc2::ISmaccClient::getComponent(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), cl_move_base_z::Pose::getReferenceFrame(), smacc2::ISmaccClientBehavior::getStateMachine(), cl_move_base_z::CbMoveBaseClientBehaviorBase::moveBaseClient_, readStartPoseFromParameterServer(), smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), and smacc2::ISmaccStateMachine::setGlobalSMData().
Referenced by onEntry().
onEntry()
void cl_move_base_z::CbNavigateGlobalPosition::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 49 of file cb_navigate_global_position.cpp.
{
  RCLCPP_INFO(getLogger(), "Entering Navigate Global position");
  RCLCPP_INFO(getLogger(), "Component requirements completed");
  auto pose = moveBaseClient_->getComponent<cl_move_base_z::Pose>()->toPoseMsg();
  auto * odomTracker = moveBaseClient_->getComponent<OdomTracker>();
  auto plannerSwitcher = moveBaseClient_->getComponent<PlannerSwitcher>();
  plannerSwitcher->setDefaultPlanners();
  auto goalCheckerSwitcher = moveBaseClient_->getComponent<GoalCheckerSwitcher>();
  goalCheckerSwitcher->setGoalCheckerId("goal_checker");
  odomTracker->pushPath();
  odomTracker->setStartPoint(pose);
  odomTracker->setWorkingMode(WorkingMode::RECORD_PATH);
  execute();
}
References execute(), smacc2::ISmaccClient::getComponent(), smacc2::ISmaccClientBehavior::getLogger(), cl_move_base_z::CbMoveBaseClientBehaviorBase::moveBaseClient_, cl_move_base_z::PlannerSwitcher::setDefaultPlanners(), and cl_move_base_z::GoalCheckerSwitcher::setGoalCheckerId().
onExit()
void cl_move_base_z::CbNavigateGlobalPosition::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 116 of file cb_navigate_global_position.cpp.
{
  RCLCPP_INFO(getLogger(), "Exiting move goal Action Client");
}
References smacc2::ISmaccClientBehavior::getLogger().
readStartPoseFromParameterServer()
void cl_move_base_z::CbNavigateGlobalPosition::readStartPoseFromParameterServer (ClMoveBaseZ::Goal & goal) private
Definition at line 90 of file cb_navigate_global_position.cpp.
{
  if (!goalPosition)
  {
    this->getCurrentState()->getParam("start_position_x", goal.pose.pose.position.x);
    this->getCurrentState()->getParam("start_position_y", goal.pose.pose.position.y);
    double yaw;
    this->getCurrentState()->getParam("start_position_yaw", yaw);
    tf2::Quaternion q;
    q.setRPY(0, 0, yaw);
    goal.pose.pose.orientation = tf2::toMsg(q);
  }
  else
  {
    goal.pose.pose.position = *goalPosition;
    tf2::Quaternion q;
    q.setRPY(0, 0, *goalYaw);
    goal.pose.pose.orientation = tf2::toMsg(q);
  }
  RCLCPP_INFO_STREAM(
    getLogger(), "start position read from parameter server: " << goal.pose.pose.position);
}
References smacc2::ISmaccClientBehavior::getCurrentState(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccState::getParam(), goalPosition, and goalYaw.
Referenced by execute().
setGoal()
void cl_move_base_z::CbNavigateGlobalPosition::setGoal (const geometry_msgs::msg::Pose & pose)
Definition at line 43 of file cb_navigate_global_position.cpp.
{
  goalPosition = pose.position;
  goalYaw = tf2::getYaw(pose.orientation);
}
References goalPosition, and goalYaw.
Member Data Documentation
goalChecker_
std::optional<std::string> cl_move_base_z::CbNavigateGlobalPosition::goalChecker_
Definition at line 39 of file cb_navigate_global_position.hpp.
goalPosition
std::optional<geometry_msgs::msg::Point> cl_move_base_z::CbNavigateGlobalPosition::goalPosition
Definition at line 33 of file cb_navigate_global_position.hpp.
Referenced by CbNavigateGlobalPosition(), readStartPoseFromParameterServer(), and setGoal().
goalYaw
std::optional<float> cl_move_base_z::CbNavigateGlobalPosition::goalYaw
Definition at line 34 of file cb_navigate_global_position.hpp.
Referenced by CbNavigateGlobalPosition(), readStartPoseFromParameterServer(), and setGoal().
yawTolerance
std::optional<float> cl_move_base_z::CbNavigateGlobalPosition::yawTolerance
Definition at line 35 of file cb_navigate_global_position.hpp.
yawToleranceX
std::optional<float> cl_move_base_z::CbNavigateGlobalPosition::yawToleranceX
Definition at line 36 of file cb_navigate_global_position.hpp.
yawToleranceY
std::optional<float> cl_move_base_z::CbNavigateGlobalPosition::yawToleranceY
Definition at line 37 of file cb_navigate_global_position.hpp.
The documentation for this class was generated from the following files:
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_navigate_global_position.hpp
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/client_behaviors/cb_navigate_global_position.cpp