SMACC2: cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType > Class Template Reference
cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType > Class Template Reference
#include <cb_default_multirole_sensor_behavior.hpp>
Public Types
typedef ClientType::TMessageType TMessageType
Public Member Functions
CbDefaultMultiRoleSensorBehavior ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename EvType >
void propagateEvent (const TMessageType &)
template<typename EvType >
void propagateEvent2 ()
void onEntry () override
void onExit ()
virtual void onMessageCallback (const TMessageType &)
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Static Public Member Functions
static std::string getEventLabel ()
Public Attributes
ClientType * sensor_
std::function< void()> deferedEventPropagation
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
template<typename ClientType>
class cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >
Definition at line 26 of file cb_default_multirole_sensor_behavior.hpp.
Member Typedef Documentation
TMessageType
template<typename ClientType > typedef ClientType::TMessageType cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::TMessageType
Definition at line 29 of file cb_default_multirole_sensor_behavior.hpp.
Constructor & Destructor Documentation
CbDefaultMultiRoleSensorBehavior()
template<typename ClientType > cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::CbDefaultMultiRoleSensorBehavior () inline
Definition at line 33 of file cb_default_multirole_sensor_behavior.hpp.
{ sensor_ = nullptr; }
References cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::sensor_.
Member Function Documentation
getEventLabel()
template<typename ClientType > static std::string cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::getEventLabel () inline static
Definition at line 35 of file cb_default_multirole_sensor_behavior.hpp.
  {
    // show ros message type
    return demangleSymbol(typeid(TMessageType).name());
  }
References smacc2::introspection::demangleSymbol().
onEntry()
template<typename ClientType > void cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onEntry () inline override virtual
Reimplemented from smacc2::SmaccClientBehavior.
Definition at line 80 of file cb_default_multirole_sensor_behavior.hpp.
  {
    RCLCPP_INFO(
      getLogger(), "[CbDefaultMultiRoleSensorBehavior] onEntry. Requires client of type '%s'",
      demangleSymbol<ClientType>().c_str());
    if (sensor_ == nullptr)
    {
      this->requiresClient(sensor_);
    }
    if (sensor_ == nullptr)
    {
      RCLCPP_FATAL_STREAM(
        getLogger(),
        "[CbDefaultMultiRoleSensorBehavior]Sensor client behavior needs a client of type: "
          << demangleSymbol<ClientType>() << " but it is not found.");
    }
    else
    {
      deferedEventPropagation();
      RCLCPP_INFO(getLogger(), "[CbDefaultMultiRoleSensorBehavior] onEntry. sensor initialize");
    }
  }
References cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::deferedEventPropagation, smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::requiresClient(), and cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::sensor_.
Referenced by sm_dance_bot::cl_lidar::CbLidarSensor::onEntry(), sm_dance_bot::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry(), sm_dance_bot_strikes_back::cl_lidar::CbLidarSensor::onEntry(), sm_dance_bot_strikes_back::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry(), sm_dance_bot_warehouse::cl_lidar::CbLidarSensor::onEntry(), sm_dance_bot_warehouse::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry(), sm_dance_bot_warehouse_2::cl_lidar::CbLidarSensor::onEntry(), sm_dance_bot_warehouse_2::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry(), sm_dance_bot_warehouse_3::cl_lidar::CbLidarSensor::onEntry(), and sm_dance_bot_warehouse_3::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry().
onExit()
template<typename ClientType > void cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onExit () inline virtual
Reimplemented from smacc2::SmaccClientBehavior.
Definition at line 105 of file cb_default_multirole_sensor_behavior.hpp.
{}
onMessageCallback()
template<typename ClientType > virtual void cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onMessageCallback (const TMessageType &) inline virtual
Definition at line 107 of file cb_default_multirole_sensor_behavior.hpp.
  {
    // empty to fill by sensor customization based on inheritance
  }
onOrthogonalAllocation()
template<typename ClientType > template<typename TOrthogonal , typename TSourceObject > void cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onOrthogonalAllocation () inline
Definition at line 44 of file cb_default_multirole_sensor_behavior.hpp.
  {
    deferedEventPropagation = [this]() {
      RCLCPP_INFO(
        getLogger(), "[CbDefaultMultiRoleSensorBehavior] onEntry. Requires client of type '%s'",
        demangleSymbol<ClientType>().c_str());
      // just propagate the client events from this client behavior source.
      sensor_->onMessageReceived(
        &CbDefaultMultiRoleSensorBehavior<ClientType>::propagateEvent<
          EvTopicMessage<TSourceObject, TOrthogonal>>,
        this);
      sensor_->onFirstMessageReceived(
        &CbDefaultMultiRoleSensorBehavior<ClientType>::propagateEvent<
          EvTopicInitialMessage<TSourceObject, TOrthogonal>>,
        this);
      sensor_->onMessageTimeout(
        &CbDefaultMultiRoleSensorBehavior<ClientType>::propagateEvent2<
          EvTopicMessageTimeout<TSourceObject, TOrthogonal>>,
        this);
    };
  }
References cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::deferedEventPropagation, smacc2::ISmaccClientBehavior::getLogger(), and cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::sensor_.
propagateEvent()
template<typename ClientType > template<typename EvType > void cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::propagateEvent (const TMessageType &) inline
Definition at line 68 of file cb_default_multirole_sensor_behavior.hpp.
  {
    // TODO: copy event concept fields
    this->postEvent<EvType>();
  }
propagateEvent2()
template<typename ClientType > template<typename EvType > void cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::propagateEvent2 () inline
Definition at line 75 of file cb_default_multirole_sensor_behavior.hpp.
  {
    this->postEvent<EvType>();
  }
Member Data Documentation
deferedEventPropagation
template<typename ClientType > std::function<void()> cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::deferedEventPropagation
Definition at line 41 of file cb_default_multirole_sensor_behavior.hpp.
Referenced by cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onEntry(), and cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onOrthogonalAllocation().
sensor_
template<typename ClientType > ClientType* cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::sensor_
Definition at line 31 of file cb_default_multirole_sensor_behavior.hpp.
Referenced by cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::CbDefaultMultiRoleSensorBehavior(), cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onEntry(), and cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onOrthogonalAllocation().
The documentation for this class was generated from the following file:
smacc2_client_library/multirole_sensor_client/include/multirole_sensor_client/client_behaviors/cb_default_multirole_sensor_behavior.hpp