SMACC2: cl_move_base_z::CbNavigateForward Class Reference
cl_move_base_z::CbNavigateForward Class Reference
#include <cb_navigate_forward.hpp>
Public Member Functions
CbNavigateForward (float forwardDistance)
CbNavigateForward ()
virtual ~CbNavigateForward ()
void onEntry () override
void onExit () override
Public Member Functions inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
virtual ~CbMoveBaseClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Public Attributes
std::optional< float > forwardDistance
std::optional< float > forwardSpeed
std::optional< geometry_msgs::msg::Quaternion > forceInitialOrientation
std::optional< std::string > goalChecker_
std::shared_ptr< tf2_ros::Buffer > listener
odom_tracker::OdomTracker * odomTracker_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void executeOnEntry () override
void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Protected Attributes inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
cl_move_base_z::ClMoveBaseZ * moveBaseClient_
Detailed Description
Definition at line 33 of file cb_navigate_forward.hpp.
Constructor & Destructor Documentation
CbNavigateForward() [1/2]
cl_move_base_z::CbNavigateForward::CbNavigateForward (float forwardDistance)
Definition at line 32 of file cb_navigate_forward.cpp.
{
  this->forwardDistance = forwardDistance;
}
References forwardDistance.
CbNavigateForward() [2/2]
cl_move_base_z::CbNavigateForward::CbNavigateForward ()
Definition at line 37 of file cb_navigate_forward.cpp.
{}
~CbNavigateForward()
cl_move_base_z::CbNavigateForward::~CbNavigateForward () virtual
Definition at line 39 of file cb_navigate_forward.cpp.
{}
Member Function Documentation
onEntry()
void cl_move_base_z::CbNavigateForward::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 41 of file cb_navigate_forward.cpp.
{
  // straight motion distance
  double dist = 3.5;
  if (!forwardDistance)
  {
    // second choice parameter server
    if (!this->getCurrentState()->getParam("straight_motion_distance", dist))
    {
      // last choice default value;
    }
  }
  else
  {
    dist = *forwardDistance;
  }
  RCLCPP_INFO_STREAM(getLogger(), "[CbNavigateForward] Straight motion distance: " << dist);
  // get current pose
  auto p = moveBaseClient_->getComponent<cl_move_base_z::Pose>();
  auto referenceFrame = p->getReferenceFrame();
  auto currentPoseMsg = p->toPoseMsg();
  tf2::Transform currentPose;
  tf2::fromMsg(currentPoseMsg, currentPose);
  RCLCPP_INFO_STREAM(getLogger(), "[CbNavigateForward] current pose: " << currentPoseMsg);
  // force global orientation if it is requested
  if (this->forceInitialOrientation)
  {
    currentPoseMsg.orientation = *forceInitialOrientation;
    RCLCPP_WARN_STREAM(
      getLogger(), "[CbNavigateForward] Forcing initial straight motion orientation: "
                     << currentPoseMsg.orientation);
  }
  // compute forward goal pose
  tf2::Transform forwardDeltaTransform;
  forwardDeltaTransform.setIdentity();
  forwardDeltaTransform.setOrigin(tf2::Vector3(dist, 0, 0));
  tf2::Transform targetPose = currentPose * forwardDeltaTransform;
  ClMoveBaseZ::Goal goal;
  goal.pose.header.frame_id = referenceFrame;
  goal.pose.header.stamp = getNode()->now();
  tf2::toMsg(targetPose, goal.pose.pose);
  RCLCPP_INFO_STREAM(getLogger(), "TARGET POSE FORWARD: " << goal.pose.pose);
  geometry_msgs::msg::PoseStamped currentStampedPoseMsg;
  currentStampedPoseMsg.header.frame_id = referenceFrame;
  currentStampedPoseMsg.header.stamp = getNode()->now();
  tf2::toMsg(currentPose, currentStampedPoseMsg.pose);
  odomTracker_ = moveBaseClient_->getComponent<OdomTracker>();
  odomTracker_->pushPath();
  odomTracker_->setStartPoint(currentStampedPoseMsg);
  odomTracker_->setWorkingMode(WorkingMode::RECORD_PATH);
  auto plannerSwitcher = moveBaseClient_->getComponent<PlannerSwitcher>();
  plannerSwitcher->setForwardPlanner();
  auto goalCheckerSwitcher = moveBaseClient_->getComponent<GoalCheckerSwitcher>();
  goalCheckerSwitcher->setGoalCheckerId("forward_goal_checker");
  moveBaseClient_->sendGoal(goal);
}
References forceInitialOrientation, forwardDistance, smacc2::ISmaccClient::getComponent(), smacc2::ISmaccClientBehavior::getCurrentState(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), cl_move_base_z::Pose::getReferenceFrame(), cl_move_base_z::CbMoveBaseClientBehaviorBase::moveBaseClient_, odomTracker_, cl_move_base_z::odom_tracker::OdomTracker::pushPath(), smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), cl_move_base_z::PlannerSwitcher::setForwardPlanner(), cl_move_base_z::GoalCheckerSwitcher::setGoalCheckerId(), cl_move_base_z::odom_tracker::OdomTracker::setStartPoint(), and cl_move_base_z::odom_tracker::OdomTracker::setWorkingMode().
onExit()
void cl_move_base_z::CbNavigateForward::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 113 of file cb_navigate_forward.cpp.
{ this->odomTracker_->setWorkingMode(WorkingMode::IDLE); }
References odomTracker_, and cl_move_base_z::odom_tracker::OdomTracker::setWorkingMode().
Member Data Documentation
forceInitialOrientation
std::optional<geometry_msgs::msg::Quaternion> cl_move_base_z::CbNavigateForward::forceInitialOrientation
Definition at line 45 of file cb_navigate_forward.hpp.
Referenced by onEntry().
forwardDistance
std::optional<float> cl_move_base_z::CbNavigateForward::forwardDistance
Definition at line 36 of file cb_navigate_forward.hpp.
Referenced by CbNavigateForward(), onEntry(), and sm_dance_bot_strikes_back::radial_motion_states::StiRadialEndPoint::runtimeConfigure().
forwardSpeed
std::optional<float> cl_move_base_z::CbNavigateForward::forwardSpeed
Definition at line 39 of file cb_navigate_forward.hpp.
goalChecker_
std::optional<std::string> cl_move_base_z::CbNavigateForward::goalChecker_
Definition at line 47 of file cb_navigate_forward.hpp.
listener
std::shared_ptr<tf2_ros::Buffer> cl_move_base_z::CbNavigateForward::listener
Definition at line 49 of file cb_navigate_forward.hpp.
odomTracker_
odom_tracker::OdomTracker* cl_move_base_z::CbNavigateForward::odomTracker_
Definition at line 51 of file cb_navigate_forward.hpp.
Referenced by onEntry(), and onExit().
The documentation for this class was generated from the following files:
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_navigate_forward.hpp
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/client_behaviors/cb_navigate_forward.cpp