SMACC2: sm_husky_barrel_search_1::cl_led_array::CbBlinking Class Reference
sm_husky_barrel_search_1::cl_led_array::CbBlinking Class Reference
#include <cb_blinking.hpp>
Public Member Functions
CbBlinking (LedColor color)
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Attributes
LedColor color_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 32 of file cb_blinking.hpp.
Constructor & Destructor Documentation
CbBlinking()
sm_husky_barrel_search_1::cl_led_array::CbBlinking::CbBlinking (LedColor color) inline
Definition at line 38 of file cb_blinking.hpp.
  :color_(color)
  {
  }
Member Function Documentation
onEntry()
void sm_husky_barrel_search_1::cl_led_array::CbBlinking::onEntry () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 44 of file cb_blinking.hpp.
  {
    cl_led_array::ClLedArray * ledarray;
    this->requiresClient(ledarray);
    while(!isShutdownRequested())
    {
      ledarray->turnOn(color_);
      rclcpp::sleep_for(1s);
      ledarray->turnOff(color_);
      rclcpp::sleep_for(500ms);
    }
  }
References color_, smacc2::SmaccAsyncClientBehavior::isShutdownRequested(), smacc2::ISmaccClientBehavior::requiresClient(), service_node_3::s, sm_husky_barrel_search_1::cl_led_array::ClLedArray::turnOff(), and sm_husky_barrel_search_1::cl_led_array::ClLedArray::turnOn().
onExit()
void sm_husky_barrel_search_1::cl_led_array::CbBlinking::onExit () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 59 of file cb_blinking.hpp.
  {
  }
Member Data Documentation
color_
LedColor sm_husky_barrel_search_1::cl_led_array::CbBlinking::color_
Definition at line 36 of file cb_blinking.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_husky_barrel_search_1/include/sm_husky_barrel_search_1/clients/led_array/client_behaviors/cb_blinking.hpp