SMACC2: service_node_3.Service3 Class Reference
service_node_3.Service3 Class Reference
Public Member Functions
def __init__ (self)
def set_bool_service (self, req, res)
def __init__ (self)
def set_bool_service (self, req, res)
def __init__ (self)
def set_bool_service (self, req, res)
def __init__ (self)
def set_bool_service (self, req, res)
def __init__ (self)
def set_bool_service (self, req, res)
Public Attributes
s
Detailed Description
Definition at line 27 of file service_node_3.py.
Constructor & Destructor Documentation
__init__() [1/5]
def service_node_3.Service3.__init__ (self)
Definition at line 28 of file service_node_3.py.
        def __init__(self):
            super().__init__("Service3")
            self.s = self.create_service(
                std_srvs.srv.SetBool, "service_node3", self.set_bool_service
            )
References service_node_3.Service3.__init__().
Referenced by service_node_3.Service3.__init__().
__init__() [2/5]
def service_node_3.Service3.__init__ (self)
Definition at line 28 of file service_node_3.py.
        def __init__(self):
            super().__init__("Service3")
            self.s = self.create_service(
                std_srvs.srv.SetBool, "service_node3", self.set_bool_service
            )
References service_node_3.Service3.__init__(), service_node_3.Service3.s, and service_node_3.Service3.set_bool_service().
__init__() [3/5]
def service_node_3.Service3.__init__ (self)
Definition at line 28 of file service_node_3.py.
        def __init__(self):
            super().__init__("Service3")
            self.s = self.create_service(
                std_srvs.srv.SetBool, "service_node3", self.set_bool_service
            )
References service_node_3.Service3.__init__(), service_node_3.Service3.s, and service_node_3.Service3.set_bool_service().
__init__() [4/5]
def service_node_3.Service3.__init__ (self)
Definition at line 28 of file service_node_3.py.
        def __init__(self):
            super().__init__("Service3")
            self.s = self.create_service(
                std_srvs.srv.SetBool, "service_node3", self.set_bool_service
            )
References service_node_3.Service3.__init__(), service_node_3.Service3.s, and service_node_3.Service3.set_bool_service().
__init__() [5/5]
def service_node_3.Service3.__init__ (self)
Definition at line 28 of file service_node_3.py.
        def __init__(self):
            super().__init__("Service3")
            self.s = self.create_service(
                std_srvs.srv.SetBool, "service_node3", self.set_bool_service
            )
References service_node_3.Service3.__init__(), service_node_3.Service3.s, and service_node_3.Service3.set_bool_service().
Member Function Documentation
set_bool_service() [1/5]
def service_node_3.Service3.set_bool_service (self, req, res)
Definition at line 34 of file service_node_3.py.
        def set_bool_service(self, req, res):
            self.get_logger().info("RECEIVING SET BOOL SERVICE REQUEST: value=" + str(req.data))
            res.message = "OK, value set"
            res.success = True
            return res
    rclpy.init(args=None)
Referenced by service_node_3.Service3.__init__().
set_bool_service() [2/5]
def service_node_3.Service3.set_bool_service (self, req, res)
Definition at line 34 of file service_node_3.py.
        def set_bool_service(self, req, res):
            self.get_logger().info("RECEIVING SET BOOL SERVICE REQUEST: value=" + str(req.data))
            res.message = "OK, value set"
            res.success = True
            return res
    rclpy.init(args=None)
Referenced by service_node_3.Service3.__init__().
set_bool_service() [3/5]
def service_node_3.Service3.set_bool_service (self, req, res)
Definition at line 34 of file service_node_3.py.
        def set_bool_service(self, req, res):
            self.get_logger().info("RECEIVING SET BOOL SERVICE REQUEST: value=" + str(req.data))
            res.message = "OK, value set"
            res.success = True
            return res
    rclpy.init(args=None)
Referenced by service_node_3.Service3.__init__().
set_bool_service() [4/5]
def service_node_3.Service3.set_bool_service (self, req, res)
Definition at line 34 of file service_node_3.py.
        def set_bool_service(self, req, res):
            self.get_logger().info("RECEIVING SET BOOL SERVICE REQUEST: value=" + str(req.data))
            res.message = "OK, value set"
            res.success = True
            return res
    rclpy.init(args=None)
Referenced by service_node_3.Service3.__init__().
set_bool_service() [5/5]
def service_node_3.Service3.set_bool_service (self, req, res)
Definition at line 34 of file service_node_3.py.
        def set_bool_service(self, req, res):
            self.get_logger().info("RECEIVING SET BOOL SERVICE REQUEST: value=" + str(req.data))
            res.message = "OK, value set"
            res.success = True
            return res
    rclpy.init(args=None)
Referenced by service_node_3.Service3.__init__().
Member Data Documentation
s
service_node_3.Service3.s
Definition at line 30 of file service_node_3.py.
Referenced by service_node_3.Service3.__init__().
The documentation for this class was generated from the following files:
smacc2_sm_reference_library/sm_dance_bot/servers/service_node_3/service_node_3.py
smacc2_sm_reference_library/sm_dance_bot_strikes_back/servers/service_node_3/service_node_3.py
smacc2_sm_reference_library/sm_dance_bot_warehouse/servers/service_node_3/service_node_3.py
smacc2_sm_reference_library/sm_dance_bot_warehouse_2/servers/service_node_3/service_node_3.py
smacc2_sm_reference_library/sm_dance_bot_warehouse_3/servers/service_node_3/service_node_3.py