SMACC2: sm_husky_barrel_search_1::cl_led_array::CbSequenceColorBlinking Class Reference
sm_husky_barrel_search_1::cl_led_array::CbSequenceColorBlinking Class Reference
#include <cb_sequence_color_blinking.hpp>
Public Member Functions
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
Definition at line 32 of file cb_sequence_color_blinking.hpp.
Member Function Documentation
onEntry()
void sm_husky_barrel_search_1::cl_led_array::CbSequenceColorBlinking::onEntry () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 35 of file cb_sequence_color_blinking.hpp.
  {
    cl_led_array::ClLedArray* ledarray;
    this->requiresClient(ledarray);
    while (!isShutdownRequested())
    {
      ledarray->turnOn(LedColor::RED);
      rclcpp::sleep_for(1s);
      ledarray->turnOff(LedColor::RED);
      ledarray->turnOn(LedColor::YELLOW);
      rclcpp::sleep_for(1s);
      ledarray->turnOff(LedColor::YELLOW);
      ledarray->turnOn(LedColor::GREEN);
      rclcpp::sleep_for(1s);
      ledarray->turnOff(LedColor::GREEN);
    }
  }
References sm_husky_barrel_search_1::cl_led_array::GREEN, smacc2::SmaccAsyncClientBehavior::isShutdownRequested(), sm_husky_barrel_search_1::cl_led_array::RED, smacc2::ISmaccClientBehavior::requiresClient(), service_node_3::s, sm_husky_barrel_search_1::cl_led_array::ClLedArray::turnOff(), sm_husky_barrel_search_1::cl_led_array::ClLedArray::turnOn(), and sm_husky_barrel_search_1::cl_led_array::YELLOW.
onExit()
void sm_husky_barrel_search_1::cl_led_array::CbSequenceColorBlinking::onExit () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 54 of file cb_sequence_color_blinking.hpp.
  {
  }
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_husky_barrel_search_1/include/sm_husky_barrel_search_1/clients/led_array/client_behaviors/cb_sequence_color_blinking.hpp