SMACC2: smacc2::CbServiceServerCallbackBase< TService > Class Template Reference
smacc2::CbServiceServerCallbackBase< TService > Class Template Reference abstract
#include <cb_service_server_callback_base.hpp>
Public Member Functions
virtual void onEntry () override
virtual void onServiceRequestReceived (const std::shared_ptr< typename TService::Request > req, std::shared_ptr< typename TService::Response > res)=0
Public Member Functions inherited from smacc2::SmaccClientBehavior
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Protected Attributes
smacc2::client_bases::SmaccServiceServerClient< TService > * attachedClient_ = nullptr
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Detailed Description
template<typename TService>
class smacc2::CbServiceServerCallbackBase< TService >
Definition at line 21 of file cb_service_server_callback_base.hpp.
Member Function Documentation
onEntry()
template<typename TService > virtual void smacc2::CbServiceServerCallbackBase< TService >::onEntry () inline override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 24 of file cb_service_server_callback_base.hpp.
  {
    this->requiresClient(attachedClient_);
    attachedClient_->onServiceRequestReceived(
      &CbServiceServerCallbackBase::onServiceRequestReceived, this);
  }
References smacc2::CbServiceServerCallbackBase< TService >::attachedClient_, smacc2::CbServiceServerCallbackBase< TService >::onServiceRequestReceived(), and smacc2::ISmaccClientBehavior::requiresClient().
onServiceRequestReceived()
template<typename TService > virtual void smacc2::CbServiceServerCallbackBase< TService >::onServiceRequestReceived (const std::shared_ptr< typename TService::Request > req, std::shared_ptr< typename TService::Response > res) pure virtual
Referenced by smacc2::CbServiceServerCallbackBase< TService >::onEntry().
Member Data Documentation
attachedClient_
template<typename TService > smacc2::client_bases::SmaccServiceServerClient<TService>* smacc2::CbServiceServerCallbackBase< TService >::attachedClient_ = nullptr protected
Definition at line 36 of file cb_service_server_callback_base.hpp.
Referenced by smacc2::CbServiceServerCallbackBase< TService >::onEntry().
The documentation for this class was generated from the following file:
smacc2/include/smacc2/client_behaviors/cb_service_server_callback_base.hpp