SMACC2: smacc2::ControllableLed Class Reference
smacc2::ControllableLed Class Reference
Public Member Functions
ControllableLed ()
void LightCmd (const std_msgs::msg::Int8::SharedPtr msg)
void Load (gazebo::physics::ModelPtr _parent, sdf::ElementPtr _sdf) override
void OnCommand (ConstIntPtr &_msg)
Public Member Functions inherited from smacc2::LedPlugin
LedPlugin ()
Constructor.
virtual ~LedPlugin ()
Destructor.
Public Member Functions inherited from smacc2::FlashLightPlugin
FlashLightPlugin ()
Constructor.
virtual ~FlashLightPlugin ()
Destructor.
void Load (gazebo::physics::ModelPtr _parent, sdf::ElementPtr _sdf) override
Public Attributes
gazebo_ros::Node::SharedPtr ros_node_
A pointer to the GazeboROS node.
rclcpp::Subscription< std_msgs::msg::Int8 >::SharedPtr subscription_
Additional Inherited Members
Protected Member Functions inherited from smacc2::LedPlugin
virtual std::shared_ptr< FlashLightSetting > CreateSetting (const sdf::ElementPtr &_sdf, const gazebo::physics::ModelPtr &_model, const gazebo::common::Time &_currentTime, gazebo_ros::Node::SharedPtr node)
Create an object of setting.
virtual void InitSettingBySpecificData (std::shared_ptr< FlashLightSetting > &_setting)
Initialize the additional part of an object of setting.
Protected Member Functions inherited from smacc2::FlashLightPlugin
virtual void OnUpdate ()
Called by the world update start event.
virtual bool TurnOn (const std::string &_lightName) final
Turn on a flash light specified by the light name If more than one link have lights with the identical name, the first appearing light in the list will be updated.
virtual bool TurnOn (const std::string &_lightName, const std::string &_linkName) final
Turn on a flash light specified by the name and its link.
virtual bool TurnOnAll () final
Turn on all flash lights.
virtual bool TurnOff (const std::string &_lightName) final
Turn off a flash light specified by the name If more than one link have lights with the identical name, the first appearing light in the list will be updated.
virtual bool TurnOff (const std::string &_lightName, const std::string &_linkName) final
Turn off a flash light specified by the name.
virtual bool TurnOffAll () final
Turn off all flash lights.
virtual bool ChangeDuration (const std::string &_lightName, const std::string &_linkName, const double _duration, const int _index) final
Change the duration of a specific block of the flashlight. If the index is a negative number, it updates all the blocks.
virtual bool ChangeDuration (const std::string &_lightName, const std::string &_linkName, const double _duration) final
Change the duration of all the blocks of the flashlight.
virtual bool ChangeInterval (const std::string &_lightName, const std::string &_linkName, const double _interval, const int _index) final
Change the interval of a specific block of the flashlight. If the index is a negative number, it updates all the blocks.
virtual bool ChangeInterval (const std::string &_lightName, const std::string &_linkName, const double _interval) final
Change the interval of all the blocks of the flashlight.
virtual bool ChangeColor (const std::string &_lightName, const std::string &_linkName, const ignition::math::Color &_color, const int _index) final
Change the color of a specific block of the flashlight. If the index is a negative number, it updates all the blocks.
virtual bool ChangeColor (const std::string &_lightName, const std::string &_linkName, const ignition::math::Color &_color) final
Change the color of all the blocks of the flashlight.
virtual std::shared_ptr< FlashLightSetting > CreateSetting (const sdf::ElementPtr &_sdf, const gazebo::physics::ModelPtr &_model, const gazebo::common::Time &_currentTime, gazebo_ros::Node::SharedPtr node)
Create an object of setting.
virtual void InitSettingBySpecificData (std::shared_ptr< FlashLightSetting > &_setting)
Initialize the additional part of an object of setting.
Detailed Description
Definition at line 38 of file controllable_led_plugin.cpp.
Constructor & Destructor Documentation
ControllableLed()
smacc2::ControllableLed::ControllableLed () inline
Definition at line 45 of file controllable_led_plugin.cpp.
                    : LedPlugin()
  {
    gzmsg << "Loading ControllableLed plugin\n";
    // Transport initialization
    // this->gzNode = gazebo::transport::NodePtr(new gazebo::transport::Node());
    // this->gzNode->Init();
    // Subscribe to ContainPlugin output
    //std::string topic("/test_cmd");
    // const bool containSub = this->dataPtr->node.Subscribe(topic,  &ControllableLed::OnCommand2, this);
    // //containSub = this->gzNode->Subscribe(topic, &ControllableLed::OnCommand, this);
    // if (!containSub)
    // {
    //   gzerr << "Failed to subscribe to [" << topic << "]\n";
    // }
    // else
    // {
    //   gzmsg << "Subscribed to [" << topic << "]\n";
    // }
    // Subscribe to ContainPlugin output
    // std::string topic("contain_example/contain");
    // std::function<void(const ignition::msgs::Boolean &)> cb =
    //   [=](const ignition::msgs::Boolean & _msg)
    // {
    //   //TurnOnLightPlugin::OnContainPluginMsg(_msg);
    // };
    // const bool containSub = this->node.Subscribe(topic, cb);
    // if (!containSub)
    // {
    //   gzerr << "Failed to subscribe to [" << topic << "]\n";
    // }
  }
Member Function Documentation
LightCmd()
void smacc2::ControllableLed::LightCmd (const std_msgs::msg::Int8::SharedPtr msg) inline
Definition at line 81 of file controllable_led_plugin.cpp.
  {
    gzmsg << "Turning on light\n";
    if (msg->data == 1)
    {
      gzmsg << "Turning on light\n";
      this->TurnOnAll();
      // lightMsg.set_range(15.0);
    }
    else if (msg->data == 0)
    {
      gzmsg << "Turning off light\n";
      this->TurnOffAll();
      // lightMsg.set_range(0.0);
    }
  }
References smacc2::FlashLightPlugin::TurnOffAll(), and smacc2::FlashLightPlugin::TurnOnAll().
Load()
void smacc2::ControllableLed::Load (gazebo::physics::ModelPtr _parent, sdf::ElementPtr _sdf) inline override
Definition at line 99 of file controllable_led_plugin.cpp.
  {
    // Subscribe to wrench messages
    // ros_node_ = gazebo_ros::Node::Get(_sdf);
    // subscription_ = ros_node_->create_subscription<std_msgs::msg::Int8>(
    // "led_cmd", rclcpp::SystemDefaultsQoS(),
    // std::bind(&ControllableLed::LightCmd, this, std::placeholders::_1));
    // // Make a publisher for the light topic
    // this->lightPub = this->gzNode->Advertise<msgs::Light>("~/light/modify");
    LedPlugin::Load(_parent, _sdf);
    //this->TurnOnAll();
  }
References smacc2::FlashLightPlugin::Load().
OnCommand()
void smacc2::ControllableLed::OnCommand (ConstIntPtr & _msg) inline
Definition at line 116 of file controllable_led_plugin.cpp.
  {
  }
Member Data Documentation
ros_node_
gazebo_ros::Node::SharedPtr smacc2::ControllableLed::ros_node_
A pointer to the GazeboROS node.
Definition at line 42 of file controllable_led_plugin.cpp.
subscription_
rclcpp::Subscription<std_msgs::msg::Int8>::SharedPtr smacc2::ControllableLed::subscription_
Definition at line 43 of file controllable_led_plugin.cpp.
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_husky_barrel_search_1/src/sm_husky_barrel_search_1/gz_plugins/controllable_led_plugin.cpp