SMACC2: sm_husky_barrel_search_1::cl_led_array::ClLedArray Class Reference
sm_husky_barrel_search_1::cl_led_array::ClLedArray Class Reference
#include <cl_led_array.hpp>
Public Member Functions
ClLedArray ()
virtual ~ClLedArray ()
void onInitialize () override
void turnOff (LedColor color)
void turnOn (LedColor color)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void onInitialize ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
const std::vector< std::shared_ptr< ISmaccComponent > > & iterateComponents () const
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Public Attributes
smacc2::components::CpTopicPublisher< std_msgs::msg::Int8 > * greenLed_
smacc2::components::CpTopicPublisher< std_msgs::msg::Int8 > * yellowLed_
smacc2::components::CpTopicPublisher< std_msgs::msg::Int8 > * redLed_
std::map< LedColor, smacc2::components::CpTopicPublisher< std_msgs::msg::Int8 > * > ledComponentByKey_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Detailed Description
Definition at line 35 of file cl_led_array.hpp.
Constructor & Destructor Documentation
ClLedArray()
sm_husky_barrel_search_1::cl_led_array::ClLedArray::ClLedArray () inline
Definition at line 44 of file cl_led_array.hpp.
{}
~ClLedArray()
virtual sm_husky_barrel_search_1::cl_led_array::ClLedArray::~ClLedArray () inline virtual
Definition at line 46 of file cl_led_array.hpp.
{}
Member Function Documentation
onInitialize()
void sm_husky_barrel_search_1::cl_led_array::ClLedArray::onInitialize () inline override virtual
Reimplemented from smacc2::ISmaccClient.
Definition at line 48 of file cl_led_array.hpp.
  {
    greenLed_ =
      getComponent<smacc2::components::CpTopicPublisher<std_msgs::msg::Int8>>("greenLed");
    yellowLed_ =
      getComponent<smacc2::components::CpTopicPublisher<std_msgs::msg::Int8>>("yellowLed");
    redLed_ = getComponent<smacc2::components::CpTopicPublisher<std_msgs::msg::Int8>>("redLed");
    ledComponentByKey_ = {{LedColor::GREEN, greenLed_},
                          {LedColor::YELLOW, yellowLed_},
                          {LedColor::RED, redLed_}
    };
  }
References sm_husky_barrel_search_1::cl_led_array::GREEN, greenLed_, ledComponentByKey_, sm_husky_barrel_search_1::cl_led_array::RED, redLed_, sm_husky_barrel_search_1::cl_led_array::YELLOW, and yellowLed_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void sm_husky_barrel_search_1::cl_led_array::ClLedArray::onOrthogonalAllocation () inline
Definition at line 77 of file cl_led_array.hpp.
  {
  }
turnOff()
void sm_husky_barrel_search_1::cl_led_array::ClLedArray::turnOff (LedColor color) inline
Definition at line 62 of file cl_led_array.hpp.
  {
    std_msgs::msg::Int8 msg;
    msg.data = 0;
    ledComponentByKey_[color]->publish(msg);
  }
References ledComponentByKey_.
Referenced by sm_husky_barrel_search_1::cl_led_array::CbBlinking::onEntry(), sm_husky_barrel_search_1::cl_led_array::CbSequenceColorBlinking::onEntry(), and sm_husky_barrel_search_1::cl_led_array::CbLEDOff::onEntry().
turnOn()
void sm_husky_barrel_search_1::cl_led_array::ClLedArray::turnOn (LedColor color) inline
Definition at line 69 of file cl_led_array.hpp.
  {
    std_msgs::msg::Int8 msg;
    msg.data = 1;
    ledComponentByKey_[color]->publish(msg);
  }
References ledComponentByKey_.
Referenced by sm_husky_barrel_search_1::cl_led_array::CbBlinking::onEntry(), sm_husky_barrel_search_1::cl_led_array::CbSequenceColorBlinking::onEntry(), and sm_husky_barrel_search_1::cl_led_array::CbLEDOn::onEntry().
Member Data Documentation
greenLed_
smacc2::components::CpTopicPublisher<std_msgs::msg::Int8>* sm_husky_barrel_search_1::cl_led_array::ClLedArray::greenLed_
Definition at line 38 of file cl_led_array.hpp.
Referenced by onInitialize().
ledComponentByKey_
std::map<LedColor, smacc2::components::CpTopicPublisher<std_msgs::msg::Int8> *> sm_husky_barrel_search_1::cl_led_array::ClLedArray::ledComponentByKey_
Definition at line 42 of file cl_led_array.hpp.
Referenced by onInitialize(), turnOff(), and turnOn().
redLed_
smacc2::components::CpTopicPublisher<std_msgs::msg::Int8>* sm_husky_barrel_search_1::cl_led_array::ClLedArray::redLed_
Definition at line 40 of file cl_led_array.hpp.
Referenced by onInitialize().
yellowLed_
smacc2::components::CpTopicPublisher<std_msgs::msg::Int8>* sm_husky_barrel_search_1::cl_led_array::ClLedArray::yellowLed_
Definition at line 39 of file cl_led_array.hpp.
Referenced by onInitialize().
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_husky_barrel_search_1/include/sm_husky_barrel_search_1/clients/led_array/cl_led_array.hpp