SMACC2: smacc2::ISmaccClientBehavior Class Reference
smacc2::ISmaccClientBehavior Class Reference
#include <smacc_client_behavior_base.hpp>
Public Member Functions
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Protected Member Functions
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
Private Member Functions
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Private Attributes
ISmaccStateMachine * stateMachine_
ISmaccState * currentState
smacc2::ISmaccOrthogonal * currentOrthogonal
Friends
class ISmaccState
class ISmaccOrthogonal
class ISmaccAsynchronousClientBehavior
Detailed Description
Definition at line 29 of file smacc_client_behavior_base.hpp.
Constructor & Destructor Documentation
ISmaccClientBehavior()
smacc2::ISmaccClientBehavior::ISmaccClientBehavior ()
Definition at line 25 of file smacc_client_behavior_base.cpp.
{
  stateMachine_ = nullptr;
  currentState = nullptr;
}
References currentState, and stateMachine_.
~ISmaccClientBehavior()
smacc2::ISmaccClientBehavior::~ISmaccClientBehavior () virtual
Definition at line 31 of file smacc_client_behavior_base.cpp.
{
  RCLCPP_WARN_STREAM(getLogger(), "[" << getName() << "Client behavior deallocated.");
}
References getLogger(), and getName().
Member Function Documentation
dispose()
void smacc2::ISmaccClientBehavior::dispose () protected virtual
Reimplemented in smacc2::SmaccAsyncClientBehavior.
Definition at line 77 of file smacc_client_behavior_base.cpp.
{}
executeOnEntry()
void smacc2::ISmaccClientBehavior::executeOnEntry () virtual
Reimplemented in smacc2::SmaccAsyncClientBehavior.
Definition at line 63 of file smacc_client_behavior_base.cpp.
{
  RCLCPP_DEBUG(
    getLogger(), "[%s] Default empty SmaccClientBehavior onEntry", this->getName().c_str());
  this->onEntry();
}
References getLogger(), getName(), and onEntry().
executeOnExit()
void smacc2::ISmaccClientBehavior::executeOnExit () virtual
Reimplemented in smacc2::SmaccAsyncClientBehavior.
Definition at line 70 of file smacc_client_behavior_base.cpp.
{
  RCLCPP_DEBUG(
    getLogger(), "[%s] Default empty SmaccClientBehavior onExit", this->getName().c_str());
  this->onExit();
}
References getLogger(), getName(), and onExit().
getCurrentState()
ISmaccState * smacc2::ISmaccClientBehavior::getCurrentState () inline protected
Definition at line 64 of file smacc_client_behavior_impl.hpp.
{ return this->currentState; }
References currentState.
Referenced by cl_nav2z::CbAbsoluteRotate::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbNavigateGlobalPosition::onEntry(), cl_nav2z::CbRotate::onEntry(), and smacc2::client_behaviors::CbSequence::then().
getLogger()
rclcpp::Logger smacc2::ISmaccClientBehavior::getLogger () const protected virtual
Definition at line 43 of file smacc_client_behavior_base.cpp.
{
  auto nh = this->getNode();
  if (nh != nullptr)
  {
    return nh->get_logger();
  }
  else
  {
    return rclcpp::get_logger("SMACC");
  }
}
References getNode(), and nh.
Referenced by cl_nav2z::CbNavigateBackwards::CbNavigateBackwards(), cl_move_group_interface::CbCircularPivotMotion::computeCurrentEndEffectorPoseRelativeToPivot(), cl_move_group_interface::CbMoveEndEffectorTrajectory::computeJointSpaceTrajectory(), smacc2::SmaccAsyncClientBehavior::dispose(), cl_nav2z::CbNavigateGlobalPosition::execute(), cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), executeOnEntry(), smacc2::SmaccAsyncClientBehavior::executeOnEntry(), executeOnExit(), smacc2::SmaccAsyncClientBehavior::executeOnExit(), cl_move_group_interface::CbCircularPivotMotion::generateTrajectory(), cl_move_group_interface::CbMoveCartesianRelative2::generateTrajectory(), cl_move_group_interface::CbCircularPouringMotion::generateTrajectory(), cl_move_group_interface::CbMoveEndEffectorTrajectory::initializeROS(), cl_nav2z::CbNav2ZClientBehaviorBase::isOwnActionResponse(), cl_move_group_interface::CbMoveKnownState::loadJointStatesFromFile(), cl_move_group_interface::CbMoveJoints::moveJoints(), cl_move_group_interface::CbMoveEndEffectorRelative::moveRelative(), cl_move_group_interface::CbMoveCartesianRelative::moveRelativeCartesian(), cl_move_group_interface::CbMoveEndEffector::moveToAbsolutePose(), smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry(), smacc2::client_behaviors::CbRosLaunch::onEntry(), smacc2::client_behaviors::CbSequence::onEntry(), smacc2::client_behaviors::CbWaitActionServer::onEntry(), smacc2::client_behaviors::CbWaitNode::onEntry(), smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onEntry(), smacc2::SmaccClientBehavior::onEntry(), cl_move_group_interface::CbAttachObject::onEntry(), cl_move_group_interface::CbDetachObject::onEntry(), cl_move_group_interface::CbEndEffectorRotate::onEntry(), cl_move_group_interface::CbMoveEndEffector::onEntry(), cl_move_group_interface::CbMoveEndEffectorRelative::onEntry(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry(), cl_move_group_interface::CbMoveLastTrajectoryInitialState::onEntry(), cl_move_group_interface::CbUndoLastTrajectory::onEntry(), cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onEntry(), cl_nav2z::CbAbsoluteRotate::onEntry(), cl_nav2z::CbNavigateBackwards::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbNavigateGlobalPosition::onEntry(), cl_nav2z::CbNavigateNextWaypoint::onEntry(), cl_nav2z::CbPauseSlam::onEntry(), cl_nav2z::CbResumeSlam::onEntry(), cl_nav2z::CbRotate::onEntry(), cl_nav2z::CbWaitNav2Nodes::onEntry(), cl_nav2z::CbWaitPose::onEntry(), cl_nav2z::CbWaitTransform::onEntry(), sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition::onEntry(), sm_dance_bot::cl_lidar::CbLidarSensor::onEntry(), sm_dance_bot::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry(), sm_dance_bot_strikes_back::cl_lidar::CbLidarSensor::onEntry(), sm_dance_bot_strikes_back::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry(), sm_dance_bot_warehouse::cl_lidar::CbLidarSensor::onEntry(), sm_dance_bot_warehouse::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry(), sm_dance_bot_warehouse_2::cl_lidar::CbLidarSensor::onEntry(), sm_dance_bot_warehouse_2::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry(), sm_dance_bot_warehouse_3::cl_lidar::CbLidarSensor::onEntry(), sm_dance_bot_warehouse_3::cl_nav2zclient::CbPureSpinning::onEntry(), sm_dance_bot_warehouse_3::cl_temperature_sensor::CbConditionTemperatureSensor::onEntry(), smacc2::SmaccClientBehavior::onExit(), cl_nav2z::CbNavigateGlobalPosition::onExit(), cl_nav2z::CbUndoPathBackwards::onExit(), cl_nav2z::CbWaitNav2Nodes::onMessageReceived(), sm_ferrari::cl_subscriber::CbMySubscriberBehavior::onMessageReceived(), sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior::onMessageReceived(), smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onMessageReceived(), cl_nav2z::CbNav2ZClientBehaviorBase::onNavigationActionAbort(), cl_nav2z::CbNav2ZClientBehaviorBase::onNavigationActionSuccess(), cl_nav2z::CbNavigateNextWaypointUntilReached::onNavigationActionSuccess(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onOrthogonalAllocation(), cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onOrthogonalAllocation(), smacc2::client_behaviors::CbSequence::onSubNodeAbort(), smacc2::client_behaviors::CbSequence::onSubNodeSuccess(), postEvent(), cl_keyboard::CbDefaultKeyboardBehavior::postKeyEvent(), smacc2::client_behaviors::CbSequence::recursiveConsumeNext(), smacc2::SmaccAsyncClientBehavior::requestForceFinish(), requiresComponent(), runtimeConfigure(), sm_dance_bot::cl_string_publisher::CbStringPublisher::runtimeConfigure(), sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher::runtimeConfigure(), sm_dance_bot_warehouse::cl_string_publisher::CbStringPublisher::runtimeConfigure(), sm_dance_bot_warehouse_2::cl_string_publisher::CbStringPublisher::runtimeConfigure(), sm_dance_bot_warehouse_3::cl_string_publisher::CbStringPublisher::runtimeConfigure(), cl_nav2z::CbNav2ZClientBehaviorBase::sendGoal(), cl_nav2z::CbNavigateForward::setForwardDistance(), smacc2::client_behaviors::CbSequence::then(), cl_nav2z::CbAbsoluteRotate::updateTemporalBehaviorParameters(), smacc2::SmaccAsyncClientBehavior::waitFutureIfNotFinished(), and ~ISmaccClientBehavior().
getName()
std::string smacc2::ISmaccClientBehavior::getName () const
Definition at line 36 of file smacc_client_behavior_base.cpp.
{ return demangleSymbol(typeid(*this).name()); }
References smacc2::introspection::demangleSymbol().
Referenced by cl_move_group_interface::CbCircularPivotMotion::computeCurrentEndEffectorPoseRelativeToPivot(), cl_move_group_interface::CbMoveEndEffectorTrajectory::computeJointSpaceTrajectory(), smacc2::SmaccAsyncClientBehavior::dispose(), cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), executeOnEntry(), smacc2::SmaccAsyncClientBehavior::executeOnEntry(), executeOnExit(), smacc2::SmaccAsyncClientBehavior::executeOnExit(), cl_move_group_interface::CbCircularPivotMotion::generateTrajectory(), cl_move_group_interface::CbMoveCartesianRelative2::generateTrajectory(), cl_move_group_interface::CbCircularPouringMotion::generateTrajectory(), cl_move_group_interface::CbMoveEndEffectorTrajectory::initializeROS(), cl_nav2z::CbNav2ZClientBehaviorBase::isOwnActionResponse(), cl_move_group_interface::CbMoveKnownState::loadJointStatesFromFile(), cl_move_group_interface::CbMoveJoints::moveJoints(), smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry(), smacc2::client_behaviors::CbWaitNode::onEntry(), smacc2::SmaccClientBehavior::onEntry(), cl_move_group_interface::CbAttachObject::onEntry(), cl_move_group_interface::CbDetachObject::onEntry(), cl_move_group_interface::CbEndEffectorRotate::onEntry(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry(), cl_move_group_interface::CbMoveLastTrajectoryInitialState::onEntry(), cl_move_group_interface::CbUndoLastTrajectory::onEntry(), cl_nav2z::CbAbsoluteRotate::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbNavigateGlobalPosition::onEntry(), cl_nav2z::CbRotate::onEntry(), sm_dance_bot_warehouse_3::cl_nav2zclient::CbPureSpinning::onEntry(), smacc2::SmaccClientBehavior::onExit(), cl_nav2z::CbUndoPathBackwards::onExit(), cl_nav2z::CbNav2ZClientBehaviorBase::onNavigationActionAbort(), cl_nav2z::CbNav2ZClientBehaviorBase::onNavigationActionSuccess(), cl_nav2z::CbNavigateNextWaypointUntilReached::onNavigationActionSuccess(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onOrthogonalAllocation(), smacc2::SmaccAsyncClientBehavior::requestForceFinish(), runtimeConfigure(), cl_nav2z::CbNav2ZClientBehaviorBase::sendGoal(), cl_nav2z::CbNavigateForward::setForwardDistance(), cl_nav2z::CbAbsoluteRotate::updateTemporalBehaviorParameters(), smacc2::SmaccAsyncClientBehavior::waitFutureIfNotFinished(), and ~ISmaccClientBehavior().
getNode()
rclcpp::Node::SharedPtr smacc2::ISmaccClientBehavior::getNode () const protected virtual
Definition at line 38 of file smacc_client_behavior_base.cpp.
{
  return this->stateMachine_->getNode();
}
References smacc2::ISmaccStateMachine::getNode(), and stateMachine_.
Referenced by cl_move_group_interface::CbCircularPivotMotion::computeCurrentEndEffectorPoseRelativeToPivot(), cl_move_group_interface::CbMoveEndEffectorTrajectory::createMarkers(), cl_move_group_interface::CbCircularPivotMotion::createMarkers(), cl_move_group_interface::CbCircularPouringMotion::createMarkers(), cl_nav2z::CbNavigateGlobalPosition::execute(), cl_move_group_interface::CbMoveCartesianRelative2::generateTrajectory(), cl_move_group_interface::CbCircularPouringMotion::generateTrajectory(), cl_move_group_interface::CbMoveEndEffectorTrajectory::getCurrentEndEffectorPose(), getLogger(), cl_move_group_interface::CbMoveEndEffectorTrajectory::initializeROS(), smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry(), smacc2::client_behaviors::CbSequence::onEntry(), smacc2::client_behaviors::CbWaitNode::onEntry(), smacc2::client_behaviors::CbWaitTopicMessage< TMessage >::onEntry(), cl_move_group_interface::CbAttachObject::onEntry(), cl_move_group_interface::CbEndEffectorRotate::onEntry(), cl_move_group_interface::CbMoveCartesianRelative::onEntry(), cl_move_group_interface::CbMoveEndEffector::onEntry(), cl_move_group_interface::CbMoveEndEffectorRelative::onEntry(), cl_move_group_interface::CbMoveJoints::onEntry(), cl_nav2z::CbAbsoluteRotate::onEntry(), cl_nav2z::CbNavigateBackwards::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbRotate::onEntry(), cl_nav2z::CbUndoPathBackwards::onEntry(), cl_nav2z::CbWaitNav2Nodes::onEntry(), cl_nav2z::CbWaitTransform::onEntry(), sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition::onEntry(), sm_autoware_avp::clients::autoware_client::CbSetupInitialPoseEstimation::onEntry(), sm_dance_bot_warehouse_3::cl_nav2zclient::CbPureSpinning::onEntry(), cl_move_group_interface::CbWaitJointState::onEntry(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onExit(), smacc2::SmaccAsyncClientBehavior::requestForceFinish(), cl_nav2z::CbAbsoluteRotate::updateTemporalBehaviorParameters(), and smacc2::SmaccAsyncClientBehavior::waitFutureIfNotFinished().
getStateMachine()
ISmaccStateMachine * smacc2::ISmaccClientBehavior::getStateMachine () inline
Definition at line 61 of file smacc_client_behavior_impl.hpp.
{ return this->stateMachine_; }
References stateMachine_.
Referenced by smacc2::SmaccAsyncClientBehavior::onFailure(), smacc2::SmaccAsyncClientBehavior::onFinished(), smacc2::SmaccAsyncClientBehavior::onSuccess(), cl_ros_timer::CbTimerCountdownLoop::onTimerTick(), and cl_ros_timer::CbTimerCountdownOnce::onTimerTick().
onEntry()
virtual void smacc2::ISmaccClientBehavior::onEntry () inline virtual
Reimplemented in cl_keyboard::CbDefaultKeyboardBehavior, sm_advanced_recovery_1::cl_subscriber::CbDefaultSubscriberBehavior, sm_advanced_recovery_1::cl_subscriber::CbWatchdogSubscriberBehavior, sm_dance_bot::cl_string_publisher::CbStringPublisher, sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse_2::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse_3::cl_string_publisher::CbStringPublisher, sm_ferrari::cl_subscriber::CbMySubscriberBehavior, sm_multi_stage_1::cl_subscriber::CbDefaultSubscriberBehavior, sm_multi_stage_1::cl_subscriber::CbWatchdogSubscriberBehavior, sm_pack_ml::cl_subscriber::CbDefaultSubscriberBehavior, sm_pack_ml::cl_subscriber::CbWatchdogSubscriberBehavior, sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior, sm_respira_1::cl_subscriber::CbDefaultSubscriberBehavior, sm_respira_1::cl_subscriber::CbWatchdogSubscriberBehavior, sm_three_some::cl_subscriber::CbDefaultSubscriberBehavior, sm_three_some::cl_subscriber::CbWatchdogSubscriberBehavior, smacc2::client_behaviors::CbServiceCall< ServiceType >, smacc2::client_behaviors::CbServiceCall< slam_toolbox::srv::Pause >, smacc2::client_behaviors::CbRosLaunch, smacc2::client_behaviors::CbSequence, smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg >, smacc2::client_behaviors::CbWaitActionServer, smacc2::client_behaviors::CbWaitNode, smacc2::client_behaviors::CbWaitTopicMessage< TMessage >, smacc2::SmaccClientBehavior, cl_move_group_interface::CbAttachObject, cl_move_group_interface::CbDetachObject, cl_move_group_interface::CbEndEffectorRotate, cl_move_group_interface::CbExecuteLastTrajectory, cl_move_group_interface::CbMoveCartesianRelative, cl_move_group_interface::CbMoveEndEffector, cl_move_group_interface::CbMoveEndEffectorRelative, cl_move_group_interface::CbMoveEndEffectorTrajectory, cl_move_group_interface::CbMoveJoints, cl_move_group_interface::CbMoveKnownState, cl_move_group_interface::CbMoveLastTrajectoryInitialState, cl_move_group_interface::CbMoveNamedTarget, cl_move_group_interface::CbUndoLastTrajectory, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >, cl_nav2z::CbAbortNavigation, cl_nav2z::CbAbsoluteRotate, cl_nav2z::CbNavigateBackwards, cl_nav2z::CbNavigateForward, cl_nav2z::CbNavigateGlobalPosition, cl_nav2z::CbNavigateNamedWaypoint, cl_nav2z::CbNavigateNextWaypoint, cl_nav2z::CbNavigateNextWaypointUntilReached, cl_nav2z::CbPauseSlam, cl_nav2z::CbResumeSlam, cl_nav2z::CbRotate, cl_nav2z::CbRotateLookAt, cl_nav2z::CbSeekWaypoint, cl_nav2z::CbUndoPathBackwards, cl_nav2z::CbWaitNav2Nodes, cl_nav2z::CbWaitPose, cl_nav2z::CbWaitTransform, cl_ros_publisher::CbDefaultPublishLoop, cl_ros_publisher::CbMutedBehavior< RosMsgType >, cl_ros_publisher::CbPublishOnce< RosMsgType >, cl_ros_timer::CbTimer, cl_ros_timer::CbTimer, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownOnce, cl_ros_timer::CbTimerCountdownOnce, cl_ros_timer::CbTimer, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownOnce, sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition, sm_autoware_avp::clients::autoware_client::CbSetupInitialPoseEstimation, sm_dance_bot::cl_led::CbLEDOff, sm_dance_bot::cl_led::CbLEDOn, sm_dance_bot::cl_lidar::CbLidarSensor, sm_dance_bot::cl_service3::CbService3, sm_dance_bot::cl_temperature_sensor::CbConditionTemperatureSensor, sm_dance_bot_strikes_back::cl_led::CbLEDOff, sm_dance_bot_strikes_back::cl_led::CbLEDOn, sm_dance_bot_strikes_back::cl_lidar::CbLidarSensor, sm_dance_bot_strikes_back::cl_service3::CbService3, sm_dance_bot_strikes_back::cl_temperature_sensor::CbConditionTemperatureSensor, sm_dance_bot_warehouse::cl_led::CbLEDOff, sm_dance_bot_warehouse::cl_led::CbLEDOn, sm_dance_bot_warehouse::cl_lidar::CbLidarSensor, sm_dance_bot_warehouse::cl_service3::CbService3, sm_dance_bot_warehouse::cl_temperature_sensor::CbConditionTemperatureSensor, sm_dance_bot_warehouse_2::cl_led::CbLEDOff, sm_dance_bot_warehouse_2::cl_led::CbLEDOn, sm_dance_bot_warehouse_2::cl_lidar::CbLidarSensor, sm_dance_bot_warehouse_2::cl_service3::CbService3, sm_dance_bot_warehouse_2::cl_temperature_sensor::CbConditionTemperatureSensor, sm_dance_bot_warehouse_3::cl_led::CbLEDOff, sm_dance_bot_warehouse_3::cl_led::CbLEDOn, sm_dance_bot_warehouse_3::cl_lidar::CbLidarSensor, sm_dance_bot_warehouse_3::cl_nav2zclient::CbPureSpinning, sm_dance_bot_warehouse_3::cl_service3::CbService3, sm_dance_bot_warehouse_3::cl_temperature_sensor::CbConditionTemperatureSensor, sm_husky_barrel_search_1::CbSleepFor, sm_husky_barrel_search_1::cl_led_array::CbBlinking, sm_husky_barrel_search_1::cl_led_array::CbSequenceColorBlinking, sm_husky_barrel_search_1::cl_led_array::CbLEDOff, sm_husky_barrel_search_1::cl_led_array::CbLEDOn, and cl_move_group_interface::CbWaitJointState.
Definition at line 46 of file smacc_client_behavior_base.hpp.
{}
Referenced by executeOnEntry(), and smacc2::SmaccAsyncClientBehavior::executeOnEntry().
onExit()
virtual void smacc2::ISmaccClientBehavior::onExit () inline virtual
Reimplemented in cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >, smacc2::client_behaviors::CbSequence, smacc2::SmaccClientBehavior, cl_move_group_interface::CbAttachObject, cl_move_group_interface::CbDetachObject, cl_move_group_interface::CbMoveCartesianRelative, cl_move_group_interface::CbMoveEndEffectorRelative, cl_move_group_interface::CbMoveEndEffectorTrajectory, cl_move_group_interface::CbMoveJoints, cl_move_group_interface::CbMoveNamedTarget, cl_nav2z::CbAbortNavigation, cl_nav2z::CbAbsoluteRotate, cl_nav2z::CbNavigateBackwards, cl_nav2z::CbNavigateForward, cl_nav2z::CbNavigateGlobalPosition, cl_nav2z::CbNavigateNamedWaypoint, cl_nav2z::CbNavigateNextWaypoint, cl_nav2z::CbNavigateNextWaypointUntilReached, cl_nav2z::CbSeekWaypoint, cl_nav2z::CbUndoPathBackwards, cl_ros_publisher::CbDefaultPublishLoop, cl_ros_publisher::CbMutedBehavior< RosMsgType >, cl_ros_publisher::CbPublishOnce< RosMsgType >, cl_ros_timer::CbTimer, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownOnce, sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition, sm_autoware_avp::clients::autoware_client::CbSetupInitialPoseEstimation, sm_dance_bot::cl_led::CbLEDOff, sm_dance_bot::cl_led::CbLEDOn, sm_dance_bot::cl_string_publisher::CbStringPublisher, sm_dance_bot_strikes_back::cl_led::CbLEDOff, sm_dance_bot_strikes_back::cl_led::CbLEDOn, sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse::cl_led::CbLEDOff, sm_dance_bot_warehouse::cl_led::CbLEDOn, sm_dance_bot_warehouse::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse_2::cl_led::CbLEDOff, sm_dance_bot_warehouse_2::cl_led::CbLEDOn, sm_dance_bot_warehouse_2::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse_3::cl_led::CbLEDOff, sm_dance_bot_warehouse_3::cl_led::CbLEDOn, sm_dance_bot_warehouse_3::cl_nav2zclient::CbPureSpinning, sm_dance_bot_warehouse_3::cl_string_publisher::CbStringPublisher, sm_husky_barrel_search_1::CbSleepFor, sm_husky_barrel_search_1::cl_led_array::CbBlinking, sm_husky_barrel_search_1::cl_led_array::CbSequenceColorBlinking, sm_husky_barrel_search_1::cl_led_array::CbLEDOff, and sm_husky_barrel_search_1::cl_led_array::CbLEDOn.
Definition at line 48 of file smacc_client_behavior_base.hpp.
{}
Referenced by executeOnExit(), and smacc2::SmaccAsyncClientBehavior::executeOnExit().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void smacc2::ISmaccClientBehavior::onOrthogonalAllocation private
Definition at line 90 of file smacc_client_behavior_impl.hpp.
{
}
postEvent() [1/2]
template<typename EventType > void smacc2::ISmaccClientBehavior::postEvent protected
Definition at line 45 of file smacc_client_behavior_impl.hpp.
{
  if (stateMachine_ == nullptr)
  {
    RCLCPP_ERROR(
      getLogger(),
      "The client behavior cannot post events before being assigned to an orthogonal. Ignoring "
      "post event call.");
  }
  else
  {
    stateMachine_->template postEvent<EventType>(EventLifeTime::CURRENT_STATE);
  }
}
References smacc2::CURRENT_STATE, getLogger(), and stateMachine_.
Referenced by sm_dance_bot::cl_temperature_sensor::CbConditionTemperatureSensor::onMessageCallback(), sm_dance_bot_strikes_back::cl_temperature_sensor::CbConditionTemperatureSensor::onMessageCallback(), sm_dance_bot_warehouse::cl_temperature_sensor::CbConditionTemperatureSensor::onMessageCallback(), sm_dance_bot_warehouse_2::cl_temperature_sensor::CbConditionTemperatureSensor::onMessageCallback(), sm_dance_bot_warehouse_3::cl_temperature_sensor::CbConditionTemperatureSensor::onMessageCallback(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onOrthogonalAllocation(), and cl_keyboard::CbDefaultKeyboardBehavior::postKeyEvent().
postEvent() [2/2]
template<typename EventType > void smacc2::ISmaccClientBehavior::postEvent (const EventType & ev) protected
Definition at line 29 of file smacc_client_behavior_impl.hpp.
{
  if (stateMachine_ == nullptr)
  {
    RCLCPP_ERROR(
      getLogger(),
      "The client behavior cannot post events before being assigned to an orthogonal. Ignoring "
      "post event call.");
  }
  else
  {
    stateMachine_->postEvent(ev, EventLifeTime::CURRENT_STATE);
  }
}
References smacc2::CURRENT_STATE, getLogger(), smacc2::ISmaccStateMachine::postEvent(), and stateMachine_.
requiresClient()
template<typename SmaccClientType > void smacc2::ISmaccClientBehavior::requiresClient (SmaccClientType *& storage)
Definition at line 67 of file smacc_client_behavior_impl.hpp.
{
  currentOrthogonal->requiresClient(storage);
}
References currentOrthogonal, and smacc2::ISmaccOrthogonal::requiresClient().
Referenced by cl_keyboard::CbDefaultKeyboardBehavior::onEntry(), sm_dance_bot::cl_string_publisher::CbStringPublisher::onEntry(), sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher::onEntry(), sm_dance_bot_warehouse::cl_string_publisher::CbStringPublisher::onEntry(), sm_dance_bot_warehouse_2::cl_string_publisher::CbStringPublisher::onEntry(), sm_dance_bot_warehouse_3::cl_string_publisher::CbStringPublisher::onEntry(), sm_ferrari::cl_subscriber::CbMySubscriberBehavior::onEntry(), sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior::onEntry(), smacc2::client_behaviors::CbRosLaunch::onEntry(), smacc2::client_behaviors::CbSubscriptionCallbackBase< TMsg >::onEntry(), cl_move_group_interface::CbAttachObject::onEntry(), cl_move_group_interface::CbDetachObject::onEntry(), cl_move_group_interface::CbEndEffectorRotate::onEntry(), cl_move_group_interface::CbExecuteLastTrajectory::onEntry(), cl_move_group_interface::CbMoveCartesianRelative::onEntry(), cl_move_group_interface::CbMoveEndEffector::onEntry(), cl_move_group_interface::CbMoveEndEffectorRelative::onEntry(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry(), cl_move_group_interface::CbMoveJoints::onEntry(), cl_move_group_interface::CbMoveNamedTarget::onEntry(), cl_move_group_interface::CbUndoLastTrajectory::onEntry(), cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >::onEntry(), cl_nav2z::CbRotate::onEntry(), cl_nav2z::CbSeekWaypoint::onEntry(), cl_ros_publisher::CbDefaultPublishLoop::onEntry(), cl_ros_publisher::CbPublishOnce< RosMsgType >::onEntry(), cl_ros_timer::CbTimer::onEntry(), cl_ros_timer::CbTimerCountdownLoop::onEntry(), cl_ros_timer::CbTimerCountdownOnce::onEntry(), sm_autoware_avp::clients::autoware_client::CbNavigateGlobalPosition::onEntry(), sm_autoware_avp::clients::autoware_client::CbSetupInitialPoseEstimation::onEntry(), sm_dance_bot::cl_led::CbLEDOff::onEntry(), sm_dance_bot::cl_led::CbLEDOn::onEntry(), sm_dance_bot::cl_service3::CbService3::onEntry(), sm_dance_bot_strikes_back::cl_led::CbLEDOff::onEntry(), sm_dance_bot_strikes_back::cl_led::CbLEDOn::onEntry(), sm_dance_bot_strikes_back::cl_service3::CbService3::onEntry(), sm_dance_bot_warehouse::cl_led::CbLEDOff::onEntry(), sm_dance_bot_warehouse::cl_led::CbLEDOn::onEntry(), sm_dance_bot_warehouse::cl_service3::CbService3::onEntry(), sm_dance_bot_warehouse_2::cl_led::CbLEDOff::onEntry(), sm_dance_bot_warehouse_2::cl_led::CbLEDOn::onEntry(), sm_dance_bot_warehouse_2::cl_service3::CbService3::onEntry(), sm_dance_bot_warehouse_3::cl_led::CbLEDOff::onEntry(), sm_dance_bot_warehouse_3::cl_led::CbLEDOn::onEntry(), sm_dance_bot_warehouse_3::cl_service3::CbService3::onEntry(), sm_husky_barrel_search_1::cl_led_array::CbBlinking::onEntry(), sm_husky_barrel_search_1::cl_led_array::CbSequenceColorBlinking::onEntry(), sm_husky_barrel_search_1::cl_led_array::CbLEDOff::onEntry(), sm_husky_barrel_search_1::cl_led_array::CbLEDOn::onEntry(), cl_move_group_interface::CbWaitJointState::onEntry(), smacc2::client_behaviors::CbWaitActionServer::onOrthogonalAllocation(), cl_nav2z::CbNav2ZClientBehaviorBase::onOrthogonalAllocation(), cl_nav2z::CbNavigateNextWaypointUntilReached::onOrthogonalAllocation(), and cl_nav2z::CbWaitPose::onOrthogonalAllocation().
requiresComponent()
template<typename SmaccComponentType > void smacc2::ISmaccClientBehavior::requiresComponent (SmaccComponentType *& storage, bool throwExceptionIfNotExist = false)
Definition at line 73 of file smacc_client_behavior_impl.hpp.
{
  if (stateMachine_ == nullptr)
  {
    RCLCPP_ERROR(
      getLogger(),
      "Cannot use the requiresComponent funcionality before assigning the client behavior to an "
      "orthogonal. Try using the OnEntry method to capture required components.");
  }
  else
  {
    stateMachine_->requiresComponent(storage, throwExceptionIfNotExist);
  }
}
References getLogger(), smacc2::ISmaccStateMachine::requiresComponent(), and stateMachine_.
Referenced by cl_move_group_interface::CbAttachObject::onEntry(), cl_move_group_interface::CbDetachObject::onEntry(), cl_move_group_interface::CbExecuteLastTrajectory::onEntry(), cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry(), cl_move_group_interface::CbMoveLastTrajectoryInitialState::onEntry(), cl_move_group_interface::CbUndoLastTrajectory::onEntry(), cl_nav2z::CbPauseSlam::onEntry(), cl_nav2z::CbResumeSlam::onEntry(), cl_nav2z::CbRotateLookAt::onEntry(), and sm_dance_bot_warehouse_3::cl_nav2zclient::CbPureSpinning::onEntry().
runtimeConfigure()
void smacc2::ISmaccClientBehavior::runtimeConfigure () protected virtual
Reimplemented in sm_dance_bot::cl_string_publisher::CbStringPublisher, sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse_2::cl_string_publisher::CbStringPublisher, and sm_dance_bot_warehouse_3::cl_string_publisher::CbStringPublisher.
Definition at line 56 of file smacc_client_behavior_base.cpp.
{
  RCLCPP_DEBUG(
    getLogger(), "[%s] Default empty SmaccClientBehavior runtimeConfigure",
    this->getName().c_str());
}
References getLogger(), and getName().
Friends And Related Function Documentation
ISmaccAsynchronousClientBehavior
friend class ISmaccAsynchronousClientBehavior friend
Definition at line 86 of file smacc_client_behavior_base.hpp.
ISmaccOrthogonal
friend class ISmaccOrthogonal friend
Definition at line 85 of file smacc_client_behavior_base.hpp.
ISmaccState
friend class ISmaccState friend
Definition at line 84 of file smacc_client_behavior_base.hpp.
Member Data Documentation
currentOrthogonal
smacc2::ISmaccOrthogonal* smacc2::ISmaccClientBehavior::currentOrthogonal private
Definition at line 82 of file smacc_client_behavior_base.hpp.
Referenced by requiresClient().
currentState
ISmaccState* smacc2::ISmaccClientBehavior::currentState private
Definition at line 81 of file smacc_client_behavior_base.hpp.
Referenced by cl_move_group_interface::CbMoveEndEffectorTrajectory::computeJointSpaceTrajectory(), getCurrentState(), ISmaccClientBehavior(), cl_nav2z::CbPauseSlam::onEntry(), and cl_nav2z::CbResumeSlam::onEntry().
stateMachine_
ISmaccStateMachine* smacc2::ISmaccClientBehavior::stateMachine_ private
Definition at line 78 of file smacc_client_behavior_base.hpp.
Referenced by getNode(), getStateMachine(), ISmaccClientBehavior(), postEvent(), and requiresComponent().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/smacc_client_behavior_base.hpp
smacc2/include/smacc2/impl/smacc_client_behavior_impl.hpp
smacc2/src/smacc2/smacc_client_behavior_base.cpp