SMACC2: sm_dance_bot_warehouse_3::cl_nav2z::CpSquareShapeBoundary Class Reference
sm_dance_bot_warehouse_3::cl_nav2z::CpSquareShapeBoundary Class Reference
#include <cp_square_shape_bondary.hpp>
Public Member Functions
CpSquareShapeBoundary (float squareLenghtMeters)
void onInitialize () override
float getForwardDistance ()
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Attributes
float squareLenghtMeters_
::cl_nav2z::Pose * robotPose_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger () const
ISmaccStateMachine * getStateMachine ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 35 of file cp_square_shape_bondary.hpp.
Constructor & Destructor Documentation
CpSquareShapeBoundary()
sm_dance_bot_warehouse_3::cl_nav2z::CpSquareShapeBoundary::CpSquareShapeBoundary (float squareLenghtMeters) inline
Definition at line 41 of file cp_square_shape_bondary.hpp.
    : squareLenghtMeters_(squareLenghtMeters)
  {
  }
Member Function Documentation
getForwardDistance()
float sm_dance_bot_warehouse_3::cl_nav2z::CpSquareShapeBoundary::getForwardDistance () inline
Definition at line 52 of file cp_square_shape_bondary.hpp.
  {
    float currentAngle = robotPose_->getYaw();
    // warp 0 to 2pi
    while(currentAngle < 0)
    {
      currentAngle+=2*M_PI;
    }
    float side = squareLenghtMeters_/2.0;
    float fwdist = -1;
    float x,y;
    if((currentAngle > 0 && currentAngle < M_PI/4  )             // rightside
      || (currentAngle > 7*M_PI/4 && currentAngle <= 2*M_PI)     // rightside
      || (currentAngle > 3*M_PI/4 && currentAngle <= 5*M_PI/4)  // leftside
      )
    {
      float m = tan(currentAngle);
      x = side;
      y = m*x;
      fwdist = sqrt(x*x + y*y);
    }
    else if((currentAngle > M_PI/4 && currentAngle <= 3*M_PI/4)      // top side
            || (currentAngle > 5*M_PI/4 && currentAngle <= 7*M_PI/4)) // bottom side
    {
        float cotan = cos(currentAngle)/sin(currentAngle);
        y = side;
        x = cotan*y;
        fwdist = sqrt(x*x + y*y);
    }
    else
    {
      RCLCPP_FATAL_STREAM(getLogger(), "[" << getName() << " ] not implemented case");
    }
    RCLCPP_INFO_STREAM(getLogger(), "[" << getName() << " ] distance for yaw angle: " << currentAngle << " and square size: "<< squareLenghtMeters_ << " -- dist: " << fwdist <<"(x: "<< x <<" y:" << y <<")");
    return fwdist;
  }
References smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getName(), cl_nav2z::Pose::getYaw(), robotPose_, and squareLenghtMeters_.
onInitialize()
void sm_dance_bot_warehouse_3::cl_nav2z::CpSquareShapeBoundary::onInitialize () inline override virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 47 of file cp_square_shape_bondary.hpp.
  {
    requiresComponent(robotPose_);
  }
References smacc2::ISmaccComponent::requiresComponent(), and robotPose_.
Member Data Documentation
robotPose_
::cl_nav2z::Pose* sm_dance_bot_warehouse_3::cl_nav2z::CpSquareShapeBoundary::robotPose_
Definition at line 39 of file cp_square_shape_bondary.hpp.
Referenced by getForwardDistance(), and onInitialize().
squareLenghtMeters_
float sm_dance_bot_warehouse_3::cl_nav2z::CpSquareShapeBoundary::squareLenghtMeters_
Definition at line 38 of file cp_square_shape_bondary.hpp.
Referenced by getForwardDistance().
The documentation for this class was generated from the following file:
smacc2_sm_reference_library/sm_dance_bot_warehouse_3/include/sm_dance_bot_warehouse_3/clients/cl_nav2z/components/cp_square_shape_bondary.hpp