SMACC2: cl_move_group_interface::CbExecuteLastTrajectory Class Reference
cl_move_group_interface::CbExecuteLastTrajectory Class Reference
#include <cb_execute_last_trajectory.hpp>
Public Member Functions
CbExecuteLastTrajectory ()
virtual ~CbExecuteLastTrajectory ()
virtual void generateTrajectory ()
virtual void onEntry () override
Public Member Functions inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
CbMoveEndEffectorTrajectory (std::optional< std::string > tipLink=std::nullopt)
CbMoveEndEffectorTrajectory (const std::vector< geometry_msgs::msg::PoseStamped > &endEffectorTrajectory, std::optional< std::string > tipLink=std::nullopt)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual void onEntry () override
virtual void onExit () override
virtual void update () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Member Functions inherited from smacc2::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (rclcpp::Duration duration)
void executeUpdate (rclcpp::Node::SharedPtr node)
void setUpdatePeriod (rclcpp::Duration duration)
Additional Inherited Members
Public Attributes inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
std::optional< std::string > group_
std::optional< std::string > tipLink_
std::optional< bool > allowInitialTrajectoryStateJointDiscontinuity_
Protected Member Functions inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
ComputeJointTrajectoryErrorCode computeJointSpaceTrajectory (moveit_msgs::msg::RobotTrajectory &computedJointTrajectory)
void executeJointSpaceTrajectory (const moveit_msgs::msg::RobotTrajectory &computedJointTrajectory)
virtual void generateTrajectory ()=0
virtual void createMarkers ()
void getCurrentEndEffectorPose (std::string globalFrame, tf2::Stamped< tf2::Transform > &currentEndEffectorTransform)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
virtual void update ()=0
Protected Attributes inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
std::vector< geometry_msgs::msg::PoseStamped > endEffectorTrajectory_
ClMoveGroup * movegroupClient_ = nullptr
visualization_msgs::msg::MarkerArray beahiorMarkers_
Detailed Description
Definition at line 27 of file cb_execute_last_trajectory.hpp.
Constructor & Destructor Documentation
CbExecuteLastTrajectory()
cl_move_group_interface::CbExecuteLastTrajectory::CbExecuteLastTrajectory ()
Definition at line 26 of file cb_execute_last_trajectory.cpp.
{}
~CbExecuteLastTrajectory()
cl_move_group_interface::CbExecuteLastTrajectory::~CbExecuteLastTrajectory () virtual
Definition at line 28 of file cb_execute_last_trajectory.cpp.
{}
Member Function Documentation
generateTrajectory()
void cl_move_group_interface::CbExecuteLastTrajectory::generateTrajectory () virtual
Implements cl_move_group_interface::CbMoveEndEffectorTrajectory.
Definition at line 30 of file cb_execute_last_trajectory.cpp.
{}
onEntry()
void cl_move_group_interface::CbExecuteLastTrajectory::onEntry () override virtual
Reimplemented from cl_move_group_interface::CbMoveEndEffectorTrajectory.
Definition at line 32 of file cb_execute_last_trajectory.cpp.
{
  this->requiresClient(movegroupClient_);
  CpTrajectoryHistory * trajectoryHistory;
  this->requiresComponent(trajectoryHistory);
  // this->generateTrajectory();
  // endEffectorTrajectory_ =
  // if (this->endEffectorTrajectory_.size() == 0)
  // {
  //     RCLCPP_WARN_STREAM(getLogger(), "[" << smacc2::demangleSymbol(typeid(*this).name()) << "] No points in the trajectory. Skipping behavior.");
  //     return;
  // }
  //this->createMarkers();
  //markersInitialized_ = true;
  moveit_msgs::msg::RobotTrajectory trajectory;
  if (trajectoryHistory->getLastTrajectory(trajectory))
  {
    this->executeJointSpaceTrajectory(trajectory);
  }
}
References cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_move_group_interface::CpTrajectoryHistory::getLastTrajectory(), cl_move_group_interface::CbMoveEndEffectorTrajectory::movegroupClient_, smacc2::ISmaccClientBehavior::requiresClient(), and smacc2::ISmaccClientBehavior::requiresComponent().
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_execute_last_trajectory.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_execute_last_trajectory.cpp