SMACC2: smacc2::ISmaccOrthogonal Class Reference
smacc2::ISmaccOrthogonal Class Reference
#include <smacc_orthogonal.hpp>
Public Member Functions
void setStateMachine (ISmaccStateMachine *value)
ISmaccStateMachine * getStateMachine ()
void addClientBehavior (std::shared_ptr< smacc2::ISmaccClientBehavior > clientBehavior)
void runtimeConfigure ()
void onEntry ()
void onExit ()
virtual std::string getName () const
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
bool requiresClient (SmaccClientType *&storage)
const std::vector< std::shared_ptr< smacc2::ISmaccClient > > & getClients ()
const std::vector< std::shared_ptr< smacc2::ISmaccClientBehavior > > & getClientBehaviors () const
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename TClientBehavior >
TClientBehavior * getClientBehavior (int index=0)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Member Functions
virtual void onInitialize ()
void initializeClients ()
template<typename TOrthogonal , typename TClient >
void assignClientToOrthogonal (TClient *client)
Protected Attributes
std::vector< std::shared_ptr< smacc2::ISmaccClient > > clients_
Private Attributes
ISmaccStateMachine * stateMachine_
std::vector< std::shared_ptr< smacc2::ISmaccClientBehavior > > clientBehaviors_
std::mutex mutex_
Friends
class ISmaccStateMachine
Detailed Description
Definition at line 27 of file smacc_orthogonal.hpp.
Member Function Documentation
addClientBehavior()
void smacc2::ISmaccOrthogonal::addClientBehavior (std::shared_ptr< smacc2::ISmaccClientBehavior > clientBehavior)
Definition at line 49 of file orthogonal.cpp.
{
  std::lock_guard<std::mutex> lock(this->mutex_);
  if (clBehavior != nullptr)
  {
    RCLCPP_INFO(
      getLogger(), "[Orthogonal %s] adding client behavior: %s", this->getName().c_str(),
      clBehavior->getName().c_str());
    clBehavior->stateMachine_ = this->getStateMachine();
    clBehavior->currentOrthogonal = this;
    clBehavior->currentState = clBehavior->stateMachine_->getCurrentState();
    clientBehaviors_.push_back(clBehavior);
  }
  else
  {
    RCLCPP_INFO(
      getLogger(), "[orthogonal %s] no client behaviors in this state", this->getName().c_str());
  }
}
References clientBehaviors_, getLogger(), getName(), getStateMachine(), and mutex_.
assignClientToOrthogonal()
template<typename TOrthogonal , typename TClient > void smacc2::ISmaccOrthogonal::assignClientToOrthogonal (TClient * client) protected
Definition at line 82 of file smacc_orthogonal_impl.hpp.
{
  client->setStateMachine(getStateMachine());
  client->setOrthogonal(this);
  client->template onOrthogonalAllocation<TOrthogonal, TClient>();
}
References getStateMachine().
getClientBehavior()
template<typename TClientBehavior > TClientBehavior * smacc2::ISmaccOrthogonal::getClientBehavior (int index = 0)
Definition at line 91 of file smacc_orthogonal_impl.hpp.
{
  int i = 0;
  for (auto & cb : this->clientBehaviors_)
  {
    auto * ret = dynamic_cast<TClientBehavior *>(cb.get());
    if (ret != nullptr)
    {
      if (i == index)
        return ret;
      else
        i++;
    }
  }
  return nullptr;
}
References clientBehaviors_.
getClientBehaviors()
const std::vector< std::shared_ptr< smacc2::ISmaccClientBehavior > > & smacc2::ISmaccOrthogonal::getClientBehaviors () const inline
Definition at line 115 of file smacc_orthogonal_impl.hpp.
{
  return this->clientBehaviors_;
}
References clientBehaviors_.
getClients()
const std::vector< std::shared_ptr< smacc2::ISmaccClient > > & smacc2::ISmaccOrthogonal::getClients () inline
Definition at line 109 of file smacc_orthogonal_impl.hpp.
{
  return clients_;
}
References clients_.
getGlobalSMData()
template<typename T > bool smacc2::ISmaccOrthogonal::getGlobalSMData (std::string name, T & ret)
Definition at line 127 of file smacc_orthogonal_impl.hpp.
{
  return this->getStateMachine()->getGlobalSMData(name, ret);
}
References smacc2::ISmaccStateMachine::getGlobalSMData(), and getStateMachine().
getLogger()
rclcpp::Logger smacc2::ISmaccOrthogonal::getLogger () inline
Definition at line 67 of file smacc_orthogonal.hpp.
{ return getNode()->get_logger(); }
References getNode().
Referenced by addClientBehavior(), smacc2::Orthogonal< TOrthogonal >::createClient(), sm_aws_warehouse_navigation::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot_strikes_back::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot_warehouse::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot_warehouse_2::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot_warehouse_3::OrNavigation::loadWaypointsFromYaml(), sm_husky_barrel_search_1::OrNavigation::loadWaypointsFromYaml(), onEntry(), onExit(), requiresClient(), requiresComponent(), and runtimeConfigure().
getName()
std::string smacc2::ISmaccOrthogonal::getName () const virtual
Definition at line 73 of file orthogonal.cpp.
{ return demangleSymbol(typeid(*this).name()); }
References smacc2::introspection::demangleSymbol().
Referenced by addClientBehavior(), and runtimeConfigure().
getNode()
rclcpp::Node::SharedPtr smacc2::ISmaccOrthogonal::getNode ()
Definition at line 47 of file orthogonal.cpp.
{ return this->stateMachine_->getNode(); }
References smacc2::ISmaccStateMachine::getNode(), and stateMachine_.
Referenced by getLogger(), sm_aws_warehouse_navigation::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot_strikes_back::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot_warehouse::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot_warehouse_2::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot_warehouse_3::OrNavigation::loadWaypointsFromYaml(), and sm_husky_barrel_search_1::OrNavigation::loadWaypointsFromYaml().
getStateMachine()
ISmaccStateMachine * smacc2::ISmaccOrthogonal::getStateMachine () inline
Definition at line 133 of file smacc_orthogonal_impl.hpp.
{ return this->stateMachine_; }
References stateMachine_.
Referenced by addClientBehavior(), assignClientToOrthogonal(), getGlobalSMData(), requiresClient(), and setGlobalSMData().
initializeClients()
void smacc2::ISmaccOrthogonal::initializeClients () protected
Definition at line 39 of file orthogonal.cpp.
{
  for (auto & c : this->clients_)
  {
    c->initialize();
  }
}
References clients_.
Referenced by setStateMachine().
onEntry()
void smacc2::ISmaccOrthogonal::onEntry ()
Definition at line 89 of file orthogonal.cpp.
{
  std::lock_guard<std::mutex> lock(this->mutex_);
  if (clientBehaviors_.size() > 0)
  {
    for (auto & clBehavior : clientBehaviors_)
    {
      RCLCPP_INFO(
        getLogger(), "[Orthogonal %s] OnEntry, current Behavior: %s", orthogonalName, cbName);
      try
      {
        TRACEPOINT(smacc2_client_behavior_on_entry_start, statename, orthogonalName, cbName);
        clBehavior->executeOnEntry();
      }
      catch (const std::exception & e)
      {
        RCLCPP_ERROR(
          getLogger(),
          "[ClientBehavior %s] Exception on Entry - continuing with next client behavior. "
          "Exception info: "
          "%s",
          cbName, e.what());
      }
      TRACEPOINT(smacc2_client_behavior_on_entry_end, statename, orthogonalName, cbName);
    }
  }
  else
  {
    RCLCPP_INFO(
      getLogger(), "[Orthogonal %s] OnEntry -> empty orthogonal (no client behavior) ",
      orthogonalName);
  }
}
References cbName, clientBehaviors_, getLogger(), mutex_, orthogonalName, smacc2_client_behavior_on_entry_end, smacc2_client_behavior_on_entry_start, statename, and TRACEPOINT().
onExit()
void smacc2::ISmaccOrthogonal::onExit ()
Definition at line 125 of file orthogonal.cpp.
{
  std::lock_guard<std::mutex> lock(this->mutex_);
  if (clientBehaviors_.size() > 0)
  {
    for (auto & clBehavior : clientBehaviors_)
    {
      RCLCPP_INFO(
        getLogger(), "[Orthogonal %s] OnExit, current Behavior: %s", orthogonalName, cbName);
      try
      {
        TRACEPOINT(smacc2_client_behavior_on_exit_start, statename, orthogonalName, cbName);
        clBehavior->executeOnExit();
      }
      catch (const std::exception & e)
      {
        RCLCPP_ERROR(
          getLogger(),
          "[ClientBehavior %s] Exception onExit - continuing with next client behavior. Exception "
          "info: %s",
          cbName, e.what());
      }
      TRACEPOINT(smacc2_client_behavior_on_exit_end, statename, orthogonalName, cbName);
    }
    int i = 0;
    for (auto & clBehavior : clientBehaviors_)
    {
      clBehavior->dispose();
      clientBehaviors_[i] = nullptr;
    }
    clientBehaviors_.clear();
  }
  else
  {
    RCLCPP_INFO(getLogger(), "[Orthogonal %s] OnExit", orthogonalName);
  }
}
References cbName, clientBehaviors_, getLogger(), mutex_, orthogonalName, smacc2_client_behavior_on_exit_end, smacc2_client_behavior_on_exit_start, statename, and TRACEPOINT().
onInitialize()
void smacc2::ISmaccOrthogonal::onInitialize () protected virtual
Reimplemented in sm_atomic_subscribers_performance_test::OrSubscriber, $sm_name$::OrTimer, sm_advanced_recovery_1::OrKeyboard, sm_advanced_recovery_1::OrSubscriber, sm_advanced_recovery_1::OrTimer, sm_advanced_recovery_1::OrUpdatablePublisher, sm_atomic::OrTimer, sm_atomic_24hr::OrTimer, sm_atomic_hierarchy::OrTimer, sm_atomic_services::OrServices, sm_atomic_services::OrTimer, sm_autoware_avp::OrAutowareAuto, sm_autoware_avp::OrTimer, sm_aws_warehouse_navigation::OrNavigation, sm_branching::OrTimer, sm_dance_bot::OrLED, sm_dance_bot::OrNavigation, sm_dance_bot::OrObstaclePerception, sm_dance_bot::OrService3, sm_dance_bot::OrStringPublisher, sm_dance_bot::OrTemperatureSensor, sm_dance_bot::OrTimer, sm_dance_bot::OrUpdatablePublisher, sm_dance_bot_strikes_back::OrLED, sm_dance_bot_strikes_back::OrNavigation, sm_dance_bot_strikes_back::OrObstaclePerception, sm_dance_bot_strikes_back::OrService3, sm_dance_bot_strikes_back::OrStringPublisher, sm_dance_bot_strikes_back::OrTemperatureSensor, sm_dance_bot_strikes_back::OrTimer, sm_dance_bot_strikes_back::OrUpdatablePublisher, sm_dance_bot_warehouse::OrLED, sm_dance_bot_warehouse::OrNavigation, sm_dance_bot_warehouse::OrObstaclePerception, sm_dance_bot_warehouse::OrService3, sm_dance_bot_warehouse::OrStringPublisher, sm_dance_bot_warehouse::OrTemperatureSensor, sm_dance_bot_warehouse::OrTimer, sm_dance_bot_warehouse::OrUpdatablePublisher, sm_dance_bot_warehouse_2::OrLED, sm_dance_bot_warehouse_2::OrNavigation, sm_dance_bot_warehouse_2::OrObstaclePerception, sm_dance_bot_warehouse_2::OrService3, sm_dance_bot_warehouse_2::OrStringPublisher, sm_dance_bot_warehouse_2::OrTemperatureSensor, sm_dance_bot_warehouse_2::OrTimer, sm_dance_bot_warehouse_2::OrUpdatablePublisher, sm_dance_bot_warehouse_3::OrLED, sm_dance_bot_warehouse_3::OrNavigation, sm_dance_bot_warehouse_3::OrObstaclePerception, sm_dance_bot_warehouse_3::OrService3, sm_dance_bot_warehouse_3::OrStringPublisher, sm_dance_bot_warehouse_3::OrTemperatureSensor, sm_dance_bot_warehouse_3::OrTimer, sm_dance_bot_warehouse_3::OrUpdatablePublisher, sm_ferrari::OrKeyboard, sm_ferrari::OrSubscriber, sm_ferrari::OrTimer, sm_ferrari::OrUpdatablePublisher, sm_husky_barrel_search_1::OrLedArray, sm_husky_barrel_search_1::OrNavigation, sm_husky_barrel_search_1::OrPerception, sm_husky_barrel_search_1::OrPerception, sm_multi_stage_1::OrKeyboard, sm_multi_stage_1::OrSubscriber, sm_multi_stage_1::OrTimer, sm_multi_stage_1::OrUpdatablePublisher, sm_multi_ur5_sim::OrArm, sm_pack_ml::OrKeyboard, sm_pack_ml::OrSubscriber, sm_pack_ml::OrTimer, sm_pack_ml::OrUpdatablePublisher, sm_pubsub_1::OrKeyboard, sm_pubsub_1::OrSubscriber, sm_pubsub_1::OrTimer, sm_pubsub_1::OrUpdatablePublisher, sm_respira_1::OrKeyboard, sm_respira_1::OrSubscriber, sm_respira_1::OrTimer, sm_respira_1::OrUpdatablePublisher, sm_test_moveit_ur5_sim::OrArm, sm_three_some::OrKeyboard, sm_three_some::OrSubscriber, sm_three_some::OrTimer, and sm_three_some::OrUpdatablePublisher.
Definition at line 71 of file orthogonal.cpp.
{}
Referenced by setStateMachine().
requiresClient()
template<typename SmaccClientType > bool smacc2::ISmaccOrthogonal::requiresClient (SmaccClientType *& storage)
Definition at line 29 of file smacc_orthogonal_impl.hpp.
{
  for (auto & client : clients_)
  {
    storage = dynamic_cast<SmaccClientType *>(client.get());
    if (storage != nullptr) return true;
  }
  auto requiredClientName = demangledTypeName<SmaccClientType>();
  RCLCPP_WARN_STREAM(
    getLogger(), "Required client ["
                   << requiredClientName
                   << "] not found in current orthogonal. Searching in other orthogonals.");
  for (auto & orthoentry : this->getStateMachine()->getOrthogonals())
  {
    for (auto & client : orthoentry.second->getClients())
    {
      storage = dynamic_cast<SmaccClientType *>(client.get());
      if (storage != nullptr)
      {
        RCLCPP_WARN_STREAM(
          getLogger(),
          "Required client  [" << requiredClientName << "] found in other orthogonal.");
        return true;
      }
    }
  }
  RCLCPP_ERROR_STREAM(
    getLogger(), "Required client ["
                   << requiredClientName
                   << "] not found even in other orthogonals. Returning null pointer. If the "
                      "requested client is used may result in a segmentation fault.");
  return false;
}
References clients_, getLogger(), and getStateMachine().
Referenced by smacc2::ISmaccClient::requiresClient(), and smacc2::ISmaccClientBehavior::requiresClient().
requiresComponent()
template<typename SmaccComponentType > void smacc2::ISmaccOrthogonal::requiresComponent (SmaccComponentType *& storage)
Definition at line 67 of file smacc_orthogonal_impl.hpp.
{
  if (stateMachine_ == nullptr)
  {
    RCLCPP_ERROR(
      getLogger(),
      "Cannot use the requiresComponent funcionality from an orthogonal before onInitialize");
  }
  else
  {
    stateMachine_->requiresComponent(storage);
  }
}
References getLogger(), smacc2::ISmaccStateMachine::requiresComponent(), and stateMachine_.
runtimeConfigure()
void smacc2::ISmaccOrthogonal::runtimeConfigure ()
Definition at line 75 of file orthogonal.cpp.
{
  std::lock_guard<std::mutex> lock(this->mutex_);
  for (auto & clBehavior : clientBehaviors_)
  {
    RCLCPP_INFO(
      getLogger(), "[Orthogonal %s] runtimeConfigure, current Behavior: %s",
      this->getName().c_str(), clBehavior->getName().c_str());
    clBehavior->runtimeConfigure();
  }
}
References clientBehaviors_, getLogger(), getName(), and mutex_.
setGlobalSMData()
template<typename T > void smacc2::ISmaccOrthogonal::setGlobalSMData (std::string name, T value)
Definition at line 121 of file smacc_orthogonal_impl.hpp.
{
  this->getStateMachine()->setGlobalSMData(name, value);
}
References getStateMachine(), and smacc2::ISmaccStateMachine::setGlobalSMData().
setStateMachine()
void smacc2::ISmaccOrthogonal::setStateMachine (ISmaccStateMachine * value)
Definition at line 32 of file orthogonal.cpp.
{
  this->stateMachine_ = value;
  this->onInitialize();
  this->initializeClients();
}
References initializeClients(), onInitialize(), and stateMachine_.
Friends And Related Function Documentation
ISmaccStateMachine
friend class ISmaccStateMachine friend
Definition at line 83 of file smacc_orthogonal.hpp.
Member Data Documentation
clientBehaviors_
std::vector<std::shared_ptr<smacc2::ISmaccClientBehavior> > smacc2::ISmaccOrthogonal::clientBehaviors_ private
Definition at line 82 of file smacc_orthogonal.hpp.
Referenced by addClientBehavior(), getClientBehavior(), getClientBehaviors(), onEntry(), onExit(), and runtimeConfigure().
clients_
std::vector<std::shared_ptr<smacc2::ISmaccClient> > smacc2::ISmaccOrthogonal::clients_ protected
Definition at line 77 of file smacc_orthogonal.hpp.
Referenced by smacc2::Orthogonal< TOrthogonal >::createClient(), getClients(), initializeClients(), and requiresClient().
mutex_
std::mutex smacc2::ISmaccOrthogonal::mutex_ private
Definition at line 85 of file smacc_orthogonal.hpp.
Referenced by addClientBehavior(), onEntry(), onExit(), and runtimeConfigure().
stateMachine_
ISmaccStateMachine* smacc2::ISmaccOrthogonal::stateMachine_ private
Definition at line 80 of file smacc_orthogonal.hpp.
Referenced by getNode(), getStateMachine(), requiresComponent(), and setStateMachine().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/smacc_orthogonal.hpp
smacc2/include/smacc2/impl/smacc_orthogonal_impl.hpp
smacc2/src/smacc2/orthogonal.cpp