SMACC2: smacc2::client_bases::ISmaccActionClient Class Reference
smacc2::client_bases::ISmaccActionClient Class Reference abstract
#include <smacc_action_client.hpp>
Public Member Functions
ISmaccActionClient ()
virtual ~ISmaccActionClient ()
std::string getNamespace () const
virtual bool cancelGoal ()=0
virtual std::shared_ptr< rclcpp_action::ClientBase > getClientBase ()=0
virtual std::string getName () const
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void onInitialize ()
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Protected Attributes
std::string name_
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Detailed Description
Definition at line 34 of file smacc_action_client.hpp.
Constructor & Destructor Documentation
ISmaccActionClient()
smacc2::client_bases::ISmaccActionClient::ISmaccActionClient ()
Definition at line 26 of file smacc_action_client.cpp.
{}
~ISmaccActionClient()
smacc2::client_bases::ISmaccActionClient::~ISmaccActionClient () virtual
Definition at line 28 of file smacc_action_client.cpp.
{}
Member Function Documentation
cancelGoal()
virtual bool smacc2::client_bases::ISmaccActionClient::cancelGoal () pure virtual
Implemented in smacc2::client_bases::SmaccActionClientBase< ActionType >, smacc2::client_bases::SmaccActionClientBase< nav2_msgs::action::NavigateToPose >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot::action::LEDControl >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_strikes_back::action::LEDControl >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_warehouse::action::LEDControl >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_warehouse_2::action::LEDControl >, and smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_warehouse_3::action::LEDControl >.
getClientBase()
virtual std::shared_ptr< rclcpp_action::ClientBase > smacc2::client_bases::ISmaccActionClient::getClientBase () pure virtual
Implemented in smacc2::client_bases::SmaccActionClientBase< ActionType >, smacc2::client_bases::SmaccActionClientBase< nav2_msgs::action::NavigateToPose >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot::action::LEDControl >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_strikes_back::action::LEDControl >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_warehouse::action::LEDControl >, smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_warehouse_2::action::LEDControl >, and smacc2::client_bases::SmaccActionClientBase< sm_dance_bot_warehouse_3::action::LEDControl >.
Referenced by smacc2::client_behaviors::CbWaitActionServer::onEntry().
getName()
virtual std::string smacc2::client_bases::ISmaccActionClient::getName () const inline virtual
Reimplemented from smacc2::ISmaccClient.
Reimplemented in sm_dance_bot::cl_led::ClLED, sm_dance_bot_strikes_back::cl_led::ClLED, sm_dance_bot_warehouse::cl_led::ClLED, sm_dance_bot_warehouse_2::cl_led::ClLED, and sm_dance_bot_warehouse_3::cl_led::ClLED.
Definition at line 50 of file smacc_action_client.hpp.
{ return name_; }
References name_.
Referenced by smacc2::client_bases::SmaccActionClientBase< ActionType >::cancelGoal(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onResult(), cl_nav2z::CostmapSwitch::registerProxyFromDynamicReconfigureServer(), and smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal().
getNamespace()
std::string smacc2::client_bases::ISmaccActionClient::getNamespace () const inline
Definition at line 44 of file smacc_action_client.hpp.
{ return name_; }
References name_.
Referenced by smacc2::client_bases::SmaccActionClientBase< ActionType >::cancelGoal().
Member Data Documentation
name_
std::string smacc2::client_bases::ISmaccActionClient::name_ protected
Definition at line 54 of file smacc_action_client.hpp.
Referenced by getName(), getNamespace(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onInitialize(), and smacc2::client_bases::SmaccActionClientBase< ActionType >::SmaccActionClientBase().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/client_bases/smacc_action_client.hpp
smacc2/src/smacc2/client_bases/smacc_action_client.cpp