SMACC2: OdomTrackerActionServer Class Reference
OdomTrackerActionServer Class Reference
Public Member Functions
OdomTrackerActionServer ()
void execute (const OdomTrackerGoalConstPtr &goal)
void run ()
Public Attributes
std::shared_ptr< Server > as_
OdomTracker odomTracker
Detailed Description
Definition at line 30 of file odom_tracker_node.cpp.
Constructor & Destructor Documentation
OdomTrackerActionServer()
OdomTrackerActionServer::OdomTrackerActionServer () inline
Definition at line 36 of file odom_tracker_node.cpp.
: odomTracker("move_base") {}
Member Function Documentation
execute()
void OdomTrackerActionServer::execute (const OdomTrackerGoalConstPtr & goal) inline
execute()
Definition at line 43 of file odom_tracker_node.cpp.
  {
    try
    {
      switch (goal->command)
      {
        case OdomTrackerGoal::RECORD_PATH:
          odomTracker.setWorkingMode(WorkingMode::RECORD_PATH);
          break;
        case OdomTrackerGoal::CLEAR_PATH:
          odomTracker.setWorkingMode(WorkingMode::CLEAR_PATH);
          break;
        case OdomTrackerGoal::IDLE:
          odomTracker.setWorkingMode(WorkingMode::IDLE);
          break;
        case OdomTrackerGoal::START_BROADCAST_PATH:
          odomTracker.setPublishMessages(true);
          break;
        case OdomTrackerGoal::STOP_BROADCAST_PATH:
          odomTracker.setPublishMessages(false);
          break;
        case OdomTrackerGoal::PUSH_PATH:
          odomTracker.pushPath();
          break;
        case OdomTrackerGoal::POP_PATH:
          odomTracker.popPath();
          break;
        default:
          RCLCPP_ERROR(
            getLogger(), "Odom Tracker Node - Action Server execute error: incorrect command - %d",
            goal->command);
          as_->setAborted();
      }
      // never reach succeeded because were are interested in keeping the feedback alive
      as_->setSucceeded();
    }
    catch (std::exception & ex)
    {
      RCLCPP_ERROR(getLogger(), "Odom Tracker Node - Action Server execute error: %s", ex.what());
      as_->setAborted();
    }
  }
References as_, odomTracker, cl_move_base_z::odom_tracker::OdomTracker::popPath(), cl_move_base_z::odom_tracker::OdomTracker::pushPath(), cl_move_base_z::odom_tracker::OdomTracker::setPublishMessages(), and cl_move_base_z::odom_tracker::OdomTracker::setWorkingMode().
Referenced by run().
run()
void OdomTrackerActionServer::run () inline
run()
Definition at line 101 of file odom_tracker_node.cpp.
  {
    rclcpp::Node::SharedPtr n;
    RCLCPP_INFO(getLogger(), "Creating odom tracker action server");
    as_ = std::make_shared<Server>(
      n, "odom_tracker", boost::bind(&OdomTrackerActionServer::execute, this, _1), false);
    RCLCPP_INFO(getLogger(), "Starting OdomTracker Action Server");
    as_->start();
    ros::spin();
  }
References as_, and execute().
Referenced by main().
Member Data Documentation
as_
std::shared_ptr<Server> OdomTrackerActionServer::as_
Definition at line 33 of file odom_tracker_node.cpp.
Referenced by execute(), and run().
odomTracker
OdomTracker OdomTrackerActionServer::odomTracker
Definition at line 34 of file odom_tracker_node.cpp.
Referenced by execute().
The documentation for this class was generated from the following file:
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/components/odom_tracker/odom_tracker_node.cpp