SMACC2: smacc2_client_library/nav2z_client/custom_planners/nav2z_planners_common/include/nav2z_planners_common/common.hpp File Reference
common.hpp File Reference
#include <iostream>
#include <tf2_geometry_msgs/tf2_geometry_msgs.h>
#include <geometry_msgs/msg/pose_stamped.hpp>
#include <geometry_msgs/msg/twist.hpp>
#include "rclcpp_lifecycle/lifecycle_node.hpp"
Functions
std::ostream & operator<< (std::ostream &out, const geometry_msgs::msg::Twist &msg)
std::ostream & operator<< (std::ostream &out, const geometry_msgs::msg::Pose &msg)
std::ostream & operator<< (std::ostream &out, const geometry_msgs::msg::PoseStamped &msg)
std::ostream & operator<< (std::ostream &out, const geometry_msgs::msg::Point &msg)
std::ostream & operator<< (std::ostream &out, const geometry_msgs::msg::Quaternion &msg)
template<typename T >
void declareOrSet (rclcpp_lifecycle::LifecycleNode::SharedPtr &node, std::string param, T &value)
Function Documentation
declareOrSet()
template<typename T > void declareOrSet (rclcpp_lifecycle::LifecycleNode::SharedPtr & node, std::string param, T & value)
Definition at line 34 of file common.hpp.
{
  if (!node->has_parameter(param))
  {
    node->declare_parameter(param, value);
    // node->set_parameter(rclcpp::Parameter(param, value));
  }
}
Referenced by cl_nav2z::backward_local_planner::BackwardLocalPlanner::configure(), cl_nav2z::forward_local_planner::ForwardLocalPlanner::configure(), cl_nav2z::pure_spinning_local_planner::PureSpinningLocalPlanner::configure(), cl_nav2z::backward_global_planner::BackwardGlobalPlanner::configure(), and cl_nav2z::undo_path_global_planner::UndoPathGlobalPlanner::configure().
operator<<() [1/5]
std::ostream & operator<< (std::ostream & out, const geometry_msgs::msg::Point & msg)
Definition at line 52 of file common.cpp.
{
  return out << "[ " << msg.x << " " << msg.y << " " << msg.z << "]";
}
operator<<() [2/5]
std::ostream & operator<< (std::ostream & out, const geometry_msgs::msg::Pose & msg)
Definition at line 36 of file common.cpp.
{
  return out << "Position[" << msg.position << "], Orientation[" << msg.orientation << "]";
}
operator<<() [3/5]
std::ostream & operator<< (std::ostream & out, const geometry_msgs::msg::PoseStamped & msg)
Definition at line 41 of file common.cpp.
{
  return out << "[serialization geometry_msgs::msg::PoseStamped] frame_id: " << msg.header.frame_id
             << ", pose: " << msg.pose;
}
operator<<() [4/5]
std::ostream & operator<< (std::ostream & out, const geometry_msgs::msg::Quaternion & msg)
Definition at line 26 of file common.cpp.
{
  return out << " Quaternion[" << msg.x << " , " << msg.y << " , " << msg.z << ", w:" << msg.w;
}
operator<<() [5/5]
std::ostream & operator<< (std::ostream & out, const geometry_msgs::msg::Twist & msg)
Definition at line 124 of file common.cpp.
{
  out << "Twist [" << msg.linear.x << "m , " << msg.linear.y << "m , " << msg.angular.z << "rad ]";
  return out;
}