SMACC2: cl_move_group_interface Namespace Reference
cl_move_group_interface Namespace Reference
Classes
class CbAttachObject
class CbCircularPivotMotion
class CbCircularPouringMotion
class CbDetachObject
class CbEndEffectorRotate
class CbExecuteLastTrajectory
class CbMoveCartesianRelative
class CbMoveCartesianRelative2
class CbMoveEndEffector
class CbMoveEndEffectorRelative
class CbMoveEndEffectorTrajectory
class CbMoveJoints
class CbMoveKnownState
class CbMoveLastTrajectoryInitialState
class CbMoveNamedTarget
class CbUndoLastTrajectory
class CbWaitJointState
class ClMoveGroup
class CpGraspingComponent
class CpTrajectoryHistory
struct EvIncorrectInitialPosition
struct EvJointDiscontinuity
struct EvMoveGroupMotionExecutionFailed
struct EvMoveGroupMotionExecutionSucceded
struct TrajectoryHistoryEntry
Enumerations
enum class ComputeJointTrajectoryErrorCode { SUCCESS , INCORRECT_INITIAL_STATE , JOINT_TRAJECTORY_DISCONTINUITY }
Functions
std::string currentJointStatesToString (moveit::planning_interface::MoveGroupInterface &moveGroupInterface, std::map< std::string, double > &targetJoints)
geometry_msgs::msg::Point & toMsg (const tf2::Vector3 &in, geometry_msgs::msg::Point &out)
void toMsg (const tf2::Transform &in, geometry_msgs::msg::Pose &out)
void fromMsg (const geometry_msgs::msg::Point &in, tf2::Vector3 &out)
Enumeration Type Documentation
ComputeJointTrajectoryErrorCode
enum class cl_move_group_interface::ComputeJointTrajectoryErrorCode strong
Enumerator
SUCCESS
INCORRECT_INITIAL_STATE
JOINT_TRAJECTORY_DISCONTINUITY
Definition at line 43 of file cb_move_end_effector_trajectory.hpp.
{
  SUCCESS,
  INCORRECT_INITIAL_STATE,
  JOINT_TRAJECTORY_DISCONTINUITY
};
Function Documentation
currentJointStatesToString()
std::string cl_move_group_interface::currentJointStatesToString (moveit::planning_interface::MoveGroupInterface & moveGroupInterface, std::map< std::string, double > & targetJoints)
Definition at line 49 of file cb_move_joints.cpp.
{
  auto state = moveGroupInterface.getCurrentState();
  if (state == nullptr) return std::string();
  auto vnames = state->getVariableNames();
  std::stringstream ss;
  for (auto & tgj : targetJoints)
  {
    auto it = std::find(vnames.begin(), vnames.end(), tgj.first);
    auto index = std::distance(vnames.begin(), it);
    ss << tgj.first << ":" << state->getVariablePosition(index) << std::endl;
  }
  return ss.str();
}
Referenced by cl_move_group_interface::CbMoveJoints::moveJoints().
fromMsg()
void cl_move_group_interface::fromMsg (const geometry_msgs::msg::Point & in, tf2::Vector3 & out)
Definition at line 56 of file cb_pouring_motion.cpp.
{
  out = tf2::Vector3(in.x, in.y, in.z);
}
Referenced by cl_move_group_interface::CbCircularPivotMotion::computeCurrentEndEffectorPoseRelativeToPivot(), cl_nav2z::backward_local_planner::BackwardLocalPlanner::computeVelocityCommands(), cl_nav2z::forward_local_planner::ForwardLocalPlanner::computeVelocityCommands(), cl_nav2z::pure_spinning_local_planner::PureSpinningLocalPlanner::computeVelocityCommands(), cl_move_group_interface::CbMoveEndEffectorTrajectory::createMarkers(), cl_move_group_interface::CbCircularPivotMotion::createMarkers(), cl_move_group_interface::CbCircularPouringMotion::createMarkers(), cl_move_group_interface::CbCircularPivotMotion::generateTrajectory(), cl_move_group_interface::CbMoveCartesianRelative2::generateTrajectory(), cl_move_group_interface::CbCircularPouringMotion::generateTrajectory(), cl_move_group_interface::CbMoveEndEffectorTrajectory::getCurrentEndEffectorPose(), cl_move_group_interface::CbEndEffectorRotate::onEntry(), cl_nav2z::CbNavigateBackwards::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbRotate::onEntry(), cl_nav2z::CbWaitTransform::onEntry(), sm_dance_bot_warehouse_3::cl_nav2zclient::CbPureSpinning::onEntry(), cl_nav2z::Pose::update(), and cl_nav2z::Pose::waitTransformUpdate().
toMsg() [1/2]
void cl_move_group_interface::toMsg (const tf2::Transform & in, geometry_msgs::msg::Pose & out)
Definition at line 48 of file cb_pouring_motion.cpp.
{
  out.position.x = in.getOrigin().getX();
  out.position.y = in.getOrigin().getY();
  out.position.z = in.getOrigin().getZ();
  out.orientation = toMsg(in.getRotation());
}
References toMsg().
Referenced by cl_move_group_interface::CbCircularPouringMotion::createMarkers(), and cl_move_group_interface::CbCircularPouringMotion::generateTrajectory().
toMsg() [2/2]
geometry_msgs::msg::Point & cl_move_group_interface::toMsg (const tf2::Vector3 & in, geometry_msgs::msg::Point & out)
Definition at line 40 of file cb_pouring_motion.cpp.
{
  out.x = in.getX();
  out.y = in.getY();
  out.z = in.getZ();
  return out;
}
Referenced by cl_move_group_interface::CbCircularPivotMotion::computeCurrentEndEffectorPoseRelativeToPivot(), cl_move_group_interface::CbCircularPouringMotion::createMarkers(), cl_nav2z::CbNavigateGlobalPosition::execute(), cl_move_group_interface::CbCircularPivotMotion::generateTrajectory(), cl_move_group_interface::CbMoveCartesianRelative2::generateTrajectory(), cl_nav2z::makePureSpinningSubPlan(), cl_move_group_interface::CbMoveEndEffectorRelative::moveRelative(), cl_move_group_interface::CbEndEffectorRotate::onEntry(), cl_nav2z::CbAbsoluteRotate::onEntry(), cl_nav2z::CbNavigateBackwards::onEntry(), cl_nav2z::CbNavigateForward::onEntry(), cl_nav2z::CbRotate::onEntry(), cl_nav2z::backward_local_planner::BackwardLocalPlanner::resamplePrecisePlan(), cl_nav2z::WaypointNavigator::setWaypoints(), toMsg(), cl_move_base_z::CpTFListener::update(), cl_nav2z::Pose::update(), and cl_nav2z::Pose::waitTransformUpdate().