SMACC2: keyboard_server_node Namespace Reference
keyboard_server_node Namespace Reference
Classes
class KeyboardPublisher
Functions
def getKey ()
def main (args=None)
Variables
settings = termios.tcgetattr(sys.stdin)
Function Documentation
getKey()
def keyboard_server_node.getKey ()
Definition at line 30 of file keyboard_server_node.py.
def getKey():
    global settings
    tty.setraw(sys.stdin.fileno())
    select.select([sys.stdin], [], [], 0)
    key = sys.stdin.read(1)
    termios.tcsetattr(sys.stdin, termios.TCSADRAIN, settings)
    return key
References getKey().
Referenced by getKey(), and keyboard_server_node.KeyboardPublisher.timer_update().
main()
def keyboard_server_node.main (args = None)
Definition at line 63 of file keyboard_server_node.py.
def main(args=None):
    rclpy.init(args=args)
    node = KeyboardPublisher()
    rclpy.spin(node)
    # Destroy the node explicitly
    # (optional - otherwise it will be done automatically
    # when the garbage collector destroys the node object)
    node.destroy_node()
    rclpy.shutdown()
References main().
Referenced by main().
Variable Documentation
settings
keyboard_server_node.settings = termios.tcgetattr(sys.stdin)
Definition at line 27 of file keyboard_server_node.py.