SMACC2: generate_debs Namespace Reference
generate_debs Namespace Reference
Functions
def build_deb_package (workspace_source_folder, package_name, packagepath, ubuntu_version, ros_distro, already_visited)
def iterate_debian_generation (workspace_source_folder, package_names, identified_install_packages, osversion, rosversion)
def get_identified_packages (workspace_folder)
def push_debian_files (repo_owner, reponame, osname, osversion, debianfiles)
def remove_debian_files (repo_owner, reponame, osname, osversion, debianfiles)
def create_and_push_smacc_debians (osname, osversion, rosversion)
Variables
string repo_owner = "pibgeus"
rospack = rospkg.RosPack()
packages = rospack.list()
packagesl = list(packages)
parser = argparse.ArgumentParser()
help
default
type
args = parser.parse_args()
string osname = "ubuntu"
osversion = args.ubuntu_version
ros_version = args.ros_version
relative_smacc_folder = args.smacc_src_folder
workspace_folder = os.path.abspath(os.path.join(os.getcwd(), "."))
homefolder = os.getenv("HOME")
packagecloud_token_filepath = os.path.join(homefolder, ".packagecloud")
outfile = open(packagecloud_token_filepath, "w")
def smacc_debians = create_and_push_smacc_debians(osname, osversion, ros_version)
Function Documentation
build_deb_package()
def generate_debs.build_deb_package (workspace_source_folder, package_name, packagepath, ubuntu_version, ros_distro, already_visited)
Definition at line 26 of file generate_debs.py.
):
    print("-----------------------")
    print("Working folder: " + str(os.getcwd()))
    print("Building debian package: " + str(package_name))
    cmd = (
        "bloom-generate rosdebian --os-name ubuntu --os-version "
        + str(ubuntu_version)
        + " --ros-distro "
        + str(ros_distro)
        + " "
        + str(packagepath)
    )
    print(cmd)
    bloomprocess = subprocess.Popen(cmd, shell=True)
    bloomprocess.wait()
    develpackagefolder = None
    for root, dirs, files in os.walk(workspace_source_folder, topdown=False):
        if "package.xml" in files and package_name == root.split("/")[-1]:
            print(root)
            develpackagefolder = root
            break
    localpackagepath = develpackagefolder
    print("current directory:")
    print(os.getcwd())
    print("debian files:")
    print(os.listdir(""))
    # copy the debian folder generated by bloom inside the package
    shutil.move("debian", os.path.join(localpackagepath, "debian"))
    os.chdir(localpackagepath)
    fakerootprocess = subprocess.Popen("fakeroot debian/rules binary", shell=True)
    fakerootprocess.wait()
    os.chdir(localpackagepath)
    shutil.rmtree("debian")
    shutil.rmtree("obj-x86_64-linux-gnu")
    os.chdir(workspace_source_folder)
    # improve this regex
    firstregexstr = ".*ros-" + ros_distro + r"-.*\.deb"
    regexstr = ".*ros-" + ros_distro + "-" + package_name.replace("_", "-") + r".*\.deb"
    print("Finding deb package: " + str(regexstr))
    thisfolderfiles = []
    for root, dirs, files in os.walk(workspace_source_folder, topdown=False):
        thisfolderfiles = thisfolderfiles + [os.path.join(root, f) for f in files]
    debianfiles = [f for f in thisfolderfiles if re.search(firstregexstr, f)]
    print("DETECTED DEBIAN FILES:")
    print(debianfiles)
    print("VISITED DEBIAN FILES:")
    print(already_visited)
    debianfilename = [
        f for f in debianfiles if re.search(regexstr, f) and f not in already_visited
    ][0]
    print("Debian file found: ")
    print(debianfilename)
    installdebiantask = subprocess.Popen("sudo dpkg -i " + debianfilename, shell=True)
    installdebiantask.wait()
    return debianfilename
References build_deb_package().
Referenced by build_deb_package(), and iterate_debian_generation().
create_and_push_smacc_debians()
def generate_debs.create_and_push_smacc_debians (osname, osversion, rosversion)
Definition at line 175 of file generate_debs.py.
def create_and_push_smacc_debians(osname, osversion, rosversion):
    workspace_source_folder = os.path.join(workspace_folder, relative_smacc_folder)
    identified_install_packages = get_identified_packages(workspace_folder)
    smacc_manual_order_packages = [  # 'forward_global_planner',
        "smacc_msgs",
        "smacc",
        "sr_all_events_go",
        "sr_conditional",
        "sr_event_countdown",
        "keyboard_client",
        "multirole_sensor_client",
        "ros_publisher_client",
        "ros_timer_client",
        "nav2z_client",
        "forward_global_planner",
        "forward_local_planner",
        "backward_global_planner",
        "undo_path_global_planner",
        "backward_local_planner",
        "move_group_interface_client",
        "sm_atomic",
        "sm_dance_bot",
        "sm_dance_bot_strikes_back",
        "sm_moveit",
    ]
    smacc_debian_files = iterate_debian_generation(
        workspace_source_folder,
        smacc_manual_order_packages,
        identified_install_packages,
        osversion,
        rosversion,
    )
    create_repo_task = subprocess.Popen("package_cloud repository create smacc", shell=True)
    create_repo_task.wait()
    # ----- PUSHING TO SMACC --------------
    remove_debian_files(repo_owner, "smacc", osname, osversion, smacc_debian_files)
    push_debian_files(repo_owner, "smacc", osname, osversion, smacc_debian_files)
    return smacc_debian_files
References create_and_push_smacc_debians(), get_identified_packages(), iterate_debian_generation(), push_debian_files(), and remove_debian_files().
Referenced by create_and_push_smacc_debians().
get_identified_packages()
def generate_debs.get_identified_packages (workspace_folder)
Definition at line 119 of file generate_debs.py.
def get_identified_packages(workspace_folder):
    identified_install_packages = {}
    exclude_with_words = ["ridgeback", "mecanum", "catkin"]
    for pname in packagesl:
        packpath = rospack.get_path(pname)
        print(pname)
        if workspace_folder in packpath:
            if any([True for excludedword in exclude_with_words if excludedword in pname]):
                continue
            identified_install_packages[pname] = packpath
    return identified_install_packages
References get_identified_packages().
Referenced by create_and_push_smacc_debians(), and get_identified_packages().
iterate_debian_generation()
def generate_debs.iterate_debian_generation (workspace_source_folder, package_names, identified_install_packages, osversion, rosversion)
Definition at line 100 of file generate_debs.py.
):
    os.chdir(workspace_source_folder)
    debianfiles = []
    for pname in package_names:
        debianfiles.append(
            build_deb_package(
                workspace_source_folder,
                pname,
                identified_install_packages[pname],
                osversion,
                rosversion,
                debianfiles,
            )
        )
    return debianfiles
References build_deb_package(), and iterate_debian_generation().
Referenced by create_and_push_smacc_debians(), and iterate_debian_generation().
push_debian_files()
def generate_debs.push_debian_files (repo_owner, reponame, osname, osversion, debianfiles)
Definition at line 133 of file generate_debs.py.
def push_debian_files(repo_owner, reponame, osname, osversion, debianfiles):
    for debf in debianfiles:
        print("pushing debfile")
        push_debian_task = subprocess.Popen(
            "package_cloud push "
            + repo_owner
            + "/"
            + reponame
            + "/"
            + osname
            + "/"
            + osversion
            + " "
            + debf,
            shell=True,
        )
        push_debian_task.wait()
References push_debian_files().
Referenced by create_and_push_smacc_debians(), and push_debian_files().
remove_debian_files()
def generate_debs.remove_debian_files (repo_owner, reponame, osname, osversion, debianfiles)
Definition at line 152 of file generate_debs.py.
def remove_debian_files(repo_owner, reponame, osname, osversion, debianfiles):
    for debf in debianfiles:
        shortdebfile = debf.split("/")[-1]
        print("yanking debfile")
        push_debian_task = subprocess.Popen(
            "package_cloud yank "
            + repo_owner
            + "/"
            + reponame
            + "/"
            + osname
            + "/"
            + osversion
            + " "
            + shortdebfile,
            shell=True,
        )
        push_debian_task.wait()
# ------------------------ SMACC PACKAGES -----------------------
References remove_debian_files().
Referenced by create_and_push_smacc_debians(), and remove_debian_files().
Variable Documentation
args
generate_debs.args = parser.parse_args()
Definition at line 257 of file generate_debs.py.
Referenced by smacc2::ISmaccState.configure(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >.configure_orthogonal(), smacc2::Orthogonal< TOrthogonal >.createClient(), smacc2::ISmaccState.createEventGenerator(), smacc2::ISmaccState.createStateReactor(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >.static_createEventGenerator(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >.static_createStateReactor(), and smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >.static_createStateReactor_aux().
default
generate_debs.default
Definition at line 241 of file generate_debs.py.
help
generate_debs.help
Definition at line 241 of file generate_debs.py.
homefolder
generate_debs.homefolder = os.getenv("HOME")
Definition at line 275 of file generate_debs.py.
osname
string generate_debs.osname = "ubuntu"
Definition at line 261 of file generate_debs.py.
osversion
generate_debs.osversion = args.ubuntu_version
Definition at line 262 of file generate_debs.py.
outfile
generate_debs.outfile = open(packagecloud_token_filepath, "w")
Definition at line 278 of file generate_debs.py.
packagecloud_token_filepath
generate_debs.packagecloud_token_filepath = os.path.join(homefolder, ".packagecloud")
Definition at line 276 of file generate_debs.py.
packages
generate_debs.packages = rospack.list()
Definition at line 237 of file generate_debs.py.
packagesl
generate_debs.packagesl = list(packages)
Definition at line 238 of file generate_debs.py.
parser
generate_debs.parser = argparse.ArgumentParser()
Definition at line 240 of file generate_debs.py.
Referenced by cl_move_group_interface::CbMoveKnownState.loadJointStatesFromFile(), cl_nav2z::WaypointNavigator.loadWayPointsFromFile(), and cl_nav2z::WaypointNavigator.loadWayPointsFromFile2().
relative_smacc_folder
generate_debs.relative_smacc_folder = args.smacc_src_folder
Definition at line 269 of file generate_debs.py.
repo_owner
string generate_debs.repo_owner = "pibgeus"
Definition at line 232 of file generate_debs.py.
ros_version
generate_debs.ros_version = args.ros_version
Definition at line 263 of file generate_debs.py.
rospack
generate_debs.rospack = rospkg.RosPack()
Definition at line 236 of file generate_debs.py.
smacc_debians
def generate_debs.smacc_debians = create_and_push_smacc_debians(osname, osversion, ros_version)
Definition at line 282 of file generate_debs.py.
type
generate_debs.type
Definition at line 248 of file generate_debs.py.
Referenced by smacc2::ISmaccState.createStateReactor(), smacc2::client_bases::SmaccActionClientBase< ActionType >.getEventLabel(), smacc2::introspection.getTransitionType(), smacc2::state_reactors::SrAllEventsGo.onInitialized(), smacc2::state_reactors::SrEventCountdown.onInitialized(), smacc2::introspection::AddSubState.operator()(), smacc2::introspection::AddTransition.operator()(), smacc2::introspection.processSubState(), smacc2::introspection.processTransitions(), smacc2::SmaccState< MostDerived, Context, InnerInitial, historyMode >.static_createStateReactor(), and smacc2::introspection::WalkStatesExecutor< InitialStateType >.walkStates().
workspace_folder
generate_debs.workspace_folder = os.path.abspath(os.path.join(os.getcwd(), "."))
Definition at line 270 of file generate_debs.py.