SMACC2: smacc2_sm_reference_library/sm_husky_barrel_search_1/servers/opencv_perception_node/opencv_perception_node.cpp File Reference
opencv_perception_node.cpp File Reference
#include "cv_mat_sensor_msgs_image_type_adapter.hpp"
#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/image.hpp>
#include <std_msgs/msg/int32.hpp>
#include <sm_husky_barrel_search_1/msg/detected_objects.hpp>
#include <iostream>
#include <opencv2/opencv.hpp>
#include <opencv2/features2d.hpp>
#include <ament_index_cpp/get_package_share_directory.hpp>
Macros
#define DEFAULT_MIN_SATURATION 20
#define DEFAULT_MIN_VALUE 20
#define DEFAULT_MIN_BLOB_AREA 20
Functions
void segmentColor (const cv::Mat &inputRGB, int hueMean, int hueWindow, cv::Mat &out, int minSaturation=20, int minValue=20, bool imgShow=false)
int testImage (cv::Mat &input, cv::Mat &debugImage, std::vector< sm_husky_barrel_search_1::msg::DetectedObject > &detectedObjects, std::string colorName, int hueMean, int hueWindow, std::string message="", int minSaturation=DEFAULT_MIN_SATURATION, int minValue=DEFAULT_MIN_VALUE, int minBlobArea=DEFAULT_MIN_BLOB_AREA, bool imgShow=false)
int testRed (cv::Mat &input, cv::Mat &debugImage, std::vector< sm_husky_barrel_search_1::msg::DetectedObject > &detectedObjects, bool imShow=false)
int testBlue (cv::Mat &input, cv::Mat &debugImage, std::vector< sm_husky_barrel_search_1::msg::DetectedObject > &detectedObjects, bool imShow=false)
int testGreen (cv::Mat &input, cv::Mat &debugImage, std::vector< sm_husky_barrel_search_1::msg::DetectedObject > &detectedObjects, bool imShow=false)
int testYellow (cv::Mat &input, cv::Mat &debugImage, std::vector< sm_husky_barrel_search_1::msg::DetectedObject > &detectedObjects, bool imShow=false)
void testYellowFile (std::string path)
void testRedFile (std::string path)
void testRedFileBench (std::string path)
void testBlueFile (std::string path, cv::Mat &debugImage)
void testGreenFile (std::string path, cv::Mat &debugImage)
int encoding2mat_type (const std::string &encoding)
cv::Mat to_cv_mat (const sensor_msgs::msg::Image &img)
void callback (const sensor_msgs::msg::Image &imgMsg)
void main_ros_loop (int argc, char **argv)
int main (int argc, char **argv)
Variables
rclcpp::Publisher< sm_husky_barrel_search_1::msg::DetectedObjects >::SharedPtr detectionPub
rclcpp::Publisher< sensor_msgs::msg::Image >::SharedPtr debugImagePub
rclcpp::Subscription< sensor_msgs::msg::Image >::SharedPtr imageSub
Macro Definition Documentation
DEFAULT_MIN_BLOB_AREA
#define DEFAULT_MIN_BLOB_AREA 20
Definition at line 69 of file opencv_perception_node.cpp.
DEFAULT_MIN_SATURATION
#define DEFAULT_MIN_SATURATION 20
Definition at line 67 of file opencv_perception_node.cpp.
DEFAULT_MIN_VALUE
#define DEFAULT_MIN_VALUE 20
Definition at line 68 of file opencv_perception_node.cpp.
Function Documentation
callback()
void callback (const sensor_msgs::msg::Image & imgMsg)
Definition at line 298 of file opencv_perception_node.cpp.
{
  cv::Mat image = to_cv_mat(imgMsg);
  // BUG: for some reason we get an image message from gazebo with as RGB but in practice we see it is BGR
  cv::cvtColor(image, image, cv::COLOR_BGR2RGB);
  sensor_msgs::msg::Image outimg = imgMsg;
  // cv::cvtColor(image, image, cv::COLOR_RGB2BGR);
  auto outmat = to_cv_mat(outimg);
  // USED TO WORK IN FILE MODE
  // cv::imwrite("/tmp/out.png", outmat);
  bool testGreenAlly = false;
  std::vector<sm_husky_barrel_search_1::msg::DetectedObject> detectedObjects;
  int detectedColor = 0;
  if (testRed(image, outmat, detectedObjects) > 0)
  {
    detectedColor = 1;
  }
  if (testGreenAlly && testGreen(image, outmat, detectedObjects) > 0)
  {
    detectedColor = 2;
  }
  if (testBlue(image, outmat, detectedObjects) > 0)
  {
    detectedColor = 3;
  }
  if (testYellow(image, outmat, detectedObjects) > 0)
  {
    detectedColor = 4;
  }
  sm_husky_barrel_search_1::msg::DetectedObjects detectedColorMsg;
  detectedColorMsg.detected_objects = detectedObjects;
  detectionPub->publish(detectedColorMsg);
  cv::cvtColor(outmat, outmat, cv::COLOR_RGB2BGR);
  outimg.header = imgMsg.header;
  debugImagePub->publish(outimg);
}
References debugImagePub, detectionPub, testBlue(), testGreen(), testRed(), testYellow(), and to_cv_mat().
Referenced by smacc2::utils::Bind< 1 >::bindaux(), smacc2::utils::Bind< 2 >::bindaux(), smacc2::utils::Bind< 3 >::bindaux(), smacc2::utils::Bind< 4 >::bindaux(), smacc2::introspection::EventGeneratorHandler::configureEventGenerator(), smacc2::introspection::StateReactorHandler::configureStateReactor(), smacc2::ISmaccClient::connectSignal(), smacc2::StateReactor::createEventCallback(), smacc2::ISmaccStateMachine::createSignalConnection(), main_ros_loop(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onAborted(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onCancelled(), smacc2::components::CpTopicSubscriber< MessageType >::onFirstMessageReceived(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onFirstMessageReceived(), cl_keyboard::ClKeyboard::OnKeyPress(), smacc2::components::CpTopicSubscriber< MessageType >::onMessageReceived(), smacc2::client_bases::SmaccSubscriberClient< MessageType >::onMessageReceived(), cl_multirole_sensor::ClMultiroleSensor< MessageType >::onMessageTimeout(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), and smacc2::state_reactors::SrConditional< TEv >::SrConditional().
encoding2mat_type()
int encoding2mat_type (const std::string & encoding)
Definition at line 252 of file opencv_perception_node.cpp.
{
  if (encoding == "mono8")
  {
    return CV_8UC1;
  }
  else if (encoding == "bgr8")
  {
    return CV_8UC3;
  }
  else if (encoding == "mono16")
  {
    return CV_16SC1;
  }
  else if (encoding == "rgba8")
  {
    return CV_8UC4;
  }
  else if (encoding == "bgra8")
  {
    return CV_8UC4;
  }
  else if (encoding == "32FC1")
  {
    return CV_32FC1;
  }
  else if (encoding == "rgb8")
  {
    return CV_8UC3;
  }
  else if (encoding == "yuv422")
  {
    return CV_8UC2;
  }
  else
  {
    throw std::runtime_error("Unsupported encoding type");
  }
}
Referenced by to_cv_mat().
main()
int main (int argc, char ** argv)
Definition at line 367 of file opencv_perception_node.cpp.
{
  main_ros_loop(argc, argv);
  auto testImagePath =
      ament_index_cpp::get_package_share_directory("sm_husky_barrel_search_1") + "/test_images/red4.png";
  // testRedFileBench(testImagePath);
  // testRedFile(testImagePath);
  /*
  testRedFile("../../red1.png");
  testRedFile("../../green1.png");
  testRedFile("../../blue1.png");
  testGreen("../../red1.png");
  testGreen("../../green1.png");
  testGreen("../../blue1.png");
  testGreen("../../red2.png");
  testBlue("../../red1.png");
  testBlue("../../green1.png");
  testBlue("../../blue1.png");
  testBlue("../../red2.png");
  */
}
References main_ros_loop().
main_ros_loop()
void main_ros_loop (int argc, char ** argv)
Definition at line 348 of file opencv_perception_node.cpp.
{
  rclcpp::init(argc, argv);
  rclcpp::Node::SharedPtr nh = rclcpp::Node::make_shared("opencv_perception_node");
  RCLCPP_INFO(nh->get_logger(), "opencv perception node started");
  detectionPub = nh->create_publisher<sm_husky_barrel_search_1::msg::DetectedObjects>("detected_objects", 1);
  imageSub = nh->create_subscription<sensor_msgs::msg::Image>("/image_raw", rclcpp::QoS(1).best_effort(), callback);
  debugImagePub = nh->create_publisher<sensor_msgs::msg::Image>("/opencv_debug_image", rclcpp::QoS(1).best_effort());
  rclcpp::Rate r(10);
  while (rclcpp::ok())
  {
    rclcpp::spin_some(nh);
    r.sleep();
  }
}
References callback(), debugImagePub, detectionPub, imageSub, and nh.
Referenced by main().
segmentColor()
void segmentColor (const cv::Mat & inputRGB, int hueMean, int hueWindow, cv::Mat & out, int minSaturation = 20, int minValue = 20, bool imgShow = false)
Definition at line 51 of file opencv_perception_node.cpp.
{
  cv::Mat hsvInput;
  cv::cvtColor(inputRGB, hsvInput, cv::COLOR_RGB2HSV);
  cv::inRange(hsvInput, cv::Scalar(hueMean - hueWindow, minSaturation, minValue),
              cv::Scalar(hueMean + hueWindow, 255, 255), out);
  cv::threshold(out, out, 100, 255, cv::THRESH_BINARY);
  if (imgShow)
  {
    cv::imshow("segment", out);
    cv::waitKey();
  }
}
Referenced by testImage().
testBlue()
int testBlue (cv::Mat & input, cv::Mat & debugImage, std::vector< sm_husky_barrel_search_1::msg::DetectedObject > & detectedObjects, bool imShow = false)
Definition at line 168 of file opencv_perception_node.cpp.
{
  return testImage(input, debugImage, detectedObjects, "blue", 10, 10, "blue-barrel", DEFAULT_MIN_SATURATION,
                   DEFAULT_MIN_VALUE, DEFAULT_MIN_BLOB_AREA, imShow);
}
References DEFAULT_MIN_BLOB_AREA, DEFAULT_MIN_SATURATION, DEFAULT_MIN_VALUE, and testImage().
Referenced by callback().
testBlueFile()
void testBlueFile (std::string path, cv::Mat & debugImage)
Definition at line 238 of file opencv_perception_node.cpp.
{
  cv::Mat input = cv::imread(path);
  std::vector<sm_husky_barrel_search_1::msg::DetectedObject> detectedObjects;
  testImage(input, debugImage, detectedObjects, "blue", 10, 10, "");
}
References testImage().
testGreen()
int testGreen (cv::Mat & input, cv::Mat & debugImage, std::vector< sm_husky_barrel_search_1::msg::DetectedObject > & detectedObjects, bool imShow = false)
Definition at line 174 of file opencv_perception_node.cpp.
{
  return testImage(input, debugImage, detectedObjects, "green", 50, 10, "ally", DEFAULT_MIN_SATURATION,
                   DEFAULT_MIN_VALUE, DEFAULT_MIN_BLOB_AREA, imShow);
}
References DEFAULT_MIN_BLOB_AREA, DEFAULT_MIN_SATURATION, DEFAULT_MIN_VALUE, and testImage().
Referenced by callback().
testGreenFile()
void testGreenFile (std::string path, cv::Mat & debugImage)
Definition at line 245 of file opencv_perception_node.cpp.
{
  cv::Mat input = cv::imread(path);
  std::vector<sm_husky_barrel_search_1::msg::DetectedObject> detectedObjects;
  testImage(input, debugImage, detectedObjects, "green", 50, 10, "");
}
References testImage().
testImage()
int testImage (cv::Mat & input, cv::Mat & debugImage, std::vector< sm_husky_barrel_search_1::msg::DetectedObject > & detectedObjects, std::string colorName, int hueMean, int hueWindow, std::string message = "", int minSaturation = DEFAULT_MIN_SATURATION, int minValue = DEFAULT_MIN_VALUE, int minBlobArea = DEFAULT_MIN_BLOB_AREA, bool imgShow = false)
Definition at line 71 of file opencv_perception_node.cpp.
{
  cv::Mat segmented;
  segmentColor(input, hueMean, hueWindow, segmented, minSaturation, minValue, imgShow);
  std::vector<std::vector<cv::Point> > contours;
  std::vector<cv::Vec4i> hierarchy;
  cv::Mat contourOutput = segmented.clone();
  cv::findContours(contourOutput, contours, hierarchy, cv::RETR_TREE, cv::CHAIN_APPROX_NONE);
  int foundCount = 0;
  cv::Mat contourImage(segmented.size(), CV_8UC3, cv::Scalar(0, 0, 0));
  for (size_t idx = 0; idx < contours.size(); idx++)
  {
    auto currentCountour = contours[idx];
    auto area = cv::contourArea(currentCountour);
    auto currentHierarchy = hierarchy[idx];
    if (area > minBlobArea && currentHierarchy[3] < 0)
    {
      foundCount++;
      auto r = cv::boundingRect(currentCountour);
      cv::drawContours(contourImage, contours, idx, cv::Scalar(255, 0, 0), 1, cv::LINE_8, hierarchy, 0);
      cv::drawContours(debugImage, contours, idx, cv::Scalar(255, 0, 0), 1, cv::LINE_8, hierarchy, 0);
      cv::rectangle(debugImage, r, cv::Scalar(255, 0, 0), 1);
      cv::putText(debugImage, message, cv::Point(r.x, r.y), cv::FONT_HERSHEY_SIMPLEX, 0.3, cv::Vec3b(255, 255, 255));
      sm_husky_barrel_search_1::msg::DetectedObject detectedObject;
      detectedObject.name = message;
      detectedObject.blob_area = area;
      detectedObjects.push_back(detectedObject);
    }
  }
  if (imgShow)
  {
    cv::imshow("contours", contourImage);
    cv::imshow("debugImage", debugImage);
  }
  return foundCount;
  // cv::SimpleBlobDetector::Params params;
  // // params.filterByArea= true;
  // // params.minArea = 10;
  // params.filterByArea = true;
  // params.minArea = minBlobArea;
  // params.maxArea = 100000;
  // params.filterByColor = false;
  // params.blobColor = 255;
  // auto blobDetector = cv::SimpleBlobDetector::create(params);
  // std::vector<cv::KeyPoint> blobs;
  // blobDetector->detect(segmented, blobs);
  // // std::cout << "-------" << std::endl;
  // for (auto& b : blobs)
  // {
  //   std::cout << "-blob " << colorName << " detected: " << b.size << std::endl;
  // }
  // if (!blobs.empty())
  // {
  //   for (auto& b : blobs)
  //   {
  //     cv::Rect r;
  //     float diameter = b.size;
  //     auto radius = diameter * 0.5;
  //     r.x = b.pt.x - radius;
  //     r.y = b.pt.y - radius;
  //     r.width = diameter;
  //     r.height = diameter;
  //     cv::rectangle(debugImage, r, cv::Scalar(255, 0, 0), 1);
  //     cv::putText(debugImage, message, cv::Point(r.x, r.y), cv::FONT_HERSHEY_SIMPLEX, 0.3, cv::Vec3b(255, 255, 255));
  //   }
  // }
  // return blobs.size();
}
References segmentColor().
Referenced by testBlue(), testBlueFile(), testGreen(), testGreenFile(), testRed(), testRedFileBench(), and testYellow().
testRed()
int testRed (cv::Mat & input, cv::Mat & debugImage, std::vector< sm_husky_barrel_search_1::msg::DetectedObject > & detectedObjects, bool imShow = false)
Definition at line 158 of file opencv_perception_node.cpp.
{
  return testImage(input, debugImage, detectedObjects, "red", 130, 20, "enemy", DEFAULT_MIN_SATURATION,
                   DEFAULT_MIN_VALUE, DEFAULT_MIN_BLOB_AREA, imShow);
  // RGB
  // return testImage(input, debugImage, "red", 10, 10, "enemy", DEFAULT_MIN_SATURATION, DEFAULT_MIN_VALUE,
  // DEFAULT_MIN_BLOB_AREA, imShow);
}
References DEFAULT_MIN_BLOB_AREA, DEFAULT_MIN_SATURATION, DEFAULT_MIN_VALUE, and testImage().
Referenced by callback(), and testRedFile().
testRedFile()
void testRedFile (std::string path)
Definition at line 203 of file opencv_perception_node.cpp.
{
  cv::Mat input = cv::imread(path);
  std::vector<sm_husky_barrel_search_1::msg::DetectedObject> detectedObjects;
  cv::Mat debugImage = input.clone();
  bool imShow = true;
  testRed(input, debugImage, detectedObjects, imShow);
  cv::imshow("red filter - " + path, debugImage);
  cv::waitKey();
}
References testRed().
testRedFileBench()
void testRedFileBench (std::string path)
Definition at line 216 of file opencv_perception_node.cpp.
{
  cv::Mat input = cv::imread(path);
  std::vector<sm_husky_barrel_search_1::msg::DetectedObject> detectedObjects;
  // cv::cvtColor(input, input, cv::COLOR_RGB2BGR);
  cv::Mat debugImage = input.clone();
  bool imShow = true;
  int size = 60;
  int step = 5;
  for (int i = 0; i < 255; i++)
  {
    auto huevalue = i;
    std::cout << "huevalue: " << huevalue << std::endl;
    testImage(input, debugImage, detectedObjects, "red", huevalue, 20, "red", DEFAULT_MIN_SATURATION, DEFAULT_MIN_VALUE,
              DEFAULT_MIN_BLOB_AREA, imShow);
    cv::imshow("red filter - " + path, debugImage);
    cv::waitKey();
  }
}
References DEFAULT_MIN_BLOB_AREA, DEFAULT_MIN_SATURATION, DEFAULT_MIN_VALUE, and testImage().
testYellow()
int testYellow (cv::Mat & input, cv::Mat & debugImage, std::vector< sm_husky_barrel_search_1::msg::DetectedObject > & detectedObjects, bool imShow = false)
Definition at line 180 of file opencv_perception_node.cpp.
{
  // hue: 31 , minvalue: 200, minsat: 40, in rgb
  // return testImage(input, debugImage, "yellow", 31, 10, "mine", 40, 200, 100, imShow);
  // return testImage(input, debugImage, "yellow", 195, 40, "mine", 40, 20, 100, imShow);
  return testImage(input, debugImage, detectedObjects, "yellow", 90, 10, "mine", 40, 200, 100, imShow);
}
References testImage().
Referenced by callback(), and testYellowFile().
testYellowFile()
void testYellowFile (std::string path)
Definition at line 189 of file opencv_perception_node.cpp.
{
  cv::Mat input;
  cv::cvtColor(cv::imread(path), input, cv::COLOR_RGB2BGR);
  std::vector<sm_husky_barrel_search_1::msg::DetectedObject> detectedObjects;
  cv::Mat debugImage = input.clone();
  testYellow(input, debugImage, detectedObjects, true);
  cv::imshow("yellow filter - " + path, debugImage);
  cv::waitKey();
}
References testYellow().
to_cv_mat()
cv::Mat to_cv_mat (const sensor_msgs::msg::Image & img)
Definition at line 292 of file opencv_perception_node.cpp.
{
  return cv::Mat(cv::Size(img.width, img.height), encoding2mat_type(img.encoding),
                 const_cast<unsigned char*>(img.data.data()));
}
References encoding2mat_type().
Referenced by callback().
Variable Documentation
debugImagePub
rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr debugImagePub
Definition at line 48 of file opencv_perception_node.cpp.
Referenced by callback(), and main_ros_loop().
detectionPub
rclcpp::Publisher<sm_husky_barrel_search_1::msg::DetectedObjects>::SharedPtr detectionPub
Definition at line 47 of file opencv_perception_node.cpp.
Referenced by callback(), and main_ros_loop().
imageSub
rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr imageSub
Definition at line 49 of file opencv_perception_node.cpp.
Referenced by main_ros_loop().