SMACC2: sm_ferrari::StState2 Struct Reference
sm_ferrari::StState2 Struct Reference
#include <st_state_2.hpp>
Classes
struct NEXT
struct PREVIOUS
struct TIMEOUT
Public Types
typedef mpl::list< Transition< EvKeyPressP< CbDefaultKeyboardBehavior, OrKeyboard >, StState1, PREVIOUS >, Transition< EvKeyPressN< CbDefaultKeyboardBehavior, OrKeyboard >, StState3, NEXT >, Transition< EvMyBehavior< CbMySubscriberBehavior, OrSubscriber >, StState3, NEXT >, Transition< EvTrue< EgConditionalGenerator, StState2 >, StState3, NEXT > > reactions
Public Types inherited from smacc2::SmaccState< StState2, MsRun >
typedef MsRun TContext
typedef Context::inner_context_type context_type
typedef context_type::state_iterator state_iterator
typedef mpl::list<> LastDeepState
typedef base_type::outermost_context_base_type outermost_context_base_type
typedef base_type::inner_context_ptr_type inner_context_ptr_type
typedef base_type::context_ptr_type context_ptr_type
typedef base_type::inner_initial_list inner_initial_list
Public Member Functions
void runtimeConfigure ()
bool eventGeneratorPredicate (ISmaccState *st)
void update () override
void onEntry ()
void onExit ()
Public Member Functions inherited from smacc2::SmaccState< StState2, MsRun >
SmaccState ()=delete
SmaccState (my_context ctx)
virtual ~SmaccState ()
const smacc2::introspection::SmaccStateInfo * getStateInfo ()
std::string getName () override
std::string getFullName ()
std::string getShortName ()
virtual ISmaccState * getParentState ()
void exit ()
void runtimeConfigure ()
void onEntry ()
void onExit ()
bool getGlobalSMData (std::string name, T &ret)
void setGlobalSMData (std::string name, T value)
void requiresComponent (SmaccComponentType *&storage)
virtual ISmaccStateMachine & getStateMachine ()
void checkWhileLoopConditionAndThrowEvent (bool(MostDerived::*conditionFn)())
void throwSequenceFinishedEvent ()
Public Member Functions inherited from smacc2::ISmaccState
virtual ISmaccStateMachine & getStateMachine ()=0
virtual std::string getName ()=0
ISmaccState * getParentState ()
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc2::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TOrthogonal , typename TClientBehavior >
TClientBehavior * getClientBehavior ()
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Public Member Functions inherited from smacc2::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (rclcpp::Duration duration)
void executeUpdate (rclcpp::Node::SharedPtr node)
void setUpdatePeriod (rclcpp::Duration duration)
Static Public Member Functions
static void staticConfigure ()
Static Public Member Functions inherited from smacc2::SmaccState< StState2, MsRun >
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh, StState2 &)> initializationFunction)
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh)> initializationFunction)
static void configure_orthogonal (Args &&... args)
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor (TArgs... args)
static std::shared_ptr< smacc2::introspection::EventGeneratorHandler > static_createEventGenerator (TUArgs... args)
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor_aux (TUArgs... args)
static void initial_deep_construct (outermost_context_base_type &outermostContextBase)
static void deep_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
static inner_context_ptr_type shallow_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
Static Public Attributes
static int k = 0
Additional Inherited Members
Public Attributes inherited from smacc2::SmaccState< StState2, MsRun >
bool finishStateThrown
mpl::list<> * smacc_inner_type
virtual void update ()=0
Protected Attributes inherited from smacc2::ISmaccState
rclcpp::Node::SharedPtr node_
std::shared_ptr< rclcpp::Logger > logger_
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc2::SmaccEventGenerator > > eventGenerators_
ISmaccState * parentState_
const smacc2::introspection::SmaccStateInfo * stateInfo_
Detailed Description
Definition at line 20 of file st_state_2.hpp.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvKeyPressP<CbDefaultKeyboardBehavior, OrKeyboard>, StState1, PREVIOUS>, Transition<EvKeyPressN<CbDefaultKeyboardBehavior, OrKeyboard>, StState3, NEXT>, Transition<EvMyBehavior<CbMySubscriberBehavior, OrSubscriber>, StState3, NEXT>, Transition<EvTrue<EgConditionalGenerator, StState2>, StState3, NEXT> > sm_ferrari::StState2::reactions
Definition at line 40 of file st_state_2.hpp.
Member Function Documentation
eventGeneratorPredicate()
bool sm_ferrari::StState2::eventGeneratorPredicate (ISmaccState * st) inline
Definition at line 71 of file st_state_2.hpp.
  {
    auto res = k > 300;
    RCLCPP_INFO(st->getLogger(), "[State2] checking k: %d  > 300 == %d", k, res);
    rclcpp::sleep_for(10ms);
    // rclcpp::Duration(10ms).sleep();
    return res;
  }
References k.
Referenced by runtimeConfigure().
onEntry()
void sm_ferrari::StState2::onEntry () inline
Definition at line 86 of file st_state_2.hpp.
{ RCLCPP_INFO(getLogger(), "On Entry!"); }
References smacc2::ISmaccState::getLogger().
onExit()
void sm_ferrari::StState2::onExit () inline
Definition at line 88 of file st_state_2.hpp.
{ RCLCPP_INFO(getLogger(), "On Exit!"); }
References smacc2::ISmaccState::getLogger().
runtimeConfigure()
void sm_ferrari::StState2::runtimeConfigure () inline
Definition at line 63 of file st_state_2.hpp.
  {
    k = 0;
    auto eg = this->getEventGenerator<EgConditionalGenerator>();
    eg->setPredicateFunction([=] { return this->eventGeneratorPredicate(this); });
  }
References eventGeneratorPredicate(), and k.
staticConfigure()
static void sm_ferrari::StState2::staticConfigure () inline static
Definition at line 45 of file st_state_2.hpp.
  {
    // configure_orthogonal<OrTimer, CbTimerCountdownOnce>(10);
    // configure_orthogonal<OrSubscriber, CbWatchdogSubscriberBehavior>();
    configure_orthogonal<OrSubscriber, CbMySubscriberBehavior>();
    // configure_orthogonal<OrUpdatablePublisher, CbDefaultPublishLoop>();
    configure_orthogonal<OrKeyboard, CbDefaultKeyboardBehavior>();
    // Create State Reactor
    // auto sbAll = static_createStateReactor<SrAllEventsGo>();
    // sbAll->addInputEvent<EvKeyPressA<CbDefaultKeyboardBehavior, OrKeyboard>>();
    // sbAll->addInputEvent<EvKeyPressB<CbDefaultKeyboardBehavior, OrKeyboard>>();
    // sbAll->addInputEvent<EvKeyPressC<CbDefaultKeyboardBehavior, OrKeyboard>>();
    // sbAll->setOutputEvent<EvAllGo<SrAllEventsGo>>();
    static_createEventGenerator<EgConditionalGenerator>(ConditionalGeneratorMode::ON_UPDATE);
  }
update()
void sm_ferrari::StState2::update () inline override virtual
Implements smacc2::ISmaccUpdatable.
Definition at line 80 of file st_state_2.hpp.
  {
    k++;
    RCLCPP_INFO(getLogger(), "[State2] internally updating k: %d", k);
  }
References smacc2::ISmaccState::getLogger(), and k.
Member Data Documentation
k
int sm_ferrari::StState2::k = 0 static
Definition at line 42 of file st_state_2.hpp.
Referenced by eventGeneratorPredicate(), runtimeConfigure(), and update().
The documentation for this struct was generated from the following file:
smacc2_sm_reference_library/sm_ferrari/include/sm_ferrari/states/st_state_2.hpp