SMACC2: smacc2::introspection::SmaccEventInfo Struct Reference
smacc2::introspection::SmaccEventInfo Struct Reference
#include <smacc_state_info.hpp>
Public Member Functions
SmaccEventInfo (std::shared_ptr< TypeInfo > eventType)
std::string getEventTypeName ()
std::string getEventSourceName ()
std::string getOrthogonalName ()
Public Attributes
std::string label
std::shared_ptr< TypeInfo > eventType
Detailed Description
Definition at line 41 of file smacc_state_info.hpp.
Constructor & Destructor Documentation
SmaccEventInfo()
smacc2::SmaccEventInfo::SmaccEventInfo (std::shared_ptr< TypeInfo > eventType)
Definition at line 93 of file smacc_state_info.cpp.
{ this->eventType = eventType; }
References eventType.
Member Function Documentation
getEventSourceName()
std::string smacc2::SmaccEventInfo::getEventSourceName ()
Definition at line 95 of file smacc_state_info.cpp.
{
  if (eventType->templateParameters.size() > 0)
  {
    auto eventsourcename = demangleSymbol(eventType->templateParameters[0]->getFullName().c_str());
    return eventsourcename;
  }
  else
  {
    return "";
  }
}
References smacc2::introspection::demangleSymbol(), and eventType.
getEventTypeName()
std::string smacc2::SmaccEventInfo::getEventTypeName ()
Definition at line 108 of file smacc_state_info.cpp.
{
  return demangleSymbol(eventType->getNonTemplatedTypeName().c_str());
}
References smacc2::introspection::demangleSymbol(), and eventType.
getOrthogonalName()
std::string smacc2::SmaccEventInfo::getOrthogonalName ()
Definition at line 113 of file smacc_state_info.cpp.
{
  if (eventType->templateParameters.size() > 1)
  {
    return demangleSymbol(eventType->templateParameters[1]->getFullName().c_str());
  }
  else
  {
    return "";
  }
}
References smacc2::introspection::demangleSymbol(), and eventType.
Member Data Documentation
eventType
std::shared_ptr<TypeInfo> smacc2::introspection::SmaccEventInfo::eventType
Definition at line 54 of file smacc_state_info.hpp.
Referenced by getEventSourceName(), getEventTypeName(), getOrthogonalName(), and SmaccEventInfo().
label
std::string smacc2::introspection::SmaccEventInfo::label
Definition at line 52 of file smacc_state_info.hpp.
The documentation for this struct was generated from the following files:
smacc2/include/smacc2/introspection/smacc_state_info.hpp
smacc2/src/smacc2/smacc_state_info.cpp