SMACC2: sm_pack_ml::CompletingSequenceBLoop Struct Reference
sm_pack_ml::CompletingSequenceBLoop Struct Reference
#include <completing_sequence_b_loop.hpp>
Public Types
typedef mpl::list< Transition< EvLoopContinue< CompletingSequenceBLoop >, SsCompletingSequenceB, CONTINUELOOP > > reactions
Public Types inherited from smacc2::SmaccState< CompletingSequenceBLoop, MsCompleting >
typedef MsCompleting TContext
typedef Context::inner_context_type context_type
typedef context_type::state_iterator state_iterator
typedef mpl::list<> LastDeepState
typedef base_type::outermost_context_base_type outermost_context_base_type
typedef base_type::inner_context_ptr_type inner_context_ptr_type
typedef base_type::context_ptr_type context_ptr_type
typedef base_type::inner_initial_list inner_initial_list
Public Member Functions
void runtimeConfigure ()
bool loopWhileCondition ()
void onEntry ()
Public Member Functions inherited from smacc2::SmaccState< CompletingSequenceBLoop, MsCompleting >
SmaccState ()=delete
SmaccState (my_context ctx)
virtual ~SmaccState ()
const smacc2::introspection::SmaccStateInfo * getStateInfo ()
std::string getName () override
std::string getFullName ()
std::string getShortName ()
virtual ISmaccState * getParentState ()
void exit ()
void runtimeConfigure ()
void onEntry ()
void onExit ()
bool getGlobalSMData (std::string name, T &ret)
void setGlobalSMData (std::string name, T value)
void requiresComponent (SmaccComponentType *&storage)
virtual ISmaccStateMachine & getStateMachine ()
void checkWhileLoopConditionAndThrowEvent (bool(MostDerived::*conditionFn)())
void throwSequenceFinishedEvent ()
Public Member Functions inherited from smacc2::ISmaccState
virtual ISmaccStateMachine & getStateMachine ()=0
virtual std::string getName ()=0
ISmaccState * getParentState ()
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc2::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TOrthogonal , typename TClientBehavior >
TClientBehavior * getClientBehavior (int index=0)
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Static Public Member Functions
static void staticConfigure ()
Static Public Member Functions inherited from smacc2::SmaccState< CompletingSequenceBLoop, MsCompleting >
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh, CompletingSequenceBLoop &)> initializationFunction)
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh)> initializationFunction)
static void configure_orthogonal (Args &&... args)
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor (TArgs... args)
static std::shared_ptr< smacc2::introspection::EventGeneratorHandler > static_createEventGenerator (TUArgs... args)
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor_aux (TUArgs... args)
static void initial_deep_construct (outermost_context_base_type &outermostContextBase)
static void deep_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
static inner_context_ptr_type shallow_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
Additional Inherited Members
Public Attributes inherited from smacc2::SmaccState< CompletingSequenceBLoop, MsCompleting >
bool finishStateThrown
mpl::list<> * smacc_inner_type
Protected Attributes inherited from smacc2::ISmaccState
rclcpp::Node::SharedPtr node_
std::shared_ptr< rclcpp::Logger > logger_
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc2::SmaccEventGenerator > > eventGenerators_
ISmaccState * parentState_
const smacc2::introspection::SmaccStateInfo * stateInfo_
Detailed Description
Definition at line 19 of file completing_sequence_b_loop.hpp.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvLoopContinue<CompletingSequenceBLoop>, SsCompletingSequenceB, CONTINUELOOP> > sm_pack_ml::CompletingSequenceBLoop::reactions
Definition at line 29 of file completing_sequence_b_loop.hpp.
Member Function Documentation
loopWhileCondition()
bool sm_pack_ml::CompletingSequenceBLoop::loopWhileCondition () inline
Definition at line 36 of file completing_sequence_b_loop.hpp.
  {
    auto & superstate = this->context<MsCompleting>();
    RCLCPP_INFO(
      getLogger(), "Loop start, current iterations: %d, total iterations: %d",
      superstate.yiteration_count, superstate.ytotal_iterations());
    return superstate.yiteration_count++ < superstate.ytotal_iterations();
  }
References smacc2::ISmaccState::getLogger().
Referenced by onEntry().
onEntry()
void sm_pack_ml::CompletingSequenceBLoop::onEntry () inline
Definition at line 46 of file completing_sequence_b_loop.hpp.
  {
    RCLCPP_INFO(getLogger(), "LOOP START ON ENTRY");
    checkWhileLoopConditionAndThrowEvent(&CompletingSequenceBLoop::loopWhileCondition);
  }
References smacc2::SmaccState< CompletingSequenceBLoop, MsCompleting >::checkWhileLoopConditionAndThrowEvent(), smacc2::ISmaccState::getLogger(), and loopWhileCondition().
runtimeConfigure()
void sm_pack_ml::CompletingSequenceBLoop::runtimeConfigure () inline
Definition at line 34 of file completing_sequence_b_loop.hpp.
{}
staticConfigure()
static void sm_pack_ml::CompletingSequenceBLoop::staticConfigure () inline static
Definition at line 32 of file completing_sequence_b_loop.hpp.
{}
The documentation for this struct was generated from the following file:
smacc2_sm_reference_library/sm_pack_ml/include/sm_pack_ml/states/completing_sequence_b_loop.hpp