SMACC2: sm_dance_bot::StNavigateForward1 Struct Reference
sm_dance_bot::StNavigateForward1 Struct Reference
#include <st_navigate_forward_1.hpp>
Public Types
typedef mpl::list< Transition< EvCbSuccess< CbNavigateForward, OrNavigation >, StRotateDegrees2 >, Transition< EvCbFailure< CbNavigateForward, OrNavigation >, StNavigateForward1, ABORT > > reactions
Public Types inherited from smacc2::SmaccState< StNavigateForward1, MsDanceBotRunMode >
typedef MsDanceBotRunMode TContext
typedef Context::inner_context_type context_type
typedef context_type::state_iterator state_iterator
typedef mpl::list<> LastDeepState
typedef base_type::outermost_context_base_type outermost_context_base_type
typedef base_type::inner_context_ptr_type inner_context_ptr_type
typedef base_type::context_ptr_type context_ptr_type
typedef base_type::inner_initial_list inner_initial_list
Public Member Functions
void runtimeConfigure ()
void onActionClientSucceeded (cl_nav2z::ClNav2Z::WrappedResult &msg)
Public Member Functions inherited from smacc2::SmaccState< StNavigateForward1, MsDanceBotRunMode >
SmaccState ()=delete
SmaccState (my_context ctx)
virtual ~SmaccState ()
const smacc2::introspection::SmaccStateInfo * getStateInfo ()
std::string getName () override
std::string getFullName ()
std::string getShortName ()
virtual ISmaccState * getParentState ()
void exit ()
void runtimeConfigure ()
void onEntry ()
void onExit ()
bool getGlobalSMData (std::string name, T &ret)
void setGlobalSMData (std::string name, T value)
void requiresComponent (SmaccComponentType *&storage)
virtual ISmaccStateMachine & getStateMachine ()
void checkWhileLoopConditionAndThrowEvent (bool(MostDerived::*conditionFn)())
void throwSequenceFinishedEvent ()
Public Member Functions inherited from smacc2::ISmaccState
virtual ISmaccStateMachine & getStateMachine ()=0
virtual std::string getName ()=0
ISmaccState * getParentState ()
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc2::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Static Public Member Functions
static void staticConfigure ()
Static Public Member Functions inherited from smacc2::SmaccState< StNavigateForward1, MsDanceBotRunMode >
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh, StNavigateForward1 &)> initializationFunction)
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh)> initializationFunction)
static void configure_orthogonal (Args &&... args)
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor (TArgs... args)
static std::shared_ptr< smacc2::introspection::EventGeneratorHandler > static_createEventGenerator (TUArgs... args)
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor_aux (TUArgs... args)
static void initial_deep_construct (outermost_context_base_type &outermostContextBase)
static void deep_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
static inner_context_ptr_type shallow_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
Additional Inherited Members
Public Attributes inherited from smacc2::SmaccState< StNavigateForward1, MsDanceBotRunMode >
bool finishStateThrown
mpl::list<> * smacc_inner_type
Protected Attributes inherited from smacc2::ISmaccState
rclcpp::Node::SharedPtr node_
std::shared_ptr< rclcpp::Logger > logger_
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc2::SmaccEventGenerator > > eventGenerators_
ISmaccState * parentState_
const smacc2::introspection::SmaccStateInfo * stateInfo_
Detailed Description
Definition at line 29 of file st_navigate_forward_1.hpp.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvCbSuccess<CbNavigateForward, OrNavigation>, StRotateDegrees2>, Transition<EvCbFailure<CbNavigateForward, OrNavigation>, StNavigateForward1, ABORT> > sm_dance_bot::StNavigateForward1::reactions
Definition at line 40 of file st_navigate_forward_1.hpp.
Member Function Documentation
onActionClientSucceeded()
void sm_dance_bot::StNavigateForward1::onActionClientSucceeded (cl_nav2z::ClNav2Z::WrappedResult & msg) inline
Definition at line 61 of file st_navigate_forward_1.hpp.
  {
    RCLCPP_INFO_STREAM(
      getLogger(),
      " [Callback SmaccSignal] Success Detected from StAcquireSensors (connected to client signal), "
      "result data: "
        << msg.result);
  }
References smacc2::ISmaccState::getLogger().
Referenced by runtimeConfigure().
runtimeConfigure()
void sm_dance_bot::StNavigateForward1::runtimeConfigure () inline
Definition at line 52 of file st_navigate_forward_1.hpp.
  {
    ClNav2Z * move_base_action_client;
    this->requiresClient(move_base_action_client);
    // we careful with the lifetime of the callbac, us a scoped connection if is not forever
    move_base_action_client->onSucceeded(&StNavigateForward1::onActionClientSucceeded, this);
  }
References onActionClientSucceeded(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), and smacc2::ISmaccState::requiresClient().
staticConfigure()
static void sm_dance_bot::StNavigateForward1::staticConfigure () inline static
Definition at line 43 of file st_navigate_forward_1.hpp.
  {
    configure_orthogonal<OrNavigation, CbNavigateForward>(1);
    configure_orthogonal<OrNavigation, CbPauseSlam>();
    configure_orthogonal<OrLED, CbLEDOff>();
    configure_orthogonal<OrObstaclePerception, CbLidarSensor>();
  }
The documentation for this struct was generated from the following file:
smacc2_sm_reference_library/sm_dance_bot/include/sm_dance_bot/states/st_navigate_forward_1.hpp