SMACC2: smacc2::state_reactors::SrAllEventsGo Class Reference
smacc2::state_reactors::SrAllEventsGo Class Reference
#include <sr_all_events_go.hpp>
Public Member Functions
SrAllEventsGo ()
void onInitialized () override
void onEventNotified (const std::type_info *eventType) override
bool triggers () override
Public Member Functions inherited from smacc2::StateReactor
StateReactor ()
virtual ~StateReactor ()
virtual void onInitialized ()
virtual void onEntry ()
virtual void onExit ()
virtual void onEventNotified (const std::type_info *eventType)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename T , typename TClass >
void createEventCallback (void(TClass::*callback)(T *), TClass *object)
template<typename T >
void createEventCallback (std::function< void(T *)> callback)
void update ()
virtual bool triggers ()=0
template<typename TEv >
void addInputEvent ()
template<typename TEv >
void setOutputEvent ()
void initialize (ISmaccState *ownerState)
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
Private Attributes
std::map< const std::type_info *, bool > triggeredEvents
Additional Inherited Members
Public Attributes inherited from smacc2::StateReactor
ISmaccState * ownerState
std::function< void()> postEventFn
std::vector< const std::type_info * > eventTypes
std::map< const std::type_info *, std::function< void(void *)> > eventCallbacks_
Detailed Description
Definition at line 31 of file sr_all_events_go.hpp.
Constructor & Destructor Documentation
SrAllEventsGo()
smacc2::state_reactors::SrAllEventsGo::SrAllEventsGo () inline
Definition at line 36 of file sr_all_events_go.hpp.
{}
Member Function Documentation
onEventNotified()
void smacc2::state_reactors::SrAllEventsGo::onEventNotified (const std::type_info * eventType) override virtual
Reimplemented from smacc2::StateReactor.
Definition at line 31 of file sr_all_events_go.cpp.
{
  RCLCPP_INFO_STREAM(
    getLogger(), "[SB ALLEventsGo] RECEIVED EVENT OF TYPE:" << demangleSymbol(eventType->name()));
  triggeredEvents[eventType] = true;
  for (auto & entry : triggeredEvents)
  {
    RCLCPP_INFO_STREAM(getLogger(), demangleSymbol(entry.first->name()) << " = " << entry.second);
  }
}
References smacc2::introspection::demangleSymbol(), smacc2::StateReactor::getLogger(), and triggeredEvents.
onInitialized()
void smacc2::state_reactors::SrAllEventsGo::onInitialized () override virtual
Reimplemented from smacc2::StateReactor.
Definition at line 23 of file sr_all_events_go.cpp.
{
  for (auto type : eventTypes)
  {
    triggeredEvents[type] = false;
  }
}
References smacc2::StateReactor::eventTypes, and triggeredEvents.
triggers()
bool smacc2::state_reactors::SrAllEventsGo::triggers () override virtual
Implements smacc2::StateReactor.
Definition at line 43 of file sr_all_events_go.cpp.
{
  RCLCPP_INFO_STREAM(getLogger(), "SB All TRIGGERS?");
  for (auto & entry : triggeredEvents)
  {
    if (!entry.second) return false;
  }
  RCLCPP_INFO_STREAM(getLogger(), "SB ALL TRIGGERED");
  return true;
}
References smacc2::StateReactor::getLogger(), and triggeredEvents.
Member Data Documentation
triggeredEvents
std::map<const std::type_info *, bool> smacc2::state_reactors::SrAllEventsGo::triggeredEvents private
Definition at line 33 of file sr_all_events_go.hpp.
Referenced by onEventNotified(), onInitialized(), and triggers().
The documentation for this class was generated from the following files:
smacc2_state_reactor_library/sr_all_events_go/include/sr_all_events_go/sr_all_events_go.hpp
smacc2_state_reactor_library/sr_all_events_go/src/sr_all_events_go/sr_all_events_go.cpp