SMACC2: cl_move_base_z::CostmapSwitch Class Reference
cl_move_base_z::CostmapSwitch Class Reference
#include <cp_costmap_switch.hpp>
Public Types
enum class StandardLayers { GLOBAL_OBSTACLES_LAYER = 0 , LOCAL_OBSTACLES_LAYER = 1 , GLOBAL_INFLATED_LAYER = 2 , LOCAL_INFLATED_LAYER = 3 }
Public Member Functions
CostmapSwitch ()
void onInitialize () override
bool exists (std::string layerName)
void enable (std::string layerName)
void enable (StandardLayers layerType)
void disable (std::string layerName)
void disable (StandardLayers layerType)
void registerProxyFromDynamicReconfigureServer (std::string costmapName, std::string enablePropertyName="enabled")
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Static Public Member Functions
static std::string getStandardCostmapName (StandardLayers layertype)
Static Public Attributes
static std::array< std::string, 4 > layerNames
Private Attributes
std::map< std::string, std::shared_ptr< CostmapProxy > > costmapProxies
cl_move_base_z::ClMoveBaseZ * moveBaseClient_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 41 of file cp_costmap_switch.hpp.
Member Enumeration Documentation
StandardLayers
enum cl_move_base_z::CostmapSwitch::StandardLayers strong
Enumerator
GLOBAL_OBSTACLES_LAYER
LOCAL_OBSTACLES_LAYER
GLOBAL_INFLATED_LAYER
LOCAL_INFLATED_LAYER
Definition at line 44 of file cp_costmap_switch.hpp.
   {
     GLOBAL_OBSTACLES_LAYER = 0,
     LOCAL_OBSTACLES_LAYER = 1,
     GLOBAL_INFLATED_LAYER = 2,
     LOCAL_INFLATED_LAYER = 3
   };
Constructor & Destructor Documentation
CostmapSwitch()
cl_move_base_z::CostmapSwitch::CostmapSwitch ()
Definition at line 34 of file cp_costmap_switch.cpp.
 {}
Member Function Documentation
disable() [1/2]
void cl_move_base_z::CostmapSwitch::disable (StandardLayers layerType)
Definition at line 111 of file cp_costmap_switch.cpp.
 {
   this->disable(getStandardCostmapName(layerType));
 }
References disable(), and getStandardCostmapName().
disable() [2/2]
void cl_move_base_z::CostmapSwitch::disable (std::string layerName)
Definition at line 93 of file cp_costmap_switch.cpp.
 {
   RCLCPP_INFO(getLogger(), "[CostmapSwitch] disabling %s", layerName.c_str());
   if (!exists(layerName))
   {
     RCLCPP_ERROR(getLogger(), "[CostmapSwitch] costmap %s does not exist", layerName.c_str());
     return;
   }
   else
   {
     RCLCPP_INFO(
       getLogger(), "[CostmapSwitch] costmap %s found. Calling dynamic reconfigure server.",
       layerName.c_str());
     costmapProxies[layerName]->setCostmapEnabled(false);
   }
 }
References costmapProxies, exists(), and smacc2::ISmaccComponent::getLogger().
Referenced by disable().
enable() [1/2]
void cl_move_base_z::CostmapSwitch::enable (StandardLayers layerType)
Definition at line 88 of file cp_costmap_switch.cpp.
 {
   this->enable(getStandardCostmapName(layerType));
 }
References enable(), and getStandardCostmapName().
enable() [2/2]
void cl_move_base_z::CostmapSwitch::enable (std::string layerName)
Definition at line 70 of file cp_costmap_switch.cpp.
 {
   RCLCPP_INFO(getLogger(), "[CostmapSwitch] enabling %s", layerName.c_str());
   if (!exists(layerName))
   {
     RCLCPP_ERROR(getLogger(), "[CostmapSwitch] costmap %s does not exist", layerName.c_str());
     return;
   }
   else
   {
     RCLCPP_INFO(
       getLogger(), "[CostmapSwitch] costmap %s found. Calling dynamic reconfigure server.",
       layerName.c_str());
     costmapProxies[layerName]->setCostmapEnabled(true);
   }
 }
References costmapProxies, exists(), and smacc2::ISmaccComponent::getLogger().
Referenced by enable().
exists()
bool cl_move_base_z::CostmapSwitch::exists (std::string layerName)
Definition at line 60 of file cp_costmap_switch.cpp.
 {
   if (!this->costmapProxies.count(layerName))
   {
     return false;
   }
   return true;
 }
References costmapProxies.
Referenced by disable(), and enable().
getStandardCostmapName()
std::string cl_move_base_z::CostmapSwitch::getStandardCostmapName (StandardLayers layertype) static
Definition at line 55 of file cp_costmap_switch.cpp.
 {
   return CostmapSwitch::layerNames[(int)layertype];
 }
References layerNames.
Referenced by disable(), enable(), and onInitialize().
onInitialize()
void cl_move_base_z::CostmapSwitch::onInitialize () override virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 36 of file cp_costmap_switch.cpp.
 {
   this->moveBaseClient_ = dynamic_cast<cl_move_base_z::ClMoveBaseZ *>(owner_);
   if (this->moveBaseClient_ == nullptr)
   {
     RCLCPP_ERROR(getLogger(), "the owner of the CostmapSwitch must be a ClMoveBaseZ");
   }
   registerProxyFromDynamicReconfigureServer(
     getStandardCostmapName(StandardLayers::GLOBAL_OBSTACLES_LAYER));
   registerProxyFromDynamicReconfigureServer(
     getStandardCostmapName(StandardLayers::LOCAL_OBSTACLES_LAYER));
   registerProxyFromDynamicReconfigureServer(
     getStandardCostmapName(StandardLayers::GLOBAL_INFLATED_LAYER));
   registerProxyFromDynamicReconfigureServer(
     getStandardCostmapName(StandardLayers::LOCAL_INFLATED_LAYER));
 }
References smacc2::ISmaccComponent::getLogger(), getStandardCostmapName(), GLOBAL_INFLATED_LAYER, GLOBAL_OBSTACLES_LAYER, LOCAL_INFLATED_LAYER, LOCAL_OBSTACLES_LAYER, moveBaseClient_, smacc2::ISmaccComponent::owner_, and registerProxyFromDynamicReconfigureServer().
registerProxyFromDynamicReconfigureServer()
void cl_move_base_z::CostmapSwitch::registerProxyFromDynamicReconfigureServer (std::string costmapName, std::string enablePropertyName = "enabled")
Definition at line 25 of file cp_costmap_switch.cpp.
 {
   RCLCPP_INFO(getLogger(), "[CostmapSwitch] registering costmap type: %s", costmapName.c_str());
   auto proxy = std::make_shared<CostmapProxy>(
     this->moveBaseClient_->name_ + "/" + costmapName, enablePropertyName, getNode());
   costmapProxies[costmapName] = proxy;
 }
References costmapProxies, smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getNode(), moveBaseClient_, and smacc2::client_bases::SmaccActionClientBase< ActionType >::name_.
Referenced by onInitialize().
Member Data Documentation
costmapProxies
std::map<std::string, std::shared_ptr<CostmapProxy> > cl_move_base_z::CostmapSwitch::costmapProxies private
Definition at line 74 of file cp_costmap_switch.hpp.
Referenced by disable(), enable(), exists(), and registerProxyFromDynamicReconfigureServer().
layerNames
std::array< std::string, 4 > cl_move_base_z::CostmapSwitch::layerNames static
Initial value:
= {
  "global_costmap/obstacles_layer",
  "local_costmap/obstacles_layer"
  "global_costmap/inflater_layer",
  "local_costmap/inflater_layer"}
Definition at line 52 of file cp_costmap_switch.hpp.
Referenced by getStandardCostmapName().
moveBaseClient_
cl_move_base_z::ClMoveBaseZ* cl_move_base_z::CostmapSwitch::moveBaseClient_ private
Definition at line 75 of file cp_costmap_switch.hpp.
Referenced by onInitialize(), and registerProxyFromDynamicReconfigureServer().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/components/costmap_switch/cp_costmap_switch.hpp
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/components/costmap_switch/cp_costmap_switch.cpp