SMACC2: cl_move_base_z::CbResumeSlam Class Reference
cl_move_base_z::CbResumeSlam Class Reference
#include <cb_resume_slam.hpp>
Public Member Functions
CbResumeSlam (std::string serviceName="/slam_toolbox/pause_new_measurements")
void onEntry () override
Public Member Functions inherited from smacc2::client_behaviors::CbServiceCall< slam_toolbox::srv::Pause >
CbServiceCall (const char *serviceName)
CbServiceCall (const char *serviceName, std::shared_ptr< typename ServiceType::Request >)
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Protected Attributes
CpSlamToolbox * slam_
Protected Attributes inherited from smacc2::client_behaviors::CbServiceCall< slam_toolbox::srv::Pause >
std::shared_ptr< rclcpp::Client< slam_toolbox::srv::Pause > > client_
std::string serviceName_
std::shared_ptr< typename ServiceType::Request > request_
Additional Inherited Members
Public Attributes inherited from smacc2::client_behaviors::CbServiceCall< slam_toolbox::srv::Pause >
std::shared_ptr< typename ServiceType::Response > result_
Protected Member Functions inherited from smacc2::client_behaviors::CbServiceCall< slam_toolbox::srv::Pause >
void onServiceResponse (typename rclcpp::Client< slam_toolbox::srv::Pause >::SharedFuture result)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Detailed Description
Definition at line 28 of file cb_resume_slam.hpp.
Constructor & Destructor Documentation
CbResumeSlam()
cl_move_base_z::CbResumeSlam::CbResumeSlam (std::string serviceName = "/slam_toolbox/pause_new_measurements")
Definition at line 24 of file cb_resume_slam.cpp.
 : smacc2::client_behaviors::CbServiceCall<slam_toolbox::srv::Pause>(serviceName.c_str())
 {
 }
Member Function Documentation
onEntry()
void cl_move_base_z::CbResumeSlam::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 29 of file cb_resume_slam.cpp.
 {
   this->requiresComponent(this->slam_);
   auto currentState = slam_->getState();
   if (currentState == CpSlamToolbox::SlamToolboxState::Paused)
   {
     RCLCPP_INFO(
       getLogger(), "[CbResumeSlam] calling pause service to toggle from paused to resumed");
     this->request_ = std::make_shared<slam_toolbox::srv::Pause::Request>();
     smacc2::client_behaviors::CbServiceCall<slam_toolbox::srv::Pause>::onEntry();
     this->slam_->toogleState();
   }
   else
   {
     this->request_ = nullptr;
     RCLCPP_INFO(
       getLogger(), "[CbResumeSlam] calling skipped. The current slam state is already resumed.");
   }
 }
References smacc2::ISmaccClientBehavior::currentState, smacc2::ISmaccClientBehavior::getLogger(), cl_move_base_z::CpSlamToolbox::getState(), smacc2::client_behaviors::CbServiceCall< ServiceType >::onEntry(), cl_move_base_z::CpSlamToolbox::Paused, smacc2::client_behaviors::CbServiceCall< slam_toolbox::srv::Pause >::request_, smacc2::ISmaccClientBehavior::requiresComponent(), slam_, and cl_move_base_z::CpSlamToolbox::toogleState().
Member Data Documentation
slam_
CpSlamToolbox* cl_move_base_z::CbResumeSlam::slam_ protected
Definition at line 35 of file cb_resume_slam.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_resume_slam.hpp
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/client_behaviors/cb_resume_slam.cpp