SMACC2: cl_move_base_z::CbNavigateBackwards Class Reference
cl_move_base_z::CbNavigateBackwards Class Reference
#include <cb_navigate_backwards.hpp>
Public Member Functions
CbNavigateBackwards (float backwardDistance)
CbNavigateBackwards ()
void onEntry () override
void onExit () override
Public Member Functions inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
virtual ~CbMoveBaseClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Public Attributes
std::optional< float > backwardDistance
std::optional< float > backwardSpeed
std::optional< std::string > goalChecker_
std::shared_ptr< tf2_ros::Buffer > listener
cl_move_base_z::odom_tracker::OdomTracker * odomTracker_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void executeOnEntry () override
void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Protected Attributes inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
cl_move_base_z::ClMoveBaseZ * moveBaseClient_
Detailed Description
Definition at line 32 of file cb_navigate_backwards.hpp.
Constructor & Destructor Documentation
CbNavigateBackwards() [1/2]
cl_move_base_z::CbNavigateBackwards::CbNavigateBackwards (float backwardDistance)
Definition at line 34 of file cb_navigate_backward.cpp.
 {
   if (backwardDistance < 0)
   {
     RCLCPP_ERROR(getLogger(), "cb backward: distance must be greater or equal than 0");
     this->backwardDistance = 0;
   }
   this->backwardDistance = backwardDistance;
 }
References backwardDistance, and smacc2::ISmaccClientBehavior::getLogger().
CbNavigateBackwards() [2/2]
cl_move_base_z::CbNavigateBackwards::CbNavigateBackwards ()
Definition at line 44 of file cb_navigate_backward.cpp.
 {}
Member Function Documentation
onEntry()
void cl_move_base_z::CbNavigateBackwards::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 46 of file cb_navigate_backward.cpp.
 {
   // straight motion distance
   double dist = 3.5;
   if (!backwardDistance)
   {
     this->getCurrentState()->param("straight_motion_distance", dist);
   }
   else
   {
     dist = *backwardDistance;
   }
   this->listener = std::make_shared<tf2_ros::Buffer>(getNode()->get_clock());
   RCLCPP_INFO_STREAM(
     getLogger(), "[CbNavigateBackwards] Straight backwards motion distance: " << dist);
   auto p = moveBaseClient_->getComponent<cl_move_base_z::Pose>();
   auto referenceFrame = p->getReferenceFrame();
   auto currentPoseMsg = p->toPoseMsg();
   tf2::Transform currentPose;
   tf2::fromMsg(currentPoseMsg, currentPose);
   tf2::Transform forwardDeltaTransform;
   forwardDeltaTransform.setIdentity();
   forwardDeltaTransform.setOrigin(tf2::Vector3(-dist, 0, 0));
   tf2::Transform targetPose = currentPose * forwardDeltaTransform;
   ClMoveBaseZ::Goal goal;
   goal.pose.header.frame_id = referenceFrame;
   goal.pose.header.stamp = getNode()->now();
   tf2::toMsg(targetPose, goal.pose.pose);
   RCLCPP_INFO_STREAM(getLogger(), "[CbNavigateBackwards] TARGET POSE BACKWARDS: " << goal.pose);
   odomTracker_ = moveBaseClient_->getComponent<OdomTracker>();
   if (odomTracker_ != nullptr)
   {
     this->odomTracker_->clearPath();
     this->odomTracker_->setStartPoint(currentPoseMsg);
     this->odomTracker_->setWorkingMode(WorkingMode::RECORD_PATH);
   }
   auto plannerSwitcher = moveBaseClient_->getComponent<PlannerSwitcher>();
   plannerSwitcher->setBackwardPlanner();
   auto goalCheckerSwitcher = moveBaseClient_->getComponent<GoalCheckerSwitcher>();
   goalCheckerSwitcher->setGoalCheckerId("backward_goal_checker");
   moveBaseClient_->sendGoal(goal);
 }
References backwardDistance, cl_move_base_z::odom_tracker::OdomTracker::clearPath(), smacc2::ISmaccClient::getComponent(), smacc2::ISmaccClientBehavior::getCurrentState(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getNode(), cl_move_base_z::Pose::getReferenceFrame(), listener, cl_move_base_z::CbMoveBaseClientBehaviorBase::moveBaseClient_, odomTracker_, smacc2::ISmaccState::param(), smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), cl_move_base_z::PlannerSwitcher::setBackwardPlanner(), cl_move_base_z::GoalCheckerSwitcher::setGoalCheckerId(), cl_move_base_z::odom_tracker::OdomTracker::setStartPoint(), and cl_move_base_z::odom_tracker::OdomTracker::setWorkingMode().
onExit()
void cl_move_base_z::CbNavigateBackwards::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 97 of file cb_navigate_backward.cpp.
 {
   if (odomTracker_)
   {
     this->odomTracker_->setWorkingMode(WorkingMode::IDLE);
   }
 }
References odomTracker_, and cl_move_base_z::odom_tracker::OdomTracker::setWorkingMode().
Member Data Documentation
backwardDistance
std::optional<float> cl_move_base_z::CbNavigateBackwards::backwardDistance
Definition at line 35 of file cb_navigate_backwards.hpp.
Referenced by CbNavigateBackwards(), and onEntry().
backwardSpeed
std::optional<float> cl_move_base_z::CbNavigateBackwards::backwardSpeed
Definition at line 38 of file cb_navigate_backwards.hpp.
goalChecker_
std::optional<std::string> cl_move_base_z::CbNavigateBackwards::goalChecker_
Definition at line 40 of file cb_navigate_backwards.hpp.
listener
std::shared_ptr<tf2_ros::Buffer> cl_move_base_z::CbNavigateBackwards::listener
Definition at line 42 of file cb_navigate_backwards.hpp.
Referenced by onEntry().
odomTracker_
cl_move_base_z::odom_tracker::OdomTracker* cl_move_base_z::CbNavigateBackwards::odomTracker_
Definition at line 44 of file cb_navigate_backwards.hpp.
Referenced by onEntry(), and onExit().
The documentation for this class was generated from the following files:
smacc_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_navigate_backwards.hpp
smacc_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/client_behaviors/cb_navigate_backward.cpp