SMACC2: smacc2::FlashLightPlugin Class Reference
smacc2::FlashLightPlugin Class Reference
#include <FlashLightPlugin.hh>
Public Member Functions
FlashLightPlugin ()
Constructor.
virtual ~FlashLightPlugin ()
Destructor.
void Load (gazebo::physics::ModelPtr _parent, sdf::ElementPtr _sdf) override
Protected Member Functions
virtual void OnUpdate ()
Called by the world update start event.
virtual bool TurnOn (const std::string &_lightName) final
Turn on a flash light specified by the light name If more than one link have lights with the identical name, the first appearing light in the list will be updated.
virtual bool TurnOn (const std::string &_lightName, const std::string &_linkName) final
Turn on a flash light specified by the name and its link.
virtual bool TurnOnAll () final
Turn on all flash lights.
virtual bool TurnOff (const std::string &_lightName) final
Turn off a flash light specified by the name If more than one link have lights with the identical name, the first appearing light in the list will be updated.
virtual bool TurnOff (const std::string &_lightName, const std::string &_linkName) final
Turn off a flash light specified by the name.
virtual bool TurnOffAll () final
Turn off all flash lights.
virtual bool ChangeDuration (const std::string &_lightName, const std::string &_linkName, const double _duration, const int _index) final
Change the duration of a specific block of the flashlight. If the index is a negative number, it updates all the blocks.
virtual bool ChangeDuration (const std::string &_lightName, const std::string &_linkName, const double _duration) final
Change the duration of all the blocks of the flashlight.
virtual bool ChangeInterval (const std::string &_lightName, const std::string &_linkName, const double _interval, const int _index) final
Change the interval of a specific block of the flashlight. If the index is a negative number, it updates all the blocks.
virtual bool ChangeInterval (const std::string &_lightName, const std::string &_linkName, const double _interval) final
Change the interval of all the blocks of the flashlight.
virtual bool ChangeColor (const std::string &_lightName, const std::string &_linkName, const ignition::math::Color &_color, const int _index) final
Change the color of a specific block of the flashlight. If the index is a negative number, it updates all the blocks.
virtual bool ChangeColor (const std::string &_lightName, const std::string &_linkName, const ignition::math::Color &_color) final
Change the color of all the blocks of the flashlight.
virtual std::shared_ptr< FlashLightSetting > CreateSetting (const sdf::ElementPtr &_sdf, const gazebo::physics::ModelPtr &_model, const gazebo::common::Time &_currentTime, gazebo_ros::Node::SharedPtr node)
Create an object of setting.
virtual void InitSettingBySpecificData (std::shared_ptr< FlashLightSetting > &_setting)
Initialize the additional part of an object of setting.
Private Attributes
std::unique_ptr< FlashLightPluginPrivate > dataPtr
Pointer to private data.
rclcpp::Subscription< std_msgs::msg::Int8 >::SharedPtr cmdledsubscription
Detailed Description
Definition at line 164 of file FlashLightPlugin.hh.
Constructor & Destructor Documentation
FlashLightPlugin()
smacc2::FlashLightPlugin::FlashLightPlugin ()
Constructor.
Definition at line 597 of file FlashLightPlugin.cc.
                                   : gazebo::ModelPlugin(),
  dataPtr(new FlashLightPluginPrivate)
{
  // Create a node
  this->dataPtr->node = gazebo::transport::NodePtr(new gazebo::transport::Node());
  this->dataPtr->node->Init();
  // advertise the topic to update lights
  // this->dataPtr->pubLight
  //    = this->dataPtr->node->Advertise<gazebo::msgs::Light>("~/light/modify");
  // this->dataPtr->pubLight->WaitForConnection();
}
References dataPtr.
~FlashLightPlugin()
smacc2::FlashLightPlugin::~FlashLightPlugin () virtual
Destructor.
Definition at line 612 of file FlashLightPlugin.cc.
{
}
Member Function Documentation
ChangeColor() [1/2]
bool smacc2::FlashLightPlugin::ChangeColor (const std::string & _lightName, const std::string & _linkName, const ignition::math::Color & _color) final protected virtual
Change the color of all the blocks of the flashlight.
Parameters
[in] _lightName The name of flash light
[in] _linkName The name of the link holding the light
[in] _color The new color to set
Returns
True if the specified light is found.
Definition at line 918 of file FlashLightPlugin.cc.
{
  return this->ChangeColor(_lightName, _linkName, _color, -1);
}
References ChangeColor().
ChangeColor() [2/2]
bool smacc2::FlashLightPlugin::ChangeColor (const std::string & _lightName, const std::string & _linkName, const ignition::math::Color & _color, const int _index) final protected virtual
Change the color of a specific block of the flashlight. If the index is a negative number, it updates all the blocks.
Parameters
[in] _lightName The name of flash light
[in] _linkName The name of the link holding the light
[in] _color The new color to set
[in] _index The index to the block to update
Returns
True if the specified light is found.
Definition at line 892 of file FlashLightPlugin.cc.
{
  std::shared_ptr<FlashLightSetting> setting
    = this->dataPtr->SettingByLightNameAndLinkName(_lightName, _linkName);
  if (setting)
  {
    if (_index >= 0)
    {
      setting->SetColor(_color, _index);
    }
    else
    {
      setting->SetColor(_color);
    }
    return true;
  }
  gzerr << "light <" + _lightName + "> does not exist." << std::endl;
  return false;
}
References dataPtr.
Referenced by ChangeColor().
ChangeDuration() [1/2]
bool smacc2::FlashLightPlugin::ChangeDuration (const std::string & _lightName, const std::string & _linkName, const double _duration) final protected virtual
Change the duration of all the blocks of the flashlight.
Parameters
[in] _lightName The name of flash light
[in] _linkName The name of the link holding the light
[in] _duration The new duration time to set
Returns
True if the specified light is found.
Definition at line 848 of file FlashLightPlugin.cc.
{
  return this->ChangeDuration(_lightName, _linkName, _duration, -1);
}
References ChangeDuration().
ChangeDuration() [2/2]
bool smacc2::FlashLightPlugin::ChangeDuration (const std::string & _lightName, const std::string & _linkName, const double _duration, const int _index) final protected virtual
Change the duration of a specific block of the flashlight. If the index is a negative number, it updates all the blocks.
Parameters
[in] _lightName The name of flash light
[in] _linkName The name of the link holding the light
[in] _duration The new duration time to set
[in] _index The index to the block to update
Returns
True if the specified light is found.
Definition at line 822 of file FlashLightPlugin.cc.
{
  std::shared_ptr<FlashLightSetting> setting
    = this->dataPtr->SettingByLightNameAndLinkName(_lightName, _linkName);
  if (setting)
  {
    if (_index >= 0)
    {
      setting->SetDuration(_duration, _index);
    }
    else
    {
      setting->SetDuration(_duration);
    }
    return true;
  }
  gzerr << "light <" + _lightName + "> does not exist." << std::endl;
  return false;
}
References dataPtr.
Referenced by ChangeDuration().
ChangeInterval() [1/2]
bool smacc2::FlashLightPlugin::ChangeInterval (const std::string & _lightName, const std::string & _linkName, const double _interval) final protected virtual
Change the interval of all the blocks of the flashlight.
Parameters
[in] _lightName The name of flash light
[in] _linkName The name of the link holding the light
[in] _interval The new interval time to set
Returns
True if the specified light is found.
Definition at line 883 of file FlashLightPlugin.cc.
{
  return this->ChangeInterval(_lightName, _linkName, _interval, -1);
}
References ChangeInterval().
ChangeInterval() [2/2]
bool smacc2::FlashLightPlugin::ChangeInterval (const std::string & _lightName, const std::string & _linkName, const double _interval, const int _index) final protected virtual
Change the interval of a specific block of the flashlight. If the index is a negative number, it updates all the blocks.
Parameters
[in] _lightName The name of flash light
[in] _linkName The name of the link holding the light
[in] _interval The new interval time to set
[in] _index The index to the block to update
Returns
True if the specified light is found.
Definition at line 857 of file FlashLightPlugin.cc.
{
  std::shared_ptr<FlashLightSetting> setting
    = this->dataPtr->SettingByLightNameAndLinkName(_lightName, _linkName);
  if (setting)
  {
    if (_index >= 0)
    {
      setting->SetInterval(_interval, _index);
    }
    else
    {
      setting->SetInterval(_interval);
    }
    return true;
  }
  gzerr << "light <" + _lightName + "> does not exist." << std::endl;
  return false;
}
References dataPtr.
Referenced by ChangeInterval().
CreateSetting()
std::shared_ptr< FlashLightSetting > smacc2::FlashLightPlugin::CreateSetting (const sdf::ElementPtr & _sdf, const gazebo::physics::ModelPtr & _model, const gazebo::common::Time & _currentTime, gazebo_ros::Node::SharedPtr node) protected virtual
Create an object of setting.
NOTE: This function is internally called in Load() of the base class. If a child class of FlashLightPlugin has also an inherited class of FlashLightSetting, this function must be overridden so that dataPtr deals with objects of the appropriate setting class.
Parameters
[in] _sdf SDF data for the setting.
[in] _model The Model pointer holding the light to control.
[in] _currentTime The current time point.
Returns
A pointer to the newly created setting object.
Reimplemented in smacc2::LedPlugin.
Definition at line 928 of file FlashLightPlugin.cc.
{
  return std::make_shared<FlashLightSetting>(_sdf, _model, _currentTime, node);
}
Referenced by Load().
InitSettingBySpecificData()
void smacc2::FlashLightPlugin::InitSettingBySpecificData (std::shared_ptr< FlashLightSetting > & _setting) protected virtual
Initialize the additional part of an object of setting.
NOTE: This function is internally called in Load() of the base class. If a child class of FlashLightPlugin has also an inherited class of FlashLightSetting, this function must be overridden so that the object can be initialized with necessary data. Also, the overridden function must call the original function in it.
Parameters
[in] _setting A pointer to the setting object.
Reimplemented in smacc2::LedPlugin.
Definition at line 938 of file FlashLightPlugin.cc.
{
  _setting->InitPubLight(this->dataPtr->pubLight);
}
References dataPtr.
Referenced by smacc2::LedPlugin::InitSettingBySpecificData(), and Load().
Load()
void smacc2::FlashLightPlugin::Load (gazebo::physics::ModelPtr _parent, sdf::ElementPtr _sdf) override
Definition at line 617 of file FlashLightPlugin.cc.
{
  // Store the pointers to the model and world
  this->dataPtr->model = _parent;
  this->dataPtr->world = _parent->GetWorld();
  auto node = gazebo_ros::Node::Get(_sdf);
  // Get the current time
  gazebo::common::Time currentTime = this->dataPtr->world->SimTime();
  // Get the parameters from sdf
  if (_sdf->HasElement("light"))
  {
    sdf::ElementPtr sdfFlashLight = _sdf->GetElement("light");
    while (sdfFlashLight)
    {
      // id required
      if (sdfFlashLight->HasElement("id"))
      {
        // Create an object of setting.
        std::shared_ptr<FlashLightSetting> setting
          = this->CreateSetting(
              sdfFlashLight, this->dataPtr->model, currentTime, node);
        // Initialize the object with the data specific to descendan classes.
        this->InitSettingBySpecificData(setting);
        // Store the setting to the list
        this->dataPtr->listFlashLight.push_back(setting);
      }
      else
      {
        // display an error message
        gzerr << "id does not exist in <light>" << std::endl;
      }
      sdfFlashLight = sdfFlashLight->GetNextElement("light");
  }
  // Turn on/off all the lights if <enable> element is given
  if (_sdf->HasElement("enable"))
  {
    if (_sdf->Get<bool>("enable"))
    {
      this->TurnOnAll();
    }
    else
    {
      this->TurnOffAll();
    }
  }
  // Turn on/off a specific light if <enable> is specifically given.
  if (_sdf->HasElement("light"))
  {
    sdf::ElementPtr sdfFlashLight = _sdf->GetElement("light");
    while (sdfFlashLight)
    {
      if (sdfFlashLight->HasElement("enable"))
      {
        std::string lightId = sdfFlashLight->Get<std::string>("id");
        int posDelim = lightId.rfind("/");
        std::string lightName = lightId.substr(posDelim+1, lightId.length());
        std::string linkName = lightId.substr(0, posDelim);
        if (sdfFlashLight->Get<bool>("enable"))
        {
          this->TurnOn(lightName, linkName);
        }
        else
        {
          this->TurnOff(lightName, linkName);
        }
      }
      sdfFlashLight = sdfFlashLight->GetNextElement("light");
    }
  }
  // listen to the update event by the World
  if (!this->dataPtr->listFlashLight.empty())
  {
    this->dataPtr->updateConnection = event::Events::ConnectWorldUpdateBegin(
      std::bind(&FlashLightPlugin::OnUpdate, this));
  }
    rclcpp::SensorDataQoS qos;
    auto topicname = "/"+ this->dataPtr->model->GetName()+  "/cmdled";
    boost::replace_all(topicname, "::","/");
    gzmsg << "topicname: " << topicname <<"\n";
    cmdledsubscription =
    node->create_subscription<std_msgs::msg::Int8>(topicname, qos,
    [this, node]
    (const std_msgs::msg::Int8::SharedPtr msg)
    {
      RCLCPP_INFO(node->get_logger(), "msg received");
      if(msg->data == 0)
      this->TurnOffAll();
      else
      this->TurnOnAll();
    });
    }
}
References cmdledsubscription, CreateSetting(), dataPtr, InitSettingBySpecificData(), OnUpdate(), TurnOff(), TurnOffAll(), TurnOn(), and TurnOnAll().
Referenced by smacc2::ControllableLed::Load().
OnUpdate()
void smacc2::FlashLightPlugin::OnUpdate () protected virtual
Called by the world update start event.
update the light
Definition at line 725 of file FlashLightPlugin.cc.
{
  gazebo::common::Time currentTime = this->dataPtr->world->SimTime();
  for (auto &setting: this->dataPtr->listFlashLight)
  {
    setting->UpdateLightInEnv(currentTime);
  }
}
References dataPtr.
Referenced by Load().
TurnOff() [1/2]
bool smacc2::FlashLightPlugin::TurnOff (const std::string & _lightName) final protected virtual
Turn off a flash light specified by the name If more than one link have lights with the identical name, the first appearing light in the list will be updated.
Parameters
[in] _lightName The name of flash light
Returns
True if the specified light is found.
Definition at line 778 of file FlashLightPlugin.cc.
{
  return this->TurnOff(_lightName, "");
}
References TurnOff().
Referenced by Load(), and TurnOff().
TurnOff() [2/2]
bool smacc2::FlashLightPlugin::TurnOff (const std::string & _lightName, const std::string & _linkName) final protected virtual
Turn off a flash light specified by the name.
Parameters
[in] _lightName The name of flash light
[in] _linkName The name of the link holding the light
Returns
True if the specified light is found.
Definition at line 784 of file FlashLightPlugin.cc.
{
  std::shared_ptr<FlashLightSetting> setting
    = this->dataPtr->SettingByLightNameAndLinkName(_lightName, _linkName);
  if (setting)
  {
    setting->SwitchOff();
    return true;
  }
  gzerr << "light: [" + _linkName + "/" + _lightName + "] does not exist."
        << std::endl;
  return false;
}
References dataPtr.
TurnOffAll()
bool smacc2::FlashLightPlugin::TurnOffAll () final protected virtual
Turn off all flash lights.
Returns
True if there is one or more lights to turn off.
Definition at line 802 of file FlashLightPlugin.cc.
{
  gzmsg << "msg TurnOffAll"  << std::endl;
  if (this->dataPtr->listFlashLight.empty())
  {
    gzerr << "no flash lights exist to turn off." << std::endl;
    return false;
  }
  gzmsg <<  "switch off" << std::endl;
  for (auto &setting: this->dataPtr->listFlashLight)
  {
    setting->SwitchOff();
  }
  return true;
}
References dataPtr.
Referenced by smacc2::ControllableLed::LightCmd(), and Load().
TurnOn() [1/2]
bool smacc2::FlashLightPlugin::TurnOn (const std::string & _lightName) final protected virtual
Turn on a flash light specified by the light name If more than one link have lights with the identical name, the first appearing light in the list will be updated.
Parameters
[in] _lightName The name of flash light
Returns
True if the specified light is found.
Definition at line 737 of file FlashLightPlugin.cc.
{
  return this->TurnOn(_lightName, "");
}
References TurnOn().
Referenced by Load(), and TurnOn().
TurnOn() [2/2]
bool smacc2::FlashLightPlugin::TurnOn (const std::string & _lightName, const std::string & _linkName) final protected virtual
Turn on a flash light specified by the name and its link.
Parameters
[in] _lightName The name of flash light
[in] _linkName The name of the link holding the light
Returns
True if the specified light is found.
Definition at line 743 of file FlashLightPlugin.cc.
{
  std::shared_ptr<FlashLightSetting> setting
    = this->dataPtr->SettingByLightNameAndLinkName(_lightName, _linkName);
  if (setting)
  {
    setting->SwitchOn();
    return true;
  }
  gzerr << "light: [" + _linkName + "/" + _lightName + "] does not exist."
        << std::endl;
  return false;
}
References dataPtr.
TurnOnAll()
bool smacc2::FlashLightPlugin::TurnOnAll () final protected virtual
Turn on all flash lights.
Returns
True if there is one or more lights to turn on.
Definition at line 761 of file FlashLightPlugin.cc.
{
  if (this->dataPtr->listFlashLight.empty())
  {
    gzerr << "no flash lights exist to turn on." << std::endl;
    return false;
  }
  for (auto &setting: this->dataPtr->listFlashLight)
  {
    setting->SwitchOn();
  }
  return true;
}
References dataPtr.
Referenced by smacc2::ControllableLed::LightCmd(), and Load().
Member Data Documentation
cmdledsubscription
rclcpp::Subscription<std_msgs::msg::Int8>::SharedPtr smacc2::FlashLightPlugin::cmdledsubscription private
Definition at line 307 of file FlashLightPlugin.hh.
Referenced by Load().
dataPtr
std::unique_ptr<FlashLightPluginPrivate> smacc2::FlashLightPlugin::dataPtr private
Pointer to private data.
Definition at line 305 of file FlashLightPlugin.hh.
Referenced by ChangeColor(), ChangeDuration(), ChangeInterval(), FlashLightPlugin(), InitSettingBySpecificData(), Load(), OnUpdate(), TurnOff(), TurnOffAll(), TurnOn(), and TurnOnAll().
The documentation for this class was generated from the following files:
smacc2_sm_reference_library/sm_husky_barrel_search_1/src/sm_husky_barrel_search_1/gz_plugins/FlashLightPlugin.hh
smacc2_sm_reference_library/sm_husky_barrel_search_1/src/sm_husky_barrel_search_1/gz_plugins/FlashLightPlugin.cc