SMACC2: smacc2::introspection::SmaccStateMachineInfo Class Reference
smacc2::introspection::SmaccStateMachineInfo Class Reference
#include <smacc_state_machine_info.hpp>
Public Member Functions
SmaccStateMachineInfo (rclcpp::Node::SharedPtr nh)
template<typename InitialStateType >
void buildStateMachineInfo ()
template<typename StateType >
std::shared_ptr< SmaccStateInfo > createState (std::shared_ptr< SmaccStateInfo > parentState)
template<typename StateType >
bool containsState ()
template<typename StateType >
std::shared_ptr< SmaccStateInfo > getState ()
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
template<typename StateType >
void addState (std::shared_ptr< StateType > &state)
void assembleSMStructureMessage (ISmaccStateMachine *sm)
Public Attributes
std::map< std::string, std::shared_ptr< SmaccStateInfo > > states
std::vector< smacc2_msgs::msg::SmaccState > stateMsgs
Private Attributes
rclcpp::Node::SharedPtr nh_
Detailed Description
Definition at line 44 of file smacc_state_machine_info.hpp.
Constructor & Destructor Documentation
SmaccStateMachineInfo()
smacc2::introspection::SmaccStateMachineInfo::SmaccStateMachineInfo (rclcpp::Node::SharedPtr nh) inline explicit
Definition at line 47 of file smacc_state_machine_info.hpp.
 : nh_(nh) {}
Member Function Documentation
addState()
template<typename StateType > void smacc2::introspection::SmaccStateMachineInfo::addState (std::shared_ptr< StateType > & state)
Definition at line 496 of file smacc_state_machine_info.hpp.
 {
   states[state->fullStateName] = state;
 }
References states.
Referenced by createState().
assembleSMStructureMessage()
void smacc2::SmaccStateMachineInfo::assembleSMStructureMessage (ISmaccStateMachine * sm)
Definition at line 20 of file smacc_state_machine_info.cpp.
 {
   std::stringstream ss;
   ss << "----------- PRINT STATE MACHINE STRUCTURE -------------------" << std::endl;
   stateMsgs.clear();
   for (auto & val : this->states)
   {
     smacc2_msgs::msg::SmaccState stateMsg;
     auto state = val.second;
     stateMsg.index = state->stateIndex_;
     ss << "**** State: " << demangleSymbol(val.first.c_str()) << std::endl;
     stateMsg.name = state->getDemangledFullName();
     stateMsg.level = (int)state->getStateLevel();
     ss << "Index: " << stateMsg.index << std::endl;
     ss << "StateLevel: " << stateMsg.level << std::endl;
     ss << " Childstates:" << std::endl;
     for (auto & child : state->children_)
     {
       auto childStateName = child->getDemangledFullName();
       stateMsg.children_states.push_back(childStateName);
       ss << " - " << childStateName << std::endl;
     }
     ss << " Transitions:" << std::endl;
     for (auto & transition : state->transitions_)
     {
       smacc2_msgs::msg::SmaccTransition transitionMsg;
       transitionInfoToMsg(transition, transitionMsg);
       ss << " - Transition.  " << std::endl;
       ss << "      - Index: " << transitionMsg.index << std::endl;
       ss << "      - Transition Name: " << transitionMsg.transition_name << std::endl;
       ss << "      - Transition Type: " << transitionMsg.transition_type << std::endl;
       ss << "      - Event Type :" << transitionMsg.event.event_type << std::endl;
       ss << "      - Event Source: " << transitionMsg.event.event_source << std::endl;
       ss << "      - Event ObjectTag: " << transitionMsg.event.event_object_tag << std::endl;
       ss << "      - Event Label: " << transitionMsg.event.label << std::endl;
       ss << "      - Destiny State: " << transitionMsg.destiny_state_name << std::endl;
       ss << "      - Owner State: " << transitionMsg.destiny_state_name << std::endl;
       ss << "      - Is History Node: " << std::to_string(transitionMsg.history_node) << std::endl;
       ss << "      - TransitionC++Type: " << transition.transitionTypeInfo->getFullName()
          << std::endl;
       ss << "      - EventC++Type: " << transition.eventInfo->eventType->getFullName() << std::endl;
       stateMsg.transitions.push_back(transitionMsg);
     }
     const std::type_info * statetid = state->tid_;
     std::map<const std::type_info *, std::vector<smacc2::ClientBehaviorInfoEntry *>>
       smaccBehaviorInfoMappingByOrthogonalType;
     ss << " Orthogonals:" << std::endl;
     if (SmaccStateInfo::staticBehaviorInfo.count(statetid) > 0)
     {
       for (auto & bhinfo : SmaccStateInfo::staticBehaviorInfo[statetid])
       {
         if (smaccBehaviorInfoMappingByOrthogonalType.count(bhinfo.orthogonalType) == 0)
         {
           smaccBehaviorInfoMappingByOrthogonalType[bhinfo.orthogonalType] =
             std::vector<smacc2::ClientBehaviorInfoEntry *>();
         }
         smaccBehaviorInfoMappingByOrthogonalType[bhinfo.orthogonalType].push_back(&bhinfo);
       }
     }
     auto & runtimeOrthogonals = sm->getOrthogonals();
     for (auto & orthogonal : runtimeOrthogonals)
     {
       smacc2_msgs::msg::SmaccOrthogonal orthogonalMsg;
       const auto * orthogonaltid = &typeid(*(orthogonal.second));
       orthogonalMsg.name = demangleSymbol(orthogonaltid->name());
       ss << " - orthogonal: " << orthogonalMsg.name << std::endl;
       if (smaccBehaviorInfoMappingByOrthogonalType[orthogonaltid].size() > 0)
       {
         auto & behaviors = smaccBehaviorInfoMappingByOrthogonalType[orthogonaltid];
         for (auto & bhinfo : behaviors)
         {
           auto ClientBehaviorName = demangleSymbol(bhinfo->behaviorType->name());
           orthogonalMsg.client_behavior_names.push_back(ClientBehaviorName);
           ss << "          - client behavior: " << ClientBehaviorName << std::endl;
         }
       }
       else
       {
         ss << "          - NO CLIENT BEHAVIORS -" << std::endl;
       }
       auto & clients = orthogonal.second->getClients();
       if (clients.size() > 0)
       {
         for (auto & client : clients)
         {
           auto clientTid = client->getType();
           auto clientName = clientTid->getNonTemplatedTypeName();
           orthogonalMsg.client_names.push_back(clientName);
           ss << "          - client: " << clientName << std::endl;
         }
       }
       else
       {
         ss << "          - NO CLIENTS - " << std::endl;
       }
       stateMsg.orthogonals.push_back(orthogonalMsg);
     }
     ss << " State event generators:" << std::endl;
     if (SmaccStateInfo::eventGeneratorsInfo.count(statetid) > 0)
     {
       int k = 0;
       for (auto & eginfo : SmaccStateInfo::eventGeneratorsInfo[statetid])
       {
         smacc2_msgs::msg::SmaccEventGenerator eventGeneratorMsg;
         eventGeneratorMsg.index = k++;
         eventGeneratorMsg.type_name = eginfo->eventGeneratorType->getFullName();
         ss << " - event generator: " << eventGeneratorMsg.type_name << std::endl;
         if (eginfo->objectTagType != nullptr)
         {
           eventGeneratorMsg.object_tag = eginfo->objectTagType->getFullName();
           ss << "        - object tag: " << eventGeneratorMsg.object_tag << std::endl;
         }
         stateMsg.event_generators.push_back(eventGeneratorMsg);
       }
     }
     ss << " State reactors:" << std::endl;
     if (SmaccStateInfo::stateReactorsInfo.count(statetid) > 0)
     {
       int k = 0;
       for (auto & srinfo : SmaccStateInfo::stateReactorsInfo[statetid])
       {
         smacc2_msgs::msg::SmaccStateReactor stateReactorMsg;
         stateReactorMsg.index = k++;
         stateReactorMsg.type_name = srinfo->stateReactorType->getFullName();
         ss << " - state reactor: " << stateReactorMsg.type_name << std::endl;
         if (srinfo->objectTagType != nullptr)
         {
           stateReactorMsg.object_tag = srinfo->objectTagType->getFullName();
           ss << "        - object tag: " << stateReactorMsg.object_tag << std::endl;
         }
         for (auto & tev : srinfo->sourceEventTypes)
         {
           // WE SHOULD CREATE A SMACC_EVENT_INFO TYPE, also using in typewalker transition
           auto eventTypeName = tev->getEventTypeName();
           smacc2_msgs::msg::SmaccEvent event;
           ss << "             - triggering event: " << tev->getEventTypeName() << std::endl;
           event.event_type = eventTypeName;
           event.event_source = tev->getEventSourceName();
           ss << "                 - source type: " << event.event_source << std::endl;
           event.event_object_tag = tev->getOrthogonalName();
           ss << "                 - source object: " << event.event_object_tag << std::endl;
           event.label = tev->label;
           ss << "                 - event label: " << event.label << std::endl;
           stateReactorMsg.event_sources.push_back(event);
         }
         stateMsg.state_reactors.push_back(stateReactorMsg);
       }
     }
     else
     {
       ss << "- NO STATE REACTORS - " << std::endl;
     }
     ss << "----------------------------------------------------------" << std::endl;
     auto resumeMsg = ss.str();
     RCLCPP_INFO(getLogger(), "%s", resumeMsg.c_str());
     stateMsgs.push_back(stateMsg);
   }
 }
References sm_atomic_performance_test_a_1::count, smacc2::introspection::demangleSymbol(), smacc2::introspection::SmaccStateInfo::eventGeneratorsInfo, getLogger(), smacc2::ISmaccStateMachine::getOrthogonals(), stateMsgs, smacc2::introspection::SmaccStateInfo::stateReactorsInfo, states, smacc2::introspection::SmaccStateInfo::staticBehaviorInfo, and smacc2::introspection::transitionInfoToMsg().
buildStateMachineInfo()
template<typename InitialStateType > void smacc2::introspection::SmaccStateMachineInfo::buildStateMachineInfo
Definition at line 464 of file smacc_state_machine_info.hpp.
 {
   auto initialState = this->createState<InitialStateType>(nullptr);
   WalkStatesExecutor<InitialStateType>::walkStates(initialState, true);
 }
References smacc2::introspection::WalkStatesExecutor< InitialStateType >::walkStates().
containsState()
template<typename StateType > bool smacc2::introspection::SmaccStateMachineInfo::containsState () inline
Definition at line 60 of file smacc_state_machine_info.hpp.
   {
     auto typeNameStr = typeid(StateType).name();
     return states.count(typeNameStr) > 0;
   }
References states.
createState()
template<typename StateType > std::shared_ptr< SmaccStateInfo > smacc2::introspection::SmaccStateMachineInfo::createState (std::shared_ptr< SmaccStateInfo > parentState)
Definition at line 471 of file smacc_state_machine_info.hpp.
 {
   auto thisptr = this->shared_from_this();
   auto * statetid = &(typeid(StateType));
   auto demangledName = demangledTypeName<StateType>();
   RCLCPP_INFO_STREAM(getLogger(), "Creating State Info: " << demangledName);
   auto state = std::make_shared<SmaccStateInfo>(statetid, parent, thisptr);
   state->demangledStateName = demangledName;
   state->fullStateName = typeid(StateType).name();
   state->stateIndex_ = states.size();
   if (parent != nullptr)
   {
     parent->children_.push_back(state);
   }
   this->addState(state);
   return state;
 }
References addState(), getLogger(), and states.
getLogger()
rclcpp::Logger smacc2::introspection::SmaccStateMachineInfo::getLogger () inline
Definition at line 79 of file smacc_state_machine_info.hpp.
 { return nh_->get_logger(); }
References nh_.
Referenced by assembleSMStructureMessage(), and createState().
getNode()
rclcpp::Node::SharedPtr smacc2::introspection::SmaccStateMachineInfo::getNode () inline
Definition at line 77 of file smacc_state_machine_info.hpp.
 { return nh_; }
References nh_.
getState()
template<typename StateType > std::shared_ptr<SmaccStateInfo> smacc2::introspection::SmaccStateMachineInfo::getState () inline
Definition at line 68 of file smacc_state_machine_info.hpp.
   {
     if (this->containsState<StateType>())
     {
       return states[typeid(StateType).name()];
     }
     return nullptr;
   }
References states.
Member Data Documentation
nh_
rclcpp::Node::SharedPtr smacc2::introspection::SmaccStateMachineInfo::nh_ private
Definition at line 86 of file smacc_state_machine_info.hpp.
Referenced by getLogger(), and getNode().
stateMsgs
std::vector<smacc2_msgs::msg::SmaccState> smacc2::introspection::SmaccStateMachineInfo::stateMsgs
Definition at line 51 of file smacc_state_machine_info.hpp.
Referenced by assembleSMStructureMessage().
states
std::map<std::string, std::shared_ptr<SmaccStateInfo> > smacc2::introspection::SmaccStateMachineInfo::states
Definition at line 49 of file smacc_state_machine_info.hpp.
Referenced by addState(), assembleSMStructureMessage(), containsState(), createState(), and getState().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/introspection/smacc_state_machine_info.hpp
smacc2/src/smacc2/smacc_state_machine_info.cpp