SMACC2: cl_move_base_z::backward_global_planner::BackwardGlobalPlanner Class Reference
cl_move_base_z::backward_global_planner::BackwardGlobalPlanner Class Reference
#include <backward_global_planner.hpp>
Public Member Functions
BackwardGlobalPlanner ()
virtual ~BackwardGlobalPlanner ()
Virtual destructor.
virtual void configure (const rclcpp_lifecycle::LifecycleNode::WeakPtr &parent, std::string name, std::shared_ptr< tf2_ros::Buffer > tf, std::shared_ptr< nav2_costmap_2d::Costmap2DROS > costmap_ros)
virtual void cleanup ()
Method to cleanup resources used on shutdown.
virtual void activate ()
Method to active planner and any threads involved in execution.
virtual void deactivate ()
Method to deactivate planner and any threads involved in execution.
virtual nav_msgs::msg::Path createPlan (const geometry_msgs::msg::PoseStamped &start, const geometry_msgs::msg::PoseStamped &goal)
Method create the plan from a starting and ending goal.
Private Member Functions
void onForwardTrailMsg (const nav_msgs::msg::Path::ConstPtr &trailMessage)
void publishGoalMarker (const geometry_msgs::msg::Pose &pose, double r, double g, double b)
void cleanMarkers ()
void createDefaultBackwardPath (const geometry_msgs::msg::PoseStamped &start, const geometry_msgs::msg::PoseStamped &goal, std::vector< geometry_msgs::msg::PoseStamped > &plan)
Private Attributes
rclcpp_lifecycle::LifecycleNode::SharedPtr nh_
std::shared_ptr< rclcpp_lifecycle::LifecyclePublisher< nav_msgs::msg::Path > > planPub_
std::shared_ptr< rclcpp_lifecycle::LifecyclePublisher< visualization_msgs::msg::MarkerArray > > markersPub_
std::shared_ptr< nav2_costmap_2d::Costmap2DROS > costmap_ros_
double skip_straight_motion_distance_
double puresSpinningRadStep_
std::string name_
std::shared_ptr< tf2_ros::Buffer > tf_
double transform_tolerance_
Detailed Description
Definition at line 31 of file backward_global_planner.hpp.
Constructor & Destructor Documentation
BackwardGlobalPlanner()
cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::BackwardGlobalPlanner ()
Constructor()
Definition at line 48 of file backward_global_planner.cpp.
 {
   skip_straight_motion_distance_ = 0.2;
   puresSpinningRadStep_ = 1000;  // rads
 }
~BackwardGlobalPlanner()
cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::~BackwardGlobalPlanner () virtual
Virtual destructor.
Definition at line 54 of file backward_global_planner.cpp.
 {}
Member Function Documentation
activate()
void cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::activate () virtual
Method to active planner and any threads involved in execution.
activate()
Definition at line 94 of file backward_global_planner.cpp.
 {
   RCLCPP_INFO_STREAM(nh_->get_logger(), "[BackwardGlobalPlanner] activating planner");
   planPub_->on_activate();
   markersPub_->on_activate();
 }
cleanMarkers()
void cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::cleanMarkers () private
Definition at line 161 of file backward_global_planner.cpp.
 {
   visualization_msgs::msg::Marker marker;
   marker.header.frame_id = this->costmap_ros_->getGlobalFrameID();
   marker.header.stamp = nh_->now();
   marker.ns = "my_namespace2";
   marker.id = 0;
   marker.action = visualization_msgs::msg::Marker::DELETEALL;
   visualization_msgs::msg::MarkerArray ma;
   ma.markers.push_back(marker);
   markersPub_->publish(ma);
 }
cleanup()
void cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::cleanup () virtual
Method to cleanup resources used on shutdown.
cleanup()
Definition at line 87 of file backward_global_planner.cpp.
 { this->cleanMarkers(); }
configure()
void cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::configure (const rclcpp_lifecycle::LifecycleNode::WeakPtr & parent, std::string name, std::shared_ptr< tf2_ros::Buffer > tf, std::shared_ptr< nav2_costmap_2d::Costmap2DROS > costmap_ros) virtual
Parameters
parent pointer to user's node
name The name of this planner
tf A pointer to a TF buffer
costmap_ros A pointer to the costmap
initialize()
Definition at line 61 of file backward_global_planner.cpp.
 {
   this->nh_ = parent.lock();
   name_ = name;
   tf_ = tf;
   transform_tolerance_ = 0.1;
   // RCLCPP_INFO_NAMED(nh_->get_logger(), "Backwards", "BackwardGlobalPlanner initialize");
   costmap_ros_ = costmap_ros;
   // RCLCPP_WARN_NAMED(nh_->get_logger(), "Backwards", "initializating global planner, costmap address: %ld",
   // (long)costmap_ros);
   planPub_ = nh_->create_publisher<nav_msgs::msg::Path>("backward_planner/global_plan", 1);
   markersPub_ =
     nh_->create_publisher<visualization_msgs::msg::MarkerArray>("backward_planner/markers", 1);
   declareOrSet(nh_, name_ + ".transform_tolerance", transform_tolerance_);
 }
References declareOrSet().
createDefaultBackwardPath()
void cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::createDefaultBackwardPath (const geometry_msgs::msg::PoseStamped & start, const geometry_msgs::msg::PoseStamped & goal, std::vector< geometry_msgs::msg::PoseStamped > & plan) private
defaultBackwardPath()
Definition at line 181 of file backward_global_planner.cpp.
 {
   auto q = start.pose.orientation;
   geometry_msgs::msg::PoseStamped pose;
   pose = start;
   double dx = start.pose.position.x - goal.pose.position.x;
   double dy = start.pose.position.y - goal.pose.position.y;
   double length = sqrt(dx * dx + dy * dy);
   geometry_msgs::msg::PoseStamped prevState;
   if (length > skip_straight_motion_distance_)
   {
     // skip initial pure spinning and initial straight motion
     RCLCPP_INFO(
       nh_->get_logger(), "1 - heading to goal position pure spinning radstep: %lf",
       puresSpinningRadStep_);
     double heading_direction = atan2(dy, dx);
     double startyaw = tf2::getYaw(q);
     double offset = angles::shortest_angular_distance(startyaw, heading_direction);
     heading_direction = startyaw + offset;
     prevState = cl_move_base_z::makePureSpinningSubPlan(
       start, heading_direction, plan, puresSpinningRadStep_);
     RCLCPP_INFO(nh_->get_logger(), "2 - going forward keep orientation pure straight");
     prevState =
       cl_move_base_z::makePureStraightSubPlan(prevState, goal.pose.position, length, plan);
   }
   else
   {
     prevState = start;
   }
   RCLCPP_WARN_STREAM(
     nh_->get_logger(), "[BackwardGlobalPlanner] backward global plan size:  " << plan.size());
 }
References cl_move_base_z::makePureSpinningSubPlan(), cl_move_base_z::makePureStraightSubPlan(), and sm_atomic_performance_test_a_1::start.
createPlan()
nav_msgs::msg::Path cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::createPlan (const geometry_msgs::msg::PoseStamped & start, const geometry_msgs::msg::PoseStamped & goal) virtual
Method create the plan from a starting and ending goal.
Parameters
start The starting pose of the robot
goal The goal pose of the robot
Returns
The sequence of poses to get from start to goal, if any
makePlan()
Definition at line 228 of file backward_global_planner.cpp.
 {
   RCLCPP_INFO_STREAM(
     nh_->get_logger(), "[BackwardGlobalPlanner] goal frame id: "
                          << goal.header.frame_id << " pose: " << goal.pose.position);
   RCLCPP_INFO_STREAM(
     nh_->get_logger(), "[BackwardGlobalPlanner] goal pose frame id: " << goal.header.frame_id);
   rclcpp::Duration ttol = rclcpp::Duration::from_seconds(transform_tolerance_);
   //---------------------------------------------------------------------
   geometry_msgs::msg::PoseStamped transformedStart;
   nav_2d_utils::transformPose(tf_, costmap_ros_->getGlobalFrameID(), start, transformedStart, ttol);
   transformedStart.header.frame_id = costmap_ros_->getGlobalFrameID();
   //---------------------------------------------------------------------
   geometry_msgs::msg::PoseStamped transformedGoal;
   nav_2d_utils::transformPose(tf_, costmap_ros_->getGlobalFrameID(), goal, transformedGoal, ttol);
   transformedGoal.header.frame_id = costmap_ros_->getGlobalFrameID();
   RCLCPP_INFO_STREAM(
     nh_->get_logger(), "[BackwardGlobalPlanner] creating default backward global plan");
   //---------------------------------------------------------------------
   std::vector<geometry_msgs::msg::PoseStamped> plan;
   this->createDefaultBackwardPath(transformedStart, transformedGoal, plan);
   RCLCPP_INFO_STREAM(nh_->get_logger(), "[BackwardGlobalPlanner] publishing markers");
   publishGoalMarker(transformedGoal.pose, 1.0, 0, 1.0);
   nav_msgs::msg::Path planMsg;
   planMsg.poses = plan;
   planMsg.header.stamp = this->nh_->now();
   planMsg.header.frame_id = this->costmap_ros_->getGlobalFrameID();
   //---------------------------------------------------------------------
   // check plan rejection if obstacle is found
   bool acceptedGlobalPlan = true;
   RCLCPP_INFO_STREAM(
     nh_->get_logger(), "[BackwardGlobalPlanner] checking backwards trajectory on costmap");
   auto costmap2d = this->costmap_ros_->getCostmap();
   for (auto & p : plan)
   {
     unsigned int mx, my;
     costmap2d->worldToMap(p.pose.position.x, p.pose.position.y, mx, my);
     auto cost = costmap2d->getCost(mx, my);
     // static const unsigned char NO_INFORMATION = 255;
     // static const unsigned char LETHAL_OBSTACLE = 254;
     // static const unsigned char INSCRIBED_INFLATED_OBSTACLE = 253;
     // static const unsigned char FREE_SPACE = 0;
     if (cost >= nav2_costmap_2d::INSCRIBED_INFLATED_OBSTACLE)
     {
       acceptedGlobalPlan = false;
       break;
     }
   }
   if (!acceptedGlobalPlan)
   {
     RCLCPP_WARN_STREAM(
       nh_->get_logger(),
       "[BackwardGlobalPlanner] backward plan request is not accepted, returning "
       "empty path");
     planMsg.poses.clear();
   }
   RCLCPP_WARN_STREAM(
     nh_->get_logger(), "[BackwardGlobalPlanner] backward global plan publishing path. poses count: "
                          << planMsg.poses.size());
   planPub_->publish(planMsg);
   return planMsg;
 }
References cl_move_base_z::pure_spinning_local_planner::publishGoalMarker(), and sm_atomic_performance_test_a_1::start.
deactivate()
void cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::deactivate () virtual
Method to deactivate planner and any threads involved in execution.
deactivate()
Definition at line 106 of file backward_global_planner.cpp.
 {
   RCLCPP_INFO_STREAM(nh_->get_logger(), "[BackwardGlobalPlanner] deactivating planner");
   // clear
   nav_msgs::msg::Path planMsg;
   planMsg.header.stamp = nh_->now();
   planPub_->publish(planMsg);
   planPub_->on_deactivate();
   this->cleanMarkers();
   markersPub_->on_deactivate();
 }
onForwardTrailMsg()
void cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::onForwardTrailMsg (const nav_msgs::msg::Path::ConstPtr & trailMessage) private
publishGoalMarker()
void cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::publishGoalMarker (const geometry_msgs::msg::Pose & pose, double r, double g, double b) private
publishGoalMarker()
Definition at line 125 of file backward_global_planner.cpp.
 {
   double phi = tf2::getYaw(pose.orientation);
   visualization_msgs::msg::Marker marker;
   marker.header.frame_id = this->costmap_ros_->getGlobalFrameID();
   marker.header.stamp = nh_->now();
   marker.ns = "my_namespace2";
   marker.id = 0;
   marker.type = visualization_msgs::msg::Marker::ARROW;
   marker.action = visualization_msgs::msg::Marker::ADD;
   marker.lifetime = rclcpp::Duration(0s);
   marker.scale.x = 0.1;
   marker.scale.y = 0.3;
   marker.scale.z = 0.1;
   marker.color.a = 1.0;
   marker.color.r = r;
   marker.color.g = g;
   marker.color.b = b;
   geometry_msgs::msg::Point start, end;
   start.x = pose.position.x;
   start.y = pose.position.y;
   end.x = pose.position.x + 0.5 * cos(phi);
   end.y = pose.position.y + 0.5 * sin(phi);
   marker.points.push_back(start);
   marker.points.push_back(end);
   visualization_msgs::msg::MarkerArray ma;
   ma.markers.push_back(marker);
   markersPub_->publish(ma);
 }
References service_node_3::s, and sm_atomic_performance_test_a_1::start.
Member Data Documentation
costmap_ros_
std::shared_ptr<nav2_costmap_2d::Costmap2DROS> cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::costmap_ros_ private
Definition at line 85 of file backward_global_planner.hpp.
markersPub_
std::shared_ptr<rclcpp_lifecycle::LifecyclePublisher<visualization_msgs::msg::MarkerArray> > cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::markersPub_ private
Definition at line 83 of file backward_global_planner.hpp.
name_
std::string cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::name_ private
Definition at line 96 of file backward_global_planner.hpp.
nh_
rclcpp_lifecycle::LifecycleNode::SharedPtr cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::nh_ private
Definition at line 78 of file backward_global_planner.hpp.
planPub_
std::shared_ptr<rclcpp_lifecycle::LifecyclePublisher<nav_msgs::msg::Path> > cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::planPub_ private
Definition at line 80 of file backward_global_planner.hpp.
puresSpinningRadStep_
double cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::puresSpinningRadStep_ private
Definition at line 94 of file backward_global_planner.hpp.
skip_straight_motion_distance_
double cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::skip_straight_motion_distance_ private
Definition at line 92 of file backward_global_planner.hpp.
tf_
std::shared_ptr<tf2_ros::Buffer> cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::tf_ private
Definition at line 98 of file backward_global_planner.hpp.
transform_tolerance_
double cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::transform_tolerance_ private
Definition at line 100 of file backward_global_planner.hpp.
The documentation for this class was generated from the following files:
smacc2_client_library/move_base_z_client/custom_planners/backward_global_planner/include/backward_global_planner/backward_global_planner.hpp
smacc2_client_library/move_base_z_client/custom_planners/backward_global_planner/src/backward_global_planner/backward_global_planner.cpp