SMACC2: cl_move_base_z::WaypointNavigator Class Reference
cl_move_base_z::WaypointNavigator Class Reference
#include <waypoints_navigator.hpp>
Public Member Functions
WaypointNavigator ()
void onInitialize () override
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void loadWayPointsFromFile (std::string filepath)
void loadWayPointsFromFile2 (std::string filepath)
void setWaypoints (const std::vector< geometry_msgs::msg::Pose > &waypoints)
void setWaypoints (const std::vector< Pose2D > &waypoints)
void sendNextGoal ()
void stopWaitingResult ()
const std::vector< geometry_msgs::msg::Pose > & getWaypoints () const
long getCurrentWaypointIndex () const
void rewind (int count)
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Public Attributes
WaypointEventDispatcher waypointsEventDispatcher
ClMoveBaseZ * client_
int currentWaypoint_
Private Member Functions
void insertWaypoint (int index, geometry_msgs::msg::Pose &newpose)
void removeWaypoint (int index)
void onGoalReached (ClMoveBaseZ::WrappedResult &res)
void onGoalCancelled (ClMoveBaseZ::WrappedResult &)
void onGoalAborted (ClMoveBaseZ::WrappedResult &)
Private Attributes
std::vector< geometry_msgs::msg::Pose > waypoints_
std::vector< std::string > waypointsNames_
boost::signals2::connection succeddedConnection_
boost::signals2::connection abortedConnection_
boost::signals2::connection cancelledConnection_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 46 of file waypoints_navigator.hpp.
Constructor & Destructor Documentation
WaypointNavigator()
cl_move_base_z::WaypointNavigator::WaypointNavigator ()
Definition at line 31 of file waypoints_navigator.cpp.
 : currentWaypoint_(0), waypoints_(0) {}
Member Function Documentation
getCurrentWaypointIndex()
long cl_move_base_z::WaypointNavigator::getCurrentWaypointIndex () const
Definition at line 168 of file waypoints_navigator.cpp.
 { return currentWaypoint_; }
References currentWaypoint_.
Referenced by cl_move_base_z::CbNavigateNextWaypoint::onEntry().
getWaypoints()
const std::vector< geometry_msgs::msg::Pose > & cl_move_base_z::WaypointNavigator::getWaypoints () const
Definition at line 163 of file waypoints_navigator.cpp.
 {
   return waypoints_;
 }
References waypoints_.
insertWaypoint()
void cl_move_base_z::WaypointNavigator::insertWaypoint (int index, geometry_msgs::msg::Pose & newpose) private
Definition at line 122 of file waypoints_navigator.cpp.
 {
   if (index >= 0 && index <= (int)waypoints_.size())
   {
     waypoints_.insert(waypoints_.begin(), index, newpose);
   }
 }
References waypoints_.
loadWayPointsFromFile()
void cl_move_base_z::WaypointNavigator::loadWayPointsFromFile (std::string filepath)
Definition at line 171 of file waypoints_navigator.cpp.
 {
   RCLCPP_INFO_STREAM(getLogger(), "[WaypointNavigator] Loading file:" << filepath);
   this->waypoints_.clear();
   std::ifstream ifs(filepath.c_str(), std::ifstream::in);
   if (ifs.good() == false)
   {
     throw std::string("Waypoints file not found");
   }
   try
   {
 #ifdef HAVE_NEW_YAMLCPP
     YAML::Node node = YAML::Load(ifs);
 #else
     YAML::Parser parser(ifs);
     parser.GetNextDocument(node);
 #endif
 #ifdef HAVE_NEW_YAMLCPP
     const YAML::Node & wp_node_tmp = node["waypoints"];
     const YAML::Node * wp_node = wp_node_tmp ? &wp_node_tmp : NULL;
 #else
     const YAML::Node * wp_node = node.FindValue("waypoints");
 #endif
     if (wp_node != NULL)
     {
       for (unsigned int i = 0; i < wp_node->size(); ++i)
       {
         // Parse waypoint entries on YAML
         geometry_msgs::msg::Pose wp;
         try
         {
           // (*wp_node)[i]["name"] >> wp.name;
           // (*wp_node)[i]["frame_id"] >> wp.header.frame_id;
           wp.position.x = (*wp_node)[i]["position"]["x"].as<double>();
           wp.position.y = (*wp_node)[i]["position"]["y"].as<double>();
           wp.position.z = (*wp_node)[i]["position"]["z"].as<double>();
           wp.orientation.x = (*wp_node)[i]["orientation"]["x"].as<double>();
           wp.orientation.y = (*wp_node)[i]["orientation"]["y"].as<double>();
           wp.orientation.z = (*wp_node)[i]["orientation"]["z"].as<double>();
           wp.orientation.w = (*wp_node)[i]["orientation"]["w"].as<double>();
           this->waypoints_.push_back(wp);
         }
         catch (...)
         {
           RCLCPP_ERROR(getLogger(), "parsing waypoint file, syntax error in point %d", i);
         }
       }
       RCLCPP_INFO_STREAM(getLogger(), "Parsed " << this->waypoints_.size() << " waypoints.");
     }
     else
     {
       RCLCPP_WARN_STREAM(getLogger(), "Couldn't find any waypoints in the provided yaml file.");
     }
   }
   catch (const YAML::ParserException & ex)
   {
     RCLCPP_ERROR_STREAM(
       getLogger(), "Error loading the Waypoints YAML file. Incorrect syntax: " << ex.what());
   }
 }
References smacc2::ISmaccComponent::getLogger(), generate_debs::parser, and waypoints_.
Referenced by sm_dance_bot::OrNavigation::loadWaypointsFromYaml(), sm_dance_bot_lite::OrNavigation::loadWaypointsFromYaml(), and sm_dance_bot_strikes_back::OrNavigation::loadWaypointsFromYaml().
loadWayPointsFromFile2()
void cl_move_base_z::WaypointNavigator::loadWayPointsFromFile2 (std::string filepath)
Definition at line 237 of file waypoints_navigator.cpp.
 {
   RCLCPP_INFO_STREAM(getLogger(), "[WaypointNavigator] Loading file:" << filepath);
   this->waypoints_.clear();
   std::ifstream ifs(filepath.c_str(), std::ifstream::in);
   if (ifs.good() == false)
   {
     throw std::string("Waypoints file not found");
   }
   try
   {
 #ifdef HAVE_NEW_YAMLCPP
     YAML::Node node = YAML::Load(ifs);
 #else
     YAML::Parser parser(ifs);
     parser.GetNextDocument(node);
 #endif
 #ifdef HAVE_NEW_YAMLCPP
     const YAML::Node & wp_node_tmp = node["waypoints"];
     const YAML::Node * wp_node = wp_node_tmp ? &wp_node_tmp : NULL;
 #else
     const YAML::Node * wp_node = node.FindValue("waypoints");
 #endif
     if (wp_node != NULL)
     {
       for (unsigned int i = 0; i < wp_node->size(); ++i)
       {
         // Parse waypoint entries on YAML
         geometry_msgs::msg::Pose wp;
         try
         {
           // (*wp_node)[i]["name"] >> wp.name;
           // (*wp_node)[i]["frame_id"] >> wp.header.frame_id;
           wp.position.x = (*wp_node)[i]["x"].as<double>();
           wp.position.y = (*wp_node)[i]["y"].as<double>();
           auto name = (*wp_node)[i]["name"].as<std::string>();
           this->waypoints_.push_back(wp);
           this->waypointsNames_.push_back(name);
         }
         catch (...)
         {
           RCLCPP_ERROR(getLogger(), "parsing waypoint file, syntax error in point %d", i);
         }
       }
       RCLCPP_INFO_STREAM(getLogger(), "Parsed " << this->waypoints_.size() << " waypoints.");
     }
     else
     {
       RCLCPP_WARN_STREAM(getLogger(), "Couldn't find any waypoints in the provided yaml file.");
     }
   }
   catch (const YAML::ParserException & ex)
   {
     RCLCPP_ERROR_STREAM(
       getLogger(), "Error loading the Waypoints YAML file. Incorrect syntax: " << ex.what());
   }
 }
References smacc2::ISmaccComponent::getLogger(), generate_debs::parser, waypoints_, and waypointsNames_.
Referenced by sm_aws_warehouse_navigation::OrNavigation::loadWaypointsFromYaml().
onGoalAborted()
void cl_move_base_z::WaypointNavigator::onGoalAborted (ClMoveBaseZ::WrappedResult &) private
Definition at line 40 of file waypoints_navigator.cpp.
 { stopWaitingResult(); }
References stopWaitingResult().
Referenced by sendNextGoal().
onGoalCancelled()
void cl_move_base_z::WaypointNavigator::onGoalCancelled (ClMoveBaseZ::WrappedResult &) private
Definition at line 35 of file waypoints_navigator.cpp.
 {
   stopWaitingResult();
 }
References stopWaitingResult().
Referenced by sendNextGoal().
onGoalReached()
void cl_move_base_z::WaypointNavigator::onGoalReached (ClMoveBaseZ::WrappedResult & res) private
Definition at line 42 of file waypoints_navigator.cpp.
 {
   waypointsEventDispatcher.postWaypointEvent(currentWaypoint_);
   currentWaypoint_++;
   RCLCPP_WARN(
     getLogger(), "[WaypointNavigator] Goal result received, incrementing waypoint index: %ld",
     currentWaypoint_);
   stopWaitingResult();
 }
References currentWaypoint_, smacc2::ISmaccComponent::getLogger(), cl_move_base_z::WaypointEventDispatcher::postWaypointEvent(), stopWaitingResult(), and waypointsEventDispatcher.
Referenced by sendNextGoal().
onInitialize()
void cl_move_base_z::WaypointNavigator::onInitialize () override virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 33 of file waypoints_navigator.cpp.
 { client_ = dynamic_cast<ClMoveBaseZ *>(owner_); }
References client_, and smacc2::ISmaccComponent::owner_.
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_move_base_z::WaypointNavigator::onOrthogonalAllocation () inline
Definition at line 58 of file waypoints_navigator.hpp.
   {
     waypointsEventDispatcher.initialize<TSourceObject, TOrthogonal>(client_);
   }
References client_, cl_move_base_z::WaypointEventDispatcher::initialize(), and waypointsEventDispatcher.
removeWaypoint()
void cl_move_base_z::WaypointNavigator::removeWaypoint (int index) private
Definition at line 155 of file waypoints_navigator.cpp.
 {
   if (index >= 0 && index < (int)waypoints_.size())
   {
     waypoints_.erase(waypoints_.begin() + index);
   }
 }
References waypoints_.
rewind()
void cl_move_base_z::WaypointNavigator::rewind (int count)
Definition at line 52 of file waypoints_navigator.cpp.
 {
   currentWaypoint_--;
   if (currentWaypoint_ < 0) currentWaypoint_ = 0;
 }
References currentWaypoint_.
sendNextGoal()
void cl_move_base_z::WaypointNavigator::sendNextGoal ()
Definition at line 68 of file waypoints_navigator.cpp.
 {
   if (currentWaypoint_ >= 0 && currentWaypoint_ < (int)waypoints_.size())
   {
     auto & next = waypoints_[currentWaypoint_];
     ClMoveBaseZ::Goal goal;
     auto p = client_->getComponent<cl_move_base_z::Pose>();
     auto pose = p->toPoseMsg();
     // configuring goal
     goal.pose.header.frame_id = p->getReferenceFrame();
     goal.pose.header.stamp = getNode()->now();
     goal.pose.pose = next;
     RCLCPP_WARN(getLogger(), "[WaypointsNavigator] Configuring default planners");
     auto plannerSwitcher = client_->getComponent<PlannerSwitcher>();
     plannerSwitcher->setDefaultPlanners();
     RCLCPP_WARN(getLogger(), "[WaypointsNavigator] Configuring default goal planner");
     auto goalCheckerSwitcher = client_->getComponent<GoalCheckerSwitcher>();
     goalCheckerSwitcher->setGoalCheckerId("goal_checker");
     // publish stuff
     //rclcpp::sleep_for(5s);
     RCLCPP_INFO(getLogger(), "[WaypointsNavigator] Getting odom tracker");
     auto odomTracker = client_->getComponent<cl_move_base_z::odom_tracker::OdomTracker>();
     if (odomTracker != nullptr)
     {
       RCLCPP_INFO(getLogger(), "[WaypointsNavigator] Storing path in odom tracker");
       odomTracker->pushPath();
       odomTracker->setStartPoint(pose);
       odomTracker->setWorkingMode(cl_move_base_z::odom_tracker::WorkingMode::RECORD_PATH);
     }
     // SEND GOAL
     if (!succeddedConnection_.connected())
     {
       this->succeddedConnection_ = client_->onSucceeded(&WaypointNavigator::onGoalReached, this);
       this->cancelledConnection_ = client_->onAborted(&WaypointNavigator::onGoalCancelled, this);
       this->abortedConnection_ = client_->onCancelled(&WaypointNavigator::onGoalAborted, this);
     }
     client_->sendGoal(goal);
   }
   else
   {
     RCLCPP_WARN(
       getLogger(),
       "[WaypointsNavigator] All waypoints were consumed. There is no more waypoints available.");
   }
 }
References abortedConnection_, cancelledConnection_, client_, currentWaypoint_, smacc2::ISmaccClient::getComponent(), smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getNode(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onAborted(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onCancelled(), onGoalAborted(), onGoalCancelled(), onGoalReached(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), cl_move_base_z::odom_tracker::RECORD_PATH, smacc2::client_bases::SmaccActionClientBase< ActionType >::sendGoal(), cl_move_base_z::PlannerSwitcher::setDefaultPlanners(), cl_move_base_z::GoalCheckerSwitcher::setGoalCheckerId(), succeddedConnection_, cl_move_base_z::Pose::toPoseMsg(), and waypoints_.
Referenced by cl_move_base_z::CbNavigateNextWaypoint::onEntry().
setWaypoints() [1/2]
void cl_move_base_z::WaypointNavigator::setWaypoints (const std::vector< geometry_msgs::msg::Pose > & waypoints)
Definition at line 130 of file waypoints_navigator.cpp.
 {
   this->waypoints_ = waypoints;
 }
References waypoints_.
setWaypoints() [2/2]
void cl_move_base_z::WaypointNavigator::setWaypoints (const std::vector< Pose2D > & waypoints)
Definition at line 135 of file waypoints_navigator.cpp.
 {
   waypoints_.clear();
   waypointsNames_.clear();
   int i = 0;
   for (auto & p : waypoints)
   {
     geometry_msgs::msg::Pose pose;
     pose.position.x = p.x_;
     pose.position.y = p.y_;
     pose.position.z = 0.0;
     tf2::Quaternion q;
     q.setRPY(0, 0, p.yaw_);
     pose.orientation = tf2::toMsg(q);
     waypoints_.push_back(pose);
     waypointsNames_.push_back(std::to_string(i++));
   }
 }
References waypoints_, and waypointsNames_.
stopWaitingResult()
void cl_move_base_z::WaypointNavigator::stopWaitingResult ()
Definition at line 58 of file waypoints_navigator.cpp.
 {
   if (succeddedConnection_.connected())
   {
     this->succeddedConnection_.disconnect();
     this->cancelledConnection_.disconnect();
     this->abortedConnection_.disconnect();
   }
 }
References abortedConnection_, cancelledConnection_, and succeddedConnection_.
Referenced by cl_move_base_z::CbNavigateNextWaypoint::onExit(), onGoalAborted(), onGoalCancelled(), and onGoalReached().
Member Data Documentation
abortedConnection_
boost::signals2::connection cl_move_base_z::WaypointNavigator::abortedConnection_ private
Definition at line 96 of file waypoints_navigator.hpp.
Referenced by sendNextGoal(), and stopWaitingResult().
cancelledConnection_
boost::signals2::connection cl_move_base_z::WaypointNavigator::cancelledConnection_ private
Definition at line 97 of file waypoints_navigator.hpp.
Referenced by sendNextGoal(), and stopWaitingResult().
client_
ClMoveBaseZ* cl_move_base_z::WaypointNavigator::client_
Definition at line 51 of file waypoints_navigator.hpp.
Referenced by onInitialize(), onOrthogonalAllocation(), and sendNextGoal().
currentWaypoint_
int cl_move_base_z::WaypointNavigator::currentWaypoint_
Definition at line 78 of file waypoints_navigator.hpp.
Referenced by getCurrentWaypointIndex(), onGoalReached(), rewind(), and sendNextGoal().
succeddedConnection_
boost::signals2::connection cl_move_base_z::WaypointNavigator::succeddedConnection_ private
Definition at line 95 of file waypoints_navigator.hpp.
Referenced by sendNextGoal(), and stopWaitingResult().
waypoints_
std::vector<geometry_msgs::msg::Pose> cl_move_base_z::WaypointNavigator::waypoints_ private
Definition at line 91 of file waypoints_navigator.hpp.
Referenced by getWaypoints(), insertWaypoint(), loadWayPointsFromFile(), loadWayPointsFromFile2(), removeWaypoint(), sendNextGoal(), and setWaypoints().
waypointsEventDispatcher
WaypointEventDispatcher cl_move_base_z::WaypointNavigator::waypointsEventDispatcher
Definition at line 49 of file waypoints_navigator.hpp.
Referenced by onGoalReached(), and onOrthogonalAllocation().
waypointsNames_
std::vector<std::string> cl_move_base_z::WaypointNavigator::waypointsNames_ private
Definition at line 93 of file waypoints_navigator.hpp.
Referenced by loadWayPointsFromFile2(), and setWaypoints().
The documentation for this class was generated from the following files:
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/components/waypoints_navigator/waypoints_navigator.hpp
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/components/waypoints_navigator/waypoints_navigator.cpp