SMACC2: smacc2::FlashLightSetting Class Reference
smacc2::FlashLightSetting Class Reference
Internal data class to hold individual flash light settings. A setting for each flash light is separately stored in a FlashLightSetting class, which takes care of dynamic specifications such as duration and interval.
#include <FlashLightPlugin.hh>
Public Member Functions
FlashLightSetting (const sdf::ElementPtr &_sdf, const gazebo::physics::ModelPtr &_model, const gazebo::common::Time &_currentTime, gazebo_ros::Node::SharedPtr node)
Constructor. Initialize the setting by the data given to the base plugin.
virtual ~FlashLightSetting ()
Destructor.
virtual void InitPubLight (const gazebo::transport::PublisherPtr &_pubLight) final
Set the publisher and send an initial light command.
virtual void UpdateLightInEnv (const gazebo::common::Time &_currentTime) final
Update the light based on the given time.
virtual const std::string Name () const final
Getter of name.
virtual const gazebo::physics::LinkPtr Link () const final
Getter of link.
virtual void SwitchOn () final
Switch on (enable the flashlight).
virtual void SwitchOff () final
Switch off (disable the flashlight).
virtual void SetDuration (const double _duration, const int _index) final
Set the duration time for the specified block.
virtual void SetDuration (const double _duration) final
Set the duration time for all the blocks.
virtual void SetInterval (const double _interval, const int _index) final
Set the interval time for the specified block.
virtual void SetInterval (const double _interval) final
Set the interval time for all the blocks.
virtual void SetColor (const ignition::math::Color &_color, const int _index) final
Set the color for the specified block.
virtual void SetColor (const ignition::math::Color &_color) final
Set the color for all the blocks.
virtual unsigned int BlockCount () final
Get the number of blocks.
virtual bool RemoveBlock (const int _index) final
Remove a specified block.
virtual void InsertBlock (const double _duration, const double _interval, const ignition::math::Color &_color, const int _index) final
Insert a block. Create a block with specified parameters. If the index is out of range, the block will be appended at the end of the list.
Protected Member Functions
virtual void Flash ()
Flash the light This function is internally used to update the light in the environment.
virtual void Dim ()
Dim the light This function is internally used to update the light in the environment.
virtual ignition::math::Color CurrentColor () final
Get the current color of the light. This is to be used by an inheriting class of FlashLightSetting class.
Private Attributes
std::unique_ptr< FlashLightSettingPrivate > dataPtr
Pointer to private data.
Detailed Description
Internal data class to hold individual flash light settings. A setting for each flash light is separately stored in a FlashLightSetting class, which takes care of dynamic specifications such as duration and interval.
Definition at line 48 of file FlashLightPlugin.hh.
Constructor & Destructor Documentation
FlashLightSetting()
smacc2::FlashLightSetting::FlashLightSetting (const sdf::ElementPtr & _sdf, const gazebo::physics::ModelPtr & _model, const gazebo::common::Time & _currentTime, gazebo_ros::Node::SharedPtr node)
Constructor. Initialize the setting by the data given to the base plugin.
Parameters
[in] _sdf SDF data for the setting.
[in] _model The Model pointer holding the light to control.
[in] _currentTime The current time point.
Definition at line 184 of file FlashLightPlugin.cc.
  : dataPtr(new FlashLightSettingPrivate)
{
  // Get the light name.
  std::string lightId;
  if (_sdf->HasElement("id"))
  {
    lightId = _sdf->Get<std::string>("id");
  }
  else
  {
    gzerr << "Parameter <id> is missing." << std::endl;
  }
  int posDelim = lightId.rfind("/");
  this->dataPtr->name = lightId.substr(posDelim+1, lightId.length());
  // link which holds this light
  this->dataPtr->link = this->dataPtr->FindLinkForLight(
                 _model, this->dataPtr->name,
                 lightId.substr(0, posDelim));
  if (_sdf->HasElement("block"))
  {
    sdf::ElementPtr sdfBlock = _sdf->GetElement("block");
    while (sdfBlock)
    {
      auto block = std::make_shared<Block>();
      // duration
      if (sdfBlock->HasElement("duration"))
      {
        block->duration = sdfBlock->Get<double>("duration");
      }
      else
      {
        //gzerr << "Parameter <duration> is missing in a block." << std::endl;
             block->duration = std::numeric_limits<double>::max();
      }
      // interval
      if (sdfBlock->HasElement("interval"))
      {
        block->interval = sdfBlock->Get<double>("interval");
      }
      else
      {
        //gzerr << "Parameter <interval> is missing in a block." << std::endl;
                   block->interval = std::numeric_limits<double>::max();
      }
      // color
      if (sdfBlock->HasElement("color"))
      {
        block->color = sdfBlock->Get<ignition::math::Color>("color");
      }
      else
      {
        block->color.Reset();
      }
      this->dataPtr->blocks.push_back(block);
      sdfBlock = sdfBlock->GetNextElement("block");
    }
  }
  else
  {
    auto block = std::make_shared<Block>();
    // duration
    if (_sdf->HasElement("duration"))
    {
      block->duration = _sdf->Get<double>("duration");
    }
    else
    {
      // gzerr << "Parameter <duration> is missing." << std::endl;
                         block->duration = std::numeric_limits<double>::max();
    }
    // interval
    if (_sdf->HasElement("interval"))
    {
      block->interval = _sdf->Get<double>("interval");
    }
    else
    {
      // gzerr << "Parameter <interval> is missing." << std::endl;
                         block->interval = std::numeric_limits<double>::max();
    }
    // color
    if (_sdf->HasElement("color"))
    {
      block->color = _sdf->Get<ignition::math::Color>("color");
    }
    else
    {
      block->color.Reset();
    }
    this->dataPtr->blocks.push_back(block);
  }
  // start time
  this->dataPtr->startTime = _currentTime;
  // If link is not nullptr, the light exists.
  if (this->dataPtr->link)
  {
  // void LightCmd(const std_msgs::msg::Int8::SharedPtr msg)
  // {
  //   gzmsg << "Turning on light\n";
  //   if (msg->data == 1)
  //   {
  //     gzmsg << "Turning on light\n";
  //     this->TurnOnAll();
  //     // lightMsg.set_range(15.0);
  //   }
  //   else if (msg->data == 0)
  //   {
  //     gzmsg << "Turning off light\n";
  //     this->TurnOffAll();
  //     // lightMsg.set_range(0.0);
  //   }
  // }
    // range
    if (this->dataPtr->link->GetSDF()->HasElement("light"))
    {
      auto sdfLight = this->dataPtr->link->GetSDF()->GetElement("light");
      while (sdfLight)
      {
        if (sdfLight->Get<std::string>("name") == this->dataPtr->name)
        {
          this->dataPtr->range
            = sdfLight->GetElement("attenuation")->Get<double>("range");
          break;
        }
        sdfLight = sdfLight->GetNextElement("light");
      }
      this->dataPtr->lightExists = true;
    }
  }
}
References dataPtr.
~FlashLightSetting()
smacc2::FlashLightSetting::~FlashLightSetting () virtual
Destructor.
Definition at line 334 of file FlashLightPlugin.cc.
{
}
Member Function Documentation
BlockCount()
unsigned int smacc2::FlashLightSetting::BlockCount () final virtual
Get the number of blocks.
Returns
The number of blocks the object currently has.
Definition at line 514 of file FlashLightPlugin.cc.
{
  return this->dataPtr->blocks.size();
}
References dataPtr.
CurrentColor()
ignition::math::Color smacc2::FlashLightSetting::CurrentColor () final protected virtual
Get the current color of the light. This is to be used by an inheriting class of FlashLightSetting class.
Returns
the color for the current block which the object is using. It returns Black if there is no update about color.
Definition at line 591 of file FlashLightPlugin.cc.
{
  return this->dataPtr->blocks[this->dataPtr->currentBlockIndex]->color;
}
References dataPtr.
Referenced by smacc2::LedSetting::Flash().
Dim()
void smacc2::FlashLightSetting::Dim () protected virtual
Dim the light This function is internally used to update the light in the environment.
Reimplemented in smacc2::LedSetting.
Definition at line 577 of file FlashLightPlugin.cc.
{
  // Set the range to zero.
  this->dataPtr->msg.set_range(0.0);
  // Send the message.
  if (this->dataPtr->lightExists)
  {
    //this->dataPtr->pubLight->Publish(this->dataPtr->msg);
  }
  // Update the state.
  this->dataPtr->flashing = false;
}
References dataPtr.
Referenced by smacc2::LedSetting::Dim(), and UpdateLightInEnv().
Flash()
void smacc2::FlashLightSetting::Flash () protected virtual
Flash the light This function is internally used to update the light in the environment.
Reimplemented in smacc2::LedSetting.
Definition at line 554 of file FlashLightPlugin.cc.
{
  // Set the range to the default value.
  this->dataPtr->msg.set_range(this->dataPtr->range);
  // set the color of light.
  if (this->dataPtr->blocks[this->dataPtr->currentBlockIndex]->color
    != ignition::math::Color::Black)
  {
    msgs::Set(this->dataPtr->msg.mutable_diffuse(),
      this->dataPtr->blocks[this->dataPtr->currentBlockIndex]->color);
    msgs::Set(this->dataPtr->msg.mutable_specular(),
      this->dataPtr->blocks[this->dataPtr->currentBlockIndex]->color);
  }
  // Send the message.
  if (this->dataPtr->lightExists)
  {
    //this->dataPtr->pubLight->Publish(this->dataPtr->msg);
  }
  // Update the state.
  this->dataPtr->flashing = true;
}
References dataPtr.
Referenced by smacc2::LedSetting::Flash(), and UpdateLightInEnv().
InitPubLight()
void smacc2::FlashLightSetting::InitPubLight (const gazebo::transport::PublisherPtr & _pubLight) final virtual
Set the publisher and send an initial light command.
Parameters
[in] _pubLight The publisher to send a message
Definition at line 339 of file FlashLightPlugin.cc.
{
  // The PublisherPtr
  this->dataPtr->pubLight = _pubLight;
  if (this->dataPtr->lightExists)
  {
    // Make a message
    this->dataPtr->msg.set_name(
      this->dataPtr->link->GetScopedName() + "::" + this->dataPtr->name);
    this->dataPtr->msg.set_range(this->dataPtr->range);
  }
}
References dataPtr.
InsertBlock()
void smacc2::FlashLightSetting::InsertBlock (const double _duration, const double _interval, const ignition::math::Color & _color, const int _index) final virtual
Insert a block. Create a block with specified parameters. If the index is out of range, the block will be appended at the end of the list.
Parameters
[in] _duration The duration for the block.
[in] _interval The interval for the block.
[in] _color The color for the block.
[in] _index The index of the block to be inserted into the list.
Definition at line 533 of file FlashLightPlugin.cc.
{
  auto block = std::make_shared<Block>();
  block->duration = _duration;
  block->interval = _interval;
  block->color = _color;
  if (_index < 0 || static_cast<int>(this->dataPtr->blocks.size()) <= _index)
  {
    this->dataPtr->blocks.push_back(block);
  }
  else
  {
    this->dataPtr->blocks.insert(this->dataPtr->blocks.begin() + _index, block);
  }
}
References dataPtr.
Link()
const gazebo::physics::LinkPtr smacc2::FlashLightSetting::Link () const final virtual
Getter of link.
Returns
A pointer to the link element.
Definition at line 427 of file FlashLightPlugin.cc.
{
  return this->dataPtr->link;
}
References dataPtr.
Referenced by smacc2::LedSetting::Dim(), smacc2::LedSetting::Flash(), smacc2::LedSetting::InitPubVisual(), and smacc2::LedSetting::LedSetting().
Name()
const std::string smacc2::FlashLightSetting::Name () const final virtual
Getter of name.
Returns
The name of the light element.
Definition at line 421 of file FlashLightPlugin.cc.
{
  return this->dataPtr->name;
}
References dataPtr.
Referenced by smacc2::LedSetting::InitPubVisual().
RemoveBlock()
bool smacc2::FlashLightSetting::RemoveBlock (const int _index) final virtual
Remove a specified block.
Parameters
[in] _index Index to the block to remove
Returns
True if the block exists and it was removed.
Definition at line 520 of file FlashLightPlugin.cc.
{
  if (_index < 0 || static_cast<int>(this->dataPtr->blocks.size()) <= _index)
  {
    return false;
  }
  this->dataPtr->blocks.erase(this->dataPtr->blocks.begin() + _index);
  return true;
}
References dataPtr.
SetColor() [1/2]
void smacc2::FlashLightSetting::SetColor (const ignition::math::Color & _color) final virtual
Set the color for all the blocks.
Parameters
[in] _color New color to set.
Definition at line 505 of file FlashLightPlugin.cc.
{
  for (auto block: this->dataPtr->blocks)
  {
    block->color = _color;
  }
}
References dataPtr.
SetColor() [2/2]
void smacc2::FlashLightSetting::SetColor (const ignition::math::Color & _color, const int _index) final virtual
Set the color for the specified block.
Parameters
[in] _color New color to set.
[in] _index The index to the block to update.
Definition at line 491 of file FlashLightPlugin.cc.
{
  if (0 <= _index && _index < static_cast<int>(this->dataPtr->blocks.size()))
  {
    this->dataPtr->blocks[_index]->color = _color;
  }
  else
  {
    gzerr << "The given index for block is out of range." << std::endl;
  }
}
References dataPtr.
SetDuration() [1/2]
void smacc2::FlashLightSetting::SetDuration (const double _duration) final virtual
Set the duration time for all the blocks.
Parameters
[in] _duration New duration time to set.
Definition at line 460 of file FlashLightPlugin.cc.
{
  for (auto block: this->dataPtr->blocks)
  {
    block->duration = _duration;
  }
}
References dataPtr.
SetDuration() [2/2]
void smacc2::FlashLightSetting::SetDuration (const double _duration, const int _index) final virtual
Set the duration time for the specified block.
Parameters
[in] _duration New duration time to set.
[in] _index The index to the block to update.
Definition at line 447 of file FlashLightPlugin.cc.
{
  if (0 <= _index && _index < static_cast<int>(this->dataPtr->blocks.size()))
  {
    this->dataPtr->blocks[_index]->duration = _duration;
  }
  else
  {
    gzerr << "The given index for block is out of range." << std::endl;
  }
}
References dataPtr.
SetInterval() [1/2]
void smacc2::FlashLightSetting::SetInterval (const double _interval) final virtual
Set the interval time for all the blocks.
Parameters
[in] _interval New interval time to set.
Definition at line 482 of file FlashLightPlugin.cc.
{
  for (auto block: this->dataPtr->blocks)
  {
    block->interval = _interval;
  }
}
References dataPtr.
SetInterval() [2/2]
void smacc2::FlashLightSetting::SetInterval (const double _interval, const int _index) final virtual
Set the interval time for the specified block.
Parameters
[in] _interval New interval time to set.
[in] _index The index to the block to update.
Definition at line 469 of file FlashLightPlugin.cc.
{
  if (0 <= _index && _index < static_cast<int>(this->dataPtr->blocks.size()))
  {
    this->dataPtr->blocks[_index]->interval = _interval;
  }
  else
  {
    gzerr << "The given index for block is out of range." << std::endl;
  }
}
References dataPtr.
SwitchOff()
void smacc2::FlashLightSetting::SwitchOff () final virtual
Switch off (disable the flashlight).
Definition at line 439 of file FlashLightPlugin.cc.
{
  gzmsg <<  "switch off" << std::endl;
  this->dataPtr->switchOn = false;
}
References dataPtr.
SwitchOn()
void smacc2::FlashLightSetting::SwitchOn () final virtual
Switch on (enable the flashlight).
Definition at line 433 of file FlashLightPlugin.cc.
{
  this->dataPtr->switchOn = true;
}
References dataPtr.
UpdateLightInEnv()
void smacc2::FlashLightSetting::UpdateLightInEnv (const gazebo::common::Time & _currentTime) final virtual
Update the light based on the given time.
Parameters
[in] _currentTime The current point of time to update the lights.
Definition at line 355 of file FlashLightPlugin.cc.
{
  if (this->dataPtr->switchOn)
  {
    this->Flash();
  }
  else
  {
    this->Dim();
  }
  // int index = this->dataPtr->currentBlockIndex;
  // // Reset the start time so the current time is within the current phase.
  // if (_currentTime < this->dataPtr->startTime ||
  //     this->dataPtr->startTime
  //     + this->dataPtr->blocks[index]->duration
  //     + this->dataPtr->blocks[index]->interval <= _currentTime)
  // {
  //   // initialize the start time.
  //   this->dataPtr->startTime = _currentTime;
  //   // proceed to the next block.
  //   index++;
  //   if (index >= static_cast<int>(this->dataPtr->blocks.size()))
  //   {
  //     index = 0;
  //   }
  //   this->dataPtr->currentBlockIndex = index;
  // }
  // if (this->dataPtr->switchOn)
  // {
  //   // time to dim
  //   if (_currentTime - this->dataPtr->startTime
  //     > this->dataPtr->blocks[index]->duration)
  //   {
  //     if (this->dataPtr->flashing)
  //     {
  //       this->Dim();
  //     }
  //   }
  //   // time to flash
  //   else
  //   {
  //     // if there is more than one block, it calls Flash() at the beginning of
  //     // every block.
  //     if (this->dataPtr->blocks.size() > 1
  //       && this->dataPtr->startTime == _currentTime)
  //     {
  //       this->Flash();
  //     }
  //     // otherwise, it calls the function only if the light is not lit yet.
  //     else if (!this->dataPtr->flashing)
  //     {
  //       this->Flash();
  //     }
  //   }
  // }
  // else if (this->dataPtr->flashing)
  // {
  //   this->Dim();
  // }
}
References dataPtr, Dim(), and Flash().
Member Data Documentation
dataPtr
std::unique_ptr<FlashLightSettingPrivate> smacc2::FlashLightSetting::dataPtr private
Pointer to private data.
Definition at line 156 of file FlashLightPlugin.hh.
Referenced by BlockCount(), CurrentColor(), Dim(), Flash(), FlashLightSetting(), InitPubLight(), InsertBlock(), Link(), Name(), RemoveBlock(), SetColor(), SetDuration(), SetInterval(), SwitchOff(), SwitchOn(), and UpdateLightInEnv().
The documentation for this class was generated from the following files:
smacc2_sm_reference_library/sm_husky_barrel_search_1/src/sm_husky_barrel_search_1/gz_plugins/FlashLightPlugin.hh
smacc2_sm_reference_library/sm_husky_barrel_search_1/src/sm_husky_barrel_search_1/gz_plugins/FlashLightPlugin.cc