SMACC2: cl_move_base_z::CbNavigateNextWaypoint Class Reference
cl_move_base_z::CbNavigateNextWaypoint Class Reference
#include <cb_navigate_next_waypoint.hpp>
Public Member Functions
CbNavigateNextWaypoint ()
virtual ~CbNavigateNextWaypoint ()
void onEntry () override
void onExit () override
Public Member Functions inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
virtual ~CbMoveBaseClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Public Attributes
WaypointNavigator * waypointsNavigator_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Protected Attributes inherited from cl_move_base_z::CbMoveBaseClientBehaviorBase
cl_move_base_z::ClMoveBaseZ * moveBaseClient_
Detailed Description
Definition at line 29 of file cb_navigate_next_waypoint.hpp.
Constructor & Destructor Documentation
CbNavigateNextWaypoint()
cl_move_base_z::CbNavigateNextWaypoint::CbNavigateNextWaypoint ()
Definition at line 25 of file cb_navigate_next_waypoint.cpp.
 {}
~CbNavigateNextWaypoint()
cl_move_base_z::CbNavigateNextWaypoint::~CbNavigateNextWaypoint () virtual
Definition at line 27 of file cb_navigate_next_waypoint.cpp.
 {}
Member Function Documentation
onEntry()
void cl_move_base_z::CbNavigateNextWaypoint::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 29 of file cb_navigate_next_waypoint.cpp.
 {
   waypointsNavigator_ = moveBaseClient_->getComponent<WaypointNavigator>();
   waypointsNavigator_->sendNextGoal();
   RCLCPP_INFO(
     getLogger(), "[CbNavigateNextWaypoint] current iteration waypoints i: %ld",
     waypointsNavigator_->getCurrentWaypointIndex());
 }
References smacc2::ISmaccClient::getComponent(), cl_move_base_z::WaypointNavigator::getCurrentWaypointIndex(), smacc2::ISmaccClientBehavior::getLogger(), cl_move_base_z::CbMoveBaseClientBehaviorBase::moveBaseClient_, cl_move_base_z::WaypointNavigator::sendNextGoal(), and waypointsNavigator_.
onExit()
void cl_move_base_z::CbNavigateNextWaypoint::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 38 of file cb_navigate_next_waypoint.cpp.
 { waypointsNavigator_->stopWaitingResult(); }
References cl_move_base_z::WaypointNavigator::stopWaitingResult(), and waypointsNavigator_.
Member Data Documentation
waypointsNavigator_
WaypointNavigator* cl_move_base_z::CbNavigateNextWaypoint::waypointsNavigator_
Definition at line 40 of file cb_navigate_next_waypoint.hpp.
Referenced by onEntry(), and onExit().
The documentation for this class was generated from the following files:
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_navigate_next_waypoint.hpp
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/client_behaviors/cb_navigate_next_waypoint.cpp