SMACC2: smacc2::SmaccClientBehavior Class Reference
smacc2::SmaccClientBehavior Class Reference
#include <smacc_client_behavior.hpp>
Public Member Functions
void onEntry () override
void onExit () override
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Detailed Description
Definition at line 26 of file smacc_client_behavior.hpp.
Member Function Documentation
onEntry()
void smacc2::SmaccClientBehavior::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Reimplemented in cl_keyboard::CbDefaultKeyboardBehavior, sm_advanced_recovery_1::cl_subscriber::CbDefaultSubscriberBehavior, sm_advanced_recovery_1::cl_subscriber::CbWatchdogSubscriberBehavior, sm_dance_bot::cl_string_publisher::CbStringPublisher, sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse_2::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse_3::cl_string_publisher::CbStringPublisher, sm_ferrari::cl_subscriber::CbMySubscriberBehavior, sm_multi_stage_1::cl_subscriber::CbDefaultSubscriberBehavior, sm_multi_stage_1::cl_subscriber::CbWatchdogSubscriberBehavior, sm_pubsub_1::cl_subscriber::CbMySubscriberBehavior, sm_respira_1::cl_subscriber::CbDefaultSubscriberBehavior, sm_respira_1::cl_subscriber::CbWatchdogSubscriberBehavior, sm_three_some::cl_subscriber::CbDefaultSubscriberBehavior, sm_three_some::cl_subscriber::CbWatchdogSubscriberBehavior, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >, cl_ros_publisher::CbDefaultPublishLoop, cl_ros_publisher::CbMutedBehavior< RosMsgType >, cl_ros_publisher::CbPublishOnce< RosMsgType >, cl_ros_timer::CbTimer, cl_ros_timer::CbTimer, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownOnce, cl_ros_timer::CbTimerCountdownOnce, cl_ros_timer::CbTimer, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownOnce, sm_dance_bot::cl_led::CbLEDOff, sm_dance_bot::cl_led::CbLEDOn, sm_dance_bot::cl_lidar::CbLidarSensor, sm_dance_bot::cl_service3::CbService3, sm_dance_bot::cl_temperature_sensor::CbConditionTemperatureSensor, sm_dance_bot_strikes_back::cl_led::CbLEDOff, sm_dance_bot_strikes_back::cl_led::CbLEDOn, sm_dance_bot_strikes_back::cl_lidar::CbLidarSensor, sm_dance_bot_strikes_back::cl_service3::CbService3, sm_dance_bot_strikes_back::cl_temperature_sensor::CbConditionTemperatureSensor, sm_dance_bot_warehouse::cl_led::CbLEDOff, sm_dance_bot_warehouse::cl_led::CbLEDOn, sm_dance_bot_warehouse::cl_lidar::CbLidarSensor, sm_dance_bot_warehouse::cl_service3::CbService3, sm_dance_bot_warehouse::cl_temperature_sensor::CbConditionTemperatureSensor, sm_dance_bot_warehouse_2::cl_led::CbLEDOff, sm_dance_bot_warehouse_2::cl_led::CbLEDOn, sm_dance_bot_warehouse_2::cl_lidar::CbLidarSensor, sm_dance_bot_warehouse_2::cl_service3::CbService3, sm_dance_bot_warehouse_2::cl_temperature_sensor::CbConditionTemperatureSensor, sm_dance_bot_warehouse_3::cl_led::CbLEDOff, sm_dance_bot_warehouse_3::cl_led::CbLEDOn, sm_dance_bot_warehouse_3::cl_lidar::CbLidarSensor, sm_dance_bot_warehouse_3::cl_service3::CbService3, sm_dance_bot_warehouse_3::cl_temperature_sensor::CbConditionTemperatureSensor, sm_husky_barrel_search_1::cl_led_array::CbLEDOff, and sm_husky_barrel_search_1::cl_led_array::CbLEDOn.
Definition at line 25 of file smacc_client_behavior.cpp.
{
  RCLCPP_DEBUG(
    getLogger(), "[%s] Default empty SmaccClientBehavior onEntry", this->getName().c_str());
}
References smacc2::ISmaccClientBehavior::getLogger(), and smacc2::ISmaccClientBehavior::getName().
onExit()
void smacc2::SmaccClientBehavior::onExit () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Reimplemented in cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClientType >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClLidarSensor >, cl_multirole_sensor::CbDefaultMultiRoleSensorBehavior< ClTemperatureSensor >, cl_ros_publisher::CbDefaultPublishLoop, cl_ros_publisher::CbMutedBehavior< RosMsgType >, cl_ros_publisher::CbPublishOnce< RosMsgType >, cl_ros_timer::CbTimer, cl_ros_timer::CbTimerCountdownLoop, cl_ros_timer::CbTimerCountdownOnce, sm_dance_bot::cl_led::CbLEDOff, sm_dance_bot::cl_led::CbLEDOn, sm_dance_bot::cl_string_publisher::CbStringPublisher, sm_dance_bot_strikes_back::cl_led::CbLEDOff, sm_dance_bot_strikes_back::cl_led::CbLEDOn, sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse::cl_led::CbLEDOff, sm_dance_bot_warehouse::cl_led::CbLEDOn, sm_dance_bot_warehouse::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse_2::cl_led::CbLEDOff, sm_dance_bot_warehouse_2::cl_led::CbLEDOn, sm_dance_bot_warehouse_2::cl_string_publisher::CbStringPublisher, sm_dance_bot_warehouse_3::cl_led::CbLEDOff, sm_dance_bot_warehouse_3::cl_led::CbLEDOn, sm_dance_bot_warehouse_3::cl_string_publisher::CbStringPublisher, sm_husky_barrel_search_1::cl_led_array::CbLEDOff, and sm_husky_barrel_search_1::cl_led_array::CbLEDOn.
Definition at line 31 of file smacc_client_behavior.cpp.
{
  RCLCPP_DEBUG(
    getLogger(), "[%s] Default empty SmaccClientBehavior onExit", this->getName().c_str());
}
References smacc2::ISmaccClientBehavior::getLogger(), and smacc2::ISmaccClientBehavior::getName().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/smacc_client_behavior.hpp
smacc2/src/smacc2/smacc_client_behavior.cpp