SMACC2: smacc2::client_bases::SmaccPublisherClient Class Reference
smacc2::client_bases::SmaccPublisherClient Class Reference
#include <smacc_publisher_client.hpp>
Public Member Functions
SmaccPublisherClient ()
virtual ~SmaccPublisherClient ()
template<typename MessageType >
void configure (std::string topicName)
template<typename MessageType >
void publish (const MessageType &msg)
Public Member Functions inherited from smacc2::ISmaccClient
ISmaccClient ()
virtual ~ISmaccClient ()
virtual void onInitialize ()
virtual std::string getName () const
template<typename TComponent >
TComponent * getComponent ()
template<typename TComponent >
TComponent * getComponent (std::string name)
template<typename TComponent >
TComponent * getComponent (int index)
virtual smacc2::introspection::TypeInfo::Ptr getType ()
ISmaccStateMachine * getStateMachine ()
template<typename TSmaccSignal , typename T >
void connectSignal (TSmaccSignal &signal, void(T::*callback)(), T *object)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
void getComponents (std::vector< std::shared_ptr< ISmaccComponent > > &components)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
Public Attributes
std::optional< std::string > topicName
std::optional< int > queueSize
std::optional< rmw_qos_durability_policy_t > durability
std::optional< rmw_qos_reliability_policy_t > reliability
rclcpp::PublisherBase::SharedPtr pub_
Private Attributes
bool initialized_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccClient
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes inherited from smacc2::ISmaccClient
std::map< ComponentKey, std::shared_ptr< smacc2::ISmaccComponent > > components_
Detailed Description
Definition at line 30 of file smacc_publisher_client.hpp.
Constructor & Destructor Documentation
SmaccPublisherClient()
smacc2::client_bases::SmaccPublisherClient::SmaccPublisherClient ()
Definition at line 27 of file smacc_publisher_client.cpp.
{ initialized_ = false; }
References initialized_.
~SmaccPublisherClient()
smacc2::client_bases::SmaccPublisherClient::~SmaccPublisherClient () virtual
Definition at line 29 of file smacc_publisher_client.cpp.
{}
Member Function Documentation
configure()
template<typename MessageType > void smacc2::client_bases::SmaccPublisherClient::configure (std::string topicName) inline
Definition at line 42 of file smacc_publisher_client.hpp.
  {
    this->topicName = topicName;
    if (!initialized_)
    {
      if (!this->topicName)
      {
        RCLCPP_ERROR(getLogger(), "topic publisher with no topic name set. Skipping advertising.");
        return;
      }
      if (!queueSize) queueSize = 1;
      if (!durability) durability = RMW_QOS_POLICY_DURABILITY_SYSTEM_DEFAULT;
      if (!reliability) reliability = RMW_QOS_POLICY_RELIABILITY_SYSTEM_DEFAULT;
      rclcpp::SensorDataQoS qos;
      qos.keep_last(*queueSize);
      qos.durability(*durability);
      qos.reliability(*reliability);
      RCLCPP_INFO_STREAM(
        getLogger(), "[" << this->getName() << "] Client Publisher to topic: " << topicName);
      pub_ = getNode()->create_publisher<MessageType>(*(this->topicName), qos);
      this->initialized_ = true;
    }
  }
References durability, smacc2::ISmaccClient::getLogger(), smacc2::ISmaccClient::getName(), smacc2::ISmaccClient::getNode(), initialized_, pub_, queueSize, reliability, and topicName.
publish()
template<typename MessageType > void smacc2::client_bases::SmaccPublisherClient::publish (const MessageType & msg) inline
Definition at line 70 of file smacc_publisher_client.hpp.
  {
    //pub_->publish(msg);
    std::dynamic_pointer_cast<rclcpp::Publisher<MessageType>>(pub_)->publish(msg);
  }
References pub_, and publish().
Referenced by sm_dance_bot::cl_string_publisher::CbStringPublisher::onExit(), sm_dance_bot_strikes_back::cl_string_publisher::CbStringPublisher::onExit(), sm_dance_bot_warehouse::cl_string_publisher::CbStringPublisher::onExit(), sm_dance_bot_warehouse_2::cl_string_publisher::CbStringPublisher::onExit(), sm_dance_bot_warehouse_3::cl_string_publisher::CbStringPublisher::onExit(), and publish().
Member Data Documentation
durability
std::optional<rmw_qos_durability_policy_t> smacc2::client_bases::SmaccPublisherClient::durability
Definition at line 35 of file smacc_publisher_client.hpp.
Referenced by configure().
initialized_
bool smacc2::client_bases::SmaccPublisherClient::initialized_ private
Definition at line 79 of file smacc_publisher_client.hpp.
Referenced by configure(), and SmaccPublisherClient().
pub_
rclcpp::PublisherBase::SharedPtr smacc2::client_bases::SmaccPublisherClient::pub_
Definition at line 76 of file smacc_publisher_client.hpp.
Referenced by configure(), and publish().
queueSize
std::optional<int> smacc2::client_bases::SmaccPublisherClient::queueSize
Definition at line 34 of file smacc_publisher_client.hpp.
Referenced by configure().
reliability
std::optional<rmw_qos_reliability_policy_t> smacc2::client_bases::SmaccPublisherClient::reliability
Definition at line 36 of file smacc_publisher_client.hpp.
Referenced by configure().
topicName
std::optional<std::string> smacc2::client_bases::SmaccPublisherClient::topicName
Definition at line 33 of file smacc_publisher_client.hpp.
Referenced by configure(), and cl_ros_publisher::ClRosPublisher::configure().
The documentation for this class was generated from the following files:
smacc2/include/smacc2/client_bases/smacc_publisher_client.hpp
smacc2/src/smacc2/client_bases/smacc_publisher_client.cpp