SMACC2: cl_move_base_z::CbWaitPose Class Reference
cl_move_base_z::CbWaitPose Class Reference
#include <cb_wait_pose.hpp>
Public Member Functions
CbWaitPose ()
virtual ~CbWaitPose ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
void onEntry () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Protected Attributes
cl_move_base_z::ClMoveBaseZ * moveBaseClient_
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void executeOnEntry () override
void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Detailed Description
Definition at line 28 of file cb_wait_pose.hpp.
Constructor & Destructor Documentation
CbWaitPose()
cl_move_base_z::CbWaitPose::CbWaitPose ()
Definition at line 29 of file cb_wait_pose.cpp.
 {}
~CbWaitPose()
cl_move_base_z::CbWaitPose::~CbWaitPose () virtual
Definition at line 31 of file cb_wait_pose.cpp.
 {}
Member Function Documentation
onEntry()
void cl_move_base_z::CbWaitPose::onEntry () override virtual
Reimplemented from smacc2::ISmaccClientBehavior.
Definition at line 33 of file cb_wait_pose.cpp.
 {
   auto pose = this->moveBaseClient_->getComponent<Pose>();
   try
   {
     pose->waitTransformUpdate(rclcpp::Rate(20));
     auto posemsg = pose->toPoseMsg();
     RCLCPP_INFO_STREAM(getLogger(), "[CbWaitPose] pose arrived: " << std::endl << posemsg);
   }
   catch (std::exception & ex)
   {
     RCLCPP_INFO(getLogger(), "[CbWaitPose] error getting the robot pose");
     this->postFailureEvent();
     return;
   }
   RCLCPP_INFO(getLogger(), "[CbWaitPose] pose received");
   this->postSuccessEvent();
 }
References smacc2::ISmaccClient::getComponent(), smacc2::ISmaccClientBehavior::getLogger(), moveBaseClient_, smacc2::SmaccAsyncClientBehavior::postFailureEvent(), smacc2::SmaccAsyncClientBehavior::postSuccessEvent(), and cl_move_base_z::Pose::waitTransformUpdate().
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_move_base_z::CbWaitPose::onOrthogonalAllocation () inline
Definition at line 35 of file cb_wait_pose.hpp.
   {
     this->requiresClient(moveBaseClient_);
     smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
   }
References moveBaseClient_, and smacc2::ISmaccClientBehavior::requiresClient().
Member Data Documentation
moveBaseClient_
cl_move_base_z::ClMoveBaseZ* cl_move_base_z::CbWaitPose::moveBaseClient_ protected
Definition at line 44 of file cb_wait_pose.hpp.
Referenced by onEntry(), and onOrthogonalAllocation().
The documentation for this class was generated from the following files:
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_wait_pose.hpp
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/client_behaviors/cb_wait_pose.cpp