SMACC2: cl_move_base_z::odom_tracker::OdomTracker Class Reference
cl_move_base_z::odom_tracker::OdomTracker Class Reference
This class track the required distance of the cord based on the external localization system.
#include <odom_tracker.hpp>
Public Member Functions
OdomTracker (std::string odomtopicName="/odom", std::string odomFrame="odom")
virtual void processOdometryMessage (const nav_msgs::msg::Odometry::SharedPtr odom)
odom callback: Updates the path - this must be called periodically for each odometry message.
void setWorkingMode (WorkingMode workingMode)
void setPublishMessages (bool value)
void pushPath ()
void popPath (int pathCount=1, bool keepPreviousPath=false)
void clearPath ()
void setStartPoint (const geometry_msgs::msg::PoseStamped &pose)
void setStartPoint (const geometry_msgs::msg::Pose &pose)
nav_msgs::msg::Path getPath ()
void logStateString ()
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Protected Member Functions
void onInitialize () override
void updateConfiguration ()
virtual void rtPublishPaths (rclcpp::Time timestamp)
virtual bool updateRecordPath (const nav_msgs::msg::Odometry &odom)
virtual bool updateClearPath (const nav_msgs::msg::Odometry &odom)
void updateAggregatedStackPath ()
Protected Member Functions inherited from smacc2::ISmaccComponent
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
Protected Attributes
rclcpp::Publisher< nav_msgs::msg::Path >::SharedPtr robotBasePathPub_
rclcpp::Publisher< nav_msgs::msg::Path >::SharedPtr robotBasePathStackedPub_
rclcpp::Subscription< nav_msgs::msg::Odometry >::SharedPtr odomSub_
double recordPointDistanceThreshold_
How much distance there is between two points of the path.
double recordAngularDistanceThreshold_
Meters.
double clearPointDistanceThreshold_
rads
double clearAngularDistanceThreshold_
rads
std::string odomFrame_
std::string odomTopicName_
bool publishMessages
nav_msgs::msg::Path baseTrajectory_
Processed path for the mouth of the reel.
WorkingMode workingMode_
std::vector< nav_msgs::msg::Path > pathStack_
nav_msgs::msg::Path aggregatedStackPathMsg_
bool subscribeToOdometryTopic_
std::mutex m_mutex_
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
This class track the required distance of the cord based on the external localization system.
Definition at line 52 of file odom_tracker.hpp.
Constructor & Destructor Documentation
OdomTracker()
cl_move_base_z::odom_tracker::OdomTracker::OdomTracker (std::string odomtopicName = "/odom", std::string odomFrame = "odom")
Definition at line 32 of file odom_tracker.cpp.
 {
   workingMode_ = WorkingMode::RECORD_PATH;
   publishMessages = true;
   subscribeToOdometryTopic_ = true;
   odomFrame_ = odomFrame;
   odomTopicName_ = odomTopicName;
 }
References odomFrame_, odomTopicName_, publishMessages, cl_move_base_z::odom_tracker::RECORD_PATH, subscribeToOdometryTopic_, and workingMode_.
Member Function Documentation
clearPath()
void cl_move_base_z::odom_tracker::OdomTracker::clearPath ()
Definition at line 203 of file odom_tracker.cpp.
 {
   std::lock_guard<std::mutex> lock(m_mutex_);
   baseTrajectory_.poses.clear();
   rtPublishPaths(getNode()->now());
   this->logStateString();
   this->updateAggregatedStackPath();
 }
References baseTrajectory_, smacc2::ISmaccComponent::getNode(), logStateString(), m_mutex_, rtPublishPaths(), and updateAggregatedStackPath().
Referenced by cl_move_base_z::CbNavigateBackwards::onEntry(), sm_dance_bot::radial_motion_states::StiRadialReturn::onExit(), and sm_dance_bot_lite::radial_motion_states::StiRadialReturn::onExit().
getPath()
nav_msgs::msg::Path cl_move_base_z::odom_tracker::OdomTracker::getPath ()
Definition at line 248 of file odom_tracker.cpp.
 {
   std::lock_guard<std::mutex> lock(m_mutex_);
   return this->baseTrajectory_;
 }
References baseTrajectory_, and m_mutex_.
logStateString()
void cl_move_base_z::odom_tracker::OdomTracker::logStateString ()
Definition at line 188 of file odom_tracker.cpp.
 {
   RCLCPP_INFO(getLogger(), "--- odom tracker state ---");
   RCLCPP_INFO(getLogger(), " - path stack size: %ld", pathStack_.size());
   RCLCPP_INFO(getLogger(), " - [STACK-HEAD active path size: %ld]", baseTrajectory_.poses.size());
   int i = 0;
   for (auto & p : pathStack_ | boost::adaptors::reversed)
   {
     RCLCPP_INFO_STREAM(
       getLogger(), " - p " << i << "[" << p.header.stamp << "], size: " << p.poses.size());
     i++;
   }
   RCLCPP_INFO(getLogger(), "---");
 }
References baseTrajectory_, smacc2::ISmaccComponent::getLogger(), and pathStack_.
Referenced by clearPath(), popPath(), and pushPath().
onInitialize()
void cl_move_base_z::odom_tracker::OdomTracker::onInitialize () override protected virtual
Reimplemented from smacc2::ISmaccComponent.
Definition at line 56 of file odom_tracker.cpp.
 {
   // default values
   recordPointDistanceThreshold_ = 0.005;  // 5 mm
   recordAngularDistanceThreshold_ = 0.1;  // radians
   clearPointDistanceThreshold_ = 0.05;    // 5 cm
   clearAngularDistanceThreshold_ = 0.1;   // radi
   auto nh = getNode();
   RCLCPP_WARN(getLogger(), "Initializing Odometry Tracker");
   parameterDeclareAndtryGetOrSet(nh, "odom_frame", this->odomFrame_);
   parameterDeclareAndtryGetOrSet(
     nh, "record_point_distance_threshold", recordPointDistanceThreshold_);
   parameterDeclareAndtryGetOrSet(
     nh, "record_angular_distance_threshold", recordAngularDistanceThreshold_);
   parameterDeclareAndtryGetOrSet(
     nh, "clear_point_distance_threshold", clearPointDistanceThreshold_);
   parameterDeclareAndtryGetOrSet(
     nh, "clear_angular_distance_threshold", clearAngularDistanceThreshold_);
   if (this->subscribeToOdometryTopic_)
   {
     rclcpp::SensorDataQoS qos;
     odomSub_ = nh->create_subscription<nav_msgs::msg::Odometry>(
       odomTopicName_, qos,
       std::bind(&OdomTracker::processOdometryMessage, this, std::placeholders::_1));
   }
   robotBasePathPub_ = nh->create_publisher<nav_msgs::msg::Path>("odom_tracker_path", 1);
   robotBasePathStackedPub_ =
     nh->create_publisher<nav_msgs::msg::Path>("odom_tracker_stacked_path", 1);
 }
References clearAngularDistanceThreshold_, clearPointDistanceThreshold_, smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getNode(), odomFrame_, odomSub_, odomTopicName_, cl_move_base_z::odom_tracker::parameterDeclareAndtryGetOrSet(), processOdometryMessage(), recordAngularDistanceThreshold_, recordPointDistanceThreshold_, robotBasePathPub_, robotBasePathStackedPub_, and subscribeToOdometryTopic_.
popPath()
void cl_move_base_z::odom_tracker::OdomTracker::popPath (int pathCount = 1, bool keepPreviousPath = false)
Definition at line 158 of file odom_tracker.cpp.
 {
   RCLCPP_INFO(getLogger(), "odom_tracker m_mutex acquire");
   std::lock_guard<std::mutex> lock(m_mutex_);
   RCLCPP_INFO(getLogger(), "POP PATH ENTRY");
   this->logStateString();
   if (!keepPreviousPath)
   {
     baseTrajectory_.poses.clear();
   }
   while (popCount > 0 && !pathStack_.empty())
   {
     auto & stacked = pathStack_.back().poses;
     baseTrajectory_.poses.insert(baseTrajectory_.poses.begin(), stacked.begin(), stacked.end());
     pathStack_.pop_back();
     popCount--;
     RCLCPP_INFO(getLogger(), "POP PATH Iteration ");
     this->logStateString();
   }
   RCLCPP_INFO(getLogger(), "POP PATH EXITING");
   this->logStateString();
   RCLCPP_INFO(getLogger(), "odom_tracker m_mutex release");
   this->updateAggregatedStackPath();
 }
References baseTrajectory_, smacc2::ISmaccComponent::getLogger(), logStateString(), m_mutex_, pathStack_, and updateAggregatedStackPath().
Referenced by OdomTrackerActionServer::execute().
processOdometryMessage()
void cl_move_base_z::odom_tracker::OdomTracker::processOdometryMessage (const nav_msgs::msg::Odometry::SharedPtr odom) virtual
odom callback: Updates the path - this must be called periodically for each odometry message.
processOdometryMessage()
Definition at line 447 of file odom_tracker.cpp.
 {
   // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex acquire");
   std::lock_guard<std::mutex> lock(m_mutex_);
   updateConfiguration();
   if (workingMode_ == WorkingMode::RECORD_PATH)
   {
     updateRecordPath(*odom);
   }
   else if (workingMode_ == WorkingMode::CLEAR_PATH)
   {
     updateClearPath(*odom);
   }
   // RCLCPP_WARN(getLogger(),"odomTracker odometry callback");
   if (publishMessages)
   {
     rtPublishPaths(odom->header.stamp);
   }
   // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex release");
 }
References cl_move_base_z::odom_tracker::CLEAR_PATH, m_mutex_, publishMessages, cl_move_base_z::odom_tracker::RECORD_PATH, rtPublishPaths(), updateClearPath(), updateConfiguration(), updateRecordPath(), and workingMode_.
Referenced by onInitialize().
pushPath()
void cl_move_base_z::odom_tracker::OdomTracker::pushPath ()
Definition at line 142 of file odom_tracker.cpp.
 {
   RCLCPP_INFO(getLogger(), "odom_tracker m_mutex acquire");
   std::lock_guard<std::mutex> lock(m_mutex_);
   RCLCPP_INFO(getLogger(), "PUSH_PATH PATH EXITING");
   this->logStateString();
   pathStack_.push_back(baseTrajectory_);
   baseTrajectory_.poses.clear();
   RCLCPP_INFO(getLogger(), "PUSH_PATH PATH EXITING");
   this->logStateString();
   RCLCPP_INFO(getLogger(), "odom_tracker m_mutex release");
   this->updateAggregatedStackPath();
 }
References baseTrajectory_, smacc2::ISmaccComponent::getLogger(), logStateString(), m_mutex_, pathStack_, and updateAggregatedStackPath().
Referenced by OdomTrackerActionServer::execute(), cl_move_base_z::CbAbsoluteRotate::onEntry(), and cl_move_base_z::CbNavigateForward::onEntry().
rtPublishPaths()
void cl_move_base_z::odom_tracker::OdomTracker::rtPublishPaths (rclcpp::Time timestamp) protected virtual
rtPublishPaths()
Definition at line 259 of file odom_tracker.cpp.
 {
   baseTrajectory_.header.stamp = timestamp;
   robotBasePathPub_->publish(baseTrajectory_);
   aggregatedStackPathMsg_.header.stamp = timestamp;
   robotBasePathStackedPub_->publish(aggregatedStackPathMsg_);
 }
References aggregatedStackPathMsg_, baseTrajectory_, robotBasePathPub_, and robotBasePathStackedPub_.
Referenced by clearPath(), and processOdometryMessage().
setPublishMessages()
void cl_move_base_z::odom_tracker::OdomTracker::setPublishMessages (bool value)
setPublishMessages()
Definition at line 133 of file odom_tracker.cpp.
 {
   // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex acquire");
   std::lock_guard<std::mutex> lock(m_mutex_);
   publishMessages = value;
   // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex release");
   this->updateAggregatedStackPath();
 }
References m_mutex_, publishMessages, and updateAggregatedStackPath().
Referenced by OdomTrackerActionServer::execute().
setStartPoint() [1/2]
void cl_move_base_z::odom_tracker::OdomTracker::setStartPoint (const geometry_msgs::msg::Pose & pose)
Definition at line 228 of file odom_tracker.cpp.
 {
   std::lock_guard<std::mutex> lock(m_mutex_);
   RCLCPP_INFO_STREAM(getLogger(), "[OdomTracker] set current path starting point: " << pose);
   geometry_msgs::msg::PoseStamped posestamped;
   posestamped.header.frame_id = this->odomFrame_;
   posestamped.header.stamp = getNode()->now();
   posestamped.pose = pose;
   if (baseTrajectory_.poses.size() > 0)
   {
     baseTrajectory_.poses[0] = posestamped;
   }
   else
   {
     baseTrajectory_.poses.push_back(posestamped);
   }
   this->updateAggregatedStackPath();
 }
References baseTrajectory_, smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getNode(), m_mutex_, odomFrame_, and updateAggregatedStackPath().
setStartPoint() [2/2]
void cl_move_base_z::odom_tracker::OdomTracker::setStartPoint (const geometry_msgs::msg::PoseStamped & pose)
Definition at line 213 of file odom_tracker.cpp.
 {
   std::lock_guard<std::mutex> lock(m_mutex_);
   RCLCPP_INFO_STREAM(getLogger(), "[OdomTracker] set current path starting point: " << pose);
   if (baseTrajectory_.poses.size() > 0)
   {
     baseTrajectory_.poses[0] = pose;
   }
   else
   {
     baseTrajectory_.poses.push_back(pose);
   }
   this->updateAggregatedStackPath();
 }
References baseTrajectory_, smacc2::ISmaccComponent::getLogger(), m_mutex_, and updateAggregatedStackPath().
Referenced by cl_move_base_z::CbNavigateBackwards::onEntry(), and cl_move_base_z::CbNavigateForward::onEntry().
setWorkingMode()
void cl_move_base_z::odom_tracker::OdomTracker::setWorkingMode (WorkingMode workingMode)
setWorkingMode()
Definition at line 95 of file odom_tracker.cpp.
 {
   // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex acquire");
   std::lock_guard<std::mutex> lock(m_mutex_);
   switch (workingMode)
   {
     case WorkingMode::RECORD_PATH:
       RCLCPP_INFO_STREAM(
         getLogger(),
         "[OdomTracker] setting working mode to RECORD - record_point_distance_threshold: "
           << recordPointDistanceThreshold_
           << ", record_angular_distance_threshold: " << recordAngularDistanceThreshold_);
       break;
     case WorkingMode::CLEAR_PATH:
       RCLCPP_INFO_STREAM(
         getLogger(),
         "[OdomTracker] setting working mode to CLEAR - clear_point_distance_threshold: "
           << clearPointDistanceThreshold_
           << ", clear_angular_distance_threshold: " << clearAngularDistanceThreshold_);
       break;
     case WorkingMode::IDLE:
       RCLCPP_INFO_STREAM(getLogger(), "[OdomTracker] setting working mode to IDLE");
       break;
     default:
       RCLCPP_INFO_STREAM(getLogger(), "[OdomTracker] setting working mode to <UNKNOWN>");
   }
   workingMode_ = workingMode;
   // RCLCPP_INFO(getLogger(),"odom_tracker m_mutex release");
 }
References cl_move_base_z::odom_tracker::CLEAR_PATH, clearAngularDistanceThreshold_, clearPointDistanceThreshold_, smacc2::ISmaccComponent::getLogger(), cl_move_base_z::odom_tracker::IDLE, m_mutex_, cl_move_base_z::odom_tracker::RECORD_PATH, recordAngularDistanceThreshold_, recordPointDistanceThreshold_, and workingMode_.
Referenced by OdomTrackerActionServer::execute(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), cl_move_base_z::CbNavigateBackwards::onExit(), and cl_move_base_z::CbNavigateForward::onExit().
updateAggregatedStackPath()
void cl_move_base_z::odom_tracker::OdomTracker::updateAggregatedStackPath () protected
Definition at line 268 of file odom_tracker.cpp.
 {
   aggregatedStackPathMsg_.poses.clear();
   for (auto & p : pathStack_)
   {
     aggregatedStackPathMsg_.poses.insert(
       aggregatedStackPathMsg_.poses.end(), p.poses.begin(), p.poses.end());
   }
   aggregatedStackPathMsg_.header.frame_id = this->odomFrame_;
 }
References aggregatedStackPathMsg_, odomFrame_, and pathStack_.
Referenced by clearPath(), popPath(), pushPath(), setPublishMessages(), and setStartPoint().
updateClearPath()
bool cl_move_base_z::odom_tracker::OdomTracker::updateClearPath (const nav_msgs::msg::Odometry & odom) protected virtual
updateBackward()
Track robot base pose
Not removing point because it is enough far from the last cord point
Definition at line 285 of file odom_tracker.cpp.
 {
   // we initially accept any message if the queue is empty
   geometry_msgs::msg::PoseStamped base_pose;
   base_pose.pose = odom.pose.pose;
   base_pose.header = odom.header;
   baseTrajectory_.header = odom.header;
   bool acceptBackward = false;
   bool clearingError = false;
   bool finished = false;
   while (!finished)
   {
     if (
       baseTrajectory_.poses.size() <=
       1)  // we at least keep always the first point of the forward path when clearing
           // (this is important for backwards planner replanning and not losing the
           // last goal)
     {
       acceptBackward = false;
       finished = true;
     }
     else
     {
       auto & carrotPose = baseTrajectory_.poses.back().pose;
       auto & carrotPoint = carrotPose.position;
       double carrotAngle = tf2::getYaw(carrotPose.orientation);
       auto & currePose = base_pose.pose;
       auto & currePoint = currePose.position;
       double currentAngle = tf2::getYaw(currePose.orientation);
       double lastpointdist = p2pDistance(carrotPoint, currePoint);
       double goalAngleOffset = fabs(angles::shortest_angular_distance(carrotAngle, currentAngle));
       acceptBackward = !baseTrajectory_.poses.empty() &&
                        lastpointdist < clearPointDistanceThreshold_ &&
                        goalAngleOffset < clearAngularDistanceThreshold_;
       clearingError = lastpointdist > 2 * clearPointDistanceThreshold_;
       RCLCPP_DEBUG_STREAM(
         getLogger(), "[OdomTracker] clearing (accepted: " << acceptBackward
                                                           << ") linerr: " << lastpointdist
                                                           << ", anglerr: " << goalAngleOffset);
     }
     // RCLCPP_INFO(getLogger(),"Backwards, last distance: %lf < %lf accept: %d", dist,
     // minPointDistanceBackwardThresh_, acceptBackward);
     if (
       acceptBackward &&
       baseTrajectory_.poses.size() > 1) /* we always leave at least one item, specially interesting
                                            for the backward local planner reach the backwards goal
                                            with enough precision*/
     {
       baseTrajectory_.poses.pop_back();
     }
     else if (clearingError)
     {
       finished = true;
       RCLCPP_WARN(getLogger(), "[OdomTracker] Incorrect odom clearing motion.");
     }
     else
     {
       finished = true;
     }
   }
   return acceptBackward;
 }
References baseTrajectory_, clearAngularDistanceThreshold_, clearPointDistanceThreshold_, smacc2::ISmaccComponent::getLogger(), and cl_move_base_z::odom_tracker::p2pDistance().
Referenced by processOdometryMessage().
updateConfiguration()
void cl_move_base_z::odom_tracker::OdomTracker::updateConfiguration () protected
reconfigCB()
Definition at line 418 of file odom_tracker.cpp.
 {
   if (!getNode()->get_parameter("odom_frame", this->odomFrame_))
   {
   }
   if (!getNode()->get_parameter("record_point_distance_threshold", recordPointDistanceThreshold_))
   {
   }
   if (!getNode()->get_parameter(
         "record_angular_distance_threshold", recordAngularDistanceThreshold_))
   {
   }
   if (!getNode()->get_parameter("clear_point_distance_threshold", clearPointDistanceThreshold_))
   {
   }
   if (!getNode()->get_parameter("clear_angular_distance_threshold", clearAngularDistanceThreshold_))
   {
   }
 }
References clearAngularDistanceThreshold_, clearPointDistanceThreshold_, smacc2::ISmaccComponent::getNode(), odomFrame_, recordAngularDistanceThreshold_, and recordPointDistanceThreshold_.
Referenced by processOdometryMessage().
updateRecordPath()
bool cl_move_base_z::odom_tracker::OdomTracker::updateRecordPath (const nav_msgs::msg::Odometry & odom) protected virtual
updateRecordPath()
Track robot base pose
Definition at line 364 of file odom_tracker.cpp.
 {
   geometry_msgs::msg::PoseStamped base_pose;
   base_pose.pose = odom.pose.pose;
   base_pose.header = odom.header;
   baseTrajectory_.header = odom.header;
   bool enqueueOdomMessage = false;
   double dist = -1;
   if (baseTrajectory_.poses.empty())
   {
     enqueueOdomMessage = true;
   }
   else
   {
     const auto & prevPose = baseTrajectory_.poses.back().pose;
     const geometry_msgs::msg::Point & prevPoint = prevPose.position;
     double prevAngle = tf2::getYaw(prevPose.orientation);
     const geometry_msgs::msg::Point & currePoint = base_pose.pose.position;
     double currentAngle = tf2::getYaw(base_pose.pose.orientation);
     dist = p2pDistance(prevPoint, currePoint);
     double goalAngleOffset = fabs(angles::shortest_angular_distance(prevAngle, currentAngle));
     // RCLCPP_WARN(getLogger(),"dist %lf vs min %lf", dist, recordPointDistanceThreshold_);
     if (dist > recordPointDistanceThreshold_ || goalAngleOffset > recordAngularDistanceThreshold_)
     {
       enqueueOdomMessage = true;
     }
     else
     {
       // RCLCPP_WARN(getLogger(),"skip odom, dist: %lf", dist);
       enqueueOdomMessage = false;
     }
   }
   if (enqueueOdomMessage)
   {
     baseTrajectory_.poses.push_back(base_pose);
   }
   return enqueueOdomMessage;
 }
References baseTrajectory_, cl_move_base_z::odom_tracker::p2pDistance(), recordAngularDistanceThreshold_, and recordPointDistanceThreshold_.
Referenced by processOdometryMessage().
Member Data Documentation
aggregatedStackPathMsg_
nav_msgs::msg::Path cl_move_base_z::odom_tracker::OdomTracker::aggregatedStackPathMsg_ protected
Definition at line 146 of file odom_tracker.hpp.
Referenced by rtPublishPaths(), and updateAggregatedStackPath().
baseTrajectory_
nav_msgs::msg::Path cl_move_base_z::odom_tracker::OdomTracker::baseTrajectory_ protected
Processed path for the mouth of the reel.
Definition at line 140 of file odom_tracker.hpp.
Referenced by clearPath(), getPath(), logStateString(), popPath(), pushPath(), rtPublishPaths(), setStartPoint(), updateClearPath(), and updateRecordPath().
clearAngularDistanceThreshold_
double cl_move_base_z::odom_tracker::OdomTracker::clearAngularDistanceThreshold_ protected
rads
Definition at line 129 of file odom_tracker.hpp.
Referenced by onInitialize(), setWorkingMode(), updateClearPath(), and updateConfiguration().
clearPointDistanceThreshold_
double cl_move_base_z::odom_tracker::OdomTracker::clearPointDistanceThreshold_ protected
rads
Definition at line 126 of file odom_tracker.hpp.
Referenced by onInitialize(), setWorkingMode(), updateClearPath(), and updateConfiguration().
m_mutex_
std::mutex cl_move_base_z::odom_tracker::OdomTracker::m_mutex_ protected
Definition at line 151 of file odom_tracker.hpp.
Referenced by clearPath(), getPath(), popPath(), processOdometryMessage(), pushPath(), setPublishMessages(), setStartPoint(), and setWorkingMode().
odomFrame_
std::string cl_move_base_z::odom_tracker::OdomTracker::odomFrame_ protected
Definition at line 131 of file odom_tracker.hpp.
Referenced by OdomTracker(), onInitialize(), setStartPoint(), updateAggregatedStackPath(), and updateConfiguration().
odomSub_
rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr cl_move_base_z::odom_tracker::OdomTracker::odomSub_ protected
Definition at line 116 of file odom_tracker.hpp.
Referenced by onInitialize().
odomTopicName_
std::string cl_move_base_z::odom_tracker::OdomTracker::odomTopicName_ protected
Definition at line 133 of file odom_tracker.hpp.
Referenced by OdomTracker(), and onInitialize().
pathStack_
std::vector<nav_msgs::msg::Path> cl_move_base_z::odom_tracker::OdomTracker::pathStack_ protected
Definition at line 144 of file odom_tracker.hpp.
Referenced by logStateString(), popPath(), pushPath(), and updateAggregatedStackPath().
publishMessages
bool cl_move_base_z::odom_tracker::OdomTracker::publishMessages protected
Definition at line 137 of file odom_tracker.hpp.
Referenced by OdomTracker(), processOdometryMessage(), and setPublishMessages().
recordAngularDistanceThreshold_
double cl_move_base_z::odom_tracker::OdomTracker::recordAngularDistanceThreshold_ protected
Meters.
Definition at line 123 of file odom_tracker.hpp.
Referenced by onInitialize(), setWorkingMode(), updateConfiguration(), and updateRecordPath().
recordPointDistanceThreshold_
double cl_move_base_z::odom_tracker::OdomTracker::recordPointDistanceThreshold_ protected
How much distance there is between two points of the path.
Definition at line 120 of file odom_tracker.hpp.
Referenced by onInitialize(), setWorkingMode(), updateConfiguration(), and updateRecordPath().
robotBasePathPub_
rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr cl_move_base_z::odom_tracker::OdomTracker::robotBasePathPub_ protected
Definition at line 110 of file odom_tracker.hpp.
Referenced by onInitialize(), and rtPublishPaths().
robotBasePathStackedPub_
rclcpp::Publisher<nav_msgs::msg::Path>::SharedPtr cl_move_base_z::odom_tracker::OdomTracker::robotBasePathStackedPub_ protected
Definition at line 111 of file odom_tracker.hpp.
Referenced by onInitialize(), and rtPublishPaths().
subscribeToOdometryTopic_
bool cl_move_base_z::odom_tracker::OdomTracker::subscribeToOdometryTopic_ protected
Definition at line 149 of file odom_tracker.hpp.
Referenced by OdomTracker(), and onInitialize().
workingMode_
WorkingMode cl_move_base_z::odom_tracker::OdomTracker::workingMode_ protected
Definition at line 142 of file odom_tracker.hpp.
Referenced by OdomTracker(), processOdometryMessage(), and setWorkingMode().
The documentation for this class was generated from the following files:
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/components/odom_tracker/odom_tracker.hpp
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/components/odom_tracker/odom_tracker.cpp