SMACC2: cl_nav2z::WaypointEventDispatcher Class Reference
cl_nav2z::WaypointEventDispatcher Class Reference
#include <waypoints_event_dispatcher.hpp>
Public Member Functions
template<typename TDerived , typename TOrthogonal >
void initialize (ClNav2Z *client)
void postWaypointEvent (int index)
Private Attributes
std::function< void()> postWaypointFn [WAYPOINTS_EVENTCOUNT]
Detailed Description
Definition at line 1573 of file waypoints_event_dispatcher.hpp.
Member Function Documentation
initialize()
template<typename TDerived , typename TOrthogonal > void cl_nav2z::WaypointEventDispatcher::initialize (ClNav2Z * client)
Definition at line 1591 of file waypoints_event_dispatcher.hpp.
 {
   configurePostEvWaypoint<EvWaypoint0<TDerived, TOrthogonal>>(postWaypointFn, client, 0);
   configurePostEvWaypoint<EvWaypoint1<TDerived, TOrthogonal>>(postWaypointFn, client, 1);
   configurePostEvWaypoint<EvWaypoint2<TDerived, TOrthogonal>>(postWaypointFn, client, 2);
   configurePostEvWaypoint<EvWaypoint3<TDerived, TOrthogonal>>(postWaypointFn, client, 3);
   configurePostEvWaypoint<EvWaypoint4<TDerived, TOrthogonal>>(postWaypointFn, client, 4);
   configurePostEvWaypoint<EvWaypoint5<TDerived, TOrthogonal>>(postWaypointFn, client, 5);
   configurePostEvWaypoint<EvWaypoint6<TDerived, TOrthogonal>>(postWaypointFn, client, 6);
   configurePostEvWaypoint<EvWaypoint7<TDerived, TOrthogonal>>(postWaypointFn, client, 7);
   configurePostEvWaypoint<EvWaypoint8<TDerived, TOrthogonal>>(postWaypointFn, client, 8);
   configurePostEvWaypoint<EvWaypoint9<TDerived, TOrthogonal>>(postWaypointFn, client, 9);
   configurePostEvWaypoint<EvWaypoint10<TDerived, TOrthogonal>>(postWaypointFn, client, 10);
   configurePostEvWaypoint<EvWaypoint11<TDerived, TOrthogonal>>(postWaypointFn, client, 11);
   configurePostEvWaypoint<EvWaypoint12<TDerived, TOrthogonal>>(postWaypointFn, client, 12);
   configurePostEvWaypoint<EvWaypoint13<TDerived, TOrthogonal>>(postWaypointFn, client, 13);
   configurePostEvWaypoint<EvWaypoint14<TDerived, TOrthogonal>>(postWaypointFn, client, 14);
   configurePostEvWaypoint<EvWaypoint15<TDerived, TOrthogonal>>(postWaypointFn, client, 15);
   configurePostEvWaypoint<EvWaypoint16<TDerived, TOrthogonal>>(postWaypointFn, client, 16);
   configurePostEvWaypoint<EvWaypoint17<TDerived, TOrthogonal>>(postWaypointFn, client, 17);
   configurePostEvWaypoint<EvWaypoint18<TDerived, TOrthogonal>>(postWaypointFn, client, 18);
   configurePostEvWaypoint<EvWaypoint19<TDerived, TOrthogonal>>(postWaypointFn, client, 19);
   configurePostEvWaypoint<EvWaypoint20<TDerived, TOrthogonal>>(postWaypointFn, client, 20);
   configurePostEvWaypoint<EvWaypoint21<TDerived, TOrthogonal>>(postWaypointFn, client, 21);
   configurePostEvWaypoint<EvWaypoint22<TDerived, TOrthogonal>>(postWaypointFn, client, 22);
   configurePostEvWaypoint<EvWaypoint23<TDerived, TOrthogonal>>(postWaypointFn, client, 23);
   configurePostEvWaypoint<EvWaypoint24<TDerived, TOrthogonal>>(postWaypointFn, client, 24);
   configurePostEvWaypoint<EvWaypoint25<TDerived, TOrthogonal>>(postWaypointFn, client, 25);
   configurePostEvWaypoint<EvWaypoint26<TDerived, TOrthogonal>>(postWaypointFn, client, 26);
   configurePostEvWaypoint<EvWaypoint27<TDerived, TOrthogonal>>(postWaypointFn, client, 27);
   configurePostEvWaypoint<EvWaypoint28<TDerived, TOrthogonal>>(postWaypointFn, client, 28);
   configurePostEvWaypoint<EvWaypoint29<TDerived, TOrthogonal>>(postWaypointFn, client, 29);
   configurePostEvWaypoint<EvWaypoint30<TDerived, TOrthogonal>>(postWaypointFn, client, 30);
   configurePostEvWaypoint<EvWaypoint31<TDerived, TOrthogonal>>(postWaypointFn, client, 31);
   configurePostEvWaypoint<EvWaypoint32<TDerived, TOrthogonal>>(postWaypointFn, client, 32);
   configurePostEvWaypoint<EvWaypoint33<TDerived, TOrthogonal>>(postWaypointFn, client, 33);
   configurePostEvWaypoint<EvWaypoint34<TDerived, TOrthogonal>>(postWaypointFn, client, 34);
   configurePostEvWaypoint<EvWaypoint35<TDerived, TOrthogonal>>(postWaypointFn, client, 35);
   configurePostEvWaypoint<EvWaypoint36<TDerived, TOrthogonal>>(postWaypointFn, client, 36);
   configurePostEvWaypoint<EvWaypoint37<TDerived, TOrthogonal>>(postWaypointFn, client, 37);
   configurePostEvWaypoint<EvWaypoint38<TDerived, TOrthogonal>>(postWaypointFn, client, 38);
   configurePostEvWaypoint<EvWaypoint39<TDerived, TOrthogonal>>(postWaypointFn, client, 39);
   configurePostEvWaypoint<EvWaypoint40<TDerived, TOrthogonal>>(postWaypointFn, client, 40);
   configurePostEvWaypoint<EvWaypoint41<TDerived, TOrthogonal>>(postWaypointFn, client, 41);
   configurePostEvWaypoint<EvWaypoint42<TDerived, TOrthogonal>>(postWaypointFn, client, 42);
   configurePostEvWaypoint<EvWaypoint43<TDerived, TOrthogonal>>(postWaypointFn, client, 43);
   configurePostEvWaypoint<EvWaypoint44<TDerived, TOrthogonal>>(postWaypointFn, client, 44);
   configurePostEvWaypoint<EvWaypoint45<TDerived, TOrthogonal>>(postWaypointFn, client, 45);
   configurePostEvWaypoint<EvWaypoint46<TDerived, TOrthogonal>>(postWaypointFn, client, 46);
   configurePostEvWaypoint<EvWaypoint47<TDerived, TOrthogonal>>(postWaypointFn, client, 47);
   configurePostEvWaypoint<EvWaypoint48<TDerived, TOrthogonal>>(postWaypointFn, client, 48);
   configurePostEvWaypoint<EvWaypoint49<TDerived, TOrthogonal>>(postWaypointFn, client, 49);
   configurePostEvWaypoint<EvWaypoint50<TDerived, TOrthogonal>>(postWaypointFn, client, 50);
   configurePostEvWaypoint<EvWaypoint51<TDerived, TOrthogonal>>(postWaypointFn, client, 51);
   configurePostEvWaypoint<EvWaypoint52<TDerived, TOrthogonal>>(postWaypointFn, client, 52);
   configurePostEvWaypoint<EvWaypoint53<TDerived, TOrthogonal>>(postWaypointFn, client, 53);
   configurePostEvWaypoint<EvWaypoint54<TDerived, TOrthogonal>>(postWaypointFn, client, 54);
   configurePostEvWaypoint<EvWaypoint55<TDerived, TOrthogonal>>(postWaypointFn, client, 55);
   configurePostEvWaypoint<EvWaypoint56<TDerived, TOrthogonal>>(postWaypointFn, client, 56);
   configurePostEvWaypoint<EvWaypoint57<TDerived, TOrthogonal>>(postWaypointFn, client, 57);
   configurePostEvWaypoint<EvWaypoint58<TDerived, TOrthogonal>>(postWaypointFn, client, 58);
   configurePostEvWaypoint<EvWaypoint59<TDerived, TOrthogonal>>(postWaypointFn, client, 59);
   configurePostEvWaypoint<EvWaypoint60<TDerived, TOrthogonal>>(postWaypointFn, client, 60);
   configurePostEvWaypoint<EvWaypoint61<TDerived, TOrthogonal>>(postWaypointFn, client, 61);
   configurePostEvWaypoint<EvWaypoint62<TDerived, TOrthogonal>>(postWaypointFn, client, 62);
   configurePostEvWaypoint<EvWaypoint63<TDerived, TOrthogonal>>(postWaypointFn, client, 63);
   configurePostEvWaypoint<EvWaypoint64<TDerived, TOrthogonal>>(postWaypointFn, client, 64);
   configurePostEvWaypoint<EvWaypoint65<TDerived, TOrthogonal>>(postWaypointFn, client, 65);
   configurePostEvWaypoint<EvWaypoint66<TDerived, TOrthogonal>>(postWaypointFn, client, 66);
   configurePostEvWaypoint<EvWaypoint67<TDerived, TOrthogonal>>(postWaypointFn, client, 67);
   configurePostEvWaypoint<EvWaypoint68<TDerived, TOrthogonal>>(postWaypointFn, client, 68);
   configurePostEvWaypoint<EvWaypoint69<TDerived, TOrthogonal>>(postWaypointFn, client, 69);
   configurePostEvWaypoint<EvWaypoint70<TDerived, TOrthogonal>>(postWaypointFn, client, 70);
   configurePostEvWaypoint<EvWaypoint71<TDerived, TOrthogonal>>(postWaypointFn, client, 71);
   configurePostEvWaypoint<EvWaypoint72<TDerived, TOrthogonal>>(postWaypointFn, client, 72);
   configurePostEvWaypoint<EvWaypoint73<TDerived, TOrthogonal>>(postWaypointFn, client, 73);
   configurePostEvWaypoint<EvWaypoint74<TDerived, TOrthogonal>>(postWaypointFn, client, 74);
   configurePostEvWaypoint<EvWaypoint75<TDerived, TOrthogonal>>(postWaypointFn, client, 75);
   configurePostEvWaypoint<EvWaypoint76<TDerived, TOrthogonal>>(postWaypointFn, client, 76);
   configurePostEvWaypoint<EvWaypoint77<TDerived, TOrthogonal>>(postWaypointFn, client, 77);
   configurePostEvWaypoint<EvWaypoint78<TDerived, TOrthogonal>>(postWaypointFn, client, 78);
   configurePostEvWaypoint<EvWaypoint79<TDerived, TOrthogonal>>(postWaypointFn, client, 79);
   configurePostEvWaypoint<EvWaypoint80<TDerived, TOrthogonal>>(postWaypointFn, client, 80);
   configurePostEvWaypoint<EvWaypoint81<TDerived, TOrthogonal>>(postWaypointFn, client, 81);
   configurePostEvWaypoint<EvWaypoint82<TDerived, TOrthogonal>>(postWaypointFn, client, 82);
   configurePostEvWaypoint<EvWaypoint83<TDerived, TOrthogonal>>(postWaypointFn, client, 83);
   configurePostEvWaypoint<EvWaypoint84<TDerived, TOrthogonal>>(postWaypointFn, client, 84);
   configurePostEvWaypoint<EvWaypoint85<TDerived, TOrthogonal>>(postWaypointFn, client, 85);
   configurePostEvWaypoint<EvWaypoint86<TDerived, TOrthogonal>>(postWaypointFn, client, 86);
   configurePostEvWaypoint<EvWaypoint87<TDerived, TOrthogonal>>(postWaypointFn, client, 87);
   configurePostEvWaypoint<EvWaypoint88<TDerived, TOrthogonal>>(postWaypointFn, client, 88);
   configurePostEvWaypoint<EvWaypoint89<TDerived, TOrthogonal>>(postWaypointFn, client, 89);
   configurePostEvWaypoint<EvWaypoint90<TDerived, TOrthogonal>>(postWaypointFn, client, 90);
   configurePostEvWaypoint<EvWaypoint91<TDerived, TOrthogonal>>(postWaypointFn, client, 91);
   configurePostEvWaypoint<EvWaypoint92<TDerived, TOrthogonal>>(postWaypointFn, client, 92);
   configurePostEvWaypoint<EvWaypoint93<TDerived, TOrthogonal>>(postWaypointFn, client, 93);
   configurePostEvWaypoint<EvWaypoint94<TDerived, TOrthogonal>>(postWaypointFn, client, 94);
   configurePostEvWaypoint<EvWaypoint95<TDerived, TOrthogonal>>(postWaypointFn, client, 95);
   configurePostEvWaypoint<EvWaypoint96<TDerived, TOrthogonal>>(postWaypointFn, client, 96);
   configurePostEvWaypoint<EvWaypoint97<TDerived, TOrthogonal>>(postWaypointFn, client, 97);
   configurePostEvWaypoint<EvWaypoint98<TDerived, TOrthogonal>>(postWaypointFn, client, 98);
   configurePostEvWaypoint<EvWaypoint99<TDerived, TOrthogonal>>(postWaypointFn, client, 99);
   configurePostEvWaypoint<EvWaypoint100<TDerived, TOrthogonal>>(postWaypointFn, client, 100);
   configurePostEvWaypoint<EvWaypoint101<TDerived, TOrthogonal>>(postWaypointFn, client, 101);
   configurePostEvWaypoint<EvWaypoint102<TDerived, TOrthogonal>>(postWaypointFn, client, 102);
   configurePostEvWaypoint<EvWaypoint103<TDerived, TOrthogonal>>(postWaypointFn, client, 103);
   configurePostEvWaypoint<EvWaypoint104<TDerived, TOrthogonal>>(postWaypointFn, client, 104);
   configurePostEvWaypoint<EvWaypoint105<TDerived, TOrthogonal>>(postWaypointFn, client, 105);
   configurePostEvWaypoint<EvWaypoint106<TDerived, TOrthogonal>>(postWaypointFn, client, 106);
   configurePostEvWaypoint<EvWaypoint107<TDerived, TOrthogonal>>(postWaypointFn, client, 107);
   configurePostEvWaypoint<EvWaypoint108<TDerived, TOrthogonal>>(postWaypointFn, client, 108);
   configurePostEvWaypoint<EvWaypoint109<TDerived, TOrthogonal>>(postWaypointFn, client, 109);
   configurePostEvWaypoint<EvWaypoint110<TDerived, TOrthogonal>>(postWaypointFn, client, 110);
   configurePostEvWaypoint<EvWaypoint111<TDerived, TOrthogonal>>(postWaypointFn, client, 111);
   configurePostEvWaypoint<EvWaypoint112<TDerived, TOrthogonal>>(postWaypointFn, client, 112);
   configurePostEvWaypoint<EvWaypoint113<TDerived, TOrthogonal>>(postWaypointFn, client, 113);
   configurePostEvWaypoint<EvWaypoint114<TDerived, TOrthogonal>>(postWaypointFn, client, 114);
   configurePostEvWaypoint<EvWaypoint115<TDerived, TOrthogonal>>(postWaypointFn, client, 115);
   configurePostEvWaypoint<EvWaypoint116<TDerived, TOrthogonal>>(postWaypointFn, client, 116);
   configurePostEvWaypoint<EvWaypoint117<TDerived, TOrthogonal>>(postWaypointFn, client, 117);
   configurePostEvWaypoint<EvWaypoint118<TDerived, TOrthogonal>>(postWaypointFn, client, 118);
   configurePostEvWaypoint<EvWaypoint119<TDerived, TOrthogonal>>(postWaypointFn, client, 119);
   configurePostEvWaypoint<EvWaypoint120<TDerived, TOrthogonal>>(postWaypointFn, client, 120);
   configurePostEvWaypoint<EvWaypoint121<TDerived, TOrthogonal>>(postWaypointFn, client, 121);
   configurePostEvWaypoint<EvWaypoint122<TDerived, TOrthogonal>>(postWaypointFn, client, 122);
   configurePostEvWaypoint<EvWaypoint123<TDerived, TOrthogonal>>(postWaypointFn, client, 123);
   configurePostEvWaypoint<EvWaypoint124<TDerived, TOrthogonal>>(postWaypointFn, client, 124);
   configurePostEvWaypoint<EvWaypoint125<TDerived, TOrthogonal>>(postWaypointFn, client, 125);
   configurePostEvWaypoint<EvWaypoint126<TDerived, TOrthogonal>>(postWaypointFn, client, 126);
   configurePostEvWaypoint<EvWaypoint127<TDerived, TOrthogonal>>(postWaypointFn, client, 127);
   configurePostEvWaypoint<EvWaypoint128<TDerived, TOrthogonal>>(postWaypointFn, client, 128);
   configurePostEvWaypoint<EvWaypoint129<TDerived, TOrthogonal>>(postWaypointFn, client, 129);
   configurePostEvWaypoint<EvWaypoint130<TDerived, TOrthogonal>>(postWaypointFn, client, 130);
   configurePostEvWaypoint<EvWaypoint131<TDerived, TOrthogonal>>(postWaypointFn, client, 131);
   configurePostEvWaypoint<EvWaypoint132<TDerived, TOrthogonal>>(postWaypointFn, client, 132);
   configurePostEvWaypoint<EvWaypoint133<TDerived, TOrthogonal>>(postWaypointFn, client, 133);
   configurePostEvWaypoint<EvWaypoint134<TDerived, TOrthogonal>>(postWaypointFn, client, 134);
   configurePostEvWaypoint<EvWaypoint135<TDerived, TOrthogonal>>(postWaypointFn, client, 135);
   configurePostEvWaypoint<EvWaypoint136<TDerived, TOrthogonal>>(postWaypointFn, client, 136);
   configurePostEvWaypoint<EvWaypoint137<TDerived, TOrthogonal>>(postWaypointFn, client, 137);
   configurePostEvWaypoint<EvWaypoint138<TDerived, TOrthogonal>>(postWaypointFn, client, 138);
   configurePostEvWaypoint<EvWaypoint139<TDerived, TOrthogonal>>(postWaypointFn, client, 139);
   configurePostEvWaypoint<EvWaypoint140<TDerived, TOrthogonal>>(postWaypointFn, client, 140);
   configurePostEvWaypoint<EvWaypoint141<TDerived, TOrthogonal>>(postWaypointFn, client, 141);
   configurePostEvWaypoint<EvWaypoint142<TDerived, TOrthogonal>>(postWaypointFn, client, 142);
   configurePostEvWaypoint<EvWaypoint143<TDerived, TOrthogonal>>(postWaypointFn, client, 143);
   configurePostEvWaypoint<EvWaypoint144<TDerived, TOrthogonal>>(postWaypointFn, client, 144);
   configurePostEvWaypoint<EvWaypoint145<TDerived, TOrthogonal>>(postWaypointFn, client, 145);
   configurePostEvWaypoint<EvWaypoint146<TDerived, TOrthogonal>>(postWaypointFn, client, 146);
   configurePostEvWaypoint<EvWaypoint147<TDerived, TOrthogonal>>(postWaypointFn, client, 147);
   configurePostEvWaypoint<EvWaypoint148<TDerived, TOrthogonal>>(postWaypointFn, client, 148);
   configurePostEvWaypoint<EvWaypoint149<TDerived, TOrthogonal>>(postWaypointFn, client, 149);
   configurePostEvWaypoint<EvWaypoint150<TDerived, TOrthogonal>>(postWaypointFn, client, 150);
   configurePostEvWaypoint<EvWaypoint151<TDerived, TOrthogonal>>(postWaypointFn, client, 151);
   configurePostEvWaypoint<EvWaypoint152<TDerived, TOrthogonal>>(postWaypointFn, client, 152);
   configurePostEvWaypoint<EvWaypoint153<TDerived, TOrthogonal>>(postWaypointFn, client, 153);
   configurePostEvWaypoint<EvWaypoint154<TDerived, TOrthogonal>>(postWaypointFn, client, 154);
   configurePostEvWaypoint<EvWaypoint155<TDerived, TOrthogonal>>(postWaypointFn, client, 155);
   configurePostEvWaypoint<EvWaypoint156<TDerived, TOrthogonal>>(postWaypointFn, client, 156);
   configurePostEvWaypoint<EvWaypoint157<TDerived, TOrthogonal>>(postWaypointFn, client, 157);
   configurePostEvWaypoint<EvWaypoint158<TDerived, TOrthogonal>>(postWaypointFn, client, 158);
   configurePostEvWaypoint<EvWaypoint159<TDerived, TOrthogonal>>(postWaypointFn, client, 159);
   configurePostEvWaypoint<EvWaypoint160<TDerived, TOrthogonal>>(postWaypointFn, client, 160);
   configurePostEvWaypoint<EvWaypoint161<TDerived, TOrthogonal>>(postWaypointFn, client, 161);
   configurePostEvWaypoint<EvWaypoint162<TDerived, TOrthogonal>>(postWaypointFn, client, 162);
   configurePostEvWaypoint<EvWaypoint163<TDerived, TOrthogonal>>(postWaypointFn, client, 163);
   configurePostEvWaypoint<EvWaypoint164<TDerived, TOrthogonal>>(postWaypointFn, client, 164);
   configurePostEvWaypoint<EvWaypoint165<TDerived, TOrthogonal>>(postWaypointFn, client, 165);
   configurePostEvWaypoint<EvWaypoint166<TDerived, TOrthogonal>>(postWaypointFn, client, 166);
   configurePostEvWaypoint<EvWaypoint167<TDerived, TOrthogonal>>(postWaypointFn, client, 167);
   configurePostEvWaypoint<EvWaypoint168<TDerived, TOrthogonal>>(postWaypointFn, client, 168);
   configurePostEvWaypoint<EvWaypoint169<TDerived, TOrthogonal>>(postWaypointFn, client, 169);
   configurePostEvWaypoint<EvWaypoint170<TDerived, TOrthogonal>>(postWaypointFn, client, 170);
   configurePostEvWaypoint<EvWaypoint171<TDerived, TOrthogonal>>(postWaypointFn, client, 171);
   configurePostEvWaypoint<EvWaypoint172<TDerived, TOrthogonal>>(postWaypointFn, client, 172);
   configurePostEvWaypoint<EvWaypoint173<TDerived, TOrthogonal>>(postWaypointFn, client, 173);
   configurePostEvWaypoint<EvWaypoint174<TDerived, TOrthogonal>>(postWaypointFn, client, 174);
   configurePostEvWaypoint<EvWaypoint175<TDerived, TOrthogonal>>(postWaypointFn, client, 175);
   configurePostEvWaypoint<EvWaypoint176<TDerived, TOrthogonal>>(postWaypointFn, client, 176);
   configurePostEvWaypoint<EvWaypoint177<TDerived, TOrthogonal>>(postWaypointFn, client, 177);
   configurePostEvWaypoint<EvWaypoint178<TDerived, TOrthogonal>>(postWaypointFn, client, 178);
   configurePostEvWaypoint<EvWaypoint179<TDerived, TOrthogonal>>(postWaypointFn, client, 179);
   configurePostEvWaypoint<EvWaypoint180<TDerived, TOrthogonal>>(postWaypointFn, client, 180);
   configurePostEvWaypoint<EvWaypoint181<TDerived, TOrthogonal>>(postWaypointFn, client, 181);
   configurePostEvWaypoint<EvWaypoint182<TDerived, TOrthogonal>>(postWaypointFn, client, 182);
   configurePostEvWaypoint<EvWaypoint183<TDerived, TOrthogonal>>(postWaypointFn, client, 183);
   configurePostEvWaypoint<EvWaypoint184<TDerived, TOrthogonal>>(postWaypointFn, client, 184);
   configurePostEvWaypoint<EvWaypoint185<TDerived, TOrthogonal>>(postWaypointFn, client, 185);
   configurePostEvWaypoint<EvWaypoint186<TDerived, TOrthogonal>>(postWaypointFn, client, 186);
   configurePostEvWaypoint<EvWaypoint187<TDerived, TOrthogonal>>(postWaypointFn, client, 187);
   configurePostEvWaypoint<EvWaypoint188<TDerived, TOrthogonal>>(postWaypointFn, client, 188);
   configurePostEvWaypoint<EvWaypoint189<TDerived, TOrthogonal>>(postWaypointFn, client, 189);
   configurePostEvWaypoint<EvWaypoint190<TDerived, TOrthogonal>>(postWaypointFn, client, 190);
   configurePostEvWaypoint<EvWaypoint191<TDerived, TOrthogonal>>(postWaypointFn, client, 191);
   configurePostEvWaypoint<EvWaypoint192<TDerived, TOrthogonal>>(postWaypointFn, client, 192);
   configurePostEvWaypoint<EvWaypoint193<TDerived, TOrthogonal>>(postWaypointFn, client, 193);
   configurePostEvWaypoint<EvWaypoint194<TDerived, TOrthogonal>>(postWaypointFn, client, 194);
   configurePostEvWaypoint<EvWaypoint195<TDerived, TOrthogonal>>(postWaypointFn, client, 195);
   configurePostEvWaypoint<EvWaypoint196<TDerived, TOrthogonal>>(postWaypointFn, client, 196);
   configurePostEvWaypoint<EvWaypoint197<TDerived, TOrthogonal>>(postWaypointFn, client, 197);
   configurePostEvWaypoint<EvWaypoint198<TDerived, TOrthogonal>>(postWaypointFn, client, 198);
   configurePostEvWaypoint<EvWaypoint199<TDerived, TOrthogonal>>(postWaypointFn, client, 199);
   configurePostEvWaypoint<EvWaypoint200<TDerived, TOrthogonal>>(postWaypointFn, client, 200);
   configurePostEvWaypoint<EvWaypoint201<TDerived, TOrthogonal>>(postWaypointFn, client, 201);
   configurePostEvWaypoint<EvWaypoint202<TDerived, TOrthogonal>>(postWaypointFn, client, 202);
   configurePostEvWaypoint<EvWaypoint203<TDerived, TOrthogonal>>(postWaypointFn, client, 203);
   configurePostEvWaypoint<EvWaypoint204<TDerived, TOrthogonal>>(postWaypointFn, client, 204);
   configurePostEvWaypoint<EvWaypoint205<TDerived, TOrthogonal>>(postWaypointFn, client, 205);
   configurePostEvWaypoint<EvWaypoint206<TDerived, TOrthogonal>>(postWaypointFn, client, 206);
   configurePostEvWaypoint<EvWaypoint207<TDerived, TOrthogonal>>(postWaypointFn, client, 207);
   configurePostEvWaypoint<EvWaypoint208<TDerived, TOrthogonal>>(postWaypointFn, client, 208);
   configurePostEvWaypoint<EvWaypoint209<TDerived, TOrthogonal>>(postWaypointFn, client, 209);
   configurePostEvWaypoint<EvWaypoint210<TDerived, TOrthogonal>>(postWaypointFn, client, 210);
   configurePostEvWaypoint<EvWaypoint211<TDerived, TOrthogonal>>(postWaypointFn, client, 211);
   configurePostEvWaypoint<EvWaypoint212<TDerived, TOrthogonal>>(postWaypointFn, client, 212);
   configurePostEvWaypoint<EvWaypoint213<TDerived, TOrthogonal>>(postWaypointFn, client, 213);
   configurePostEvWaypoint<EvWaypoint214<TDerived, TOrthogonal>>(postWaypointFn, client, 214);
   configurePostEvWaypoint<EvWaypoint215<TDerived, TOrthogonal>>(postWaypointFn, client, 215);
   configurePostEvWaypoint<EvWaypoint216<TDerived, TOrthogonal>>(postWaypointFn, client, 216);
   configurePostEvWaypoint<EvWaypoint217<TDerived, TOrthogonal>>(postWaypointFn, client, 217);
   configurePostEvWaypoint<EvWaypoint218<TDerived, TOrthogonal>>(postWaypointFn, client, 218);
   configurePostEvWaypoint<EvWaypoint219<TDerived, TOrthogonal>>(postWaypointFn, client, 219);
   configurePostEvWaypoint<EvWaypoint220<TDerived, TOrthogonal>>(postWaypointFn, client, 220);
   configurePostEvWaypoint<EvWaypoint221<TDerived, TOrthogonal>>(postWaypointFn, client, 221);
   configurePostEvWaypoint<EvWaypoint222<TDerived, TOrthogonal>>(postWaypointFn, client, 222);
   configurePostEvWaypoint<EvWaypoint223<TDerived, TOrthogonal>>(postWaypointFn, client, 223);
   configurePostEvWaypoint<EvWaypoint224<TDerived, TOrthogonal>>(postWaypointFn, client, 224);
   configurePostEvWaypoint<EvWaypoint225<TDerived, TOrthogonal>>(postWaypointFn, client, 225);
   configurePostEvWaypoint<EvWaypoint226<TDerived, TOrthogonal>>(postWaypointFn, client, 226);
   configurePostEvWaypoint<EvWaypoint227<TDerived, TOrthogonal>>(postWaypointFn, client, 227);
   configurePostEvWaypoint<EvWaypoint228<TDerived, TOrthogonal>>(postWaypointFn, client, 228);
   configurePostEvWaypoint<EvWaypoint229<TDerived, TOrthogonal>>(postWaypointFn, client, 229);
   configurePostEvWaypoint<EvWaypoint230<TDerived, TOrthogonal>>(postWaypointFn, client, 230);
   configurePostEvWaypoint<EvWaypoint231<TDerived, TOrthogonal>>(postWaypointFn, client, 231);
   configurePostEvWaypoint<EvWaypoint232<TDerived, TOrthogonal>>(postWaypointFn, client, 232);
   configurePostEvWaypoint<EvWaypoint233<TDerived, TOrthogonal>>(postWaypointFn, client, 233);
   configurePostEvWaypoint<EvWaypoint234<TDerived, TOrthogonal>>(postWaypointFn, client, 234);
   configurePostEvWaypoint<EvWaypoint235<TDerived, TOrthogonal>>(postWaypointFn, client, 235);
   configurePostEvWaypoint<EvWaypoint236<TDerived, TOrthogonal>>(postWaypointFn, client, 236);
   configurePostEvWaypoint<EvWaypoint237<TDerived, TOrthogonal>>(postWaypointFn, client, 237);
   configurePostEvWaypoint<EvWaypoint238<TDerived, TOrthogonal>>(postWaypointFn, client, 238);
   configurePostEvWaypoint<EvWaypoint239<TDerived, TOrthogonal>>(postWaypointFn, client, 239);
   configurePostEvWaypoint<EvWaypoint240<TDerived, TOrthogonal>>(postWaypointFn, client, 240);
   configurePostEvWaypoint<EvWaypoint241<TDerived, TOrthogonal>>(postWaypointFn, client, 241);
   configurePostEvWaypoint<EvWaypoint242<TDerived, TOrthogonal>>(postWaypointFn, client, 242);
   configurePostEvWaypoint<EvWaypoint243<TDerived, TOrthogonal>>(postWaypointFn, client, 243);
   configurePostEvWaypoint<EvWaypoint244<TDerived, TOrthogonal>>(postWaypointFn, client, 244);
   configurePostEvWaypoint<EvWaypoint245<TDerived, TOrthogonal>>(postWaypointFn, client, 245);
   configurePostEvWaypoint<EvWaypoint246<TDerived, TOrthogonal>>(postWaypointFn, client, 246);
   configurePostEvWaypoint<EvWaypoint247<TDerived, TOrthogonal>>(postWaypointFn, client, 247);
   configurePostEvWaypoint<EvWaypoint248<TDerived, TOrthogonal>>(postWaypointFn, client, 248);
   configurePostEvWaypoint<EvWaypoint249<TDerived, TOrthogonal>>(postWaypointFn, client, 249);
   configurePostEvWaypoint<EvWaypoint250<TDerived, TOrthogonal>>(postWaypointFn, client, 250);
   configurePostEvWaypoint<EvWaypoint251<TDerived, TOrthogonal>>(postWaypointFn, client, 251);
   configurePostEvWaypoint<EvWaypoint252<TDerived, TOrthogonal>>(postWaypointFn, client, 252);
   configurePostEvWaypoint<EvWaypoint253<TDerived, TOrthogonal>>(postWaypointFn, client, 253);
   configurePostEvWaypoint<EvWaypoint254<TDerived, TOrthogonal>>(postWaypointFn, client, 254);
   configurePostEvWaypoint<EvWaypoint255<TDerived, TOrthogonal>>(postWaypointFn, client, 255);
   configurePostEvWaypoint<EvWaypoint256<TDerived, TOrthogonal>>(postWaypointFn, client, 256);
 }
References postWaypointFn.
Referenced by cl_nav2z::WaypointNavigator::onOrthogonalAllocation().
postWaypointEvent()
void cl_nav2z::WaypointEventDispatcher::postWaypointEvent (int index)
Definition at line 19 of file waypoints_event_dispatcher.cpp.
 {
   auto & fn = postWaypointFn[index % WAYPOINTS_EVENTCOUNT];
   if (fn != nullptr) fn();
 }
References postWaypointFn, and WAYPOINTS_EVENTCOUNT.
Referenced by cl_nav2z::WaypointNavigator::onGoalReached().
Member Data Documentation
postWaypointFn
std::function<void()> cl_nav2z::WaypointEventDispatcher::postWaypointFn[WAYPOINTS_EVENTCOUNT] private
Definition at line 1575 of file waypoints_event_dispatcher.hpp.
Referenced by initialize(), and postWaypointEvent().
The documentation for this class was generated from the following files:
smacc2_client_library/nav2z_client/nav2z_client/include/nav2z_client/components/waypoints_navigator/waypoints_event_dispatcher.hpp
smacc2_client_library/nav2z_client/nav2z_client/src/nav2z_client/components/waypoints_navigator/waypoints_event_dispatcher.cpp