SMACC2: cl_move_base_z::CbMoveBaseClientBehaviorBase Class Reference
cl_move_base_z::CbMoveBaseClientBehaviorBase Class Reference
#include <cb_move_base_client_behavior_base.hpp>
Public Member Functions
virtual ~CbMoveBaseClientBehaviorBase ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
Protected Attributes
cl_move_base_z::ClMoveBaseZ * moveBaseClient_
Private Member Functions
void propagateSuccessEvent (ClMoveBaseZ::WrappedResult &)
void propagateFailureEvent (ClMoveBaseZ::WrappedResult &)
Additional Inherited Members
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void executeOnEntry () override
void executeOnExit () override
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
virtual void onEntry ()
virtual void onExit ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual rclcpp::Node::SharedPtr getNode ()
virtual rclcpp::Logger getLogger ()
Detailed Description
Definition at line 28 of file cb_move_base_client_behavior_base.hpp.
Constructor & Destructor Documentation
~CbMoveBaseClientBehaviorBase()
cl_move_base_z::CbMoveBaseClientBehaviorBase::~CbMoveBaseClientBehaviorBase () virtual
Definition at line 24 of file cb_move_base_client_behavior_base.cpp.
 {}
Member Function Documentation
onOrthogonalAllocation()
template<typename TOrthogonal , typename TSourceObject > void cl_move_base_z::CbMoveBaseClientBehaviorBase::onOrthogonalAllocation () inline
Definition at line 34 of file cb_move_base_client_behavior_base.hpp.
   {
     this->requiresClient(moveBaseClient_);
     smacc2::SmaccAsyncClientBehavior::onOrthogonalAllocation<TOrthogonal, TSourceObject>();
     moveBaseClient_->onSucceeded(&CbMoveBaseClientBehaviorBase::propagateSuccessEvent, this);
     moveBaseClient_->onAborted(&CbMoveBaseClientBehaviorBase::propagateFailureEvent, this);
   }
References moveBaseClient_, smacc2::client_bases::SmaccActionClientBase< ActionType >::onAborted(), smacc2::client_bases::SmaccActionClientBase< ActionType >::onSucceeded(), propagateFailureEvent(), propagateSuccessEvent(), and smacc2::ISmaccClientBehavior::requiresClient().
propagateFailureEvent()
void cl_move_base_z::CbMoveBaseClientBehaviorBase::propagateFailureEvent (ClMoveBaseZ::WrappedResult &) private
Definition at line 30 of file cb_move_base_client_behavior_base.cpp.
 {
   this->postFailureEvent();
 }
References smacc2::SmaccAsyncClientBehavior::postFailureEvent().
Referenced by onOrthogonalAllocation().
propagateSuccessEvent()
void cl_move_base_z::CbMoveBaseClientBehaviorBase::propagateSuccessEvent (ClMoveBaseZ::WrappedResult &) private
Definition at line 26 of file cb_move_base_client_behavior_base.cpp.
 {
   this->postSuccessEvent();
 }
References smacc2::SmaccAsyncClientBehavior::postSuccessEvent().
Referenced by onOrthogonalAllocation().
Member Data Documentation
moveBaseClient_
cl_move_base_z::ClMoveBaseZ* cl_move_base_z::CbMoveBaseClientBehaviorBase::moveBaseClient_ protected
Definition at line 43 of file cb_move_base_client_behavior_base.hpp.
Referenced by cl_move_base_z::CbNavigateGlobalPosition::execute(), cl_move_base_z::CbAbsoluteRotate::onEntry(), cl_move_base_z::CbNavigateBackwards::onEntry(), cl_move_base_z::CbNavigateForward::onEntry(), cl_move_base_z::CbNavigateGlobalPosition::onEntry(), cl_move_base_z::CbNavigateNextWaypoint::onEntry(), cl_move_base_z::CbRotate::onEntry(), cl_move_base_z::CbUndoPathBackwards::onEntry(), cl_move_base_z::CbUndoPathBackwards::onExit(), and onOrthogonalAllocation().
The documentation for this class was generated from the following files:
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/include/move_base_z_client_plugin/client_behaviors/cb_move_base_client_behavior_base.hpp
smacc2_client_library/move_base_z_client/move_base_z_client_plugin/src/move_base_z_client_plugin/client_behaviors/cb_move_base_client_behavior_base.cpp