SMACC2: smacc2_client_library/move_base_z_client/custom_planners/move_base_z_planners_common/include/move_base_z_planners_common/common.hpp File Reference
common.hpp File Reference
#include <iostream>
#include <geometry_msgs/msg/pose_stamped.hpp>
#include <geometry_msgs/msg/twist.hpp>
#include <tf2_geometry_msgs/tf2_geometry_msgs.hpp>
#include "rclcpp_lifecycle/lifecycle_node.hpp"
Functions
std::ostream & operator<< (std::ostream &out, const geometry_msgs::msg::Twist &msg)
std::ostream & operator<< (std::ostream &out, const geometry_msgs::msg::Pose &msg)
std::ostream & operator<< (std::ostream &out, const geometry_msgs::msg::PoseStamped &msg)
std::ostream & operator<< (std::ostream &out, const geometry_msgs::msg::Point &msg)
std::ostream & operator<< (std::ostream &out, const geometry_msgs::msg::Quaternion &msg)
template<typename T >
void declareOrSet (rclcpp_lifecycle::LifecycleNode::SharedPtr &node, std::string param, T &value)
Function Documentation
declareOrSet()
template<typename T > void declareOrSet (rclcpp_lifecycle::LifecycleNode::SharedPtr & node, std::string param, T & value)
Definition at line 34 of file common.hpp.
 {
   if (!node->has_parameter(param))
   {
     node->declare_parameter(param, value);
     // node->set_parameter(rclcpp::Parameter(param, value));
   }
 }
Referenced by cl_move_base_z::backward_local_planner::BackwardLocalPlanner::configure(), cl_move_base_z::forward_local_planner::ForwardLocalPlanner::configure(), cl_move_base_z::pure_spinning_local_planner::PureSpinningLocalPlanner::configure(), cl_move_base_z::backward_global_planner::BackwardGlobalPlanner::configure(), and cl_move_base_z::undo_path_global_planner::UndoPathGlobalPlanner::configure().
operator<<() [1/5]
std::ostream& operator<< (std::ostream & out, const geometry_msgs::msg::Point & msg)
Definition at line 139 of file common.cpp.
 {
   out << "Position [" << msg.x << "m , " << msg.y << "m , " << msg.z << "m ]";
   return out;
 }
operator<<() [2/5]
std::ostream& operator<< (std::ostream & out, const geometry_msgs::msg::Pose & msg)
Definition at line 130 of file common.cpp.
 {
   out << "Position [" << msg.position.x << "m , " << msg.position.y << "m , " << msg.position.z
       << "m ]";
   out << " Orientation [" << msg.orientation.x << " , " << msg.orientation.y << " , "
       << msg.orientation.z << ", " << msg.orientation.w << "]";
   return out;
 }
operator<<() [3/5]
std::ostream& operator<< (std::ostream & out, const geometry_msgs::msg::PoseStamped & msg)
Definition at line 151 of file common.cpp.
 {
   out << msg.pose;
   return out;
 }
operator<<() [4/5]
std::ostream& operator<< (std::ostream & out, const geometry_msgs::msg::Quaternion & msg)
Definition at line 145 of file common.cpp.
 {
   out << "Quaternion [" << msg.x << " , " << msg.y << " , " << msg.z << ", " << msg.w << "]";
   return out;
 }
operator<<() [5/5]
std::ostream& operator<< (std::ostream & out, const geometry_msgs::msg::Twist & msg)
Definition at line 124 of file common.cpp.
 {
   out << "Twist [" << msg.linear.x << "m , " << msg.linear.y << "m , " << msg.angular.z << "rad ]";
   return out;
 }