SMACC2: cl_nav2z::pure_spinning_local_planner Namespace Reference
cl_nav2z::pure_spinning_local_planner Namespace Reference
Classes
class PureSpinningLocalPlanner
Functions
template<typename T >
void tryGetOrSet (rclcpp_lifecycle::LifecycleNode::SharedPtr &node, std::string param, T &value)
void publishGoalMarker (double, double, double)
Function Documentation
publishGoalMarker()
void cl_nav2z::pure_spinning_local_planner::publishGoalMarker (double , double , double)
Definition at line 209 of file pure_spinning_local_planner.cpp.
 {}
Referenced by cl_nav2z::backward_global_planner::BackwardGlobalPlanner::createPlan(), and cl_nav2z::undo_path_global_planner::UndoPathGlobalPlanner::createPlan().
tryGetOrSet()
template<typename T > void cl_nav2z::pure_spinning_local_planner::tryGetOrSet (rclcpp_lifecycle::LifecycleNode::SharedPtr & node, std::string param, T & value)
Definition at line 27 of file pure_spinning_local_planner.cpp.
 {
   if (!node->get_parameter(param, value))
   {
     node->set_parameter(rclcpp::Parameter(param, value));
   }
 }
Referenced by cl_nav2z::pure_spinning_local_planner::PureSpinningLocalPlanner::updateParameters().