SMACC2: sm_test_moveit_ur5_sim Namespace Reference
sm_test_moveit_ur5_sim Namespace Reference
Classes
class OrArm
struct SmTestMoveitUr5Sim
struct StAttachObject
struct StCircularPivotMotion
struct StDetatchObject
struct StEndEffectorRotate
struct StExecuteLastTrajectory
struct StMoveCartesianRelative
struct StMoveCartesianRelative2
struct StMoveEndEffector
struct StMoveJoints
struct StMoveKnownState
struct StMoveLastTrajectoryInitialState
struct StMoveNamedTarget
struct StPouringMotion
struct StUndoLastTrajectory
Functions
def construct_angle_radians (loader, node)
def construct_angle_degrees (loader, node)
def load_yaml (package_name, file_path)
def load_yaml_abs (absolute_file_path)
def launch_setup (context, *args, **kwargs)
def generate_launch_description ()
Function Documentation
construct_angle_degrees()
def sm_test_moveit_ur5_sim.construct_angle_degrees (loader, node)
utility function for converting degrees into radians from yaml.
Definition at line 40 of file sm_test_moveit_ur5_sim.launch.py.
 def construct_angle_degrees(loader, node):
     """utility function for converting degrees into radians from yaml."""
     return math.radians(construct_angle_radians(loader, node))
References construct_angle_radians().
construct_angle_radians()
def sm_test_moveit_ur5_sim.construct_angle_radians (loader, node)
utility function to construct radian values from yaml.
Definition at line 31 of file sm_test_moveit_ur5_sim.launch.py.
 def construct_angle_radians(loader, node):
     """utility function to construct radian values from yaml."""
     value = loader.construct_scalar(node)
     try:
         return float(value)
     except SyntaxError:
         raise Exception("invalid expression: %s" % value)
Referenced by construct_angle_degrees().
generate_launch_description()
def sm_test_moveit_ur5_sim.generate_launch_description ()
Definition at line 284 of file sm_test_moveit_ur5_sim.launch.py.
 def generate_launch_description():
     # Initialize Arguments
     declared_arguments = []
     declared_arguments.append(
         DeclareLaunchArgument(
             "robot_ip", description="The IP address at which the robot is reachable."
         )
     )
     # UR specific arguments
     declared_arguments.append(
         DeclareLaunchArgument(
             "ur_type",
             description="Type/series of used UR robot.",
             default_value="ur5e",
             choices=["ur3", "ur3e", "ur5", "ur5e", "ur10", "ur10e", "ur16e"],
         )
     )
     declared_arguments.append(
         DeclareLaunchArgument(
             "moveit_config_package",
             default_value="ur_moveit_config",
             description="MoveIt config package with robot SRDF/XACRO files. Usually the argument \
     is not set, it enables use of a custom moveit config.",
         )
     )
     # TODO(anyone): enable this when added into ROS2-foxy
     # choices=['ur3', 'ur3e', 'ur5', 'ur5e', 'ur10', 'ur10e', 'ur16e']))
     declared_arguments.append(
         DeclareLaunchArgument(
             "safety_limits",
             default_value="true",
             description="Enables the safety limits controller if true.",
         )
     )
     declared_arguments.append(
         DeclareLaunchArgument(
             "safety_pos_margin",
             default_value="0.15",
             description="The margin to lower and upper limits in the safety controller.",
         )
     )
     declared_arguments.append(
         DeclareLaunchArgument(
             "safety_k_position",
             default_value="20",
             description="k-position factor in the safety controller.",
         )
     )
     # General arguments
     # General arguments
     declared_arguments.append(
         DeclareLaunchArgument(
             "description_package",
             default_value="ur_description",
             description="Description package with robot URDF/XACRO files. Usually the argument \
         is not set, it enables use of a custom description.",
         )
     )
     declared_arguments.append(
         DeclareLaunchArgument(
             "description_file",
             default_value="ur.urdf.xacro",
             description="URDF/XACRO description file with the robot.",
         )
     )
     declared_arguments.append(
         DeclareLaunchArgument(
             "moveit_config_package",
             default_value="ur_moveit_config",
             description="MoveIt config package with robot SRDF/XACRO files. Usually the argument \
         is not set, it enables use of a custom moveit config.",
         )
     )
     declared_arguments.append(
         DeclareLaunchArgument(
             "moveit_config_file",
             default_value="ur.srdf.xacro",
             description="MoveIt SRDF/XACRO description file with the robot.",
         )
     )
     declared_arguments.append(
         DeclareLaunchArgument(
             "prefix",
             default_value='""',
             description="Prefix of the joint names, useful for \
         multi-robot setup. If changed than also joint names in the controllers' configuration \
         have to be updated.",
         )
     )
     declared_arguments.append(
         DeclareLaunchArgument(
             "fake_sensor_commands",
             default_value="false",
             description="Enable fake command interfaces for sensors used for simple simulations. \
             Used only if 'use_fake_hardware' parameter is true.",
         )
     )
     return LaunchDescription(declared_arguments + [OpaqueFunction(function=launch_setup)])
launch_setup()
def sm_test_moveit_ur5_sim.launch_setup (context, * args, ** kwargs)
Definition at line 77 of file sm_test_moveit_ur5_sim.launch.py.
 def launch_setup(context, *args, **kwargs):
     # evaluate arguments
     ur_type = LaunchConfiguration("ur_type")
     robot_ip = LaunchConfiguration("robot_ip")
     safety_limits = LaunchConfiguration("safety_limits")
     safety_pos_margin = LaunchConfiguration("safety_pos_margin")
     safety_k_position = LaunchConfiguration("safety_k_position")
     # General arguments
     description_package = LaunchConfiguration("description_package")
     description_file = LaunchConfiguration("description_file")
     moveit_config_package = LaunchConfiguration("moveit_config_package")
     moveit_config_file = LaunchConfiguration("moveit_config_file")
     prefix = LaunchConfiguration("prefix")
     use_fake_hardware = LaunchConfiguration("use_fake_hardware")
     fake_sensor_commands = LaunchConfiguration("fake_sensor_commands")
     launch_rviz = LaunchConfiguration("launch_rviz")
     joint_limit_params = PathJoinSubstitution(
         [FindPackageShare(description_package), "config", ur_type, "joint_limits.yaml"]
     )
     kinematics_params = PathJoinSubstitution(
         [FindPackageShare(description_package), "config", ur_type, "default_kinematics.yaml"]
     )
     physical_params = PathJoinSubstitution(
         [FindPackageShare(description_package), "config", ur_type, "physical_parameters.yaml"]
     )
     visual_params = PathJoinSubstitution(
         [FindPackageShare(description_package), "config", ur_type, "visual_parameters.yaml"]
     )
     script_filename = PathJoinSubstitution(
         [FindPackageShare("ur_robot_driver"), "resources", "ros_control.urscript"]
     )
     input_recipe_filename = PathJoinSubstitution(
         [FindPackageShare("ur_robot_driver"), "resources", "rtde_input_recipe.txt"]
     )
     output_recipe_filename = PathJoinSubstitution(
         [FindPackageShare("ur_robot_driver"), "resources", "rtde_output_recipe.txt"]
     )
     robot_description_content = Command(
         [
             PathJoinSubstitution([FindExecutable(name="xacro")]),
             " ",
             PathJoinSubstitution(
                 [FindPackageShare(description_package), "urdf", description_file]
             ),
             " ",
             "robot_ip:=",
             robot_ip,
             " ",
             "joint_limit_params:=",
             joint_limit_params,
             " ",
             "kinematics_params:=",
             kinematics_params,
             " ",
             "physical_params:=",
             physical_params,
             " ",
             "visual_params:=",
             visual_params,
             " ",
             "safety_limits:=",
             safety_limits,
             " ",
             "safety_pos_margin:=",
             safety_pos_margin,
             " ",
             "safety_k_position:=",
             safety_k_position,
             " ",
             "name:=",
             # Also ur_type parameter could be used but then the planning group names in yaml
             # configs has to be updated!
             "ur",
             " ",
             "script_filename:=",
             script_filename,
             " ",
             "input_recipe_filename:=",
             input_recipe_filename,
             " ",
             "output_recipe_filename:=",
             output_recipe_filename,
             " ",
             "prefix:=",
             prefix,
             " ",
             "use_fake_hardware:=",
             use_fake_hardware,
             " ",
             "fake_sensor_commands:=",
             fake_sensor_commands,
             " ",
         ]
     )
     robot_description = {"robot_description": robot_description_content}
     # MoveIt Configuration
     robot_description_semantic_content = Command(
         [
             PathJoinSubstitution([FindExecutable(name="xacro")]),
             " ",
             PathJoinSubstitution(
                 [FindPackageShare(moveit_config_package), "srdf", moveit_config_file]
             ),
             " ",
             "name:=",
             # Also ur_type parameter could be used but then the planning group names in yaml
             # configs has to be updated!
             "ur",
             " ",
             "prefix:=",
             prefix,
             " ",
         ]
     )
     robot_description_semantic = {"robot_description_semantic": robot_description_semantic_content}
     kinematics_yaml = load_yaml("ur_moveit_config", "config/kinematics.yaml")
     robot_description_kinematics = {"robot_description_kinematics": kinematics_yaml}
     sm_test_moveit_ur5_sim_node = Node(
         package="sm_test_moveit_ur5_sim",
         executable="sm_test_moveit_ur5_sim_node",
         prefix="xterm -xrm 'XTerm*scrollBar:  true' -xrm 'xterm*rightScrollBar: true' -hold -sl 10000 -geometry 1000x600 -e",
         parameters=[
             robot_description,
             robot_description_semantic,
             robot_description_kinematics,
             os.path.join(
                 get_package_share_directory("sm_test_moveit_ur5_sim"),
                 "config/sm_test_moveit_ur5_sim_config.yaml",
             ),
         ],
         arguments=["--log-level", "smacc2:=DEBUG"],
     )
     ur5_control_launch_file = os.path.join(
         get_package_share_directory("ur_bringup"), "launch", "ur_control.launch.py"
     )
     ur5_control_include = IncludeLaunchDescription(
         PythonLaunchDescriptionSource(ur5_control_launch_file),
         launch_arguments={
             "ur_type": ur_type,
             "robot_ip": "yyy.yyy.yyy.yyy",
             "robot_controller": "scaled_joint_trajectory_controller",
             "use_fake_hardware": "true",
             "launch_rviz": "false",
         }.items(),
     )
     ur5_moveit_launch_file = os.path.join(
         get_package_share_directory("ur_bringup"), "launch", "ur_moveit.launch.py"
     )
     ur5_moveit_include = IncludeLaunchDescription(
         PythonLaunchDescriptionSource(ur5_moveit_launch_file),
         launch_arguments={
             "ur_type": "ur5e",
             "robot_ip": "yyy.yyy.yyy.yyy",
             "launch_rviz": "true",
         }.items(),
     )
     # Planning Configuration
     ompl_planning_pipeline_config = {
         "move_group": {
             "planning_plugin": "ompl_interface/OMPLPlanner",
             "request_adapters": """default_planner_request_adapters/AddTimeOptimalParameterization default_planner_request_adapters/FixWorkspaceBounds default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/FixStartStatePathConstraints""",
             "start_state_max_bounds_error": 0.1,
         }
     }
     ompl_planning_yaml = load_yaml("ur_moveit_config", "config/ompl_planning.yaml")
     ompl_planning_pipeline_config["move_group"].update(ompl_planning_yaml)
     robot_description_planning = {
         "robot_description_planning": load_yaml_abs(str(joint_limit_params.perform(context)))
     }
     # rviz with moveit configuration
     rviz_config_file = PathJoinSubstitution(
         [FindPackageShare("sm_test_moveit_ur5_sim"), "config", "view_robot.rviz"]
     )
     rviz_node = Node(
         package="rviz2",
         condition=IfCondition(launch_rviz),
         executable="rviz2",
         name="rviz2_moveit",
         output="log",
         arguments=["-d", rviz_config_file],
         parameters=[
             robot_description,
             robot_description_semantic,
             ompl_planning_pipeline_config,
             robot_description_kinematics,
             robot_description_planning,
         ],
     )
     nodes_to_start = [sm_test_moveit_ur5_sim_node, rviz_node]
     include_files = [ur5_control_include, ur5_moveit_include]
     return nodes_to_start + include_files
References load_yaml(), and load_yaml_abs().
load_yaml()
def sm_test_moveit_ur5_sim.load_yaml (package_name, file_path)
Definition at line 45 of file sm_test_moveit_ur5_sim.launch.py.
 def load_yaml(package_name, file_path):
     package_path = get_package_share_directory(package_name)
     absolute_file_path = os.path.join(package_path, file_path)
     try:
         yaml.SafeLoader.add_constructor("!radians", construct_angle_radians)
         yaml.SafeLoader.add_constructor("!degrees", construct_angle_degrees)
     except Exception:
         raise Exception("yaml support not available; install python-yaml")
     try:
         with open(absolute_file_path) as file:
             return yaml.safe_load(file)
     except OSError:  # parent of IOError, OSError *and* WindowsError where available
         return None
Referenced by launch_setup().
load_yaml_abs()
def sm_test_moveit_ur5_sim.load_yaml_abs (absolute_file_path)
Definition at line 62 of file sm_test_moveit_ur5_sim.launch.py.
 def load_yaml_abs(absolute_file_path):
     try:
         yaml.SafeLoader.add_constructor("!radians", construct_angle_radians)
         yaml.SafeLoader.add_constructor("!degrees", construct_angle_degrees)
     except Exception:
         raise Exception("yaml support not available; install python-yaml")
     try:
         with open(absolute_file_path) as file:
             return yaml.safe_load(file)
     except OSError:  # parent of IOError, OSError *and* WindowsError where available
         return None
Referenced by launch_setup().