SMACC2: sm_aws_warehouse_navigation::StAcquireSensors Struct Reference
sm_aws_warehouse_navigation::StAcquireSensors Struct Reference
#include <st_acquire_sensors.hpp>
Public Types
typedef mpl::list< Transition< EvCbSuccess< CbWaitPose, OrNavigation >, StInitialNavigateForward, SUCCESS > > reactions
Public Types inherited from smacc2::SmaccState< StAcquireSensors, SmAwsWarehouseNavigation >
typedef SmAwsWarehouseNavigation TContext
typedef Context::inner_context_type context_type
typedef context_type::state_iterator state_iterator
typedef mpl::list<> LastDeepState
typedef base_type::outermost_context_base_type outermost_context_base_type
typedef base_type::inner_context_ptr_type inner_context_ptr_type
typedef base_type::context_ptr_type context_ptr_type
typedef base_type::inner_initial_list inner_initial_list
Public Member Functions
void runtimeConfigure ()
void onEntry ()
void update ()
void sendInitialPoseEstimation ()
void onExit ()
Public Member Functions inherited from smacc2::SmaccState< StAcquireSensors, SmAwsWarehouseNavigation >
SmaccState ()=delete
SmaccState (my_context ctx)
virtual ~SmaccState ()
const smacc2::introspection::SmaccStateInfo * getStateInfo ()
std::string getFullName ()
std::string getShortName ()
virtual ISmaccState * getParentState ()
void exit ()
void runtimeConfigure ()
void onEntry ()
void onExit ()
bool getGlobalSMData (std::string name, T &ret)
void setGlobalSMData (std::string name, T value)
void requiresComponent (SmaccComponentType *&storage)
virtual ISmaccStateMachine & getStateMachine ()
void checkWhileLoopConditionAndThrowEvent (bool(MostDerived::*conditionFn)())
void throwSequenceFinishedEvent ()
Public Member Functions inherited from smacc2::ISmaccState
ISmaccState * getParentState ()
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc2::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename T >
bool getParam (std::string param_name, T &param_storage)
template<typename T >
void setParam (std::string param_name, T param_val)
void param (std::string param_name)
template<typename T >
void param (std::string param_name, T default_value)
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Public Member Functions inherited from smacc2::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (rclcpp::Duration duration)
void executeUpdate (rclcpp::Node::SharedPtr node)
void setUpdatePeriod (rclcpp::Duration duration)
Static Public Member Functions
static void staticConfigure ()
Static Public Member Functions inherited from smacc2::SmaccState< StAcquireSensors, SmAwsWarehouseNavigation >
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh, StAcquireSensors &)> initializationFunction)
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh)> initializationFunction)
static void configure_orthogonal (Args &&... args)
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor (TArgs... args)
static std::shared_ptr< smacc2::introspection::EventGeneratorHandler > static_createEventGenerator (TUArgs... args)
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor_aux (TUArgs... args)
static void initial_deep_construct (outermost_context_base_type &outermostContextBase)
static void deep_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
static inner_context_ptr_type shallow_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
Public Attributes
cl_move_base_z::Amcl * amcl_
Public Attributes inherited from smacc2::SmaccState< StAcquireSensors, SmAwsWarehouseNavigation >
bool finishStateThrown
mpl::list<> * smacc_inner_type
Public Attributes inherited from smacc2::ISmaccState
rclcpp::Node::SharedPtr stateNode_
Additional Inherited Members
Protected Attributes inherited from smacc2::ISmaccState
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc2::SmaccEventGenerator > > eventGenerators_
rclcpp::Node::SharedPtr contextNh
ISmaccState * parentState_
const smacc2::introspection::SmaccStateInfo * stateInfo_
Detailed Description
Definition at line 9 of file st_acquire_sensors.hpp.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvCbSuccess<CbWaitPose, OrNavigation>, StInitialNavigateForward, SUCCESS> > sm_aws_warehouse_navigation::StAcquireSensors::reactions
Definition at line 20 of file st_acquire_sensors.hpp.
Member Function Documentation
onEntry()
void sm_aws_warehouse_navigation::StAcquireSensors::onEntry () inline
Definition at line 40 of file st_acquire_sensors.hpp.
   {
     //rclcpp::sleep_for(10s);
     // this->setUpdatePeriod(rclcpp::Duration(1s));
     sendInitialPoseEstimation();
   }
onExit()
void sm_aws_warehouse_navigation::StAcquireSensors::onExit () inline
Definition at line 83 of file st_acquire_sensors.hpp.
 {}
runtimeConfigure()
void sm_aws_warehouse_navigation::StAcquireSensors::runtimeConfigure () inline
Definition at line 31 of file st_acquire_sensors.hpp.
   {
     ClMoveBaseZ * navClient;
     getOrthogonal<OrNavigation>()->requiresClient(navClient);
     amcl_ = navClient->getComponent<Amcl>();
   }
References smacc2::ISmaccClient::getComponent(), and smacc2::ISmaccClient::requiresClient().
sendInitialPoseEstimation()
void sm_aws_warehouse_navigation::StAcquireSensors::sendInitialPoseEstimation () inline
Definition at line 54 of file st_acquire_sensors.hpp.
   {
     geometry_msgs::msg::PoseWithCovarianceStamped initialposemsg;
     bool useSimTime = getNode()->get_parameter("use_sim_time").as_bool();
     //getNode()->set_parameter("use_sim_time",true);
     initialposemsg.header.stamp = getNode()->now();
     initialposemsg.header.frame_id = "map";
     initialposemsg.pose.pose.position.x = 3.415412425994873;
     initialposemsg.pose.pose.position.y = 2.0;
     initialposemsg.pose.pose.position.z = 0;
     initialposemsg.pose.pose.orientation.x = 0;
     initialposemsg.pose.pose.orientation.y = 0;
     initialposemsg.pose.pose.orientation.z = 1;
     initialposemsg.pose.pose.orientation.w = 0;
     //z: 0.9999985465626609
     // w: 0.00170495529732811
     initialposemsg.pose.covariance = {
       0.25, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.25, 0.0, 0.0, 0.0, 0.0,
       0.0,  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  0.0, 0.0, 0.0, 0.0,
       0.0,  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,  0.0, 0.0, 0.0, 0.06853891909122467};
     amcl_->setInitialPose(initialposemsg);
   }
References cl_move_base_z::Amcl::setInitialPose().
staticConfigure()
static void sm_aws_warehouse_navigation::StAcquireSensors::staticConfigure () inline static
Definition at line 25 of file st_acquire_sensors.hpp.
   {
     configure_orthogonal<OrNavigation, CbWaitPose>();
     configure_orthogonal<OrNavigation, CbWaitActionServer>(std::chrono::milliseconds(10000));
   }
update()
void sm_aws_warehouse_navigation::StAcquireSensors::update () inline virtual
Implements smacc2::ISmaccUpdatable.
Definition at line 47 of file st_acquire_sensors.hpp.
   {
     // insist publishing the initial state estimation until amcl responds with a correct global pose estimation
   }
Member Data Documentation
amcl_
cl_move_base_z::Amcl* sm_aws_warehouse_navigation::StAcquireSensors::amcl_
Definition at line 22 of file st_acquire_sensors.hpp.
The documentation for this struct was generated from the following file:
smacc2_sm_reference_library/sm_aws_warehouse_navigation/include/sm_aws_warehouse_navigation/states/st_acquire_sensors.hpp