SMACC2: sm_dance_bot_warehouse::SS2::SsRadialPattern2 Struct Reference
sm_dance_bot_warehouse::SS2::SsRadialPattern2 Struct Reference
#include <ss_radial_pattern_2.hpp>
Public Types
typedef mpl::list< Transition< EvLoopEnd< StiRadialLoopStart >, StNavigateToWaypointsX, ENDLOOP > > reactions
Public Types inherited from smacc2::SmaccState< SsRadialPattern2, MsDanceBotRunMode, StiRadialLoopStart >
typedef MsDanceBotRunMode TContext
typedef Context::inner_context_type context_type
typedef context_type::state_iterator state_iterator
typedef StiRadialLoopStart LastDeepState
typedef base_type::outermost_context_base_type outermost_context_base_type
typedef base_type::inner_context_ptr_type inner_context_ptr_type
typedef base_type::context_ptr_type context_ptr_type
typedef base_type::inner_initial_list inner_initial_list
Public Member Functions
void runtimeConfigure ()
void onExit ()
Public Member Functions inherited from smacc2::SmaccState< SsRadialPattern2, MsDanceBotRunMode, StiRadialLoopStart >
SmaccState ()=delete
SmaccState (my_context ctx)
virtual ~SmaccState ()
const smacc2::introspection::SmaccStateInfo * getStateInfo ()
std::string getName () override
std::string getFullName ()
std::string getShortName ()
virtual ISmaccState * getParentState ()
void exit ()
void runtimeConfigure ()
void onEntry ()
void onExit ()
bool getGlobalSMData (std::string name, T &ret)
void setGlobalSMData (std::string name, T value)
void requiresComponent (SmaccComponentType *&storage)
virtual ISmaccStateMachine & getStateMachine ()
void checkWhileLoopConditionAndThrowEvent (bool(MostDerived::*conditionFn)())
void throwSequenceFinishedEvent ()
Public Member Functions inherited from smacc2::ISmaccState
virtual ISmaccStateMachine & getStateMachine ()=0
virtual std::string getName ()=0
ISmaccState * getParentState ()
rclcpp::Node::SharedPtr & getNode ()
rclcpp::Logger getLogger ()
virtual std::string getClassName ()
template<typename TOrthogonal , typename TBehavior , typename... Args>
std::shared_ptr< TBehavior > configure (Args &&... args)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage)
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename T >
bool getGlobalSMData (std::string name, T &ret)
template<typename T >
void setGlobalSMData (std::string name, T value)
template<typename TStateReactor , typename TTriggerEvent , typename TEventList , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TStateReactor , typename... TEvArgs>
std::shared_ptr< TStateReactor > createStateReactor (TEvArgs... args)
template<typename TEventGenerator , typename... TEvArgs>
std::shared_ptr< TEventGenerator > createEventGenerator (TEvArgs... args)
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TransitionType >
void notifyTransition ()
void notifyTransitionFromTransitionTypeInfo (std::shared_ptr< smacc2::introspection::TypeInfo > &transitionTypeInfo)
std::vector< std::shared_ptr< StateReactor > > & getStateReactors ()
std::vector< std::shared_ptr< SmaccEventGenerator > > & getEventGenerators ()
template<typename TOrthogonal >
TOrthogonal * getOrthogonal ()
template<typename TEventGenerator >
TEventGenerator * getEventGenerator ()
template<typename TStateReactor >
TStateReactor * getStateReactor ()
Static Public Member Functions
static void staticConfigure ()
static constexpr int total_iterations ()
static constexpr float ray_angle_increment_degree ()
static constexpr float ray_length_meters ()
Static Public Member Functions inherited from smacc2::SmaccState< SsRadialPattern2, MsDanceBotRunMode, StiRadialLoopStart >
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh, SsRadialPattern2 &)> initializationFunction)
static void configure_orthogonal_runtime (std::function< void(TBehavior &bh)> initializationFunction)
static void configure_orthogonal (Args &&... args)
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor (TArgs... args)
static std::shared_ptr< smacc2::introspection::EventGeneratorHandler > static_createEventGenerator (TUArgs... args)
static std::shared_ptr< smacc2::introspection::StateReactorHandler > static_createStateReactor_aux (TUArgs... args)
static void initial_deep_construct (outermost_context_base_type &outermostContextBase)
static void deep_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
static inner_context_ptr_type shallow_construct (const context_ptr_type &pContext, outermost_context_base_type &outermostContextBase)
Public Attributes
int iteration_count = 0
Public Attributes inherited from smacc2::SmaccState< SsRadialPattern2, MsDanceBotRunMode, StiRadialLoopStart >
bool finishStateThrown
StiRadialLoopStart * smacc_inner_type
Additional Inherited Members
Protected Attributes inherited from smacc2::ISmaccState
rclcpp::Node::SharedPtr node_
std::shared_ptr< rclcpp::Logger > logger_
std::vector< std::shared_ptr< StateReactor > > stateReactors_
std::vector< std::shared_ptr< smacc2::SmaccEventGenerator > > eventGenerators_
ISmaccState * parentState_
const smacc2::introspection::SmaccStateInfo * stateInfo_
Detailed Description
Definition at line 41 of file ss_radial_pattern_2.hpp.
Member Typedef Documentation
reactions
typedef mpl::list< Transition<EvLoopEnd<StiRadialLoopStart>, StNavigateToWaypointsX, ENDLOOP> > sm_dance_bot_warehouse::SS2::SsRadialPattern2::reactions
Definition at line 52 of file ss_radial_pattern_2.hpp.
Member Function Documentation
onExit()
void sm_dance_bot_warehouse::SS2::SsRadialPattern2::onExit () inline
Definition at line 67 of file ss_radial_pattern_2.hpp.
  {
    rclcpp::sleep_for(5s);
    RCLCPP_INFO(getLogger(), "[SsRadialPattern1] waiting 5 seconds");
  }
References smacc2::ISmaccState::getLogger(), and service_node_3::s.
ray_angle_increment_degree()
static constexpr float sm_dance_bot_warehouse::SS2::SsRadialPattern2::ray_angle_increment_degree () inline static constexpr
Definition at line 64 of file ss_radial_pattern_2.hpp.
{ return 360.0 / total_iterations(); }
References total_iterations().
ray_length_meters()
static constexpr float sm_dance_bot_warehouse::SS2::SsRadialPattern2::ray_length_meters () inline static constexpr
Definition at line 65 of file ss_radial_pattern_2.hpp.
{ return 5; }
runtimeConfigure()
void sm_dance_bot_warehouse::SS2::SsRadialPattern2::runtimeConfigure () inline
Definition at line 60 of file ss_radial_pattern_2.hpp.
{}
staticConfigure()
static void sm_dance_bot_warehouse::SS2::SsRadialPattern2::staticConfigure () inline static
Definition at line 55 of file ss_radial_pattern_2.hpp.
  {
    //configure_orthogonal<OrObstaclePerception, CbLidarSensor>();
  }
total_iterations()
static constexpr int sm_dance_bot_warehouse::SS2::SsRadialPattern2::total_iterations () inline static constexpr
Definition at line 63 of file ss_radial_pattern_2.hpp.
{ return 35; }
Referenced by ray_angle_increment_degree().
Member Data Documentation
iteration_count
int sm_dance_bot_warehouse::SS2::SsRadialPattern2::iteration_count = 0
Definition at line 62 of file ss_radial_pattern_2.hpp.
The documentation for this struct was generated from the following file:
smacc2_sm_reference_library/sm_dance_bot_warehouse/include/sm_dance_bot_warehouse/superstates/ss_radial_pattern_2.hpp