SMACC2: cl_move_group_interface::CbUndoLastTrajectory Class Reference
cl_move_group_interface::CbUndoLastTrajectory Class Reference
#include <cb_undo_last_trajectory.hpp>
Public Member Functions
CbUndoLastTrajectory ()
CbUndoLastTrajectory (int backIndex)
virtual ~CbUndoLastTrajectory ()
virtual void onEntry () override
virtual void generateTrajectory ()
Public Member Functions inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
CbMoveEndEffectorTrajectory (std::optional< std::string > tipLink=std::nullopt)
CbMoveEndEffectorTrajectory (const std::vector< geometry_msgs::msg::PoseStamped > &endEffectorTrajectory, std::optional< std::string > tipLink=std::nullopt)
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual void onEntry () override
virtual void onExit () override
virtual void update () override
Public Member Functions inherited from smacc2::SmaccAsyncClientBehavior
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
virtual ~SmaccAsyncClientBehavior ()
template<typename TCallback , typename T >
boost::signals2::connection onSuccess (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFinished (TCallback callback, T *object)
template<typename TCallback , typename T >
boost::signals2::connection onFailure (TCallback callback, T *object)
void requestForceFinish ()
void executeOnEntry () override
void executeOnExit () override
void waitOnEntryThread (bool requestFinish)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onSuccess (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFinished (TCallbackMethod callback, T *object)
template<typename TCallbackMethod , typename T >
boost::signals2::connection onFailure (TCallbackMethod callback, T *object)
Public Member Functions inherited from smacc2::ISmaccClientBehavior
ISmaccClientBehavior ()
virtual ~ISmaccClientBehavior ()
ISmaccStateMachine * getStateMachine ()
std::string getName () const
template<typename SmaccClientType >
void requiresClient (SmaccClientType *&storage)
template<typename SmaccComponentType >
void requiresComponent (SmaccComponentType *&storage, bool throwExceptionIfNotExist=false)
virtual void onEntry ()
virtual void onExit ()
virtual void executeOnEntry ()
virtual void executeOnExit ()
Public Member Functions inherited from smacc2::ISmaccUpdatable
ISmaccUpdatable ()
ISmaccUpdatable (rclcpp::Duration duration)
void executeUpdate (rclcpp::Node::SharedPtr node)
void setUpdatePeriod (rclcpp::Duration duration)
Private Attributes
int backIndex_ = -1
moveit_msgs::msg::RobotTrajectory trajectory
moveit_msgs::msg::RobotTrajectory reversed
Additional Inherited Members
Public Attributes inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
std::optional< std::string > group_
std::optional< std::string > tipLink_
std::optional< bool > allowInitialTrajectoryStateJointDiscontinuity_
Protected Member Functions inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
ComputeJointTrajectoryErrorCode computeJointSpaceTrajectory (moveit_msgs::msg::RobotTrajectory &computedJointTrajectory)
void executeJointSpaceTrajectory (const moveit_msgs::msg::RobotTrajectory &computedJointTrajectory)
virtual void generateTrajectory ()=0
virtual void createMarkers ()
void getCurrentEndEffectorPose (std::string globalFrame, tf2::Stamped< tf2::Transform > &currentEndEffectorTransform)
Protected Member Functions inherited from smacc2::SmaccAsyncClientBehavior
void postSuccessEvent ()
void postFailureEvent ()
virtual void dispose () override
bool isShutdownRequested ()
onEntry is executed in a new thread. However the current state cannot be left until the onEntry thread finishes. This flag can be checked from the onEntry thread to force finishing the thread.
Protected Member Functions inherited from smacc2::ISmaccClientBehavior
virtual void runtimeConfigure ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
ISmaccState * getCurrentState ()
virtual void dispose ()
virtual rclcpp::Node::SharedPtr getNode () const
virtual rclcpp::Logger getLogger () const
virtual void update ()=0
Protected Attributes inherited from cl_move_group_interface::CbMoveEndEffectorTrajectory
std::vector< geometry_msgs::msg::PoseStamped > endEffectorTrajectory_
ClMoveGroup * movegroupClient_ = nullptr
visualization_msgs::msg::MarkerArray beahiorMarkers_
Detailed Description
Definition at line 28 of file cb_undo_last_trajectory.hpp.
Constructor & Destructor Documentation
CbUndoLastTrajectory() [1/2]
cl_move_group_interface::CbUndoLastTrajectory::CbUndoLastTrajectory ()
Definition at line 26 of file cb_undo_last_trajectory.cpp.
{}
CbUndoLastTrajectory() [2/2]
cl_move_group_interface::CbUndoLastTrajectory::CbUndoLastTrajectory (int backIndex)
Definition at line 28 of file cb_undo_last_trajectory.cpp.
: backIndex_(backIndex) {}
~CbUndoLastTrajectory()
cl_move_group_interface::CbUndoLastTrajectory::~CbUndoLastTrajectory () virtual
Definition at line 30 of file cb_undo_last_trajectory.cpp.
{}
Member Function Documentation
generateTrajectory()
void cl_move_group_interface::CbUndoLastTrajectory::generateTrajectory () virtual
Implements cl_move_group_interface::CbMoveEndEffectorTrajectory.
Definition at line 32 of file cb_undo_last_trajectory.cpp.
{}
onEntry()
void cl_move_group_interface::CbUndoLastTrajectory::onEntry () override virtual
Reimplemented from cl_move_group_interface::CbMoveEndEffectorTrajectory.
Definition at line 34 of file cb_undo_last_trajectory.cpp.
{
  CpTrajectoryHistory * trajectoryHistory;
  this->requiresComponent(trajectoryHistory);
  this->requiresClient(movegroupClient_);
  if (trajectoryHistory->getLastTrajectory(backIndex_, trajectory))
  {
    RCLCPP_WARN_STREAM(
      getLogger(), "[" << getName() << "] reversing last trajectory [" << backIndex_ << "]");
    auto initialTime = trajectory.joint_trajectory.points.back().time_from_start;
    reversed = trajectory;
    std::reverse(reversed.joint_trajectory.points.begin(), reversed.joint_trajectory.points.end());
    for (auto & jp : reversed.joint_trajectory.points)
    {
      jp.time_from_start = rclcpp::Duration(initialTime) - rclcpp::Duration(jp.time_from_start);
    }
    this->executeJointSpaceTrajectory(reversed);
  }
  else
  {
    RCLCPP_WARN_STREAM(
      getLogger(), "[" << getName() << "] could not undo last trajectory, trajectory not found.");
  }
}
References backIndex_, cl_move_group_interface::CbMoveEndEffectorTrajectory::executeJointSpaceTrajectory(), cl_move_group_interface::CpTrajectoryHistory::getLastTrajectory(), smacc2::ISmaccClientBehavior::getLogger(), smacc2::ISmaccClientBehavior::getName(), cl_move_group_interface::CbMoveEndEffectorTrajectory::movegroupClient_, smacc2::ISmaccClientBehavior::requiresClient(), smacc2::ISmaccClientBehavior::requiresComponent(), reversed, and trajectory.
Member Data Documentation
backIndex_
int cl_move_group_interface::CbUndoLastTrajectory::backIndex_ = -1 private
Definition at line 42 of file cb_undo_last_trajectory.hpp.
Referenced by onEntry().
reversed
moveit_msgs::msg::RobotTrajectory cl_move_group_interface::CbUndoLastTrajectory::reversed private
Definition at line 45 of file cb_undo_last_trajectory.hpp.
Referenced by onEntry().
trajectory
moveit_msgs::msg::RobotTrajectory cl_move_group_interface::CbUndoLastTrajectory::trajectory private
Definition at line 44 of file cb_undo_last_trajectory.hpp.
Referenced by onEntry().
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/client_behaviors/cb_undo_last_trajectory.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/client_behaviors/cb_undo_last_trajectory.cpp