SMACC2: cl_move_group_interface::CpTrajectoryHistory Class Reference
cl_move_group_interface::CpTrajectoryHistory Class Reference
#include <cp_trajectory_history.hpp>
Public Member Functions
bool getLastTrajectory (int backIndex, moveit_msgs::msg::RobotTrajectory &trajectory)
bool getLastTrajectory (moveit_msgs::msg::RobotTrajectory &trajectory)
void pushTrajectory (std::string name, const moveit_msgs::msg::RobotTrajectory &trajectory, moveit_msgs::msg::MoveItErrorCodes result)
Public Member Functions inherited from smacc2::ISmaccComponent
ISmaccComponent ()
virtual ~ISmaccComponent ()
virtual std::string getName () const
Private Attributes
std::vector< TrajectoryHistoryEntry > trajectoryHistory_
Additional Inherited Members
Protected Member Functions inherited from smacc2::ISmaccComponent
virtual void onInitialize ()
template<typename EventType >
void postEvent (const EventType &ev)
template<typename EventType >
void postEvent ()
template<typename TOrthogonal , typename TSourceObject >
void onOrthogonalAllocation ()
template<typename TComponent >
void requiresComponent (TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TComponent >
void requiresComponent (std::string name, TComponent *&requiredComponentStorage, bool throwExceptionIfNotExist=false)
template<typename TClient >
void requiresClient (TClient *&requiredClientStorage)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingComponent (TArgs... targs)
template<typename SmaccComponentType , typename TOrthogonal , typename TClient , typename... TArgs>
SmaccComponentType * createSiblingNamedComponent (std::string name, TArgs... targs)
rclcpp::Node::SharedPtr getNode ()
rclcpp::Logger getLogger ()
ISmaccStateMachine * getStateMachine ()
Protected Attributes inherited from smacc2::ISmaccComponent
ISmaccStateMachine * stateMachine_
ISmaccClient * owner_
Detailed Description
Definition at line 37 of file cp_trajectory_history.hpp.
Member Function Documentation
getLastTrajectory() [1/2]
bool cl_move_group_interface::CpTrajectoryHistory::getLastTrajectory (int backIndex, moveit_msgs::msg::RobotTrajectory & trajectory)
Definition at line 25 of file cp_trajectory_history.cpp.
{
  if (trajectoryHistory_.size() == 0)
  {
    RCLCPP_WARN_STREAM(
      getLogger(), "[" << getName() << "] requested index: " << backIndex
                       << ", history size: " << trajectoryHistory_.size());
    return false;
  }
  if (backIndex < 0)
  {
    backIndex = 0;
  }
  else if ((size_t)backIndex >= this->trajectoryHistory_.size())
  {
    RCLCPP_WARN_STREAM(
      getLogger(), "[" << getName() << "] requested index: " << backIndex
                       << ", history size: " << trajectoryHistory_.size());
    return false;
  }
  trajectory = this->trajectoryHistory_[this->trajectoryHistory_.size() - 1 - backIndex].trajectory;
  return true;
}
References smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getName(), and trajectoryHistory_.
Referenced by getLastTrajectory(), cl_move_group_interface::CbExecuteLastTrajectory::onEntry(), cl_move_group_interface::CbMoveLastTrajectoryInitialState::onEntry(), and cl_move_group_interface::CbUndoLastTrajectory::onEntry().
getLastTrajectory() [2/2]
bool cl_move_group_interface::CpTrajectoryHistory::getLastTrajectory (moveit_msgs::msg::RobotTrajectory & trajectory)
Definition at line 53 of file cp_trajectory_history.cpp.
{
  return getLastTrajectory(-1, trajectory);
}
References getLastTrajectory().
pushTrajectory()
void cl_move_group_interface::CpTrajectoryHistory::pushTrajectory (std::string name, const moveit_msgs::msg::RobotTrajectory & trajectory, moveit_msgs::msg::MoveItErrorCodes result)
Definition at line 58 of file cp_trajectory_history.cpp.
{
  RCLCPP_INFO_STREAM(
    getLogger(), "[" << getName() << "] adding a new trajectory to the history ( "
                     << trajectory.joint_trajectory.points.size() << " poses)");
  TrajectoryHistoryEntry entry;
  this->trajectoryHistory_.push_back(entry);
  auto & last = this->trajectoryHistory_.back();
  last.trajectory = trajectory;
  last.result = result;
  last.name = name;
}
References smacc2::ISmaccComponent::getLogger(), smacc2::ISmaccComponent::getName(), and trajectoryHistory_.
Referenced by cl_move_group_interface::CbMoveEndEffectorTrajectory::onEntry().
Member Data Documentation
trajectoryHistory_
std::vector<TrajectoryHistoryEntry> cl_move_group_interface::CpTrajectoryHistory::trajectoryHistory_ private
Definition at line 49 of file cp_trajectory_history.hpp.
Referenced by getLastTrajectory(), and pushTrajectory().
The documentation for this class was generated from the following files:
smacc2_client_library/move_group_interface_client/include/move_group_interface_client/components/cp_trajectory_history.hpp
smacc2_client_library/move_group_interface_client/src/move_group_interface_client/components/cp_trajectory_history.cpp